### ISSUE TITLE
SetFileTime DateTime? not updated in samples

### ISSUE THREAD

**Issue by Dobatymo** [dokan-dev/dokany#10]
I am not experienced in C#, but if I try to compile the dokan_net samples from the latest release 0.7.1 in VS 2013 it doesnt work.
SetFileTime DateTime? change from the last update seems to be one of the problems.

**Comment by Liryna** [comment]
Yes the DateTime declaration has changed 46d7789bf5ceb969e73195785e74cfc2a91a8764.
In Dokan 0.6.0, DateTime was equal to DateTime.MinValue when dokan failed.
Make DateTime nullable give a better detection of dokan failure.

What is your build error ?

**Comment by Maxhy** [comment]
DotNet wrapper changed drastically based on the apaka review. This issue is not valid anymore I believe and C# discussion should continue on https://github.com/dokan-dev/dokan-dotnet
