### ISSUE TITLE
Logically dead code sys/Exception

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokany#100]
Hello @marinkobabic ,

I have a question about DokanExceptionFilter that you have created.
https://github.com/dokan-dev/dokany/blame/master/sys/except.c

The NtStatus is set to EXCEPTION_EXECUTE_HANDLER at the begining of the function and never changed before
```
if (Status == EXCEPTION_EXECUTE_HANDLER ||
        FsRtlIsNtstatusExpected(ExceptionCode)) {
```

it mean that FsRtlIsNtstatusExpected is never reached and the condition always true. Is it normal ?

**Comment by marinkobabic** [comment]
You are right. The initial value should be EXCEPTION_CONTINUE_SEARCH



Von Samsung Mobile gesendet


-------- Ursprüngliche Nachricht --------
Von: Liryna
Datum:30.10.2015 17:01 (GMT+01:00)
An: dokan-dev/dokany
Cc: Babic Marinko
Betreff: [dokany] Logically dead code sys/Exception (#100)


Hello @marinkobabic<https://github.com/marinkobabic> ,

I have a question about DokanExceptionFilter that you have created.
https://github.com/dokan-dev/dokany/blame/master/sys/except.c

The NtStatus is set to EXCEPTION_EXECUTE_HANDLER at the begining of the function and never changed before

if (Status == EXCEPTION_EXECUTE_HANDLER ||
        FsRtlIsNtstatusExpected(ExceptionCode)) {


it mean that FsRtlIsNtstatusExpected is never reached and the condition always true. Is it normal ?

-

**Comment by Liryna** [comment]
Ok great! Thank you :+1:
