### ISSUE TITLE
ERROR_INSUFFICIENT_BUFFER and invalid file handle errors when sharing mirrored drive

### ISSUE THREAD

**Issue by mufunyo** [dokan-dev/dokany#1002]
# Environment
 * Windows version: 21H1 19043.1052
 * Processor architecture: x64 (Zen2)
 * Dokany version: 1.5.0.3000
 * Library type (Dokany/FUSE): Dokany (mirror sample)
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

This issue is similar but not identical to #447. I am sharing Google DriveFS over Windows File Sharing, and resolving oddities with the DriveFS implementation by passing it through Dokany, which among other things fixes permissions so that networked clients can access the share. When accessing files (PNG images in my case) through Explorer and Windows Picture Viewer everything is fine, but when I copy an entire folder full of files, all the resulting files are incomplete. The log file reveals an `ERROR_INSUFFICIENT_BUFFER` error. The system is provisioned with 16GB of RAM and has plenty free.
Another error that pops up frequently in the log is `invalid file handle. Error is 87`.

Files as they appear on the remote share:
![image](https://user-images.githubusercontent.com/2671260/125480451-9284f0c7-fb22-4bb8-a71e-f20fbdad962f.png)

Files as they appear after copying to a local folder:
![image](https://user-images.githubusercontent.com/2671260/125480532-8bfe657b-e8f6-40fd-aeda-8cf0f4e2a138.png)

# Logs
Please attach in separate files: mirror [output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#mirrorfs), library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#get-logs).
In case of BSOD, please attach minidump or dump [analyze output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#crash-report-bsod).

I tried creating a kernel log using DbgView but there were no log entries during the repro process.

Mirror log file: [log.txt](https://github.com/dokan-dev/dokany/files/6810171/log.txt)

**Comment by Liryna** [comment]
Hi @mufunyo ,

Thank you for the feedback.

This error is returned when the internal timeout for the request is reached.
The user filesystem can request more time by using the reset timeout API but unfortunately mirror does not implement it.

Mirror is just a sample of the library. If someone is willing to change the mirror to support, I would be welcome to review the pull request.
