### ISSUE TITLE
Problem with files being in use

### ISSUE THREAD

**Issue by enyar-boop** [dokan-dev/dokany#1004]
# Environment
 * Windows version: Windows 10
 * Processor architecture: x64
 * Dokany version: 1.3+
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

Hello, we've encountered problem trying to update dokany to 1.4.1.1000 (latest version at the moment of update) from 1.1.0.2000. We run through some ranorex testes and it always fail on files copy, some of the files got stuck in use and cannot be released until the app is rebooted. We tried different versions(1.5.0.3000 included) and found out that it hapends on every version older then 1.3.0.1000(inclusive). It's running good up to 1.2.2.1000 version. No change in implementation.

We just want to find out what changes may couse this problems so we can fix it in our implementation, couse we don't realy think that's a dokany problem. We want a hint in what direction we should look too. We use dokan-dotnet for calling, but changing it versions of it didn't change a thing, so we think it something to do with the dokany itself.

**Comment by Liryna** [comment]
Hey!
I am not sure to understand the issue. Are you talking about file in used when update dokan installation files ? Or file in used inside the virtual drive?
Maybe some screenshots or logs would help here to understand the situation.

**Comment by enyar-boop** [comment]
Oh, i'm sorry, i'm talking about files in virtual drive. For example: we copy 1000 files 40kb from actual hard drive to virtual disk and after the copy is done, we can't read some files(1-5 it's random) because some of them are still in use, even after some time.

**Comment by enyar-boop** [comment]
I'm not able to provide logs right now, will get them by the end of the next wekk, just didn't expect the answer so soon.

**Comment by enyar-boop** [comment]
We managed to repeat this with single file and log it.
[singli file copy.LOG](https://github.com/dokan-dev/dokany/files/6938000/singli.file.copy.LOG)

**Comment by enyar-boop** [comment]
> Hey!
> I am not sure to understand the issue. Are you talking about file in used when update dokan installation files ? Or file in used inside the virtual drive?
> Maybe some screenshots or logs would help here to understand the situation.

We are still at the same problem, should we provide some mode info?

**Comment by Liryna** [comment]
@enyar-boop I still do not have time to look into this right now. The logs you sent should be enough. Will let you know when I can get this done.

**Comment by enyar-boop** [comment]
Ok, i understend, thank you for your time, will be waiting.

**Comment by Liryna** [comment]
Hi @enyar-boop ,

Have you been able to get more details / find a solution on this issue ?
