### ISSUE TITLE
DokanCtl.exe sometimes inserts invalid characters into driver path during registration

### ISSUE THREAD

**Issue by Corillian** [dokan-dev/dokany#101]
Sometimes the Dokan driver path is registered as `\??\C:\Windows\system32\drivers\dokan.sys` which is invalid and prevents the service manager from being able to start it. The driver should be registered with the path `%SystemRoot%\system32\drivers\dokan.sys`.

**Comment by Liryna** [comment]
Hi @Corillian,

Do you think GetSystemDirectory is returning a wrong path ?
https://github.com/dokan-dev/dokany/blob/master/dokan_control/dokanctl.c#L145

We should check the return value of GetSystemDirectory but it is still strange that you get `\??\` in front of the path.

**Comment by Liryna** [comment]
Fixed with https://github.com/dokan-dev/dokany/pull/104
Thank again @Corillian for your contribution !
