### ISSUE TITLE
dokanctl - unmount-by-number is advertized in examples, but not actually working.

### ISSUE THREAD

**Issue by the-Arioch** [dokan-dev/dokany#1017]
```
c:\Program Files\Dokan\Dokan Library-1.5.0>dokanctl /?
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
dokanctl /u MountPoint
dokanctl /u M
dokanctl /i [d||n]
dokanctl /r [d||n]
dokanctl /v

Example:
  /u M                : Unmount M: drive
  /u C:\mount\dokan   : Unmount mount point C:\mount\dokan
  /u 1                : Unmount mount point 1
  /i d                : Install driver
  /i n                : Install network provider
  /r d                : Remove driver
  /r n                : Remove network provider
  /l a                : List current mount points
  /d [0-7]            : Enable Kernel Debug output
  /v                  : Print Dokan version
```

The `/u 1` example seems straightforward. It was not actually listed in the "menu" above, but it is so simple and obvious that no one gonna double-check.

And then suddenly:

```
c:\Program Files\Dokan\Dokan Library-1.5.0>dokanctl /l
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
  Mount points: 2
  0# MountPoint: \DosDevices\P: - UNC:  - DeviceName: \Device\Volume{d6cc17c5-17
28-4085-bce7-964f1e9f5de9}
  1# MountPoint: \DosDevices\W: - UNC:  - DeviceName: \Device\Volume{d6cc17c5-17
29-4085-bce7-964f1e9f5de9}
```

First is mirror, second is yafsw. Though should not matter.

```
c:\Program Files\Dokan\Dokan Library-1.5.0>dokanctl /u 0
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
send global release for 0:
DokanError: Ioctl 0x92010 failed with code 122 on Device \\.\Dokan_1
Failed to unmount: 0:
Unmount status = 1

c:\Program Files\Dokan\Dokan Library-1.5.0>dokanctl /u 1
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
send global release for 1:
DokanError: Ioctl 0x92010 failed with code 122 on Device \\.\Dokan_1
Failed to unmount: 1:
Unmount status = 1
```

Ooooops! 
Few hours of "random shaman dances" later....

```
c:\Program Files\Dokan\Dokan Library-1.5.0>dokanctl /u P
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
send global release for P:
Unmount status = 0

c:\Program Files\Dokan\Dokan Library-1.5.0>dokanctl /u W
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
send global release for W:
Unmount status = 0
```

Wooops!
Talk about looking for black cat in black night....

Related: https://github.com/DDoSolitary/yasfw/issues/28

P.S. While i never saw it "in the wild", but there were talks that API-wise WinNT allows all 255 not-null ASCII characters to act as drive letters. And someone got tripped over it, actually making such a drive "letter" and then being unable to do anything with it short of reboot. Then they started discussing using non-Latin letters as drive letters, etc. Just some loose memory here...

However, if that actually IS possible API-wise, then it seems to be ambiguity whether `/u 1` would mean topmost mountpoint, second mountpoitn ("1#") - or a (probably non-existent) drive letter `1:\`

That said, i never saw such a thing in the wild, so perhaps no practical problem in that.

**Comment by Rondom** [comment]
The numbering is not stable. See: https://github.com/dokan-dev/dokany/blob/31f8381e1efc207e7c02bdea0a47c819e9810c3f/dokan_control/dokanctl.c#L213-L214

As long this is not a given, it does not make sense to have this functionality in the first place, because it would be racy. I think support for it should only be restored, if there is a unique identifier for a dokan-volume. When designing, we need to make sure that #136 is taken into consideration.

**Comment by the-Arioch** [comment]
I suspect the numbering is quasi-stable within one cmd.exe session. User is expected to `dokanctl /l` and then immediately shoot down the disks by `dokanctl /u`.

And if to consider different user accounts running `dokanctl` (services, RunAs, UAC elevation) then drive letters would also be unstable (they have different drive letters maps, albeit partially overlapping).

And if time dimension is in then the whole Pandora box is opened: while you are keying in `dokan /u M` someone else might already unmount M: and re-use that drive letter to some other FS. So, there can be no bullet-proof yet easy to use ID stability anyway.

I am not arguing for keeping this option, just to call spade a spade.

And anyway the error message better be user-readable like "There is no drive 4:\" rather than arcane "Ioctl 0x92010 failed with code 122"

**Comment by Rondom** [comment]
Of course, just pointing out that adding the feature back (if it ever existed) does not make much sense as long as you do not output a stable identifier.

**Comment by the-Arioch** [comment]
But there is no truly stable identifiers anyway.

Random GUIDs are hard to use and can randomly overlap (they did!)
An ever-increasing-after-power-up counter? you can not have it for Dokan driver is loading/unloading without reboots.

Any practical identifier you would make is NOT truly stable. And that was not causing actual trouble yet.

Unless you see a plausible scenario when within the same cmd.exe session (or at very least within a single "interactive session" of a user and without UAC elevation) and ID changes value with, say, 30 seconds without intentional disruptnig actions of said user. Because i don't.

Thus, as i see it, there is no truly unique/stable identifiers, there are number of quasi-stable ones, and those latter are ok for practical purposes yet.

------------

Okay, i dived into the sources and for what i see...

1. `dokanctl /u 1` would jump straight into dokan1.dll / mount.c / `DokanRemoveMountPointEx`
2. the DLL would call `IsMountPointDriveLetter` which is kinda naive and only checks if the string is `{any char}[maybe ":"[maybe "\\"]]` without ever wondering what that first char is (except for NULL).
3. it "canonicalizes" any input into `{any char} ':'` pair.

``` 
wcscpy_s(mountPoint, sizeof(mountPoint) / sizeof(WCHAR), L"C:");
mountPoint[0] = MountPoint[0];
```

4. then it dives into dokan.c / `SendGlobalReleaseIRP`
5. which just forwards it to the driver itself - 

```
        if (!SendToDevice(DOKAN_GLOBAL_DEVICE_NAME, FSCTL_EVENT_RELEASE,
                          szMountPoint, inputLength, NULL, 0,
                          &returnedLength)) {
```

So to sum it up:

1. Userland tool/DLL really dees any single-char `/u` argument the same. Be it "a", "A', "4" or "*" - it is considered a drive letter and passed to the driver almost verbatim (ensuring only it has one following colon and nothing else). 
1.1. This also means that `dokanctl /u 10` or `dokanctl /u 123` would NOT be processed the same way, which would probably confuse users. Neither would `dokanctl /u 01`.
2. It is up to the driver to decide if that thing REALLY is drive letter or something else. 
3. Which is odd to me, as different users can have different drive letter mappings (common problem: UAC-elevated user's applications do not see the network drives non-elevated user mounted before). I wonder if that is the source of problems of "dokan maps filesystem onto a wrong drive letter" kind.
4. However it means the "just number" identifier can be a quasi-stable one, as there is a single global entity (driver) responsible to decide what either ID means.
5. Of course, if decided so, it HAS to be mounted. We might EXPECT that the array index in the code @Rondom 's quoted above corresponds to driver's internal numbering, but there is no CONTRACT on that.
6. My assumption about "within one cmd.exe session" was probably wrong, the digit goes down to the driver.

The driver would have it either in `DokanEventRelease` in sys\notification.c (immediately or by a proxy of `DokanGlobalEventRelease`). Most probably the latter. Which has this snippet:

```
  if ((szMountPoint->Length / sizeof(WCHAR)) < 4) {
    dokanControl.MountPoint[12] = towupper(szMountPoint->Buffer[0]);
    dokanControl.MountPoint[13] = L':';
    dokanControl.MountPoint[14] = L'\0';
  } else {
    if (szMountPoint->Length >
        sizeof(dokanControl.MountPoint) - 12 * sizeof(WCHAR)) {
      DOKAN_LOG_FINE_IRP(RequestContext, "Mount point buffer has invalid size");
      return STATUS_BUFFER_OVERFLOW;
    }
    RtlCopyMemory(&dokanControl.MountPoint[12], szMountPoint->Buffer,
                  szMountPoint->Length);
  }
```

Oooops!

So the driver would obediently try to find and then unmount kernel global mountpoints like `'\DosDevices\C:'0` or `'\DosDevices\8:'0` or `'\DosDevices\*:'0` or `'\DosDevices\Ш:'0` or perhaps even `'\DosDevices\ш:'0`  (i am not sure `towupper` correctly processes non-Latin letters).

==========

Net result: 

1. the alleged 'unmount by number' feature is never implemented in Dokan 1.5.
2. no one seemed to ask it ever, so it is safe to be totally removed (one false line in docs) and banned (for safety)
3. the banning would take Dokan1.dll to match the passed "letter" with the list of actual letters, either received from kernel32.dll (easier) or from Dokan driver (maybe more secure) and fail with human-readable "drive not found" without even trying to go into driver.
4. would it turn out NT Kernel really provides for non-letter drive letters, so be it then, as of now this proposal seems to be "future-compatible" :-)

**Comment by Liryna** [comment]
Hi @the-Arioch ,

Thanks for reopening the issue here and being the only one after so many years to find this incorrect doc 😄 

That's a good reading and I agree with your analyze. It is not worst it and no one is asking for it.
Would you be able to create a pull request to remove "this feature" ?
Feel free also to improve the flaky code you pointed here like `IsMountPointDriveLetter`.

**Comment by the-Arioch** [comment]
Because i'm a perv, or my luck is.

Seasoned devs and users know well what to do and what NOT to do with the app, they safely drive highways and not turn to drak alleys.
Noobs occasionally take wrong turns, then they say many bad words and go away to never look back.
Then there is me, who make bad turn, then goes to say bad words into github, forums, maillist and other places where Google crawling bot would notice me :-)

I am not good with pull requests though. Theory says every feature branch should be insulated, at the same time theory says we should merge often between features and devel, ub the end every featue branch i tried was becoming a snowball if not avalanche :-)

Patchsets seem more controllable to me, at least i can cherry-pick commits :-D

---

"Removing" this feature would take removing one line 51 at `dokany\dokan_control\dokanctl.c` 

If that is not enough and you mean true removal... i would say a thing that i hate to hear when said to me, you need design documents, because it would mean changing driver's API... But that is for another issue, or for a forum...

**Comment by the-Arioch** [comment]
About flaky code, first i have to make my mind to which degree we have a warranty that device letters seen by user are device letters seen by kernel

it is definitely NOT so with network drives
it MAY be so with filesystems
or not

if not, then driver can NOT provide stable API referring to drive letters, ooops

**Comment by Liryna** [comment]
https://github.com/dokan-dev/dokany/commit/009b4948962806d7f2799d8e2edd8b964b3a2585 Done
@the-Arioch Thanks again for being the only one finding this non available option :D !
