### ISSUE TITLE
wiki 404

### ISSUE THREAD

**Issue by the-Arioch** [dokan-dev/dokany#1019]
https://github.com/dokan-dev/dokany/wiki/Unsupported

the link to FS mini-filters is dead

i think cab be replaced with

https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/filter-manager-concepts

**Comment by the-Arioch** [comment]
Also

> Most operating systems including Windows has native support for WebDAV

HAVE not has :-)

**Comment by Liryna** [comment]
Thanks @the-Arioch for the review and report! Fixed 😃
