### ISSUE TITLE
How does dokany work in more than 100 threads? help me.

### ISSUE THREAD

**Issue by zofoc** [dokan-dev/dokany#1020]
Is the maximum value of threadcount 64? I modify dokan myself DOKAN_MAX_THREAD becomes 127 and recompiled. After running, the threadcount  is 64 too. Is this a limitation of the dokany driver kernel? Do I want the dokang worker thread to be greater than 100? How to operate.thank you

**Comment by Liryna** [comment]
Hi @zofoc ,

There is no limitation. Are you sure the new library was used when running your test?
Try to print `ThreadCount ` here
https://github.com/dokan-dev/dokany/blob/31f8381e1efc207e7c02bdea0a47c819e9810c3f/dokan/dokan.c#L235

If you want to handle more request at a time, you might be interested to contribute to this feature: https://github.com/dokan-dev/dokany/issues/981

**Comment by zofoc** [comment]
> Hi @zofoc ,
> 
> There is no limitation. Are you sure the new library was used when running your test? Try to print `ThreadCount ` here
> 
> https://github.com/dokan-dev/dokany/blob/31f8381e1efc207e7c02bdea0a47c819e9810c3f/dokan/dokan.c#L235
> 
> If you want to handle more request at a time, you might be interested to contribute to this feature: #981

Yes.I'm sure that the new library I recompiled was used .but ThreadCount is 64 too. I set  DokanOptions->ThreadCount =127 Directly .but  ThreadCount  is 64 too. Are there any details I haven't done well

**Comment by Liryna** [comment]
@zofoc How do you see that there is only 64 thread if it is set to 127 ?
There is no logic outside the function I pointed. It should be easy to have it set to 127.

**Comment by Liryna** [comment]
@zofoc Could you share the code with the log that prints the number of threads as I pointed and a screenshot of the log being printer ?

**Comment by zofoc** [comment]
In the latest 1.5.0.3, is there any implementation details of the core driver including the option allowipcbatching? Is this option possible to improve the performance of my application environment?

**Comment by Liryna** [comment]
It is really an option that is here to improve the type of situation you have described.
Yes the latest version has the option in the kernel side. It is only the library that needs to be adapted to support it.

**Comment by zofoc** [comment]
What is the kernel driver implementation of the allowipcbatching option? No implementation details on the library? So now I can't set this option to achieve the effect?

**Comment by Liryna** [comment]
Exact the feature does not exist in the library and need someone to look into it.
