### ISSUE TITLE
Issues with installing latest (1.5.1.1000) build

### ISSUE THREAD

**Issue by SgtMcBiscuits** [dokan-dev/dokany#1029]
# Environment
 * Windows version: Windows 10 update 21H1
 * Processor architecture: x64
 * Dokany version: Trying to install 1.5.1.1000
 * Library type (Dokany/FUSE): None
 
# Check List
  - [*] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [*] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [*] I can always reproduce the issue with the provided description below.
  - [*] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I'm trying to install Dokany 1.5.1.1000, which was just released. When doing so, it tells me there is another installation of that same version, and it needs to be uninstalled first. There is no other version installed, I have checked both through Windows uninstaller and CCleaner. I have stopped and uninstalled all previous drivers, and deleted all Dokan files I can find. Now that I've tried to install the new release, the previous release (1.5.0.3000) will no longer work either, instead giving me only the option to uninstall (which fails). I've tried installing manually, restarting my computer numerous times, etc. Since it's not installed, I can only give the log from when it tries to install.

# Logs
[Dokan_Library_1.5.1.1000_Bundle_20211126215556.log](https://github.com/dokan-dev/dokany/files/7611217/Dokan_Library_1.5.1.1000_Bundle_20211126215556.log)

**Comment by tomato3107** [comment]
There should exist another log file for Dokan_x64 that is required for analysis (as the bundle log only tells us Error 0x80070643: Failed to execute MSI package). Please upload that as well.

**Comment by Liryna** [comment]
@tomato3107 Do you still have a dokan1.sys driver present in Windows/system32/drivers ?

**Comment by SgtMcBiscuits** [comment]
> There should exist another log file for Dokan_x64 that is required for analysis (as the bundle log only tells us Error 0x80070643: Failed to execute MSI package). Please upload that as well.

Where would I find the second log file? The one I uploaded was from the installer itself.

> Do you still have a dokan1.sys driver present in Windows/system32/drivers ?

No, I do not have the dokan1.sys file present.

**Comment by tomato3107** [comment]
Your registry seems to be left in a FU state after your CCleaner runs. 

In issue https://github.com/dokan-dev/dokany/issues/918 somebody fixed his problems with the Microsoft tool [Windows troubleshooter](https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed).

**Comment by SgtMcBiscuits** [comment]
Okay, you're correct, it's now installed and works. However, I'm now running into a different issue. With it installed and mirroring a network drive, I cannot write to the file system. My setup is this:

A SMB share on my local server, which I can use "Map network drive" on Windows and interact with the drive as usual, with full R/W access. However, if I use mirror.exe to map the drive as local in Windows, I am unable to write files to it. This is the batch file I'm using:

"C:\Users\DELETED\Documents\Dokan\mirror.exe" /r \\192.168.1.201\Disk /l L

When doing this, the drive successfully maps to the L: drive letter and appears, and I can read files with no issue. When using the right click context menu, under New I only have Folder, with an Admin icon next to it. If I drag and drop a file into the drive, small ones (<~1MB) appear to transfer okay, but larger ones will give me a Windows error, telling me the file no longer exists. I can transfer it to the drive as a network share through Windows though, and it appears and is readable through Dokan immediately.

What can be causing this behavior?

**Comment by Liryna** [comment]
@SgtMcBiscuits The mirror is not built for remote mirroring so such issues are expected.
I imagine one of the request timeout or does not respond the expected data.

Instead of opening an issue specifically for this situation m, a feature request should be opened to have remote storage supported (if it does not already exist).

**Comment by SgtMcBiscuits** [comment]
Ah, I apologize, I was told by someone (unrelated to the project) that it was designed for this. Additionally, it had worked in the past for me, but I understand that was a fluke then. Thank you for your time!

**Comment by Liryna** [comment]
I would be very happy to review any contribution to support and stabilize remote storage with the mirror in case anyone seeing this would be interested!
