### ISSUE TITLE
install question

### ISSUE THREAD

**Issue by Lujunchen** [dokan-dev/dokany#1033]
@Liryna
I dowanload dokan.zip V1.0 && dokan.zip V1.4.
in same win7 environment，i used dokanctl.exe /i d to install dokan driver。i successed install and run server for V1.0。but failed in V1.4，reason is can't start docan service， error code is 577.
but when i used dokansetup.exe，i can install driver in V1.0 && V1.4.
somebody can help me？

**Comment by Lujunchen** [comment]
![无标题](https://user-images.githubusercontent.com/34757982/145226484-4729213d-0145-4561-ab34-938379b502a1.png)
Duplicate of #

**Comment by Lujunchen** [comment]
> ![无标题](https://user-images.githubusercontent.com/34757982/145226484-4729213d-0145-4561-ab34-938379b502a1.png) Duplicate of #

@Liryna

**Comment by Liryna** [comment]
Please see https://github.com/dokan-dev/dokany/issues/830
