### ISSUE TITLE
Restart request forces a restart anyways upon denial.

### ISSUE THREAD

**Issue by Cenoic** [dokan-dev/dokany#1036]
Uninstall requests restart, then upon denial, restarts anyways.

Fix it before you get sued half way to sunday for damages.
Almost lost 5 hours of work because of your ignorance.

**Comment by Liryna** [comment]
Please read the license. Have a great day

**Comment by Cenoic** [comment]
Legally speaking, your licenses was never agreed to as this tagged along as a dependency of Disk Drill and set up shop. 

Having never seen or been provided the information that Disk Drill was utilizing your library, your license / ToS is void amd we can not be bound too it as we had no information your library was on the system. In the states at minimum...

If you really want to hide behind legality, please ensure that people agree to the ToS of your library when installing other programs otherwise had we had damages, we could have sued you-

Now you could have a clause that theoretically states that it's on the developers that utilize your library to include that- which Disk Drill doesn't- Disk Drill could have breached your contract with them making them liable and you could retrieve compensation through breach on contract.

But as it stands, Myself and Cenoic LLC are not bound through contract to you and would their have been damages on our servers, no, you are not covered by a license we never agreed to.

**Comment by Liryna** [comment]
Thank you @Cenoic @JacobGrisham @JacobGrishamPowerSchool for removing your issue #1037 containing insults and threat posted with the user @UrAShitDeveloper that is now also removed. Be sure backups were made.

So as you and I are not lawyers and what you are implying does not look to be consistent,
I would highly suggest you read about the project license and contact Disk Drill. Maybe @CleverFiles would be interested to fill the gap.

As far as Dokan goes, the uninstall of their version does not restart the computer when using the right button.
![disk-drill](https://user-images.githubusercontent.com/4311419/147387216-e50f946d-a1de-4847-94d7-be0a290729e7.gif)

**Comment by JacobGrisham** [comment]
@Liryna I have no idea what's going on. Maybe I was tagged erroneously. I have no affiliation or work history with dokan-dev or dokany.

**Comment by Liryna** [comment]
Sorry wrong Jacob. I was trying to tag this Jacob Grisham that could be hiding behind the fake account. https://www.linkedin.com/in/jacob-grisham-b7098166
