### ISSUE TITLE
Windows 11?

### ISSUE THREAD

**Issue by bailey27** [dokan-dev/dokany#1054]
I know it's frowned upon on github to use a project's issues section like a forum, but I don't know where else to ask this question.

I'd like to upgrade my PC to Windows 11, but I can't find any good information as to whether or not anybody's had luck using the latest Dokany 2.0.0.2000 on Windows 11.

I need Dokany to work on my PC.  I'd rather stay on Windows 10 if there's problems using Dokany 2.0.0.2000 on Windows 11.

I would try it in a VM, but it looks like it's a fair amount of work to get Windows 11 to run in a VM, so I figured I'd ask if it anybody else has tried Dokany 2.0.0.2000 on Windows 11.

If I had another physical PC that I didn't need to have Dokany working on that I could upgrade to Windows 11 and try it on, then I would have done that instead.

**Comment by Liryna** [comment]
Hey @bailey27 !

Glad to see you again!

Yes, dokany support Windows 11. I even did the Windows 11 arm 64 combo and everything was fine.

I will let this issue open to remind me to update the readme after I fix the bsod with my last commit :(
