### ISSUE TITLE
V1 and V2 side by side installation

### ISSUE THREAD

**Issue by pp111** [dokan-dev/dokany#1055]
Hi, I would like to have both v1 and v2 installed on my system.

Currently I only have version 1 installed, however when I try to install the version 2.0.1.1000. The installer shows that a previous version is installed ans should be uninstalled first and the installation aborts.

It is supposed that version 2.0.1.1000 allows side by side v1 and v2 installation, however the installer does not allow it. Is it a bug on the installer? Or, should I use another procedure?

**Comment by tomato3107** [comment]
@Liryna : the BundleUpgradeCode in version.xml needs to be different between versions if it's required that both can be installed concurrently.
@pp111 : a workaround would be to install the .msi directly.

**Comment by js69** [comment]
@Liryna : the BundleUpgradeCode in version.xml needs to be different between versions if it's required that both can be installed concurrently.
@pp111 : a workaround would be to install the .msi directly.

**Comment by Liryna** [comment]
Oh my bad, thanks for the report! I will do a new release tomorrow!

**Comment by Liryna** [comment]
The new install was just published https://github.com/dokan-dev/dokany/releases/tag/v2.0.1.2000
@pp111 let me know if you have any other issue.

**Comment by pp111** [comment]
Hello, I downloaded v2.0.1.2000 and still shows that a previous versions is already installed and I must uninstall it first. I only have version 1.3.0.1000 installed on my computer. Am I missing something?

**Comment by Liryna** [comment]
@pp111 sorry 😢 another value had to be changed. Please redownload the installer at https://github.com/dokan-dev/dokany/releases/tag/v2.0.1.2000 I changed it with a working one.

**Comment by pp111** [comment]
Thank you it is working now :)
