### ISSUE TITLE
rmdir is not working

### ISSUE THREAD

**Issue by Temtaime** [dokan-dev/dokany#1064]
# Environment
 * Windows version: 11
 * Processor architecture: x64
 * Dokany version: latest
 * Library type (Dokany/FUSE): FUSE
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [?] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Hi.
Seems that DeleteDirectory is not working at all because of missed rmdir call.
See https://github.com/dokan-dev/dokany/blob/master/dokan_fuse/src/fusemain.cpp#L464

**Comment by Liryna** [comment]
Hi @Temtaime ,

Here is the rmdir call: https://github.com/dokan-dev/dokany/blob/master/dokan_fuse/src/fusemain.cpp#L172

**Comment by Temtaime** [comment]
[log.txt](https://github.com/dokan-dev/dokany/files/8009097/log.txt)
I grab a log but cannot find anything particular ☹️

**Comment by Temtaime** [comment]
Found it.
For those who get "invalid ms-dos function" upon deleting a file - set 0777 permissions on st_mode in getattr function.
