### ISSUE TITLE
Fuse wrapper crashes on high IO

### ISSUE THREAD

**Issue by Temtaime** [dokan-dev/dokany#1066]
# Environment
 * Windows version: 11
 * Processor architecture: amd64
 * Dokany version: latest
 * Library type (Dokany/FUSE): FUSE
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Run fuse mirror.
Use crystal disk mark with nvme preset and third option(Q32T16).
![image](https://user-images.githubusercontent.com/7421889/153468992-faeff3de-3cd1-4760-b179-0902ca75d138.png)
It will crash almost instantly.
`The instruction at 0x7FFBE7F313AD referenced memory at 0x20. The memory could not be written -> 0000000000000020`
in
`cygdokanfuse2.dll:cygdokanfuse2__ZN14impl_file_lock9lock_fileEP16impl_file_handlexxb`

Sometimes it crashes on EnterCriticalSection, sometimes on LeaveCriticalSection.
Most of the crashes are in `impl_file_lock::remove_file` with invalid `this` pointer.

# Logs
It is not related to dokan, but to fuse wrapper. So no logs here.

**Comment by Temtaime** [comment]
I'm using 2.0.2.1000
Do you mean i should try https://github.com/dokan-dev/dokany/commit/81164bc9cee53a23ec6733de0991249f789dd47e ?

**Comment by Temtaime** [comment]
nvme option provides 16 threads instead of just 1, without this option it takes some time for bug to appear.
The problem lies in file handles/locks being corrupted, i don't think it is related to dokan2 library, but lies in fuse wrapper.
I'll try to provide more info in days

**Comment by Liryna** [comment]
@Temtaime Were you able to look more into this issue?

**Comment by Temtaime** [comment]
Sorry, was a little busy unexpectedly.
Sadly that bug reports are get closed without fixes. You could try to reproduce it on your own.
