### ISSUE TITLE
Passive installation v2.0.3.1000

### ISSUE THREAD

**Issue by pp111** [dokan-dev/dokany#1068]
Hi,

When I run the installer like this:

DokanSetup.exe /passive

Dokan is installed correctly. However if I run again the same command again, dokan is uninstalled.

What I expect is the same behavior than in version 1 installer. If dokan is already installed the installation aborts (since it can not be updated), and it remains installed. It should be only uninstalled if I run the command with /uninstall parameter.

**Comment by Liryna** [comment]
@pp111 Have you tried this:
/install /passive

**Comment by pp111** [comment]
Hi, even if I use /install the driver is uninstalled

A few files files are not removed and remain in the folder
C:\Program Files\Dokan\Dokan Library-2.0.3
these files are not removed even with normal uninstall, so it seems another issue.
