### ISSUE TITLE
32 bit uninstall dokan2 and dokan1

### ISSUE THREAD

**Issue by pp111** [dokan-dev/dokany#1069]
Hi, in a 32 bits machine if I have installed both dokan1 and dokan2 and I try to uninstall dokan2 it is not uninstalled. To uninstall it I have to uninstall first dokan1, and then, dokan2 can be uninstalled.

On 64 bits it is working fine.

**Comment by Liryna** [comment]
@pp111 Can you share the installer logs for all cases ? (64/32 and V1/V2)
