### ISSUE TITLE
Cannot stop driver using 'sc stop dokan2'

### ISSUE THREAD

**Issue by Dwedit** [dokan-dev/dokany#1074]
# Environment
 * Windows version: 10
 * Processor architecture:  x64
 * Dokany version: 2.0.2
 
# Description
In Windows, it is possible to start and stop Kernel-mode drivers using the Service Control Manager.  There is a console tool called `sc.exe` that can request drivers to start or stop.  `sc.exe` needs to be run under administrative privileges.

If you attempt to use the command `sc stop dokan2`, this appears:
```
SERVICE_NAME: dokan2
        TYPE               : 2  FILE_SYSTEM_DRIVER
        STATE              : 3  STOP_PENDING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```
If you try to use "sc query dokan", you will see that it is stuck on `STOP_PENDING`.

Perhaps if this could be resolved, then Dokan could possibly be upgraded on a running system without rebooting.

**Comment by Liryna** [comment]
Hi @Dwedit ,

This was already discussed here https://github.com/dokan-dev/dokany/issues/669 Let me know if that answers your question

**Comment by Liryna** [comment]
I can reopen the issue if you have more input.
