### ISSUE TITLE
FindFilesWithPattern This method will be executed every time you click the resource manager

### ISSUE THREAD

**Issue by TheBestMore** [dokan-dev/dokany#1081]
# Environment
 * Windows version: 
 * Processor architecture: 
 * Dokany version: 
 * Library type (Dokany/FUSE): 
 
# Check List
  - [ ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ ] I can always reproduce the issue with the provided description below.
  - [ ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
 
How to control execution only when opening the drive letter directory?

**Comment by Liryna** [comment]
Dokan just forward the calls received from the OS. Windows might be interested to list files during that action for some reason.
