### ISSUE TITLE
Dokan2: clarify breaking changes regarding FindFiles & FindFilesWithPattern

### ISSUE THREAD

**Issue by robert-j** [dokan-dev/dokany#1084]
# Environment
 * Windows version: 10
 * Processor architecture: x64 
 * Dokany version: 2.0.3.2000
 * Library type (Dokany/FUSE):  Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation. **Mirror does not implement FindFilesWithPattern, so it cannot be used to reproduce the issue**.
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

The documentation of Dokany 2.0.3 FindFiles states that
>  * \ref DOKAN_OPERATIONS.FindFilesWithPattern is checked first. If it is not implemented or
>  * returns \c STATUS_NOT_IMPLEMENTED, then FindFiles is called, if implemented.

The documentation of Dokany 2.0.3 FindFilesWithPattern states that
>  * If the function is not implemented, \ref DOKAN_OPERATIONS.FindFiles
>  * will be called instead and the result will be filtered internally by the library.

This is not true in Dokany 2 any more. I've finished porting a project from 1.4 to 2.0.3 in which FindFiles* were implemented as follows:

    static
    NTSTATUS
    DOKAN_CALLBACK
    MyDriverFindFiles(
        LPCWSTR FileName,
        PFillFindData FillFindData,
        PDOKAN_FILE_INFO DokanFileInfo)
    {
        return STATUS_NOT_IMPLEMENTED;
    }

    static
    NTSTATUS
    DOKAN_CALLBACK
    MyDriverFindFilesWithPattern(
        LPCWSTR PathName,
        LPCWSTR SearchPattern,
        PFillFindData FillFindData,
        PDOKAN_FILE_INFO DokanFileInfo)
    {
        // actual implementation
    }

This code is causing all FindFirst operations to fail because Dokany is never invoking MyDriverFindFilesWithPattern. It is only invoking MyDriverFindFiles, and doesn't pay attention to STATUS_NOT_IMPLEMENTED.

I also tried to set DOKAN_OPERATIONS.FindFiles = NULL to no avail.

The document [Update Dokan 1.1.0 application to Dokany 2.0.0](https://github.com/dokan-dev/dokany/wiki/Update-Dokan-1.1.0-application-to-Dokany-2.0.0) is also misleading as it states:

> Previously FindFilesWithPattern could return STATUS_NOT_IMPLEMENTED and FindFiles would be called right after to process the request. This is no longer the case. If FindFilesWithPattern is assigned to the DOKAN_OPERATIONS struct, it will be called and STATUS_NOT_IMPLEMENTED will fail the request. So if FindFilesWithPattern is not implemented, it must not be assigned to DOKAN_OPERATIONS struct.

It must also mention that FindFiles must be implemented as well if FindFilesWithPattern is provided.

**Comment by Liryna** [comment]
Thanks @robert-j for raising this documentation issues!

I have updated the doc in the library to remove the FindFiles part https://github.com/dokan-dev/dokany/commit/54ad5d71dfed4f885d985ad52c2029a0067fd3f7 but I believe the FindFilesWithPattern is correct, if it is null assigned, FindFiles will be called. https://github.com/dokan-dev/dokany/blob/master/dokan/directory.c#L695-L714

>It must also mention that FindFiles must be implemented as well if FindFilesWithPattern is provided.

We can improve this 👍 https://github.com/dokan-dev/dokany/commit/eb7b3ae4d6aeb4d02b7b2c3d0f852dad83793cf9

Does that look to be correct for you now ?

**Comment by robert-j** [comment]
@Liryna, yes the patch looks good. Thank you.

The FindFilesWithPattern docs are indeed correct.

**Comment by Liryna** [comment]
That's true in the last release but with my last commit you can just implement FindFilesWithPattern and it will be called with a wildcard.

**Comment by robert-j** [comment]
Yes, I saw this. I was just nitpicking. SHOULD was meant as in "implement it when you can". It would save a lot of DokanIsNameInExpression calls, for example.

**Comment by Liryna** [comment]
Good point 👍  https://github.com/dokan-dev/dokany/commit/3cbd08ea8c08c1053d62d0e43a0011fe017e8f22
Note: The library code path used behind is the same whether FindFiles or FindFilesWithPattern was used during a non-pattern listing https://github.com/dokan-dev/dokany/blob/master/dokan/directory.c#L404

Thanks again for your report 😎
