### ISSUE TITLE
SMB Share as Local Phyical Drive

### ISSUE THREAD

**Issue by Nexow91** [dokan-dev/dokany#1087]
Hello and first of all many thanks for Dakony the program is simple and works so far.

The only problem I have is that when I create a drive, it is not recognized as a physical local drive. This means that it is not stored as a local hard disk under Windows Disk Management.

My thought was to back up an SMB share via Veeam Backup Agent.

Veeam can backup local hard drives free of charge, e.g. an external USB hard drive, but also internal hard drives.

Here the mounted drive is not recognized by Veeam, only stored in Explorer. That's why I think it's still a virtual drive.

Please let me know if there is a way to mount the drive so that it is recognized as a full local drive.

Otherwise, thank you for the program.

**Comment by Liryna** [comment]
Hi @Nexow91 ,

Indeed dokan is not a physical disk so it cannot be shown in Windows Disk Management. See [Dokan fs not showing in Disk Manager](https://github.com/dokan-dev/dokany/discussions/1012).

Otherwise, have you tried with the mount manager option ? it is `/o` if you use the mirror sample.

**Comment by Nexow91** [comment]
Thanks for the feedback, unfortunately the /O option didn't help either. I think that the backup program really only shows volumes / disks that can also be seen in Windows Disk Management. Pity

**Comment by Liryna** [comment]
That's unfortunate 😢 There is not much we can do here if the app expect a disk volume.

**Comment by js69** [comment]
Just a question to @Nexow91 : does Veeam work with a drive created by ImDisk? http://www.ltr-data.se/opencode.html/#ImDisk

**Comment by Nexow91** [comment]
Englisch

Thank you for the information, unfortunately it doesn't work here either. Unfortunately, programs such as NetDrive or OSFMount do not work either.

What I haven't tried yet might be ISCSI Connect or Hard Symlink with mklink.
