### ISSUE TITLE
Dokany Releases

### ISSUE THREAD

**Issue by landrix** [dokan-dev/dokany#109]
Hi, is it possible to provide the release binarys as zip at next releases? I would like to install it manually.

**Comment by Liryna** [comment]
Hi,

A script has been added to help during the release and also provide a zip.
https://github.com/dokan-dev/dokany/commit/06fe345a7ae0d33878066a39ea01fca0629c8673

I have also added a zip to this release.
https://github.com/dokan-dev/dokany/releases/tag/v0.8.0-RC3

**Comment by landrix** [comment]
great, thanks :)
