### ISSUE TITLE
How to increase the eject menu on the virtual disk?

### ISSUE THREAD

**Issue by 834772509** [dokan-dev/dokany#1090]
# Environment
 * Windows version: Windows10 19043
 * Processor architecture: AMD
 * Dokany version: 1.5.0 (Rust)
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [ x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x ] I can always reproduce the issue with the provided description below.
  - [ ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

I want to add the "eject" menu to the right-click menu of the virtual disk, like "vhd, iso". I try to create a removable virtual disk in mirror.exe, but when I click the eject menu it says "An error occurred while ejecting DOKAN (M:)."
How to listen for this event? The unmounted() interface has no effect.

# Logs
Please attach in separate files: mirror [output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#mirrorfs), library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#get-logs).
In case of BSOD, please attach minidump or dump [analyze output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#crash-report-bsod).

**Comment by Liryna** [comment]
Could you retry with dokan v2 and share the logs generated by the sample: `mirror /r C:\Users /l m /m /e` after eject button was clicked ?

**Comment by 834772509** [comment]
> 您能否使用 dokan v2 重试并共享示例生成的日志：`mirror /r C:\Users /l m /m /e`单击弹出按钮后？
[logs.txt](https://github.com/dokan-dev/dokany/files/8530761/logs.txt)
The same problem happened in the latest V2.0.3.2000 version.

**Comment by Liryna** [comment]
Thanks! Actually this options is just bugged and we should not support it https://github.com/dokan-dev/dokany/commit/21f149784d79daa39aa4be020436c0d53db397a1
