### ISSUE TITLE
problems with dokan x64 2.0.3.2000

### ISSUE THREAD

**Issue by gilles007-** [dokan-dev/dokany#1091]
# Environment
 * Windows version: W10 x64 21H2 19044.1620
 * Processor architecture: intel
 * Dokany version: x64 2.0.3.2000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [X] I can always reproduce the issue with the provided description below.
  - [X] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
programs crash when using dokany x64 2.0.3.2000 with cppcryptfs >= 1.4.3.11
sometimes; i can close them, sometimes i can't even kill them and i need to reboot
cppcryptfs 1.4.3.10 and dokany 1.5.1.1000 is OK

i can replicate with : mirror.exe /d /s /r C:\ /l m
when my program is blocked, i use ctrl+c to terminate mirror.exe

# Logs
[Document.txt](https://github.com/dokan-dev/dokany/files/8560062/Document.txt)

**Comment by Liryna** [comment]
Could you provide in detail the steps I need to follow to reproduce the issue ? Which program are you talking about ?

**Comment by gilles007-** [comment]
on windows : mirror.exe /d /s /r C:\ /l m
download sublime text 3 or 4 (portable version) : https://www.sublimetext.com/download
create a text file on M:\ and use ctrl+s to save (sometimes you need to do it multiple times)
program will freeze (tested on 3 W10 and a W2012 VM)
i can replicate with others programs : VS2019, paint shop pro 6

**Comment by Liryna** [comment]
I cannot reproduce the issue with sublime text 3 portable or not.
* What is the output of https://github.com/dokan-dev/dokany/blob/master/dokan/dokan.c#L798 ? (it is not part of your logs.
* Does it also happens without `/d /s` ?
* And with `mirror.exe /r C:\ /l m /o` ?
* [procmon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) logs would help us find out if there is an IO stuck somewhere (status column empty)

**Comment by gilles007-** [comment]
_What is the output of https://github.com/dokan-dev/dokany/blob/master/dokan/dokan.c#L798 ? (it is not part of your logs._
Dokan: Using 2 main pull threads

_Does it also happens without /d /s ?_
yes

_And with mirror.exe /r C:\ /l m /o ?_
yes

i made a video and uploaded logs from procmon
[Document.txt](https://github.com/dokan-dev/dokany/files/8581209/Document.txt)
[Logfile.CSV](https://github.com/dokan-dev/dokany/files/8581210/Logfile.CSV)
keep in mind that i don't have this bug all the time : it can happen on save or on close file
to make the video, i had to close the file and reopen it

https://user-images.githubusercontent.com/4212960/165717111-02bb49db-6e53-4904-b764-3a811b8fe3c3.mp4

**Comment by Liryna** [comment]
From the logs, the write happen but follow a lot of QueryBasicInformationFile & NotifyChangeDirectory which probably are due to the incorrect repetition of change notification https://github.com/dokan-dev/dokany/issues/1086

**Comment by gilles007-** [comment]
OK, i'm still using Dokany 1.5.0.3000

**Comment by Liryna** [comment]
@gilles007- please give a try with https://github.com/dokan-dev/dokany/releases/tag/v2.0.4.1000

**Comment by gilles007-** [comment]
tested 2.0.4.1000 for 2 days and it's OK.
thank you
