### ISSUE TITLE
Increase MAX_READ_SIZE in dokan fuse.

### ISSUE THREAD

**Issue by Moonpuck** [dokan-dev/dokany#1092]
Can dokan fuse increase MAX_READ_SIZE from 64KB to 1MB, or make it to fuse option? We built our network filesystem with dokan, and we do not want to do more read calls for big read(1MB or more). Thanks.

**Comment by Moonpuck** [comment]
Another question. I tried to modify MAX_READ_SIZE and build dokan fuse in my windows server 2016(MinGW-64bit env) with the command in build.ps1. Then I got a 553KB libdokanfuse2.dll and a 84KB libdokanfuse2.dll.a file. Is my libdokanfuse2.dll different from which in the installer(470KB libdokanfuse2.dll)? Thanks.

**Comment by Liryna** [comment]
Done. The binary size difference must just be due to the difference of the compiler version.
