### ISSUE TITLE
Invalid parameter on execute and cannot copy

### ISSUE THREAD

**Issue by aktivo** [dokan-dev/dokany#110]
I'm using DokanInstall_0.8.0_redist-RC3.exe with dokan-dotnet-master.
I have two problems:

1. When i try copy files/dirs from virtual drive and paste to physical drive, this error message occurs: 
"The system cannot find message text for message number 0x%1 in message file for 0x%2". 
Files/dirs is not copied.
I try it on Windows 8.1 x64, but on Windows 7 x64 - no errors.

2. When i try run exe file, this error message occurs: "Invalid parameter". 
Exe file is not executed.
I try it on Windows 7 x64, but on Windows 8.1 x64 - no errors.

**Comment by Liryna** [comment]
Hi,

Are you talking about your code or the C# mirror ?
What are your observation regarding the logs ?

**Comment by aktivo** [comment]
It is my own file system. MirrorNet example works fine, but MirrorNet using FileStream for everything.

My own filesystem support this functions (i'm not using Windows FileStream FS = new FileStream ....): 
- CreateFile( string FileName )
- CreateDirectory( string FileName )
- DeleteFile( string FileName )
- DeleteDirectory( string FileName )
- List( string FileName, List<OwnItem> OwnItems )
- Read( string FileName, long Pos, long Length, byte[] Buffer )
- Write( string FileName, long Pos, long Length, byte[] Buffer )
- GetFileInformation( string FileName )
- SetAttributes( string FileName, OWN Attributes )
- SetTime( string FileName, DateTime CreationTime, DateTime LastAccessTime, DateTime LastWriteTime )
- SetFileLength( string FileName, long Length )
- Move( string OldFileName, string NewFileName, bool Overwrite )

I can send you my implementation of DokanOperations - if you want check if it is correct.

if i try copy some file - DokanOperations.Read is not called. But if i try to view file, DokanOperation.Read is called and file is read and viewed (on Windows 8.1 x64).

This logs shows, what happened if i try copy file 'dokannet.dll' from virtual drive M: to physical drive.

[_Log1_.txt](https://github.com/dokan-dev/dokany/files/37782/_Log1_.txt)
[_Log2_.txt](https://github.com/dokan-dev/dokany/files/37781/_Log2_.txt)

**Comment by Liryna** [comment]
If the Mirror C# work, you should compare the difference in the behaviour with your implementation.
I am sorry I do not have personnally the time to review your logs or code. But I know that there is probably some people who would be glad to help you on the dokan group/mailing, could you create a discution there and report your issue ?

**Comment by aktivo** [comment]
Where can i create discussion for my issue ?

**Comment by Liryna** [comment]
Here is the mailing list/group: https://groups.google.com/forum/#!forum/dokan

**Comment by aktivo** [comment]
Thanks you.

**Comment by Liryna** [comment]
NP, I will try to take a look If I can this weekend.

**Comment by aktivo** [comment]
I solve my issue. It is problem with function *DokanOperations.GetFileSecurity*.
**My own file system does not support any security** - i don't know what can return in parameter/variable *__security__*, because solution below does not working:
```cs
security = null;
return( DokanResult.Error ); 
or
return( DokanResult.PrivilegeNotHeld );

security = new FileSystemSecurity();    // cannot be used
```

**My solution:**
1.. i create one file named: '_fSecurity_' and one directory named: '_dSecurity_'
2.. In constructor of DokanOperations i get file and directory security (one time)
```cs
FileInformation FI = new FileInformation( "_fSecurity_" );
fSecurity = FI.GetAccessControl();
DirectoryInformation DI = new DirectoryInformation( "_dSecurity_" );
dSecurity = DI.GetAccessControl();
```
3.. In *DokanOperations.GetFileSecurity* i write this code:
```cs
if (info.IsDirectory == true) { security = dSecurity; } else { security = fSecurity; }
return( DokanResult.Success );
```

- copy files/dirs from virtual directory to physical directory on Windows v8.1 x64 works fine
- execute files on Windows 7 x64 works fine

**Comment by Liryna** [comment]
Glad to hear it :+1: 
Otherwise, did you try to `return NtStatus.NotImplemented;` in GetFileSecurity & SetFileSecurity  ?

**Comment by marinkobabic** [comment]
If the drive does not support security you have to remove acls from FileSystemFlags. This should be added to wiki.

**Comment by sandstorm121** [comment]
Dear Liryna,

How can I detect copying files from dokan drive to the same dokan drive?
I need to filter copying to get only cases of copying files in dokan drive internally.

Look forward to hearing from you soon.
Best regards,
Simon
