### ISSUE TITLE
Failed to uninstall Dokany

### ISSUE THREAD

**Issue by leochou0729** [dokan-dev/dokany#1100]
Hello,
I installed Dokany a couple of months ago. When I try to uninstall it today, it just fails with this log file.
[Dokan_Library_1.4.1.1000_Bundle_20220727170730.log](https://www.dropbox.com/s/nfqf41i7ypzel6o/Dokan_Library_1.4.1.1000_Bundle_20220727170730.log?dl=1)
Does anyone know what the reason is? Is there any way to clean up the old version? Thanks!

Leo

**Comment by Liryna** [comment]
Hi @leochou0729 ,

Could you share all the Dokan logs you can find in `C:\Users\YOUR_USER\AppData\Local\Temp` ?
The one you included does not provide the exact reason of the failure.

**Comment by leochou0729** [comment]
These are all the logs. Thanks!
[Dokan_Library_1.4.1.1000_Bundle_20220727170521_000_Dokan_x64.msi.log](https://www.dropbox.com/s/me6u1rq19iiuvqv/Dokan_Library_1.4.1.1000_Bundle_20220727170521_000_Dokan_x64.msi.log?dl=1)
[Dokan_Library_1.4.1.1000_Bundle_20220727170521.log](https://www.dropbox.com/s/0fcfqjzker2en0m/Dokan_Library_1.4.1.1000_Bundle_20220727170521.log?dl=1)
[Dokan_Library_1.4.1.1000_Bundle_20220727170730_000_Dokan_x64.msi.log](https://www.dropbox.com/s/zw5r8el1gsttkli/Dokan_Library_1.4.1.1000_Bundle_20220727170730_000_Dokan_x64.msi.log?dl=1)
[Dokan_Library_1.4.1.1000_Bundle_20220727170730.log](https://www.dropbox.com/s/nfqf41i7ypzel6o/Dokan_Library_1.4.1.1000_Bundle_20220727170730.log?dl=1)

**Comment by js69** [comment]
ExecuteUninstall:  InstallDokanctlPath="C:\Program Files\Dokan\Dokan Library-1.4.1\dokanctl.exe /r n"
ExecuteUninstall:  Create redirect pipe.
ExecuteUninstall:  CreateProcess dokanctl.
ExecuteUninstall:  CreateProcess failed
ExecuteUninstall:  Error 0x80004004: StartDokanCtlProcess failed

It failed to execute dokanctl.exe for some reason. Does "C:\Program Files\Dokan\Dokan Library-1.4.1\dokanctl.exe" exist on that system?

**Comment by leochou0729** [comment]
The installation folder doesn't exist now. I have no idea what prevents me from installing new versions on my computer. Thanks!

**Comment by js69** [comment]
Folder and files were not removed by the uninstall process. Somebody or something else must have manipulated your system then.

**Comment by Liryna** [comment]
@leochou0729 you could try to download the zip file of this release version on GitHub and restore manually that file to see if it allows the uninstall to continue.

Otherwise you will need to use a Microsoft tool to force the cleanup of the remaining information.
And for the driver, you will need to uninstall it with dokanctl manually: dokanctl /r d
And reboot to delete the dokan1.sys file

**Comment by Liryna** [comment]
@leochou0729 do you need further help on this ?
