### ISSUE TITLE
Question: How to prevent Dokany from unmounting drive if there are some opened files?

### ISSUE THREAD

**Issue by shujaat-github** [dokan-dev/dokany#1103]
- Windows version: Windows 10 64bit
- Application type: Win32 C++ Application
- Dokany version: 2.0.5.1000
- Library type (Dokany/FUSE): Dokany

I have come across a need to prevent Dokany from unmounting drive if there are some opened files. I wonder if there is any built-in feature in Dokany to achieve this or there is any workaround.

**Comment by Liryna** [comment]
Hi @shujaat-github ,

What is exactly the situation ? You would like to know whether files are open and if it is safe for you to ask Dokan for unmounting the drive ?

**Comment by shujaat-github** [comment]
> Hi @shujaat-github ,
> 
> What is exactly the situation ? You would like to know whether files are open and if it is safe for you to ask Dokan for unmounting the drive ?

Yes, this is exactly what I want.

**Comment by Liryna** [comment]
Unfortunately, the library does not keep an Open / Close count but luckily that's something that possible to implement by the userland filesystem by increasing a counter on Open and decreasing on Close. You might want to ignore some Open that are kept long by the system to be aware if the target has changed like folders.

**Comment by shujaat-github** [comment]
@Liryna Probably you are talking about the following two functions for close and open respectively:  https://github.com/dokan-dev/dokany/blob/1c9c20d1d874c1756cfb7d2ebf61e746054196df/samples/dokan_mirror/mirror.c#L1738 https://github.com/dokan-dev/dokany/blob/1c9c20d1d874c1756cfb7d2ebf61e746054196df/samples/dokan_mirror/mirror.c#L1739

But I saw that **MirrorCloseFile** is called more than **MirrorReadFile** for the **_SAME FILE_**, so when I use a **signed integer counter** and decrease that counter on MirrorCloseFile than the counter becomes **negative** while the file remains open in my Word Application.

**Comment by Liryna** [comment]
There is one Close for each CreateFile for one context.
You can have multiple CreateFile on the same file at the same time. That's why you will have the same number of close. The number of readfile is not linked. You can have none in the create close context.

**Comment by Liryna** [comment]
@shujaat-github Let me know if you need further information otherwise can I close this issue ?
