### ISSUE TITLE
GUID's?

### ISSUE THREAD

**Issue by Rikitav** [dokan-dev/dokany#1104]
Can I recognize the Guid number of Linux partitions?

**Comment by Liryna** [comment]
Hi @Rikitav ,

Dokany is Windows only. Not sure what you mean with Linux partitions. Please do not hesitate to detail your question and I will reopen the issue.

**Comment by Rikitav** [comment]
@Liryna Well, look, I have on the first partition of Windows, and on the second Linux Ubuntu.
I ask about it

**Comment by Liryna** [comment]
@Rikitav Dokany is not the right tool for this unfortunately.

**Comment by Rikitav** [comment]
OK, Understood
