### ISSUE TITLE
How do I start HLK testing for DOKAN

### ISSUE THREAD

**Issue by bobohuang1985** [dokan-dev/dokany#1105]
Because microsoft require all drivers pass HLK testing in win 11 22h2, if you preload the driver in win 11 22h2.
So i need to test the Dokan  drivers in win 11 22h2 HLK environment.
But i do not know how to start it.
Normally, I need to choose a device to start test, but Dokan  does NOT create a device by defualt.
So "How do I start HLK testing for DOKAN"?

Thanks

**Comment by Liryna** [comment]
Hi @bobohuang1985 ,
Could you share where have you seen win 11 22h2 now requires HLK testing ?
Which type of driver changes have you applied ? It would help me to guide you through the HLK testing with Dokan.

**Comment by bobohuang1985** [comment]
Hi @Liryna 
It is  the demand for computer manufacturers from microsoft. When the computer is pre-installed with Win11 22H2, all pre-installed drivers must pass the HLK test of 22H2. If the Dokan Driver is not pre-installed on the Win11 22H2 computer, it only needs to pass the HLK test above Win10, I think Dokan has passed that test now.
Now I've only changed some of the names to prevent it from colliding with the original Dokan driver.
1: Changes ServiceName in INF
2: Change DriverName in INF
3: Change DOKAN_DEVICE_PREFIX_NAME in sys/doka.h

Thanks.

**Comment by Liryna** [comment]
Glad you were able to pass the tests! I was doing it in the past but that was actually not necessary. I never had any issue to install the driver with the Microsoft EV signature (like all our releases) on any computers.

**Comment by bobohuang1985** [comment]
@Liryna 
Oh, I think you misunderstand me. I haven't passed the test yet.
Yes, If you're getting Dokan by installation, there's really no problem. But if you pre-install it, i mean it was in the machine when it left the factory, then Microsoft require it pass the HLK in WIN 11H2.
How did you get it the Microsoft EV signature? I think it also need to pass the HLK test, right?
Thanks.

**Comment by Liryna** [comment]
See "A Work-Around for Some"
https://www.osr.com/blog/2021/04/08/lost-cause-no-driver-updates-allowed-except-for-win-10/
If this still does not work (let me know if that's the case and please share a screenshot of the signature on your binaries), I just followed the Microsoft doc to setup the HLK env. Created the server and client VM, pass the test which was taking about ~10min, sign the test results and upload the create archive on Microsoft dashboard.
https://docs.microsoft.com/en-us/windows-hardware/test/hlk/user/windows-hardware-lab-kit-user-s-guide

**Comment by bobohuang1985** [comment]
Hi @Liryna 
   Yes, i had  setup the HLK env, but i can't find the dokan device in "device manager" in HLK Studio.
So How do I start HLK testing for DOKAN?

![Screenshot 2022-08-18 095253](https://user-images.githubusercontent.com/19987113/185274876-80ea5bc4-b5d7-4021-a8cd-31a69f1ca78d.png)

**Comment by Liryna** [comment]
Was the driver installed and started correctly ?

**Comment by bobohuang1985** [comment]
Yes. Do i need to mount a device firstly then select the mounted device to start test?

**Comment by Liryna** [comment]
No, just having the service started is enough. I do not recall if the driver was showing in this section. But it was visible in one of them for sure.

**Comment by bobohuang1985** [comment]
Yes, i found it in "software device". Let me try to test it.

Thanks.

**Comment by bobohuang1985** [comment]
@Liryna 
Thanks for your help.
I've already passed the test, and get the windows logo.

Thanks
