### ISSUE TITLE
changelog.md: year is weird, still 2021

### ISSUE THREAD

**Issue by hpvd** [dokan-dev/dokany#1107]
changelog.md: year is weird, still 2021

see https://github.com/dokan-dev/dokany/blob/master/CHANGELOG.md

![2022-09-07_12h11_30](https://user-images.githubusercontent.com/5681880/188853414-f566cc3c-6d3b-488e-b8c3-c23ed0883f79.png)

**Comment by Liryna** [comment]
Hi @hpvd , Indeed 😄 it is now fixed. Thanks for the report!
