### ISSUE TITLE
Windows 10 applications can't open some files on dokany drive

### ISSUE THREAD

**Issue by shi-yan** [dokan-dev/dokany#111]
I'm testing the latest mirror.c example. I noticed that certain files (png and pdf), can't be open by certain windows 10 built-in applications, such as the "photos" and "Microsoft Edge"

![cantopen](https://cloud.githubusercontent.com/assets/326807/11315600/8a142c10-8fa9-11e5-9de9-e424a7757304.png)

To reproduce this issue, 

1. build and install the latest dokany driver
2. create a folder called test under c:\    (c:\test)
3. download a png image and save it to c:\test
4. build and run mirror, with the following command: mirror.exe /r c:\\test /l m
5. the test folder should be mounted as m:\, and the png file should be seen.
6. right click on the file, and select "open"
7. the default windows app named "photo" should be launched, but the image can't be open.

the same issue is found with Microsoft edge on pdf files. 

Chrome has no trouble opening the same files on the same dokan drive. the issue only happens with the two microsoft apps.

![cantopen2](https://cloud.githubusercontent.com/assets/326807/11315631/2bb0cbe6-8faa-11e5-95da-5de3bb0646a5.png)

the photo app will eventually tells you that the file can't be opened. either it is moved or doesn't exist anymore. the Edge browser will just keep loading the file forever.

**Comment by Liryna** [comment]
Hello,

Thanks for the report !

This has already been reported in a discussion of a closed ticket.
#26 (comment), #97
The possible fix has been added to the TODO of dokan (see Add Oplock Semantics)
#45

If you can provide patch to add the implementation it would be really great !

**Comment by Liryna** [comment]
Fixed in https://github.com/dokan-dev/dokany/commit/731a6279dc8e67460a6169e56886475225f9d8b8

**Comment by shi-yan** [comment]
thank you very much.

geez, wish I was as knowledgeable as you are about filesystem. implementing a simple filesystem program already gives me headache. :(

**Comment by wistful23** [comment]
It looks like Microsoft Edge cannot open PDF files. I observe the same symptoms as in the description. I tried the latest version 1.0.1.1000.

**Comment by Rondom** [comment]
You might need to use the mount manager option for this to work.

**Comment by wistful23** [comment]
Thank you, @Rondom. It works fine with the mount manager option.
