### ISSUE TITLE
Error: canonicalizing path

### ISSUE THREAD

**Issue by shujaat-github** [dokan-dev/dokany#1113]
# Environment
 * Windows version:  **Microsoft Windows 11 x64**
 * Processor architecture:  **Intel Core i7**
 * Dokany version: **2.0.5.1000**
 * Library type (Dokany/FUSE): **Dokany**
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
When using **[Mirror](https://github.com/dokan-dev/dokany/tree/master/samples/dokan_mirror)** sample I get **warning** & **error** while **creating** and **compiling** a **[rust-lang](https://www.rust-lang.org/)** hello world application in the DOKAN mounted drive (in my case drive letter is **U**). 

**When I use any other normal drive I don't get such warning and error.** 

I have [Rust V1.63.0](https://www.rust-lang.org/), using [Visual Studio Code V1.71.2](https://code.visualstudio.com/) on Windows 11, and I use [rust-analyzer](https://github.com/rust-lang/rust-analyzer) extension for VS Code if that can help in Debugging.

## Warning
```
warning: could not canonicalize path: 'U:\'
```

![image](https://user-images.githubusercontent.com/99479518/192433502-872bd60d-56cd-46b9-b3f5-d07f9b4be30e.png)

## Error
``` 
error canonicalizing path `U:\sample_project\target\debug\incremental\sample_project-a5l8xa3t1bei`: The system cannot find the file specified. (os error 2)
```

![image](https://user-images.githubusercontent.com/99479518/192433915-db41fa36-84a0-40e0-aeea-4aa1e73eb2b2.png)

**Comment by shujaat-github** [comment]
Apart from **[Rust issue ](https://github.com/mimidesunya/encfsy/issues/4#issuecomment-1253514066)**, both **[Dokany ](https://github.com/dokan-dev/dokany)** and **[EncFSy ](https://github.com/mimidesunya/encfsy)** has been tested to work **flawlessly** as it can be seen in **[ this report](https://github.com/mimidesunya/encfsy/issues/4#issuecomment-1256039221)**.

**Comment by Liryna** [comment]
Hi @shujaat-github , can you share the command line you used to run the mirror ? Have you tried with the option `/o` ?

**Comment by shujaat-github** [comment]
Hi @Liryna, with `/o` option no warning or error is shown and the project compiles and runs perfectly.
Previously I used this command line to run the mirror:
```
mirror.exe /r C:\Dokany_Mirror_Test /l U
```
Now I use this command line to run the mirror:
```
mirror.exe /r C:\Dokany_Mirror_Test /l U /o
```
![image](https://user-images.githubusercontent.com/99479518/192687374-e774a9f9-d0bb-4097-a3e8-de2e8f9b67f7.png)

Although mirror works perfectly with the option `/o` but I don't want the **Recycle Bin** feature as in case of **EncFSy** some confidential data may end up in the recycle bin. Is it possible to **turn off Recycle Bin feature** even when using `/o` option?

**Comment by shujaat-github** [comment]
@Liryna I may be wrong about security issues if I enable **mount manager** using `/o` option. I would love to hear some comments in this regard from you.

I wonder why mirror doesn't work properly when we don't use `/o` option. It would have been nice if mirror worked without this option.

**Comment by Liryna** [comment]
I might be wrong but this can be configured per drive in the recycle bin setting.
There might be a way to do it programmatically?

Otherwise a better option is to make encFSy to detect the move to recycle bin and directly delete the files instead and return a file not found error.

**Comment by shujaat-github** [comment]
@Liryna Can you please see if it is possible to fix the **canonicalizing path** issue without the `/o` option **?**

@Liryna I appreciate the suggestions you provided. I will definitely check them out.

**Comment by Liryna** [comment]
This is unfortunately not possible. The option register the drive to the mount manager and the API that was failing use the mount manager database to gather the drive information.

**Comment by shujaat-github** [comment]
> This is unfortunately not possible. The option register the drive to the mount manager and the API that was failing use the mount manager database to gather the drive information.

This concludes the issue very well. I'm much thankful for your time.

**Comment by Liryna** [comment]
Glad I was able to help you!
