### ISSUE TITLE
VCRUNTIME140.dll

### ISSUE THREAD

**Issue by kenjiuno** [dokan-dev/dokany#112]
Hi.

v0.8.0-RC3 setup leads me to VC 2013 runtime redist setup.

However, v0.8.0-RC3 setup process fails due to missing VCRUNTIME140.dll. Is it VC 2015 runtime?

**Comment by Liryna** [comment]
Hi @kenjiuno ,

Yes it is VS 2015 runtime. The link to download the runtime was not updated.

This has already been fixed with: https://github.com/dokan-dev/dokany/commit/78324e9fd5391c7ad3df1619c4e00f991fc0669c

**Comment by kenjiuno** [comment]
Ok thanks.
