### ISSUE TITLE
An exception occurs when the memfs_test.ps1 is running.

### ISSUE THREAD

**Issue by zhengkaihu** [dokan-dev/dokany#1120]
# Environment
 * Windows version: win11
 * Processor architecture: Intel 64
 * Dokany version: V2.0.6.1000
 * Library type (Dokany/FUSE): winfstest
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Run memfs_test.ps1 using Windows PowerShell.
Four winfstest displays 'not ok'.

This problem also occurs when winfstest is used to test other files.
cd TestSuite
run-winfstest.bat . D:\temp
total ................................. ok 502/506 - not ok 4/506

# Logs
D:\dokany\samples\winfstest\TestSuite\\.\t\base\00_CreateFile_Dispositions.t  ok
D:\dokany\samples\winfstest\TestSuite\\.\t\base\01_CreateFile_Attributes.t  ok
D:\dokany\samples\winfstest\TestSuite\\.\t\base\02_CreateRemoveDirectory.t  ok
D:\dokany\samples\winfstest\TestSuite\\.\t\base\03_FindFiles.t  ok
D:\dokany\samples\winfstest\TestSuite\\.\t\base\04_MoveFile.t  ok
D:\dokany\samples\winfstest\TestSuite\\.\t\base\05_CreateFile_Truncation.t  ok
D:\dokany\samples\winfstest\TestSuite\\.\t\base\06_FileTimes.t  ok
D:\dokany\samples\winfstest\TestSuite\\.\t\base\07_SetGetFileAttributes.t  ok
D:\dokany\samples\winfstest\TestSuite\\.\t\base\08_CreateFile_Delete.t  
not ok 4 - expect "CreateFile M:\20bc9a78 GENERIC_READ FILE_SHARE_READ+FILE_SHARE_WRITE+FILE_SHARE_DELETE 0 OPEN_EXISTING 0 0" ERROR_ACCESS_DENIED - got ERROR_FILE_NOT_FOUND
not ok 9 - testeval(len(s) == 3)
not ok 12 - testeval("foo" in s)
not ok 3/17
D:\dokany\samples\winfstest\TestSuite\\.\t\base\09_CreateFile_Sharing.t  ok
D:\dokany\samples\winfstest\TestSuite\\.\t\base\10_GetSetSecurity.t  
not ok 9 - expect "CreateFile M:\2d8b3e4a GENERIC_READ 0 0 OPEN_EXISTING 0 0" ERROR_ACCESS_DENIED - got 0
not ok 1/15
D:\dokany\samples\winfstest\TestSuite\\.\t\streams\00_Create_Delete_FileStreams.t  ok
D:\dokany\samples\winfstest\TestSuite\\.\t\streams\01_Create_Delete_DirectoryStreams.t  ok
D:\dokany\samples\winfstest\TestSuite\\.\t\streams\02_FindStreams.t  ok

total ................................. ok 502/506 - not ok 4/506
[log.txt](https://github.com/dokan-dev/dokany/files/10010735/log.txt)

**Comment by zhengkaihu** [comment]
mirror_test.ps1 can pass the test.
total ................................. ok 506/506

**Comment by Liryna** [comment]
Hi @zhengkaihu , it is known that memfs does not support all but most NTFS features.
