### ISSUE TITLE
Building fuse-mirror?

### ISSUE THREAD

**Issue by lonnietc** [dokan-dev/dokany#1122]
Hello,

I have installed Visual Studio 2019 on my Windows 11 (64-bit) system and have been able to build Dokan along with the memfs and mirrorfs so far.

I did not see any sample project in the solution to build the "fuse_mirror" sample and wanted to know if there is a project file for it somewhere as I would like to build this sample and then use that as a template for some other existing non-windows FUSE filesystems that I want to port over to Dokan for a project that I am working on now.

Any help would be greatly appreciated.

Thanks,

**Comment by Liryna** [comment]
Hi @lonnietc ,

There is no Visual Studio solution to build the `fuse_mirror`. We directly use command lines with the different compiler available on msys2 or cygwin: https://github.com/dokan-dev/dokany/blob/31f8381e1efc207e7c02bdea0a47c819e9810c3f/dokan_fuse/build.ps1#L30

**Comment by lonnietc** [comment]
Yea, I also sow some stuff on building with those as well, but as this will be integrated into another project that has a visual studio solution, I was hoping for a dokan-fuse VS solution. 

I will have to find some other way to accomplish it. Maybe a port of the FUSE repo over to Dokan would work.

Thanks again

**Comment by Liryna** [comment]
Just to be sure, the dokan fuse code has a project which is part of the main solution.
The sample mirror fuse is not our project and is provided as is without a visual studio solution.

**Comment by lonnietc** [comment]
Thank for the information on this and I will probably just try to port a fuse one over to Dokan to see what I can come up with.
