### ISSUE TITLE
Fuse Mirror - Invalid Argument

### ISSUE THREAD

**Issue by FatSkat** [dokan-dev/dokany#1127]
# Environment
 * Windows version: Windows 7 PS1 64bit
 * Processor architecture: Intel i5-750
 * Dokany version: 2.0.6
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I am trying to mirror a FUSE based drive (created by rclone) but it seems like I am not using the right commands. I have not found any examples with FUSE Mirroring but I've tried what works for mirror:
mirror.exe /r FuseDrive: /l NewDriveLetter
I get invalid argument 'FuseDrive:"

Any help would be appreciated.

# Logs

**Comment by Liryna** [comment]
Hi @FatSkat ,

The `fuse_mirror` use the standard fuse arguments https://github.com/dokan-dev/dokany/blob/master/dokan_fuse/src/fuse_helpers.c#L43-L82

**Comment by FatSkat** [comment]
Thank you for your reply! I still can't figure it out but I'll take another look tomorrow

**Comment by Liryna** [comment]
What are you trying to do and why use the fuse mirror and not the dokan mirror ?

**Comment by FatSkat** [comment]
I am trying to mirror a FUSE-rclone file system to show as NTFS. I've basically mounted a Google Drive through rclone (which is using FUSE https://rclone.org/commands/rclone_mount/ ) and I am now trying to mirror that as a local NTFS drive. It doesn't seem to work with dokan mirror so I thought maybe fuse mirror would do the trick. Thank you!
