### ISSUE TITLE
Speed test problems

### ISSUE THREAD

**Issue by huddhudd** [dokan-dev/dokany#1128]
![image](https://user-images.githubusercontent.com/8034908/210947807-939c02d7-7d60-47c7-9493-4a9a58f9e474.png)

When I test that I do not read the disk directly

Windows cache reads other disks to 4G
But the M-disk of dokany is only 1.3G
There is a big gap. Can you tell me why? thank you

**Comment by huddhudd** [comment]
I'll test the read speed of Windows file cache again and compare it with that of dokany

It seems that dokany does not use Windows cache

When R3 reads files, there will be a cache. 
But R0 (dokany) ->R3 (Mirror. exe) ->WindowsCache (NTFS)

Then go back the same way. thus. Reading cached file data is much slower.

 recommended ：R0 (dokany)   read  WINDOWS cache

**Comment by Liryna** [comment]
Please see https://github.com/dokan-dev/dokany/discussions/1047 @huddhudd I might answer your question
