### ISSUE TITLE
volumes visibility

### ISSUE THREAD

**Issue by maurosampietro** [dokan-dev/dokany#113]
I'd like to make my volume invisible to explorer is there any mount option to do this?

I'd also like to point out that Dokan volumes are not visible from disk management, at least in windows 7.

**Comment by Liryna** [comment]
Explorer: Did you try something like: http://www.howtogeek.com/howto/windows-vista/hide-drives-from-your-computer-in-windows-vista/ ?

Dokan is not a real volume for windows for now.
But with https://github.com/dokan-dev/dokany/issues/50,  Dokan volumes are going to be visible from disk management.

**Comment by maurosampietro** [comment]
Yes i am able to hide a volume by creating a key in the registry, that requires to logoff or reboot tipically so it is not optimal for me. 

Mauro Sampietro
Inviato da iPhone

**Comment by Liryna** [comment]
You can also return acces denied to all explorer.exe calls.
See: https://github.com/dokan-dev/dokany/blob/a15e41bfbaa34d47854b7e303fd1d012aaf8a21f/dokan/dokan.h#L72
