### ISSUE TITLE
Can Dokany support lock the same file through diffrent volume

### ISSUE THREAD

**Issue by ylgybbz** [dokan-dev/dokany#1133]
# Environment
 * Windows version: Windows Server 2019
 * Processor architecture: x86
 * Dokany version: 2.0.3.1000
 * Library type (Dokany/FUSE):Dokany 
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [ ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I developed a file system using dokany,  according to the instructions, no lock-related interfaces have been implemented(Dokan wil handle it). The test is : mount the same filesystem with different volumes lable on a host, I lock the file on volume 1, produce another IO process tries to lock the same file through volume 2, but the lock is also successful. However，I expect the second lock should failed，I wonder Can This scenario supported by dokany kernel without usermode lock-handler？

# Logs
Please attach in separate files: mirror [output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#mirrorfs), library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#get-logs).
In case of BSOD, please attach minidump or dump [analyze output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#crash-report-bsod).

**Comment by Liryna** [comment]
Hi @ylgybbz ,

Why would the lock on the second volume should fail ? Both files are different.

**Comment by ylgybbz** [comment]
> Both



> Hi @ylgybbz ,
> 
> Why would the lock on the second volume should fail ? Both files are different.

actually two volume share the same space/filesystem through network,  but just mount twice. so the file is the same one

**Comment by Liryna** [comment]
Dokan can forward the lock request to userland when `DOKAN_OPTION_FILELOCK_USER_MODE` mount option is used. After that you will need to implement your own locking on those files through the network.

**Comment by ylgybbz** [comment]
> Dokan can forward the lock request to userland when `DOKAN_OPTION_FILELOCK_USER_MODE` mount option is used. After that you will need to implement your own locking of those files through the network when receiving the lock requests.
Thanks，I have learned this from the interface description. I just want to confirm whether dokany or the kernel can handle it by itself if this interface is not implemented

**Comment by ylgybbz** [comment]
> Dokan can forward the lock request to userland when `DOKAN_OPTION_FILELOCK_USER_MODE` mount option is used. After that you will need to implement your own locking of those files through the network when receiving the lock requests.

Thanks，I have learned this from the interface description. I just want to confirm whether dokany or the kernel can handle it by itself if this interface is not implemented
