### ISSUE TITLE
Can't mount a network share

### ISSUE THREAD

**Issue by BakaPhoenix** [dokan-dev/dokany#1134]
# Environment
 * Windows version: 10 Pro 22H2
 * Processor architecture: Ryzen 9 5900x
 * Dokany version: 2.0.6(tried 2.0.5 aswell)
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [v] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [v] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [v] I can always reproduce the issue with the provided description below.
  - [v] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [v] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
When i try to access the drive i mounted i get this error:
![image](https://user-images.githubusercontent.com/3168993/224571339-82022b44-744d-4ae6-8ae1-91d945322624.png)
the dokany window is empty:
![image](https://user-images.githubusercontent.com/3168993/224571909-91eb6b11-60b4-43fe-b4a4-3951c7ada781.png)

The command i used to mount the share is:
`runas /savecred /user:Administrator "mirror.exe -r \\truenas\nas -l Z"`

I added the nas as location and i can access it fine

# Logs

[mirror_log.txt](https://github.com/dokan-dev/dokany/files/10952013/mirror_log.txt)
I couldn't get DbgView logs because the program froze when I tried to save the output, there wasn't anything related to dokany only some razer synapse stuff, if they are needed I'll try to get them again

**Comment by Liryna** [comment]
Hi @BakaPhoenix 

In the logs, it is `C:\Users\_YOU_LOGIN_` that is mirrored instead of `\\truenas\nas`. Could you check and provide new logs ?

Are you sure the mirror has access to `\\truenas\nas` ?

**Comment by BakaPhoenix** [comment]
After some testing you are right. The problem is i run dokany as Administrator account to fix some of the permission problems but i never opened the share with that Administrator account, only used my other local account, so it failed to access it.

After accessing and saving the credential with that account i can mount the nas no problem.
Thanks for the help.
