### ISSUE TITLE
How to mount a MooseFS with Dokany on Windows?

### ISSUE THREAD

**Issue by hwhsu1231** [dokan-dev/dokany#1135]
### Problem Description

I saw this Dokany on MoosesFS's GitHub page.

Link: https://github.com/moosefs/moosefs#supported-platforms

I wondered how do I use Dokany to mount a MooseFS on Windows?

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/224694000-85baf349-882a-4997-ab01-0bec9651cc6e.png)

**Comment by Liryna** [comment]
Hi @hwhsu1231 ,

MooseFS must have implemented a Dokan filesystem but I can't say where you can get it. Best to ask them directly.

**Comment by VideoFX** [comment]
I would also like this, however it seems MooseFS is only supporting that directly as part of a commercial plan.
