### ISSUE TITLE
dokan-python wrapper

### ISSUE THREAD

**Issue by arekbulski** [dokan-dev/dokany#115]
I see there is a wrapper for Ruby but not a wrapper for Python. Perhaps someone interested would be willing to work on that. I do not have the necessary knowledge to create one. There is a possibility that project Cameleonica #42 will end up being implemented in Python, which then means FUSE/Python, and next step will be... Dokan.

**Comment by Liryna** [comment]
:+1: for the python wrapper or even if someone could share his experience with a fuse-python wrapper and  dokany !

**Comment by Liryna** [comment]
Hi @arekbulski,
I just seen that there is an implementation of dokan (probably old and abandonned)
http://docs.pyfilesystem.org/en/latest/expose/dokan.html
It is probably old and abandonned, but it is better than nothing for a start.

**Comment by arekbulski** [comment]
Thanks @Liryna 
I would not have known about PyFilesystem if you did not mention it, thanks. I only started reading about it but it seems to be very useful to me. :+1:  In fact, I think this solves the Issue.

**Comment by kitsmag** [comment]
PyFilesystem/pyfilesystem#236

**Comment by arekbulski** [comment]
Lyrina fixed the pyfilesystem-dokan issues.
