### ISSUE TITLE
Dokan Mount Failed from remote using rdp

### ISSUE THREAD

**Issue by Lucasq11** [dokan-dev/dokany#1150]
# Environment
 * Windows version: Win10 professional
 * Processor architecture: x64
 * Dokany version: 1.4.0.1000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [Yes] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [Yes] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [Yes] I can always reproduce the issue with the provided description below.
  - [No] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [No] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I use rdp to connect my remote machine and mount my filesystem on D:\mount dir. It fails and I got log like below. When I refered to https://github.com/dokan-dev/dokany/issues/240#issuecomment-225802352, I used adminstator to open cmd and execute mount command, then it worked. I think the log says it can't create a file handle for mount dir, but why rdp has to switch to adminstrator? It works localy without admin right.

# Logs
Dokan: debug mode on
Dokan: use stderr
AllocationUnitSize: 512 SectorSize: 512
device opened
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1758-4085-bce7-964f1e9f5de9}: 5
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1758-4085-bce7-964f1e9f5de9}: 5
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1758-4085-bce7-964f1e9f5de9}: 5
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1758-4085-bce7-964f1e9f5de9}: 5
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1758-4085-bce7-964f1e9f5de9}: 5
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1758-4085-bce7-964f1e9f5de9}: 5
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1758-4085-bce7-964f1e9f5de9}: 5
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1758-4085-bce7-964f1e9f5de9}: 5
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1758-4085-bce7-964f1e9f5de9}: 5
CreateMountPoint D:\mount -> \??\Volume{d6cc17c5-1758-4085-bce7-964f1e9f5de9}\ success
Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1758-4085-bce7-964f1e9f5de9}: 5
mounted: D:\mount -> \Volume{d6cc17c5-1758-4085-bce7-964f1e9f5de9}
Mounted
Unmount

unload
send global release for D:\mount
DokanError: Ioctl failed with code 122
Failed to unmount: D:\mount

Mount using Mirror is also unavailable without adminstrator right, log is like:

[Mirror] Failed to add security privilege to process
        => GetFileSecurity/SetFileSecurity may not work properly
        => Please restart mirror sample with administrator rights to fix it

And it is also available to mount in a admin cmd

**Comment by Liryna** [comment]
Hi @Lucasq11 ,

What mirror param are you using ? It looks like the current user do not have access to open the device that was created for the mount instance.
Is it a fresh Windows install ? Could it be that an application block the access of the device (antivirus etc)

**Comment by Liryna** [comment]
Is it a fresh Windows install ? Could it be that an application block the access of the device (antivirus etc)

Have you tried with dokan 2 ?

**Comment by Lucasq11** [comment]
I think it is due to antivirus back ground process, thanks.
