### ISSUE TITLE
Unable to install Dokan even with windows in safe mode

### ISSUE THREAD

**Issue by AlbertoA340** [dokan-dev/dokany#1156]
# Environment
 * Windows version: WINDOWS 11 PRO Versione	10.0.22621 build 22621
 * Processor architecture: I7 13700K
 * Dokany version: 2.0.6
 * Library type (Dokany/FUSE): Dokan library 2.0.6.1000
 
# Check List
  - [Yes] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [not tried yet] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [Yes] I can always reproduce the issue with the provided description below.
  - [Tes] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [No] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Hi guys
I've a problem with installing dokan.exe and also the .msi 
Before all this problem i used dokan for AUTOORTHO ( A image streaming for X-plane) and it worked well until i update the autoortho version to the lastest 
The thing is i uninstalled Dokan without any problem just to see if the problem of autoortho was due to dokan but i discovered it wasn't.
After uninstalling Dokan i tried installing it again without success.
I tought the problec could be some left files of dokan so i deleted it without success 
Also i deleted any traces of dokan in the registry too.
I also tried installing it with windows in safe mode and nothing 
Which problem could be?
Sorry about the log but all of them are all the attempt i made

# Logs
Please attach in separate files: mirror [output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#mirrorfs), library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#get-logs).
In case of BSOD, please attach minidump or dump [analyze output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#crash-report-bsod).
[Dokan_Library_2.0.6.1000_Bundle_20230625173138_000_Dokan_x64.msi.log](https://github.com/dokan-dev/dokany/files/11860402/Dokan_Library_2.0.6.1000_Bundle_20230625173138_000_Dokan_x64.msi.log)
[Dokan_Library_2.0.6.1000_Bundle_20230625173026.log](https://github.com/dokan-dev/dokany/files/11860403/Dokan_Library_2.0.6.1000_Bundle_20230625173026.log)
[Dokan_Library_2.0.6.1000_Bundle_20230625190320.log](https://github.com/dokan-dev/dokany/files/11860404/Dokan_Library_2.0.6.1000_Bundle_20230625190320.log)
[Dokan_Library_2.0.6.1000_Bundle_20230625190320_000_Dokan_x64.msi.log](https://github.com/dokan-dev/dokany/files/11860405/Dokan_Library_2.0.6.1000_Bundle_20230625190320_000_Dokan_x64.msi.log)
[Dokan_Library_2.0.6.1000_Bundle_20230625190305.log](https://github.com/dokan-dev/dokany/files/11860406/Dokan_Library_2.0.6.1000_Bundle_20230625190305.log)

[Dokan_Library_2.0.6.1000_Bundle_20230625190300.log](https://github.com/dokan-dev/dokany/files/11860407/Dokan_Library_2.0.6.1000_Bundle_20230625190300.log)
[Dokan_Library_2.0.6.1000_Bundle_20230625190300_000_Dokan_x64.msi.log](https://github.com/dokan-dev/dokany/files/11860408/Dokan_Library_2.0.6.1000_Bundle_20230625190300_000_Dokan_x64.msi.log)
[Dokan_Library_2.0.6.1000_Bundle_20230625173712.log](https://github.com/dokan-dev/dokany/files/11860409/Dokan_Library_2.0.6.1000_Bundle_20230625173712.log)
[Dokan_Library_2.0.6.1000_Bundle_20230625173138.log](https://github.com/dokan-dev/dokany/files/11860410/Dokan_Library_2.0.6.1000_Bundle_20230625173138.log)

**Comment by Liryna** [comment]
Hi @AlbertoA340 sorry for the delay. I can't see any failure. It seems to think Dokan is still installed ?
The best would be to try to use Fix-It Windows tool to clean up the remaining of the installation.
