### ISSUE TITLE
Dokan critical error

### ISSUE THREAD

**Issue by shorinkirill** [dokan-dev/dokany#1159]
# Environment
 * Windows version: Windows 10, 22H2 (OS 19045.3208)
 * Processor architecture: Core i5-9400 is 2.9 GHz.  x64
 * Dokany version:  Dokan Library-1.4.1
 * Library type (Dokany/FUSE):  Dokany
 
# Check List
  - [X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ ] I can always reproduce the issue with the provided description below.
  - [ ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
When I launched 3 threads of my program, each 1000 * 1024 * 1024 bytes should have written in parallel to a network drive through a dokan, after 3 files visually appeared at 0 bytes, the system immediately crashed
# Logs

[072023-9234-01.zip](https://github.com/dokan-dev/dokany/files/12109467/072023-9234-01.zip)

**Comment by Liryna** [comment]
Hi @shorinkirill,

It might be difficult to investigate such issues without reproducing with one of the official sample. Have you checked if the issue could be related to how your implementation returns or set the data ?

**Comment by Liryna** [comment]
A lot has changed since Dokan 1.4.1. I would suggest updating to the latest and retry.
