### ISSUE TITLE
issue: dokan wiki page outdated

### ISSUE THREAD

**Issue by luc-git** [dokan-dev/dokany#1166]
If you open this link you can see the function "DOKAN_OPERATIONS::OpenDirectory". But this function doesn't exist anymore.
The function "DOKAN_OPERATIONS::CreateFile" is now called "DOKAN_OPERATIONS::ZwCreateFile".

https://github.com/dokan-dev/dokany/wiki/FUSE

**Comment by Liryna** [comment]
Thanks @luc-git ! Indeed this should be updated. I will take care of it later 👍

**Comment by Liryna** [comment]
Took me some time but this is done 😎  Thank again for the report.
