### ISSUE TITLE
Fuse3 support

### ISSUE THREAD

**Issue by smessmer** [dokan-dev/dokany#1167]
Fuse3 was released in 2016 and is now in the process of replacing fuse2 in all major distributions. I'm in the process of upgrading [CryFS](https://cryfs.org) ([repo](https://github.com/cryfs/cryfs)) to fuse3 but this doesn't seem to work with DokanY.

Fuse3 introduced [some API changes](https://github.com/libfuse/libfuse/releases/tag/fuse-3.0.0), e.g. `readdir` now takes an additional parameter `fuse_readdir_flags` but it seems DokanY still uses the fuse2 APIs. Would it be possible to upgrade the dokan-fuse wrapper to add the fuse3 APIs? Possibly gated by the fuse `FUSE_USE_VERSION` macro so we don't have to break fuse2 implementations?

**Comment by Liryna** [comment]
Hi @smessmer ,

Indeed that would be a good change! Please see the already open ticket here https://github.com/dokan-dev/dokany/issues/182
