### ISSUE TITLE
It cannot be mounted in the current directory, but the documentation indicates that it is possible.

### ISSUE THREAD

**Issue by hkf7703** [dokan-dev/dokany#1176]
According to the documentation, set the mount point to the current directory (d:\\execpath\\data), but report: Can't assign a drive letter or mount point. test on project DokanNetMirror.
![image](https://github.com/dokan-dev/dokany/assets/1559696/28e2fc3f-dd63-48fc-9e46-032b9bd532db)

**Comment by LTRData** [comment]
The mount point directory needs to be empty. Could that be the issue in your case?

**Comment by hkf7703** [comment]
Thank you. If the mount point folder is created and empty, it can be mounted. Previously, it was because I didn't create this folder.

**Comment by Liryna** [comment]
Thanks @hkf7703 for the question and @LTRData for the answer 😃 . I updated the documentation to include those requirements
