### ISSUE TITLE
Compatible jdokan.dll

### ISSUE THREAD

**Issue by exaptations** [dokan-dev/dokany#119]
Would it be possible for java developers who just want to leverage the java wrapper, and aren't setup to compile jdokan.dll against would it be possible to have a later snapshot / production release 

https://oss.sonatype.org/content/repositories/snapshots/com/github/dokan-dev/dokan-java/dokan-java/0.1-SNAPSHOT/

As the jdokan.dll isn't compatible with 0.8.0.x

**Comment by Liryna** [comment]
Hello @exaptations ,

Could you recreate this ticket in the dokan-java repository ?
https://github.com/dokan-dev/dokan-java

It is @sherter that handle the java part of dokan.
You can also propose a pull request to update the wrapper, I am sure he would be glad to get some help on it !
