### ISSUE TITLE
How to safely remove ISO mount?

### ISSUE THREAD

**Issue by lanopk** [dokan-dev/dokany#1197]
# Environment
 * Windows version: Windows 11 Pro
 * Processor architecture: X64
 * Dokany version: 2.1.0.1000
 * Library type (Dokany/FUSE):  Dokany
 
# Check List
  - [X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [X] I can always reproduce the issue with the provided description below.
  - [X] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [X] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

Set the MountManager option using Dokan to connect the drive to z:.

Then mount one ISO file by double-clicking in Explorer.
The ISO is mounted on "L:".
“DVD Drive (L:) <label name>” appears in Explorer.

And then disconnect “Z: drive”.

Problem 1: “DVD Drive (L:) <label name>” still exists in Explorer.

Right-click on “DVD Drive (L:) <label name>” and select Eject.
“DVD Drive (L:) <label name>” disappears.

Problem 2: When I open "My PC" in Explorer, "DVD Drive (L:)" appears, and an "CDROM(0) DVD(L:} No Media" exists in Disk Manager.
This empty L: drive will not perform any operations, such as ejecting.
It won't go away until I reboot the system.

How can I safely remove the mounted ISO before disconnecting the "Z: drive"?

As a side note, when I inspect the list of open files before disconnecting the Z: drive, Explorer still keeps the ISO file open.
So, is there a way to solve this problem by sending a signal to Explorer about the file?

**Comment by Liryna** [comment]
Dokan does not mount ISO and is not a CDROM driver. Perhaps you are using a third-party software to do it ?

**Comment by lanopk** [comment]
I just connect the drive with Dokan and
I double-clicked one ISO file on that drive in Explorer.
Then I released the drive.
The CDROM mount will then remain on my system.
This is the same even if you use a mirror. (MountManager Option must be added.)

I don't use any other software to mount ISO.

**Comment by Liryna** [comment]
I am curious what is Windows behavior when a real drive is used.
I don't think there is a lot we can do here to tell the truth.

**Comment by lanopk** [comment]
If I can't handle it in the driver, I have to do something in my program, but it's really difficult with my lack of knowledge.
thank you for the reply.
