### ISSUE TITLE
There is no certificate in dokan2.sys for version 2.1.0.1000.

### ISSUE THREAD

**Issue by lanopk** [dokan-dev/dokany#1198]
DokanSetup failed, so I looked at the Dokan.zip file and found that dokan2.sys does not contain a certificate.

An error occurs when installing manually.

dokanctl.exe /i d

Installing driver...
 : DokanServiceInstall: Service (Dokan2) installed
DokanServiceControl: Failed to start service (Dokan2). error = 577
DokanServiceInstall: Service (Dokan2) start failed
Driver install failed

**Comment by lanopk** [comment]
sorry.
There is something signed in the sys folder.

**Comment by Liryna** [comment]
Hi, this is expected. Only the driver in the sys folder is signed and ready for release.
