### ISSUE TITLE
transifex/other tm. 

### ISSUE THREAD

**Issue by necrose99** [dokan-dev/dokany#12]
if you want i can update the jp readme or spanish

**Comment by Maxhy** [comment]
Thanks for your proposol @necrose99.
I don't think we should disperse our effort on translation here but focus on English language improvement.

**Comment by necrose99** [comment]
its no bigg'y , transifex.com or other tm's I've used with many other projects, its more passive , ie push a pot and or docs and let it crowd source/volunteers do so..  integrate at leisure. 
thus you can focus more on the core product. , volunteers can translate at their leisure also

**Comment by Maxhy** [comment]
Ok why not, I don't have any experience with necrose99 but I will give a try.
I invited you as a team manager if you want to take care about the initial step. Thank you.

**Comment by Maxhy** [comment]
Discussion should continue on Transifex, https://www.transifex.com/projects/p/dokany/
