### ISSUE TITLE
Dokan2 driver fails to install on Windows 10

### ISSUE THREAD

**Issue by cowboy823** [dokan-dev/dokany#1225]
Hello Dokan.

When I installed the latest version dokan 2.1.0, it works well on my vm pc(Win10).
But when attempting to intall it manually (see below) with my dokan driver I built, it returns an error 127. I'm not sure what I have mistake.

C:\MyWork\Dokan\dokany-2.1.0.1000\x64\Release>dokanctl /i d
Driver path: 'C:\WINDOWS\system32\drivers\dokan2.sys'
Installing driver...
DokanServiceInstall: Service (Dokan2) installed
DokanServiceControl: Failed to start service (Dokan2). error = 127
DokanServiceInstall: Service (Dokan2) start failed
Driver install failed

I have successfully built dokan driver on VS 2022. And to pass kernel code signing verification I already configured my vm with dokan tutorial.
How can I solve this issue? please help me.

**Comment by Liryna** [comment]
Hi @cowboy823 ,

Please see https://github.com/dokan-dev/dokany/issues/1174#issuecomment-1732839633

**Comment by cowboy823** [comment]
Thank you for your help.
But I have not solved my issue yet.
My OS is Windows 10 Enterprise 22H2, OS build 19045.4529, I used VS 2022, WDK 10.0.22621 but still does not work.
And That article is for Dokan1.0
I'm compilng dokany 2.0
Please check my issue again.
