### ISSUE TITLE
Network Provider names are inconsistent

### ISSUE THREAD

**Issue by pollylm** [dokan-dev/dokany#123]
Hello
I think found an issue with the network provider names set in the registry keys. HKLM/SYSTEM/CurrentControlSet/Services/Dokan/NetworkProvider and HKLM/SYSTEM/CurrentControlSet/control/NetworkProvider/Order use the names 'DokanNP' and 'Dokan', respectively.
This makes the Windows utility 'net use' fail when Dokan is installed, and possibly others. Changing both names to 'DokanNP' allows the utility to work, and as far as I have seen lets Dokan work as well.

Looking into the class mount.c, i think that the name is set to the variable DOKAN_NP_NAME, while the ProviderOrder is hard coded to 'Dokan'. 

Also, using dokanctl.exe to reinstall the network provider sets them to the same names again.

**Comment by Maxhy** [comment]
Indeed this looks like an old issue.
Fixed, thanks!
