### ISSUE TITLE
v2.2.0.1000 is missing from chocolatey

### ISSUE THREAD

**Issue by lostmsu** [dokan-dev/dokany#1243]
Hi @Liryna 

Please assign this issue to me if you would like me to follow up with chocolatey. They seem to have some CPU architecture-related issue with the package. Ugh

**Comment by Liryna** [comment]
Hi @lostmsu 

Which error are you seeing? The package seems to be present and passed the checks.
https://community.chocolatey.org/packages/dokany2/2.2.0.1000

**Comment by Liryna** [comment]
Oh sorry it is in moderation looks like 😮 
`This version is in [moderation](https://docs.chocolatey.org/en-us/faqs#what-is-moderation) and has not yet been approved. This means it doesn't show up under normal search.`

**Comment by Liryna** [comment]
The package was manually approved 👍 Let me know @lostmsu if you see something else that we need to handle
