### ISSUE TITLE
Mirror : File corruption when copying from mounted drive

### ISSUE THREAD

**Issue by michelgre** [dokan-dev/dokany#1244]
Hello

I noticed a problem when using mirror.exe to mount and copy files.

# Environment
 * Windows version: 11
 * Processor architecture: AMD
 * Dokany version: 2.2.0.1000 (and previous)
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I use mirror.exe to mount a SMB share to a drive of my PC.
For some files, but not all, the data is corrupted when I copy the file from the mounted drive. The file length is OK and there is no error popup, but the content is partially messed up and replaced with nulls. The actual content varies from one copy to another for the same file. I noticed that for PDF files and for images files, because the viewer complains that the file is corrupt.

If I open the file directly from the mounted drive, there is no error, the content is correct. The corruption occurs only if I copy the file using Windows explorer or CMD copy.

If I copy the file using the UNC path of the shared folder, there is no error.

If I copy the file with Cygwin cp from the mounted drive, there is no error.

I noticed this problem while I was using an older version of Dokan so I upgraded to the latest version but it did not solve it.

Command to mount the disk : "c:\Program Files\Dokan\mirror.exe" /r \\QNAP2\Public\Dokan /l Q:\ /s 
(as administrator).

Attached:
- mirror log
- dbgview log
- original file
- copied file (corrupt)

# Logs
[mirror.log](https://github.com/user-attachments/files/16727483/mirror.log)
[DbgView.log](https://github.com/user-attachments/files/16727487/DbgView.log)
[30141_50_2.pdf](https://github.com/user-attachments/files/16727490/30141_50_2.pdf)
[Copied.pdf](https://github.com/user-attachments/files/16727494/Copied.pdf)

Thank you.

**Comment by Liryna** [comment]
Hi @michelgre,

Explorer and copy are working the same for all files but since the issue only happens for some type of files, I would tend to believe it is due to a third party software.
I wonder if `"c:\Program Files\Dokan\mirror.exe" /r \QNAP2\Public\Dokan /l Q:\ /o` could help here  (mount manager option) ?

**Comment by michelgre** [comment]
Hello 

Thank you Liryna.

I tried but it didn't help.

About the file types, I am not sure that it is the reason. I renamed the example pdf file to .txt to make sure that nothing specific happens and I got the same issue. The copied file is corrupt. It's less about file types than about the content, which is strange.

If I open the (actually pdf) txt file directly in a text editor, from the mounted drive, I get the 
%PDF-1.3
header at the top.

![image](https://github.com/user-attachments/assets/85fa57a1-26bd-44bc-80f0-75ee16798608)

If I copy this file locally and then open it, the file is messed, the beginning is actually the middle data, and somewhere in the middle there are nulls to fill the file to its original size. Very strange.

![image](https://github.com/user-attachments/assets/3030157c-980f-489f-9c74-c40fe7b24b24)

This part can be found inside the original file : 
![image](https://github.com/user-attachments/assets/bb2c32b1-926e-4b38-865a-b258d56e192c)

If I delete the copy and copy again, I have a different content:
![image](https://github.com/user-attachments/assets/99b8853e-5964-46ac-b64d-0526ff1250cc)

I suspected my NAS (QNAP / QTS 5.1) at first but if I copy the same file using the UNC path, there is no problem so the SMB share works. 

I also disabled the antivirus program during the test.

It's more like some data inside the file would trigged the incorrect behavior of mirror, like retrieving the wrong data block, and only during a windows copy.

**Comment by Liryna** [comment]
> I also disabled the antivirus program during the test.

That often not enough to fully disable them. Do you have the possibility to do the test on a clean environment ?

Read and write are well tested and the description of the issue really makes me believe there is a third party corrupting the data.
You might be lucky to find which one by using [procmon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) and inspect the read callstack. It could show one of those present in your `fltmc filters` output

**Comment by Liryna** [comment]
Please do not hesitate to reopen if you have new information
