### ISSUE TITLE
Cryfs, Dokany and Win 11

### ISSUE THREAD

**Issue by realjench** [dokan-dev/dokany#1245]
Hi there.

As it's seems stuck, may you have idea on this issue with [cryfs](https://github.com/cryfs/cryfs/issues/474#issue-2479453297)? 

Thans :-)

**Comment by Liryna** [comment]
Hey @realjench , This is unfortunately not a Dokany related issue https://github.com/cryfs/cryfs/issues/474#issuecomment-2347378690 😢
