### ISSUE TITLE
File is getting deleted even when CreateFile and DeleteFile returns STATUS_ACCESS_DENIED

### ISSUE THREAD

**Issue by ajaykumargdr** [dokan-dev/dokany#1248]
# Environment
 * Windows version: Windows 11 Pro (23H2)
 * Processor architecture: x86
 * Dokany version: 2.2.0.1000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
We are trying to restrict deletion of file in some predefined cases. We tried returning `STATUSS_ACCESS_DENIED` from `DeleteFile` if the predefined condition are met. But later we got to know that `DeleteFile` is not getting called all the time when a file is getting deleted. So we also tried returning `STATUSS_ACCESS_DENIED` in `CreateFile` if `delete_on_close` is to true and predefined conditions met, but this also not preventing the file from getting deleted.
We also went thought the [Question about preventing dokan delete a file](https://github.com/dokan-dev/dokany/discussions/1146) discussion. We tried this fix but it didn't work for us.

**Comment by LTRData** [comment]
You need to check in CreateFile whether the file is opened for delete access and then return STATUS_ACCESS_DENIED there if deletion should not be granted.
