### ISSUE TITLE
fuse, fi->flags not set on release

### ISSUE THREAD

**Issue by usrecnik** [dokan-dev/dokany#1250]
# Environment
 * Windows version: Windows 11 (24H2, OS Build 26100.2033)
 * Processor architecture: x64
 * Dokany version: 2.2.0
 * Library type (Dokany/FUSE): FUSE
 
# Check List
  - [y] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [y] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [y] I can always reproduce the issue with the provided description below.
  - [y] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [n] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I'm working on [ddlfs](https://github.com/usrecnik/ddlfs) and I came across an issue for which I believe is likely a bug in dokan-fuse. I can also demonstrate the same behaviour using mirror sample (fusexmp.c). I have no issues on Linux using libfuse3 (this bug does not occur there).

Testcase is very simple: open any .txt file using notepad.exe and click Save. Observe what happens in open() and release() functions when "Save" operation is performed and take a close look on parameter `struct fuse_file_info *fi`, specifically `flags` member; `open()` call has corect `fi->flags` as `O_RDWR` while `release()` has no flags set. Therefore, on release, my filesystem cannot know if the file was previously open as read-only or as read-write.

Debug output of ddlfs, which displays value of `fi->flags` on open() and release():
```
2024-11-10 15:07:30 INFO  fuse-open: [/DDLFS/VIEW/MYVIEW.SQL], fi->flags=[2] (O_RDWR)
2024-11-10 15:07:30 INFO  fuse-write: [/DDLFS/VIEW/MYVIEW.SQL]
2024-11-10 15:07:30 INFO  fs_truncate() - [/DDLFS/VIEW/MYVIEW.SQL] to [97] bytes
2024-11-10 15:07:30 INFO  fuse-release: [/DDLFS/VIEW/MYVIEW.SQL], fi->flags=[0]
```

# mirror default sample

Check List wishes to verify what I'm describing using mirror default sample. I had some unrelated difficulties with this sample, but, the same behaviour appears there:

1. I've compiled it using cygwin (`gcc -Wall fusexmp.c -D_FILE_OFFSET_BITS=64 -I../../include/ -L../../ -ldokanfuse2 -lpthread  -o demo.exe`), and not like source of `fusexmp.c` suggest in the header (`gcc -Wall fusexmp.c `pkg-config fuse3 --cflags --libs` -o fusexmp`). The way it is documented in this file would only work on Linux I think. Besides, Dokan-fuse compatibility is with fuse v2, not with fuse v3 (right?).

2. I can run it via cygwin, like this: ` ./demo.exe -f X:`

3. I modified the fusexmp.c by adding two `printf()` calls, one to xmp_open() function, and the other to xmp_release() function. I get this output from those added `printf()` calls (I did *not* modify anything else):

```
xmp_open, path=[/home/test/test1.txt.txt], fi->flags=[2]
xmp_release, path=[/home/test/test1.txt.txt], fi->flags=[0]
```

**Comment by Liryna** [comment]
Hi @usrecnik ,

You are correct this wasn't supported. See this comment 
https://github.com/dokan-dev/dokany/blob/45021e00ec54e38b936620f339c8fb22c3f999d2/dokan_fuse/src/fusemain.cpp#L1201

I just pushed https://github.com/dokan-dev/dokany/commit/255e4a508b744996191d652af70d912c26c74f56 , could you give a try and let me know ?

**Comment by usrecnik** [comment]
tnx, yes, I get correct flags now on release with latest version.

**Comment by Liryna** [comment]
Thanks for reporting the issue and verifying! 🏆
