### ISSUE TITLE
Dokan Library 2.2.0.1000 Setup Failed

### ISSUE THREAD

**Issue by Metjuw** [dokan-dev/dokany#1254]
**Environment**

 * Windows version: **11**
 * Processor architecture: **x64**
 * Dokany version: **2.2.0.1000**
 * Library type (Dokany/FUSE): **Dokany Library Bundle**

**Description**

I downloaded the [Dokan_x64.msi](https://github.com/dokan-dev/dokany/releases/download/v2.2.0.1000/Dokan_x64.msi) and I was getting an error that the installation ended prematurely. So I checked on GitHub and saw that I had to install **Visual Studio** together with the **Windows 10 SDK** and the **WDK10** so I downloaded them and installed them respectively. I restarted my PC and tried the same installer but I got the same error.

I have also searched on Google for a fix and ended up trying the following:

- I checked that the Windows Installer Service is running
- Cleared the Temp folder,
- Re-registered the VBScript.dll and the Windows Installer Service
- Made sure that the .NET Framework 4.8 is on; and

- Also ran an SFC scan but to no avail

I downloaded the [DokanSetup.exe](https://github.com/dokan-dev/dokany/releases/download/v2.2.0.1000/DokanSetup.exe) and I'm getting the following error code "**0x80070643 - Fatal error during installation**" and I have also attached the log below for the error I'm getting.

Is there any way I can resolve this issue please?

**Log**

[Dokan_Library_2.2.0.1000_Bundle_20241209223346.log](https://github.com/user-attachments/files/18068416/Dokan_Library_2.2.0.1000_Bundle_20241209223346.log)
[Dokan_Library_2.2.0.1000_Bundle_20241209223346_000_Dokan_x64.msi.log](https://github.com/user-attachments/files/18079429/Dokan_Library_2.2.0.1000_Bundle_20241209223346_000_Dokan_x64.msi.log)
[Dokan_Library_2.2.0.1000_Bundle_20241209223354.elevated.log](https://github.com/user-attachments/files/18079431/Dokan_Library_2.2.0.1000_Bundle_20241209223354.elevated.log)

**Comment by Liryna** [comment]
Hi @Metjuw , Could you share all `C:\Users\cmfmf\AppData\Local\Temp\Dokan_Library_2.2.0.1000_Bundle_*` logs ?

**Comment by Metjuw** [comment]
> Hi @Metjuw , Could you share all `C:\Users\cmfmf\AppData\Local\Temp\Dokan_Library_2.2.0.1000_Bundle_*` logs ?

Sure I updated the Logs section of my original post and included the other two logs.

**Comment by Liryna** [comment]
```
The file C:\WINDOWS\System32\drivers\dokan2.sys is being held in use.
ExecuteInstall:  dokanctl output : "DokanServiceInstall: Service (Dokan2) is already installed
```
Seems like the driver was already installed. 

If you previously installed the driver manually, I would suggest downloading the zip file of the latest version, do `dokanctl /r d` with elevated permissions, reboot, remove `C:\WINDOWS\System32\drivers\dokan2.sys` and retry the installation.

**Comment by Metjuw** [comment]
Yes, that worked thank you for your assistance! 🙂

**Comment by WolfgangWenzel** [comment]
There is an entry in the registry but no sysfile in the windows folder. I have a project management system which tries to install the docan 1.3 bundle which crashed without any report.

**Comment by Liryna** [comment]
@WolfgangWenzel could you please open a new issue with Dokan installer logs ?
