### ISSUE TITLE
Change from 0.8.0 RC4 to Final breaks termination

### ISSUE THREAD

**Issue by js69** [dokan-dev/dokany#128]
Before I try to identify the responsible Dokan code myself, maybe somebody has the answer already. 

My application terminates gracefully (after Unmount etc) with the 0.8.0 RC4 driver installed while with the 0.8.0 Final driver something has changed and my app will just remain as an open process (all .NET assemblies unloaded after Environment.Exit()). 

Any quick ideas, do I need to change something in my app?

**Comment by Liryna** [comment]
https://github.com/dokan-dev/dokany/compare/v0.8.0-RC4...v0.8.0
Does Unmounted is called with 0.8.0 Final ?

**Comment by js69** [comment]
I apologize, the issue already exists in RC4, it works in RC3.

Unmounted callback was added in RC4 I understand, so no, it's not called (compiled with latest DokanNet).

**Comment by Liryna** [comment]
Surprising, can you try the C# sample ?

**Comment by js69** [comment]
I will. 

I found this difference RC3 to RC4:
: 
RC4 removes the case IRP_MJ_SHUTDOWN in dokan\dokan.c which had a comment in RC3:
// this case is used before unmount not shutdown

The VOID DispatchUnmount function was also removed.

Was that dead code or how was it replaced?

**Comment by js69** [comment]
The code from DispatchUnmount has been moved to DllMain case DLL_PROCESS_DETACH.

DllMain will apparently not be called when an apllication has been terminated via Enviroment.Exit (aka TerminateProcess WinAPI) or with the TaskManager.

There needs to be a cleanup for Unmount as it was before.

**Comment by Liryna** [comment]
@js69 DispatchUnmount was a dead code. 

So you say that process detach is never called with environment.exit? 

Otherwise even if unmounted is not called. I don't think it is the reason that you still get the process running.

**Comment by js69** [comment]
This issue I had was in correlation with a forced abortion of the thread that had the Dokan.Mount running. When I terminate the thread gracefully (which depended on Unmount actually ending the Dokan.Mount) and actually wait for the thread to end (which takes about 2 secs) before shutting down the application, it works nicely. But this is still a different behavior compared to RC3.

**Comment by Liryna** [comment]
Can you try to rebuild the dokan.dll, remove https://github.com/dokan-dev/dokany/blob/master/dokan/dokan.c#L659 and see if fix your issue ?

**Comment by Liryna** [comment]
I was able to reprocude it with the mirror
```
Mirror mirror = new Mirror("C:");

Thread workerThread = new Thread(() =>
{
	mirror.Mount("n:\\", DokanOptions.DebugMode, 5);
});

workerThread.Start();


Thread.Sleep(1000);
Environment.Exit(0);
```

**Comment by Liryna** [comment]
In C#, the object seems to no longer be here during DLL_PROCESS_DETACH.
I think this part of the code should be removed. Anyway if a application exit, is should clean the resource before.
