### ISSUE TITLE
Dealing with different Dokany dependencies

### ISSUE THREAD

**Issue by kriswebdev** [dokan-dev/dokany#129]
Note: I'm posting this issue here, but I'm not sure this is appropriate.

If I install Dokany 0.7.4, encfs4win reloaded (2.00) that currently relies on it works.

Then, if I install Paragon ExtFS (2.1.440), I get, while starting encfs4win reloaded with advanced debugging:
- "(src\docanfuse.cpp:490) Couldn't load DLL." if I don't do anything
- "failed to connect DokanMounter service: 2" if I add Dokany 0.7.4 DLL in the program dir.

I think Paragon ExtFS relies on Dokany 0.6 but I'm not sure (dokan.sys file doesn't mention the true Dokany verison). It also installs its own mounter service called "ParagonMounter".

So how to run apps that use different versions of Dokany ? Especially 0.6 vs 0.7.4 or 0.8.

Note: I am not able to force Dokany 0.7.4 reinstall above Paragon ExtFS as Dokany 0.7.4 will refuse to install as dokan.sys and DLL exist and are used. Also, even after uninstalling Paragon ExtFS, the old version of dokany wasn't properly uninstalled. This lead Dokany in a state where it couldn't be removed nor "clean" reinstalled. System32 DLL and driver sys files couldn't be deleted ("this file is used by another program"). I wasn't able to properly uninstall the old dokany version throuh any known method (dokanctl /r a, Device Manager, pnputil, rundll32 DefaultUninstall, etc). That's until I found, trough Process Explorer (Find "dokan"), that explorer.exe was using dokannp.dll. So I killed explorer.exe and deleted dokannp.dll through cmd, then I could delete dokan.dll and dokan.sys.

**Comment by Maxhy** [comment]
Indeed in case of dokannp, this can be run by explorer. The (un)installer should handle this case, maybe an update on the coming WiX-based installer.

About backward compatibility now. This is an interesting subject.
Dokany should be backward compatible from 0.6.0 to 0.7.4. In that case you should just have the latest version installed and both software (the one using 0.6.0 and the other one using 0.7.4) should work correctly.
Here the issue could come from Paragon ExtFS. I was aware of this product and checking it was on my TODO. Because of compatibility issue, because they are repackaging the mounter and all libraries, and because they are providing Win10 compatibility with signed drivers, _without source code_, I believe they could violate Dokan licenses.

Anyone from Paragon ExtFS watching this repo who could bring some details?
Otherwise I will contact them to ensure there is no mistake on license use.

**Comment by js69** [comment]
Could you please try and identify the registry entries that are created by Paragon for the Dokany driver in case they are different from Software\Microsoft\Windows\CurrentVersion\Uninstall\DokanLibrary?

We will be able to check with WiX for the presence of any existing driver and give a warning accordingly (i.e. "An obsolete version of the Dokan Library is still installed on this system. Please uninstall the existing Dokan Library before executing this setup again. Installing a newer Dokan driver might break compatibilty with applications relying on the older version.")

**Comment by Liryna** [comment]
:+1: @Maxhy, @js69

@Paragon-Software-Group, @SteamDragon, @feoff3, can you enlighten us if Paragon/dokan 0.6.0 is modified version of dokan 0.6.0 ?

**Comment by feoff3** [comment]
Hi there,

Unfortunately I'm not involved with to the dev of this piece of software.

**Comment by kriswebdev** [comment]
Thank you all for your replies.
Please find some additonal information about Paragon files/registry entries on [this pastebin](http://pastebin.com/raw/mG7Mpv5g).

Most important findings:
- Paragon is using a `system32\drivers\dokan.sys` signed by Paragon with its own copyrighted INF file. Version reported by Paragon embedded dokanctl is *"Dokan driver version : 0x190"*.
- Paragon is using a `SysWOW64\dokan.dll` probably built by Paragon, and that is not compatible with official Dokany 0.7.4 dokanctl and other official tools. Version reported by Paragon embedded dokanctl is *"Dokan version : 600"*. It differs from official DLL at least in that it has an additional `_DokanGlobalInit@4` function.
- Paragon Dokany files were built in August this year, thus they are necessarly based on Dokany < 0.8 that was released in October.
- Paragon has its own ParagonMounter service. It is unclear if it also uses DokanMounter service.
- Paragon is not using Dokany mounter binary. Instead, it has a dedicated extmounter.exe binary.

In conclusion, neither Paragon `dokan.dll` or Paragon `dokan.sys` are compatible with Dokany 0.7.4 and clearly cause conflicts with any software based on the official Dokany 0.7.4 builds as these files are put in place of the official ones.

But even if Paragon was using official 0.7.4 release SYS and DLL files, it would be incompatible with any app based on Dokany 0.8 as this new version breaks compatibility. And I want to upgrade my app to version 0.8, and still be able to use it along with other apps based on other Dokany versions.

My point is not to blame Paragon (except for their possible license infrigement), they certainly have good reasons to build their own Dokany SYS/DLL. Instead, I would like to find a way to have **several versions of Dokany cohabiting on the same system** (official dokany build or not, 0.7.4 vs 0.8...). I'm not a driver/service expert, but **how could we run a "dedicated instance" of Dokany driver & service for a particular app?**

**Comment by marinkobabic** [comment]
The dokan.sys must contain the version number as part of the file like dokan2.sys. Also the service name must contain the version number. The pipe name and other constant in the driver. The version resp. file name should be changed as soon as the backward compatibility is not guaranteed. 

Two versions should be able to coexist on the same machine. 

I was wondering why nobody raised this issue before.

**Comment by feoff3** [comment]
Hi everyone,


I’ll forward your requests to guys involved into Paragon dokan dev.


AFAIK dokan was used as a basic library for some Filesystem impl by Paragon. But it’s unknown what version is used and whether it’s being updated during the dev process.






From: Marinko
Sent: ‎Thursday‎, ‎December‎ ‎24‎, ‎2015 ‎1‎:‎47‎ ‎AM
To: dokan-dev/dokany
Cc: Vladimir Fedorov





The dokan.sys must contain the version number as part of the file like dokan2.sys. Also the service name must contain the version number. The pipe name and other constant in the driver. The version resp. file name should be changed as soon as the backward compatibility is not guaranteed. 

Two versions should be able to coexist on the same machine. 

I was wondering why nobody raised this issue before.

**Comment by andreyloktev** [comment]
Hi everyone,

dokan 0.6.0 is used in Paragon ExtFS.
Some changes were made in the dokan driver and the dokan library:
 library:
  - DokanGlobalInit was added to push mounter.exe work into a PragonMounter service
  - fixed "MirrortUnmount is not called"
 driver:
  - fixed "MirrortUnmount is not called"
  - fixed a file map read/write
  - fixed "Insufficient system resources exist to complete the request"
  - fixed file deletion on Win8

In the latest dokany release there are almost all fixes. So in the next Paragon ExtFS release we will try to use Dokany.

**Comment by Liryna** [comment]
Hi @andreyloktev, @feoff3 ,

Thank you for your answers ! 

It would be great that dokany get the improvement that you made.
I would be interesting to see the fix of "MirrortUnmount is not called". We have made some changes in the 0.8.0 but I think it can be improved.

About several versions of Dokany cohabiting on the same system, I agree with @marinkobabic.

So what we have to do (if everyone agree):
* Add version in dokan driver like dokan-0.8.sys (without minor version since major are used when compatibility is break)
* Move install folder Dokan\DokanLibrary to Dokan\DokanLibrary-{version}
* Add version to service name
* Add version to pipe name and other constant in the driver

I also question myself about dokannp.dll and dokan.dll in system32. Do we add version in the name also ?
Or even, does they really need to be there ? should we just not keep them in the install directory ? About dokan.dll, the software will anyway embedded his own dll no ?

**Comment by marinkobabic** [comment]
dokan.dll should be in the directory of the specific application. To make it obvious which version belong together I would suggest also here to have the version number in the filename. Then you have the full flexibility.

**Comment by Maxhy** [comment]
Concerning binary names, I also agree we should rename dll/driver with version number on filenames, but only major version number (dokan1.dll, dokan2.dll, ...). This means we should start to respect [Semantic Versioning](http://semver.org/).

Ok @andreyloktev @feoff3. I would also be interested to see your changes, could you share it somewhere? I don't want to rush you but remember that this is excepted by Dokan licenses. Thank you!

**Comment by Liryna** [comment]
If we move to semantic versioning, we should therefore move to a Dokan 1.0.0 at least.

**Comment by andreyloktev** [comment]
Hi @Maxhy @Liryna !
Dokan 0.6.0 with changes: https://drive.google.com/open?id=0BxgWEqB7RUd-Zl9nRU5OLW1UbFk
- MirrorUnmount is not called:
files: sys\device.c; dokan\dokan.c; IOCTL_DOKAN_UNMOUNT was added.
- Map read\write:
 as well as in the pull request #64

**Comment by Liryna** [comment]
Thank you a lot @andreyloktev !
We will look into your changes :+1: as we can

**Comment by js69** [comment]
We can easily add the generated version number to all file names. I would suggest using the same naming scheme for all files, dokan-x.y.sys, dokan-x.y.dll, dokannp-x.y.dll, dokanfuse-x.y.dll

**Comment by Liryna** [comment]
Great @js69 !
About using the same naming for all files, I agree for the dll but for the kernel, I think we should only use the MAJOR version.
MAJOR version is used when incompatible API changes. Therefore, it mean that a dokan-1.6.dll can work with dokan-1.sys. Or even if someone update the dokan sys, all application with the same major version will  continue to work.

**Comment by js69** [comment]
If backwards compatibiltiy of an updated dokanX.sys with applications built for an older Dokan revision of the same major version really is no issue, then I would agree. Else there will have to be many changes to the major version.

**Comment by Corillian** [comment]
I agree with @marinkobabic that it's probably best to require the client to ship the user-mode dll with the application. Forcing a single major version of the kernel driver however makes me nervous. In theory it shouldn't be a problem with a compatible API however there's no real way to guarantee that a new version of the kernel driver won't break existing applications. One possibility would be to have the kernel driver service operate as a lightweight version manager that loads a different dll for each version of the kernel mode driver. The user mode dll can specify the version of the kernel driver it's looking for during mounting. You could have a different kernel mode driver service for each major version and have the service load kernel dll's for each minor version or you could have one global service that handles all versions.

If the kernel driver service already exists and doesn't need to be updated installing a new kernel mode driver could be as simple as copying the new kernel mode dll. The kernel driver service could use a file system watcher to detect changes, verify the digital signature for any new driver dll's, and then load them.

I'm not super familiar with all of the kernel mounting logic so none this may be a good idea but it's a thought =).

**Comment by Liryna** [comment]
The service has been removed with the `mountmanager` feature https://github.com/dokan-dev/dokany/commit/c4a0ae2c8620cdbeeb4c6b0297e983d4eb7a711a https://github.com/dokan-dev/dokany/issues/50 

**Update**: So what we have to do (if everyone agree):
* We move to [Semantic Versioning](http://semver.org/) - Therefore dokan next release have to be 1.0.0
* Add MAJOR version in dokan driver like dokan-1.sys
* Move install folder Dokan\DokanLibrary to Dokan\DokanLibrary-{version}
* Do not install dokan.dll into system32 anymore - Application embedded there own dokan dll
* Add MAJOR version to pipe name and other constant in the driver
* Add version in dll dokan dokannp dokanfuse like dokan-1.0.0.dll

Using only MAJOR version of the driver and the pipe name, it will give the ability to an application using an older dokan.dll but same MAJOR version enjoy the driver fix. By simply installing the new dokan.

**Comment by Maxhy** [comment]
@andreyloktev, I reviewed your changes since Dokan 0.6.0.
With current Dokany state, your changes doesn't have any value except what you already submitted on PR #64 (which cannot be merged unfortunately because unstable/incomplete). Thank you for the license respect and source code publish!

**Comment by Corillian** [comment]
@Liryna yes but the kernel mode driver is still installed as a service. Presumably when a command to mount a filesystem comes from the user-mode DLL a version number could be supplied and the kernel driver could then attempt to load the corresponding kernel DLL (if it hasn't already been loaded).

**Comment by Liryna** [comment]
@Corillian Oh ok I see ! So yes the the MAJOR version has to be in the driver service name (added to my list). About your question with the communication between user-mode DLL and filesystem, they use `DOKAN_GLOBAL_DEVICE_NAME` to 'communicate'.

For exemple in the last commit I added the MAJOR version in the dll and kernel https://github.com/dokan-dev/dokany/commit/662cb4b68da175046fa74dacc94858ce295f11cf#diff-059764d049d447be862f6329b2c10bb7L31. It already mean that the new dokan.dll is no longer able to request a mount from the 0.8.0 dokan.sys.

**Comment by Liryna** [comment]
Version has been made here: https://github.com/dokan-dev/dokany/commit/78b94934eb6a9e1eaea7db358959fe8bb0473126

I would like some feedback about it (see if everything work for everyone, if some part can be improved...)

There is just the `dokannp.dll` that I didn't moved from system folder to the install folder.

**Comment by js69** [comment]
To test this with DokanNet, I only need to change the DllImport("dokan.dll") line in NativeMethods?

**Comment by Liryna** [comment]
Yes !
Or you can directly use the branch I made with the changes: https://github.com/dokan-dev/dokan-dotnet/tree/1.0.0

**Comment by jetwhiz** [comment]
Is it safe to assume 1.x is and will be keeping backwards compatibility with 0.8 then?  Migration from 0.8 to 1.x should be relatively trivial in that case?

**Comment by Liryna** [comment]
Yes, we will keep compatibility with 0.8.0 API.
You will just need to change dokan library link name from dokan.dll to dokan-1.dll and embedded it to your installer.

**Comment by Liryna** [comment]
Dokan is now able to be install beside Dokan legacy.
 https://github.com/dokan-dev/dokany/releases/tag/v1.0.0-RC1

Thanks all of you for your input/suggestion and moreover your help :heart: !

**Comment by Liryna** [comment]
We made the choice to remove it from system32 for forcing application to embedded the dll.
We have changed our mind and since there is no issue to have dlls in system32 when application embedded it. We are going to put them back in it and give the choice to the devs.
