### ISSUE TITLE
Copying empty folders returns error in Cmd and Total Commander

### ISSUE THREAD

**Issue by js69** [dokan-dev/dokany#131]
Tested with Dokan.Dotnet DokanNetMirror sample and latest Dokany.

Copying an empty folder from the mirror drive works with Explorer.

Trying to do the same action in Total Commander or in Cmd.exe returns an error "cannot find file" in 
cmd.exe and "cannot read path" in Total Commander (though the empty folder itself will be copied correctly).

"C:\EmptyTest" contains only an empty folder "EmptyDir". "c:\TestCopy" is an empty folder as well. N: is the mirror of C:

Testing with cmd.exe:

>C:\>xcopy C:\EmptyTest C:\TestCopy /S /E
>0 Datei(en) kopiert

>C:\>del c:\TestCopy\EmptyDir
>Möchten Sie "c:\TestCopy\EmptyDir\*" löschen (J/N)? j

>C:\>xcopy N:\EmptyTest C:\TestCopy /S /E
>Das System kann die angegebene Datei nicht finden.

I've traced everything I could think of and it doesn't seem to be caused by anything in DokanOperationProxy.cs or Mirror.cs but rather in the driver itself.

Copying folders with any number of files >0 in them works.

**Comment by Liryna** [comment]
hi @js69 ,

Have you made the test it with the C mirror also ?
C# mirror is kind of very simple so there could be some mistakes.

**Comment by js69** [comment]
It seems to work correctly with the C mirror.exe.

What operation would be the best candidate for the cause of the issue in DokanNetMirror?

**Comment by Liryna** [comment]
I have been able to reproduce the issue that you describe but didn't find the reason for now :cry: 
xcopy return a error but the copy has been made.

You can have the debug information by adding the stdoutput flag and set the thread to 1 (less flood)
```
mirror.Mount("n:\\", DokanOptions.DebugMode | DokanOptions.StderrOutput, 1);
```

**Comment by js69** [comment]
I think I found the cause: FindFiles did not return items for "." and ".." in my code and probably neither in DokanNetMirror.

**Comment by Liryna** [comment]
@js69 Yes I was thinking the same but had no time to do something that work. It would be nice if you can PR a fix for it ❤️

**Comment by Liryna** [comment]
You was right, adding "." and ".." fixed the problem for me.
Could you tell me it worked for you too ?

**Comment by js69** [comment]
It works now. I think the date info (CreationTime etc) for those items should be set to those of the current folder though.
