### ISSUE TITLE
Dokan has a dependency on KB2999226

### ISSUE THREAD

**Issue by Corillian** [dokan-dev/dokany#135]
Anything compiled with vs2015 and the Windows 10 SDK has a dependency on the Win10 Universal CRT. Unfortunately the vc2015 redist does not appear to install this and it needs to be checked for and installed by the installer: https://support.microsoft.com/en-us/kb/2999226#bookmark-prerequisites

I've verified that the 0.8.0 NSIS installer and all of the WiX installers will fail if this dependency isn't already installed. Given that there is a different .msu for every single OS it may be easier to check for and install this through Windows Update: https://msdn.microsoft.com/en-us/library/windows/desktop/aa386065(v=vs.85).aspx

#124,  #116, and #125 all need to take this into consideration.

**Comment by Liryna** [comment]
Oh thats interesting ! I was not aware of it!

Maybe this is even the reason why Dinesh Ramalingam had an issue to install 
https://groups.google.com/forum/#!topic/dokan/ngQOghks5g4

Therefore I agree with you, The next WiX installer should be able to check it.
`may be easier to check for and install this through Windows Update` Do you mean that WiX can launch the install of it from the Windows Update ?

**Comment by Corillian** [comment]
Yes that's exactly what Dinesh's problem was. As far as I'm aware WiX doesn't have built-in support for Windows Update but we could write a custom action for it. The one problem with using Windows Update is that most big companies tend to have Windows Update locked down and they control the installation of updates themselves. Thus I'm a bit torn as to whether or not it's better to include all of the different .msu's or use Windows Update.

Regardless I think we'll have to use the Windows Update API to detect if the update is currently installed or not.

**Comment by Liryna** [comment]
:+1: After WiX installer merged, we have to find a solution for it before releasing it.

I hope I get time to review js69 pull request this weekend. Since you have more knowledge in WiX than me :smiley: do you think to have time to take a look on it ?

**Comment by js69** [comment]
Wow, that's a quite heavy new requirement MS drops on everybody.

From my experience: never trust that Windows Update will do anything for you. In large networks it will be disabled by default respectively only admin-controlled updates are rolled out so many users might never see an update unless they manually force-install it.

I will implement the CRT update install as on demand download in the wxs just like we do it for the VC 2015 runtime, we already detect the OS anyway.

**Comment by Liryna** [comment]
Oh that would be great !!! :+1:

**Comment by js69** [comment]
OK, the msi files will show an error message if the UCRT is not installed:

"Installation failed because the Universal C Runtime is not installed. You can download it here: https://support.microsoft.com/en-us/kb/2999226"

The bundle is going to install the UCRT when it's not already present.

My check looks like this:

    <Property Id="UCRTINSTALLED">
      <DirectorySearch Id="searchSystem2" Path="[SystemFolder]" Depth="0">
        <FileSearch Id="UCRT_FileSearch"
                    Name="ucrtbase.dll"
                    MinVersion="10.0.10240.16389"/>
      </DirectorySearch>
    </Property>

**Comment by Liryna** [comment]
@js69 This seems to be correct according to microsoft information.

What is the size of the installer when everything is embedded ?

(your branch seems to not be updated :smiley: )

**Comment by js69** [comment]
My branch is updated now and KB2999226 should be installed by the Bootstrapper if it wasn't already (couldn't test it myself yet).

MSIs will show an error if UCRT (KB2999226 )is not installed.

**Comment by js69** [comment]
Updated my branch to fix bundle syntax.

I have now tested on a clean Win 8.1 image and found a new issue: KB2999226 will only allow to be installed when a certain Win 8.1 update level has been reached before, apparently to what was current in July 2015. I'll investigate further.

**Comment by js69** [comment]
MSI error text has been modified to show:

<CustomAction Id='CheckForUCRT' Error="Installation failed because the Universal C Runtime is not installed. Please run Windows Update and install all required Windows updates. You can download the UCRT separately from here: https://support.microsoft.com/en-us/kb/2999226" />

**Comment by Liryna** [comment]
I think this will be more simple yes :smile: Microsoft didn't make it well at all

**Comment by js69** [comment]
I have noticed the VC 2015 SP1 runtimes try to install KB2999226 already.

Dinesh Ramalingam was probably testing with the not-SP1 runtime, right?

**Comment by Liryna** [comment]
You mean Redistribuable Visual C++ from VC 2015 SP1 ?
We gave him the direct link so I think he had them.

**Comment by Liryna** [comment]
This has been made with @js69 WiX installer.
https://github.com/dokan-dev/dokany/commit/943a5d5c6551bc5085317c50d975bd8db55e73ac

It has not been heavily tested but 'should' work.

**Comment by Corillian** [comment]
Based on my current understanding commit https://github.com/dokan-dev/dokany/commit/943a5d5c6551bc5085317c50d975bd8db55e73ac has some errors surrounding its usage of `VersionNT`. Specifically `VersionNT` is an integer per Microsoft's documentation: https://msdn.microsoft.com/en-us/library/windows/desktop/aa372495(v=vs.85).aspx

It is used as such within both Dokan_x64.wxs and Dokan_x86.wxs however it is compared against a string in the format of `v6.x` within Bundle.wxs. My understanding of the code is that the UCRT MSU will never be installed because the VersionNT comparison in the condition will always fail. Looking at my own logs it appears that `VersionNT` is definitely being set to an integer.

**Comment by Liryna** [comment]
You seems to be right @Corillian 
http://wixtoolset.org/documentation/manual/v3/howtos/redistributables_and_install_checks/block_install_on_os.html

VersionNT is a interger and it should be changed.
https://msdn.microsoft.com/en-us/library/windows/desktop/aa370556%28v=vs.85%29.aspx

**Comment by js69** [comment]
Unfortunately the syntax and behavior of VersionNT in Bundles is different than it is for Products (and not or hardly at all documented) - you need the "v" in the Bundle. The code in the bundle is tested on a few VMs but it cannot hurt to verify on x86 specifically.

**Comment by CADbloke** [comment]
Thanks for posting this info, I have the same problem with an AutoCAD-based app. Your solution (thanks Google) is helpful. FYI if you have problems with installing a Windows Update on locked-down environments you can (conditionally, of course) install the runtime DLLs as an App-Local deployment. See https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/ part 6

A lot of my users machines are managed by [insert generic plural derogative term for BOFH] so I am going for the app-local deployment. My app is >300MB anyway. YMMV.

**Comment by archenroot** [comment]
@js69 I tried today latest bundle to install and the message on Windows 7 host was still referring to VC++ 2015 runtime missing, no more detailed message show.

**Comment by archenroot** [comment]
Even when installed the Windows6.1-KB2999226-x64 on my Windows 7 system I am still getting with 1.0.1.10000 Dokan (I tested with 1.0.2 as well):
`Installation failed because the VC++ 2015 x64 Runtime is not installed. You can download it here: https://www.visualstudio.com/downloads/download-visual-studio-vs#d-visual-c`

**Comment by Liryna** [comment]
@archenroot  What happen when you install VC++ 2015 x64 Runtime ? any error message ?

**Comment by Rondom** [comment]
@archenroot So, to summarize, the installer is working as it should (i.e. detecting what is missing and telling you to download the right things?)

**Comment by JokerQyou** [comment]
I've got the same problem as @archenroot. I downloaded Visual C++ 2015 x64 redist by searching throughout Microsoft website, the file version of the redis installer is `14.0.23026.0`. It finished without any error or warning but Dokan installer was still complaining about missing VC++ 2015 x64 runtime.

This was fixed by installing the `Microsoft Visual C++ 2015 Redistributable Update 3` (version 14.0.24215.1) package. However the requirement check for VC++ 2015 x86 runtime passed without installing an update.

**Comment by Liryna** [comment]
@JokerQyou This is strange because both check for x64 and x86 are the same about the version 
https://github.com/dokan-dev/dokany/blob/master/dokan_wix/Dokan_x86.wxs#L124
https://github.com/dokan-dev/dokany/blob/master/dokan_wix/Dokan_x64.wxs#L135-L136

**Comment by JokerQyou** [comment]
@Liryna Yeah I know that's strange. Seems like I forgot to mention, the machine I was testing on runs Windows 7 x64 system. Maybe the installer checked for both x86 and x64 of VC++ 2015 runtime, but only used the x64 one?
