### ISSUE TITLE
Cannot install 0.8.0 on Windows 10

### ISSUE THREAD

**Issue by MarkR1** [dokan-dev/dokany#142]
When I try to install 0.8.0 version I receive the message that previous version must be uninstalled first. I did have 0.6.0 version installed previously (when my pc was Win 7) I have since upgraded to windows 10 and have removed 0.6.0 (after Win 10 upgrade) but it seems it may not have uninstalled completely.  Are there any registry keys that I need to remove manually before the 0.8.0 install will succeed?

**Comment by Liryna** [comment]
Search for dokan.dll or dokan.sys in the system32.
I think you will find dokan.sys.

Remove it and it should be alright.

**Comment by MarkR1** [comment]
You are correct, this has solved the problem. Thank you :-)
