### ISSUE TITLE
dokan.zip missing for 1.0.0 beta

### ISSUE THREAD

**Issue by taruti** [dokan-dev/dokany#143]
Installing Dokan on 64 bit Windows skips installing the 32bit dokan.lib while installing both 32 and 64 bit dlls. The 32bit dokan.lib is needed for compiling 32bit versions of applications using Dokan. Previously it was available in the dokan.zip release, but that zip is missing from the 1.0.0 beta release page (https://github.com/dokan-dev/dokany/releases).

**Comment by Liryna** [comment]
Oh yes sorry I forgot it ><

Are you sure it is not in the Prog x68\Dokan\DokanLibrary\lib ?

**Comment by taruti** [comment]
Ah, it is installing in both \Prog and \Prog x86. Sorry to have bothered you and thanks for the help.
