### ISSUE TITLE
Read PDF from Dokan

### ISSUE THREAD

**Issue by acavalheiro** [dokan-dev/dokany#144]
Hi all,
First of all give my congratulations for this project.
I have tested the mirror sample for .net c# and i found that pdf cannot be read from microsoft edge for example.

I have made a small pdf reader for test this, and if a read all bytes of the file to a memory stream everything works.

But if a read a file directly from a filestream it hangs ups.

Thanks

**Comment by Liryna** [comment]
@acavalheiro Hi, 

This is a know issue, pdf reader work but edge have some issues. 

Could you share your test code? I will try to reproduce it and see what is happening. 

Otherwise did you test with the mirror C? Did it worked?

**Comment by acavalheiro** [comment]
Hi, with c mirror sample isnot working too.

Do you need the logs for my app, i have put log4net to log each call on dokan .net.

It seems a lot of call at getfileinformation.

**Comment by Liryna** [comment]
Logs would be great yes.
Or if you can provide a small code that reproduce ` read a file directly from a filestream it hangs ups.`. It would be great !

**Comment by acavalheiro** [comment]
Using Mirror Sample C#

[VirtualDrive.txt](https://github.com/dokan-dev/dokany/files/109532/VirtualDrive.txt)

Non Working code
` var file = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);`
use file to yours pdf viewer object and doesnt work

Working Code
`MemoryStream fileStream = new MemoryStream()
using (var file = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read))
file.CopyTo(fileStream) `

use filestream to your pdf viewer object and its work

**Comment by Liryna** [comment]
Just to be sure,

Do you say that an external software reading a file in dokan device with 
```
var file = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);
```
it will not work but with:
```
MemoryStream fileStream = new MemoryStream() using (var file = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read)) file.CopyTo(fileStream)
```

It will work ?

**Comment by acavalheiro** [comment]
yup, what i think is that memory stream reads all the bytes and put in memory that is no problem.

When using file stream all the call are made to dokan i think.

**Comment by Liryna** [comment]
@acavalheiro , I have tested you example with the C mirror and I get proper calls:

```
var file = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);
var buffer = new byte[10000];
int readed = file.Read(buffer, 0, 10000);
//readed = 10000
....
###Create 0011
CreateFile : C:\Users\liryna\Desktop\test\pdf\plaquette_de_presentation_sfa.pdf
  AccountName: liryna, DomainName: DESKTOP-RBPTIQA
        ShareMode = 0x1
        FILE_SHARE_READ
        AccessMode = 0x120089
        FILE_READ_DATA
        FILE_READ_ATTRIBUTES
        FILE_READ_EA
        READ_CONTROL
        SYNCHRONIZE
        STANDARD_RIGHTS_READ
        STANDARD_RIGHTS_WRITE
        STANDARD_RIGHTS_EXECUTE
        FlagsAndAttributes = 0x0
        OPEN_EXISTING

CreateFile status = 0 - lastError = 0
###Read 0011
ReadFile : C:\Users\liryna\Desktop\test\pdf\plaquette_de_presentation_sfa.pdf
        read 10000, offset 0
```

```
MemoryStream fileStream = new MemoryStream();
 using (var file = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read))
{
  file.CopyTo(fileStream);
}
// file.Length = 396315
....
###Create 0009
CreateFile : C:\Users\liryna\Desktop\test\pdf\plaquette_de_presentation_sfa.pdf
  AccountName: liryna, DomainName: DESKTOP-RBPTIQA
        ShareMode = 0x1
        FILE_SHARE_READ
        AccessMode = 0x120089
        FILE_READ_DATA
        FILE_READ_ATTRIBUTES
        FILE_READ_EA
        READ_CONTROL
        SYNCHRONIZE
        STANDARD_RIGHTS_READ
        STANDARD_RIGHTS_WRITE
        STANDARD_RIGHTS_EXECUTE
        FlagsAndAttributes = 0x0
        OPEN_EXISTING

CreateFile status = 0 - lastError = 0
###Read 0009
ReadFile : C:\Users\liryna\Desktop\test\pdf\plaquette_de_presentation_sfa.pdf
        read 81920, offset 0

###Read 0009
ReadFile : C:\Users\liryna\Desktop\test\pdf\plaquette_de_presentation_sfa.pdf
        read 81920, offset 81920

###Read 0009
ReadFile : C:\Users\liryna\Desktop\test\pdf\plaquette_de_presentation_sfa.pdf
        read 81920, offset 163840

###Read 0009
ReadFile : C:\Users\liryna\Desktop\test\pdf\plaquette_de_presentation_sfa.pdf
        read 81920, offset 245760

###Read 0009
ReadFile : C:\Users\liryna\Desktop\test\pdf\plaquette_de_presentation_sfa.pdf
        read 68635, offset 327680

###Read 0009
ReadFile : C:\Users\liryna\Desktop\test\pdf\plaquette_de_presentation_sfa.pdf
        read 0, offset 396315

###GetFileInfo 0009
GetFileInfo : C:\Users\liryna\Desktop\test\pdf\plaquette_de_presentation_sfa.pdf
        GetFileInformationByHandle success, file size = 396315
....
```

Could you give the full code of your test that fail in dokan Mirror ?

**Comment by Liryna** [comment]
Feel free to reopen if you have new informations.
