### ISSUE TITLE
File redirect

### ISSUE THREAD

**Issue by MarkR1** [dokan-dev/dokany#145]
Not sure if this is the most appropriate place to ask this so apologies if it isn't!...

Is it possible to redirect requests for files to a different target? By this I mean in the file explorer I display Document.pdf for example but when this file is opened the request actually calls a proxy exe of some kind that determines if the file is available locally (and if so executes it) and if not goes and gets the file from some remote store.  I feel like this is something that needs to be handled at a higher level but just wanted to check that I cannot achieve this functionality in the dokany driver.

**Comment by Liryna** [comment]
Hi @MarkR1 ,

It would question should be more in the dokan google group but I will answer it

Yes, this is possible but you will have to do it in your user land code (your proxy exe).
When you open Document.pdf in your dokan Virtual Device mounted by the 'proxy exe', you will get a request of ReadFile that request to fill a buffer with specific size.
This buffer can contain what ever you want, in your case it can be data that you got from local file or to a remote 

Does this answer your request ?

**Comment by MarkR1** [comment]
Not sure, that answers my question.  I'll give you the scenario.  I have successfully created my virtual device which creates a virtual folder and file structure based on a local cache (which is periodically updated from a remote server). Reading the meta data is not a problem it's when a user attempts to open a file that problems occur, especially when the file is large and it has to be retrieved from a remote source - I am often getting timeouts reading files that are several mb's.  My hopeful solution is to intercept the file explorer original request such that instead of Document.pdf being the target this is replaced with [get the file in some other process.exe] which then does the work to determine if the file exists locally and if it does simply executes it or displays a progress bar whilst it is being downloaded and ultimately display the file or display a user friendly failed/retry feedback. Does that make sense?

**Comment by Liryna** [comment]
Humm this behaviour of an external .exe is not possible as I know.

`I am often getting timeouts reading files that are several mb's.`
Did you try to use DokanResetTimeout during such request ?

**Comment by MarkR1** [comment]
Just to let you know I discovered that the actual cause of my timeouts was because I was attempting to call back into the file system during a file open call, this was causing the routine to block.  Fixed this and the files now download nicely :-)  Thanks for your assistance today, most appreciated.
