### ISSUE TITLE
GetVolumeInformation, GetDiskFreeSpace and  DokanOpenRequestorToken

### ISSUE THREAD

**Issue by taruti** [dokan-dev/dokany#146]
GetVolumeInformation and GetDiskFreeSpace can be called without CreateFile, thus checking permissions from them via DokanOpenRequestorToken would be nice. However this is not possible at the moment.

A solution for checking the requestor token before calling them or supporting DokanOpenRequestorToken would be very nice.

**Comment by Liryna** [comment]
IRP_MJ_QUERY_VOLUME_INFORMATION does not provide, like IRP_MJ_CREATE, a SecurityContext with user request information.

See https://github.com/dokan-dev/dokany/blob/master/sys/access.c#L86

**Comment by taruti** [comment]
Yes, I looked at access.c, but I'd like to deny other users access to those two (in addition to doing stuff in CreateFile) and it seems hard to do with the current API.

**Comment by Liryna** [comment]
I guess your goal is to totally hide the volume to some users. This have to be done in another way.
For now dokany mount the device in global for all the system, this should be done.

See TODO `Add option for normal user to mount device as Global`
https://github.com/dokan-dev/dokany/issues/45

Your request is kind of related to it.

**Comment by Liryna** [comment]
@taruti 

They are talking about it in the same time here:
https://github.com/dokan-dev/dokany/pull/141#issuecomment-177520984

**Comment by Rambalac** [comment]
@taruti You can try to get processId from Info and find whose that process is. But I have no idea what happen if SYSTEM get error on such requests. Maybe none of users see that drive at all.

**Comment by Liryna** [comment]
@taruti , there is now a new dokan option DOKAN_OPTION_CURRENT_SESSION
It make the device only available for the current session.
https://github.com/dokan-dev/dokany/commit/3083fdda2e04d8fc798a7d6cb9eafceafa8bdbaa

**Comment by taruti** [comment]
Thank you very much.
