### ISSUE TITLE
Using Lookaside Lists

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokany#148]
Use [LookasideList](https://msdn.microsoft.com/en-us/library/windows/hardware/ff565416%28v=vs.85%29.aspx)

Drivers that must allocate fixed-size buffers dynamically to perform on-demand I/O operations can use the ExXxxLookasideListEx or ExXxxLookasideList support routines. After such a driver initializes its lookaside list, the operating system will hold some number of dynamically allocated buffers of the given size in the driver's lookaside list, effectively reserving a set of reusable, fixed-size buffers for the driver. The format and contents of a driver's fixed-size buffers (also known as entries) in its lookaside list are driver-determined.

**Comment by Liryna** [comment]
Hi @marinkobabic ,

I am looking for changing the most `ExAllocatePool` in the kernel driver by LookasideList.
For now I have only found the struct `DokanCCB` and `DokanFCB` allocated every CreateFile.
https://github.com/dokan-dev/dokany/blob/4ec77fd4d4aa149910a02cd8d4b8c9b0daa92ceb/sys/create.c#L202
https://github.com/dokan-dev/dokany/blob/4ec77fd4d4aa149910a02cd8d4b8c9b0daa92ceb/sys/create.c#L30

Do you have any suggestion of `ExAllocatePool` that we should replace by LookasideList ?

**Comment by marinkobabic** [comment]
This two structs are exactly which should be replaced using Lookaside Lists.

**Comment by Liryna** [comment]
Thank you @marinkobabic :heart: 
It is done with https://github.com/dokan-dev/dokany/commit/26b9652e7b9435910227f0473bd6ca8cd28c99c3
