### ISSUE TITLE
Implement CreateFile SharedAccess

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokany#152]
Dokan should have a option to make the driver check the file sharedaccess request before forwarding the request to the library.
This will give the ability for the user to not implement his own checks.

See https://github.com/dokan-dev/dokany/issues/32
Begining of implementation https://github.com/marinkobabic/dokanx/commit/888bd0dd038279f166fbf0a91ff4cf1386d88beb

**Comment by Corillian** [comment]
Implementing this correctly under all circumstances in my own driver has proved quite frustrating as the documentation is not always clear under which circumstances a set of flags should be checked:

https://msdn.microsoft.com/en-us/library/windows/desktop/aa363874(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/hardware/aa364399(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/hardware/ff540466(v=vs.85).aspx

I suspect the best way to approach this will be to lookup how it's handled in Microsoft's driver examples such as FastFAT: https://github.com/Microsoft/Windows-driver-samples/tree/master/filesys/fastfat

**Comment by Maxhy** [comment]
In addition to @marinkobabic tests, latest oplock changes first attempted to also implement shared access. The code is currently partially implemented and commented, see https://github.com/dokan-dev/dokany/blob/master/sys/create.c#L829

**Comment by Liryna** [comment]
DokanCheckShareAccess has been fixed and enabled. It seems to work with issues but more testing should be done to be sure that all cases are handled.

**Comment by Liryna** [comment]
IFSTest ShareAccessTest pass 👍 all seems to be good !
