### ISSUE TITLE
unresolved external symbol: utf8_to_wchar_buf

### ISSUE THREAD

**Issue by Driim** [dokan-dev/dokany#156]
I am trying to port encfs4Win to dokany 0.8.0. 

encfs uses from utils.h:
- utf8_to_wchar_buf
- filetimeToUnixTime
- wchar_to_utf8_cstr

but they are no longer available

error LNK2001: unresolved external symbol "void __cdecl utf8_to_wchar_buf(char const *,wchar_t *,int)" (?utf8_to_wchar_buf@@YAXPBDPA_WH@Z)

**Comment by Liryna** [comment]
Hi @Driim ,

That's a good initiative !

This function exist into dokan_fuse but they don't seems to be exported.
Could you look with http://www.dependencywalker.com/ the exported fonctions ?

**Comment by Driim** [comment]
![dokan](https://cloud.githubusercontent.com/assets/1021338/12813894/1637a978-cb4c-11e5-9466-3602223c65ab.png)

**Comment by Driim** [comment]
Functions are not exported

**Comment by Liryna** [comment]
Ok thank you,

I am going to add this functions to the .def file. Is it alright for you ?
utf8_to_wchar_buf_old
utf8_to_wchar_buf
wchar_to_utf8_cstr

unixify
extract_file_name
extract_dir_name

unixTimeToFiletime
filetimeToUnixTime
is_filetime_set

**Comment by Driim** [comment]
Yes, allright! Thank you

**Comment by Liryna** [comment]
Done https://github.com/dokan-dev/dokany/commit/b16cb156b057c6f58537725e0116bbd4dc6ce0f6
But you will have to wait next beta for it :disappointed:
