### ISSUE TITLE
Beta setup - dokan-1.sys

### ISSUE THREAD

**Issue by marinkobabic** [dokan-dev/dokany#157]
Hi Liryna

You are going to change the setup, so that the c:\windows\system32\drivers\dokan-1.sys is installed instead of dokan.sys? This way multiple versions of driver can coexist on the same machine.

Thanks
Marinko

**Comment by Liryna** [comment]
Hi @marinkobabic ,

It is already the case in the NSIS installer but it is right that the changes was made after 1.0.0-BETA1.
https://github.com/dokan-dev/dokany/blob/master/dokan_install/install.nsi#L118

Next BETA are going to be with the NSIS changes or with WiX installer (both installer handle dokan-1.sys).
https://github.com/dokan-dev/dokany/pull/124

I am just waiting the the network driver mount fix (https://github.com/dokan-dev/dokany/pull/141#issuecomment-177953501) before releasing a second beta.

**Comment by marinkobabic** [comment]
Ok, Will check what is there going on :smile:
