### ISSUE TITLE
driver file name - suggestion

### ISSUE THREAD

**Issue by marinkobabic** [dokan-dev/dokany#159]
Hi Liryna

I would suggest to have the following file name **dokan1.sys** instead of **dokan-1.sys**. The reason is that the installation service name is **Dokan1**. This way it would be consistent.

Thanks
Marinko

**Comment by Liryna** [comment]
Hi @marinkobabic ,

I totally agree :smiley: : with you. It was a bad idea to put a `-`

Even in the dll, I never seen someone who was doing it.

I am going to remove it from every name later.

**Comment by marinkobabic** [comment]
Thanks a lot :smile: You can close this issue as soon as you have done the change.

**Comment by Maxhy** [comment]
:+1:

**Comment by Liryna** [comment]
Done with https://github.com/dokan-dev/dokany/commit/e9cd1d598707874357b12664cb45c4499a9426a6
