### ISSUE TITLE
there is a big proplem when explore .exe files with dokan

### ISSUE THREAD

**Issue by fenggeyeyin** [dokan-dev/dokany#161]
If there are .exe files exist in a folder , enter the folder and use windows explorer  to scoll up and down ,  the explorer will  initiate a “READ” operation to all the .exe files .  if the .exe file is in a big size   (for example: JDK installer .exe file or chrome installer .exe file)  , with continuing reading file content the explorer will become very slack, or might even  be shutdown.  How to solve this problem ?
(we use dokan with network so the reading speed is slow ,  ,just 5MB/s)

**Comment by Liryna** [comment]
Dokan logs are required here. See https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan

**Comment by shlatchz** [comment]
I assume that it happens because Microsoft Explorer is searching for the thumbnails in the folder.
I've experienced it too... 
When the thumbnails are saved, it doesn't read the *.exe files, until one of them is selected.

**Comment by Liryna** [comment]
I also think it is linked to https://github.com/dokan-dev/dokany/issues/154

**Comment by fenggeyeyin** [comment]
Hello, thanks for reply, but how to forbid or avoid this searching ?　
I also find the file reading is started when one of .exe files is just only selected(not executing) ,making explorer slack, i want to stop this.....
But i still need to keep the .exe file execute and copy functions are normal. So any good suggestion ? Thank you very much.

At 2016-02-10 01:26:42, "shlatchz" <notifications@github.com> wrote:


I assume that it happens because Microsoft Explorer is searching for the thumbnails in the folder.
I've experienced it too...
When the thumbnails are saved, it doesn't read the *.exe files, until one of them is selected.
