### ISSUE TITLE
Dokan 1.0-BETA driver conflict in Windows 10

### ISSUE THREAD

**Issue by infograb** [dokan-dev/dokany#168]
Dokan 1.0 driver renders useless Slysoft's Virtual CloneDrive v5.5.0.0 image mounter. No problem with Dokan 0.8.

after using "dokanctl /r d" and rebooting things are sorting out.

Can be done something about this?

**Comment by Maxhy** [comment]
And what about 1.0.0-RC1? I will give a try to Virtual CloneDrive later to see the behavior.

**Comment by infograb** [comment]
Hey I've missed RC1 :) Will check this out.

**Comment by infograb** [comment]
Thank you for pointing this out ;) my bad... "please Insert disk to the drive" problem with CloneDrive eliminated.
