### ISSUE TITLE
The directory name is invalid

### ISSUE THREAD

**Issue by marinkobabic** [dokan-dev/dokany#17]
I have modified the .net RegistoryFS sample the GetFileInformation method to return an information if the key ends with temp

              if (filename.EndsWith("TEMP"))
                {
                    fileinfo.Attributes = System.IO.FileAttributes.ReadOnly;
                    fileinfo.LastAccessTime = DateTime.Now;
                    fileinfo.LastWriteTime = DateTime.Now;
                    fileinfo.CreationTime = DateTime.Now;
                    return 0;
                }

Then I have executed the test and navigated to CurrentUser\Environment and made a double click on the TEMP entry. Windows 7 x64 brings up a message "The directory name is invalid"

Have you an idea why?

The whole example is build to return GetFileInformation only if it is a directory, otherwise it returns -1

**Comment by Maxhy** [comment]
What do you attempt to achieve?
I believe your changes was working (you can run in debug and set a breakpoint just for the test to be sure it is called). If *TEMP* isn't a RegistryKey the method `FindFiles` and `GetFileInformation` will fail.
