### ISSUE TITLE
Can't find dokan1.dll

### ISSUE THREAD

**Issue by shlatchz** [dokan-dev/dokany#170]
When I try running mirror.exe with the latest release, I get:

![image](https://cloud.githubusercontent.com/assets/4594463/13034028/8ec48148-d332-11e5-88b9-3ea0179e8e80.png)

**Comment by Liryna** [comment]
@shlatchz Dokan dll is no longer installed into the system. You need to copie it yourself. You will find it in the dokan install folder. 

But will probably just add it for the mirror for the last release. 

See release note.

**Comment by shlatchz** [comment]
I copied both dokan1.dll and dokanfuse1.dll to mirror's folder,
and now when I run:

    mirror.exe /s /d /o /r E:\Temp /l m

I get:

	RootDirectory: E:\Temp
	## Attempting to add SE_SECURITY_NAME privilege to process token ##
	  success: privilege already present
	Dokan: debug mode on
	Dokan: use stderr
	device opened
	mounted: m -> \Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}
	Mounted
	###Create 0000
	CreateFile : E:\Temp\System Volume Information\MountPointManagerRemoteDatabase
	  AccountName: SYSTEM, DomainName: NT AUTHORITY
			ShareMode = 0x0
			AccessMode = 0x12019f
			FILE_READ_DATA
			FILE_READ_ATTRIBUTES
			FILE_READ_EA
			READ_CONTROL
			FILE_WRITE_DATA
			FILE_WRITE_ATTRIBUTES
			FILE_WRITE_EA
			FILE_APPEND_DATA
			SYNCHRONIZE
			STANDARD_RIGHTS_READ
			STANDARD_RIGHTS_WRITE
			STANDARD_RIGHTS_EXECUTE
			FlagsAndAttributes = 0x86
			FILE_ATTRIBUTE_HIDDEN
			FILE_ATTRIBUTE_NORMAL
			FILE_ATTRIBUTE_SYSTEM
			OPEN_EXISTING
			error code = 3


	CreateFile status = 3221225530 - lastError = 3
	###Create 0001
	CreateFile : E:\Temp\$Extend\$Reparse:$R:$INDEX_ALLOCATION
	  AccountName: SYSTEM, DomainName: NT AUTHORITY
			ShareMode = 0x3
			FILE_SHARE_READ
			FILE_SHARE_WRITE
			AccessMode = 0x120089
			FILE_READ_DATA
			FILE_READ_ATTRIBUTES
			FILE_READ_EA
			READ_CONTROL
			SYNCHRONIZE
			STANDARD_RIGHTS_READ
			STANDARD_RIGHTS_WRITE
			STANDARD_RIGHTS_EXECUTE
			FlagsAndAttributes = 0x0
			OPEN_EXISTING
			error code = 3


	CreateFile status = 3221225530 - lastError = 3

and the drive doesn't show up.
When I press CTRL + C, mirror.exe crashes.

**Comment by Liryna** [comment]
I made the test on my side and it worked.

Could you check if you have the rights to user E:\Temp or even if it really exist ?
Is it the only one command that don't work for you ?

**Comment by shlatchz** [comment]
It worked with previous versions...
I've also tried a different path and it didn't work :\

**Comment by Liryna** [comment]
@shlatchz New mirror does not need administration rights be sure that your user have access to the folder.

**Comment by shlatchz** [comment]
Without admin rights, I get:

	## Attempting to add SE_SECURITY_NAME privilege to process token ##
	  failed: Unable to adjust token privileges: 1300
	Failed to add security privilege to process
			=> GetFileSecurity/SetFileSecurity may not work properly
			=> Please restart mirror sample with administrator rights to fix it

There is no path that works for me with mirror :/

**Comment by shlatchz** [comment]
Also, when I tried running my program with the new dokan,
the drives are mounted but I can't see them under my computer....
I also can't access them with writing "N:\" in the address bar.
The only way I can access them is programatically:

    Process.Start(diskLetter + @":\");

**Comment by Liryna** [comment]
If you kill explorer does it work ?

**Comment by shlatchz** [comment]
YES!!

**Comment by Liryna** [comment]
Humm...normally you should not get this behaviour.

Without the `/o` do you have the same behaviour ?

**Comment by shlatchz** [comment]
Yeah

**Comment by Liryna** [comment]
Ok, could you add some logs here:
https://github.com/dokan-dev/dokany/commit/bfc57e716d76ea7c694a64b1ea7d2b67231a436a#diff-08219a05f4fe629d8ee8975f81ac9012R434

And see if everything is working well ?
(this part of code is made to notify explorer for arrival of new device)

**Comment by Liryna** [comment]
@shlatchz , there was a fix after the release of RC1 that could help your issue.
Can you rebuild the dokan.dll yourself and try with it ?

If not, we will needs logs as requested in my last message

**Comment by Liryna** [comment]
@shlatchz can you try with one of this installer:
https://drive.google.com/folderview?id=0B3E9tU82h-RMMmh3RkJFamM4WTA&usp=sharing

Remove previous dokan-1.0.0 RC1 before installing it
