### ISSUE TITLE
Move dokannp.dll to Dokan Library install folder

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokany#171]
`dokannp.dll` is now installed in the system32 folder.
There is not reason for him to be there. It should be move in the install folder.
`dokanctl.exe` has to be changed to fit the changed (since it is him who install dokannp into the registry).

**Comment by Liryna** [comment]
Done with https://github.com/dokan-dev/dokany/commit/e4ad8dcfcec858e8e934e698fc016569340eae5c

**Comment by sm4rk0** [comment]
I had various versions of dokan installed and figured out that there were still old versions of dokan.dll and dokannp.dll in system32 and sysWOW64 directories and some processes were using it (checked with Process Explorer). Can this cause an error? Can the new installer clean this up upon installation?

**Comment by Liryna** [comment]
Normally old installer should cleanup the dokannp (or it was bugged 😢 )

I don't think we should clean it in the new installer because this would mean to detect with older version is installed / used and if there is remaining files.

If fill that this is mandatory, contributions are very appreciated and I would be glad to help you on this 👍

**Comment by sm4rk0** [comment]
I don't feel it's mandatory. Just wanted to avoid some potential problems that would be hard to debug.
Thank you for prompt answer!

**Comment by Rondom** [comment]
Dokan 1.x.y uses dokannp1.dll, so this may hopefully avoid any conflicts.
