### ISSUE TITLE
add dokan.inf to sys project

### ISSUE THREAD

**Issue by marinkobabic** [dokan-dev/dokany#172]
Hi Liryna

Is there any reason to not add the dokan.inf to the project sys, Driver Files?

If you would add the file to the Driver Files:

- Visual Studio would set the version number automatically for you depending on the project settings stampinf section
- The dokan1.cat file would be created and would be signed automatically

The benefit of doing it is to have the three files **dokan1.sys**, **dokan1.inf** and **dokan1.cat** like all the other drivers. Using this files the integration into installshield is quite simple. You have no drawbacks when doing it.

Thanks
Marinko

**Comment by Liryna** [comment]
Hi @marinkobabic,

There is no reasons , I just never tought about it :smiley: 

This would be interesting for handling the version automatically !
About signing, we sign the binary ourself with the bat script in the repository.

Does the .cat is really usefull ? we are using `Driver` directive of WiX
http://wixtoolset.org/documentation/manual/v3/xsd/difxapp/driver.html

**Comment by marinkobabic** [comment]
This is standard when doing the stuff in Installshield. If you set the settings in a proper way in visual studio (two properties) then visual studio does the signing for you. No batch required. When I was working with dokanx project, then I also used to work with a batch file. Now with visual studio it's quite simple. Project Properties -> Driver Signing ->

- Cross-Signing Certificate
- Production Certificate

and the job is done :smile: . The cat file will be created automatically, not additional settings needed. All you have to do is to specify the name of the cat file in the dokan.inf, which is a must setting.

**Comment by Liryna** [comment]
Hi @marinkobabic ,

I have add the .inf in the solution as you told.
https://github.com/dokan-dev/dokany/commit/9dec989f43a12c062514d4d14b9445792241cb8e

Now visual studio correctly set the version automatically.
The installer now also embedded the .inf and .cat even if I have not found now how to use them with WiX for installing them.

About signing, the visual studio configuration is only local and it is impossible to cross sign sha1/sha2...so I think I will keep my sign script for now :smiley:

**Comment by Liryna** [comment]
Done with https://github.com/dokan-dev/dokany/commit/a9e0cff1be23258aff49bf5025421ea8c1da56d3
