### ISSUE TITLE
Installer always shows "Uninstall"

### ISSUE THREAD

**Issue by g3gg0** [dokan-dev/dokany#173]
had a weird behavior of the un-/installer after using the debug build version.

__procedure__
had 1.0-beta installed
installed 1.0-rc-debug
realized that the old code wasnt uninstalled automatically and may cause trouble
uninstalled 1.0-beta
rebooted

tried mirror.exe -> works
tried fuse code (MLVFS) -> fuse_main_real returns 1, no debug output
uninstalled 1.0-rc-debug
rebooted
ran installer for 1.0-rc -> installer only allows to uninstall
ran installer for 1.0-rc -> installer only allows to uninstall
[...]
ran installer for 1.0-rc -> installer only allows to uninstall
rebooted -> still installer only allows to uninstall

manually deleted ProgramFiles folders -> still only allows uninstall
manually deleted HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Dependencies\{5F030BFA-CE6E-408A-9694-F593B319DBBE}
ran installer for 1.0-rc -> installer only allows to uninstall
ran installer for 1.0-rc -> installer suddenly allows installation ?!
no files installed though

**Comment by g3gg0** [comment]
checking control panel shows two installations of "Dokan Library 1.0.0 Bundle".
trying to get rid of them...

**Comment by Liryna** [comment]
This happen because all installer of this release have the same GUID.
When you run the dbg installer, he think that he is already installed kind of.

We can create 4 GUID for normal/Dbg with and without redist installer.

https://github.com/dokan-dev/dokany/blob/master/dokan_wix/version.xml

**Comment by Corillian** [comment]
Doesn't 1.0 Beta1 still use the older installer? If so you cannot install 1.0 RC1 on top of it (or any prior version for that matter) because they use completely different installation engines. If this is the case the 1.0 RC1 should have caught that an older version was installed and returned an error code.

**Comment by Liryna** [comment]
1.0 RC1 look if dokan1.sys is present in system32/drivers. To be sure that there is no other dokan installation with the same API already installed.

1.0 beta1 still had the driver named dokan.sys so it has not been detected here.

**Comment by Liryna** [comment]
Fixed with https://github.com/dokan-dev/dokany/pull/188 by @js69 !
