### ISSUE TITLE
Missing x86 .lib files when installing on x64 machine

### ISSUE THREAD

**Issue by g3gg0** [dokan-dev/dokany#174]
Previously the x86 .lib's were in ProgramFiles(x86), so i could use those to build a x86 tool that uses dokan.
With the new installer, dokan is installed in ProgramFiles and only comes with x86 .dll's, but no x86 .lib's.

Here some compiler-output when using the x64 .lib's (no surprise here)
```
1>main.obj : error LNK2019: unresolved external symbol _fuse_opt_parse referenced in function _main
1>     1>
1>main.obj : error LNK2019: unresolved external symbol _fuse_opt_free_args referenced in function _main
1>     1>
1>main.obj : error LNK2019: unresolved external symbol _fuse_main_real referenced in function _main
1>     1>
1>C:\Program Files\Dokan\Dokan Library-1.0.0\lib\dokanfuse1.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'X86'
1>     1>
1>D:\cygwin\home\g3gg0\git\mlvfs\mlvfs\dokany\Debug\mlvfs.exe : fatal error LNK1120: 3 unresolved externals
1>
```

**Comment by Liryna** [comment]
You are right @g3gg0 

x86 library was missing from the installer x64.

This has been added with https://github.com/dokan-dev/dokany/commit/18c344b88bcb679934b1c264a3795645d35f774d

Could you try with one of the installer if you have any issues ?
https://drive.google.com/folderview?id=0B3E9tU82h-RMMmh3RkJFamM4WTA&usp=sharing

**Comment by Driim** [comment]
I try Dbg version and it works fine.

**Comment by g3gg0** [comment]
i just installed the version of DokanSetup.exe you posted on drive.
installed it "over" the existing installation.
didnt work properly (because due to GUID mixup i guess)

after deinstalling through control panel and resinstalling -> all is fine

thanks!

**Comment by Liryna** [comment]
@Driim and @g3gg0 thank you for your feedback :+1: 

About GUID issue, something has to be found but I have no idea for now.
Because even if it has the same GUID, I think it should have propose you to remove and not to install over :(

**Comment by js69** [comment]
Liryna, I'll commit a tool end of this week to automatically increase the product codes.

For MSIs though to avoid update problems we would also ideally have an always increasing revision number, i.e. 1.0.0.x where x < 65536. Is there an easy way to retrieve the git revision number?

**Comment by g3gg0** [comment]
i dont know of an easy way. but i am using a VS custom rule that will fill a AssemblyInfo.cs.intermediate

might also help: http://nowfromhome.com/msbuild-add-git-commit-hash-to-assemblyinfo/
