### ISSUE TITLE
dokanfuse1.dll loading dokan.dll

### ISSUE THREAD

**Issue by g3gg0** [dokan-dev/dokany#175]
hi,

our MLVFS didn't work anymore with the latest dokan version.
debugging the x64 assembly with IDA etc, i figured out that the delivered
"dokanfuse1.dll" is trying to load "dokan.dll" and failing - because the DLL is named "dokan1.dll"

```
.text:0000000180004130 sub_180004130   proc near               ; CODE XREF: sub_1800038F0+14Ap
.text:0000000180004130                                         ; fuse_unmount+7Ap
.text:0000000180004130                                         ; DATA XREF: ...
.text:0000000180004130                 push    rbx
.text:0000000180004132                 sub     rsp, 20h
.text:0000000180004136                 mov     rbx, rcx
.text:0000000180004139                 lea     rcx, LibFileName ; "dokan.dll"
.text:0000000180004140                 call    cs:LoadLibraryW
.text:0000000180004146                 mov     [rbx+38h], rax
.text:000000018000414A                 test    rax, rax

```

guess you should also update https://github.com/dokan-dev/dokany/blob/master/dokan_fuse/include/docanfuse.h  ;)

BR,
g3gg0

**Comment by Liryna** [comment]
Hi @g3gg0 

Well found ! :disappointed: How could I missed it.

Fixed with https://github.com/dokan-dev/dokany/commit/3a7f0c1c450523aa67587799db86a208f1fe979e

Thank you !

**Comment by g3gg0** [comment]
thank *you*

**Comment by AquiloSpiritus** [comment]
I'm afraid it happened again
