### ISSUE TITLE
Disk not visible in explorer but accessible in cmd (dos)

### ISSUE THREAD

**Issue by Goster** [dokan-dev/dokany#177]
Dokany 1.0.0-RC1 + Win 7 prof

>dokanctl.exe /v
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
dokanctl : Feb 13 2016 10:23:23
Dokan version : 100
Dokan driver version : 0x190

I run following command in cmd: "mirror.exe /r c:\ /l m". This command don't exit and just hangs (prompt doesn't return). In cmd I can change drive to "m:" and I see my files there. But in windows explorer I don't see any new drive and I can't type path "m:" into explorer bar because I get error that such a path doesn't exist.

When I run:
>mirror.exe /r c:\ /l m /d /s
then I get:
## Attempting to add SE_SECURITY_NAME privilege to process token ##
  success: privilege already present
Dokan: debug mode on
Dokan: use stderr
device opened
mounted: m -> \Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}
Mounted

**Comment by Liryna** [comment]
Hi @Goster ,

Could you remove the dokan 1.0.0-RC1 you have installed and try with 
https://drive.google.com/folderview?id=0B3E9tU82h-RMMmh3RkJFamM4WTA&usp=sharing
to see if there is a difference.

**Comment by Goster** [comment]
Unfortunately there is no difference. Still no disc in win expl

>mirror.exe /r c:\ /l m /d /s
## Attempting to add SE_SECURITY_NAME privilege to process token ##
  success: privilege already present
Dokan: debug mode on
Dokan: use stderr
device opened
mounted: m -> \Volume{d6cc17c5-1737-4085-bce7-964f1e9f5de9}
Mounted
###QueryVolumeInfo -001

**Comment by Liryna** [comment]
Ok, could you add some logs here:
https://github.com/dokan-dev/dokany/commit/bfc57e716d76ea7c694a64b1ea7d2b67231a436a#diff-08219a05f4fe629d8ee8975f81ac9012R434
and here:
https://github.com/dokan-dev/dokany/commit/bfc57e716d76ea7c694a64b1ea7d2b67231a436a#diff-08219a05f4fe629d8ee8975f81ac9012R474

(this part of code is made to notify explorer for arrival of new device)

**Comment by Maxhy** [comment]
Looks like the mount point is not mounted globally, which shouldn't be the case as `/c` is not in argument list. Could you try to run mirror.exe without elevated privileges?

**Comment by Matroschker** [comment]
The same error in my test with "mirror.exe /r c:\temp /l m /d /s"

C:\Program Files\Dokan\Dokan Library-1.0.0>dokanctl /v
Driver path: 'C:\WINDOWS\system32\drivers\dokan1.sys'
dokanctl : Feb 13 2016 10:23:23
Dokan version : 100
Dokan driver version : 0x190

...on Win 10 Pro

**with Administrator permission:**
it hangs and if I try to open drive z (I could see drive z in win expl) my whole Windows crashed

**without Administrator permission:**
## Attempting to add SE_SECURITY_NAME privilege to process token ##
  failed: Unable to adjust token privileges: 1300
Failed to add security privilege to process
        => GetFileSecurity/SetFileSecurity may not work properly
        => Please restart mirror sample with administrator rights to fix it
Dokan: debug mode on
Dokan: use stderr
device opened
mounted: Z -> \Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}
Mounted
Ioctl failed for wait with code 1.
Thread will be terminated
Ioctl failed for wait with code 1.
Thread will be terminated
Ioctl failed for wait with code 1.
Thread will be terminated
Ioctl failed for wait with code 1.
Thread will be terminated
Ioctl failed for wait with code 1.
Thread will be terminated
Unmounted

unload
Success

**Comment by Liryna** [comment]
Hi @Matroschker ,

Could you try with network option:
`mirror.exe /r c:\temp /l m /d /s /n`

**Comment by Goster** [comment]
@Maxhy 
> Could you try to run mirror.exe without elevated privileges?

Still no effect. Disc visible in cmd but no in explorer:

dokanctl.exe /v
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
dokanctl : Feb 16 2016 13:29:30
Dokan version : 100
Dokan driver version : 0x190

mirror.exe /r c:\ /l m /d /s
## Attempting to add SE_SECURITY_NAME privilege to process token ##
  failed: Unable to adjust token privileges: 1300
Failed to add security privilege to process
        => GetFileSecurity/SetFileSecurity may not work properly
        => Please restart mirror sample with administrator rights to fix it
Dokan: debug mode on
Dokan: use stderr
device opened
mounted: m -> \Volume{d6cc17c5-1730-4085-bce7-964f1e9f5de9}
Mounted

C:\> m:
M:\>

----
@Liryna 
> Could you test it with network option:

The same here - no effect ;-(

mirror.exe /r c:\temp /l m /d /s /n
## Attempting to add SE_SECURITY_NAME privilege to process token ##
  success: privilege already present
Dokan: debug mode on
Dokan: use stderr
device opened
mounted: m -> \DokanRedirector1{d6cc17c5-1732-4085-bce7-964f1e9f5de9}
Mounted

**Comment by taruti** [comment]
Can also confirm this with 1.0.0-RC1, perhaps this is the same as #138?

**Comment by Liryna** [comment]
@Matroschker your issue seems to be different than other people.
Could you test this version https://drive.google.com/folderview?id=0B3E9tU82h-RMMmh3RkJFamM4WTA&usp=sharing see if it fix your issue.

@taruti , what OS are you using ?
@Goster , I will try to make the test on Win7 also

**Comment by taruti** [comment]
@Liryna 

Tested with two Windows 7 x64 machines. One had previous Dokan versions and the other had never had a Dokan installation before (thus not a conflict caused by an older version). Using the 1.0.0-RC1.

Looks superficially like the same issue as in #134 (which includes logs).

After running `mirror.exe /r C:\ /l n /d /s`:
* cmd.exe browsing N: works
* explorer does not see N:
* killing explorer makes explorer see N:
* /n, /m, or /o don't fix it
* the same issue is present in other filesystems besides mirror.exe

**Comment by Liryna** [comment]
I have not been able to reproduce the issue.

We need kernel logs here https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#enable-logs

**Comment by taruti** [comment]
Here are some logs:

From mirror.exe runs first `mirror.exe /d /s /r C:\q /l q` and then `mirror.exe /d /s /r C:\q /l q /o`. Both dbgview and stderr. Windows 7 x64 DokanSetupDbg_redist.exe 1.0.0-RC1 (sha1 2539aef28cffccbbf5ba4a395aa374d0f5fc4926).

[mirror.dsrl.dbgview.log.txt](https://github.com/dokan-dev/dokany/files/150758/mirror.dsrl.dbgview.log.txt)
[mirror.dsrl.stderr.log.txt](https://github.com/dokan-dev/dokany/files/150760/mirror.dsrl.stderr.log.txt)
[mirror.dsrlo.dbgview.log.txt](https://github.com/dokan-dev/dokany/files/150759/mirror.dsrlo.dbgview.log.txt)
[mirror.dsrlo.stderr.log.txt](https://github.com/dokan-dev/dokany/files/150761/mirror.dsrlo.stderr.log.txt)

**Comment by Liryna** [comment]
Thank you @taruti for the logs !

It seems that now it request a storage query property that we do not handle.
```
[DokanFS]   IOCTL_STORAGE_QUERY_PROPERTY
[DokanFS]     PropertyStandardQuery Unknown
```
The PropertyStandardQuery requested is `StorageAccessAlignmentProperty`.

I don't know if this request is the source of the issue unfortunatly :cry: 
@marinkobabic , what do you think about it ?

**Comment by marinkobabic** [comment]
I think we should check the result of Send MessageTimout and if 0 log the GetLastError 

https://github.com/dokan-dev/dokany/blob/b1011c50f2332171f8b3495534fb2ea6c80db661/dokan/mount.c#L442-443

I'm sure that in some cases the last error will be access denied. But let's add the check as first and then analyze the log output.

**Comment by taruti** [comment]
Btw the code in mount.c (referenced from the previous comment):
```
	  ZeroMemory(&hdr, sizeof(DEV_BROADCAST_VOLUME));
	  hdr.dbcv_devicetype = DBT_DEVTYP_VOLUME;
	  hdr.dbcv_flags &= DBTF_MEDIA;
```
1) First we zero out whole hdr
2) set dbcv_devicetype
3) `&=` dbcv_flags, except that it is zero, and thus the end result is zero too?

**Comment by marinkobabic** [comment]
You are right taruti. The code should look like 
hdr.dbcv_size = sizeof(DEV_BROADCAST_VOLUME);
hdr.dbcv_devicetype = DBT_DEVTYP_VOLUME;
hdr.dbcv_reserved = 0;
hdr.dbcv_flags = DBTF_MEDIA;
hdr.dbcv_unitmask |=(1 << (MountPoint[0] - L'A'));

@Liryna 
In my previous comment I said that we will get access denied. Maybe we are returning access denied by not handling properly the request mentioned by you.

Let's see how the log looks like after the changes above.

**Comment by Liryna** [comment]
@taruti @marinkobabic here is a release with your changes https://github.com/dokan-dev/dokany/commit/e370ff8196a521c8fc56e71f5ec32d5655fe82cc
https://drive.google.com/folderview?id=0B3E9tU82h-RMMmh3RkJFamM4WTA&usp=sharing

If people who faced the issue could test and bring the log in case of failure it would be great :+1:

**Comment by Liryna** [comment]
I still face the issue with my win 7 :disappointed: 

Kernel logs at mount:
http://pastebin.com/jGyPSZUY
Kernel logs when try to acces it:
http://pastebin.com/x7HG2eqA
Mirror logs:
http://pastebin.com/5BXB5SGX

Kernel logs after explorer reboot and access succeed:
http://pastebin.com/qudV5F4e
Mirror logs:
http://pastebin.com/brJKuw1S

**Comment by marinkobabic** [comment]
We can try to do broadcast like the following one:

```C

static void VfdBroadcastLink(
	CHAR			cLetter,
	BOOL			bRemoved)
{
	DWORD			receipients;
	DWORD			device_event;
	DEV_BROADCAST_VOLUME params;

	if (!isalpha(cLetter)) {
		VFDTRACE(0,
			("VfdBroadcastLink: invalid parameter"))
		return;
	}

	receipients = BSM_APPLICATIONS;

	device_event = bRemoved ?
		DBT_DEVICEREMOVECOMPLETE : DBT_DEVICEARRIVAL;

	ZeroMemory(&params, sizeof(params));

	params.dbcv_size		= sizeof(params);
	params.dbcv_devicetype	= DBT_DEVTYP_VOLUME;
	params.dbcv_reserved	= 0;
	params.dbcv_unitmask	= (1 << (toupper(cLetter) - 'A'));
	params.dbcv_flags		= 0;

	if (BroadcastSystemMessage(
		BSF_NOHANG | BSF_FORCEIFHUNG | BSF_NOTIMEOUTIFNOTHUNG,
		&receipients,
		WM_DEVICECHANGE,
		device_event,
		(LPARAM)&params) <= 0) {

		VFDTRACE(0,
			("VfdBroadcastLink: BroadcastSystemMessage - %s",
			SystemMessage(GetLastError())));
	}
}
```

**Comment by Liryna** [comment]
We got something here @marinkobabic ! :trophy: 

At first, I tried with uppercase ... it does not change the issue.

So I tested `VfdBroadcastLink` and it worked !!!
I also added SHChangeNotify since I have not found if BroadcastSystemMessage does the SHChangeNotify job: https://github.com/dokan-dev/dokany/commit/c7a7a0d5401ff1751a879e3dfb5145092e14d90f

Also `BroadcastSystemMessage` use `BSM_APPLICATIONS`, do you think it is enough or `BSM_ALLCOMPONENTS` should be use ?
https://msdn.microsoft.com/en-us/library/windows/desktop/ms644952%28v=vs.85%29.aspx


I made a new release. if @taruti @Goster @Matroschker could test it and give a feedback it would be nice !
https://drive.google.com/drive/folders/0B3E9tU82h-RMMmh3RkJFamM4WTA

**Comment by taruti** [comment]
That google drive link appears not to work unlike the previous ones. Asks for login and then has an error.

**Comment by Liryna** [comment]
Fixed :disappointed:

**Comment by taruti** [comment]
This makes the drive appear in explorer for me! Fixed for my test machines.

**Comment by marinkobabic** [comment]
@Liryna Let's see what the results are and what  the guys say which have reported the issue. Did you test it with the current session mount flag?

Just to let you know. The original code for the broadcast camed from here https://sourceforge.net/projects/vfd/?source=typ_redirect

**Comment by Liryna** [comment]
@marinkobabic I just made the test and with current session mount flag it does not work :cry:

**Comment by marinkobabic** [comment]
@Liryna This is what I expected. In my opinion if this flag is used and mount manager is not used  we should execute DefineDosDevice in dokan user Library. 

@Maxhy What do you think?

**Comment by Goster** [comment]
> I made a new release. if @taruti @Goster @Matroschker could test it and give a feedback it would be nice !
> https://drive.google.com/folderview?id=0B3E9tU82h-RMMmh3RkJFamM4WTA&usp=sharing

I tested this build with dimov-cz/win-sshfs 1.6.0 RC2 and mounting and unmounting ssh disk now works ;-)

**Comment by forkineye** [comment]
As a workaround with 1.0.0 RC-1, restarting explorer.exe will make the mount accessible.

**Comment by Matroschker** [comment]
I tested again the last version (https://drive.google.com/folderview?id=0B3E9tU82h-RMMmh3RkJFamM4WTA&usp=sharing) on Win10 Pro with and without administrator privileges, but in both cases my Windows crashes.
This was my call: mirror.exe /r c:\temp /l m /d /s /n

**Comment by Liryna** [comment]
Hi @Matroschker ,

Could you create another issue with dokan logs (Mirror & Kernel logs from Dbg build `DokanSetupDbg.exe`).
https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#enable-logs

Thank you in advance,

**Comment by Maxhy** [comment]
@marinkobabic I tend to agree with you and DefineDosDevice should be run in user mode if mounted for current session only. The only thing that bother me is that we are not really sure technically why this issue is only happening on few computers, the workaround will work but we will not know the root issue. I don't see alternatives anyway.

**Comment by marinkobabic** [comment]
@Maxhy
Let's try to identify the os and architecture where it works. I have never see it working without restarting explorer once.

**Comment by Liryna** [comment]
Oh really ? It always have worked for me on my Windows 10.

**Comment by marinkobabic** [comment]
Will do the test on Sunday in my vm with Windows 10 x64. According to your statement:

When I use the current session flag and mount for example the drive x:
* Then I can see the new drive X: in the explorer
* When I navigate to drive x: and then close the mirror.exe, then the explorer is closed automatically because the drive x does not exist anymore

Please can you confirm this behavior.

**Comment by Liryna** [comment]
I remade the test with old and new notification functions.

With both code on Windows 10 x64, I see the drive X: appeared without doing something. If I browse the device and quit mirror, the explorer window close automatically as you described.

**Comment by marinkobabic** [comment]
You used the current session flag? This is our discussion point.

**Comment by Liryna** [comment]
Oh, my bad :(

So I did the test with `/c` and it also work.

**Comment by marinkobabic** [comment]
This means Windows 10 works properly but Windows 8.1 and Windows 7 not, when the flag /c is used?

**Comment by Liryna** [comment]
@marinkobabic From what I see this is right (I only have tested it on win 10 & 7). 

I can only make a test on win8 next week.

**Comment by marinkobabic** [comment]
@Liryna 
I did now a test on Windows 8.1 x64 and all seems to work properly. Please just confirm that you have the same results. I use always the following program to see if broadcast has been sent properly or not http://www.codeproject.com/Articles/18062/Detecting-USB-Drive-Removal-in-a-C-Program (You can compile it using higher .Net Framework version)

It looks to me that we have only the issue on Windows 7?

**Comment by marinkobabic** [comment]
@Liryna 
I tested now also on Windows 7 Professional x64 and also there all works fine. Where you can reproduce that it does not work? It would be interesting to know if the program above does indicate that the drive has been added or removed in this specific case? Does the BroadCast return an error in this case?

**Comment by Liryna** [comment]
@marinkobabic I face the issue only on Win7 32bit as far as I can see.
I tested with the codeproject software that you provided. 

>mirror.exe /r C:\Users /l m /d /s /c
```
Drive arrived M:\
Drive removed M:\ <-- When I ctrl+c
```
So your software see correctly the device coming and leaving.

But it still cannot be seen in explorer even if killed.

**Comment by marinkobabic** [comment]
When you type in explorer M:\ then it works fine?

We are totally sure that this is the only affected os version?  Windows 10 x86 and Windows 8.1 x86 work fine?

This means that the broadcast is sent properly but the explorer just ignores it. It makes no difference if UAC is turned off?

After restarting explorer the drive must be there normally. The only reason that it's not there can be that the symbolic link is not created. This can be verified using the WinObj.exe

**Comment by js69** [comment]
Just wanted to report that a current build from last Friday works fine in my Win7-x86 VM; explorer shows drive after mounting and Explorer window on that drive is closed on unmount.

**Comment by Liryna** [comment]
@js69 Did you try with /c option?

**Comment by js69** [comment]
Ah, I only tested with my own FS. Did it now with mirror.exe, it does not work with that option (mirror.exe started in Run as Admin cmd.exe).

Other observation: CTRL+C on mirror.exe does not work correctly, it creates an error "mirror.exe doesn't work anymore", stdout output shows as last line:

DokanBroadcastLink: Begin SHChangeNotify

**Comment by Liryna** [comment]
@marinkobabic 

> you type in explorer M:\ then it works fine?

Windows can't find 'm:\'

>We are totally sure that this is the only affected os version? Windows 10 x86 and Windows 8.1 x86 work fine?

I do not have other x86 system. Does anyone else could test it ?

>This means that the broadcast is sent properly but the explorer just ignores it. It makes no difference if UAC is turned off?

Change nothing :(

>After restarting explorer the drive must be there normally. The only reason that it's not there can be that the symbolic link is not created. This can be verified using the WinObj.exe

He seems to be here:
![untitled](https://cloud.githubusercontent.com/assets/4311419/13602923/ea4d7ce0-e539-11e5-8b35-b9c86c0a84ce.png)

**Comment by marinkobabic** [comment]
@Liryna I just installed a new virtual box with Windows 7 x86 Professional with SP1 and started mirror using the following parameters mirror.exe /r c:\ /l m /t 5 /s /c and all works properly. So I'm not able to replicate the issue you have with Windows 7 x86. Are you using this version is your tests  https://drive.google.com/folderview?id=0B3E9tU82h-RMMmh3RkJFamM4WTA&usp=sharing? Please can you provide the FileSystem Log when so that we can see what happens when you try to access the drive? So where is the difference from my fresh installed Windows 7 and yours? SP1 is also installed in your case?

**Comment by accorp** [comment]
With current session flag mounted volume is visible only to programs which are running with same privileges as mirror.exe, i.e. if mirror.exe is started with administrator rights, then explorer (which is running with limited privileges) is not able to show the volume. Now if explorer has been killed and started with UAC elevation - it shows volume and its content. Then if I run mirror.exe without admin privileges - volume is not appeared in explorer, but if it is restarted with limited privileges - drive shows up!

What is more strange, I can start two mirror.exe - with and without UAC elevation, and mount two different folders with same volume letter! Then applications with different privileges will show different content for the same drive! Nice joke for April Fools' Day :smile: 

I can reproduce this behaviour on three virtual machines with win7-x86, win7-x64 and win8.1-x86.

**Comment by Liryna** [comment]
@marinkobabic :disappointed: My bad...it was my test that was wrong.
@accorp made me understood my mistake with mirror and explorer different privileges.

It is perfectly working on my Win7 32bit. Mirror run with simple user rights, the explorer see it.
If run the mirror and notepad with admin rights, notepad see correctly the device but not explorer as expected.

This can be closed and sorry again for the testing failure :cry:

**Comment by accorp** [comment]
@Liryna
About mirror sample crash on Win7. My delphi translation of mirror.c after ctrl+c shows
```
###Close 0107
Close: d:\test

send global release for m:
DokanBroadcastLink: Begin SHChangeNotify
DokanBroadcastLink: SHChangeNotify done
^C
```
so maybe it is not SHChangeNotify fault.

**Comment by Liryna** [comment]
@accorp , Are you testing on Win 7 x86 ? Do you face the issue with the mirror ?
For me it is really SHChangeNotify during removal that it happen. If I remove it I have no issues.

**Comment by accorp** [comment]
Yes, Win7-x86, and yes - mirror.exe crashed all times after CTRL+C.
But delphi translation of mirror is not :smile:

**Comment by Liryna** [comment]
hum :cry: Ok I see.
Do you have the possibilities to attach a debugger to see where the mirror crash ?

**Comment by accorp** [comment]
@Liryna  Ok, I'll try to make some test later.
