### ISSUE TITLE
Dokan1 driver fails to start on Windows 7

### ISSUE THREAD

**Issue by jetwhiz** [dokan-dev/dokany#179]
I can't seem to get dokan-1.0-RC1 to run on Windows 7.  I installed dokan via the provided release "DokanSetup.exe", restarted the computer, and it does not show up under Services.  When attempting to start it manually (see below), it returns an error 127.  I didn't notice any errors thrown during installation.  

```cmd
cmd> dokanctl.exe /i d
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
Installing driver...
DokanServiceInstall: Service (Dokan1) installed
DokanServiceControl: Failed to start service (Dokan1). error = 127
DokanServiceInstall: Service (Dokan1) start failed
Driver install failed
```

I have successfully built encfs4win against dokan-1.0 (as per https://github.com/jetwhiz/encfs4win/issues/7), but when I try to run it the program exits as if dokan is not installed at all.  This is what made me notice that the service is not running.

**Comment by hijkrix** [comment]
I have met the same error.
You will notice a warning if you don't restart Windows as soon as you have installed dokan.

**Comment by Liryna** [comment]
Hi @jetwhiz ,

Does you windows 7 is updated ? Is it a 32bit ?
Could you look at `'C:\Windows\system32\drivers\dokan1.sys` signature details ? (A screenshot would be nice :smiley: )

```
ERROR_PROC_NOT_FOUND
    127 (0x7F)
    The specified procedure could not be found.
```

It is the first time you try it with Win7 ?

**Comment by jetwhiz** [comment]
Hey @Liryna 

Yes it is 32-bit, with all of the most recent updates.  This Win7 virtual machine is what I have used for all versions of Dokany for testing.  Your installer for 0.7.4 works on it, and 0.8.0 works as well (but there is the issue of renaming files/folders, which I think is unrelated).  Dokany 1.0, however, does not run at all on it. 

Here is the file details of C:\Windows\system32\drivers\dokan1.sys.  Is that what you wanted to see? 

![virtualbox_win7_21_02_2016_17_30_10](https://cloud.githubusercontent.com/assets/533569/13203867/6d79c7fc-d8c1-11e5-9584-c37d95fb7c0b.png)

**Comment by Liryna** [comment]
Thank you for the informations @jetwhiz 

Could you screen the `Digital Signatures` window ?

I am installing a Win7 32bit to test it :smiley:

**Comment by jetwhiz** [comment]
Thanks @Liryna !

Here is the Digital Signatures window: 
![virtualbox_win7_21_02_2016_17_47_53](https://cloud.githubusercontent.com/assets/533569/13203939/63475216-d8c3-11e5-9940-bc20effec317.png)

**Comment by Liryna** [comment]
Ok so that's not a sign issue.

There should be a problem with the installer. Probably it does not install the correct files.
I will look into it.

**Comment by js69** [comment]
jetwhiz, could you please post the setup log, in %TEMP% the Dokan*x86*.log file?

**Comment by jetwhiz** [comment]
Hi @js69 

Here is the log file: [Dokan_x86.msi.txt](https://github.com/dokan-dev/dokany/files/139774/Dokan_x86.msi.txt)

**Comment by js69** [comment]
DIFXAPP: ERROR:  Unable to start service 'dokan' because of error 0x7F

Got to look up that error code.

You did reboot the machine and nothing changed?

**Comment by jetwhiz** [comment]
@js69 -- yes, I rebooted immediately after installing (as the installer suggested)

**Comment by marinkobabic** [comment]
What happens when you run as Administrator

net start Dokan1
net start dokan1

What information do you have in your event viewer?

**Comment by jetwhiz** [comment]
@marinkobabic - nothing shows up in event viewer, but I get this error when running it on the command line: 

```cmd
cmd>net start Dokan1
System error 127 has occurred.

The specified procedure could not be found.

cmd>net start dokan1
System error 127 has occurred.

The specified procedure could not be found.
```

**Comment by Liryna** [comment]
After some tests, this is not linked to the installer.

**Comment by Liryna** [comment]
The issue with the commit https://github.com/dokan-dev/dokany/commit/c4a0ae2c8620cdbeeb4c6b0297e983d4eb7a711a -> Add Mount Manager support
The commit just before https://github.com/dokan-dev/dokany/commit/797d5961f68821bda9c194c6ea77ae70730d5bb2 work perfectly..

I have not found the source of the issue... @marinkobabic do you have an idea ? The build seems to be correct. Could it be a issue when windows try to 'register' it ?

**Comment by Liryna** [comment]
The issue does not happen on Win7 64bit.

Does anyone have another Windows 32bit to test it ? It would be interesting to know if it is a 32bit issue.

**Comment by jetwhiz** [comment]
Have you been able to replicate this on Win7 32-bit, @Liryna ?

**Comment by Liryna** [comment]
Yes, I made a simple Win7 32-bit install and faced the issue directly.

**Comment by marinkobabic** [comment]
@Liryna 

Please can you compile a Windows 7 x86 driver on your machine, sign it and copy to the target machine where the start of the driver fails. Then perform net start dokan1. Does the driver start?

**Comment by Liryna** [comment]
@marinkobabic 

```
>dokanctl.exe /i d
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
Installing driver...
DokanServiceInstall: Service (Dokan1) installed
DokanServiceControl: Failed to start service (Dokan1). error = 127
DokanServiceInstall: Service (Dokan1) start failed
Driver install failed

>net start Dokan1
System error 127 has occurred.

The specified procedure could not be found.
```

**Comment by marinkobabic** [comment]
Just take your dokan1.sys and replace the file manually in c:\windows\system32\drivers and then execute 
net start dokan1

I will now do a small test using Windows 8 x86 because I have no Windows 7 virtual machine yet.

**Comment by Liryna** [comment]
Same behaviour :cry: 

Test on Windows 8 x86 would be interesting indeed !

**Comment by marinkobabic** [comment]
Please create a reg file using the following content and execute it. Then reboot the machine and do net start dokan1

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\dokan1]
"Type"=dword:00000002
"Start"=dword:00000000
"ErrorControl"=dword:00000001
"Tag"=dword:00000001
"ImagePath"=hex(2):73,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,64,00,\
  72,00,69,00,76,00,65,00,72,00,73,00,5c,00,64,00,6f,00,6b,00,61,00,6e,00,31,\
  00,2e,00,73,00,79,00,73,00,00,00
"DisplayName"="dokan1"
"Group"="File System"

**Comment by Liryna** [comment]
My Win7 does not really like it :smile: 

He directly reboot on repair mode.

**Comment by marinkobabic** [comment]
The installation is strange. It installs 
..\Service\dokan
..\Service\Dokan1

inside of Dokan1 ist the NetworkProvider key. The dokan services works properly on windows 8 x64.

Should not all be installed in the key

..\Services\dokan1 (lowercase please)


Thanks
Marinko

**Comment by Liryna** [comment]
I will look to make the changes.

You Win8 is x64 or x86 ?

**Comment by marinkobabic** [comment]
Oh sorry it's x86 :smile:

**Comment by Liryna** [comment]
:p Ok good to know that it is not all x86

Do you have any idea what in https://github.com/dokan-dev/dokany/commit/c4a0ae2c8620cdbeeb4c6b0297e983d4eb7a711a could 'break' Win7 32 bit ?

**Comment by marinkobabic** [comment]
When windows starts the service the DriverEntry is executed. We execute then the DokanCreateGlobalDiskDevice. Actually I have no idea why it should not work on Windows 7. Maybe you can turn the driver logging on to get more information. It seems to me that it can't event find the DriverEntry. But let's check the log if you are able to get one.

**Comment by Liryna** [comment]
@marinkobabic I have been able to get debug logs DriverEntry in the commit https://github.com/dokan-dev/dokany/commit/797d5961f68821bda9c194c6ea77ae70730d5bb2 before https://github.com/dokan-dev/dokany/commit/c4a0ae2c8620cdbeeb4c6b0297e983d4eb7a711a -> Add Mount Manager support
```
[DokanFS] ==> DriverEntry ver.190, Feb 23 2016 13:46:36
[DokanFS] DokanGlobalDevice: \Device\Dokan created
[DokanFS] SymbolicLink: \Device\Dokan -> \DosDevices\Global\Dokan created
[DokanFS] <== DriverEntry
```

But with `Add Mount Manager support` there is absolutly not logs at all. DriverEntry is even not called.

I can definitly say that there is something in the `sys/` code that make WinXP 32bit unable to call DriverEntry.

**Comment by Liryna** [comment]
Ok I found that the issue come from the file `device.c` in this commit https://github.com/dokan-dev/dokany/commit/c4a0ae2c8620cdbeeb4c6b0297e983d4eb7a711a

The change is big but the issue is inside.

**Comment by marinkobabic** [comment]
You can figure out, where the issue comes from when you just start to remove code from device.c. When the DriverEntry can be found, then you have identified the suspect lines. My expectation was that some IOCTL are not supported, but nothing found so far.

**Comment by Liryna** [comment]
Ok I will look into it :+1:

**Comment by Liryna** [comment]
I found the guilty line:
```
memcmp(mountdevName->Name, dcb->MountPoint->Buffer,
                     mountdevName->NameLength) == 0
```
https://github.com/dokan-dev/dokany/blob/4343350589e6c6bfce31e2675e0462c63c8618ca/sys/device.c#L538

If I remove this `memcmp` form the `if`, the driver is correctly installed O_o

I have no idea why and what to do with it...

**Comment by marinkobabic** [comment]
So please use RtlCompareMemory instead of memcmp.

**Comment by Liryna** [comment]
Done with https://github.com/dokan-dev/dokany/commit/58bc43b0576a2406c2bad3075230283869070c35

@jetwhiz could you try this release to see if it work for you:
https://drive.google.com/folderview?id=0B3E9tU82h-RMMmh3RkJFamM4WTA&usp=sharing

**Comment by js69** [comment]
I'm not Jetwhiz, but tested it anyway in a Win7_x86 VM, it works fine. :+1:

**Comment by Liryna** [comment]
Thank you :smile: ! Had no issue during the install and mirror worked fine ?
(I have some trouble on my side and special that the mirror crash when I CTRL +C)

**Comment by js69** [comment]
We need to do something with the ProductCodes and build numbers for clean setup upgrades. The tool I have to take care of that currently relies on a build number in a version.txt file, that would mean you'd have to manually increment the revision before you rebuild a version at least for public release.

**Comment by Liryna** [comment]
Yes I agree !
Also I found that, if the installation fail when it was installing the driver, it does not remove the dokan.sys. Is it possible to have a action that always remove it ?

**Comment by js69** [comment]
The dokan1.sys is copied to the drivers folder by difxapp so WiX might not know it has to rollback that file when difxapp fails. We can probably take care of that in a CustomAction by verifying the Dokan service is actually running.

**Comment by js69** [comment]
The nonstarting service in Win32 wasn't interpreted as a setup error but rather as a success with reboot requirement:

```
DIFXAPP: ERROR:  Unable to start service 'dokan' because of error 0x7F
DIFXAPP: SUCCESS:Installation completed with code 0x0.
DIFXAPP: INFO:   RETURN: DriverPackageInstallW  (0x0)
DIFXAPP: INFO:   ENTER:  DriverPackageGetPathW
DIFXAPP: SUCCESS:Found driver store entry.
DIFXAPP: INFO:   RETURN: DriverPackageGetPathW  (0x7A)
DIFXAPP: INFO:   ENTER:  DriverPackageGetPathW
DIFXAPP: SUCCESS:Found driver store entry.
DIFXAPP: INFO:   RETURN: DriverPackageGetPathW  (0x0)
DIFXAPP: INFO: driver store entry for 'C:\Program Files\Dokan\DokanLibrary-1.0.0\driver\dokan.inf' is 'C:\Windows\system32\DRVSTORE\dokan_85E7F627E2CF93D06A9D389C5A3368C67C5421BE\dokan.inf'.
DIFXAPP: INFO: The component Id '{1AFEA463-3DB8-48FA-87D1-7151BE92DB4B}' is now set to point to driver store: 'C:\Windows\system32\DRVSTORE\dokan_85E7F627E2CF93D06A9D389C5A3368C67C5421BE\dokan.inf'
DIFXAPP: INFO: A reboot is needed to install the component '{1AFEA463-3DB8-48FA-87D1-7151BE92DB4B}'.
DIFXAPP: RETURN: InstallDriverPackages() 0 (0x0)
```
Our custom action would have to recheck the service is running and initiate a rollback.

**Comment by Liryna** [comment]
@js69 I think it is more my logic to check if dokan1.sys is installed that is wrong https://github.com/dokan-dev/dokany/blob/master/dokan_wix/Dokan_x64.wxs#L68

Is there any way to 'play' with Product/ Update Codes to have one product by API like that we know that dokan 1 is already installed and therefore we refuse to install ?

**Comment by jetwhiz** [comment]
Hi @Liryna -- sorry it took so long to respond ... I didn't realize you had left messages on this issue.  For some reason GitHub only alerted me of the issue being closed!  I can confirm that the installer does appear to correctly install the drivers now, though!  

On a side note, I'm a little confused as to how mounting is supposed to be done now that dokan_mount has been removed as of 1.0.0.  In 0.7.4 and 0.8.0 there was a DokanMounter service running, that allowed our software to mount filesystems.  Since this service no longer exists, our software does not mount anymore as of 1.0.0.  Is there a new way that mounting is supposed to be performed now?

**Comment by Liryna** [comment]
Hi @jetwhiz ,

Could you give a example how your software mount ?
The service was just here to remember mount point and was source of instability.
Moreover the mount.exe was only using the dokan.dll api that are still here.

**Comment by jetwhiz** [comment]
@Liryna -- We mount in our software using the "fuse_main" macro.  In previous versions of Dokan, this required the DokanMounter service to be running.  When I stop this service, our software is no longer able to mount filesystems.  Is this not the way that it should be done?

**Comment by Liryna** [comment]
@jetwhiz I don't really understand what you are saying. There is more service. Which service are you stopping?

**Comment by marinkobabic** [comment]
@jetwhiz
The MounterService is not anymore needed. In previous versions the dokan.dll did the mount on behalf of this service. Now the mounting happens inside of the driver. You should just use the fuse_main like you did before and the rest is done in background for you.

**Comment by jetwhiz** [comment]
The DokanMounter service that I am referring to is this one: 

![virtualbox_win7_06_03_2016_14_33_17](https://cloud.githubusercontent.com/assets/533569/13554457/7d420306-e3a8-11e5-8a60-9f92bd2aa6aa.png)
 
This service only exists in Dokan 0.7.4 and 0.8.0, but not when I install 1.0.0.  For 0.7.4 and 0.8.0, this service must be running for my software to work correctly.  Is this supposed to exist in 1.0.0 as well?

**Comment by Liryna** [comment]
@jetwhiz No, it has been removed and the logic code has been moved to the kernel like marinko say. I think your software is using the wrong dll and you are still running with old dokan version. 

Be sure to use dokan1.dll and dokanfuse1. Dll

**Comment by jetwhiz** [comment]
@Liryna -- Got it working!  When building against your signed .lib and .dll files it works, so the problem must be when I try to build dokan on my side.  Thanks!

**Comment by DavidXanatos** [comment]
Great that you had that issue and found the cause, I just stumbled upon the same problem.

and i have a a bit nice fix just add the missing function to your code

```
//---------------------------------------------------------------------------
//
// Fix for the WindowsKernelModeDriver10.0 not creating Win 7 32bit compatible code
//
//---------------------------------------------------------------------------

#ifndef _WIN64
int __cdecl memcmp(
	_In_reads_bytes_(_Size) void const* _Buf1,
	_In_reads_bytes_(_Size) void const* _Buf2,
	_In_                    size_t      _Size
)
{
	return (RtlCompareMemory(_Buf1, _Buf2, _Size) == _Size) ? 0 : 1;
}
#endif
```

in the file you do that you need to disable optimization or else it will not work.

**Comment by Liryna** [comment]
@DavidXanatos Could you give a more context on this ? I am not sure to understand

**Comment by DavidXanatos** [comment]
> 
> 
> @DavidXanatos Thanks. I am not sure memcmp is ever used in the driver now.

Sure.... so the problem is that drivers on win 7 32 bit can not find memcmp in ntdll.dll, 
the way this is implemented is that the ntdll.lib has functions stubs for all the ntdll.dll imports.
The linker will pick only those actually used and put them in the final binary together with instructions for the loader to populate the appropriate address table with the used functions from the ntdll.dll
For whatever reason this operation fails on win 7 32 bit for drivers build with a more modern tool chain.
The solution here is to obviously not try to use the memcmp implementation from the ntdll.dll but instead something different.

One way of doing that is what you did, just go through the code and replace memcmp with for example RtlCompareMemory.
But this is work and work is best avoided if one can come up with a smart way to bypass it and get to the result right away

So my solution is to provide an own memcmp implementation. When the linker finds a memcmp in the project itself it wont take the one from the ntdll.lib which in turn would necessitate memcmp being dynamically linked into the driver, instead every callto memcmp ends up being emulated with a call to RtlCompareMemory.

The thing about disabling optimization is that compilers come with own optimized implementations of some common functions like memcmp so if that is enabled you can't provide an own function body. But this is only a problem on a per file level so you need only to disable that for one file and you will get your memcmp into an object file where it than can be found by the linker and used wherever the compiler decided to use it instead of the own optimized implementation.

With this trick I only need to add a few lines of code at one place and that only for the 32 bit build.

**Comment by Liryna** [comment]
Understood but the issue was solved as we changed the `memcmp` to `RtlCompareMemory`.
I am correct that your fix is no longer needed ?

**Comment by DavidXanatos** [comment]
> 
> 
> Understood but the issue was solved when we changed the `memcmp` to `RtlCompareMemory`.
> I am correct that your fix is not needed after this change ?

Yes

My fix is just a way to when someone has memcmp at 100 places not to have to edit all of them by hand but get the same result with only one C&P

I just thought that if I found this thread when googling my issue others will to and they may appreciate a a less work intensive approach.
