### ISSUE TITLE
Windows requires a digitally signed driver

### ISSUE THREAD

**Issue by qaisjp** [dokan-dev/dokany#187]
when installing "DokanSetup_redist.exe" in [v1.0.0-RC1](https://github.com/dokan-dev/dokany/releases/tag/v1.0.0-RC1)

![image](https://cloud.githubusercontent.com/assets/923242/13490346/f507382a-e123-11e5-850c-4c3f18aed5b5.png)

I'm on Windows Enterprise 7

**Comment by Liryna** [comment]
Did you update you windows 7 ?
The drivers are signed SHA1/SHA2, you can see it in the file properties.

**Comment by qaisjp** [comment]
![image](https://cloud.githubusercontent.com/assets/923242/13490422/4f57b96c-e124-11e5-8c45-0e7349b46172.png)

I'm on a networked computer so I cannot update this computer. There was a recent update to this computer but I'm not sure if that's what you're talking about

**Comment by Liryna** [comment]
Yes, Thanks this is what I am talking about.

There should be two signature but since your system is not updated it only see the SHA1 that is Microsoft deprecated....since 2016.

**Comment by qaisjp** [comment]
Okay well I've disabled verification using `bcdedit /set nointegritychecks ON`... lets hope it works..

**Comment by js69** [comment]
Is Service Pack 1 installed for that Windows 7? The setup should fail if it isn't but let's verify anyway.

SHA2 for Windows 7 might need this Windows update:
https://technet.microsoft.com/en-us/library/security/3033929

**Comment by qaisjp** [comment]
No idea if SP1 is installed ... like I said I can't install any updates because updates are managed by my sysadmin.

**Comment by js69** [comment]
You could post the setup log files, in your %TEMP% there should be Dokan* text files.

**Comment by qaisjp** [comment]
ok

**Comment by qaisjp** [comment]
here are all the logs
[Dokan_Library_1.0.0_Bundle_20160303092855_000_Dokan_x64.msi.log.txt](https://github.com/dokan-dev/dokany/files/156501/Dokan_Library_1.0.0_Bundle_20160303092855_000_Dokan_x64.msi.log.txt)
[Dokan_Library_1.0.0_Bundle_20160303093340.log.txt](https://github.com/dokan-dev/dokany/files/156502/Dokan_Library_1.0.0_Bundle_20160303093340.log.txt)
[Dokan_Library_1.0.0_Bundle_20160303093340_000_Dokan_x64.msi.log.txt](https://github.com/dokan-dev/dokany/files/156503/Dokan_Library_1.0.0_Bundle_20160303093340_000_Dokan_x64.msi.log.txt)
[Dokan_Library_1.0.0_Bundle_20160303093500.log.txt](https://github.com/dokan-dev/dokany/files/156504/Dokan_Library_1.0.0_Bundle_20160303093500.log.txt)
[Dokan_Library_1.0.0_Bundle_20160303093500_000_Dokan_x64.msi.log.txt](https://github.com/dokan-dev/dokany/files/156505/Dokan_Library_1.0.0_Bundle_20160303093500_000_Dokan_x64.msi.log.txt)
[Dokan_Library_1.0.0_Bundle_20160303094615.log.txt](https://github.com/dokan-dev/dokany/files/156506/Dokan_Library_1.0.0_Bundle_20160303094615.log.txt)
[Dokan_Library_1.0.0_Bundle_20160303094923.log.txt](https://github.com/dokan-dev/dokany/files/156507/Dokan_Library_1.0.0_Bundle_20160303094923.log.txt)
[Dokan_Library_1.0.0_Bundle_20160303094923_000_Dokan_x64.msi.log.txt](https://github.com/dokan-dev/dokany/files/156508/Dokan_Library_1.0.0_Bundle_20160303094923_000_Dokan_x64.msi.log.txt)
[Dokan_Library_1.0.0_Bundle_20160303095118.log.txt](https://github.com/dokan-dev/dokany/files/156509/Dokan_Library_1.0.0_Bundle_20160303095118.log.txt)
[Dokan_Library_1.0.0_Bundle_20160303095118_000_Dokan_x64.msi.log.txt](https://github.com/dokan-dev/dokany/files/156510/Dokan_Library_1.0.0_Bundle_20160303095118_000_Dokan_x64.msi.log.txt)
[Dokan_Library_1.0.0_Bundle_20160303092242.log.txt](https://github.com/dokan-dev/dokany/files/156512/Dokan_Library_1.0.0_Bundle_20160303092242.log.txt)
[Dokan_Library_1.0.0_Bundle_20160303092242_000_Dokan_x64.msi.log.txt](https://github.com/dokan-dev/dokany/files/156511/Dokan_Library_1.0.0_Bundle_20160303092242_000_Dokan_x64.msi.log.txt)
[Dokan_Library_1.0.0_Bundle_20160303092721.log.txt](https://github.com/dokan-dev/dokany/files/156514/Dokan_Library_1.0.0_Bundle_20160303092721.log.txt)
[Dokan_Library_1.0.0_Bundle_20160303092839.log.txt](https://github.com/dokan-dev/dokany/files/156515/Dokan_Library_1.0.0_Bundle_20160303092839.log.txt)
[Dokan_Library_1.0.0_Bundle_20160303092839_000_Dokan_x64.msi.log.txt](https://github.com/dokan-dev/dokany/files/156513/Dokan_Library_1.0.0_Bundle_20160303092839_000_Dokan_x64.msi.log.txt)
[Dokan_Library_1.0.0_Bundle_20160303092855.log.txt](https://github.com/dokan-dev/dokany/files/156516/Dokan_Library_1.0.0_Bundle_20160303092855.log.txt)

**Comment by Liryna** [comment]
I question myself about the dokan signature process....
We are using SHA2 certificate to sign SHA1 & SHA2.

I am wondering if we need a SHA1 cert to sign SHA1 and cert SHA2 to sign SHA2.
@js69 do you know something about it ?
Because it is strange that @qaisjp see a mix of SHA1/SHA2.

**Comment by qaisjp** [comment]
sha1 is for the countersign

**Comment by js69** [comment]
DIFXAPP: ERROR:  Unable to start service 'dokan' because of error 0x241

qaisjp: I think you should try to use the fixed driver package mentioned in issue 179:

https://drive.google.com/folderview?id=0B3E9tU82h-RMMmh3RkJFamM4WTA&usp=sharing

**Comment by js69** [comment]
"I am wondering if we need a SHA1 cert to sign SHA1 and cert SHA2 to sign SHA2."

 I don't think so. The only potential issue I would suspect is with non-updated Win 7 if you use a SHA2 cert for anything.

**Comment by qaisjp** [comment]
The fixed drivers aren't working either.

New set of logs: https://www.dropbox.com/sh/0cvw913y3kloans/AABNdN4Kf7HnKqjq1myC9GMQa?dl=0

**Comment by qaisjp** [comment]
Okay well I've reverted back to 0.7.3 (and an old version of winssh-fs)... the bug still probably exists for people in the same situation as me though.

**Comment by Liryna** [comment]
0.7.x will work because there was sign SHA1 before 2016.

This is a Microsoft limitations, I don't think we can do much with it.

**Comment by js69** [comment]
You could perhaps create a test driver setup signed with your old SHA1-cert to verify that is the reason here.

**Comment by js69** [comment]
qaisjp, you don't have any chance of installing https://support.microsoft.com/en-us/kb/3033929 on your machine and try after that?

**Comment by js69** [comment]
Some useful info on certificate issues can be found here:

http://www.davidegrayson.com/signing/#kmod

**Comment by GrantGatchel** [comment]
Installing the Security Update for Windows 7 (KB3033929) helped me:
https://www.microsoft.com/en-us/download/details.aspx?id=46078

**Comment by js69** [comment]
Liryna, I think we should install KB3033929 as well with the bundle like we do it for UCRT.

**Comment by Liryna** [comment]
It seems that we will need to do it yes. it is really strange that even without this patch it cannot validate the SHA1....

**Comment by js69** [comment]
Liryna, I've implemented KB3033929 installation with the bundle but that's not a final or elegant solution. 

The update requires a restart before it becomes active:

Applied execute package: Win71_KB3033929_x64, result: 0x0, restart: Required

Because that restart is not scheduled by WiX Burn before the Dokan driver is installed, users will still see the unsigned driver warning. After restart the driver though is installed correctly because the KB3033929-updated DLLs will then allow SHA256-signed drivers.

Adding the KB3033929 msu files also increases the size of DokanSetup_redist.exe to 110 MB.

Scheduling the restart before Dokan driver installation is only possible with a custom bootstrapper.

As an alternative I'd rather implement a check for install status of KB3033929 and show an error in case it isn't already installed (only relevant for WIn 7).

**Comment by Liryna** [comment]
@js69 Thank you for the test !
I think your solution of showing an error on Win7 would be the best solution as you said !
