### ISSUE TITLE
Improve uninstall: support service STOP, UNLOAD and DokanServiceDelete to avoid reboot?

### ISSUE THREAD

**Issue by js69** [dokan-dev/dokany#189]
Currently the driver requires a reboot to cleanly remove its service and allow deleting the driver file.

DIFXAPP: WARNING:Service 'dokan1' never stopped
DIFXAPP: WARNING:File C:\Windows\system32\DRIVERS\dokan1.sys not yet deleted but scheduled to be deleted on next reboot.

Would it be possible to support STOP and UNLOAD for the service?

There is some discussion about that for ext2fsd but I don't think the conclusion of too many unknown dependents for the service applies in the Dokan case:

https://sourceforge.net/p/ext2fsd/discussion/143329/thread/d829b011/

**Comment by marinkobabic** [comment]
Dokan Service is a FileSystem Service. Windows normally does not allow to stop this kind of services. It can only mark it for delete for the next reboot.

**Comment by js69** [comment]
Yeah, after reading some stuff on OSR I have to agree. Closing.

**Comment by js69** [comment]
Just an observation though, the service returns STOPPABLE on query::

C:\Windows\system32>sc query dokan1

SERVICE_NAME: dokan1
        TYPE               : 2  FILE_SYSTEM_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

**Comment by Liryna** [comment]
what happen if you try to stop it ?

net Dokan1 stop

**Comment by marinkobabic** [comment]
You will get a message like the service can't be stopped. The tool osrloader.exe can't also stop the service. All it can do is to unregister the service. After the reboot the service is not running anymore, because windows has no knowledge about it of course. I have actually no pc in front of me but the question  is, is NTFS stoppable? If no, then is the question why dokan has the stoppable flag.
