### ISSUE TITLE
mirror didnt mount

### ISSUE THREAD

**Issue by gvonkreisler** [dokan-dev/dokany#190]
C:\Users\Avid_01\Documents\Visual Studio 2015\Projects\dokany-1.0.0-RC1\x64\Release>mirror.exe /r A: /l Z /d /s
## Attempting to add SE_SECURITY_NAME privilege to process token ##
  success: privilege already present
Dokan: debug mode on
Dokan: use stderr
device opened
mounted: Z -> \Volume{d6cc17c5-1727-4085-bce7-964f1e9f5de9}
Mounted
ReturnedLength 0
ReturnedLength 0
ReturnedLength 0
ReturnedLength 0
ReturnedLength 0
Ioctl failed for wait with code 1.
Ioctl failed for wait with code 1.
Ioctl failed for wait with code 1.
Thread will be terminated
Ioctl failed for wait with code 1.
Thread will be terminated
Thread will be terminated
Ioctl failed for wait with code 1.
Thread will be terminated
Thread will be terminated
Unmounted

unload
Success

**Comment by gvonkreisler** [comment]
+ when stop the dokan service and do a new start ....

The service cannot accept control messages at this time

An instance of the service is already running.

Greatings george

**Comment by gvonkreisler** [comment]
By the way

the files that are created during compile are all named dokan1 ( 1) but all you wikis are based on dokan...
That makes the " Thinks" not easy ...
George

**Comment by Maxhy** [comment]
Related to your other issue #191.

**Comment by gvonkreisler** [comment]
Dear Maxhy,
![capture](https://cloud.githubusercontent.com/assets/17441707/13555293/ef4cfff0-e3bc-11e5-9f88-1eb5f98bcfbe.PNG)
and do the regedit key.
And of course I have wrote my own kdmf filter with the VS cert .... no problems 

Documents\Visual Studio 2015\Projects\dokany-1.0.0-RC1\x64\Release>dokanctl.exe /i a
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
Documents\Visual Studio 2015\Projects\dokany-1.0.0-RC1\x64\Release>mirror.exe /r A: /l m /d /s
## Attempting to add SE_SECURITY_NAME privilege to process token ##
  success: privilege already present
Dokan: debug mode on
Dokan: use stderr
device opened
mounted: m -> \Volume{d6cc17c5-1736-4085-bce7-964f1e9f5de9}
Mounted
ReturnedLength 0
ReturnedLength 0
ReturnedLength 0
ReturnedLength 0
Ioctl failed for wait with code 1.
Ioctl failed for wait with code 1.
Ioctl failed for wait with code 1.
Thread will be terminated
Ioctl failed for wait with code 1.
Thread will be terminated
Thread will be terminated
Ioctl failed for wait with code 1.
Thread will be terminated
Thread will be terminated
Unmounted

unload
"Success"

Why I get a "success only" as out of a funktion (driver unload) but nothing worked ?

I think some is wrong with your volume querry funktion.
ReturnedLength 0         -->     filefsattribute

Have had the same Problem with the offered exe, so I compiled dokan1 by my self.
Ans of course I have a vbox running with a new system to, but same errors.

I read a that other users have the same problem.
Thanks for your answer.

Chears

**Comment by Maxhy** [comment]
Is https://drive.google.com/folderview?id=0B3E9tU82h-RMMmh3RkJFamM4WTA&usp=sharing working (drive version because of possible bsod issue in rc1 once mounted)? If so it's a sign issue.

**Comment by gvonkreisler** [comment]
Not Found Error 404

when i open you link...

But I have a other question....

Your networkProvider dokannp:

Normaly if I map a network share from Linux I get the provider Info

wmic providername

Windows Bla Bla

When I would change this Info what funktion I have to use

DWORD APIENTRY NPAddConnection3

DWORD APIENTRY NPGetResourceInformation

or an other one ?


Greatings

George



Schnitt & Schnittig GmbH

mobil: +49 151 240 59 58 4   tel: +49 221 99 20 55 07

Schnitt, Postproduktions-Management, Netzwerktechnik


2016-03-06 17:18 GMT+01:00 Maxime C. <notifications@github.com>:

**Comment by gvonkreisler** [comment]
Ok now the link worked...
But this is an exe ....
Cut I install it or have I to delete eyery think from dokann1?

chears
George

Schnitt & Schnittig GmbH

mobil: +49 151 240 59 58 4   tel: +49 221 99 20 55 07

Schnitt, Postproduktions-Management, Netzwerktechnik


2016-03-06 17:18 GMT+01:00 Maxime C. <notifications@github.com>:

**Comment by gvonkreisler** [comment]
[image: Inline-Bild 1]


Schnitt & Schnittig GmbH

mobil: +49 151 240 59 58 4   tel: +49 221 99 20 55 07

Schnitt, Postproduktions-Management, Netzwerktechnik


2016-03-06 17:18 GMT+01:00 Maxime C. <notifications@github.com>:

**Comment by Liryna** [comment]
@gvonkreisler , please uninstall & remove all binaries that you have installed and build.
Use the install that Maxhy gave you and test the mirror that has been installed.

If it work, use the dokan.dll and header from the installer for your application.

**Comment by gvonkreisler** [comment]
Thank you
will test

Chears

Schnitt & Schnittig GmbH

mobil: +49 151 240 59 58 4   tel: +49 221 99 20 55 07

Schnitt, Postproduktions-Management, Netzwerktechnik


2016-03-06 18:11 GMT+01:00 Liryna <notifications@github.com>:

**Comment by gvonkreisler** [comment]
Dear Lyrna

C:\Program Files\Dokan\Dokan Library-1.0.0\sample\mirror>sc start dokan1
[SC] StartService FAILED 577:

Windows cannot verify the digital signature for this file. A recent
hardware or software change might have installed a file that is signed
incorrectly or damaged, or that might be malicious software from an unknown
source.


C:\Program Files\Dokan\Dokan Library-1.0.0\sample\mirror>
So what shut I do...

Again patch registry with the ci key ?
What does the .inf File ?
Normaly it does the reg entrys

LG
Georg

Schnitt & Schnittig GmbH

mobil: +49 151 240 59 58 4   tel: +49 221 99 20 55 07

Schnitt, Postproduktions-Management, Netzwerktechnik


2016-03-06 18:11 GMT+01:00 Liryna <notifications@github.com>:

**Comment by Liryna** [comment]
Ok, Does your system is fully updated ?
