### ISSUE TITLE
Service didnt start

### ISSUE THREAD

**Issue by gvonkreisler** [dokan-dev/dokany#191]
Documents\Visual Studio 2015\Projects\dokany-1.0.0-RC1\x64\Release>dokanctl.exe /i d
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
Installing driver...
DokanServiceInstall: Service (Dokan1) installed
DokanServiceControl: Failed to start service (Dokan1). error = 2
DokanServiceInstall: Service (Dokan1) start failed
Driver install failed

**Comment by gvonkreisler** [comment]
Documents\Visual Studio 2015\Projects\dokany-1.0.0-RC1\x64\Release>dokanctl.exe /v
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
dokanctl : Mar  5 2016 22:33:01
Dokan version : 100
Dokan driver version : 0x190

**Comment by gvonkreisler** [comment]
C:\Users\Avid_01\Documents\Visual Studio 2015\Projects\dokany-1.0.0-RC1\x64\Release>sc start dokan
[SC] StartService FAILED 1056:

An instance of the service is already running.


C:\Users\Avid_01\Documents\Visual Studio 2015\Projects\dokany-1.0.0-RC1\x64\Release>sc stop dokan

SERVICE_NAME: dokan 
        TYPE               : 1  KERNEL_DRIVER  
        STATE              : 3  STOP_PENDING 
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

C:\Users\Avid_01\Documents\Visual Studio 2015\Projects\dokany-1.0.0-RC1\x64\Release>

**Comment by gvonkreisler** [comment]
Documents\Visual Studio 2015\Projects\dokany-1.0.0-RC1\x64\Release>sc start dokan
[SC] StartService FAILED 1056:

An instance of the service is already running.


C:\Users\Avid_01\Documents\Visual Studio 2015\Projects\dokany-1.0.0-RC1\x64\Release>

**Comment by gvonkreisler** [comment]
\Documents\Visual Studio 2015\Projects\dokany-1.0.0-RC1\x64\Release>sc start dokan1
[SC] StartService FAILED 2:

The system cannot find the file specified.

**Comment by gvonkreisler** [comment]
Nothing works at all....
My 3. test on dokan...
Mabe you need some time to fix all the problems
Than I would name a program 1.0
1.0 ---> This looks like, there is a change to get it run for a "normal user" ....

But
No chance...
George

**Comment by Maxhy** [comment]
Please don't flood, this will give us some confidence that you tried before posting :wink:.

Anyway, your issue is related to driver signing: you build the driver by yourself which is fine but means you will have to sign it or enable test-signed drivers to load on your system.
