### ISSUE TITLE
Network device showed as disconnected

### ISSUE THREAD

**Issue by gvonkreisler** [dokan-dev/dokany#199]
# Environment
 * Windows version: win7 
 * Processor architecture: 64
 * Dokany version: 1.0.0.102 (RC2)
 * Library type (Dokany/FUSE): 
 
# Check List
- [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
- [x] I can always reproduce the issue with the provided description bellow
- [x] If I updated Dokan driver (installer or .sys), I tried to restart the computer before my tests
- [x] It can be reproduced on latest [release and pre-release](https://github.com/dokan-dev/dokany/releases)

# Description
Disconnected Netwokdrive ( Red Cross) but Drive is their and ok when using mirror with `/n` option

# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
In case of BSOD, please attach minidump or dump analyze output.

**Comment by gvonkreisler** [comment]
![dokan rc 1 0 102](https://cloud.githubusercontent.com/assets/17441707/13826181/754fe490-ebb6-11e5-8917-d026c3f8dc88.PNG)

**Comment by gvonkreisler** [comment]
Dear Liryna,

I think their is some thig not ok with the "rights" , I cant change the owner or group values in windows ( on this drive) but creating and deleting and renaming. Maby its normal in a /disconnected networkdrive/ I dont know...
Did you create a netprovirder id in dokannp like "Microsoft Windows Network" so the redirector knows the provider ?

chears george

**Comment by Liryna** [comment]
Hi @gvonkreisler ,

Yes there is a network provider (dokannp1.dll that you can find in system32).
You can find the source here: https://github.com/dokan-dev/dokany/blob/master/dokan_np/dokannp.c
And it is registered by: https://github.com/dokan-dev/dokany/blob/master/dokan/mount.c#L242

(For you informations, since the release you are using, I have changed the code to move dokannp1.dll in the same folder as dokanctl.exe that why the path is taken by GetModuleFileName)

It is a very simple implementation just made to have the device as 'Connected' (that it seems to not working in your case).

**Comment by marinkobabic** [comment]
@Liryna The reason it does not work is the ProviderOrder registry entry. The name used there must be  **Dokan1**. Please fix the setup and it will work. Maybe also this issue will then be fixed https://github.com/dokan-dev/dokany/issues/200

**Comment by Liryna** [comment]
:+1: @marinkobabic Thank you it work perfectly with Dokan1 as you told.

I think it was my mistake when I have updated the name :cry: with api version.

**Comment by gvonkreisler** [comment]
Thank you
Works ...
First time I get it run ...
LG
George

Schnitt & Schnittig GmbH

mobil: +49 151 240 59 58 4   tel: +49 221 99 20 55 07

Schnitt, Postproduktions-Management, Netzwerktechnik


2016-03-17 10:48 GMT+01:00 Marinko <notifications@github.com>:

**Comment by CollinChaffin** [comment]
This needs to be PULLED!!  Installing this provider totally BREAKS networking on WIN7x64!  All NET USE commands no longer work generate "network name not valid" despite a simple "dir \\xxxxxx\dir" on the same dir working fine.  Uninstalling this DOKANY redist solves the issue.
