### ISSUE TITLE
Build instructions - need help

### ISSUE THREAD

**Issue by kallekataja** [dokan-dev/dokany#20]
Hello,

I hope this finds you well, in good spirit and having a good day.

I would like to start helping with the Dokany project, if I can.

However because my experience is mostly from Linux/GNU programming, I would need help to get started with the Visual Studio, please.

I created a Windows Server 2008 R2 virtual machine, and installed Visual Studio 2013 Express for Desktop with the WDK 8.1 as written on:

https://github.com/dokan-dev/dokany/wiki/Build

But I do not understand or find how to do this:

"On VS menu, select Generate => Background Configuration then check all Win32/x64 Release configuration and click on Generate."

My friend who has worked with Visual Studio before could not tell me what does it mean either.

I did give him remote desktop access to the box, and he tried to build it, but it said 4 succeed 2 failed, and that it built dokan.dll but could not find dokan.lib.

It would be great if you can help me get started with this, as I hope I can then be able to get into it and help to fix things in the future.

Has anyone been able to build it according to the Build page instructions out of the box?

Sorry for the 'newbie'-ish issue, but once I get over it, hopefully I can get cracking!

Further advice and clarification would be great.

With best wishes,

Kalle.

**Comment by Maxhy** [comment]
Yes this part of the documentation requires Visual Studio Professional.
This was just a shortcut, you can build manually all Release Win32/x64 one by one and it will result the same.

**Comment by kallekataja** [comment]
Thank you. Got it to build now, no problem. I feel almost stupid to have asked - it's one of those things that after asking, you then get it to work flawlessly.

Anyway, thanks for all the efforts so far, hope I can chip in soon enough with any issues!
