### ISSUE TITLE
FUSE sample fusexmp just exits

### ISSUE THREAD

**Issue by Stefitzky** [dokan-dev/dokany#202]
# Environment
 * Windows version: Win7 64bit
 * Processor architecture: x86_64
 * Dokany version: 1.0.0_RC2
 * Library type (Dokany/FUSE): FUSE
 
# Check List
  - [ X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ X] I can always reproduce the issue with the provided description below.
  - [ X] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description

When I compile fusexmp.c under a fairly new Cygwin (**32bit**) using the gcc compiler, the build works fine. When I start fusexmp.exe however, it just returns with exit code 0. My steps were:

* installed dokany-1.0.0-RC2 and rebooted. The Dokany installation then is in `c:\Program Files\Dokan\Dokan Library-1.0.0`
* copied the c:\Program Files\Dokan\Dokan Library-1.0.0\sample\fuse_mirror files to a local directory
* compiled the program with this command: `gcc -o fusexmp -D_FILE_OFFSET_BITS=64 -I/cygdrive/c/Program\ Files/Dokan/Dokan\ Library-1.0.0/include/fuse -L . -l cygdokanfuse1 fusexmp.c`. No compilation errors
* started the program with `./fusexmp m`. The program starts and just exits (exit code 0).
* ran `ldd fusexmp.exe`, all libraries are found
* copied fusexmp.exe, cygdokanfuse1.dll and dokan1.dll to /usr/bin/
* ran `cygcheck fusexmp`, again all libraries are found
* I even started the program in gdb, the relevant output was

> Starting program: /home/user/dokany/fusexmp
> [New Thread 1648.0x760]
> [New Thread 1648.0x6cc]
> [New Thread 1648.0x910]
> [New Thread 1648.0x3e0]
> [Thread 1648.0x6cc exited with code 0]
> [Thread 1648.0x910 exited with code 0]
> [Thread 1648.0x3e0 exited with code 0]
> [Inferior 1 (process 1648) exited normally]

I have no clue as to what the problem might be. I don't think that the problem is the combination of 64bit Windows and 32bit Cygwin, because that would rather lead to compile time errors.

# Logs

**Comment by Liryna** [comment]
Hi,

Did you try the already build sample in `c:\Program Files\Dokan\Dokan Library-1.0.0\samples\fuse_mirror` ?

Otherwise, could try try to copy `cygdokanfuse1.dll` and `dokan1.dll ` in the same folder as `fusexmp.exe` ? cygdokanfuse1 need dokan1 to be side by side. https://github.com/dokan-dev/dokany/blob/master/dokan_fuse/src/docanfuse.cpp#L521

**Comment by Stefitzky** [comment]
Thanks for your super quick reply

Yes, I already did all of the above. **HOWEVER**, I found the problem: it was the **missing x86 (32bit) MS VC Redistributable**. I believe your installation package only comprises the 64bit version, so I had to install the 32 bit version manually. Now everything works as a charm.

I found the solution as soon as I tried running the 32bit mirror example (the normal one, not the FUSE version). That one (as opposed to the FUSE library) issued an error message requesting the VC  redist and died horribly, so it was clear what was missing.

For future releases, I think it would be nice if fuse_mainloop() would die screaming havoc, too, if any redistributable is missing, instead of exiting with RC 0 (which looks like ok).

Please mark this incident as closed. 

Thanks for your great work!

**Comment by Liryna** [comment]
@Stefitzky , thats a good new !
Strange that it returned 0
Normally it should return -1 -> https://github.com/dokan-dev/dokany/blob/master/dokan_fuse/src/docanfuse.cpp#L510

Did you used `DokanSetup_redist.exe` or `DokanSetup.exe` ?

**Comment by Stefitzky** [comment]
Both, actually. First I installed DokanSetup.exe, then it occurred to me (even before I compiled anything) that the redistributable might be missing, so I installed DokanSetup_redist.exe (and did a reboot).

**Comment by js69** [comment]
Could you please post the log files from the no-redist setup attempt (dokan*txt files in %TEMP%)? 

It should have prompted you with an error as well when it couldn't download the redist files itself.

**Comment by Liryna** [comment]
Done with https://github.com/dokan-dev/dokany/commit/a415ea952adadf6ce9635e75df7e7a2f34e08f62

Thank you for your feedback @Stefitzky  !
