### ISSUE TITLE
Kernel thread timeout?

### ISSUE THREAD

**Issue by Stefitzky** [dokan-dev/dokany#205]
# Environment
 * Windows version: Win7 64bit
 * Processor architecture: x86_64 (virtual, KVM hypervisor)
 * Dokany version: 1.0.0_RC2
 * Library type (Dokany/FUSE): FUSE 
 
# Check List
  - [X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [X] I can always reproduce the issue with the provided description below.
  - [X] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description

Me again :-) I have continued to test Dokany/FUSE mirror. On a KVM based virtual machine, I am accessing different directories (only reading) in a large directory tree with sometimes a couple of hundred files per directory. Sometimes, the drive process just disappears (no error messages, just -poof-, end of process) in the middle of an operation, like some timeout occurred. Until now, this only occurred on virtual machines (three of them). As far as I can tell, it is not restricted to certain files/directories or even file/directory sizes. Sometimes, it is enough to keep the drive in a Windows explorer open and do something else that drains away all/most of the CPU; then, the drive suddenly becomes inaccessible, although the drive letter remains visible.

I have come to suspect that there might be a certain amount of time the software is willing to wait for its kernel worker threads; if they don't report back within the given time, they are presumed dead due to some hardware error or network issue and the drive stops working. That would explain why this happens on virtual machines only/mainly (where no CPU time basically also means no I/O).

If this is the case, is there any possibility of raising the timeout value to something a bit more patient?

Or is there any other explanation why the drive keeps disappearing under stress?

Thanks for any suggestions.

# Logs

**Comment by Liryna** [comment]
Hi @Stefitzky ,

The device disappear automatically when the request made take too much time to process.
It is a security in case the user land application crashed or there is nobody to control the device. So to not let a device that could slow Windows or even in some case crash it...dokan unmount himself..

Otherwise, there is possibility to request more time during a request with DokanResetTimeout. https://github.com/dokan-dev/dokany/blob/4343350589e6c6bfce31e2675e0462c63c8618ca/dokan/timeout.c#L26

But since you are using FUSE wrapper, I am not sure you can use it :cry: 
Do you know if with FUSE there is such behaviour to request more time that exist ?

Can you see which part of the code take the most time ?

**Comment by Stefitzky** [comment]
Thanks for your hint, `DokanResetTimeout` is just what I hoped for. Since FUSE is only a wrapper around Dokan, I guess `DokanResetTimeout` will most probably work with it, too. I will try in any case.

As to your question: it is not the FUSE code that takes too long, it is other processes on the system that drain away the I/O (by means of CPU and or actual disk access) that lead to Dokan being killed. Dokan by itself seems not to run into performance problems (as far as I can tell for now).

Let me report back to you as soon as I did some tests with `DokanResetTimeout`.

**Comment by Liryna** [comment]
Hi @Stefitzky ,

Have you been able to make your test ?

**Comment by Stefitzky** [comment]
I constructed a test setup on a virtual machine with Windows 7 that starts a software with heavy random CPU load during about one minute (after which the program just waits for the drive process to end), while mounting a (FUSE) Dokan based mirror drive in a forked process (i.e. concurrently). Without any modifications, this gives me the expected results (drive goes away, not always, but usually).

Then I tried to reset the time Dokan waits for its worker threads. The function `DokanResetTimeout` just resets the timeout for one (the next) Dokan call - obviously this is not usable with FUSE, as it wraps the Dokan calls in its own functions.

However, there is an option `daemon_timeout` that can be set at FUSE initialization time (via `fuse_opt_add_arg`). That one should do the trick (globally). If I set this to a large value (60 seconds), the drive indeed seems to have better chances of survival, but even then, the drive just goes away most of the time. Not always right at the beginning during the high CPU load period (as it does without the `daemon_timeout` setting), but sometimes a little later while browsing the contents with the explorer. And sometimes it just vanishes minutes after the software startup, without any user interaction (as though some process stopped waiting for something to happen, because nothing continued to happen for too long...).

The drive almost always goes away immediately if a Windows explorer is open during software startup. I started to believe that maybe the explorer does some initial scan of the directory structure that fails to complete in time, which then kills the drive. My impression was that the deeper the structure, the higher the chances the drive dies. While investigating how deep the directory tree must be in order to make the drive fail always, I found out that you cannot create paths with Dokan FUSE that are longer than about 248 bytes?!? According to some digging around in different forums this seems to be some old limitation of the Windows file API (used by Cygwin). 

Now I turned to the question of virus scanners; maybe these keep Dokan busy? I have MS Security Essentials active on this machine, so I added the drive path (Q:\) to the ignore list. And from this point on, the machine always went directly and immediately to a blue screen whenever I started the drive. So Dokan does not like MS Essentials exclude lists or vice versa (at least on Win7). Removing the exclude from MS Essentials resolved this issue.

I then did the same testing (not the MS Essentials part though) on a physical machine (Win7 Pro 64bit, Quadcore, 32 GB RAM). Here, Dokan FUSE was running very reliably, which made me a little happy. I wrote a script that zips and unzips some directories on the FUSE drive to do some stress testing. When the drive kept working ok for a couple of hours, I started to feel really happy, but then the first blue screen occurred. So I tried again. This time, it took a few minutes of zipping/unzipping till BSOD. The third time, the script was running for over a day before the machine went down.

**Comment by Stefitzky** [comment]
wrong button, sorry...

**Comment by Maxhy** [comment]
@Stefitzky it seems you have several issues here
 * **Requests Timeout**: that's your original issue, I believe we are not tolerant enough here and should found a way to distinguish stressful conditions with a dead user-mode file system.
 * **FUSE MAX_PATH**: this could easily be isolated on fuse wrapper. It makes several uses to MAX_PATH define which is 260 length, I beilieve this is related.
 * **BSODs**: crash minidump or analyze would be really helpful here

Thanks.

**Comment by Liryna** [comment]
Feel free to reopen if you have any informations.
