### ISSUE TITLE
should use _WIN32 instead of WIN32 in FUSE

### ISSUE THREAD

**Issue by x1596357** [dokan-dev/dokany#208]
# Description
```
---- WIN32 Matches (3 in 2 files) ----
Fuse.h (dokan_fuse\include):13
#ifdef WIN32
#include "fuse_win.h"
typedef struct _FILETIME FILETIME;
Fuse.h (dokan_fuse\include):448
#ifdef WIN32
	/* these to support extented windows calls */
	uint32_t (*win_get_attributes) (const char *fn);
Fuse_common.h (dokan_fuse\include):34
#ifndef WIN32
/* This interface uses 64 bit off_t */
#if _FILE_OFFSET_BITS != 64
```

I think we should use [_WIN32](https://msdn.microsoft.com/en-us/library/b0084kay.aspx) instead of WIN32.
 _WIN32: Defined for applications for Win32 and Win64. Always defined. 
However WIN32 is only defined in Win32, which means in Win64 we think the environment is not Windows.

**Comment by Liryna** [comment]
Hi @x1596357 ,

WIN32 does exist in x64, it is define in Windows SDK without checking if it is x86 or x64.
http://stackoverflow.com/questions/662084/whats-the-difference-between-the-win32-and-win32-defines-in-c

I agree that it is better to use _WIN32 in case the file where they are us does not include a SDK windows file that define WIN32 (not our case for now :smiley: )

You can make a pull request if you want ^^

**Comment by x1596357** [comment]
When using fuse wrapper headers to develop applications in VS, that is the situation where SDK is not included. I am gonna make a PR
