### ISSUE TITLE
I can't use  Iometer to test mirror program

### ISSUE THREAD

**Issue by zmfsea** [dokan-dev/dokany#215]
It seems that the iometer tool can't recognize the driver letter mapping by mirror program. I change to network driver using /n parameter but still not work. I found that the network driver mapping by samba can be recognized by iometer.

**Comment by Liryna** [comment]
Hi @zmfsea ,

Can you try with the `/o` option ?

**Comment by zmfsea** [comment]
hi @Liryna,
I add /o and remove /n , but the driver letter is still not recognized by iometer. By the way I notice that "Create DeviceObject for the File System" is moved from DokanCreateDiskDevice to DokanCreateGlobalDiskDevice , Why ? Does this cause the problem ?

**Comment by Liryna** [comment]
I think iometer is listing physical device and therefore does not get the dokan device. It would be interesting if you can see in their source code how they get this disk list.


>"Create DeviceObject for the File System" is moved from DokanCreateDiskDevice to DokanCreateGlobalDiskDevice

This is related to a context issue: https://github.com/dokan-dev/dokany/pull/141#issuecomment-174047455

**Comment by Liryna** [comment]
@zmfsea have you been able to take a look at  Iometer  source code ?

**Comment by Liryna** [comment]
Feel free to reopen if you have any informations.
