### ISSUE TITLE
Installer doesn't work on Windows Vista

### ISSUE THREAD

**Issue by suy** [dokan-dev/dokany#22]
Hi.

According to a message from Maxime, and the [Unsupported](https://github.com/dokan-dev/dokany/wiki/Unsupported) wiki page, Vista is supported, but the installer refuses to continue in it. I still have an ancient machine that I would like to use to test my app. If you could change the installer to allow installations on Vista, I would again be very thankful. :)

**Comment by dimov-cz** [comment]
Try compatibility mode

**Comment by Maxhy** [comment]
Oh indeed, Vista is not officially supported anymore as we focus on WDK version >= 8.1 Update
This because drivers are not compiled for this target.

**Comment by suy** [comment]
Thank you for the info. I've see you've updated the wiki already, so closing then. :)
