### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [dokan-dev/dokany#220]
I would like to point out that identifiers like "[`_DOKAN_H_`](https://github.com/dokan-dev/dokany/blob/0e8366c7441ad1358a6a33b584341c335f33781d/dokan/dokan.h#L22)" and "[`_DOKAN_ACCESS_STATE`](https://github.com/dokan-dev/dokany/blob/90ee4996d9eee2f78a774b9bc509172adfaf29f6/sys/public.h#L133)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by Liryna** [comment]
Hi @elfring ,

It is a C project.
I will fix the Include guards to fit C standard (ISO/IEC 9899) section 7.1.3/1. http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1124.pdf

Underscore struct are not made to be used directly, but only through the accompanied typedef so there is not need to change it.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by Liryna** [comment]
This is far from undefined behavior in practice.

**Comment by elfring** [comment]
I would appreciate if [more identifiers will become standard-compliant](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier "What are the rules about using an underscore in a C++ identifier?").

**Comment by Liryna** [comment]
like ?

**Comment by elfring** [comment]
I suggest to delete underscores at some source code places.

**Comment by Liryna** [comment]
Include guard has been changed but struct will still as they are (see my first answer for the reason).
https://github.com/dokan-dev/dokany/commit/1d9d28d78636f723706eece1b48b773192174004

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/dokan-dev/dokany/commit/1d9d28d78636f723706eece1b48b773192174004 "Renaming of include guards").
I hope that remaining update candidates can be considered once more later.
