### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [dokan-dev/dokany#221]
Would you like to replace more defines for constant values by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages) to stress their relationships?
* [DOKAN_OPTION_…](https://github.com/dokan-dev/dokany/blob/0e8366c7441ad1358a6a33b584341c335f33781d/dokan/dokan.h#L53)
* [IRP_MJ_…](https://github.com/dokan-dev/dokany/blob/4ec77fd4d4aa149910a02cd8d4b8c9b0daa92ceb/dokan/fileinfo.h#L25)

**Comment by Liryna** [comment]
Changing DOKAN_OPTION to enum could be an idea but It would break user code. I have take a look at it for 1.0.0.
IRP are declared as define in Windows Kernel headers so we will keep it like that.

**Comment by Liryna** [comment]
Done with https://github.com/dokan-dev/dokany/commit/f5afbea312cf69fcd217cb14fb2af51067d89b83

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/dokan-dev/dokany/commit/f5afbea312cf69fcd217cb14fb2af51067d89b83#diff-641844c42f5ba7de1b7fd5347b56b3eeR53 "Transformation of DOKAN_OPTION to an enumeration").

**Comment by Liryna** [comment]
This has been revert.
