### ISSUE TITLE
Feature: Is there a way to automatically mount a user file system when a PC starts?

### ISSUE THREAD

**Issue by MRYingLEE** [dokan-dev/dokany#222]
I tried Dokany and its sample Mirror. And I noticed the manual process to mount Mirror.

Just wonder whether there is a way to mount a user file system, such as Mirror, automatically when a PC starts.

Thank you in advance,

Ying

**Comment by Liryna** [comment]
Dokany device need an application (like the mirror) to run. Therefore it mean that the mirror should run at start. This can easily be made by adding the mirror in windows startup.

**Comment by MRYingLEE** [comment]
Your suggestion works. But there is an ugly terminal window shown. If a user accidently closes the window, the mounting will be terminated.
I am looking for a better solution.

Thank you for your very prompt response.
Ying

**Comment by Liryna** [comment]
Humm with a minimum of changes, you can change the mirror to become a windows service that would start automatically at boot.

You will not get terminal window shown.

**Comment by shai** [comment]
What I did was create a task in Windows _Task Scheduler_ and set it to run on Startup with a 1 minute delay (to allow Windows to connect to the LAN, just in case).

**Comment by Liryna** [comment]
@shai that's also a working idea. For LAN requirements, a service with a dependency on network service is also a great solution.
