### ISSUE TITLE
Installer writes "HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\NetworkProvider\HwOrder" wrongly

### ISSUE THREAD

**Issue by axkibe** [dokan-dev/dokany#223]
# Environment
 * Windows version: Windows 7 Enterprise
 * Processor architecture: x64
 * Dokany version: 1.0.0-RC2
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [ x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ x ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ x ] I can always reproduce the issue with the provided description below.
  - [ x ] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description

Installer sets HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control\NetworkProvider\HwOrder wrong, see
https://github.com/dokan-dev/dokany/issues/199

Changing it fixes the issue described there, I suggest having the installer write the correct value "Dokan1" vs "DokanNP1" (which it was in my case)

# Logs

**Comment by Liryna** [comment]
Hi @axkibe ,

This has already been reported here: https://github.com/dokan-dev/dokany/issues/199

I just made a test by building dokanctl, mirror, dokannp and running: `dokanctl.exe /i n` && `mirror.exe /r C:\Users /l m /n` and it work perfectly.
Can you make also a test on your side ?

**Comment by axkibe** [comment]
When can we expect RC3?

**Comment by Liryna** [comment]
@axkibe it is plan :wink:

**Comment by axkibe** [comment]
Suggestion could you note in the Release Notes of RC2 that the registry need a manual fix?

**Comment by axkibe** [comment]
OK what do I need to write there to make it work with 0.7.4?
As I've been advised* to use that until 1.0 is released.

* https://github.com/dimov-cz/win-sshfs/issues/87

**Comment by axkibe** [comment]
Ok lets forget that, I'll go with both release candidates in production, RC or not, everything else doesn't work at all (and the software I used so far crashes eitherway)
