### ISSUE TITLE
Please, try to make it more portable

### ISSUE THREAD

**Issue by dorvan** [dokan-dev/dokany#225]
- Please, try to make it more portable without installer or by a self contained service.
- add user variables serialization, due per-user environment access and common configurations.

Thanks.
Ivan

**Comment by Maxhy** [comment]
I'm not sure to understand your requests here, sorry.

 * Could you details what you mean by `portable`? I don't see how a driver could become portable as it has to be _registered_ to the system at some point. Moreover several other features also require some kind of registration (network provider, ...)
 * User variables serialization? I don't get it, but are you talking about?

**Comment by axkibe** [comment]
A system driver cannot be self contained.

**Comment by Liryna** [comment]
@dorvan feel free to reopen when you have more informations on your request.

**Comment by sergeevabc** [comment]
Veracrypt is able to run portable.
It consists of .exe binary and .sys driver.
Would be marvelous to see, for example, CPPCryptFS + Dokany portable.
