### ISSUE TITLE
Needs additional Visual Studio Redistributable 2015

### ISSUE THREAD

**Issue by axkibe** [dokan-dev/dokany#226]
# Environment
 * Windows version:  Win 7
 * Processor architecture: x64
 * Dokany version: 1.0 RC2
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [ * ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ * ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation (I suppose so)
  - [ * ] I can always reproduce the issue with the provided description below.
  - [ * ] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description
After I installed 1.0.0-RC2 using the DokanSetup_redist.exe installer, i still need to install "Visual Studio 2015 Redistributable" for 32 and 64 bit to make Dokan1.dll loadable. Otherwise it won't load.

I suggest having the installer provide the x64 and x86 restributables as well.

**Comment by Liryna** [comment]
The goal of DokanSetup_redist is specially to install the redist.
https://github.com/dokan-dev/dokany/blob/a415ea952adadf6ce9635e75df7e7a2f34e08f62/dokan_wix/Dokan_x64.wxs#L101

Are you running the x86 mirror or x64 ? (both are present in the x64 installer) In rc2 that was an issue with x86 redist that was not installed.

could you please post the setup log, in %TEMP% the Dokan ... x64 ...log file?

**Comment by axkibe** [comment]
Im currently installing a series of PCs. I'll can post the log file for the next one i get to.

**Comment by axkibe** [comment]
On this machine I had to manually post-install the x86 redistributable to make the dll loadable.

[Dokan_Library_1.0.0.102_Bundle_20160506134215.log.txt](https://github.com/dokan-dev/dokany/files/252119/Dokan_Library_1.0.0.102_Bundle_20160506134215.log.txt)
[Dokan_Library_1.0.0.102_Bundle_20160506134215_002_Dokan_x64.msi.log.txt](https://github.com/dokan-dev/dokany/files/252118/Dokan_Library_1.0.0.102_Bundle_20160506134215_002_Dokan_x64.msi.log.txt)

**Comment by Liryna** [comment]
Ah it is the x86 redistribuable, thats has been fixed already for RC3 https://github.com/dokan-dev/dokany/commit/a415ea952adadf6ce9635e75df7e7a2f34e08f62

**Comment by axkibe** [comment]
All the isues I need to workaround for the un-pre-released RC3 :-/...
