### ISSUE TITLE
Feature Request : Release an RC3 build with signed drivers

### ISSUE THREAD

**Issue by opendedup** [dokan-dev/dokany#228]
Would it be possible to release an RC3 with the signed drivers. I don't have the ability to sign code and want to test the updates made from RC2 with my opensource project, OpenDedupe.

Thanks!

Sam

**Comment by Liryna** [comment]
Hi @opendedup ,

It is plan just after https://github.com/dokan-dev/dokany/issues/165 is fixed.
The RC3 had to be release today :( but last minute issue will report it probably next week.

**Comment by Liryna** [comment]
Done https://github.com/dokan-dev/dokany/releases/tag/v1.0.0-RC3 !
