### ISSUE TITLE
Can't load dokan1 dll after installation on a clean Windows.

### ISSUE THREAD

**Issue by matepek** [dokan-dev/dokany#229]
# Environment
 * Windows version: Windows 10
 * Processor architecture: x64
 * Dokany version: 1.0.0-RC2
 * Library type (Dokany/FUSE): Dokany and DokanFuse
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after. (Not related in this case.)

# Description
Can't load dokan1.dll after installation 1.0.0-RC2 on a clean Windows. If we install "x86 - Visual C++ Redistributable for Visual Studio 2015" from (https://www.microsoft.com/en-us/download/details.aspx?id=48145) it works.

We checked,
If we install https://github.com/dokan-dev/dokany/releases/download/v1.0.0-RC2/DokanSetup.exe,
it installs the redist x64 package, but not the x86. And our 32 bit program can't load the dlls, but the dll-s are in the SysWOW64 folder.

# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
In case of BSOD, please attach minidump or dump analyze output.

**Comment by Liryna** [comment]
Hi @matepek ,

The x86 redistribuable check is missing in the RC2. It has already  been fixed for RC3 a415ea9

**Comment by matepek** [comment]
Thank you.
