### ISSUE TITLE
Feature request: about DOKAN_OPTION_NETWORK with fuse

### ISSUE THREAD

**Issue by gang929** [dokan-dev/dokany#232]
when i port a wdfs (the linux webdav client filesystem with fuse) to windows 7, I found the disk mounted by DOKAN_OPTION_REMOVABLE.
How can i mount disk with DOKAN_OPTION_NETWORK?

**Comment by Liryna** [comment]
Hi @gang929 ,

Since there is no such option on FUSE (as I know), you will need to rebuild dokan fuse and add the option here: https://github.com/dokan-dev/dokany/blob/4d11614c5df85b96442838158e75af26d3d4aa4e/dokan_fuse/src/dokanfuse.cpp#L588
