### ISSUE TITLE
Fuse call destroy at mount

### ISSUE THREAD

**Issue by gang929** [dokan-dev/dokany#233]
In my case,  I use fuse interface for porting the wdfs.
when the disk mounted,  the fuse destroy interface will be called!  it will free my all resources,  it should not be only call when disk umounted or app exit?
I checked the mount and umount implemets, found they both call opts.destroy.
after mount disk, the destroy method should called? why?

```
int impl_fuse_context::mounted(PDOKAN_FILE_INFO DokanFileInfo) {
	if (ops_.destroy)
		ops_.destroy(user_data_); // Ignoring result
	return 0;
}
```

**Comment by Liryna** [comment]
This seems to be a beautiful copy past of `unmounted` :smile: 

Fixed https://github.com/dokan-dev/dokany/commit/468e08ebfd74ce4d282896c7c3eeecf85e94a882

Thank you @gang929 for the report !
