### ISSUE TITLE
The encoding of filenames in fuse api

### ISSUE THREAD

**Issue by netheril96** [dokan-dev/dokany#235]
What is the encoding of filenames in the fuse api like `getattr(const char*, struct fuse_info*)`? Is it always encoded in UTF-8, or some locale dependent one like CP-1252?

**Comment by netheril96** [comment]
I'm porting a FUSE project to Windows, and have always assumed the filenames to be in UTF-8, as is often the case for UNIX-like systems. If dokanfuse does not encode the filenames in UTF-8, the porting would probably be a monumental task.

**Comment by Liryna** [comment]
Hi @netheril96 ,

Did you made a test ? I had no issue so far.

**Comment by netheril96** [comment]
@Liryna I haven't started the port yet.

> I had no issue so far.

Do you ever use filenames not in iso-8859-1?

**Comment by Liryna** [comment]
I am not sure :smiley:  but I think it should be simply test. I see nothing that would not make it work.

**Comment by netheril96** [comment]
Sigh, I guess you never have to deal with Unicode problems.

**Comment by netheril96** [comment]
After inspecting the source of dokan fuse, it seems that the filenames are indeed encoded in UTF-8.
