### ISSUE TITLE
Dokany FUSE does not support all args

### ISSUE THREAD

**Issue by netheril96** [dokan-dev/dokany#237]
# Environment
 * Windows version: Windows 10
 * Processor architecture: x64
 * Dokany version: 1.0.0 RC3 debug
 * Library type (Dokany/FUSE): FUSE 

# Description

`fuse_main` accepts command line args that tune its behavior, but dokany fuse completely ignores the flags. `-b` flag send the program into background, but my program still stays in the foreground. `-s` should put in single threaded mode, but my program has four threads running.

**Comment by Liryna** [comment]
Hi @netheril96 ,

See https://github.com/dokan-dev/dokany/blob/master/dokan_fuse/src/dokanfuse.cpp#L662 for a list of current dokan fuse supported.

`-s` can be easily supported with `dokanOptions->ThreadCount = 0`

the same for `-b` by using `FreeConsole` https://msdn.microsoft.com/fr-fr/library/windows/desktop/ms683150%28v=vs.85%29.aspx

Do you think you can provide a pull request for this options ?

**Comment by Liryna** [comment]
hi @netheril96 ?

Took a look at the fuse options and it seems that single thread option is supported 
https://github.com/dokan-dev/dokany/blob/4d11614c5df85b96442838158e75af26d3d4aa4e/dokan_fuse/src/dokanfuse.cpp#L596
With `-s` option https://github.com/dokan-dev/dokany/blob/4ec77fd4d4aa149910a02cd8d4b8c9b0daa92ceb/dokan_fuse/src/fuse_helpers.c#L47

Can you make a test to be sure that `-s` was ignored ? And if so too look why ?

Also `-b` option does not exist, libfuse only has `-f` (foreground) that is currently supported on cygwin only. I made a fix for having the same behaviour on Windows: https://github.com/dokan-dev/dokany/commit/8a8f4ce65893b6701cac85498951bc731c1ced30

**Comment by Liryna** [comment]
I have debug `-f` (foreground) and `-s` (single thread). They work as expected.
