### ISSUE TITLE
Dokany Installer - silent exit if same version is already installed?

### ISSUE THREAD

**Issue by Eumeltier76** [dokan-dev/dokany#238]
Hello,

i am using Dokany 0.8.0.
I would like to call the dokay installer during the installation of my own program.
This works without problems with the "/S" silent install option.

But if the Dokany 0.8.0 is already installed, the installer gives an error. Furthermore it gives back an error code so that my own installer would stop installation.

I think it would be best if the dokany installer find the version already installed to skip silently the installation without giving any error code back. (At least if called with option /S)

Has this improved with Dokay 1.0 ?

Best regards,
Martin

**Comment by Liryna** [comment]
Hi @Eumeltier76 ,

Dokany 1.0.0 use a new installer. I made a test and if Dokan is already installed and you run the installer with `/quiet` you get an `%errorlevel% = 0`.

You issue should therefore be solved.

Best regards,
