### ISSUE TITLE
DokanMountVolume intermittently fails silently because the timer thread completes before mount.

### ISSUE THREAD

**Issue by shashiu** [dokan-dev/dokany#239]
# Environment
 * Windows version: 2012 R2
 * Processor architecture: x64
 * Dokany version: 1.0.0.RC2
 * Library type (Dokany/FUSE): Dokany 
 
# Check List
  - [ X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ X] I can always reproduce the issue with the provided description below.
  - [ X] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description
The DokanMountVolume call fails intermittently and silently, because the timer thread kicked off by DokanStartCheckThread completes before the DokanCreateMountPoint call completes and proeeds to unmount while the mount is still in progess. Arranging the timeout values before kicking off the DokanStartCheckThread fixes this issue.

Fix:
Instead of
  // Start check thread
  DokanStartCheckThread(dcb);  
  ExAcquireResourceExclusiveLite(&dcb->Resource, TRUE);
  DokanUpdateTimeout(&dcb->TickCount, DOKAN_KEEPALIVE_TIMEOUT * 3);
  ExReleaseResourceLite(&dcb->Resource);
Do
  // Start check thread
  ExAcquireResourceExclusiveLite(&dcb->Resource, TRUE);
  DokanUpdateTimeout(&dcb->TickCount, DOKAN_KEEPALIVE_TIMEOUT * 3);
  ExReleaseResourceLite(&dcb->Resource);
  DokanStartCheckThread(dcb);

# Logs
Dokan kernel debug output that shows the problem.
00000399	21.17994499	[DokanFS]   IRP_MN_MOUNT_VOLUME	
00000400	21.18202591	[DokanFS]    IdType = DCB	
00000401	21.18327904	[DokanFS] FindMountEntry \DosDevices\U: -> \Device\Volume{d6cc17c5-1735-4085-bce7-964f1e9f5de9}	
00000402	21.18724632	[DokanFS] ==> DokanStartCheckThread	
00000403	21.24897957	[DokanFS] ==> DokanTimeoutThread	
00000404	21.25038719	[DokanFS] ==> ReleaseTimeoutPendingIRP	
00000405	21.25367355	[DokanFS]   IrpQueue is Empty	
00000406	21.34831619	[DokanFS]   Timeout, umount	
00000407	21.34947205	[DokanFS] ==> DokanUnmount	
00000408	21.35064316	[DokanFS]   Send Unmount to Service : \Volume{d6cc17c5-1735-4085-bce7-964f1e9f5de9}	
00000409	21.35312462	[DokanFS] <== DokanStartCheckThread	
00000410	21.40439796	[DokanFS] => DokanCreateMountPointSysProc	
00000411	21.40576935	[DokanFS] <= DokanCreateMountPointSysProc	
00000412	21.40710449	[DokanFS]   status = 0x0	
00000413	21.40967560	[DokanFS]   status = STATUS_SUCCESS	
00000414	21.46957397	[DokanFS] <== DokanFileSystemControl	
00000415	21.47083855	[DokanFS]   MountId:2

**Comment by shashiu** [comment]
[dokany-0001-Fix-for-a-bug-where-the-timer-thread-completes-befor.patch.txt](https://github.com/dokan-dev/dokany/files/265541/dokany-0001-Fix-for-a-bug-where-the-timer-thread-completes-befor.patch.txt)

**Comment by marinkobabic** [comment]
The fix can be done like suggested by you, should not have any negative side effects. Why are you not making a pull request?

**Comment by Maxhy** [comment]
Thanks for your report and patch @shashiu, after review and few tests I also agree to this change (commit 55db24ddb1fe9d6ebc2a270b24d3edf4ec3e99d7).
Pull request would be better to handle than patches as pointed out by @marinkobabic , but patch are still appreciated of course.
