### ISSUE TITLE
Mount failure in Windows Terminal Services session because the Volume device is inaccessible

### ISSUE THREAD

**Issue by shashiu** [dokan-dev/dokany#240]
# Environment
 * Windows version: 2012 R2
 * Processor architecture: x64
 * Dokany version: 1.0.0.RC2
 * Library type (Dokany/FUSE): Dokany 
 
# Check List
  - [ X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ X] I can always reproduce the issue with the provided description below.
  - [ X] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description
In a terminal services session, Dokan mount volume device is not accessible via the the \\.\ namespace. Instead, all accesses to the device for IOCTL purposes can be initiated using the MountPoint directly. The patch has been attached to this issue.  

Patch:
[dokany-0002-Mounting-fails-in-a-terminal-services-session-becaus.patch.txt](https://github.com/dokan-dev/dokany/files/265546/dokany-0002-Mounting-fails-in-a-terminal-services-session-becaus.patch.txt)

# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
Following is the verbose logs from the dokan driver and the user model DLL

00001034	26.89942360	[DokanFS] ==> DokanCreate	
00001035	26.89942360	[DokanFS]   ProcessId 3544	
00001036	26.89942551	[DokanFS]   FileName:\	
00001037	26.89942741	[DokanFS]    IdType = VCB	
00001038	26.89942932	[DokanFS]   Here we only go in if some antivirus software tries to create files before startup is finished.	
00001039	26.89942932	[DokanFS]   status = 0x0	
00001040	26.89943123	[DokanFS]   status = STATUS_SUCCESS	
00001041	26.89943314	[DokanFS] <== DokanCreate	
00001042	26.89943504	[DokanFS] ==> DokanCleanup	
00001043	26.89943695	[DokanFS]   ProcessId 3544	
00001044	26.89943886	[DokanFS]   FileName: \ FCB.FileName: (null)	
00001045	26.89944077	[DokanFS]    IdType = DCB	
00001046	26.89944077	[DokanFS]    ccb is NULL	
00001047	26.89944267	[DokanFS]   status = 0x0	
00001048	26.89944458	[DokanFS]   status = STATUS_SUCCESS	
00001049	26.89944458	[DokanFS] <== DokanCleanup	
00001050	26.89944839	[DokanFS] ==> DokanClose	
00001051	26.89944839	[DokanFS]   ProcessId 3544	
00001052	26.89945030	[DokanFS]   FileName: \ FCB.FileName: (null)	
00001053	26.89945221	[DokanFS]    IdType = DCB	
00001054	26.89945412	[DokanFS]    ccb is NULL	
00001055	26.89945602	[DokanFS]   status = 0x0	
00001056	26.89945602	[DokanFS]   status = STATUS_SUCCESS	
00001057	26.89945602	[DokanFS] <== DokanClose	
00001058	26.91243744	[3544] Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}: 5	
00001059	26.91261101	[3544] Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}: 5	
00001060	26.91281509	[3544] Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}: 5	
00001061	26.91296768	[3544] Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}: 5	
00001062	26.91311455	[3544] Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}: 5	
00001063	26.91319084	[DokanFS] ==> DokanCleanup	
00001064	26.91319656	[DokanFS]   ProcessId 3544	
00001065	26.91319847	[DokanFS]   FileName: (null) FCB.FileName: (null)	
00001066	26.91320038	[DokanFS]   status = 0x0	
00001067	26.91320229	[DokanFS]   status = STATUS_SUCCESS	
00001068	26.91320229	[DokanFS] <== DokanCleanup

**Comment by marinkobabic** [comment]
The access of the file failed also when the DOKAN_OPTION_CURRENT_SESSION was used?

**Comment by Maxhy** [comment]
Oh indeed. This is related on how global kernel objects are accessible from Windows Terminal Services as you pointed out, so yes @marinkobabic this will always fail I believe as we try to access the global device directly.
@shashiu your fix is fine as all these object access are currently done on the same session than the mount application. For the sake of knowledge, could you just confirm that changing https://github.com/dokan-dev/dokany/blob/55db24ddb1fe9d6ebc2a270b24d3edf4ec3e99d7/dokan/dokan.c#L339 to `wcscpy_s(DestinationBuffer, DestinationBufferSizeInElements, L"\\\\.\\Global");` also fix this issue (I cannot test TSE right now)? Thanks.

**Comment by marinkobabic** [comment]
If he uses the current session option the device is not anymore global. So why it should fail? MountPoint is just a link to an existing device. Maybe I'm missing here something? 

Should the drive be global resp. for all sessions accessible or just for the current one?

**Comment by shashiu** [comment]
Hi Maxime,
I can confirm that finding the volume device in the L"\\\\.\\Global" namespace does NOT fix the issue. It also fails with ERROR_NOT_FOUND. The only way to fix this appears to be to access the device it via the mount point symbolic link.  

- Shashi
Date: Mon, 16 May 2016 13:32:32 -0700

**Comment by shashiu** [comment]
Hi Marinko,
The device namespace (\\.\Volume\{xxx}) is not directly accessible from the session, even though the device is being mapped into the session. The mount point symbolic link is the only way that the device object seems to be accessible. There is not enough MSDN documentation on why that might be the case, but, that appears to be how it works.
- Shashi
Date: Mon, 16 May 2016 14:10:07 -0700

**Comment by marinkobabic** [comment]
Thanks for feedback. Have now more background information  http://stackoverflow.com/questions/21703592/open-device-name-using-createfile

Names of the form \Device\xxx are internal NT object manager names which are inaccessible to Win32. You will only be able to access your device if it creates a symbolic link to \Device\MyDevice from the \??\ directory. Objects in the \??\ kernel directory show up through \\.\ in Win32. Use Winobj in the DDK (or download it from www.sysinternals.com) to check.

So please do a pull request. :smiley:

**Comment by shashiu** [comment]
Hi,
I dont have access to create a remote branch on the dokany project, to be able to create a pull request. I have, however, included a patch with the issue ticket.

- Shashi

Date: Mon, 16 May 2016 23:33:47 -0700

**Comment by Liryna** [comment]
Hi @shashiu ,

I tested your patch by simply running the `mirror.exe` (locally without TSE).
It seems that the mirror is no longer able to communicate with the driver:
```
Dokan: debug mode on
Dokan: use stderr
AllocationUnitSize: 512 SectorSize: 512
device opened
mounted: f -> \Volume{d6cc17c5-1730-4085-bce7-964f1e9f5de9}
Mounted
Dokan Error: CreateFile failed f: (\\.\Volume{d6cc17c5-1730-4085-bce7-964f1e9f5de9}) 2
Dokan Error: CreateFile failed f: (\\.\Volume{d6cc17c5-1730-4085-bce7-964f1e9f5de9}) 2
Dokan Error: CreateFile failed f: (\\.\Volume{d6cc17c5-1730-4085-bce7-964f1e9f5de9}) 2
Dokan Error: CreateFile failed f: (\\.\Volume{d6cc17c5-1730-4085-bce7-964f1e9f5de9}) 2
Dokan Error: CreateFile failed f: (\\.\Volume{d6cc17c5-1730-4085-bce7-964f1e9f5de9}) 2
Unmounted

unload
Success
```

Kernel logs show that it is correctly mount but unmount just after since there is no communication with the mirror.

**Comment by marinkobabic** [comment]
@Liryna 
Did you try to CreateFile using  \\.\f instead of just F:

_stprintf(szDriveCreate, _T(\\\\.\\%c), cDrive);

**Comment by Liryna** [comment]
@marinkobabic It also fail if I replace 
https://github.com/dokan-dev/dokany/blob/a8d06c7ff30e05f8243ed28c06b09f1d0b6f17d3/dokan/dokan.c#L369
by `device = CreateFile(L"\\\\.\\f",`

**Comment by marinkobabic** [comment]
Have analyzed the code. The code should work like it is, so no patch is needed for DeviceName. Here my arguments:

1. IOCTL_EVENT_START is sent from user mode application
2. DokanEventStart is executed
3. DokanCreateDiskDevice is executed
4. DOKAN_DISK_DEVICE_NAME is created \\Device\Volume{xy} = dcb ->DiskDeviceName
5. DOKAN_SYMBOLIC_LINK_NAME is created \\DosDevices\\Global\\Volume{xy} = dcb->SymbilicLinkName
6. IoCreateSymbolicLink(dcb->SymbolicLinkName, dcb->DiskDeviceName);
7. Mount happens and so the DokanCreateMountPointSysProc is executed
8. IoCreateSymbolicLink(Dcb->MountPoint, Dcb->DiskDeviceName);
9. The dcb->SymbolicLinkName is used to set the driverInfo->DeviceName  

MountPoint and SymbolicLinkName point to DiskDeviceName. The difference here is that the 

- MointPoint is for example \\DosDevices\F and SymbolicLinkName is \\DosDevices\\**Global**\\Volume{xy}
- if Dcb->MountGlobally the symbolic link for the MointPoint is created in a system thread which is never the case for the dcb->SymbolicLinkName

As we can see here the usermode uses always the SymbolicLinkName to comunicate with the driver. So the reported issue is not related to the CreateFile which uses DokanInstance->DeviceName. 
**Instance->DeviceName = driverInfo.DeviceName = dbc->SymbolicLinkName** 

The source of the problem may be the mentioned two differences above.

**Comment by marinkobabic** [comment]
I have installed Windows 2012 R2 x64 as virtual machine. I can run mirror without any issue in two separate remote desktop sessions at the same time. So how to reproduce your issue?

**Comment by shashiu** [comment]
Is this with /c (current session) flag ? 
It says its mounted but when I access it, I can't access any of the files in the mirrored drive. 
Date: Thu, 19 May 2016 14:27:49 -0700

**Comment by shashiu** [comment]
Here's the exact repro steps.
- Run mstsc.exe and log into the RDP session- Run the dbgview sysinternals tool to watch the debug output (make sure to enable all the Capture options)- Run a command prompt- Run mirror /m /c /d /r <yourdirectory> /l m- Watch the debug out in dbgview. Notice there are 'Dokan Error: CreateFile failed ... 2' messages- Try to open the m: drive, you wont be able to even though it is mounted.
From: shashi_uli@hotmail.com
To: reply@reply.github.com; dokany@noreply.github.com
CC: mention@noreply.github.com
Subject: RE: [dokan-dev/dokany] Mount failure in Windows Terminal Services session because the Volume device is inaccessible (#240)
Date: Thu, 19 May 2016 22:32:14 -0400




Is this with /c (current session) flag ? 
It says its mounted but when I access it, I can't access any of the files in the mirrored drive. 
Date: Thu, 19 May 2016 14:27:49 -0700

**Comment by marinkobabic** [comment]
Does the user have access to the <yourdirectory> in your case? What when you use for example c:\temp and you set full access ntfs rights for everyone?

**Comment by marinkobabic** [comment]
What happens when you don't use the option /m in your case?

**Comment by shashiu** [comment]
The user has full access to the directory I am mounting with mirror.

**Comment by shashiu** [comment]
I am not using the /n option. Not using the /m option makes no difference. Same error.

**Comment by marinkobabic** [comment]
The usermode says access denied but there is nothing in the kernel log. Please can you provide the full kernel log? The mirror is executed in your case in a console with no admistrative rights hopefully, just a double click on a link which contains the required parameters? Do you have any special antivirus software running on your machine? Any special policies?

**Comment by marinkobabic** [comment]
Please run process monitor by sysinternals. Maybe it will provide more information about access denied.

**Comment by Maxhy** [comment]
@marinkobabic as you seems to have noticed in your 17 days ago explanation, Device Object are created globally and only mount point is created global or according to the session.
It's why I asked about the `\Global` prefix test.

After testing by myself, adding this prefix as I specified doesn't change anything. It's not that it fails, it's just literally the same thing that without on current OS versions, even when using Remote Desktop connection.
Then I found out that I can reproduce @shashiu behavior but only if the session was created remotely (not a disconnect from console/connect remotely), and only at the first attempt. Second attempt will mount successfully. Definitely not a namespace issue.

After investigation it seems to be related to `BroadcastSystemMessage` taking a lot of time (something like 30sec on my side). I don't know why here and it may be related to the system on something out of Dokan scope. Anyway KeepAlive and Loop threads should be created before forcing all applications to realize about the new mount point ; and this seems to fix the issue (BroadcastSystemMessage will still hang but mount will not fail).

See https://github.com/dokan-dev/dokany/commit/e43052006c96bc440dc9b6481b3863aac30bc9da.
@shashiu @gh223682 please test and confirm, thanks.

**Comment by gh223682** [comment]
@Maxhy I have not been able to reproduce this behavior in Windows 10 x64, trying to mount a volume with EncFS4Win.

Furthermore, if I log in via a Terminal Services session to an already-established regular desktop session where a Dokan volume is already mounted, I cannot mount that same volume again after unmounting.

**Comment by Rondom** [comment]
With current master it works for me with the Dokan Mirror but fails with the FUSE Mirror. I am using Win 2008 R2 x64 and I am connecting via RDP. Running as Administrator will help.

FUSE:

	C:\>"c:\Program Files\Dokan\Dokan Library-1.0.0\sample\fuse_mirror\mirror.exe" L: -f -d
	Dokan: debug mode on
	Dokan: use stderr
	AllocationUnitSize: 512 SectorSize: 512
	device opened
	Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1731-4085-bce7-964f1e9f5de9}: 5
	Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1731-4085-bce7-964f1e9f5de9}: 5
	Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1731-4085-bce7-964f1e9f5de9}: 5
	Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1731-4085-bce7-964f1e9f5de9}: 5
	Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1731-4085-bce7-964f1e9f5de9}: 5
	Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1731-4085-bce7-964f1e9f5de9}: 5
	Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1731-4085-bce7-964f1e9f5de9}: 5
	Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1731-4085-bce7-964f1e9f5de9}: 5
	Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1731-4085-bce7-964f1e9f5de9}: 5
	Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1731-4085-bce7-964f1e9f5de9}: 5
	mounted: L: -> \Volume{d6cc17c5-1731-4085-bce7-964f1e9f5de9}

	unload
	send global release for L:

Dokan:

	C:\>"c:\Program Files\Dokan\Dokan Library-1.0.0\sample\mirror\mirror.exe" /r c:\temp /l L: /s /d
	## Attempting to add SE_SECURITY_NAME privilege to process token ##
	  failed: Unable to adjust token privileges: 1300
	Failed to add security privilege to process
		=> GetFileSecurity/SetFileSecurity may not work properly
		=> Please restart mirror sample with administrator rights to fix it
	Dokan: debug mode on
	Dokan: use stderr
	AllocationUnitSize: 512 SectorSize: 512
	device opened
	mounted: L: -> \Volume{d6cc17c5-173d-4085-bce7-964f1e9f5de9}
	Mounted

**Comment by Liryna** [comment]
@Rondom that's strange :hushed: If it work for the mirror it should with FUSE.
Just to be sure, can you copy the `dokan.dll` from the mirror to fuse_mirror ?
(the fix was in it)

**Comment by Rondom** [comment]
Ooops... my fault! I had old copies of the DLLs lying in the fuse_mirror-directory. Pretty easy to miss...

Anyways, I can now confirm that this works for me with the latest version for both FUSE and Dokan Mirror.

**Comment by Liryna** [comment]
Ah great ! :+1: Thank you for your time and feeback @Rondom and others !
