### ISSUE TITLE
dokan 0.7.4 hangs when renaming file in explorer in Windows 10

### ISSUE THREAD

**Issue by zTrix** [dokan-dev/dokany#241]
# Environment
 * Windows version: Win10 x64
 * Processor architecture: x64
 * Dokany version: 0.7.4
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description

Dokany 0.7.4 is described to support win10, but seems buggy. Here is the step to reproduce:

1. Installed dokany 0.7.4 version(downloaded from https://github.com/dokan-dev/dokany/releases/download/v0.7.4/DokanInstall_0.7.4.exe) on windows 10, x64 version. (downloaded from https://www.microsoft.com/zh-cn/software-download/windows10ISO)
1. use mirror to mount local fs to another virtual disk: `mirror.exe /r c:\dt /l m /t 1 /d /s /n`
1. create a file with name `asdf`
1. rename the file in explorer.(Press F2, rename, hit enter)
1. the operation will hang about 1min to be successful.(expected to be 
1. I tried rename operation in cmd shell using `ren` command, which works just fine, `ren` returned success instantly.

And version 1.0.0rc2 seems to be OK.

# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
In case of BSOD, please attach minidump or dump analyze output.

**Comment by zTrix** [comment]
Here is the log.

[dokan-log.txt](https://github.com/dokan-dev/dokany/files/265637/dokan-log.txt)

**Comment by Liryna** [comment]
Hi @zTrix ,

There is a lots of changes since 0.7.4. It gonna be hard for me to tell what change fixed the issue.
I can only propose you to use the new 1.0.0 RC or to try to convert the new mirror for 0.7.4 (to test if the fix was in it)

**Comment by zTrix** [comment]
Hi, @Liryna 

Thanks for your quick response, but our applications are using 0.6 for a long time, and 1.0.0 RC seems to break the API compatibility, so we're unable to switch to 1.0.0 RC for now.

**Comment by Liryna** [comment]
Ok I see.

I have you seen https://github.com/dokan-dev/dokany/wiki/Update-dokan-legacy-application-to-Dokany ?
With mirror as example and the wiki, normally your implementation should be update in less than a hour.

**Comment by zTrix** [comment]
I'll have a try to see whether I can find the root cause of this issue.

**Comment by zTrix** [comment]
I've tried v0.8.0 redist version, which works without this issue, so this issue should be solved between 0.7.4 and 0.8.0.

**Comment by Liryna** [comment]
The changes are pretty big: https://github.com/dokan-dev/dokany/compare/v0.7.4...v0.8.0
I really cannot help you on this sorry :(

**Comment by Maxhy** [comment]
I cannot help neither. I believe you should be able to identify the fix by applying commits one after another from 0.7.4 and making the same test for each change.
I'm gonna close this as it is not a current issue anymore. Good hunt ;)!

**Comment by zTrix** [comment]
Further investigation shows that if compiled using windows 10(vs2015, latest wdk and sdk), v0.7.4 also works, but the binary downloaded from github (https://github.com/dokan-dev/dokany/releases/download/v0.7.4/DokanInstall_0.7.4.exe) is the buggy one, so I think that it should be a issue related to windows API compatibility.

**Comment by Liryna** [comment]
:+1: @zTrix Thank you for your feedback ! It gonna help peoples that will face this issue with the 0.7.4.
