### ISSUE TITLE
Can not install in windows server 2008 R2

### ISSUE THREAD

**Issue by superhq** [dokan-dev/dokany#244]
# Environment
 * Windows version: Windows Server 2008 R2 Enterprise
 * Processor architecture: 64 bit Intel(R) Core(TM) i5-3317U 
 * Dokany version: 1.0.0-RC3
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description
I run DokanSetup.exe in WS-2008-R2, everything seems find. But the mirror sample can not work,and output error message:

> Can't install driver

# Logs
I try to reinstall the driver use dokanctl.exe, and the log as follow:

> PS C:\Program Files\Dokan\Dokan Library-1.0.0> .\dokanctl.exe /i  d
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
Installing driver...
DokanServiceInstall: Service (Dokan1) is already installed
Driver install failed
PS C:\Program Files\Dokan\Dokan Library-1.0.0> .\dokanctl.exe /r d
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
Removing 'Dokan1'...
DokanServiceControl: Service (Dokan1) deleted
'Dokan1' removed.
PS C:\Program Files\Dokan\Dokan Library-1.0.0> .\dokanctl.exe /i d
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
Installing driver...
DokanServiceInstall: Service (Dokan1) installed
DokanServiceControl: Failed to start service (Dokan1). error = 577
DokanServiceInstall: Service (Dokan1) start failed
Driver install failed

I try to uninstall the driver,restart OS and reinstall the driver, but the result is same.

**Comment by Liryna** [comment]
Hi @superhq ,

Error 557 mean that the system does not recognize the driver signature.
You will need to install all windows updates.
See https://github.com/dokan-dev/dokany/issues/187 (2008 r2 is the same as Win7)
