### ISSUE TITLE
Dokany FUSE freezes when attempting to access (empty?) folders.  

### ISSUE THREAD

**Issue by jetwhiz** [dokan-dev/dokany#245]
# Environment
 * Windows version: Windows 7 
 * Processor architecture: 32-bit
 * Dokany version: 1.0.0-RC3
 * Library type (Dokany/FUSE): FUSE
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description
Starting with Dokany 1.0.0-RC3 (issue does not exist in RC2), FUSE freezes when attempting to access (empty?) folders.  

When using fuse_mirror, it is not possible to access any folders without Explorer freezing. 

# Logs
[fuse_mirror.txt](https://github.com/dokan-dev/dokany/files/276156/fuse_mirror.txt)

**Comment by Liryna** [comment]
Hi @jetwhiz ,

(Ths fuse debug output is horrible :smile: , it will need to be changed https://github.com/dokan-dev/dokany/issues/247)

I had not the time to make the test for now but if explorer is freezing, it is probably because his is making a loop a request until having a valid answer (that he seems to not get).
Have you been able to see if there is such request made ?

**Comment by Liryna** [comment]
Hi @jetwhiz ,

I made a test and have been able to access an empty folder without issue :cry: 
![Uploading Sans titre.png…]()

Do you have more information for me to reproduce the issue ?

**Comment by jetwhiz** [comment]
Actually, after further testing I found that the folder doesn't even need to be empty.  

I can successfully navigate folders on the command line, but it is not possible to do via Explorer.  

Also, I have mounted my FS directly to a drive letter (Z:), and it is impossible to navigate any folders below Z:\ via Explorer.  The folders eventually load, but there is a very long delay (a few minutes).  I can right-click a folder and select "Properties" and the information all loads fine, though.  

Do you have any suggestions on which FUSE callbacks I can target for deeper debugging to see where the issue lies?

**Comment by Liryna** [comment]
Actually, I don't really have ideas :cry: 

Does the mirror is still running ? no crash of the mirror ?

Dokan FUSE logs really need to be implemented :'(

**Comment by Rondom** [comment]
@jetwhiz From your description in your last comment that sounds exactly like the issue I am experiencing! Working with the filesystem on the command line works fine, but when changing folders in explorer there is a hang of approximately a minute where the log is stuck at GetFileSecurity. Your logs looked different, so I thought it is not the same issue. I am going to come back with more analysis on Monday.

**Comment by jetwhiz** [comment]
@Rondom I suspect the problem is coming from AddSeSecurityNamePrivilege or FuseGetFileSecurity, since that's the only real change to FUSE between RC2 and RC3 (and RC2 works fine for me).  

See https://github.com/dokan-dev/dokany/compare/v1.0.0-RC2...v1.0.0-RC3#diff-6d5ff575218237cd8f26b3588063923d

**Comment by Rondom** [comment]
I am going to try on Monday with the patch reverted and do some debugging as well.

**Comment by jetwhiz** [comment]
@Liryna @Rondom 

I just removed the FuseGetFileSecurity operation and it appears to be working correctly now, so the problem does originate from GetFileSecurity.  

After some debugging I found that the blockage is occurring on the CreateFileW call (https://github.com/dokan-dev/dokany/compare/v1.0.0-RC2...v1.0.0-RC3#diff-6d5ff575218237cd8f26b3588063923dR498), though I'm not sure why.

**Comment by Liryna** [comment]
Add @matepek to the issue.

**Comment by Rondom** [comment]
@Liryna What OS are you trying to reproduce this on?
I am using Win 2008 R2 and @jetwhiz is using Win 7.

I have not done in-depth debugging, yet, but it seems like some deadlock. I can also trigger the bug in a directory of 5 files and single-clicking (i.e. selecting) individual files in quick succession. If I wait until the debug log in the console output in the console window has stopped between each click, the hang will not occur.

**Comment by Liryna** [comment]
I made the test only on Win10 x64 without issues for now.

The FUSE FuseGetFileSecurity does not add really much See: https://github.com/dokan-dev/dokany/pull/211
FuseGetFileSecurity is more a hack fix, if the behaviour is unstable and impossible to fix, we will have to revert it.

**Comment by matepek** [comment]
Hello,
Sorry to hear this issue.
It is developed on a Win10 - 64bit, and tested on other Win10s, but probably not on Win7 - 32bit.
Hopefully, I can look after it at the next week.

**Comment by Maxhy** [comment]
#211 is definitely a hack fix but does the job as long extended attributes (to do ACL mapping) are not handled.
But then I believe it would be better for now to avoid a recursive call to the file system (which is hanging here btw) and create a permissive new security descriptor.
@matepek as it is related to your PR do you think you could handle this new change again and do appropriate tests? I think you may be inspired by https://msdn.microsoft.com/en-US/library/windows/desktop/aa446595(v=vs.85).aspx but for Directory object. Thanks!

**Comment by Liryna** [comment]
I have changed FuseGetFileSecurity implementation by using sddl from dokan kernel for all folders.
https://github.com/dokan-dev/dokany/commit/11bb829a70961e797adfef1354a98fada3491af7

I have tested the code but since I never faced the issue of create folder needing admin rights, can someone test and valide if the behaviour is correct and stable ?

**Comment by jetwhiz** [comment]
@Liryna - This seems to fix the issue for me!

**Comment by Liryna** [comment]
Ah great @jetwhiz thank you for your feedback!

**Comment by Rondom** [comment]
Good to hear.
Maybe @matepek can test whether the patch fixes the issue which made the patch necessary.

**Comment by matepek** [comment]
Hello,
Sorry for the late answer. ([Reason :)](http://www.commitstrip.com/en/2014/09/08/the-other-infinite-loop-that-all-coders-fear/))
Thanks for thinking of us.
I tried out, it works like before my "fix", but it's OK for now.
We haven't gotten time yet to came out with a better solution.
