### ISSUE TITLE
Request - Release with recent fixes

### ISSUE THREAD

**Issue by taruti** [dokan-dev/dokany#248]
Currently stuck with 0.8 due to 1.0RC3 suffering from the bug fixed in master:
https://github.com/dokan-dev/dokany/commit/55db24ddb1fe9d6ebc2a270b24d3edf4ec3e99d7

Any hope to push a RC/build with that one out?

**Comment by Rondom** [comment]
Maybe we can configure the artifacts-section in appveyor for this. This way people can test builds easily, saving them from setting up a complete dev-environment with VS, DDK and whatnot.

See http://www.appveyor.com/docs/packaging-artifacts and http://www.appveyor.com/docs/appveyor-yml

**Comment by Liryna** [comment]
Yes, this can be a solution ! Since the installer is already build it should not be difficult.
The only issue is that it is self signed so the person who will want to test will have to install the certificat used by appveyor
As explained here: https://github.com/dokan-dev/dokany/wiki/Build#signing

**Comment by Liryna** [comment]
Done with https://github.com/dokan-dev/dokany/commit/ba95eec566a0e0de39538b9b725bfddee32c2065
You will now find a Dokan Installer self signed for each commit/appveyor build.
Ex: https://ci.appveyor.com/project/Maxhy/dokany/branch/master/job/c8u7yfpik1xla50a/artifacts

The installer is self signed with certificates that you can find in `cert` folder.
To run correctly the installer, you will need the first time to install the Dokan self signed certificates
```
cd dokany
Powershell.exe -executionpolicy remotesigned -File .\cert\dokan-import.ps1
//reboot computer before running dokan installer
```

**Comment by Rondom** [comment]
Thanks!
