### ISSUE TITLE
Mountpoint to NTFS-Path don't work

### ISSUE THREAD

**Issue by landrix** [dokan-dev/dokany#25]
i tested .net sample and delphi sample. in both apps, i can't mount to an empty ntfs-path like d:\test

DokanMain retrn with DOKAN_MOUNT_POINT_ERROR

**Comment by Liryna** [comment]
Does the test folder exist ?
Can you make a test with a valid drive letter that is available ?

**Comment by landrix** [comment]
Strangely, I have found the error. if the mountet path contains "share" only ones at the end, mounting fails:

D:\share
D:\someone\share

this works

D:\share\empty
D:\share\share
D:\someone\share\share

**Comment by landrix** [comment]
As yet to be another problem. I look further.

**Comment by landrix** [comment]
after a reboot, now it now it works also with "share", i have no idea, you?

you can close this issue, if you want

**Comment by Liryna** [comment]
I have really no idea :(
You should only get this error only if the folder does not exist.
No links with "share" as I know :(
