### ISSUE TITLE
Bring the libdokanfuse headers' directory-structure in line with libfuse

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#250]
The current directory structure of Dokan_FUSE is not in line with the original libfuse. Compiling the same codebase with both libfuse and libdokanfuse currently requires "hacks" such as symlinking or manually copying files around (if "advanced" headers such as fuse_opt.h are used). What do others think about bringing libdokanfuse in line with libfuse in that regard to simplify things?

The organization of the source does not need to reflect the installation-path of the headers (it does not for libfuse either) If people prefer to leave the files as they are in the source tree it can also be solved within CMakeLists.txt

libfuse puts its headers in a subdirectory inside include. [The fuse.h at the toplevel is only a dummy (see link)](https://github.com/libfuse/libfuse/blob/fuse-2.9.6/include/old/fuse.h).

    fuse296/include
    ├── fuse
    │   ├── cuse_lowlevel.h
    │   ├── fuse_common_compat.h
    │   ├── fuse_common.h
    │   ├── fuse_compat.h
    │   ├── fuse.h
    │   ├── fuse_lowlevel_compat.h
    │   ├── fuse_lowlevel.h
    │   └── fuse_opt.h
    ├── fuse.h
    └── ulockmgr.h

Dokan_FUSE currently looks like this:

    dokan_fuse/include
    ├── dokanfuse.h
    ├── fuse_common.h
    ├── fuse.h
    ├── fusemain.h
    ├── fuse_opt.h
    ├── fuse_sem_fix.h
    ├── fuse_win.h
    ├── ScopeGuard.h
    └── utils.h

**Comment by Liryna** [comment]
@Rondom Hi, 

That's a good idea! Do you think you can make a pull request that fix it?

**Comment by Rondom** [comment]
That's why I asked :-)

**Comment by Liryna** [comment]
:heart:

Do not forget the installer also :smiley: !

**Comment by Liryna** [comment]
@Rondom , did had the time to see about this issue ?
(If I do not make mistakes I think I seen a fix for it in your repository at a moment)
