### ISSUE TITLE
FUSE mirror crashes with --help

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#253]
# Environment
 * Windows version: 2008 R2
 * Processor architecture: x64
 * Dokany version: 1.0-RC3
 * Library type (Dokany/FUSE): FUSE
 
# Check List
  - [ x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ x ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ x ] I can always reproduce the issue with the provided description below.
  - [ x ] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description
Running the Cygwin FUSE mirror (x64) with --help
Actual: Crashes with `1 [main] mirror 4064 cygwin_exception::open_stackdumpfile: Dumping stack trace to mirror.exe.stackdump`

Expectation: Help text is printed without crash

**Comment by jetwhiz** [comment]
I notice the same issue when running help via the FUSE API: 

````C++
  int argc = 2;
  const char *argv[] = {"...", "-h"};
  fuse_main(argc, const_cast<char **>(argv), (fuse_operations *)NULL, NULL);
````

This results in a crash of our program.

**Comment by monceaux** [comment]
I was able to get this working after I determined it to be some kind of 64-bit vs. 32-bit unsigned integer issue in fuse_opt.c on line 200.

https://github.com/dokan-dev/dokany/blob/e43052006c96bc440dc9b6481b3863aac30bc9da/dokan_fuse/src/fuse_opt.c#L200

All of this was done on Windows 7 64-bit running cygwin64.

I changed the line from:

```
if (opt->offset == (unsigned long)-1) {
```
to:
```
if ((uint32_t)(opt->offset) == (uint32_t)(-1)) {
```

I then recompiled the `cygdokanfuse1.dll`, and recompiled the `fusexmp.c`.  Running the following then works:

```
$ ./a.exe -h
usage: ./a mountpoint [options]

general options:
    -o opt,[opt...]        mount options
    -h   --help            print help
    -V   --version         print version

FUSE options:
    -d   -o debug          enable debug output (implies -f)
    -f                     foreground operation
    -s                     disable multi-threaded operation

    -o umask=M             set file and directory permissions (octal)
    -o fileumask=M         set file permissions (octal)
    -o dirumask=M          set directory permissions (octal)
    -o fsname=M            set filesystem name
    -o volname=M           set volume name
    -o setsignals=M        set signal usage (1 to use)
    -o daemon_timeout=M    set timeout in seconds
    -n                     use network drive
```

I don't have the time to create a pull request at the moment, but will try to shortly.

**Comment by Liryna** [comment]
Hi @Rondom, @monceaux,

Thank you for you report and your analyse !

@monceaux you have found the source of the issue but there were a more easy fix :smiley: .
offset was incorrectly set to (unsigned int) -1 so the condition would never succeed :cry: 

Fixed here: https://github.com/dokan-dev/dokany/commit/aad686c7bfc640c9be34618f51ef758e759c8d55
