### ISSUE TITLE
Installer requires .NET Framework 4.0 which is not included in Win7

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#254]
# Environment
 * Windows version: 2008 R2
 * Processor architecture: x64
 * Dokany version: master

# Description
The installer's custom actions (WiXCA) target .NET 4.0. Windows 7 and Windows 2008 R2 do not include .NET 4.0 (they come with 3.5) which will make the installation fail if it is not installed. The error is buried deep in the logs and it is quite hard to find out why the installation fails, especially because the error is not in the main log. I had to dig in the file system to find the log that finally provided me with the root-cause.

# Suggested Action
* Preferred: port the WiXCA project to .NET 3.5 (preferred). Maybe someone with .NET skills can volunteer?
* Workaround: Patch installer to check for at least .NET 4.0. It is hard to argue though, why one should download hundreds of MBs, when it is only needed during installation.

# Logs
* [Dokan_Library_1.0.0.102_Bundle_20160425124552.log.txt](https://github.com/dokan-dev/dokany/files/303123/Dokan_Library_1.0.0.102_Bundle_20160425124552.log.txt) (unhelpful log given by installer)
* [Dokan_Library_1.0.0.102_Bundle_20160425124552_001_Dokan_x64.msi.log.txt](https://github.com/dokan-dev/dokany/files/303122/Dokan_Library_1.0.0.102_Bundle_20160425124552_001_Dokan_x64.msi.log.txt) (helpful log found in filesystem)

**Comment by js69** [comment]
It's an easy fix, will do it tomorrow.

**Comment by js69** [comment]
See https://github.com/dokan-dev/dokany/pull/255

**Comment by Rondom** [comment]
Great, thanks!

> CustomAction uses NET4 features, so retargeting wasn't possible.

:-'( Well, ok then. It is probably not worth the effort to jump through hoops for an old OS. I tried changing the target framework and all I got was a slew of error-message which is why I filed this issue.

**Comment by js69** [comment]
For Dokany to work Windows 7 needs to have SP1 and a bunch of other recent updates installed as well so artificially attempting to stay compatible with systems that lack basic components like NET4 might be a valiant, but somewhat quixotic effort.

**Comment by Rondom** [comment]
I agree. I have prepared some patches that detect this properly in the installer and will submit a pull request next week.

**Comment by Liryna** [comment]
Hi @Rondom ,

Thank you for your feedback !

@js69 changes has been merged

@Rondom , do you have the possibility to test the installer from appveyor ?
https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.0-595/job/8ijit6j59gdua1pn/artifacts
The installer is self signed with certificates that you can find in cert folder.
To run correctly the installer, you will need the first time to install the Dokan self signed certificates

```
cd dokany
Powershell.exe -executionpolicy remotesigned -File .\cert\dokan-import.ps1
//reboot computer before running dokan installer
```
