### ISSUE TITLE
FuseCreateFile's FileAttributes parameter only passes through lowest 16 bit attributes 

### ISSUE THREAD

**Issue by jetwhiz** [dokan-dev/dokany#259]
From what I can tell, only the bottom 16 bits for FileAttributes are passed through to FuseCreateFile (the basic FILE_ATTRIBUTE_* attributes).  All of the FILE_FLAG_* attributes are not available (the ones defined in the upper 16 bits).  

For instance, calling "FILE_FLAG_DELETE_ON_CLOSE" or "FILE_FLAG_RANDOM_ACCESS" do not show up in the debug printout for the FileAttributes variable.  Right now, the top 16 bits are always 0. 

Is it possible you can implement this functionality, so that our program can detect the FILE_FLAG_* attributes being set?  We need to know when the DELETE_ON_CLOSE functionality has been requested from calling programs.

**Comment by Liryna** [comment]
Hi @jetwhiz ,

FuseCreateFile is getting the Kernel flags of the createfile. The kernel attributes does not have the same value as user land. To convert the kernel flag to user flags, we need to call DokanMapKernelToUserCreateFileFlags.

I have commit a patch that will give you the ability to get this flags: https://github.com/dokan-dev/dokany/commit/043fc668444e4c9f9bdfbddfb61ce8f8c381a57f

After this line: https://github.com/dokan-dev/dokany/commit/043fc668444e4c9f9bdfbddfb61ce8f8c381a57f#diff-6d5ff575218237cd8f26b3588063923dR180
You will be able to get the correct values of AttributesAndFlags & creationDisposition.

Can you make a test and tell me if this need improvement and your point of view of it ?

**Comment by jetwhiz** [comment]
@Liryna The results appear to be the same with the above patch applied.  

CreateFileW command used: 
````C++
HANDLE h = CreateFileW(s2ws(filename).c_str(), GENERIC_READ | GENERIC_WRITE, NULL, NULL, CREATE_ALWAYS, FILE_FLAG_DELETE_ON_CLOSE | FILE_ATTRIBUTE_TEMPORARY | FILE_ATTRIBUTE_SYSTEM | FILE_ATTRIBUTE_HIDDEN, NULL);
````

Dokany debug output: 
````cmd
###Create 0017
CreateFile : \testers.txt
        DesiredAccess: FILE_GENERIC_WRITE|FILE_GENERIC_READ|DELETE
        ShareAccess: 0x0
        Disposition: FILE_OVERWRITE_IF (5)
        Attributes: 262 (0x106)
        Options: 4192 (0x1060)
encfs_open attributes for /testers.txt: 0x00000106
````

I would expect Attributes to read: 0x04000106, but it only provides 0x106 (FILE_ATTRIBUTE_TEMPORARY | FILE_ATTRIBUTE_SYSTEM | FILE_ATTRIBUTE_HIDDEN).  The FILE_FLAG_DELETE_ON_CLOSE attribute should be setting 0x04000000 (https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx).

**Comment by Liryna** [comment]
@jetwhiz ,

I have not changed the debug output :smile: 
I just converted the flag in `fileAttributesAndFlags` and `creationDisposition` to give you the ability to make the check as you want `fileAttributesAndFlags & FILE_FLAG_DELETE_ON_CLOSE`.

But I agree that the debug output should be probably restore as it was before:
https://github.com/dokan-dev/dokany/pull/91/files#diff-96df580dcf9bedf28ac688489cbf7c1cL196
(Printing user land variable values)

**Comment by Liryna** [comment]
Something like https://github.com/dokan-dev/dokany/commit/9a44ee2f2171013a712fe2c7256c44c47045d1f2

**Comment by Liryna** [comment]
@jetwhiz ,I have not changed the debug output :smile: 
I just converted the flag in fileAttributesAndFlags and creationDisposition to give you the ability to make the check as you want `fileAttributesAndFlags & FILE_FLAG_DELETE_ON_CLOSE`.

But I agree that the debug output should be probably restore as it was before:
https://github.com/dokan-dev/dokany/pull/91/files#diff-96df580dcf9bedf28ac688489cbf7c1cL196
(Printing user land variable values)

I commited the debug ouput changes:
https://github.com/dokan-dev/dokany/commit/9a44ee2f2171013a712fe2c7256c44c47045d1f2

**Comment by jetwhiz** [comment]
@Liryna You're right ... I completely missed that! ^^  Yes that works perfectly now, thanks!  

Is it possible that you can also pass the "fileAttributesAndFlags" variable in via the fuse_file_info variable, similar to how the "flags" variable is passed in?  For instance, like this: 

[flagsAndAttributes.txt](https://github.com/dokan-dev/dokany/files/312074/flagsAndAttributes.txt)

That way we have access to it from the FUSE interface.

**Comment by Liryna** [comment]
@jetwhiz unfortunatly we cannot do this :(
We would break fuse compatibility with this changes no ?

**Comment by jetwhiz** [comment]
@Liryna Yes, the interface would no longer be consistent with the FUSE interface.  I'm trying to think of how else this information can be passed (since it is Windows-specific).  I think we are also unable to have it passed in via FUSE open(const char* path, struct fuse_file_info* fi) as a new parameter.  

Maybe it is possible to have a 

````c++
win_open(const char* path, struct fuse_file_info* fi, unsigned int flagsAndAttributes) 
````

function that is triggered whenever the fileAttributesAndFlags is set (if the user has defined a callback for win_open)?  Similar to win_get_attributes, et al.  This way Windows users have the ability to catch these flags in win_open() instead of open().

**Comment by Liryna** [comment]
@jetwhiz is it only the `FILE_FLAG_DELETE_ON_CLOSE` that you are interested or all flagsAndAttributes ?
If it is only the delete flag, maybe we can reused somehow the flag argument of open (it is just an idea :smiley: , I would like to explore all possibilities)

**Comment by jetwhiz** [comment]
@Liryna Right now we're mainly interested in FILE_FLAG_DELETE_ON_CLOSE, so it's a good idea of trying to reuse the flag argument (at least for a short-term solution).  In the future it might be useful to have access to all of the flags, though we don't need them right now as far as I can tell.

**Comment by Liryna** [comment]
@jetwhiz I didn't gave up on this issue :smiley: I just had not the time to look into it.
Just for information, there were an issue with the flag during cleanup (rmdir/unlink) see: https://github.com/dokan-dev/dokan-dotnet/issues/83#issuecomment-227229432
In case of this can explain a behaviour you faced.

**Comment by jetwhiz** [comment]
Thanks, @Liryna!  The issue we are experiencing is that the temporary files created by Microsoft Office are not automatically removed after closing the program.  We are using the FUSE interface and we create files with CreateFileW, though, so I'm not sure if this is related to the Dokany driver?

**Comment by Liryna** [comment]
humm @jetwhiz ! If in your case rmdir/unlink were not called at all for the temporary files created by Microsoft Office, this fix https://github.com/dokan-dev/dokany/commit/59d08ffca07f69c40d9d46e5a687816cb72d0a49 should be tested :+1: 

It was the same behaviour with C Mirror. I think you should really give a try !

**Comment by jetwhiz** [comment]
@Liryna  It sounds promising ... I'll give it a try!  When you say "kernel driver", are you referring to dokan1.dll in the System32 folder?

**Comment by Liryna** [comment]
No, the dokan1.sys in System32, you need to have it signed. So the possibility is to wait the next release or to create a VM, download https://ci.appveyor.com/api/buildjobs/jw9memsn22f6dvwe/artifacts/DokanSetup-1.0.0.3623.exe and see how to install the self signed dokan cert here: https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot

**Comment by jetwhiz** [comment]
Hi @Liryna -- the latest version of Dokany (RC4) now appears to honor the FILE_FLAG_DELETE_ON_CLOSE flag for files created, so I believe this issue is no longer necessary (unless you want to keep it open to implement these flags as pass-through in FUSE, though I personally do not need them now).

**Comment by Liryna** [comment]
Thank you for your feedback @jetwhiz ! :+1: 
I think this can be closed and if someone need the flag I am willing to reopen it !
