### ISSUE TITLE
(CI-built) Installers do not detect that earlier version is installed

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#261]
# Environment
 * Windows version: 2008 R2
 * Processor architecture: x64 
 * Dokany version: see below
 
# Check List
  - [ x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ x ] I can always reproduce the issue with the provided description below.
  - [ x ] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description
When installing builds from CI over an earlier version I encounter weird behaviour. This has been like this for quite some time, so the recent changes to the installer are unlikely to blame.

# Actual:
1. Installed [1.0.0-604](https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.0-604/job/ajujc3vgy8ylwda8/artifacts)
2. Without uninstalling the older version before, I tried to install [1.0.0-606](https://ci.appveyor.com/project/Maxhy/dokany/build/job/b9v3h3mif09s8sp3/artifacts)
3. Installation seemed to complete VERY quickly. In fact no files were updated at all. Control Panel Software applet had two entries for Dokan after that installation. Uninstalling both the phantom-entry and the real entry and re-installing

# Expected
Error message asking to uninstall the old version (or doing that automatically/upgrading which I don't think is implemented).

# Comment 
Maybe we could also add the build number as the minor-minor version to all the DLLs and the installer to make troubleshooting issues easier. Maybe we can multiply it by ten (or any other number) to have some room in between to create signed releases

# Logs
Do not show anything at all. :-(
[Dokan_Library_1.0.0.103_Bundle_20160614101759.log.txt](https://github.com/dokan-dev/dokany/files/313447/Dokan_Library_1.0.0.103_Bundle_20160614101759.log.txt)

**Comment by Liryna** [comment]
Hi @Rondom ,

Thats an issue with appveyor configuration :cry: 

There is a tools in dokan repository `SetAssemblyVersion` made by @js69 that does update the version.
https://github.com/dokan-dev/dokany/tree/master/dokan_wix/SetAssemblyVersion

I will add it in the appveyor build like that all appveyor installer will have there own version and will fix the issue you are facing.

**Comment by js69** [comment]
Liryna, regarding build numbers: both of these installers 604 and 606 described above use the same build number 1.0.0.103. MSI generally doesn't like two different packages to have the same version - what Rondom describes is the effect of the WIndows installer not seeing a version difference.

Incrementing the build number is always preferred (as we use SVN here we use the SVN revision number for that).

Also, it might be helpful to increment version numbers for different RCs by larger increments so that private builds can be updated by new official releases.

I would suggest the following versioning policy: a new RC will be set to the next build version multiple of 1000, e.g.:
RC1 would be 1.0.0.1000, RC2 would be 1.0.0.2000, RC3 then 1.0.0.3000 and so forth. When we create a new private build based on a RC2 it could be 1.0.0.2001 and not cause any conflicts with newer RCs.

**Comment by Liryna** [comment]
Ok I see @js69 , so If I make appveyor set the BuildVersion at 3606 (1 for RC3 and 606 from the build version of appveyor) in the xml, it gonna be good ?

Just before calling SetAssemblyVersion

**Comment by Rondom** [comment]
Where/When is this SetAssemblyVersion called? So far all DLLs have version 1.0.0.0 and only the installer has a different version.

**Comment by Liryna** [comment]
SetAssemblyVersion is only called in the release build script here:
https://github.com/dokan-dev/dokany/blob/master/dokan_wix/build.bat#L10

His goal is to set C# installer version correctly.

Dll version is from here: https://github.com/dokan-dev/dokany/blob/master/Dokan.props#L6

**Comment by Rondom** [comment]
Looking through the RC3 Dokan.zip there is no file that has the version set to something else than 1.0.0.0 or no version at all as far as I can see.

Maybe we could also change the filenames to include the version-number for the artifacts (and the releases as well for consistency

**Comment by Rondom** [comment]
Ah, I see. I only looked at the source of SetAssemblyVersion and it contains code to update .rc files as well (as far as I can see). So I assumed it would update the different dll-files' version information as well.

**Comment by Liryna** [comment]
Dokan library only hold the major API (`dokan1.dll`) and it will stay like this.

The goal in this, it is that dokan library should be packaged in the other application installer side by side. This will give the ability that all application with the same MAJOR API but with different version, can work in the same computer.
Also that application with old dokan library can still enjoy dokan driver updates without issues.

**Comment by Rondom** [comment]
> Ok I see @js69 , so If I make appveyor set the BuildVersion at 3606 (1 for RC3 and 606 from the build version of appveyor) in the xml, it gonna be good ?

How would this scale as soon the appveyor-build-ids crack the 1000 mark?

**Comment by Liryna** [comment]
I hope that we are going to make a release before 1000 commit :D
But your question was good :smile:  ! I just found that build version can be reset. I will do it in the same time as when I change appveyor version here after a release: https://github.com/dokan-dev/dokany/blob/master/appveyor.yml#L12

**Comment by Rondom** [comment]
> Dokan library only hold the major API (dokan1.dll) and it will stay like this.

@Liryna Oh, I think we are talking about two (or three or more) different things here.
1. The installer version
2. The ABI version (I guess defined in https://github.com/dokan-dev/dokany/blob/master/Dokan.props#L6)
3. The version resource embedded into the individual DLLs (view Properties in Explorer and look at tab "Details"). If I understand correctly, those are defined in RC-files
4. The filenames of artifacts from appveyor and releases. For people testing different versions, it is useful/convenient to not have multiple versions with the same filename in the download-folder.

**Comment by Liryna** [comment]
Yes, you are right.

What I propose, if you agree @Rondom , @js69 :
- [ ] RC-files (dokan.dll, ...) should be updated by SetAssemblyVersion
- [ ] Change version as @js69 proposed (RC1 would be 1.0.0.1000, RC2 would be 1.0.0.2000, RC3 then 1.0.0.3000)
- [ ] Make appeveyor set BuildVersion with his build number like 3606 for RC3 and build nb 606.
- [ ] Add build version in artifacts

**Comment by js69** [comment]
As long as you can avoid overflowing the 999 build number, yup.

**Comment by Rondom** [comment]
Sounds good! :+1:

**Comment by Liryna** [comment]
Changes have been made https://github.com/dokan-dev/dokany/commit/54943033d2acff2d3ac0e2b90e3128eb87704fdd

Now RC files are correctly set by SetAssemblyVersion and appveyor use his build version in his release.

I just remember that dokan is install in `C:\Programmes\Dokan\Dokan Library-1.0.0`, I dont know if this should be changed to `C:\Programmes\Dokan\Dokan Library-1.0.0.3606` ?

**Comment by Rondom** [comment]
Tested under Win2K8R2, detects previous version and pending reboot correctly!

**Comment by Liryna** [comment]
:+1: and all file versions are ok ?

**Comment by Rondom** [comment]
No :-( They all have version 1.0.0.3000

**Comment by Liryna** [comment]
https://github.com/dokan-dev/dokany/commit/6d88a23d22d44edc604a19bd64da05c0bd65ce86
It gonna do the job :sunglasses: 
https://ci.appveyor.com/project/Maxhy/dokany/branch/master/job/n4pu1sd5urwdqiac

**Comment by Rondom** [comment]
Versions are correct now.

Regarding your question about the folder name: I would leave it as it is because I cannot see a reason to change it.

**Comment by Liryna** [comment]
Great ! So we will let it as it is.

Thanks for your time @Rondom and @js69 !
