### ISSUE TITLE
Cannot paste file from zip file using Explorer

### ISSUE THREAD

**Issue by bailey27** [dokan-dev/dokany#265]
# Environment
 * Windows version: Windows 10
 * Processor architecture: x64
 * Dokany version: 1.0.0-RC3
 * Library type Dokany
 
# Check List
  - [x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x ] I can always reproduce the issue with the provided description below.
  - [x ] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description

If I open a zip file in File Explorer, then right-click on one of the files in it and select "copy", then go to the mirror drive and right click and do "paste", then Explorer and Dokany/mirror go into an infinite loop. I have to ctrl-c mirror and then close the Explorer window which seems to kill it and causes windows to re-launch it.

To reproduce:

run (as administrator) 
mirror.exe /t 1 /d /s /r c:\tmp\mirror /l m 2> c:\tmp\mirror_unzip.log

The open the attached foo.zip in Explorer (it was in c:\tmp when I tried it) right click and copy foo.txt, then go to the M: drive in Explorer and try to paste the file there.

# Logs
Here are the attached logs.  I included a screenshot of the file copy progress window from Explorer that gets stuck as shown.

[mirror_unzip.zip](https://github.com/dokan-dev/dokany/files/320255/mirror_unzip.zip)

**Comment by bailey27** [comment]
I really thought I did tried this before.  But Apparently I didn't.

If I disable Windows Defender real time scanning, then the problem doesn't happen.

Or, if I leave it enabled, but exclude the Dokan drive letter from scanning, then it also doesn't happen.

So the problem must be caused by Windows defender.

I see in the logs "AccountName: SYSTEM, DomainName: NT AUTHORITY" trying to access the file.

Another thing I noticed is that if I put a huge file in a zip file and extract it by copy and paste from Explorer, the problem doesn't happen either (regardless of whether or not Windows Defender is configured to scan that drive).

From the logs, it looks like if a huge file is extracted, then "AccountName: SYSTEM, DomainName: NT AUTHORITY" doesn't even bother with it.

So I guess the workaround would be to exclude in Windows Defender the drive letters one uses for mounting Dokany-based file systems.

I think t would be interesting to find why this problem really happens, though.

**Comment by Liryna** [comment]
Oh that's interesting. Probably yes Windows Defender bother the process of zip.

I also think this will not happen with a dokan full signed like the RC release.

**Comment by bailey27** [comment]
I think I was running RC-3 release (not Dbg) when I first saw it.

Just now I ran the Dbg uninstall, rebooted and installed from RC3 DokanSetup_redist.exe in my VM (and rebooted again to make sure).  I looked and verified the signature of dokan1.sys.

It happens with the non-debug RC-3.

I also tried excluding the root folder of the mirrored fs (c:\tmp\mirror for me), but that didn't help.

Only excluding the Dokany drive letter seems to work (or turning off real-time scanning completely)..

**Comment by Liryna** [comment]
Even mirror.exe and dokan1.dll  are signed ? :cry:

**Comment by bailey27** [comment]
dokan1.dll is signed.

There is a dokan1.dll in c:\windows\system32 and there is one in C:\Program Files\Dokan\Dokan Library-1.0.0\sample\mirror.  Both are signed ISLOG.  They are the same file (same sha25sum: 51d92eed83819134a8b8c7ac338ebc3935960ae79a428d6f595745d68e78e14b).

In C:\Program Files\Dokan\Dokan Library-1.0.0\sample\mirror there is mirror.exe but it is NOT signed.

I think it won't matter.  I think Windows Defender cares about a possible infection in the file being extracted from the .zip file and not about what program is involved in extracting it.

**Comment by bailey27** [comment]
I think it is maybe better to not put a dokan1.dll in C:\Program Files\Dokan\Dokan Library-1.0.0\sample\mirror.  When I tested my fix for https://github.com/dokan-dev/dokany/issues/267 I needed to rename it in C:\Program Files\Dokan\Dokan Library-1.0.0\sample\mirror so mirror.exe woudn't load the old DLL.

**Comment by Liryna** [comment]
dokan1.dll always has to be embedded with user applications because the one in system32 can be another version of the major API 1 and being not binary compatible.

**Comment by bailey27** [comment]
Yes, I think it is a good idea.  It was my mistake not noticing it was there the first time I tried a different dll.  I should have replace the one in the mirror directory.

**Comment by Liryna** [comment]
Since this is related to Windows Defender, can this issue be closed ?
I am not sure we can do something about it :cry:

**Comment by mylemans** [comment]
Rather sure you cannot go wait on Microsoft to 'fix' it for you?

**Comment by bailey27** [comment]
I think this bug mabye has something to do with oplocks.

Defender seems to use them.

I was reading this about FsRtlCheckOplock() on MSDN:

> If a file system or filter driver uses opportunistic locks, it must call FsRtlCheckOplock from any dispatch routines for I/O operations that can cause opportunistic lock breaks. This rule applies to the following types of I/O operations, because these operations can cause opportunistic lock breaks:
> 
> IRP_MJ_CLEANUP
> IRP_MJ_CREATE
> IRP_MJ_FILE_SYSTEM_CONTROL
> IRP_MJ_FLUSH_BUFFERS
> IRP_MJ_LOCK_CONTROL
> IRP_MJ_READ
> IRP_MJ_SET_INFORMATION
> IRP_MJ_WRITE
> 

But I see it only in these files in sys

```
C:\git\forks\dokany\sys>grep -l FsRtlCheckOplock *.c
create.c
lock.c
read.c
```

Maybe the driver isn't checking about oplocks in all the places it should and that is causing this to happen?

**Comment by Liryna** [comment]
That's a big if and hard to check :cry: 
But you are right, FsRtlCheckOplock should be implemented in other IRP !

**Comment by marinkobabic** [comment]
Here what happens. Os sends IRP_MN_USER_FS_REQUEST and FSCTL_REQUEST_FILTER_OPLOCK. The method DokanOplockRequest is executed which will call FsRtlOplockFsctrl. The FsRtlOplockFsctrl returns STATUS_PENDING and according to the documentation means this granted https://msdn.microsoft.com/en-us/library/windows/hardware/ff545518(v=vs.85).aspx. Dokan must not complete the irp and this is fine so far. The problem we have here is that the Irp hangs and it's never completed. You can watch this using process monitor.

**Comment by marinkobabic** [comment]
Before doing oplock the resource should be locked using ExAcquireResourceExclusiveLite instead of ExAcquireResourceSharedLite. This is how cdfs locks the resource. https://github.com/Microsoft/Windows-driver-samples/blob/6e1115d6af3c22b693eccc472ebb0d53a1905cd9/filesys/cdfs/fsctrl.c#L1790

**Comment by bailey27** [comment]
I think the driver should check if there should be an oplock break by calling FsRtlCheckOplock() in all of those operations listed on MSDN.

I did a hasty addition of FsRtlCheckOplock() for all the operations except IRP_MJ_FILE_SYSTEM_CONTROL.

Now the bug does not happen.

**Comment by bailey27** [comment]
Yes, I see it in fastfat as well.  When they are doing that, they acquire a shared lock on the vcb but an exclusive lock on the fcb.  I will change my banch to do that as well and test it.

**Comment by bailey27** [comment]
I don't know if "oplock break" is the right term.  

I mean I think the driver needs to make the FsRtlCheckOplock() call in in those operations in case somebody has an oplock and the irp needs to be completed later.

**Comment by marinkobabic** [comment]
I would implement it in all operations implemented in fastfat. In most cases is fastfat the only reference.

**Comment by bailey27** [comment]
Here are my changes

https://github.com/bailey27/dokany/commit/9527353b15d56473b8e99274a3bcf7aa86b35672

I also changed DokanOplockRequest() to get an exclusive lock on the fcb as the sample drivers do as per @marinkobabic 's suggestion.

I cannot find where fastfat is using FsRtlCheckOplock() with IRP_MJ_FILE_SYSTEM_CONTROL.  So I cannot figure out where or how I should do that.

The fastfat cleanup.c has, for windows 8 and higher, two additional uses of FsRtlCheckOplockEx() (not FsRtlCheckOplock()).

fastfats' cleanup is way more complicated than dokany's.  And it looks like fastfat has way more state about the fs than dokany does (e.g. is a directory empty).

I think these calls to FsRtlCheckOplockEx() are there to gain an performance improvement with oplocks.  I think they aren't needed for correct behavior.  So I didn't put them there.

Also, in fastfat's cleanup, they actually ignore the return value for FsRtlCheckOplock() (and pass in null for the callback parameters).  The comments in fastfast say it will never return pending there.  But I don't see any harm in passing in the callback parameters and checking the result here as the code does in all the other places where it calls FsRtlCheckOplock().

**Comment by Liryna** [comment]
@bailey27 your changes, seems to be correct, does it solve complitly the zip issue ?
This should be well test to see if not other cases have been broken.

Dokan does not support `IRP_MJ_FILE_SYSTEM_CONTROL` so it is not important that FsRtlCheckOplock is missing.

About fastfat's cleanup, if found nothing on msdn about returning pending, I would say it is safe for now :smiley: 
https://msdn.microsoft.com/en-us/library/windows/hardware/ff548608(v=vs.85).aspx

Thank you again for taking the time on this issue ! I let @marinkobabic review it, give his final word and will test it.

**Comment by bailey27** [comment]
Yes, it solves the zip issue.  I cannot reproduce it anymore with these changes.

**Comment by bailey27** [comment]
@marinkobabic commented that I should handle return status other than STATUS_PENDING from FsRtlCheckOplock().

I did this in this commit.  I changed the handling of it in read.c too.

https://github.com/bailey27/dokany/commit/0c64b849c8ce817037dcd5e67dac29bdd33971e1

I was looking at the lock code about this.

There's a variable in the disk control block dcb->FileLockInUserMode.

Whenever the driver gets to DokanDispatchLock(), then it always allocates an eventContext.  But if dcb->FileLockInUserMode is false, then it ends up calling DokanCommonLockControl(), which does not dispatch the event to user mode.  

So I think it's leaking the eventContext in this case.

Also, DokanCommonLockControl() calls FsRtlCheckOplock() with the eventContext and the oplock callback (DokanOplockComplete()).  So if FsRtlCheckOplock() did return pending on the operation, then this lock request would get dispatched by DokanOplockComplete() to user mode even though dcb->FileLockInUserMode is FALSE (which is why it ended up in DokanCommonLockControl() in the first place.

Also, it looks to me like if dcb->FileLockInUserMode is TRUE, then FsRtlCheckOplock() will never be called about locks because DokanCommonLockControl() isn't called then.  DokanCommonLockControl() is the only place in lock.c where FsRtlCheckOplock() is called.

**Comment by Liryna** [comment]
@bailey27 If I am not wrong, when FileLockInUserMode is false, DokanCommonLockControl will call FsRtlCheckOplock with callback DokanOplockComplete then DokanRegisterPendingIrp that will free the eventContext.

`So if FsRtlCheckOplock() did return pending on the operation, then this lock request would get dispatched by DokanOplockComplete() to user mode even though `
We should ping @Maxhy to have an answer for this probably :+1: 


`dcb->FileLockInUserMode is TRUE, then FsRtlCheckOplock() will never be called about locks because DokanCommonLockControl() isn't called then.`
If I am not wrong (correct me @Maxhy ), this is made in purpose to give the ability here for the user mode to lock his resource himself with Lock Unlock dokan operation.

**Comment by bailey27** [comment]
I think if FileLockInUserMode is false, then if FsRtlCheckOplock() doesn't return pending, then the eventContext will be leaked.  And if FsRtlCheckOplock() does return pending, then the lock request will be sent to user mode, which wasn't the intent.

**Comment by bailey27** [comment]
@marinkobabic , did you see my changes?  

https://github.com/bailey27/dokany/commit/0c64b849c8ce817037dcd5e67dac29bdd33971e1

Do you think it is okay now?

**Comment by marinkobabic** [comment]
@bailey27 The changes look fine.

**Comment by Liryna** [comment]
Fixed with your contribution @bailey27 Thanks again !
