### ISSUE TITLE
(fix offered) Visual Studio cannot open program database vc140.idb on mirror drive

### ISSUE THREAD

**Issue by bailey27** [dokan-dev/dokany#267]
# Environment
 * Windows version: Windows 10
 * Processor architecture: x64
 * Dokany version: 1.0.0-RC3
 * Library type Dokany 
 
# Check List
  - [ x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ x] I can always reproduce the issue with the provided description below.
  - [ x] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description

I found this bug when trying to debug https://github.com/dokan-dev/dokany/issues/264

I installed Windows 10 64-bit Home in a VM.  Then I installed Visual Studio 2015 Community Edition.

My goal was to reproduce https://github.com/dokan-dev/dokany/issues/264 in the VM.

When I created a project, https://github.com/dokan-dev/dokany/issues/264 did not happen.

Visual Studio did not try to create a projectname.sdf (Microsft SQL Server Compact) browsing database in the root of the project.

Instead, it created a projectname.VC.db (SQLite) instead.  This succeeded.

However, when I tried to build the project, The build failed because Visual Studio claimed that it could not open vc140.idb.  

```
g:\consoleapplication2\consoleapplication2\stdafx.cpp : fatal error C1033: cannot open program database 'g:\ConsoleApplication2\ConsoleApplication2\Debug\vc140.idb'
```

I verified that SQL Server Compact was installed, re-installed Windows and Visual Studio three times different ways, but I still couldn't get it make a projectname.sdf intead of a projectname.VC.db in my VM.

So I decided to debug the vc140.idb problem instead.

I looked in my log, and around where it was doing stuff with vc140.idb, I saw where dokan1.dll printed

```
###GetFileInfo 2925
	result =  0
  unknown type:59
	DispatchQueryInformation result =  3221225485
```

Type 59 is for FileIdInformation.

I implemented handling of the FileIdInformation file information class in fileinfo.c in the DLL, and now it works.  

I can build projects in my VM.  

I also noticed that when you do DokanFillFileAllInfo(), you weren't filling in the InternalInfo.  This information is available (and is very similar to what FileIdInformation is), and I think it should be passed back when somebody calls GetFileInformationByHandle() Windows api.

If you call GetFileInformationByHandle() on a mirror drive, you currently get 0 for both nFileIndexLow and nFileIndexHigh in the BY_HANDLE_FILE_INFORMATION.  But if DokanFillFileAllInfo() does DokanFillInternalInfo() in DokanFillFileAllInfo(), then you get non-zero numbers for those values.

My proposed changes are

fileinfo.h:
--------
```
diff --git a/dokan/fileinfo.h b/dokan/fileinfo.h
old mode 100644
new mode 100755
index bd614f9..c1c4ed4
--- a/dokan/fileinfo.h
+++ b/dokan/fileinfo.h
@@ -295,6 +295,11 @@ typedef struct _FILE_INTERNAL_INFORMATION {
   LARGE_INTEGER IndexNumber;
 } FILE_INTERNAL_INFORMATION, *PFILE_INTERNAL_INFORMATION;
 
+typedef struct _FILE_ID_INFORMATION {
+    ULONGLONG VolumeSerialNumber;
+    FILE_ID_128 FileId;
+} FILE_ID_INFORMATION, *PFILE_ID_INFORMATION;
+
 typedef struct _FILE_EA_INFORMATION {
   ULONG EaSize;
 } FILE_EA_INFORMATION, *PFILE_EA_INFORMATION;

```

fileinfo.c:
--------
I created a prototype for DokanFillInternalInfo() instead of moving it up above DokanFillFileAllInfo()

```
diff --git a/dokan/fileinfo.c b/dokan/fileinfo.c
old mode 100644
new mode 100755
index b0cff1a..b233d44
--- a/dokan/fileinfo.c
+++ b/dokan/fileinfo.c
@@ -26,6 +26,11 @@ with this program. If not, see <http://www.gnu.org/licenses/>.
 #include <stdlib.h>
 
 NTSTATUS
+DokanFillInternalInfo(PFILE_INTERNAL_INFORMATION InternalInfo,
+                      PBY_HANDLE_FILE_INFORMATION FileInfo,
+                      PULONG RemainingLength);
+
+NTSTATUS
 DokanFillFileBasicInfo(PFILE_BASIC_INFORMATION BasicInfo,
                        PBY_HANDLE_FILE_INFORMATION FileInfo,
                        PULONG RemainingLength) {
@@ -114,6 +119,10 @@ DokanFillFileAllInfo(PFILE_ALL_INFORMATION AllInfo,
   DokanFillFileStandardInfo(&AllInfo->StandardInformation, FileInfo,
                             RemainingLength, DokanInstance);
 
+  // FileInternalInformation
+  DokanFillInternalInfo(&AllInfo->InternalInformation, FileInfo,
+                            RemainingLength);
+
   // FilePositionInformation
   DokanFillFilePositionInfo(&AllInfo->PositionInformation, FileInfo,
                             RemainingLength);
@@ -259,6 +268,28 @@ DokanFillInternalInfo(PFILE_INTERNAL_INFORMATION InternalInfo,
   return STATUS_SUCCESS;
 }
 
+
+NTSTATUS
+DokanFillIdInfo(PFILE_ID_INFORMATION IdInfo,
+                      PBY_HANDLE_FILE_INFORMATION FileInfo,
+                      PULONG RemainingLength) {
+  if (*RemainingLength < sizeof(FILE_ID_INFORMATION)) {
+    return STATUS_BUFFER_OVERFLOW;
+  }
+
+  IdInfo->VolumeSerialNumber = FileInfo->dwVolumeSerialNumber;
+
+  ZeroMemory(IdInfo->FileId.Identifier, sizeof(IdInfo->FileId.Identifier));
+
+  ((DWORD*)(IdInfo->FileId.Identifier))[0] = FileInfo->nFileIndexLow;
+  ((DWORD*)(IdInfo->FileId.Identifier))[1] = FileInfo->nFileIndexHigh;
+  
+  *RemainingLength -= sizeof(FILE_ID_INFORMATION);
+
+  return STATUS_SUCCESS;
+}
+
+
 typedef struct _DOKAN_FIND_STREAM_DATA {
   WIN32_FIND_STREAM_DATA FindStreamData;
   LIST_ENTRY ListEntry;
@@ -423,6 +454,13 @@ VOID DispatchQueryInformation(HANDLE Handle, PEVENT_CONTEXT EventContext,
                                  &byHandleFileInfo, &remainingLength);
       break;
 
+    case FileIdInformation:
+      DbgPrint("\tFileIdInformation\n");
+      status =
+          DokanFillIdInfo((PFILE_ID_INFORMATION)eventInfo->Buffer,
+                                &byHandleFileInfo, &remainingLength);
+      break;
+
     case FileInternalInformation:
       DbgPrint("\tFileInternalInformation\n");
       status =
```

**Comment by Liryna** [comment]
Hi @bailey27 !

Thank you for your report and analyse !

After review of your code, this seems to be alright !
This seems to be a new request for Windows 10 (there is a couple like this so we add it when we face it...)

Do you want to make a pull request yourself or I apply your patch with your name in the commit ?

**Comment by bailey27** [comment]
Thanks for accepting my patch.

I made the pull request.

**Comment by Liryna** [comment]
Patch merged https://github.com/dokan-dev/dokany/pull/268
Thank you @bailey27 !
