### ISSUE TITLE
Driver Signing changes in Windows 10, version 1607

### ISSUE THREAD

**Issue by ghost** [dokan-dev/dokany#271]
# Environment
 * Windows version: Windows 10 Pro **Insider Preview** Build 14376.rs1_release.160624-1700
 * Processor architecture: AMD64
 * Dokany version: 1.0.0-RC3
 * Library type (Dokany/FUSE): Dokany
 * **Secure Boot Enabled**
 
(Note. Windows 10 Build 14366 was fine. and after clean up Windows and install driver. problem is appeared)
(All Check List are checked.)

# Description
Driver can't install with latest Win10 Insider Preview.
`sc start dokan1` say [ERROR_INVALID_IMAGE_HASH: 577](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681388(v=vs.85).aspx).

I check driver sign is vaild, and `dokan1.sys` are equal with new dokany 1.0.0-RC3's `dokan1.sys`.

https://msdn.microsoft.com/en-us/library/windows/hardware/ff548231(v=vs.85).aspx would be help for solve this problem. (But how we can getting WHQL signature? i don't know)

# Logs
[console.log](https://github.com/dokan-dev/dokany/files/339206/console.log.txt)
[mirror.log](https://github.com/dokan-dev/dokany/files/339207/mirror.log.txt)

**Comment by Liryna** [comment]
Hi @EcmaXp ,

When you look at the signature, does windows show it as valide signature ?
If not, it would mean that the godaddy root certificate is missing (probably because you use a Insider Preview or a restricted environnement).

**Comment by EcmaXp** [comment]
Yes, windows say it as vaild signaure. (when check by file property)

sha1 and sha256 digest both.

**Comment by Liryna** [comment]
Humm well on a side Windows say it is a valide signature and another side it say it is not.

`Secure Boot Enabled`, do you mean bios/uefi option ?

**Comment by EcmaXp** [comment]
Absolutely yes. Microsoft Windows are provide Secure Boot when UEFI setting enabled.

And, when i turn off uefi settings, Service Instance are successfully started.

(When turn off **Secure Boot**)
```
C:\WINDOWS\system32>sc query dokan1

SERVICE_NAME: dokan1
        종류               : 2  FILE_SYSTEM_DRIVER
        상태               : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        검사점             : 0x0
        WAIT_HINT          : 0x0
```

**Comment by Liryna** [comment]
If WHQL is needed for Secure Boot, will not be able to get it.
But it would be interesting to know if this is exactly the source of the issue.

**Comment by EcmaXp** [comment]
Should i change issue title?

**Comment by Liryna** [comment]
https://www.osronline.com/ShowThread.cfm?link=269799
With Secure Boot, windows load only driver WHQL driver you are right.
Dokan will never pass WHQL, I think this can be close.

Thank you @EcmaXp for the report ! I was not aware of this !

**Comment by Maxhy** [comment]
Coming 2nd August Win10 update will become a nightmare for those deploying their user-mode file system in production as this feature will be enabled by default.

*End of the world* will start tomorrow and we will see, but basically we will have to change our signing certificate (more expensive and can be bought at Micro$oft friends only: Symantec & DigiCert, but that's the easy part), then we will have to pass WHQL certification (more work!).
This is a long time process but I believe it cannot be ignored anymore.

**Comment by js69** [comment]
https://xkcd.com/1200/

Installing the Anniversary Update now in a VM with Dokany driver preinstalled. It shouldn't complain, I guess, only later when I install a new driver version.

**Comment by js69** [comment]
Install of Dokany RC4 was without issue on Microsoft Windows [Version 10.0.14393]. Will have to try now with drivers signed after August 2nd.

**Comment by js69** [comment]
Still works fine my today's signed driver.

Seems like WHQL-requirement isn't enforced yet.

**Comment by EcmaXp** [comment]
My desktop still not working with dokan driver...

![image](https://cloud.githubusercontent.com/assets/13285311/17362630/e80a1c04-59b0-11e6-85d3-8830231d2b1d.png)
(That alart message say 'Digital-signed driver are required')

Desktop
Dokan version: 1.0 RC4
Windows version: (Win10 Pro) 14393.10
Still using *Secure Boot*

Desktop: clean install for update to Windows 10 Pro, Anniversary Update

<del>But, something is wrong. my surface 4 also getting window 10 update. but still work!</del>
<del>Surface 4: just update from Windows 10 Pro TH2</del>

**Comment by Maxhy** [comment]
Thanks for your test @js69. Seems that it is not enforced if it is an update, maybe only on new installations, or if you enable it manually as in @EcmaXp case.

**Comment by EcmaXp** [comment]
@Maxhy yes, my surface 4 are update to latest windows update and still work!

**Comment by js69** [comment]
Maxhy, you are right:

"OS signing enforcement is only for new OS installations; systems upgraded from an earlier OS to Windows 10, version 1607 will not be affected by this change."

https://blogs.msdn.microsoft.com/windows_hardware_certification/2016/07/26/driver-signing-changes-in-windows-10-version-1607/

**Comment by EcmaXp** [comment]
EV certificates???...

**Comment by js69** [comment]
"PCs with Secure Boot OFF will still permit installation of cross-signed drivers."

**Comment by kbarnes3** [comment]
From what I've read, it sounds like you can support Windows 10 desktops, but not Server 2016, buy using an attestation signed driver. This requires an EV cert still, but doesn't require passing WHQL. There might also be a scary looking dialog involved at installation time.

https://msdn.microsoft.com/en-us/windows/hardware/drivers/develop/attestation-signing-a-kernel-driver-for-public-release?f=255&MSPPError=-2147217396

I've never gone through this process though, so take everything above with a grain of salt.

**Comment by Liryna** [comment]
@zanderz I seen that you was using an EV certificat to sign Dokany,
did you already made a test on a newly installed Win10 from the iso released a the anniversary update ?

**Comment by sdecugis** [comment]
This post clarifies the rules quite well I think: https://blogs.msdn.microsoft.com/windows_hardware_certification/2016/07/26/driver-signing-changes-in-windows-10-version-1607/

Is there anything contributors can do to help getting the driver accepted on newer Win10 machines with Secure Boot ON ? This is a serious issue for many people I believe...

**Comment by Liryna** [comment]
Hi @sdecugis ,

Thank you for the link ! This make it more clear. I was aware that we need EV certificat first but I was afraid that we need to pass WHQL and it seems to be not :+1: 

We are currently asking to our company (ISLOG who is sponsoring Dokany by providing the current sign certificate) if they can buy an EV certificate needed here.
But this seems to take his time because it is an unplanned cost for them.

I would like to use the dokany donation that should be used in such purpose for buying the certificate but we are extremely far from it (thank to our only  1$ donor ! :heart: )

**Comment by sdecugis** [comment]
Thank you for the update @Liryna :) What is the cost of such signing certificate ? (is it one-time or is it an annual fee?)

**Comment by Liryna** [comment]
Microsoft list all authorities that can provide it here:
https://msdn.microsoft.com/en-us/library/windows/hardware/hh801887.aspx

Also on Developer Center Dashboard portal I found:
```
A Dashboard account for your company is a prerequisite for creating user accounts. You must establish your company’s identity by purchasing a codesigning certificate. Additionally, as an extra measure of security, all submitted files must be signed using the same codesigning certificate.

We accept code sign certificates from Symantec and DigiCert. 
```

So we will need to take a Symantec or a DigiCert cert.
I was not able to find Symantec pric but for DigiCert  it is $224.00 USD / year  or $497.00 USD for 3 years.
https://www.digicert.com/order/order-1.php

**Comment by sdecugis** [comment]
Thank you for the information. I will try asking on my side as well if helping is possible.

**Comment by zanderz** [comment]
Apologies @Liryna, I thought I had replied earlier. We do have users who are already attempting the fresh AU Windows 10 install + keybase, and being blocked from installing the drivers, though we have signed them with our EV cert. We are signed up on the Developer Center, but I just haven't gotten around to making a submission in the required format.

Keybase would like to sponsor an EV cert for the Dokany project. Should we make a donation on the main page, or what's the best way?

BTW, keep in mind that Microsoft rules require EV certs to be on a hardware key, which only works during a logged in session, making automation and distributed builds very cumbersome. Some have had luck building in a cloud VM with USB ports forwarded. We have a dedicated machine that stays logged in always, configured to be a Jenkins slave for a remote master. This is with DigiCert - I believe Symantec would have the same limitations but we don't have an EV cert from them.

**Comment by Liryna** [comment]
Ah perfect @zanderz ! highly appreciate information that you are providing !
Alright so Developer Center is going to be an obligation. I just hope it is adapted for drivers like Dokan.

Yes, the donation button on the README for PayPal https://github.com/dokan-dev/dokany/blob/master/README.md is the current way to make a donation but if you would like to use another system (since PayPal has fees) we are open to any proposition !

You are right, I just find out when looking at the price that they ship the cert in a Hardware Token as you explained.
For information, it is going to take 10-15 days of shipment.
Also do you know if the `DigiCert offers code signing certs to Sysdevs at 50% off our regular pricing.` https://www.digicert.com/friends/sysdev/ is enough O_o ? They don't explain the limitation of the sysdev offer.

Even Symantec price is practically 1k$/y O_o there is a big gap between DigiCert offer.
https://www.symantec.com/page.jsp%3Fid%3Dcompare-ssl-certificates

**Comment by zanderz** [comment]
No idea about sysdev discount, sorry, but try it! Maybe that's because of this new MS requirement.

SSL site certificates are a different product from codesigning ones, maybe that explains some of the price difference.

**Comment by zanderz** [comment]
@Liryna, it is your choice, we'll use paypal or can also use TransferWise if you prefer - we use it to pay people in Europe. Looks like paypal fees are 3% or so? Let us know.

**Comment by Liryna** [comment]
From DigiCert Support `Yes, the EV cert is compatible for the kernel driver signing and works fine with the Sys dev portal. No difference, the sysdev link is just a 50 percent discount.`
So we will also take a DigiCert.

@zanderz OK for TransferWise , It seems like I have to create a link with the exact amount. How much would you like to donate ? (you can contact me directly by mail if you want more privacy on this liryna.stark@gmail.com)

**Comment by Liryna** [comment]
Thank to Keybase donation : , we will start the EV buying procedure Monday.
I will keep update this ticket with the status of the submission procedure to make Dokan run on Windows 10, version 1607 with secure boot.

I know that dokan is used in different business projects and I would only like to remember companies that open source is good but supporting it by providing resources or donation is also very well appreciated !

Without Keybase sponsorship, we would probably not be able to go further on this issue.
Thanks again to them !

**Comment by Liryna** [comment]
The DigiCert Hardware Token with EV Certificate has just been shipped.
We should get it in the 10-15 next days.

**Comment by Liryna** [comment]
I have been able to submit a dokan driver x64 for windows 10 family signature.
I don't have a windows 10 family for now but this should work since the driver has the Microsoft SHA2 signature.

The submit is manually for x64 and x86 :-1: and take some minutes to be approved.

Also like I said before, this version does only work with windows 10 family, other  windows 10 version needs HLK test.

**Comment by Rondom** [comment]
What does this MS-approval implemented technically? Is there be an additional signature from MS added to the binaries?

**Comment by Rondom** [comment]
> other windows 10 version needs HLK test.

Can you elaborate? What other Windows 10 versions are there? Any what do you mean by "Windows 10 Family"?

**Comment by Liryna** [comment]
The simple signature process (that I did and only work on windows 10 family) scan the binary to see if it has been signed by an EV certificate and if there is no virus and such.
When finished, you can download your driver back with the "Microsoft Windows Hardware Compatibility Publisher" SHA2 binary signature that replace your.

The HLK submission for making it work on other windows version will take more time (installing and configuring two windows server 2012 r2 with testing software) will take more time. And we will probably have to request and vendor ID to Microsoft.
It seems like Microsoft gives you a test profile that you have to run on your driver and when it passes all the test you can submit the report to the Microsoft portal that will sign your driver.

The second part is only supposition since...documentation is not clear on this.

**Comment by Liryna** [comment]
>Can you elaborate? What other Windows 10 versions are there? Any what do you mean by "Windows 10 Family"?


I just sent a mail to windows support with the exact question :smile: I have no idea and I have no more information on this that this link  https://msdn.microsoft.com/windows/hardware/drivers/develop/attestation-signing-a-kernel-driver-for-public-release

See how the submission is very full of information:
![untitled](https://cloud.githubusercontent.com/assets/4311419/17970953/f5f3b706-6ad8-11e6-947b-50d9ff0729ca.png)

**Comment by Rondom** [comment]
I think "family" it is just a way of saying that it applies to all "family members" in the Windows 10 family. What those family members are, I don't know. Maybe the editions (Home, Pro etc), or the versions or something else.... I don't know?

**Comment by Liryna** [comment]
@Rondom no idea also, I will give more informations when I get the microsoft support answer :(

**Comment by zanderz** [comment]
Your submission was approved in minutes? Ours is still pending after 3 days.

**Comment by Liryna** [comment]
@zanderz Yes, I just needed to wait that the bot analyse the cab during some minutes and I was able to download it directly.

I got an answer from sysdev support:
>I just signed my driver for Windows 10 Client family by using the hardware dev center, file signing services (create driver signing submission).
Does it only work for windows 10 family (Home ?) ? Or all Desktop (Home, Pro, Education and Enterprise) ?
[Jack] It covers all Win10 client SKU.
On which version on windows does the HLK signature is now forced ?
[Jack] All Windows OSes except Windows RS1(1607). 
Please refer to https://blogs.msdn.microsoft.com/windows_hardware_certification/2016/08/02/submissions-using-windows-10-version-1607-and-windows-server-2016-are-now-being-accepted/

I have not found an official list but it seems like windows 10 SKU are:

    Windows 10 Home
    Windows 10 Pro
    Windows 10 Mobile
    Windows 10 Enterprise
    Windows 10 Enterprise LTSB (Long Term Servicing Branch)
    Windows 10 Mobile Enterprise
    Windows 10 Education
    Windows 10 IoT Core (special versions for small footprint, low cost devices)
 http://www.askvg.com/list-of-windows-10-editions-skus/

Does someone know exactly what are Win10 client SKU ?

**Comment by kbarnes3** [comment]
Generally when someone at Microsoft says "Win 10 client SKU" they mean Home, Pro, Enterprise, Enterprise LTSB, and Education. In other words, versions of Windows 10 that most customers would run on a laptop or desktop. Mobile and IoT are not client SKUs.

Probably the biggest callout of something that isn't a Win 10 client SKU is Windows Server 2016, even though it has the same version number as Windows 10 1607 and runs on a lot of the same hardware.

**Comment by Liryna** [comment]
Thank you @kbarnes3 for making it clearer :smiley: !

I have been able to install HLK test environment.
Dokan **only** needs to pass the test "HyperVisor Integrity Readiness Test" http://go.microsoft.com/fwlink/?LinkId=787617

The test is very simple and passes with success on my side. I did all the steps but  have not been able to create a submission package on sysdev portal for now. I currently don’t have the certificate needed for it with me.

Also with the new system made by Microsoft, the release process becomes very heavy....it seems like test + submission has to be made on each architecture for each release and cannot be atomized :cry:

**Comment by sdecugis** [comment]
Dear @Liryna, thank you for your hard work and keeping us posted on the status. 
Can you share what is your plan related to releasing a driver compatible with this new Win 10 family ? When you write "on each architecture" do you mean you cannot use the previous way (with your older certificate or the newer one) for Win7, Win8, Win8.1, and only use the new submission process for Win10 (32 an 64) to limit the workload ? Or am I misunderstanding your sentence ?
Thank you~

**Comment by Liryna** [comment]
Hi @sdecugis ,

Dokan 1.0.0 will normally be release next week and will have a driver compatible with new Win 10.
I hope to get time until that to test HLK submission and make the release also compatible with windows 10 server.

> When you write "on each architecture" do you mean you cannot use the previous way (with your older certificate or the newer one) for Win7, Win8, Win8.1, and only use the new submission process for Win10 (32 an 64) to limit the workload ?

Yes, we can still sign as before the Win7, Win8, Win8.1 with SHA1/SHA2. It is only with Win 10 where you have to submit a your driver for 32 and 64 bit at each release manually and download back your driver with Microsoft signature SHA2. It means that I will make a manual step on the build script that will ask you to do the submission on Microsoft portal.

I hope I have been clearer :wink:

**Comment by sdecugis** [comment]
Yes, it is completely clear now, thank you!
Hopefully release 1.0.0 is completely stable and you don t need to update often afterwards :)

**Comment by Liryna** [comment]
HLK submission passed :+1: SO normally this should work on windows server also

If someone would like to test and give some feedback: (rename .pdf to .zip)
[dokan1.pdf](https://github.com/dokan-dev/dokany/files/452154/dokan1.pdf)

Install:
```
dokanctl /r d
//reboot
//replace C:\Windows\System32\drivers\dokan1.sys
dokanctl /i d
```

**Comment by Rondom** [comment]
So, when you refer to "Windows Server", does this mean it will work on Windows Server 2016?

**Comment by Liryna** [comment]
@Rondom Yes it should. I don't have a windows server 2016 for testing it but from Microsoft support information, this should be the case.

I don't even know if secure boot can be enabled with virtualbox to test it :'(

Dokan is even deployed in windows update :smile: (it is part of the submission that cannot be disabled...)

**Comment by Rondom** [comment]
I will try to setup a Win2016 after the weekend if no-one else volunteers ;-)
HyperV 2nd generation VMs support SecureBoot. KVM/qemu on Linux does as well once you have loaded some Microsoft-Keys manually.

**Comment by Rondom** [comment]
I am wondering... if Windows Update will update the Dokan driver, will there be any problems/conflicts with the MSI?

**Comment by Liryna** [comment]
@Rondom I don't think so, there is even no publishing version asked.
I guess this is only used if you plug device that match the driver description product ID.

**Comment by Rondom** [comment]
I (faintly) remember that Windows Update once offered me an update for a screen I only had connected to once. This was years ago, so take this with a grain of salt.
So I would not be surprised that users that have installed 1.0.0 would get 1.0.1 via Windows Update if you submit it to MS.

**Comment by Liryna** [comment]
No idea on this, but I truly don't give information about the dokan driver else than the .inf

This would be surprising behaviour if they do it :D

**Comment by sdecugis** [comment]
@Liryna: 
"If someone would like to test and give some feedback (x64):
dokan1.zip"
>> sorry for the late feedback; we tested that version on our side and it works properly for us on a fresh Win10 with secure boot enabled. Thank you for the great work!

Looking forward to the 1.0.0 stable release. (is it still planned shortly ? anything we can help with ?)

Kind regards

**Comment by Liryna** [comment]
@sdecugis oh that's perfect news ! Thank a lot for the testing ! It was something where I didn't have the hardware for it.

About 1.0.0 release, I am waiting a PR from @Rondom and two issues need to be fixed:
https://github.com/dokan-dev/dokany/issues/332
https://github.com/dokan-dev/dokany/issues/331
I am going to look at them during the next days but if someone can give a hand on it... :smiley: 

We are going to force the release next week.
@Rondom do you think this gonna be possible ?

**Comment by Rondom** [comment]
I should be able to make that by the end of the week (Friday) latest.
Testing under Win2016 I will only find time to on Thursday.

**Comment by Rondom** [comment]
Windows 2016 Technical Preview 5 with SecureBoot enabled does not accept the driver, it says it is not signed properly.
Maybe I misunderstood something. I thought running the HLK-tests is what is needed to get Windows Server 2016 to accept the driver as well.

**Comment by Liryna** [comment]
:cry: I tought it too...I don't see other way to sign it.
Does the microsoft signature on the driver is showed as valid by your windows 2016 ?

**Comment by Rondom** [comment]
I can see the Microsoft-signature, yes.

**Comment by js69** [comment]
Rondom, the normal signed RC4 driver doesn't work either on secure booted WinServ2016?

Only mention I could find of driver signing policy on that platform is here:

https://www.osr.com/blog/2015/12/29/recommendations-driver-signing-windows-10-otherwise/

OSR has some additional info here: http://insider.osr.com/2016/ntinsider_2016_01.pdf

**Comment by js69** [comment]
"An attestation signed driver will only work for Windows 10 Desktop; it will not work for other versions of Windows, such as Windows Server 2016"

https://msdn.microsoft.com/en-us/library/windows/hardware/hh801887#code_signing_faq

**Comment by Liryna** [comment]
@js69 
>OSR has some additional info here: http://insider.osr.com/2016/ntinsider_2016_01.pdf

Interesting ! They only tested microsoft signature on windows desktop also :D but nothing about windows server :cry: (page 19)

>https://msdn.microsoft.com/en-us/library/windows/hardware/hh801887#code_signing_faq
A dashboard signed driver that has passed the HLK tests will work on Windows Vista through Windows 10, including Windows Server editions.

Probably the HLK test has to be done on a Windows server 2016 to be signed compatible for this version. If that's the case, the release are really going to be fun :disappointed:

Windows server 2016 is going to be release in the next month. If I don't have the time to install a windows server 2016 next week, I will do the signature in the next release for it.

**Comment by js69** [comment]
https://developer.microsoft.com/en-us/windows/hardware/windows-hardware-lab-kit

> It is designed to help your company deliver systems, software, and hardware products that are compatible with Windows and that run reliably on Windows 10 for desktop editions (Home, Pro, and Enterprise) and Windows Server 2016.

The page doesn't mention anything further about Server 2016. There are also no Server 2016 iso files to download. I guess asking Microsoft directly is the best option.

**Comment by js69** [comment]
Did you run the "Static Tools Test"? There are apparently specific tests for Server 2016.

https://blogs.msdn.microsoft.com/windows_hardware_certification/2016/04/13/changes-to-the-static-tools-test-for-windows-server-2016/

**Comment by Liryna** [comment]
@js69 no I didn't and there nothing is nothing on the sysdev portal about it. It is probably only a testing framework.

There is an iso Windows Server 2016 Technical Preview 5 (x64) - DVD (English) on the msdn store. I will try to install it and submit a driver from it tomorrow.

**Comment by Liryna** [comment]
No time today, I moved the test to tomorrow.

**Comment by Liryna** [comment]
:sunglasses: Release will be signed for Windows server 2016
`Signature Only - Device - Compatible with Windows Server 2016, x64 `

**Comment by Liryna** [comment]
https://github.com/dokan-dev/dokany/releases/tag/v1.0.0
Driver are now signed for 1607.

If you have any issue, please let me know !

**Comment by Liryna** [comment]
EV Code Signing Certificate will expire this August. Dokan need again companies support 🔉 
https://github.com/dokan-dev/dokany/issues/808
