### ISSUE TITLE
sys/except.c: Suspicious code - Status is always EXCEPTION_CONTINUE_SEARCH in if condition

### ISSUE THREAD

**Issue by taruti** [dokan-dev/dokany#278]
`sys/except.c` contains the following:

```
  NTSTATUS Status = EXCEPTION_CONTINUE_SEARCH;
  ...
  if (Status == EXCEPTION_EXECUTE_HANDLER ||
      FsRtlIsNtstatusExpected(ExceptionCode)) {
```

Nothing modifies Status between these. 

Is this by purpose? Should Status be set differently or not checked at all in the if condition?

**Comment by marinkobabic** [comment]
You are right, only if the FsRtlIsNtstatusExpected(ExceptionCode)) is true, the Status will be changed. The Check of Status in if statement could by removed.

**Comment by Liryna** [comment]
You are right @taruti !
This has been removed: https://github.com/dokan-dev/dokany/commit/9d6bacedee6831619e00f701bb2de8e7853dd414
