### ISSUE TITLE
Cannot Unmount with DokanCtl.exe on Windows 8.1

### ISSUE THREAD

**Issue by Vassile-D** [dokan-dev/dokany#28]
I have a 64-bit Windows 8.1 system. After mounting a drive (say I mount it to F:), I cannot unmount it with `DokanCtl.exe /u F` or `DokanCtl.exe /u F:`. It will say that the mounter is Dokan's `mounter.exe`, path is Dokan's *SYS* file and `Unmount status: 0`.

I use Dokany with this application: https://cuemounter.codeplex.com/, so I'm not sure it is a Dokan issue.

Please look into it.

**Comment by Liryna** [comment]
Hi,

I made a test on my 64-bit Windows 8.1 VM with the mirror.
```
C:\Program Files\Dokan\DokanLibrary\sample\mirror>mirror.exe /r C:\Users /l m
Success
```
and in another shell
```
C:\Program Files\Dokan\DokanLibrary>dokanctl.exe /u m
mounter path C:\Program Files\Dokan\DokanLibrary\mounter.exe
driver path C:\Windows\system32\drivers\dokan.sys
Unmount status = 1
```
Can you try it ?

**Comment by Vassile-D** [comment]
![dokan x86](https://cloud.githubusercontent.com/assets/3415065/8419883/6ad0cffa-1e8b-11e5-86c6-8ded0f212047.jpg)

![dokan x64](https://cloud.githubusercontent.com/assets/3415065/8419895/746412f2-1e8b-11e5-9dff-81b86d8b7b4f.jpg)

`mirror.exe` **hangs** after executing, leaves no return in CMD, but *Disk M* (in another case *Disk N*) is accessible until I terminate the mirror process.

During the hang `DokanCtl.exe` returns **Unmount status = 0**.

**Comment by Liryna** [comment]
It is normal that ```mirror.exe``` hangs. It control the device and when it die, it close it.

But I never seen dokanctrl return 0 in a such simple test :O

Sorry to ask but just to be sure, What is the dokan version that you are using ? CueMounter propose the 0.5.3 but we have the [0.7.3](https://github.com/dokan-dev/dokany/releases/tag/0.7.3-RC)

**Comment by Vassile-D** [comment]
I'm using the latest RC version. The old project homepage is not there so I can't find v0.5.3.

I guess I can simply terminate process `mirror.exe` every time I want to get everything unmounted.

Might be just me, something wrong with my system, or it might be related to CUEMounter. If no other experiences this issue, you can close it for good.

**Comment by Liryna** [comment]
I am really sorry that I cannot help you more :(

I will let the ticket open if anybody have the same behaviour.

**Comment by Rondom** [comment]
See https://github.com/udaken/cuemounter for a fork of CueMounter with some activity that has been updated to Dokany.
