### ISSUE TITLE
Add solution EditorConfig properties for converting tabs to spaces

### ISSUE THREAD

**Issue by Corillian** [dokan-dev/dokany#284]
I use tabs but Dokan seems to use spaces. I never switch to spaces because I work with multiple solutions throughout the day and it's just a pain to be constantly toggling it. Visual Studio now has the ability to create editor config's with global solution settings for tabs/spaces so that when I open the Dokan solution it will automatically use the proper method of indentation: http://stackoverflow.com/questions/1212092/visual-studio-per-solution-indentation-settings

The plugin is at: https://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328

We should do this.

**Comment by Rondom** [comment]
Btw: there is already a clang-format file in the root directory

**Comment by Liryna** [comment]
@Rondom is right, we already use clang format.
It do a very great job, the only issue is that the plugin only indent when the code is selected and plugin called.

I still hope that one day the integration would be better :(

**Comment by Corillian** [comment]
Why not switch to something that's automatic then? I confess I'm a bit amazed that Visual Studio still doesn't support an elegant way to handle this out of the box but it looks like this add-in automatically formats for you.

**Comment by Liryna** [comment]
We can use EditorConfig to set proper indent tab space size but Visual studio will still not be able to handle the format style :cry:

**Comment by Liryna** [comment]
Current EditorConfig:
```
root = true

[*.{c, h, cpp, hpp}]
end_of_line = lf
insert_final_newline = false
trim_trailing_whitespace = false
indent_style = space
indent_size = 2
tab_width = 8
charset = utf-8
```

I tried to reproduce LLVM indent style. It work but EditorConfig even with `indent_brace_style = K&R`, it keep go to new line after `}` like:
```
//expected
} else {
}
//EditorConfig
}
else {
}
```

Also function arguments on multi lines are not aligned as clang format and there seems to be no option to handle it.
https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties

This is better than default Visual studio configuration so I would agree to add it but it cannot replace clang format.

**Comment by Corillian** [comment]
That's because the LLVM style is insane and makes code as hard to read as possible :p

**Comment by Liryna** [comment]
@Corillian , I think the EditorConfig I made should be added to the repository.

About LLVM style, I would totally be open to change it if people think it is horrible to work with.
I applied LLVM style because there were no limite in characet per line and it was horrible to scroll from right to the left every time and also because it was the most acceptable compared to other I found.

What would be the best code style to apply ?

**Comment by Corillian** [comment]
Yeah I have a 4k monitor and I really wish GitHub would allow code windows to take up more screen real-estate. That being said you can use a different coding standard while still maintaining discipline about character width - the two aren't mutually exclusive.

There's a school of thought that advocates for as much code being crammed into a small space as possible because it reduces the need for scrolling and therefore makes code more readable. I vehemently disagree with this and in fact think it achieves the opposite effect - making code extraordinarily unreadable. Personally I think inline bracing, the style that Dokan currently uses, encourages this type of behavior. For example:

```c++
if (NULL == Vcb) {
    Status = STATUS_INVALID_PARAMETER;
} else if (Vcb->Identifier.Type != VCB) {
    Status = STATUS_INVALID_PARAMETER;
} else if (!Vcb->Dcb->Mounted) {
    Status = STATUS_VOLUME_DISMOUNTED;
}
```

This is hopelessly difficult to read - particularly without syntax highlighting. I personally consider whitespace to be your friend and would refactor it as such:

```c++
if (NULL == Vcb)
{
    Status = STATUS_INVALID_PARAMETER;
}
else if (Vcb->Identifier.Type != VCB)
{
    Status = STATUS_INVALID_PARAMETER;
}
else if (!Vcb->Dcb->Mounted)
{
    Status = STATUS_VOLUME_DISMOUNTED;
}
```

Does it require more scrolling to read? Yes - however if you are quickly scanning code for specific types of statements it is *much* easier to identify what you are looking for. Here's another example:

```c++
if (NT_SUCCESS(status) && EventInfo->BufferLength != 0 &&
    fileObject->Flags & FO_SYNCHRONOUS_IO && !(irp->Flags & IRP_PAGING_IO)) {
    // update current byte offset only when synchronous IO and not paging IO
    fileObject->CurrentByteOffset.QuadPart =
        EventInfo->Operation.Write.CurrentByteOffset.QuadPart;
    DDbgPrint("  Updated CurrentByteOffset %I64d\n",
              fileObject->CurrentByteOffset.QuadPart);
}
```

Which I would refactor as:

```c++
if (NT_SUCCESS(status)
    && EventInfo->BufferLength != 0
    && (fileObject->Flags & FO_SYNCHRONOUS_IO)
    && !(irp->Flags & IRP_PAGING_IO))
{
    // update current byte offset only when synchronous IO and not paging IO
    fileObject->CurrentByteOffset.QuadPart =
        EventInfo->Operation.Write.CurrentByteOffset.QuadPart;

    DDbgPrint("  Updated CurrentByteOffset %I64d\n",
              fileObject->CurrentByteOffset.QuadPart);
}
```

In my opinion that's dramatically easier to read and still maintains your character width restrictions.

Lastly I would encourage a requirement that all control flow statements, such as if...else, are required to use braces. When I used to write safety critical software for the aerospace industry this was actually a requirement. For example:

```c++
if(someVar)
    DoSomething(); // BAD

if(someVar)
{
    DoSomething(); // GOOD
}
```

The heartbleed bug in OpenSSL that made half of the internet insecure was caused by this very issue. Someone created an `if()` statement without braces and when someone else later added an additional statement they forgot to add braces along with it.

Those are my 2 cents if anyone else has any thoughts on the matter.

**Comment by Liryna** [comment]
:+1: You made your point
I will check to config cland format to look like this after your contribution (otherwise the merge gonna be hell :smile: )

**Comment by Liryna** [comment]
Hi @Corillian ,

I have made some changes on clang format in a test branch https://github.com/dokan-dev/dokany/commit/18532667a0e7fdcf46e1962bf2771669969f079c

I have up ColumnLimit to 120, enable break at each braces and up indent width to 4.
This look a little more what you proposed for improving code reading.

I have looked to add braces on singles if and add break at each if conditions but both seems to be currently not possible with clang format 😢 

I would like some feedback on this and know if it should be applied on the master ?

**Comment by Liryna** [comment]
Lets run clang format with this changes on 2.0.0 since the indent is already changed

**Comment by Liryna** [comment]
We will keep the google code style as it is. This can be reopen if there is a strong argument.
