### ISSUE TITLE
Can copy but not open remote files with 1.0.0-rc3

### ISSUE THREAD

**Issue by lefty74** [dokan-dev/dokany#288]
# Environment
 * Windows version: 8.1 Enterprise
 * Processor architecture: Intel Core i7-4770
 * Dokany version: 1.0.0-rc3
 * Library type (Dokany/FUSE): Not sure
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation _[I'm not sure what this means]_
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description
Using dokany 1.0.0-rc3 with win-sshfs 1.6.0-rc2, I found I could not open files from my remote directory. I could copy them to a local directory and they then opened.
I went back to win-sshfs 1.5.12.8 with dokany 7.4 and files can open OK.
I realise that's not much to go on right now, but I'm not sure what to do to troubleshoot. I'm happy to respond to requests for troubleshooting steps or log files.
The remote directory is on a server on the university LAN.

# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
In case of BSOD, please attach minidump or dump analyze output.
_I do not have these log files and the instructions in the link aren't clear to me, but I will get log files given some more detailed instructions_

**Comment by Liryna** [comment]
Hi @lefty74 ,

This is a win-sshfs issue, not dokan. You should open a ticket there.

**Comment by lefty74** [comment]
OK. I wasn't sure which component wasn't working so I raised it in both places.
