### ISSUE TITLE
FILE_OPEN_REQUIRING_OPLOCK doesn't work

### ISSUE THREAD

**Issue by bailey27** [dokan-dev/dokany#289]
# Environment
 * Windows version:  Windows 10
 * Processor architecture: x64
 * Dokany version: current source
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x ] I can always reproduce the issue with the provided description below.
  - [ x] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description

I remember when working on https://github.com/dokan-dev/dokany/issues/249 seeing this code fail

https://github.com/dokan-dev/dokany/blob/1e1bff388751a903fb2c099d6cebbaeb8b76e90e/sys/create.c#L1101-L1116

And I noticed it again when working on https://github.com/dokan-dev/dokany/issues/285

I wrote this test program to reproduce the failure.

http://pastebin.com/kp6L3uCk

I think I found the reason.  If I add a call that I found in fastfast that sets the oplock key, if any, then the create with FILE_OPEN_REQUIRING_OPLOCK  succeeds.

Here is what I think should be the fix, in a branch in my fork:

https://github.com/bailey27/dokany/commit/6610d7765ee19c55255ac86cb09046cce882eb47

It doesn't seem to break anything else by doing this.

# Logs
When it fails, it prints this

```
DokanFS]    FsRtlOplockFsctrl failed with 0xc000000d, fileName = \foo.txt, fileCount = 1
```

**Comment by Liryna** [comment]
Hi @bailey27 ,

This does seems to be the good way to handle `FILE_OPEN_REQUIRING_OPLOCK` from what I see in the documentation and osronline explanation https://www.osronline.com/showThread.CFM?link=148269

You can create a pull request if you want, otherwise I add your patch like other contribution :smiley: 

It would be great to have a testing framework for oplock, to be sure that next change would not break it :(

**Comment by Liryna** [comment]
@bailey27 after testing, I pushed your changes on the master.

Thank you for your contribution as always !!! :+1:
