### ISSUE TITLE
dokanctl fails to install services (Main device file not found)

### ISSUE THREAD

**Issue by suy** [dokan-dev/dokany#29]
Hi.

In some circumstances, we can't get our application to work. DokanMain fails like this:

    [3032] Dokan: debug mode on
    [3032] Dokan Error: CreatFile Failed \\.\Dokan: 2
    [3032] DokanMain completed with status -3
    [3032] Can't install driver

The last two lines are the return value we get from DokanMain and the text in the dokan.h file next to the #define.

From what I see in the DokanMain code, that's CreateFile returning ERROR_FILE_NOT_FOUND on the main driver device. What could cause this? Is there something that we can try to find out the issue? The installer worked fine, and gave no errors. What could be the reason theh device it's not there?

Thank you.

PS: We are using DokanY 7.3 RC.

**Comment by Liryna** [comment]
Hi,

I already had such behaviour too.
Does it work If you use the dokanctl to reinstall the driver & service ?
Have you run the install in Administrator ?

**Comment by suy** [comment]
El Tuesday 30 June 2015, Liryna escribió:
> I already had such behaviour too.
> Does it work If you use the dokanctl to reinstall the driver & service ?

I'll try ASAP. I tried to uninstall and install again, but same result.

On that note: dokanctl is a really small application that calls some functions 
that are available in the library, but have no public header (are in 
dokanc.h). The DokanService* functions might be useful for application 
developers, e.g. for their own installers. Do you have an opinion about those?

Otherwise I'll maybe launch the process from my application, if that's going 
to fix it.

> Have you run the install in Administrator ?

Not explicitly. I thought it would ask for Administrator rights if needed.

-- 
Alex (a.k.a. suy) | GPG ID 0x0B8B0BC2
http://barnacity.net/ | http://disperso.net

**Comment by Liryna** [comment]
> On that note: dokanctl is a really small application that calls some functions that are available in the library, but have no public header (are in dokanc.h). The DokanService* functions might be useful for application developers, e.g. for their own installers. Do you have an opinion about those?

Export DokanService functions can be a good idea for people who need it.

>Not explicitly. I thought it would ask for Administrator rights if needed.

Sorry, I made a mistake. Yes normally it should always ask you the admin rights.

I made a test again and the driver and services was not installed because  the Packages redistribuables Visual C++ 2013 was not installed. The installation was alright but dokanctl command failed in silence.
Do you think it could be the same case as you ?

**Comment by suy** [comment]
Yes! That could be the case indeed. On my machine it has worked well always, but not on machines with less (development) things installed.

I'm also trying to run dokanctl commands in the machine where everything else is working, and those fail... sometimes. E.g., on a recently rebooted system, I try my app and works. Then run `dokanctl /r a` and uninstalls everything. Then `dokanctl /i a` and only installs the mounter but not the driver. Reboot, and run `dokanctl /i d` to install the driver. The message says it has failed, but the file system application works again.

I'll try to see if I can reproduce it properly. Please, let me know if you know more details.

And thank you.

**Comment by Liryna** [comment]
:O
Yes, if you can have some more details about it ! it is a strange behaviour that you describe.

**Comment by suy** [comment]
For now I can confirm that on one computer the installation fails. When `dokanctl /i a` runs, Windows complains that it "failed" or "closed" (I don't know the original message, that copy is localized in Spanish), and the installer shows that it returned with exit 255. It complained about the lack of a MSVC DLL, so you were right about that.

**Comment by marinkobabic** [comment]
The next time you have this issue please execute inside of the command prompt

NET START Dokan

And check if the application works.

**Comment by suy** [comment]
@marinkobabic Thank you for the hint, I was not aware of that. I was going to implement myself the DokanServiceInstall. I get "the service name is not valid" error, though. :-(  With dokan.sys being there.

I'll try to install the services from my own application and try to find the exact place were it fails. Let me know if there is more information I can provide.

Thanks!

PS: I'll rename the issue. At this point is clear that it's a driver/service installation issue.

**Comment by suy** [comment]
Phew, confirmed, in the other troubled system the problem (and the fix) was the same. :) I'll leave it open, but feel free to close if you think it's right. It's a problem with the installer only, after all.

**Comment by suy** [comment]
Oops, wrong button. Sorry for the noise. And thank you.

**Comment by Liryna** [comment]
Ok great ! I will close it so :+1:

**Comment by marinkobabic** [comment]
@suy 
You don't need to write any installer for tests. Just <a href="http://liveupdate.ruf.ch/transfer/dokanx_driver.zip" target="_blank">download this driver</a> and perform the test again and let me know if all works as expected. Before you do that, remove the previous driver. For installation just right mouse click on inf file and select install. Reboot the machine and check if all works. It's the simplest way to install the driver.

**Comment by marinkobabic** [comment]
@suy 
Is the machine Windows 7. If the answer is yes, so try to install the following hotfix

https://www.microsoft.com/en-us/download/details.aspx?id=46148

**Comment by suy** [comment]
@marinkobabic Thanks for your help! Respect the driver: as I understand it, we never had an issue with the driver by itself, it's just that dokanctl failed to do the CreateService call to install it. In the second machine where I had the issue, yes, it was Windows 7, and putting the library there fixed it. Since we'll have to ship it anyway alongside our executable, it's fine.

**Comment by Maxhy** [comment]
Ok to warn for this issue I just pushed commit https://github.com/dokan-dev/dokany/commit/a4762f4aa01063ed0188290db43d7cf310a38fc1 which do VC++ 2013 prerequisite check at installation and ask to open Microsoft download page if missing (no check done in silent mode).
