### ISSUE TITLE
Optimize directory FindFiles by caching searches in the kernel

### ISSUE THREAD

**Issue by Corillian** [dokan-dev/dokany#291]
From the discussion in #210.

The user-mode driver dokan.dll caches directory searches because the OS can request partial results from the same directory search multiple times. This caching should be moved into the kernel to avoid the two extra user/kernel mode transitions. Lastly Dokan should probably provide a way for the user-mode driver to invalidate this cache and notify the OS that the filesystem has changed. This is important if a driver is, for example, mirroring a remote FTP server and it notices that the remote directory has been modified.

**Comment by Liryna** [comment]
This is now implemented from v2
