### ISSUE TITLE
Error 0x80070643 when installing on Window 7

### ISSUE THREAD

**Issue by Green7** [dokan-dev/dokany#292]
# Environment
 * Windows version: 7 
 * Processor architecture: x64
 * Dokany version: 1.0.0-RC3
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet]
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the latest version and have reboot my computer after.

# Description

I have fresh Windows 7 SP1 x64 machine. Before Dokan KB3033929 was installed. After this machine was rebooted.
When I'm installing Dokan (DokanSetup_redist.exe) I have error 0x80070643.

# Logs
[Dokan_Library_1.0.0.103_Bundle_20160720225015.txt](https://github.com/dokan-dev/dokany/files/374646/Dokan_Library_1.0.0.103_Bundle_20160720225015.txt)

**Comment by Liryna** [comment]
@js69 did you already faced this error ?
I only found .NET installation corrupt when I look for 0x80070643

**Comment by js69** [comment]
Green7, could you please also upload C:\Users\Admin\AppData\Local\Temp\Dokan_Library_1.0.0.103_Bundle_20160720225015_003_Dokan_x64.msi.log ?

0x80070643 is basically a "catch everything else" error, details are in the other log.

**Comment by Green7** [comment]
Here is log.
[Dokan_Library_1.0.0.103_Bundle_20160720225015_003_Dokan_x64.msi.log.zip](https://github.com/dokan-dev/dokany/files/374774/Dokan_Library_1.0.0.103_Bundle_20160720225015_003_Dokan_x64.msi.log.zip)

**Comment by js69** [comment]
Windows Installer couln't execute the CustomAction. 

There is no .NET 4 installed yet? Newer installers will check for that.

---
Calling custom action WiXCA!WiXCA.CustomActions.ExecuteInstall
Error: could not load custom action class WiXCA.CustomActions from assembly: WiXCA
System.BadImageFormatException: Nie można załadować pliku lub zestawu 'WiXCA' lub jednej z jego zależności. Ten zestaw jest konstruowany przez moduł wykonawczy nowszy niż aktualnie załadowany i nie można go załadować.
Nazwa pliku: 'WiXCA'
   w System.Reflection.Assembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, Assembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection)
   w System.Reflection.Assembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, Assembly locationHint, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection)
   w System.Reflection.Assembly.InternalLoad(AssemblyName assemblyRef, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   w System.Reflection.Assembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   w System.AppDomain.Load(String assemblyString)
   w Microsoft.Deployment.WindowsInstaller.CustomActionProxy.GetCustomActionMethod(Session session, String assemblyName, String className, String methodName)

OSTRZEŻENIE: rejestrowanie informacji o powiązaniach zestaww jest wyłączone.
Aby włączyć rejestrowanie błędw powiązań zestaww, ustaw wartość rejestru  (DWORD) rwną 1.
Uwaga: z włączeniem rejestrowania błędw powiązań zestaww wiąże się pewien spadek wydajności.
Aby wyłączyć tę funkcję, usuń wartość rejestru .

**Comment by Green7** [comment]
Yes you're right, the .NET 4 was not installed.
So I:
- installed .NET 4 framework
- after this Dokan installer was successful
- but the Dokan driver was still not installed. When I tried mirror example I had "Can't install driver" message.
- so I'm ran: dokanctl.exe /i d  
After this everything works correctly.

**Comment by js69** [comment]
That's probably because the previous driver wasn't rolled back completely from the failed install.

Did you reboot before you installed again?

**Comment by Green7** [comment]
No. But I can check everything one more time on fresh system.

**Comment by Liryna** [comment]
Thank you @js69 for your analyse :heart: 

@Green7 like said @js69 , this issue will be fixed in the next release by the .NET 4 check.
Thank you for your report !

**Comment by Rondom** [comment]
I know there are quite some bugs to be fixed before 1.0. What about pushing out another RC (to facilitate wider testing of the installer)?

**Comment by Liryna** [comment]
:+1: I will just wait @marinkobabic changes on mount unmount that his is currently testing with @taruti
