### ISSUE TITLE
Invalid size for library generated with VS on dokan versus 'standard' volume

### ISSUE THREAD

**Issue by EpsilonXX** [dokan-dev/dokany#295]
Hi guys,

I got some troubles to build a lib using Dokan,I'm wondering if you got  the same issues.
(BTW thanks for the fix for the socket network issues, work like a charm)

Thx

# Environment
 * Windows version: Win7 -Win10 ,
 * Processor architecture:x64 
 * Dokany version: lastest branch 
 * Library type (Dokany/FUSE): dll
 
# Check List

# Description
When a library is generated with the ms linker ,its end of file is filled of zero (the linker writes to much data  (like rounding to 32Kb in my case instead of 9 848 bytes ) ,as a result when you link an application with a this file ,visual will invalid it as corrupted.
Steps to repro:
Compile the sample provided in a standard drive and mounted drive ,
C: 9848 bytes
Dokan:32Kb ( with the correct data untit 0 following to reach the 32Kb)

I spent time to understand why the linker requests to much data to write without a chance..
Any ideas ?

(please rename the pdf extension to zip,the upload didn't allow me with the zip extension)

[mismatchLibSize.pdf](https://github.com/dokan-dev/dokany/files/375648/mismatchLibSize.pdf)

**Comment by Liryna** [comment]
Hi @EpsilonXX ,

If I understood correctly, you are building the library on a dokan device ?
Did you try to play with Sector and AllocationUnit Size ?
https://github.com/dokan-dev/dokany/blob/1675b21181abb8e0a032453bd6da968759cbbd65/dokan/dokan.h#L77-L78

**Comment by EpsilonXX** [comment]
Hi Liryna,

Yep ,i built the lib on a dokan device ,I played with both flags Sector and AllocationUnit Size without a chance.
The linker seems to compute a 'size to write' based some information from the volume or files ,filespy shows the difference with the IRP_MJ_WRITE between using dokan or not.

**Comment by Liryna** [comment]
This option does change the behaviour of the Write size request from the kernel.
Are you using the C mirror ?

**Comment by EpsilonXX** [comment]
I got the same 'bugged' size changing the sector size but I didn't check if the request was the same.
I use the  C mirror, I forgot to mention that the linker called setallocationsize/ setEndOfFile and mix read/write within the same handle file.

**Comment by Liryna** [comment]
Hi @EpsilonXX ,

I did the test and you are right sector size does not affect the behavior.

There is a difference of size between library build on NTFS and dokan.
There is an extra, write of 32768 made by link.exe at the end of the build that explains the difference on Dokan devices.

When you compare IRP between NTFS and Dokan (see filespy logs), they all seem to be the same EXCEPT most of the write on NTFS are using FASTIO.

I don't know if this behavior is happening because FASTIO is currently not supported by Dokan.


[dokan-filespy-build.txt](https://github.com/dokan-dev/dokany/files/380181/dokan-filespy-build.txt)
[mirror-build.txt](https://github.com/dokan-dev/dokany/files/380179/mirror-build.txt)
[normal-filespy-build.txt](https://github.com/dokan-dev/dokany/files/380180/normal-filespy-build.txt)

This behavior does not happen with Console Application projects.

**Comment by EpsilonXX** [comment]
Hi Liryna,

From  the normal-filespy log ,it seems that the write operation allow to write until the EndOfFile value
(	IRP_MJ_WRITE	00060003	FFFFC00058F90C00	...mismatchLibSize.lib	STATUS_SUCCESS	Offset: 00000000-00000000 ToWrite: 3000 Written: 274A) (EndOfFile: 00000000-0000274A)

in the dokan log ,it's not the case =>IRP_MJ_WRITE	00060043	FFFFE00063053448	... mismatchLibSize.lib	STATUS_SUCCESS	Offset: 00000000-00000000 ToWrite: 8000 Written: 8000 (EndOfFile: 00000000-00002700)

As I know ,when 'write' calls return less bytes that requested it's because an insufficient disk space ) ,might the situation we have is one of the behavior that end of file/allocation size handle. (from mdsn SetEndOfFile function can be used to truncate or extend a file.)

**Comment by Liryna** [comment]
From https://msdn.microsoft.com/en-us/library/windows/desktop/aa365747(v=vs.85).aspx
`The system interprets zero bytes to write as specifying a null write operation and WriteFile does not truncate or extend the file. To truncate or extend a file, use the SetEndOfFile function.`

So as you said, writefile from mirror should not write all data.
I am wondering why it succeed.

**Comment by EpsilonXX** [comment]
I did these quick test with my Dokan application
in the setendofFile , I store the endoffile in my file context 
and before the write operation ,I use this pseudo code

  u32 newPosEndFile = Offset + NumberOfBytesToWrite;
        if (file->hasEndOfFile() && newPosEndFile > file->getEndOfFile())
        {
            NumberOfBytesToWrite = file->getEndOfFile() - Offset;
        }

It's working for the 80 libraries used on our project  (the lib matched the expected size,and final link succeeded =>exe worked like a charm).

Still investigating..

**Comment by bailey27** [comment]
Could this maybe be related to https://github.com/dokan-dev/dokany/issues/62 ?

It looks to me that in @Liryna 's filespy log that when it writes to the .lib, the IRP_PAGING_IO (0x00000002) flag is set, so the write shouldn't go past the end of the file.  

That's what fastfat does https://github.com/Microsoft/Windows-driver-samples/blob/master/filesys/fastfat/write.c#L1390-L1403

**Comment by Liryna** [comment]
:+1: Exact !
Cache file should really be thinked and implemented.
I haven't found a way to do it correctly without making user land heavy to handle it.

**Comment by Liryna** [comment]
https://github.com/dokan-dev/dokany/pull/64 does seems to handle it correctly.
I just found it too heavy for the user land.
For exemple the issue we face is handle in the mirror: https://github.com/dokan-dev/dokany/pull/64/files#diff-210b81c018cd0036b1a9abb162fb97b9R551
@bailey27 do you have an idea about it ?

**Comment by bailey27** [comment]
@Liryna ,

I don't understand what you mean by it being too heavy for user mode.  I think the only maybe heaving thing user mode would need is the GetFileSize().  But I think that isn't too heavy.

I don't understand what that code (https://github.com/dokan-dev/dokany/pull/64/files#diff-210b81c018cd0036b1a9abb162fb97b9R551) is doing around line 551 in mirror.c.  That doesn't look to me like right way to limit the length of the write to not go past the end of file.

What I did is like this https://github.com/bailey27/cppcryptfs/commit/2b11457c2bd903a0885f1a57cd32848a81e12e54

Which makes the .lib be about 9KB instead of 32KB.

By the way, my linker is happy with the 32KB .lib as it is with the 9KB.  Even if I add a function to the library and call it from the main program it is linked with, the link still succeeds in either case.

I did find that I have a problem with generating precompiled headers with cppcryptfs (but not with mirror).  I had to turn them off for it to work.  I need to look into that.

**Comment by Liryna** [comment]
line 551 is not the same as https://github.com/bailey27/cppcryptfs/commit/2b11457c2bd903a0885f1a57cd32848a81e12e54#diff-a4697fdfb06ecd4d9b754a7e2a58aa26R262 ?

Yes, it is not that heavy for user land. I was just thinking to handle cases like https://github.com/dokan-dev/dokany/pull/64/files#diff-210b81c018cd0036b1a9abb162fb97b9R528 directly in dokan without contacting the FS. But it don't seems that there is much more :smiley: 

I will test to merge the PR in the master. Does precompiled headers happen with a default generate solution ?

**Comment by bailey27** [comment]
@Liryna ,

I guess dokan could keep track of the application-side view of what the end of the file is and disallow writes past it.  But the GetFile|Size() won't necessarily be the same (as in the case of cppcryptfs).

The precompiled header problem does happen with a default solution.  But it doesn't happen with mirror.

**Comment by Liryna** [comment]
@bailey27 ,

alright, I merged the changes on my repository for now
https://github.com/Liryna/dokany/commit/5d0edafd220967f36c2a6a2408d5c4048fcc9db1

fsx tools with memory mapped operations pass perfectly now.
I moved end of file and paging IO check in kernel. Is this alright for you ?
https://github.com/Liryna/dokany/commit/5d0edafd220967f36c2a6a2408d5c4048fcc9db1#diff-186f697a50e48562500c4beb285c7e58R133

Other operations do not seem to be movable like you told :+1:

**Comment by bailey27** [comment]
@Liryna ,

It looks ok to me. Before I was confused about the code that was checking for unsigned/signed subtraction wrapping, but I understand now.

**Comment by Liryna** [comment]
Ok thank you @bailey27 this has been merged to the master https://github.com/dokan-dev/dokany/commit/1d53d9ae44e7b95563739729959f764812870d3d

@EpsilonXX can you make a test ?

**Comment by Liryna** [comment]
@EpsilonXX you can test the fix with last RC https://github.com/dokan-dev/dokany/releases/tag/v1.0.0-RC4

**Comment by EpsilonXX** [comment]
Hi Liryna,

Unfortunately ,it didn't work for me ,with RC4, the compilation never finished and the mirror application leaked with the handles.
With the latest fixes ,the leaks are gone but still stuck with the compilation process.
I had to back to RC3.

Thx

**Comment by Liryna** [comment]
Hi @EpsilonXX ,

There was a missing mutex unlock that was making VS not able to proceed the build.
Fixed with https://github.com/dokan-dev/dokany/commit/4a66a6f5e32fc56d33e3569591cfd88b8a13cd3f

**Comment by EpsilonXX** [comment]
It's working now.
Thx
