### ISSUE TITLE
This is a new solution for developing user mode file systems for Windows

### ISSUE THREAD

**Issue by pccq2002** [dokan-dev/dokany#298]
This is a new solution for developing user mode file systems for Windows，[https://github.com/billziss-gh/winfsp](url)

![image](https://cloud.githubusercontent.com/assets/374212/17054656/d4395b7e-503a-11e6-854e-b2a15bf65289.png)

**Comment by Liryna** [comment]
Google groupe already talk about it :) 
Please join the thread
