### ISSUE TITLE
WriteFile() of length zero bytes fails

### ISSUE THREAD

**Issue by bailey27** [dokan-dev/dokany#299]
# Environment
 * Windows version: Windows 10
 * Processor architecture: x64
 * Dokany version: 1.0.0-RC3 and current source
 * Library type (Dokany/FUSE): Dokany 
 
# Check List
  - [x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ x] I can always reproduce the issue with the provided description below.
  - [x ] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description

If you open a file on a mirror fs and call WriteFile() with nNumberOfBytesToWrite = 0 (write 0 bytes), then the WriteFile() fails with LastError = ERROR_INVALID_PARAMETER.

It succeeds on the C: drive.

The problem seems to be that the kernel-mode driver is returning status success without completing the irp.

The fastfat driver checks this condition early as well, but it completes the irp normally.

ReadFile() of zero bytes was working though, I think because the irp was being completed normally in that case.

I also noticed that in both read and write, if the length is zero, the driver was not setting Irp->IoStatus.Information = 0 like the fastfast driver does in both cases.

**Comment by Liryna** [comment]
Hi @bailey27 ,

You are right ! Write should well return SUCCESS when length is 0.
https://github.com/Microsoft/Windows-driver-samples/blob/6e1115d6af3c22b693eccc472ebb0d53a1905cd9/filesys/fastfat/write.c#L334

Thank you for your contribution and very appreciate as always!
and for installing clang-format ! :+1: 

Are your still working on cppcryptfs or reviewing dokany :heart:  ?

**Comment by bailey27** [comment]
@Liryna ,

You're welcome.

I haven't used clang-format before.  I use Notepad++ to edit the Dokany code.  I set the tab size to 2 and expand tabs as spaces.  I can still mess up the formatting, though.

I see the .clang-format file .   I will get clang-format and try it out.  Thanks for telling me about it.

I think cppcryptfs is completed.  It doesn't seem to have any more bugs that don't happen with mirror.  It really isn't much more than a mirror with encryption.

I think I'll have to change cppcryptfs when https://github.com/dokan-dev/dokany/issues/210 is done.  I don't mind.  I can really see how anything that uses networking needs those changes.

**Comment by Liryna** [comment]
Notepad++ seems to be compatible with EditorConfig https://github.com/dokan-dev/dokany/issues/284
I begin to think this should be really added :smile: !
Yes, #210 is going to be a great improvement !

**Comment by dmi3s** [comment]
MS World, Excel and PowerPoint won't work without this fix. @bailey27, @Liryna thanks a lot!

**Comment by Liryna** [comment]
No problem :+1: 
What kind of version of Office did you was using ?

**Comment by dmi3s** [comment]
ms office 2013. but even a paint from ms windows 10 can't rewrite existing file on a virtual disk. this is really a great patch!
