### ISSUE TITLE
WS 2008 R2 64bit MSVCR120.dll

### ISSUE THREAD

**Issue by witchi** [dokan-dev/dokany#30]
I have tried 0.7.1 and 0.7.2, but both return only that MSVCR120.dll is missing. What I have to install additionally?

**Comment by suy** [comment]
See issue #29. Latest installers (release candidates for 0.7.3) should have the fix, I think.

**Comment by landrix** [comment]
You need the Visual C++ redistribuables for Visual Studio 2013 
from here
https://www.microsoft.com/de-DE/download/details.aspx?id=40784

https://github.com/dokan-dev/dokany/wiki/Installation

**Comment by witchi** [comment]
I have installed the package, but the lib is still missing. I can see the Microsoft Visual C++ 2013 Redistributable (x64) in version 12.0.30501.0 within the Control Panel/Programs and Features, but the Dokan installation routine can't find it ("Your system does not appear to have Microsoft Visual C++ 2013 Runtime installed. Would you like to download it?").

If I ignore the message, Dokan will be installed. But dokanctl.exe says, the MSVCR120.dll is still missing.

**Comment by witchi** [comment]
I have to install the x86 version of Microsoft Visual C++ 2013 Redistributable too. Then it will work. On a 64bit system you have to install both versions.

Thanks!

**Comment by marinkobabic** [comment]
It depends how your application which consumes the dokan.dll is compiled. If it's compiled for for x86 then your have to install Visual C++ 2013 Redistributable for x86 and otherwise fro x64. This is the only logical way. Depending on the target plattform you will use different dokan.dll.

**Comment by Maxhy** [comment]
Yes. And on a x64 system the installer check for both prerequisites (VC++ 2013 x86 and x64) because both Dokan Libraries files sets are installed.
