### ISSUE TITLE
Installer: Verify KB3033929 check is sufficient with both GDR/LDR

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#306]
We check for [KB3033929](https://support.microsoft.com/en-us/kb/3033929), by looking at the version of wintrust.dll. 

During investigation into issue #304 I looked at [KB2862966](https://support.microsoft.com/en-us/kb/2862966) which is an older update the user had installed. I was looking at the files contained in the update and was alarmed that an older update can actually install a strictly speaking newer version of the file (if one compared the version numbers).  This older update can install 6.1.7601.22380 which is larger than the 6.1.7601.18741 we check for. KB3033929 ships with both 6.1.7601.18741 and 6.1.7601.22948. There seem to be GDR and LDR versions shipped with updates depending on whether you have non-security bugfix-only updates installed. So, I am wondering whether the current check we have is enough, given that there are GDR and LDR versions shipped with the updates. I do not have much of a clue about Windows and the difference between GDR and LDR. Here is some info (first, google result) https://blogs.technet.microsoft.com/mrsnrub/2009/05/14/gdr-qfe-ldr-wth/.

Somehow if the last part is 6.1.760**1.18**xxx it is GDR and if it is  6.1.760**1.22**xxx it is LDR. So we might need to check for both versions.

Maybe someone with some Windows and MSI expertise (@js69) can suggest a good way to deal with this.

**Comment by js69** [comment]
Microsoft Updates will not overwrite a higher version with a lower one (unless something crazy is going on). KB3033929 should install the new file in any case as it is a higher version.

**Comment by Rondom** [comment]
Yeah, but we  could detect that KB3033929 is installed even if it is not if we only check for >6.1.7601.18741 and some 6.1.7601.22xxx smaller than 6.1.7601.22948 is installed.

**Comment by js69** [comment]
The check is for MinVersion="6.1.7601.18740". Both 6.1.7601.18741 and 6.1.7601.22380 should give true.

The problem on DimitarKapashikov's Win 7 is that he has version 6.1.7601.18205 which fails that check.

If he can not install/uninstall KB3033929 he has unrelated general issues with Windows Update.

**Comment by Rondom** [comment]
I am well aware that this issue is unrelated to  DimitarKapashikov's issue #304
 
> The check is for MinVersion="6.1.7601.18740". Both 6.1.7601.18741 and 6.1.7601.22380 should give true.

Don't you see this as a problem? 6.1.7601.22380 is too old for us! We need at least 6.1.7601.22948 which comes with KB3033929.

**Comment by js69** [comment]
Ah, I now grok what you mean. I'm not quite sure though when the 22380 would ever be installed.

We'll have to combine a few version checks (or write a CustomAction) for that logic (>6.1.7601.18740 AND <6.1.7601.20000) OR >6.1.7601.22947

**Comment by Liryna** [comment]
Well found @Rondom :+1: 
@js69 do you have an idea how this could be improved ?

**Comment by Rondom** [comment]
IIRC it is possible to store the DLL's version number in a variable. If I am not mistaken it might even be stored in the variable and we use it only in a boolean context right now.

**Comment by Liryna** [comment]
```
<Property Id="WIN7KB3033929GDRINSTALLED" Secure="yes">
      <DirectorySearch Id="searchSystem3" Path="[SystemFolder]" Depth="0">
        <FileSearch Id="WINTRUST_FileSearch"
                    Name="wintrust.dll"
                    MinVersion="6.1.7601.18740"
                    MaxVersion="6.1.7601.20000"/>
      </DirectorySearch>
</Property>

<Property Id="WIN7KB3033929LDRINSTALLED" Secure="yes">
      <DirectorySearch Id="searchSystem3" Path="[SystemFolder]" Depth="0">
        <FileSearch Id="WINTRUST_FileSearch"
                    Name="wintrust.dll"
                    MinVersion="6.1.7601.22947"/>
      </DirectorySearch>
</Property>
```

This should do the job if I am correct @js69  ? We will need to check if `(VersionNT = 601 AND WIN7KB3033929GDRINSTALLED OR WIN7KB3033929LDRINSTALLED)` ?

**Comment by js69** [comment]
(VersionNT = 601 AND (WIN7KB3033929GDRINSTALLED OR WIN7KB3033929LDRINSTALLED)) I guess should work, right.

I just don't know how to find/create a OS situation where 6.1.7601.22380 is actually installed.

**Comment by Liryna** [comment]
http://social.technet.microsoft.com/wiki/contents/articles/3323.how-to-forcibly-install-the-ldr-branch-from-a-particular-hotfix-package.aspx

It seems that you can extract the patch and select LDR version.

**Comment by Liryna** [comment]
I have been able to install it.
Download and put the kb on a folder, run **two** times `Windows6.1-KB3033929-x64.msu` 
It gonna extract a lots of files.
Install LDR version with `Dism.exe /Online /Add-Package /PackagePath:"C:\...\update-bf.mum"`

My wintrust has now the version 6.1.7601.22948

**Comment by Liryna** [comment]
Fixed with https://github.com/dokan-dev/dokany/commit/9782a6491775ef3660a71f40f381d3f48e511f14

I tested without the KB, install failed as expected.
Installed theKB with GDR  6.1.7601.18741 or LDR 6.1.7601.22948, Dokan detected it correctly.
I just have not been able to install a version under 6.1.7601.22948 but at the view of the code, this should fail like under 6.1.7601.18741.
