### ISSUE TITLE
Cygwin question

### ISSUE THREAD

**Issue by DarylOliver** [dokan-dev/dokany#309]
More of a question than a bug I was wondering if dokany could be installed into Cobain somehow in order to use some of the programs that use it

**Comment by Liryna** [comment]
@DarylOliver What is Cobain? I know only Kurt :(

**Comment by Rondom** [comment]
I think Cygwin is meant 😂

**Comment by Liryna** [comment]
@Rondom :D but I like Kurt! 

Dokan fuse can be build for cygwin for offering fuse compatibility to other applications already use it on Linux or osx. 

There is going to be an official fuse package that will be created and available direct from cygwin package manager in the next week's. 

Does this answer your question?

**Comment by DarylOliver** [comment]
yes it does thank you I look forward to that package being released. 

also yeah I just realized my dang motorolla spell checker altered what I had said honestly android is glorious but at times a tad annoying.
