### ISSUE TITLE
mirror causes blue screen on 64-bit Windows7 on ctrl-c when trying to dismount

### ISSUE THREAD

**Issue by alexpmorris** [dokan-dev/dokany#31]
I recently published an interface to mount the ipfs distributed file system as a Windows drive via dokan:

https://github.com/alexpmorris/dipfs

Using the version of dokan 0.6.0 included in my repo, it works perfectly on 32-bit Windows, as well as 64-bit Windows 7.  

I wanted to see if your updated dokany version would work as well, and while it worked as expected throughout operation, when I hit ctrl-C to kill the program (which should also dismount the drive), the PC immediately blue-screened each time.  

At first I thought it was something I did wrong, but then I tried your version of mirror.exe, and the same bluescreen occurred when I tried to close down mirror.exe as well.  This happened with both dokany version 0.7.2 and 0.7.3-rc2.

If it would help, I can send a minidump.  But basically, it shows:

`dokan.sys+2a00  PAGE_FAULT_IN_NONPAGED_AREA`

**Comment by alexpmorris** [comment]
One other note, it sounds like this issue may be related to some of the other BSOD issues that have been described.  Whatever is causing it, though, seems to be some change that's taken place since version 0.6.0.

**Comment by marinkobabic** [comment]
Will be fixed

https://github.com/dokan-dev/dokany/issues/27#issuecomment-122595741

**Comment by Maxhy** [comment]
Yes it's the same issue. I'm closing this, please continue discussion on #27.
