### ISSUE TITLE
Add more documentation to mirror and fuse-mirror

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#310]
Since the mirror examples are one of the first interaction points for someone new to Dokan, the documentation could be improved. We do not have manpages under Windows, but we could make the `--help`-text less terse and more self-explanatory.

I will post some questions/comments to each option for inspiration.

    mirror.exe                             # document minimum req'd params
      /r RootDirectory (ex. /r c:\test)
      /l DriveLetter (ex. /l m)            # document mount as network share and to directory junction
      /t ThreadCount (ex. /t 5)            # what is the default?
      /d (enable debug output)             # where is it written to if not stderr (/s)?
      /s (use stderr for output)
      /n (use network drive)               # this needs explanation (maybe an example as well?) of what it means and what the implications are
      /m (use removable drive)             # what are the pros/cons? when would one us one or the other
      /w (write-protect drive)
      /o (use mount manager)               # this really needs explanation. I cannot find any documentation about it. Explain when one would use it
      /c (mount for current session only)
      /u UNC provider name
      /a Allocation unit size (ex. /a 512) # what is the default? Is it determined from the source directory?
      /k Sector size (ex. /k 512)          # dito
      /i (Timeout in Milliseconds ex. /i 30000) # mention what happens after the timeout (Error-code returned "not enough resources"). What is the default?

    # maybe add 3 examples (normal drive mount, directory-junction mount, network-mount)

**Comment by Liryna** [comment]
@Rondom :+1: real good idea and should be made before 1.0.0 release! 

 Also dokan-dotnet documentation has been really improved last week and there is a good part that could be reused in dokan.h to explain dokan operation and interface.

**Comment by Rondom** [comment]
A hint about how to unmount the volume is probably useful

**Comment by Liryna** [comment]
@Rondom does such output would be enough ? (first darft :smiley: )

```
mirror.exe [/l MountPoint]
  /r RootDirectory (ex. /r c:\test)     # Directory source to mirror
  /l MountPoint (ex. /l m)      # Mount point. Can be M:\ (drive letter) or empty NTFS folder C:\mount\dokan
  /t ThreadCount (ex. /t 5)     # Number of threads to be used internally by Dokan library.
                                # More thread will handle more events at the same time.
  /d (enable debug output)      # Enable debugger debug output
  /s (use stderr for output)    # Write debug output on stderr
  /n (use network drive)        # Show device as network device.
  /m (use removable drive)      # Show device as removable media.
  /w (write-protect drive)      # Read only filesystem.
  /o (use mount manager)        # Register device to Windows mount manager.
                                # This enables advanced Windows features like recycle bin and more...
  /c (mount for current session only)           # Device only visible for current user
  /u (UNC provider name ex. \localhost\myfs)    # UNC name used for network volume
  /a Allocation unit size (ex. /a 512)          # Allocation Unit Size of the volume. This will behave on the file size.
  /k Sector size (ex. /k 512)                   # Sector Size of the volume. This will behave on the file size.
  /i (Timeout in Milliseconds ex. /i 30000)     # Max timeout in milliseconds of each request before Dokan give up.

Examples:
        mirror.exe /r C:\Users /l m                     # Mirror C:\Users as RootDirectory into a drive of letter M:\.
        mirror.exe /r C:\Users /l C:\mount\dokan        # Mirror C:\Users as RootDirectory into NTFS folder C:\mount\dokan.
        mirror.exe /r C:\Users /l m /n /u \myfs\myfs1   # Mirror C:\Users as RootDirectory into a network drive M:\. with UNC \\myfs\myfs1

```

**Comment by Liryna** [comment]
@Rondom a quick review of this would be nice :)
If you agree with it will push my pending commit

**Comment by Rondom** [comment]
Sorry for the delay. All in all it looks good. Some comments below.

I am not very familiar with Windows-style command line interface conventions, but the hash-signs (´#`) look a bit odd to me next to the options. For the examples they are fine, because they act as a comment-sign to separate the command from explanation.

>  /t ThreadCount (ex. /t 5)     # Number of threads to be used internally by Dokan library.
>                                # More thread will handle more events at the same time.

"more thread**s**"

>  /d (enable debug output)      # Enable debugger debug output
  /s (use stderr for output)    # Write debug output on stderr

I suggest "Enable debug output to an attached debugger" and "Enable debug output to stderr"


>  /c (mount for current session only)           # Device only visible for current user

Is it really the current *user* or is it the current user session, i.e. when logging in multiple times with the same user only the session that runs Dokan will be able to use the FS?


>  /a Allocation unit size (ex. /a 512)          # Allocation Unit Size of the volume. This will behave on the file size.
  /k Sector size (ex. /k 512)                   # Sector Size of the volume. This will behave on the file size.

I do not get what the sentence "This will behave on the file size." is supposed to mean. Are you sure "behave" is the right word to use? Please elaborate.

>  /i (Timeout in Milliseconds ex. /i 30000)     # Max timeout in milliseconds of each request before Dokan give up.

I am not entirely sure whether it is "for" or "of each request". Maybe mention the error returned instead of the vague "give up"

>    Examples:
            mirror.exe /r C:\Users /l m                     # Mirror C:\Users as RootDirectory into a drive of letter M:\.
            mirror.exe /r C:\Users /l C:\mount\dokan        # Mirror C:\Users as RootDirectory into NTFS folder C:\mount\dokan.
            mirror.exe /r C:\Users /l m /n /u \myfs\myfs1   # Mirror C:\Users as RootDirectory into a network drive M:\. with UNC \\myfs\myfs1
        
maybe make the m an M: to make its purpose clearer (not saying that it is not clear already :-D)

> Unmount the drive with CTRL + C in the console.

... or alternatively via ´dokanctl /u MountPoint´

**Comment by Liryna** [comment]
Thank you for your feedback @Rondom !

Standard windows command output does not use `#`, they just add a big space like (dir /?):
```
Displays a list of files and subdirectories in a directory.

DIR [drive:][path][filename] [/A[[:]attributes]] [/B] [/C] [/D] [/L] [/N]
  [/O[[:]sortorder]] [/P] [/Q] [/R] [/S] [/T[[:]timefield]] [/W] [/X] [/4]

  [drive:][path][filename]
              Specifies drive, directory, and/or files to list.

  /A          Displays files with specified attributes.
  attributes   D  Directories                R  Read-only files
               H  Hidden files               A  Files ready for archiving
               S  System files               I  Not content indexed files
               L  Reparse Points             -  Prefix meaning not
  /B          Uses bare format (no heading information or summary).
  /C          Display the thousand separator in file sizes.  This is the
              default.  Use /-C to disable display of separator.
  /D          Same as wide but files are list sorted by column.
```
I will try to reproduce such style.

>Is it really the current user or is it the current user session, i.e. when logging in multiple times with the same user only the session that runs Dokan will be able to use the FS?

`device object name and a user-visible name for the device.`
https://msdn.microsoft.com/en-us/library/windows/hardware/ff549043(v=vs.85).aspx
Therefor I would say current user session (I didn't made more test when logging in multiple times with the same user)

>I am not entirely sure whether it is "for" or "of each request". Maybe mention the error returned instead of the vague "give up"
`/i (Timeout in Milliseconds ex. /i 30000) # Max timeout until a dokan operation is aborted and device unmount.`
Is it more clear ?
The case it is the FS take too much time (more than 30000 ms here) to answer, Dokan will automatically unmount it.

I will make other changes that your pointed also :+1: ty !

**Comment by Rondom** [comment]
Looks all good, though I would suggest "Timeout until a running operation is aborted and the device is unmounted" or "Timeout until an operation is aborted and the device is unmounted"

**Comment by Liryna** [comment]
Done with https://github.com/dokan-dev/dokany/commit/1007ad49378bdb029962fe7069ad823a5de23ac5

Thank you for your help @Rondom ! very appricate :)
