### ISSUE TITLE
Usability: dokanctl elevates permissions even when it is not needed

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#311]
1. Open a non-Administrator command prompt
2. Run a harmless command such as `dokanctl /?`

What happens: 
UAC-Prompt pops up, after acknowledging the prompt, a new cmd-window with the help-text appears and disappears immediately.

Expected:
dokanctl should only ask administrator rights when it is really needed. I am not sure which operations those are, but I would like to display the help-text at least. Showing the version, the list of mountpoints and possibly unmount the user's own volumes would be nice as well (maybe create a separate issue for that if it requires deeper changes).

**Comment by Liryna** [comment]
Hi @Rondom ,

I agree with you so I made the changes as requested:
https://github.com/dokan-dev/dokany/commit/008cf74e1bdf8494b0c0bb9ee72d32f409aefe64
Dokanctl no longer need admin permission for listing mount point, show usage and print version.

There is currently no possibility to check volume owners and therefore see if the user has the right to unmount them. `/u` will require admin rights for now.
This requires more changes. The easiest solution would be to retrieve SymbolicLink owner information (if that’s possible) and see if it matches the current user.

**Comment by Liryna** [comment]
Issue created https://github.com/dokan-dev/dokany/issues/312

@Rondom You can close this issue if my changes answer your request.
