### ISSUE TITLE
Dokan documentation style

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokany#313]
Hello,

I am looking for improving Dokan documentation, at least for the API at first.
I wanted to find something that could generate markdown documentation for github wiki but without success or with bad results.

I usually used Doxygen but I am wondering if some of you have preference on the documentation comments style and the tools that should be used for generating html, markdown or ... ?

**Comment by Rondom** [comment]
I think Doxygen works fine. I am not sure why you want to export to the wiki. I see the problem that people start to edit the Wiki instead of the source. Wouldn't a link be enough?
Why not have a separate repo "dokan-docs" with a gh-pages branch where we (or CI) push the documentation to?
If your concern is to have the same design for the Wiki and Doxygen output one could also push jekyll-generated HTML there.

**Comment by magol** [comment]
I've also done a little research on this. Unfortunately I have not had enough time to come up with a solution yet.

I hope I get some more time for this.

I have looked at [Sandcastle ](https://github.com/EWSoftware/SHFB) that previously was used by Microsoft to generate entire MSDN from a collection of XML files containing all content. These XML files together with the XML comments in the source code is compiled into HTML files, but there is also some support for markdown.

I'm not sure if this is the way to go, Doxygen also seems promising when I quickly read through what it can do.

**Comment by magol** [comment]
@Rondom I also have a concern that people start to edit the documentation in the wrong place.

One solution I've been thinking about is that maybe to write all documentation in Markdown, and use a build script to automatically update the Markdown files with the latest API syntax based on the source files. This requires that the Markdown files is written in a fixed format, or using custom tags.

I'm also thinking about a build script that can generate an XML file based on the Markdown files which can then be used together with the [`<include>`](https://msdn.microsoft.com/en-us/library/ms177232.aspx) tag. Then Visual Studio can access the documentation to present information about the features when implementing.

**Comment by Liryna** [comment]
@magol This would be complicate I think :D
Include tag would be less easy for developpers that want to read comments directly from the source code.

Like @Rondom proposed, we should probably generate documentation from doxygen comments and we or CI update the documentation automatically.

I will try to convert the current documentation to doxygen and see what is the results.

**Comment by magol** [comment]
@Liryna Yes, complicate it will be :-p
And, I do not like my idea either.
But when you brainstorming, you should not keep quiet about your ideas just because it is useless :-)

**Comment by magol** [comment]
I really like the idea to have the documentation in the source code and use Doxygen.

The only concern I see is to keep documentation between C ++ and C # in sync.
You could have a script that compares the generated documentation from the two code bases. But we might be able to keep it in fairly sync manually?

**Comment by Liryna** [comment]
We will have to keep it manually sync I think :cry: 
Files are too different to be able to important doc.

**Comment by Rondom** [comment]
This is a common problem among all language bindings wrapping a lower-level library. I think all you can do is some cross-referencing.
Also there might be subtle differences between the language implementations, for example with regards to parameter and return types. Though I am sure you could create some script that parses your source for references to the original documentation and then generate a new file with the documentation (if you will to spend the time for that, that is). Editing your existing higher-level source-code does not sound feasible.

**Comment by Liryna** [comment]
```
typedef struct _DOKAN_OPERATIONS {
  /**
  * \brief CreateFile Dokan API callback
  *
  * In case OPEN_ALWAYS & CREATE_ALWAYS are opening successfully a already
  * existing file, you have to SetLastError(ERROR_ALREADY_EXISTS)
  * If file is a directory, CreateFile is also called.
  * In this case, CreateFile should return STATUS_SUCCESS when that directory
  * can be opened.
  *
  * You should set TRUE on DokanFileInfo->IsDirectory when file is a directory.
  *
  * DokanFileInfo->Context can be use to store Data (like HANDLE)
  * that can be retrieved in all other request related to the Context
  *
  * See ZwCreateFile for more information about the parameters of this callback.
  * https://msdn.microsoft.com/en-us/library/windows/hardware/ff566424(v=vs.85).aspx
  *
  *
  * \param FileName File path requested by the Kernel on the FileSystem.
  * \param SecurityContext SecurityContext, see https://msdn.microsoft.com/en-us/library/windows/hardware/ff550613(v=vs.85).aspx
  * \param DesiredAccess Specifies an ACCESS_MASK value that determines the requested access to the object.
  * \param FileAttributes Specifies one or more FILE_ATTRIBUTE_XXX flags, which represent the file attributes to set if you create or overwrite a file.
  * \param ShareAccess Type of share access, which is specified as zero or any combination of FILE_SHARE_* flags.
  * \param CreateDisposition Specifies the action to perform if the file does or does not exist.
  * \param CreateOptions Specifies the options to apply when the driver creates or opens the file.
  * \param DokanFileInfo Information about the file or directory.
  * \return STATUS_SUCCESS on success or NTSTATUS appropriate to the request result.
  */
  NTSTATUS(DOKAN_CALLBACK *ZwCreateFile)
  (LPCWSTR FileName, PDOKAN_IO_SECURITY_CONTEXT SecurityContext,
   ACCESS_MASK DesiredAccess, ULONG FileAttributes, ULONG ShareAccess,
   ULONG CreateDisposition, ULONG CreateOptions,
   PDOKAN_FILE_INFO DokanFileInfo);
}
```

Doxygen does not even detect ZwCreateFile and all others callback that return NTSTATUS. If I change the return type to a know type like void/long, I work. Does anyone already faced such issue ?

**Comment by Rondom** [comment]
Maybe you need to teach Doxygen some defines? A quick look leads me to ´PREDEFINED´. To troubleshoot, maybe produce simple example-structs with two members or so, where you alternate syntax and used defines.

Btw: You should be able to document individual parameters right before or after the parameter (like in the current style)

**Comment by Liryna** [comment]
PREDEFINED DOKAN_CALLBACK= was the way to do it :+1: Thank you @Rondom 

He do not seems to like to document individual parameters right before or after the parameter. Only \param seems to work :(

**Comment by Liryna** [comment]
Alright I think I have import all documentation
https://github.com/dokan-dev/dokany/commit/de9a3fbd0f6d035c4488c3a9b67070838165eef4

The result can be checkout here: https://github.com/Liryna/dokany/tree/gh-pages/documentations/doc/html

I would like some feedback/pull request before adding gh-pages on this repository.

**Comment by Rondom** [comment]
For easier browsing 😉: https://liryna.github.io/dokany/documentations/doc/html/

My first impression is pretty good. 👍
I will not have time until the beginning of next week to give a thorough review, though. I will have some content-related input and some language fixes. But maybe a native speaker (do we have someone?) is better at commenting on the latter.

For production use, I would use a separate repository to avoid pushing lots of generated "stuff" into the main repository. I know it's a separate branch and bandwidth is cheap nowadays, but for me it feels cleaner to have this separate from another. The repository could have subdirectories with the generated info for each tag (and possibly also branch) of the main repo.

Publishing pull requests automatically is *probably* a bad idea from a security point of view. For PRs a ZIP-file with the docs as a build artifact is probably enough if security is a concern.

**Comment by Liryna** [comment]
Thank you @Rondom for the quick review and the link :smile: !

A native speaker would be very helpful yes !

I have updated oxygen style and fixed some form.

I agree about creating a git submodule that would be tagged on another repository that stores the documentation.

**Comment by magol** [comment]
Yes, it can be closed, it is now XML comments for most parts.
Then I hope we can use Doxygen to generate documentation from this, like in [#313](https://github.com/dokan-dev/dokany/issues/313)

**Comment by Rondom** [comment]
> I agree about creating a git submodule that would be tagged on another repository that stores the documentation.

I am not sure what problem you are trying to solve and how git submodules would exactly help. Please elaborate.

Thanks for spending the effort on this! The new bootstrap-style looks nice, it seems like we finally arrived in the 21st century :-D I am wondering if it would be "just including the CSS" to make the look consistent with https://dokan-dev.github.io. Then we could also link back between the docs and the webpage in the header for a "seamless" experience. We could also place the Wiki/Howto link more prominently in the header using a layout-XML file (´doxygen -l´).

Some ideas for later CI:
* we could link to the corresponding source on GitHub by setting an environment variable to the output of `git describe --always --dirty` to generate a link to the source the documentation was generated from
* we could set PROJECT_NUMBER using an environment variable as well

**Comment by Liryna** [comment]
>I am not sure what problem you are trying to solve and how git submodules would exactly help. Please elaborate.

`/documentations/doc` is where doxygen generate html. We can make this folder as submodule of dokan-doc repository branch gh-pages that will be checkout as the same TAG (version) of dokan. Like that we would have the documentation generated on another repository and that can be retrieved later without needing to generate it.
Is it more clear :D ?

> I am wondering if it would be "just including the CSS" to make the look consistent with https://dokan-dev.github.io
> We could also place the Wiki/Howto link more prominently in the header using a layout-XML file (´doxygen -l´).

If someone has the skills for it :+1: that's something I will take too much time to do :smile: 

We can make appveyor push documentation automatically on success to the dokan-doc repository branch gh-pages.
Like that we would have documentation always update from the master.
See https://github.com/mnjordan/SpectreCore/blob/2b5671a32276a3cb46c1250cc7317a1a5a30807e/appveyor.yml

**Comment by Liryna** [comment]
Dokan documentation is now pushed auto by appveyor https://github.com/dokan-dev/dokany/commit/b797eadd7fbf4bd274ec8ac662e8e70366cb7971
The documentation is in this repository https://github.com/Liryna/dokany-doc (it gonna be move dokan-dev/ next week)
And can be read from here https://liryna.github.io/dokany-doc/html/

I will add the link to github wiki when the repository will be moved.

For information, at the build doxygen show what is currently not documented https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.0-700/job/9hsaoo84af2di3vd#L5169

**Comment by Liryna** [comment]
All missing doxygen documentation warnings has been fixed.
https://github.com/dokan-dev/dokany/commit/b3b0ef2dffad298fe4df26bece0ffa564bc6671b

If some of you have the time to review at least the most important like DOKAN_OPERATIONS and DOKAN_OPTIONS it would be nice :heart:

**Comment by Liryna** [comment]
Documentation moved to https://dokan-dev.github.io/dokany-doc/html/
Also added Dokan API documentation from WIKI directly on the mainpage

**Comment by Liryna** [comment]
I think this can be closed since the documentation has been completed (at least the dokan API for devs).
