### ISSUE TITLE
Add a CHANGELOG.md to the root.

### ISSUE THREAD

**Issue by magol** [dokan-dev/dokany#319]
Change logs are now both in each [release](https://github.com/dokan-dev/dokany/releases) and in [dokan_wix/version.txt](https://github.com/dokan-dev/dokany/blob/master/dokan_wix/version.txt)

I think it is better if it is rewritten according to the "standard" available. See [Keep a CHANGELOG](http://keepachangelog.com/en/0.3.0/).

This does not prevent to have change logs in the releases and in **version.txt**, but it will be easier to manage when it follow a standard.

I could create this file just like I did for [ Dokan-dotnet](https://github.com/dokan-dev/dokan-dotnet/blob/master/CHANGELOG.md), but I feel I have to little knowledge in Dokany to do a good job.

**Comment by Liryna** [comment]
Hi @magol ,

Does this would make it: https://gist.github.com/Liryna/31d723354f0bd7bbad9949ab5409aaac ?

**Comment by magol** [comment]
Just what I mean, well done :-)

**Comment 1**
The head should be changed to following according to recent changes in [Keep a CHANGELOG](https://github.com/olivierlacan/keep-a-changelog/edit/master/CHANGELOG.md):

> All notable changes to this project will be documented in this file.
> 
> **The format is based on [Keep a Changelog](http://keepachangelog.com/) and** this project adheres to [Semantic Versioning](http://semver.org/).

**Comment 2**
I think it would be good if you group the changes based on which project they belong to. And that it is clearly and consistently marked what project each change belonging to. You use for example `FUSE - Export utils fonctions`, do it consistently for all.

**Comment 3**
FSCTL_REQUEST_OPLOCK #97
are not particularly informative. Please, clarify what it is that you do not have to follow the link to see what it is.

**Comment 4**
For version 0.6.0, you can have a link to [web.archive.org/web/20150419082954/http://dokan-dev.net/en]( http://web.archive.org/web/20150419082954/http://dokan-dev.net/en/) and perhaps [ode.google.com/archive/p/dokan](https://code.google.com/archive/p/dokan/). I do not know if it's relevant, but it's still a part of history.

**Comment by Liryna** [comment]
Changelog added with your changes 
https://github.com/dokan-dev/dokany/commit/c5ec2d7d609dcdb5addbd452c01cad3e0ed199c3

Thank you again @magol !

**Comment by Liryna** [comment]
Changelog added to all stable release
