### ISSUE TITLE
MirrorCreateFile fails with error number 87

### ISSUE THREAD

**Issue by JxLiu2016** [dokan-dev/dokany#324]
# Environment
 * Windows version: Win7 SP1
 * Processor architecture: x64
 * Dokany version: 1.0.0 (Driver Ver. 0x190)
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [ X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ X] I can always reproduce the issue with the provided description below.
  - [ X] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description
I use mirror sample without any modification.
Then I use command "mirror \d \s \r M:\test2 \l N"
Yet some file can be created while some fail with error number 87.

# Logs

###Create 0059
CreateFile : M:\test2\7A756AC7-16A9-4E2D-A607-EF25B9222EA7\cache.xml
xxxxx M:\test2\7A756AC7-16A9-4E2D-A607-EF25B9222EA7\cache.xml
  AccountName: test, DomainName: test-pc
	ShareMode = 0x3
	FILE_SHARE_READ
	FILE_SHARE_WRITE
	AccessMode = 0x12019f
	FILE_READ_DATA
	FILE_READ_ATTRIBUTES
	FILE_READ_EA
	READ_CONTROL
	FILE_WRITE_DATA
	FILE_WRITE_ATTRIBUTES
	FILE_WRITE_EA
	FILE_APPEND_DATA
	SYNCHRONIZE
	STANDARD_RIGHTS_READ
	STANDARD_RIGHTS_WRITE
	STANDARD_RIGHTS_EXECUTE
	FlagsAndAttributes = 0x20000000
	FILE_FLAG_NO_BUFFERING
	CREATE_ALWAYS
	error code = 87

CreateFile status = c000000d - lastError = 87

###Create 0040
CreateFile : M:\test2\7A756AC7-16A9-4E2D-A607-EF25B9222EA7\config.xml
xxxxx M:\test2\7A756AC7-16A9-4E2D-A607-EF25B9222EA7\config.xml
  AccountName: test, DomainName: test-pc
	ShareMode = 0x1
	FILE_SHARE_READ
	AccessMode = 0x120196
	FILE_READ_ATTRIBUTES
	READ_CONTROL
	FILE_WRITE_DATA
	FILE_WRITE_ATTRIBUTES
	FILE_WRITE_EA
	FILE_APPEND_DATA
	SYNCHRONIZE
	STANDARD_RIGHTS_READ
	STANDARD_RIGHTS_WRITE
	STANDARD_RIGHTS_EXECUTE
	FlagsAndAttributes = 0x80
	FILE_ATTRIBUTE_NORMAL
	CREATE_ALWAYS

CreateFile status = 0 - lastError = 0

**Comment by Liryna** [comment]
Hi @JxLiu2016 

This is the same issue as https://github.com/dokan-dev/dokany/issues/197

If you have any idea how this could be improve :cry:

**Comment by JxLiu2016** [comment]
Hi @Liryna 
Thank you very much for your reply. :)
I will see what I can do.

Thanks

**Comment by Liryna** [comment]
Thank you @JxLiu2016 this would be very appricate !

I just close the ticket to keep the discution in the origin issue.
