### ISSUE TITLE
version.txt and changelog.md duplication

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#334]
Both `version.txt` and `changelog.md` contain a changelog.
The difference between the two is the format and that `changelog.md` does not have individual entries for the RCs.

`version.txt` is currently used for updating the version-information in several files using SetAssemblyVersion

**Comment by Liryna** [comment]
@Rondom version.txt should be replaced by the md but it is used by the tools to detect what version to build. It mean that the tools does also has to be changed

**Comment by Rondom** [comment]
That's what I wanted to imply by the last sentence ;-)

**Comment by Liryna** [comment]
This is not very "standard" from http://keepachangelog.com/en/0.3.0/ but can we just add the version to unreleased section and use it in SetAssemblyVersion ?
https://github.com/dokan-dev/dokany/blob/master/CHANGELOG.md#unreleased

with this we can remove the version.txt

ping @magol

**Comment by magol** [comment]
Well,  it is just a recommendation.  So I don't see any problem to add the version number to the Unreleased section. :)

**Comment by Liryna** [comment]
ok ! version.txt will be removed so and SetAssemblyVersion  changed to use the changelog !

**Comment by Liryna** [comment]
Done with https://github.com/dokan-dev/dokany/commit/a0202c23dc15bd1ae959e5648c64057c62f3d803

**Comment by Rondom** [comment]
Have you tested this on AppVeyor?

**Comment by Liryna** [comment]
I did the test locally and file were correctly updated.

**Comment by Liryna** [comment]
@Rondom quick fix to come :+1:
