### ISSUE TITLE
Cygwin-cmake is broken on Appveyor-CI

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#335]
Currently we always install the latest version of cmake for Cygwin when doing CI builds on Appveyor.
For some reason cmake is broken on Appveyor.

I logged in via RDP to the build worker and found out that the cmake command will just silently exit, no matter what parameters you provide.
Reinstalling cmake using the Cygwin installer seems to fix the problem as far as I can see.

Does anyone have any ideas what is wrong or want to troubleshoot themselves?

**Comment by Liryna** [comment]
RDP on appveyor :open_mouth: ?

I already seen that couple of time cygwin packages does not work for a reason after an update.
I just tested on my env and it no longer work...
Usually I wait some days that it come back :+1: but here with the release of next week it gonna be an issue :cry:

**Comment by Liryna** [comment]
https://www.cygwin.com/ml/cygwin/2016-09/msg00167.html
cmake has been update the 12, it is porbably linked to ?

**Comment by Liryna** [comment]
I don't know how to answer to his annonce ><
But we should probably report it since he say he does not make release offen :D

**Comment by Rondom** [comment]
Have you tried reinstalling cmake using the Cygwin installer UI?
I cannot reproduce it on my machine. On the Appveyor Build-Worker, reinstalling fixed the issue. I used the old installer in C:\cygwin instead of the new one that the CI-script downloads.
Maybe the bug only occurs with the new cygwin-installer version?

**Comment by Rondom** [comment]
Regarding RDP in appveyor:

      init:
       - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      on_finish:
       - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

RDP-credentials are printed into the log (so use with your private repo). The last two lines will make the build block until you delete a file from the Desktop.

**Comment by Liryna** [comment]
@Rondom I have request to réinstall the package from the UI and it work !

https://cygwin.com/faq/faq.html#faq.setup.cli
it seems like there is not such option to do it by cmd line.
we probably need to remove the package and reinstall it

**Comment by Rondom** [comment]
`/var/log/setup.log` and `/var/log/setup.log.full` has a log of the setup. I do not notice anything unusual. Maybe you can have a look as well?

**Comment by Liryna** [comment]
Just checked and there is only informations of the succesfull reinstall :disappointed:

**Comment by Rondom** [comment]
Double-clicking cmake.exe yields the following error-message: 

    ---------------------------
    cmake.exe - Entry Point Not Found
    ---------------------------
    The procedure entry point __locale_ctype_ptr could not be located in the dynamic link library C:\cygwin\bin\cmake.exe.

**Comment by Liryna** [comment]
ah ! :smiley: this would be helpful for the cmake maintainer !

**Comment by Rondom** [comment]
As a solution, we can point our CI-script to a specific point in time using: http://www.fruitbat.org/Cygwin/#cygwintimemachine (Let's hope that mirror is stable)

Still we should keep this open and report this following the instructions at https://cygwin.com/problems.html. @Liryna, can you reliably reproduce it?

**Comment by Liryna** [comment]
@Rondom No longer can reproduce it on my env :'( 
only coming from and old version seems to create this behaviour like appveyor.

I will try to report to the maintainer but now idea how to answer to his topic :'(

**Comment by Rondom** [comment]
Wait a bit

**Comment by Rondom** [comment]
Problem is that the new cmake-package's dependencies are not up to date. It seems like the cmake-binary is linked against newer libraries, but the dependencies still say "old version or later".
So there is indeed a bug in the cmake-package.

We can work around this by upgrading all packages. This fixes the issue but might increase build-time a bit. PR is coming ;-)

**Comment by Rondom** [comment]
For reference: There is no bug in the cmake-packaging. Cygwin seems to simply have no concept of versioned dependencies whatsoever. :open_mouth:  :fearful:

So, whenever installing a new package without having upgraded the whole installation before it is pure coincidence that things are working!

**Comment by Liryna** [comment]
😨 Wow that scary but good to know !
