### ISSUE TITLE
CI-built DLL versions now have two zeros more at the end

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#339]
Recent CI-built DLLs now have two zeros more at the end (see below).
The installer (and its filename) still have the original scheme without the missing zeros. Also I see that at least the Win7 Explorer does not seem to be able to cope with such a high product version (file version is fine). I faintly remember reading an article on Old New Thing about why that is.

We should stick to one version scheme for both installer and DLLs.

    PS C:\> (Get-Item 'C:\Program Files\Dokan\Dokan Library-1.0.0\*.dll').VersionInfo

    ProductVersion   FileVersion      FileName
    --------------   -----------      --------
    1.0.0.474700     1.0.0.474700     C:\Program Files\Dokan\Dokan Library-1.0.0\cygdokanfuse1.dll
    1.0.0.474700     1.0.0.474700     C:\Program Files\Dokan\Dokan Library-1.0.0\dokan1.dll
    1.0.0.474700     1.0.0.474700     C:\Program Files\Dokan\Dokan Library-1.0.0\dokanfuse1.dll
    1.0.0.474700     1.0.0.474700     C:\Program Files\Dokan\Dokan Library-1.0.0\dokannp1.dll
    1.0.0.474700     1.0.0.474700     C:\Program Files\Dokan\Dokan Library-1.0.0\libdokanfuse1.dll

    PS C:\> (Get-Item 'C:\Dokan\*.dll').VersionInfo

    ProductVersion   FileVersion      FileName
    --------------   -----------      --------
                                      C:\Dokan\cygdokanfuse1.dll
    1.0.0.3628       1.0.0.3628       C:\Dokan\dokan1.dll
    1.0.0.3628       1.0.0.3628       C:\Dokan\dokanfuse1.dll
    1.0.0.3628       1.0.0.3628       C:\Dokan\dokannp1.dll
                                      C:\Dokan\libdokanfuse1.dll

**Comment by js69** [comment]
What result do you get with:
(Get-Item 'C:\Program Files\Dokan\Dokan Library-1.0.0\*.dll').FileVersion

a.b.c.d versions for Windows are normally limited at 255.255.65535.65535

**Comment by Liryna** [comment]
@js69 is it not the same as frist command that gave @Rondom ? (it show FileVersion)

**Comment by Rondom** [comment]
FileVersion does not work on my Win2k8r2, but I guess it is the same as the FileVersion column?

![dokandll-version](https://cloud.githubusercontent.com/assets/125913/18552129/7bba74e6-7b5b-11e6-9803-4b9802057e9f.png)

**Comment by js69** [comment]
FileVersion and ProductVersion are different and what is actually returned in VersionInfo seems quite obscure.

http://stackoverflow.com/questions/752162/whats-the-difference-between-a-dlls-fileversion-and-productversion
https://social.msdn.microsoft.com/Forums/vstudio/en-US/698cc95c-0524-4940-bc55-08602b8ea90f/difference-between-assemblyversion-and-fileversion-and-productversion-in-net-versioning-philosophy?forum=netfxbcl

Good practice in my experience is to keep both numbers identical.

**Comment by Rondom** [comment]
Does anyone have an idea what change could have caused this?

**Comment by Liryna** [comment]
No idea, but https://github.com/dokan-dev/dokany/blob/master/appveyor.yml#L133-L140 this part of the code generate the version.

**Comment by Liryna** [comment]
Fixed with https://github.com/dokan-dev/dokany/commit/da39829ddccbf68e7d4af3966edb8b0c91afa25f

Regex :heart: :
