### ISSUE TITLE
VLC doesn't play video with Dokan

### ISSUE THREAD

**Issue by shlatchz** [dokan-dev/dokany#34]
See the issue opened in [stackoverflow](http://stackoverflow.com/questions/31590131/vlc-doesnt-play-video-with-dokan).

Thanks.

**Comment by Liryna** [comment]
`filesystem error: read error: Invalid argument` I guess you have a read issue.

**Comment by shlatchz** [comment]
[CreateFile()] \[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 25 [720p].mkv, Access: Read, Share: ReadWrite, Mode: Open, Options: None, ID: 459
    [GetFileInformation()] \[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 25 [720p].mkv, ID: 459
    [ReadFile()] \[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 25 [720p].mkv, Buffer Length: 1024, Offset 0, ID: 459
    [GetFileInformation()] \[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 25 [720p].mkv, ID: 459
    [ReadFile()] \[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 25 [720p].mkv, Buffer Length: 512, Offset 1024, ID: 459
    [GetFileInformation()] \[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 25 [720p].mkv, ID: 459
    [ReadFile()] \[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 25 [720p].mkv, Buffer Length: 512, Offset 4151, ID: 459
    [GetFileInformation()] \[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 25 [720p].mkv, ID: 459
    [ReadFile()] \[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 25 [720p].mkv, Buffer Length: 512, Offset 338605090, ID: 459
    [GetFileInformation()] \[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 25 [720p].mkv, ID: 459
    [Cleanup()] \[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 25 [720p].mkv, ID: 459
    [CloseFile()] \[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 25 [720p].mkv, ID: 459

OS calls create file, that calls get file information and returns 0.
After that, OS calls get file information and returns 0;
After that, OS calls read file and receives the requested buffer and so on
until the cleanup and close functions.

I wan't to stress that the video file DOES play with Media Player Classic.
It just won't play with VLC.

Thanks!

**Comment by Liryna** [comment]
Calls does not seems to be specials, are you sure of the data returned by your implementation ?

**Comment by shlatchz** [comment]
Yes. As I said, it does work with a different player. Just not with VLC.

**Comment by Liryna** [comment]
Still looks like a read error.
It can happen that some softwares ask to read a offset/size but expect to read a different size.
This could be the case.

I do not think it is a dokan issue and I do not have your code, so I cannot help you more :(

**Comment by shlatchz** [comment]
The problem is that there is no error \ exception in the code. The OS doesn't request an offset that exceeds the file's size or receives something smaller than the size of readBytes..

The question is, whether there is some metadata that the OS requests but Dokan doesn't supply to the OS? Can there be a callback that is needed in this situation, but Dokan doesn't implement at all?

**Comment by Liryna** [comment]
Nop,
Metadata are gotten by the read function.
As an example, when you see the preview of a picture or the icon of a exe, it is explorer.exe that open every files of the directory and extract informations with read.

**Comment by shlatchz** [comment]
Yeah, I know that the explorer process requests FindFiles for the directory, and then GetFileInformation for each file & also ReadFile to get the thumbnails.. and it works.
Only VLC fails to work for some reason :( :( :(

Also, I just noticed that when you try to customize a folder and change it from "General items" to "Pictures", explorer.exe crashes.
Does it happen to you guys?

**Comment by suy** [comment]
On my filesystem, I noticed that VLC choked and failed to play the file properly if the contents are not given to it fast enough. Is that your case? In my app, I fetch contents from a remote site, but cache them. After the contents are cached, VLC is happy (from the network is too slow in some videos at least). If your filesystem can't be very fast, try with a video with a very low resolution and bitrate, so it needs to read as little as possible. Just to confirm.

**Comment by shlatchz** [comment]
Hi!
You might be right :)
For small files, at first, VLC prints the same error.
After I hit play, VLC prints the error several times and then starts the movie!
It might be a latency problem..
I also use a caching mechanism (Redis), but with big video files, I guess it's still not enough. 
What kind of caching do you use?

Thanks!

**Comment by suy** [comment]
Well, my filesystem "just" maps remote files locally, but when it is downloaded, it is saved in a cache, so next access to the same file is much faster. If you were doing some kind of filesystem where you (for example) show the contents of compressed archives as a tree, then you probably don't have caching as an option, because it could duplicate a lot of data.

**Comment by Liryna** [comment]
@shlatchz 
```
Also, I just noticed that when you try to customize a folder and change it from "General items" to "Pictures", explorer.exe crashes.
Does it happen to you guys?
```
I have made a test with last Dokan/Mirror release on Win8.1 and It worked :(

There is a big chance that @suy is right :smiley: !
We probably should add good practice to the documentation to explain such case of failure.
Suy, did you faced other case like this ?

**Comment by shlatchz** [comment]
@Liryna , I'm using Win7. 
@suy, even when I map a local file to the ReadFile request, instead of fetching it from a remote server,
VLC won't play it.

    using (BinaryReader reader = new BinaryReader(new FileStream(@"E:\Downloads\[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 25 [720p].mkv", FileMode.Open)))
    {
    	reader.BaseStream.Seek(offset, SeekOrigin.Begin);
    	readBytes = (uint)reader.Read(buffer, 0, buffer.Length);
    	if (readBytes == 0)
    	{
    		return DokanNet.DokanError;
    	}
    	reader.Close();
    	reader.Dispose();
    }

**Comment by Liryna** [comment]
Mapping at every call of ReadFile does not make it faster, it even make it slower.
You should map the file in CreateFile, keep it somewhere and clean it on close.

**Comment by shlatchz** [comment]
I tried that as well:

    BinaryReader reader = new BinaryReader(new FileStream(@"E:\Downloads\[HorribleSubs] Fate Stay Night - Unlimited Blade Works - 25 [720p].mkv", FileMode.Open));
	public int ReadFile(string filePath, byte[] buffer, ref uint readBytes, long offset, DokanFileInfo info)
	{
	    lock (reader)
		{
			reader.BaseStream.Seek(offset, SeekOrigin.Begin);
			readBytes = (uint)reader.Read(buffer, 0, buffer.Length);
			if (readBytes == 0)
			{
				return DokanNet.DokanError;
			}
		}
		return DokanNet.DokanSuccess;
	}
	
and it didn't help :(

**Comment by marinkobabic** [comment]
@shlatchz

Please try using the mirror.exe and your video file. If you still fail please provide the video file and tell us which version of vlc player you use.

If you don't fail using the mirror,  you can investigate what you are doing different.

**Comment by shlatchz** [comment]
I just noticed that the DokanNet repository was updated.
I will try using the newer version and will keep you posted!

**Comment by shlatchz** [comment]
Everything works with the new version of DokanNet! Hurray!

**Comment by bryanbabel** [comment]
I'm using Dokan 0.7.3 on Windows 10, and I'm having the same issue. I can play a song using Windows Media Player but VLC gives an error message. I can view a photo using Paint and Windows Photo Viewer but VLC gives an error message. Please give me some insights, thanks a lot

**Comment by bryanbabel** [comment]
![vlc_zel](https://cloud.githubusercontent.com/assets/2852456/9023395/f7adf012-38a1-11e5-8012-315d94a1fd70.png)

**Comment by bryanbabel** [comment]
But plays with windows media player. This is with the new Dokan 0.7.3 RC4, on Windows 10. But it plays on VLC on windows 8.1. What  could be the issue? Thanks in advance

![vlc_zel2](https://cloud.githubusercontent.com/assets/2852456/9023407/7ed58744-38a2-11e5-9935-986fd6522df8.png)

**Comment by Liryna** [comment]
VLC logs should help you to find your problem.

**Comment by bryanbabel** [comment]
I have just tried it with mirror, it also fails with VLC, but succeeds with windows media player

**Comment by bryanbabel** [comment]
@Liryna  I think there's something new in Windows 10 that you need to investigate. Because even mirror has the same issue. At your own time, test mirror on Windows and try playing media

**Comment by Liryna** [comment]
@bryanbabel you need to investigate on this discussion and special about how shlatchz have resolved it.
Mirror have no issue, it purpose is to stay clean and simple. We will add not advanced reading feature in it. But I agree that making a new sample for such case could be helpful.

**Comment by Rambalac** [comment]
Overlapped read problem?

**Comment by sqc1999** [comment]
I encountered the problem too, with the latest Dokany and DokanNet. Any solutions?

**Comment by dangibson** [comment]
I had the same problem this week (I was using 1.4.0.1000 and 1.5.1.1000 on Windows 7). An mkv file would sometimes play in vlc, but usually failed (other types like mp4 played ok, but not an mkv file). sysinternals Process Monitor showed INVALID_PARAMETER on ReadFile.

The mirror sample worked.

In the mirror sample, CreateFile returns NotADirectory if you try to open a file as a directory, but my code did not. Adding this check to my code seems to have resolved the problem.

**Comment by qiandi** [comment]
I had the same problem this week
