### ISSUE TITLE
Using python to make a file system on windows with this?

### ISSUE THREAD

**Issue by chibill** [dokan-dev/dokany#351]
Any idea how I would do this fusepy (Which the wiki says to use) does not work so any idea?

**Comment by chibill** [comment]
Okay  I also figured out that on my windows 10 install it installs as dokan1.dll in system32 and also SysWOW64 odd...  So I might be able to get fusepy to work.

**Comment by Liryna** [comment]
Hi @chibill ,

There is a pull request currently made on pyfilesystem to add dokan 1.0.0 support. https://github.com/PyFilesystem/pyfilesystem/pull/258

It is currently working on my side 👍 and waiting for the merge

**Comment by chibill** [comment]
Okay. I guess that can work.
