### ISSUE TITLE
Step By Step Guide In Windows 10 How To Use Please

### ISSUE THREAD

**Issue by arfaatc** [dokan-dev/dokany#358]
Hey, I am so sorry i dont know i should post it or not but i really need help i want to set this up but i am a complete noob in developing world please can u help me step by step how to use it please ?
I am having WINDOWS 10

**Comment by Liryna** [comment]
@arfaatc the library is targeting developpers.
Like I already told you by mail, you need ton contact directly https://github.com/Rambalac/ACDDokanNet
for mounting amazone driver on windows.
