### ISSUE TITLE
Dokan causes BSOD on filesystem mount on Windows 10 build 14936

### ISSUE THREAD

**Issue by cerebrate** [dokan-dev/dokany#359]
# Environment
 * Windows version: 10 (Insider build 14936)
 * Processor architecture: x64
 * Dokany version: 1.0.0 release (latest)
 * Library type (Dokany/FUSE):  Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description

System blue-screens with SYSTEM_SERVICE_EXCEPTION as soon as any user-mode filesystem (tested with keybase, mirror, own test code) attempts to mount.

# Logs

Memory dump attached here:

https://1drv.ms/u/s!AqrcZdowvFOLqLsbQypTta7rom317w

**Comment by Liryna** [comment]
Hi @cerebrate ,

Thank you for the report !

I cannot use the dump unfortunately :'( is not me who built the version (need the dbg from the build).

This is a very interesting case to see what Microsoft changed! I will follow the KeyBase discussion 👍

**Comment by cerebrate** [comment]
@Liryna Is there a way I can get you a dump that you can use? (If it's just a matter of using the debug version of Dokan as per the "How to Debug" wiki page, I can do that easily enough.)

**Comment by Liryna** [comment]
@cerebrate try to install https://github.com/dokan-dev/dokany/releases/download/v1.0.0/DokanSetup_redist-1.0.0.5000.exe (enable optino install dev tools). Run the mirror in dokan sample folder.
`mirror.exe /r C:\Users /l m`

Browse the M:\ 👍

**Comment by CrosseyeJack** [comment]
I tried to follow the instrustions on the wiki and installed your advice to install redist which dev tools but that didn't give me mirror.exe to run so I downloaded it from the release zip. Ran dbgview, told it to log to a file, ran the command and it BSOD'ed and wrote nothing to the log file. tried to capture stdout&stderr but again no output was written before BSOD.

If I'm doing something wrong please let me know and i'll try again.

**Comment by Liryna** [comment]
@CrosseyeJack the mirror is installed when you click on option button in the installer and check "install dev tools" (something like that :smiley: ). But download zip also work :+1: 
DbgView is only working if you use Dbg installer https://github.com/dokan-dev/dokany/releases/download/v1.0.0/DokanSetupDbg_redist-1.0.0.5000.exe (it has debug output enabled).

For now, just try the WinDbg analyze before going any further :+1:

**Comment by CrosseyeJack** [comment]
POsted in the other issue, but might as well has it here too :-p
[windbg.txt](https://github.com/dokan-dev/dokany/files/507068/windbg.txt)

**Comment by marinkobabic** [comment]
@CrosseyeJack

Can you give me more details what kind of software uses this filter cldflt!HsmiCfgOpenSettingFile?

**Comment by CrosseyeJack** [comment]
@marinkobabic Not off the top of my head. The BSOD only happens when I have keybase run on start up so I would say thats the only software I have that uses it knowingly. With Windows 10 (not sure of the version) you can no uninstall onedrive (Searching for OneDrive in start, right clicking and selecting uninstall brings up the classic uninstall option that doesn't list OneDrive and that is the only thing I can think that is running on my system that could use cldflt.sys) If I disable keybase (which is the only think that uses dokan on my machine) from start up I don't have any BSOD's. If I use mirror.exe from dokan without Keybase installed I still get the same BSOD when running the command that uses mirror.exe.

**Comment by zanderz** [comment]
I managed to get this preview version and make a few dumps in a vm after downloading the above linked build. Let me know if there's anything else I can do. This is a pretty bare installation, no other third party products.

[dumps_2016.10.04.zip](https://github.com/dokan-dev/dokany/files/509535/dumps_2016.10.04.zip)

**Comment by marinkobabic** [comment]
Please can you post here the !analyze -v output This makes it simpler to me to analyze the problem before doing any debugging. Thanks a lot.

**Comment by zanderz** [comment]
[100416-7000-01.txt](https://github.com/dokan-dev/dokany/files/509628/100416-7000-01.txt)
[100416-8281-01.txt](https://github.com/dokan-dev/dokany/files/509627/100416-8281-01.txt)
[100416-9640-01.txt](https://github.com/dokan-dev/dokany/files/509629/100416-9640-01.txt)

**Comment by cerebrate** [comment]
@Liryna I have now installed that version and tried running the mirror sample with that command line. (Didn't get quite to browsing M:, though, since it BSODed as soon as I ran it.) Dump file for that run, MEMORY-2.7z, is here:

https://1drv.ms/u/s!AqrcZdowvFOLqLsghTyFh4vA_puEJw

)

**Comment by marinkobabic** [comment]
So please test the pull request above. The issue comed from the request of "\system volume information\Cloud Files" which was responded with SUCCESS. The os wanted to read some files there but the used handle was invalid which caused the BSOD. To fix the issue the first request will not get a handle resp. the driver responds with a not Not SUCCESS message. 

In generally the proposed solution is still a hack but required using the actual architecture. Normally all the requests should be handled by usermode application. At this point it's actually not possible to forward the requested to usermode application because the original request camed from there (add interrupts to pool) but a driver filter added some requests more. So driver had no usermode interrupt to be able to handle the driver filter requests by them.

**Comment by Liryna** [comment]
Hi @marinkobabic ,

Thank you for the PR and the fix ! I see that we are still in the case where Dokan is contacted before the user land is available 😢 ...

>the original request camed from there (add interrupts to pool) but a driver filter added some requests more. So driver had no usermode interrupt to be able to handle the driver filter requests by them.

Sorry I am maybe lacking of some knowledge, can you describe a little in another words ❤️  ?

**Comment by marinkobabic** [comment]
So let's try. 

In Usermode we are creating the device here

https://github.com/dokan-dev/dokany/blob/master/dokan/dokan.c#L218

This works fine. Then we are starting DokanLoop threads

https://github.com/dokan-dev/dokany/blob/master/dokan/dokan.c#L275

**This threads are doing CreateFile to the new created device**
https://github.com/dokan-dev/dokany/blob/master/dokan/dokan.c#L364

 and send the DeviceIoControl IOCTL_EVENT_WAIT 

https://github.com/dokan-dev/dokany/blob/master/dokan/dokan.c#L387

This Irp will be added to the drivers list of workers. This are the usermode workes, which are used to process the requests.

When the driver has something to do it will respond the IOCTL_EVENT_WAIT and the usermode will process the respond from the driver

https://github.com/dokan-dev/dokany/blob/master/dokan/dokan.c#L422

after the job is processed it will do SendEventInformation IOCTL_EVENT_INFO to the driver

https://github.com/dokan-dev/dokany/blob/master/dokan/dokan.c#L491

and then the thread will do again CreateFile and IOCTL_EVENT_WAIT

https://github.com/dokan-dev/dokany/blob/master/dokan/dokan.c#L364

So this should be clear. The way the drivers are designed is in stacks. When we have created the totally new device, we are going to open the new device using CreateFile (bold text above). Now the stack is used for our CreateFile. Inside of the stack we have as first all the Driver Filters and then is the request passed down to the driver it self. If in our example we are doing the CreateFile and the IOCTL_EVENT_WAIT the first time, the filters can block the call and send as first some other request to the driver before the real request is passed down. This is what happens using antivirus software or in this case the Cloud Files filter. If the filters do that, the driver has no usermode workers in this list

https://github.com/dokan-dev/dokany/blob/da39829ddccbf68e7d4af3966edb8b0c91afa25f/sys/event.c#L216

So, it can't pass the requests to the usermode application. If the driver responds using STATUS_PENDING the whole stuff will hang.

**Comment by Liryna** [comment]
Han !!! Perfect explanation @marinkobabic big thanks !
I perfectly understand it now ❤️ 

It seems to be a case to case behavior and your fix seems to be the way it has to be done.
I will just test a thing on my side and merge your pull request and let @cerebrate make a test with a snapshot build 👍 

thank you again @marinkobabic for taking the time to look at the issue and making the explanation clear !

**Comment by Liryna** [comment]
@cerebrate @CrosseyeJack @zanderz 
@marinkobabic Fix has been merged 👍 A snapshot build can be download here https://ci.appveyor.com/api/buildjobs/vyak0xn91hnk5eb3/artifacts/DokanSetup-1.0.1.0790.exe
It is selfsigned see https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot if you wanna test it.

**Comment by cerebrate** [comment]
@Liryna Just installed it now; works perfectly, both with the mirror sample and with Keybase. Thanks muchly!

**Comment by Liryna** [comment]
Ah perfect ! Thanks for the quick feedback @cerebrate !

All the 🏆 goes to @marinkobabic 😉

**Comment by marinkobabic** [comment]
Not all. It's really amazing how much time you invest to support the community here. Thanks a lot @Liryna You are doing a great job!!!
