### ISSUE TITLE
encfs4win - (encfs.cpp:141) error caught in getattr

### ISSUE THREAD

**Issue by Owyn** [dokan-dev/dokany#36]
Can't get encfs4win ( http://members.ferrara.linux.it/freddy77/encfs.html ) to work with dokany latest RC, with administrator user it works almost fine but with an usual user it outputs `(encfs.cpp:141) error caught in getattr` error for every directory listing or file access attempt (and it won't open any files - gives "file not found" error).  (folders open fine)

same error is given even when run as administrator when encrypted file is attempted to be deleted - so delete doesn't work but modify does

Is this fixable from dokany?

*running in reverse mode: `"C:\Program Files (x86)\Dokan\encfs4win\encfs.exe" --reverse -f C:\test X:` (same with local folders as mount-point)
Windows10 10240

**Comment by Liryna** [comment]
Did you rebuild encfs4win ?

**Comment by Owyn** [comment]
No I didn't rebuild it, And its repository is unavailable now anyway. 
I found a github claiming to host it (there is no way to check if it has same files now) - https://github.com/freddy77/encfs4win but still compiling it is not a thing everyone could do ( http://stackoverflow.com/questions/18993141/howto-compile-encfs4win-on-windows )

**Comment by Liryna** [comment]
Without rebuild it is for sure that you will have a issue :(
Binary compatibility changed since we have moved to Visual Studio 2013.

Encfs4win seems to be a good projet. If someone want to maintain it, I would be glad to add it to the dokan-dev !

**Comment by Owyn** [comment]
@Liryna ok... I rebuilt it with VS 2013 and guess what? it gives pretty same error...

`23:26:48 (..\encfs\encfs.cpp:141) error caught in getattr`

**Comment by Liryna** [comment]
Ah that's great ! You will be able to debug it now.
It would be nice if you could fork encfs4win with the fix.

**Comment by Liryna** [comment]
@Owyn Have you been able to make encfs4win work with dokany ?

**Comment by Owyn** [comment]
@Liryna it worked from the box. just without some feautures which got broken.

**Comment by Liryna** [comment]
So I will close this issue if you don't mind. I think it is related to encfs4win.
It is pretty sad that even with a good number of users, nobody is willing to maintain it.
I hope someone will take the flag in a near future !

**Comment by jetwhiz** [comment]
Hi @Liryna -- maybe you have some ideas that can help me fix this issue?  I have noticed that when encfs4win is mounted to a drive letter (e.g., "Z:") then everything works well, but when encfs4win is mounted to an empty folder (e.g., "C:\myfiles\mountpoint"), all of the requests for getattr are for the short name (8.3 filename).  

For instance, when requesting the file "Z:\file.txt", getattr provides "file.txt".  When requesting "C:\myfiles\mountpoint\file.txt", however, getattr provides the file "FILE.TXT".  

Normally this is not an issue on Windows, but since we are encrypting the file names in encfs, there is a big difference between "file.txt" and "FILE.TXT".  Do you have any ideas as to why Dokan is providing the short filename for mounted drives ("C:\myfiles\mountpoint\") but provides the long filename when the filesystem is mounted to a drive letter ("Z:") for us?

**Comment by Liryna** [comment]
Hi @jetwhiz ,

This is interesting, does C mirror also get FILE.TXT when mounted to C:\myfiles\mountpoint ?

**Comment by jetwhiz** [comment]
I just did a quick test (dumping Dokan debug output) and it looks like it might be the same on the fuse mirror: 

Mounted to "Z:"
````cmd
FileMatch? : .. (Cygwin.ico,0,0)
FileMatch? : bin (Cygwin.ico,0,0)
FileMatch? : Cygwin-Terminal.ico (Cygwin.ico,0,0)
FileMatch? : Cygwin.bat (Cygwin.ico,0,0)
FileMatch? : Cygwin.ico (Cygwin.ico,0,0)
  =>return single entry
````

Mounted to "C:\dec"
````cmd
FileMatch? : apropos (BUNZIP2.EXE,0,0)
FileMatch? : arch.exe (BUNZIP2.EXE,0,0)
FileMatch? : ash.exe (BUNZIP2.EXE,0,0)
FileMatch? : awk (BUNZIP2.EXE,0,0)
FileMatch? : base32.exe (BUNZIP2.EXE,0,0)
FileMatch? : base64.exe (BUNZIP2.EXE,0,0)
FileMatch? : basename.exe (BUNZIP2.EXE,0,0)
FileMatch? : bash.exe (BUNZIP2.EXE,0,0)
FileMatch? : bashbug (BUNZIP2.EXE,0,0)
FileMatch? : bunzip2.exe (BUNZIP2.EXE,0,0)
  =>return single entry
````

**Comment by Liryna** [comment]
I created an issue related to it https://github.com/dokan-dev/dokany/issues/293
I am unable to see for now if it is a dokan issue or it is the system that request such names because of the reparse point.

**Comment by jetwhiz** [comment]
Ok, thank you, @Liryna!  I will try to look into the code to see why there might be a difference here.
