### ISSUE TITLE
can not install dokan on clean windows 8.1

### ISSUE THREAD

**Issue by cdarau** [dokan-dev/dokany#362]
# Environment
 * Windows version: 8.1 Enterprise
 * Processor architecture: x64
 * Dokany version: 1.0.0.5000
 * Library type (Dokany/FUSE): Dokany
 
# Description
When I try to install dokan on a clean windows, I get the following error:
[0AAC:0F0C][2016-10-03T23:46:01]i301: Applying execute package: vcredist_2015_x86.exe, action: Install, path: C:\ProgramData\Package Cache\D6927D811724CE0EC60E880D7D4F46772284FDBE\vc_redist.x86.exe, arguments: '"C:\ProgramData\Package Cache\D6927D811724CE0EC60E880D7D4F46772284FDBE\vc_redist.x86.exe" /norestart /q /chainingpackage ADMINDEPLOYMENT'
[0AAC:0F0C][2016-10-03T23:52:33]e000: Error 0x80070017: Process returned error: 0x17
[0AAC:0F0C][2016-10-03T23:52:33]e000: Error 0x80070017: Failed to execute EXE package.
[0A70:0804][2016-10-03T23:52:33]e000: Error 0x80070017: Failed to configure per-machine EXE package.
[0A70:0804][2016-10-03T23:52:33]i319: Applied execute package: vcredist_2015_x86.exe, result: 0x80070017, restart: None
[0A70:0804][2016-10-03T23:52:33]e000: Error 0x80070017: Failed to execute EXE package.

After inspecting around it, I came to the following conclusions:
- vc_redist.x86.exe has as prereq Windows8.1-KB2999226-x64.msu
- Windows8.1-KB2999226-x64.msu has as prereq Windows8.1-KB2919355-x64.msu
- Windows8.1-KB2919355-x64.msu has as prereq Windows8.1-KB2919442-x64.msu
- Windows8.1-KB2919442-x64.msu has no prereq

The problem is that the installer doesn't treat the last two prereqs, thus stopping at KB2999226, which is clearly not enough for the win81 scenario. I tried to modify the installer in order to install the needed msus, but I'm having problems detecting if KB2919442 is already installed.

Also, it's kind of strange that the installer fails in the manner it does (with the above visible error to the end-user), because this scenario is pretty common, I guess. Do I miss something obvious here?

Any help would be very appreciated. Thanks!

# Logs
[log_install_dokany_win81clean.txt](https://github.com/dokan-dev/dokany/files/509920/log_install_dokany_win81clean.txt)

**Comment by js69** [comment]
Could you please post the vc_redist logs as well?

**Comment by Liryna** [comment]
There is an issue open at microsft about this: https://connect.microsoft.com/VisualStudio/feedback/details/1598704/microsoft-visual-c-2015-redistributable-x86-and-x64-14-0-23026-fail-to-properly-install-on-windows-8-1-x64

**Comment by js69** [comment]
A mandatory update that isn't mandatory. Don't we all love Microsoft. 

Guess we need to include the two other KB msus as well.

**Comment by Liryna** [comment]
😞 I hope the size of them are acceptable. Otherwise it is better to simply add an error message.

**Comment by js69** [comment]
319 MB for just KB2919355-x86 is kinda prohibitive. So we just add checks with download links?

**Comment by Liryna** [comment]
😆 A link would be much better yes haha !

**Comment by js69** [comment]
https://support.microsoft.com/en-us/kb/2919355

"The updates must be installed in the following order: clearcompressionflag.exe, KB2919355, KB2932046, KB2959977, KB2937592, KB2938439, and KB2934018."

They were either quite lazy not to repackage all of that into one download or just plain insane.

**Comment by Liryna** [comment]
Let's simply say to install KB2999226 with a link to https://support.microsoft.com/en-us/kb/2999226 😃

**Comment by cdarau** [comment]
I don't have the vc_redist logs, sorry.

Thanks for the rest of the informations. Very valuable.

Btw, KB2919355 for x64 is aprox 700 MB. It's clearly a mess wrt Microsoft updates.

**Comment by Liryna** [comment]
@js69 do you think you can handle this for the 1.0.1 ? ❤️

**Comment by js69** [comment]
I hope to find the time tomorrow. We'll need version numbers of DLLs in those patches we can check for though unless we want to trust the registry for installed KBs alone. 

Anyone have Win 8.1 VMs before and after those KBs installed?

**Comment by Liryna** [comment]
Last message of Microsoft https://connect.microsoft.com/VisualStudio/feedback/details/1598704/microsoft-visual-c-2015-redistributable-x86-and-x64-14-0-23026-fail-to-properly-install-on-windows-8-1-x64
```
check that the file version of:
C:\Windows\SysWOW64\wuaueng.dll
C:\Windows\System32\wuaueng.dll
is 7.9.9600.17031 or later.
```

I will be able to install a 8.1 clean to test it 👍

**Comment by cdarau** [comment]
There is another problem though. This particular update (KB2919355) has another prerequisite, namely KB2919442. The microsoft link is: https://support.microsoft.com/en-us/kb/2919442. I already dealt with this problem, since treating just the KB2919355 hotfix didn't solve the problem (as you will see by yourselves).

I had to check for TiWorker.exe's version, which lies in one of the many subfolders underneath %windir%\WinSxS\. I done this with the following snippet:

`<Property Id="WINKB2919442INSTALLED" Secure="yes">
      <DirectorySearch Id="SearchSystemWinKB2919442" Path="[WindowsFolder]WinSxS" Depth="2">
        <FileSearch Name="TiWorker.exe"
                    MinVersion="6.3.9600.17030"/>
      </DirectorySearch>
    </Property>`

Hope this helps!

**Comment by Liryna** [comment]
Checking only KB2999226 is enough no ?

**Comment by cdarau** [comment]
Well it depends what you mean by "enough". If I understood correctly, you wanted to give the end-user a chance to install these hotfixes, so checking only KB2999226 would not be enough in case it isn't there. I would start by checking for KB2919442 (only for win8.1), than check for KB2919355 (only for win8.1) and only than would I check for KB2999226 (needed for all versions).

**Comment by Liryna** [comment]
Well, OK I agree that could be the best to have a personalized error message.
Just to understand, the KB2999226 can only be installed if other KB that you listed are also installed ? (that's why I wanted to check only this ony and probably also list all KB dependency)

Thanks again @cdarau for taking the time on this !

**Comment by cdarau** [comment]
Yes, on win8.1, KB2999226 can only be installed if KB2919355 is installed. Also, KB2919355 can only be installed if KB2919442 is installed. I already tried this on clean, intermediate and fully prepared environments.

No problem. This work came out from using dokan, so you guys should be the one to be thanking to. Cheers!

**Comment by Liryna** [comment]
@js69 I wanted to add the check but I remember/found that we already have a check for this situation no ?
https://github.com/dokan-dev/dokany/blob/da39829ddccbf68e7d4af3966edb8b0c91afa25f/dokan_wix/Bootstrapper/Bundle.wxs#L153-L177

Does that mean there is something missing this check or ?

**Comment by js69** [comment]
Those are install/detect conditions which don't stop installation attempts. We will need a bal:Condition check to catch what cdarau described above.

```
<Property Id="WINKB2919442INSTALLED" Secure="yes"> <DirectorySearch Id="SearchSystemWinKB2919442" Path="[WindowsFolder]WinSxS" Depth="2"> <FileSearch Name="TiWorker.exe" MinVersion="6.3.9600.17030"/> </DirectorySearch> </Property>

<bal:Condition Message="Installation failed because on Windows 8.1 the installation of KB2919355 and its prerequisites KB2999226 and KB2919442 is required. For more info please visit https://support.microsoft.com/en-us/kb/2919355"><![CDATA[Installed OR VersionNT = v6.3] AND NOT WINKB2919442INSTALLED]></bal:Condition>
```

**Comment by cdarau** [comment]
Just a short mention. It's not "the installation of KB2919355 and its prerequisites KB2999226 and KB2919442 is required". It's "the installation of KB2999226 and its prerequisites KB2919355 and KB2919442 is required".

**Comment by js69** [comment]
I find it quite hilarious that a higher numbered KB could be a prereq for a lower number.

**Comment by Liryna** [comment]
I have add the @js69 check https://github.com/dokan-dev/dokany/commit/bbf256e1bd21362ce60cec76c95d8107582e4f9a#diff-2b9d1f43d6d6c50ec9813a10ad44c436R205 👍 

I tried to have a windows 8 without KB2919355  but all my iso installation have it already.... @cdarau do you think you can test the installer and see if you get the error as expected ? 
https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.1-804/job/emsti3fiyqbql85n/artifacts

(the installer is selfsigned https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot so the mirror will not work.)

**Comment by Rondom** [comment]
I do not want to spill oil in the fire by over-complicating an already complicated situation, but ...

... do we also need to check GDR and LDR versions like we do for the Win7-Update?

**Comment by Liryna** [comment]
https://support.microsoft.com/en-us/kb/2919442 there don't seems to be a difference of version for GDR LDR (at least it does not seems to be documented)

**Comment by Rondom** [comment]
Thank god 😄

**Comment by js69** [comment]
Liryna, is there a problem with the check above, since you reverted?

On a different note, I think we should install the dev files (mirror) by default, at least with the bundle. To be added:

<Variable Name="DevFilesCheckbox" Type="numeric" Value="1"/>

**Comment by Liryna** [comment]
@js69 I didn't revert my commit :O what do you mean ?

Yes, I think we are going to set the dev files by default. Already a couple of people have not found it.

**Comment by js69** [comment]
I could have sworn I saw the commit canceled in my Github client, but it is Monday, so I might very easily be wrong :)

**Comment by cdarau** [comment]
Sorry for my late response. Unfortunately, I can't test that scenario myself, because I already installed the said KB on my env (when I dealt with the problem).

**Comment by Liryna** [comment]
😢 humm looks like we will wait that someone open an issue in case this can still be faced.

Thanks @cdarau and @js69 for taking the time on this 👍

**Comment by Rondom** [comment]
I think there are quite a few non-developers who  are installing Dokan, because it is a dependency of e.g. WinSSHFS.
I would rather make the checkbox more prominent on the first page. Currently it is hidden behind some advanced options button and developers will know that they want to "development files"

**Comment by js69** [comment]
Rondom, 1 MB or so for the dev files are not doing any harm. We can decide to change the default back again later, when everything is more solid.

**Comment by Rondom** [comment]
Okay, point taken :-)

**Comment by Liryna** [comment]
I have enabled it for now https://github.com/dokan-dev/dokany/commit/8dcbd930d7c4e01f3fd99d716ce17002f43953c8
