### ISSUE TITLE
mirror.exe missing

### ISSUE THREAD

**Issue by dimov-cz** [dokan-dev/dokany#364]
https://github.com/dokan-dev/dokany/wiki/Use-Mirror-example

> Mirror.exe is embedded with dokan install `Dokan\DokanLibrary\sample\mirror`.

mirror.exe is not in the current package. The page above is out-of-date or someone forgot to add it to install. Where can I get current version of mirror without compiling it myself?

**Comment by Liryna** [comment]
@dimov-cz You have to enable the option to accept installing development files.

**Comment by dimov-cz** [comment]
Ops, my fault, i didn't notice options button. Thanks
