### ISSUE TITLE
DokanFCBUnlock() should be called in sys/create.c, sys/fscontrol.c

### ISSUE THREAD

**Issue by RogerlinInquartik** [dokan-dev/dokany#367]
# Environment
 * Windows version: Win7 
 * Processor architecture: x64
 * Dokany version: 1.0.1.791
 * Library type (Dokany/FUSE): Dokany
 
# Description:
   Hi! I found some places call DokanFCBLockRW() or DokanFCBLockRO(), but not call DokanFCBUnlock(). I suppose these should be put in. Please help to review if these are necessary.

#git patch:
<p>sys/create.c | 2 ++<br /> sys/fscontrol.c | 3 +++<br /> 2 files changed, 5 insertions(+)</p>
<p>diff --git a/sys/create.c b/sys/create.c<br />index 93c225e..af1f6f3 100755<br />--- a/sys/create.c<br />+++ b/sys/create.c<br />@@ -596,6 +596,7 @@ Return Value:<br /> if (relatedFileName == NULL) {<br /> DDbgPrint(" Can't allocatePool for relatedFileName\n");<br /> status = STATUS_INSUFFICIENT_RESOURCES;<br />+ DokanFCBUnlock(relatedFcb);<br /> __leave;<br /> }<br /> relatedFileName-&gt;Buffer =<br />@@ -605,6 +606,7 @@ Return Value:<br /> ExFreePool(relatedFileName);<br /> relatedFileName = NULL;<br /> status = STATUS_INSUFFICIENT_RESOURCES;<br />+ DokanFCBUnlock(relatedFcb);<br /> __leave;<br /> }<br /> relatedFileName-&gt;MaximumLength = relatedFcb-&gt;FileName.MaximumLength;<br />diff --git a/sys/fscontrol.c b/sys/fscontrol.c<br />index d10522c..c90af5c 100644<br />--- a/sys/fscontrol.c<br />+++ b/sys/fscontrol.c<br />@@ -206,6 +206,9 @@ NTSTATUS DokanOplockRequest(__in PIRP *pIrp) {<br /> ) &amp;&amp;<br /> DokanFCBFlagsIsSet(Fcb, DOKAN_DELETE_ON_CLOSE)) {</p>
<p>+ if (AcquiredFcb) {<br />+ DokanFCBUnlock(Fcb);<br />+ }<br /> DDbgPrint(" DokanOplockRequest STATUS_DELETE_PENDING\n");<br /> return STATUS_DELETE_PENDING;<br /> }</p>

**Comment by Liryna** [comment]
Hi @RogerlinInquartik ,

Thank your for the report and the patch !

I agree about the missing `DokanFCBUnlock` in create.c 👍 my mistake 😢 well found ! https://github.com/dokan-dev/dokany/commit/2c11442c4d904f191c60ba720e5e5be2d85dc44c

About fscontrol.c, the return is in a try finally so the finally will be executed and the lock will be released.
What do you think about it  ?

**Comment by RogerlinInquartik** [comment]
Yes,that is right. My mistake.  finally will be called even we use return.
