### ISSUE TITLE
Photos App in Windows 10 hangs Dokany when saving

### ISSUE THREAD

**Issue by js69** [dokan-dev/dokany#368]
See issue https://github.com/dokan-dev/dokany/issues/137

Windows 10 10586
DokanSetup-1.0.1.0792.exe

Photos saves forever
CTRL-C on mirror hangs forever after "unload, Success"
mirror.exe can not be killed, "Access denied" in taskmgr

**Comment by Liryna** [comment]
I have been able to reproduce and it seems that `FsRtlOplockBreakH` without ending 😢 
https://github.com/dokan-dev/dokany/blob/2c11442c4d904f191c60ba720e5e5be2d85dc44c/sys/create.c#L1039

@bailey27 I remember you was talking about this `FsRtlOplockBreakH` in your comment here:
https://github.com/dokan-dev/dokany/issues/285#issuecomment-232012297

Do you think we should enable the callback ?

**Comment by Liryna** [comment]
@js69 did you also faced the issue on RC4 ? (in case of you remember doing this)

**Comment by js69** [comment]
With RC4 Photos does not have the issue, just retested it in the VM.

**Comment by Liryna** [comment]
Ok so it should be a lock issue (only change made since RC4)
Thank you for the test @js69 !
Will try to fix it this weekend :)

**Comment by js69** [comment]
I've just tested it with DokanSetup-1.0.0.5000 and it still works correctly there.

**Comment by Liryna** [comment]
Ok @js69 I have test all commit and found that the issue appear with https://github.com/dokan-dev/dokany/commit/45f89a88a4f4715a5f9b2dab0d480ed217ea99fe 👍

**Comment by js69** [comment]
For me 790 still works, 791 shows the issue. That would mean commit https://github.com/dokan-dev/dokany/commit/d15e23cb7d0f77c79e7e5c62b6e7fdb4a8a08134 is responsible.

**Comment by Liryna** [comment]
Humm are you sure 😮 ? I tested it and still have the issue.

**Comment by js69** [comment]
Yes, reproduced uninstalls/installs between 790 and 791. 790 works, 791 does not.

Dokan1.sys is 1.0.1.790 from October 7th. My Microsoft.Photos.exe has the file version 1.0.1607.22006.

**Comment by js69** [comment]
Ugh, it happened with 790 now. Size of the jpg seems to matter, bigger has created the issue.

**Comment by js69** [comment]
Ok, sorry, the issue happens with 789 first, 788 seems to work correctly.

**Comment by Liryna** [comment]
I tested more and this seems to be a race condition when it happen.
I have been able to reproduce on 1.0.0 😢

**Comment by js69** [comment]
Yup, last version that really works for me is RC4.

**Comment by Liryna** [comment]
I made a fix (unlock during oplock) https://github.com/dokan-dev/dokany/commit/b69f03e7a84e14a3a89c11dab5363cb2823b8ab5
Can you test on your side ?

**Comment by js69** [comment]
With 793 I did get an error message the first time clicking on Edit "modification not possible, file already opened" (my translation here) but the hanging does not occur anymore so far. The error message might have occurred because mirror with output is somewhat slow so file handle was still open on the first save (after rotating the picture) when I clicked on Edit (which does another save, or rather a more elaborate save to tmp file and rename operation as Photos does).

**Comment by Liryna** [comment]
👍 Thank you @js69 for the test!

The Delete is the desire access but does not specially mean that you will delete it. But if FILE_FLAG_DELETE_ON_CLOSE (dwFlagsAndAttributes) is requested, the DeleteOnClose will be set at CreateFile.
I hope I have answered your question 😃
