### ISSUE TITLE
Install FUSE headers alongside rest

### ISSUE THREAD

**Issue by raymond-h** [dokan-dev/dokany#37]
I made a fork of [`mafintosh/fuse-bindings`](https://github.com/mafintosh/fuse-bindings) to add support for Windows using the FUSE API of this repo. It's available at [`raymond-h/fuse-bindings`](https://github.com/raymond-h/fuse-bindings).

It works, however at the moment, you need to **both** install Dokany for binary files, **and** clone the repo for the dokan-fuse headers.

It'd be great if the dokan-fuse headers were bundled with the install as well.

**Comment by Liryna** [comment]
Hi,

Thats a very Great PR you have made :+1: 
I see no problem of adding the fuse header with the installer.

Do you need all headers of `dokan_fuse/include/` ?
I will add them into `\Dokan\DokanLibrary\include\fuse` if you see no objection.

I will make the changes when your PR will be merged.

**Comment by raymond-h** [comment]
Yeah, all headers would be great.

**Comment by Liryna** [comment]
Well done for your merged. :trophy: 
I will make a new release the 17 august with the includes you asked.
