### ISSUE TITLE
Question about cygwin files and installation

### ISSUE THREAD

**Issue by AireagoirSteam** [dokan-dev/dokany#374]
A possible feature if it doesn't exist already.

I was wondering in the dokan zip there is a cygwin folder I was wondering how would i install the contents of that folder into my cygwin install?

Secondly could I use fuse functionality in cygwin without dokany on the windows system? an example I have gigolo installed in cygwin and would like to be able to mount sftp which uses fuse to work but I also would like that install to be portable since I would prefer to use it at college and I don't use the same computer everyday.

**Comment by Liryna** [comment]
Hi @AireagoirSteam ,

Cygwin files in the zip has to be side by side of your application or in your runtime library path for being used by your application.

Unfortunately dokany is not portable and is mandatory for mounting file system with FUSE.
Dokany is a kernel windows driver and it is something that cannot be portable at all 😢 

Tell me if this answered your question 👍
