### ISSUE TITLE
Get rid of warnings in build process (and maybe enable more?)

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#376]
This is low priority. Currently the build process emits two kinds of warnings. I do not feel fully qualified to fix them myself since I am not so familiar with MSVC and WiX. I think the first one can be ignored, and the second one, I am not really sure about. 

# nameless struct/union

`C4201: nonstandard extension used: nameless struct/union` in  `mount.c:78`

I think we can safely disable this warning. The feature is supported by GCC using `-fms-extensions` as well and it is part of C11 and thus should be supported by any compiler that supports C11 (GCC, clang).

I am not sure about C++ standards compliance or whether there are plans. If someone knows, I am interested. It is C-Code, so at least in this case it does not matter.

# Bundle

`LGHT1132: The Payload 'vcredist_2015_x86.exe' is embedded but included a @DownloadUrl attribute. Embedded Payloads cannot be downloaded so the download URL is being ignored.` in `dokan_wix\Bootstrapper\Bundle.wxs`

This can be seen on AppVeyor. I am not really sure, what this means. ~~but from what I understand/guess, this only occurs, when not bundling the update-packages into the bundle. So the message is harmless when we are not building with the update-installers included~~

**Comment by Liryna** [comment]
Hi @Rondom ,

I removed the warning: https://github.com/dokan-dev/dokany/commit/da7b14f6c32cccd706b113d8f5d71214ba843372  👍 
I forgot to do it when I did the same for the mirror https://github.com/dokan-dev/dokany/blob/0955ed25243f5ba6f0290e1f4207ec5c996a1863/samples/dokan_mirror/mirror.c#L1211

About bundle warning, you are right, it only happens when we build an installer without redist embedded. This will make the installer download the redist during install if missing (never tested it). If we can remove the warning, it could be great but I have not an idea how to do this 😢 a
@js69 correct me if I am wrong 😄

**Comment by js69** [comment]
To remove LGHT1132 warning, In Bootstrapper.wixproj add this under the `<IntermediateOutputPath>obj\$(Configuration)\</IntermediateOutputPath>` lines:

`<LinkerAdditionalOptions>-sw1132</LinkerAdditionalOptions>`

**Comment by Rondom** [comment]
And I guess the warning can never appear for the "with-redist", build so we can unconditionally enable it?

**Comment by js69** [comment]
Correct.

**Comment by Liryna** [comment]
Thank you @js69 ! I added the option https://github.com/dokan-dev/dokany/commit/c234814992be7843a4c355fc23293b511e59c8d9 ❤️ 
No warnings 👍 https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.1-814/job/diq2gm4u0ae8x35j

@Rondom is that all warnings you found ?

**Comment by Rondom** [comment]
Yes, that's all, I think.
Just in case you are wondering, why I am "nitpicking". I plan to use the messages-tab in AppVeyor more, so any new warnings are spotted easily and can get fixed/ignored.

493a4cbb1f9610910565fda0f8e04607ba737d47

**Comment by Rondom** [comment]
Yes, that's all, I think.
Just in case you are wondering, why I am "nitpicking". I plan to use the messages-tab in AppVeyor more, so any new warnings are spotted easily and can get fixed/ignored.

a315e7d0aa2aadd2e9240858cfa58255dfdb559a
