### ISSUE TITLE
Asynchronous DokanMain for multi-FS support?

### ISSUE THREAD

**Issue by atanamir** [dokan-dev/dokany#381]
Hi,

I'm trying to use Dokan to create a remote cloud-based file system.  I was designing it so each mount point would refer to a different remote endpoint (e.g. cloud service account, etc.).  It'd be nice to be able to do this from a single process -- so I could call DokanMain for every cloud account the user wants to mount.  Since there's no async/OVERLAPPED support, I would have to create a thread for every DokanMain call... would it be possible to add asynchronous completion into DokanMain so I don't need to create multiple threads?

Thanks!

**Comment by Liryna** [comment]
Hi @atanamir ,

This behavior will be changed with https://github.com/dokan-dev/dokany/pull/307
See https://github.com/dokan-dev/dokan-dotnet/issues/87 (same request but on dokan-dotnet repository)

**Comment by Liryna** [comment]
I close this issue @atanamir if you would like since there is already an issue opened for it here https://github.com/dokan-dev/dokany/issues/210
