### ISSUE TITLE
AppVeyor CI: FSTest target hang

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#384]
I noticed that the FSTest "configuration" hangs sometimes at the start of the job sometime at or after repository checkout. We also had one situation were it was hanging in the middle of the build.

I somehow cannot see how the recent changes in the build could have been a cause of this, because they did not touch the FSTest stuff at all.

Examples:
1. https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.1-826/job/x7f57qbif5xk7kda
2. https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.1-831/job/4ai7fn022112ru3t
3. https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.1-840/job/6cf06sh16pcpqqc8  <= This is one where it does not hang

Does anyone have an idea about 3? What could have happened there? I guess for 1 and 2 we need to post a question in the AppVeyor forum.

**Comment by Liryna** [comment]
I agree that is pretty strange, specially that it is always the FSTest.
But I still think that it is an appveyor issue, should I open one here https://github.com/appveyor/ci/issues ?

**Comment by Rondom** [comment]
Yeah, probably that's the best. I could not find anything about it on their forums or their issue tracker.

Do you have any idea about the third build (the one that hung somewhere in the middle)?

**Comment by Liryna** [comment]
I think the third build is the same as others. Probably the VM crash or the output shell is disconnected.
It already happened in  the past that appveyor has some build that hang but these days are more offen.

OK I will open it after 👍

**Comment by Liryna** [comment]
Done: https://github.com/appveyor/ci/issues/1141

**Comment by Rondom** [comment]
The restarts you are describing in the issue are caused by a BSOD. Shame on us ;-) I opened a separate issue #386

**Comment by Rondom** [comment]
I filed a feature request appveyor/ci#1158 to handle BSODs cleanly.
Closing this issue as it is solved, probably due to the new cache.
