### ISSUE TITLE
Microsoft Visual C++ 2015 Redistributable Update 3 RC breaks DetectCondition

### ISSUE THREAD

**Issue by js69** [dokan-dev/dokany#388]
Hi Liryna,

please update the redists to 14.0.24212.
https://www.microsoft.com/en-us/download/details.aspx?id=53587

The previous RC redists (24123) broke the DetectCondition on a VM here that was updated to Win 10 1607 and had all current rollups. Result was setup error 80070666 in our bundle.

Changed URLs for Bootstrapper.wixproj should be:
powershell -command "wget https://download.microsoft.com/download/6/D/F/6DF3FF94-F7F9-4F0B-838C-A328D1A7D0EE/vc_redist.x86.exe -OutFile Redist\VCRedist_2015\VC_redist.x86.exe"
powershell -command "wget https://download.microsoft.com/download/6/D/F/6DF3FF94-F7F9-4F0B-838C-A328D1A7D0EE/vc_redist.x64.exe -OutFile Redist\VCRedist_2015\VC_redist.x64.exe"

**Comment by Liryna** [comment]
Hi @js69 ,

Thank you for keeping me update on this 😄 I never follow the release of it ❤️ 

Updated => https://github.com/dokan-dev/dokany/commit/a9d66d0665b3fa625a750388b1ffa4bb0eac6d9f

**Comment by sajjadkhan22** [comment]
thank yot
