### ISSUE TITLE
Change security attribute fail on Win 7 & Win 10 with mirror.exe

### ISSUE THREAD

**Issue by yin19941005** [dokan-dev/dokany#393]
# Environment
 * Windows version: 
1. Windows 7 SP1 with KB3033929 patch (32 bit)
2. Windows 10 Anniversary (64 bit)
 * Processor architecture: amd64
 * Dokany version: 1.0.1.1000 release
 * Library type (Dokany/FUSE): (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

p.s. Snapshot used : [1.0.1-14](https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.1-14/job/bbp9bqdt0syja902/artifacts)  (Only tested for Windows 7 32 bit)
# Description
I had tested to change the security attribute (adding a new user or changing the permission of user) on the dokan mounted drive but it return `The parameter is incorrect.` for some files. For the failed case, the `error code 998` is returned on the debug mode of mirror.exe. ([Error Code References](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681388(v=vs.85).aspx)) I had further test them and discovery that the file name is the factor on the changing security attribute is success or not.

It seems the file path with even numbers of character will success to change the security attribute and the one with odd numbers of character will fail. The error code 998 is related to the memory alignment. I think this maybe is because the filename is using UTF-16 for Windows (NTFS). During the file name conversion in dokany process may get some problem and cause this bug.

In my opinion, I think the bug occur in or related to `\dokan\security.c\DispatchSetSecurity` this function. I am trying to figure it out why this happening.

Command used for mount : `mirror.exe /r C:\temp /l Z /d /s`

# Logs
Fail Case:
![change_security_attribute_fail](https://cloud.githubusercontent.com/assets/23186757/20124406/1115de24-a661-11e6-9403-354fcefddbf7.png)

Sucess Case: (just append 'q' in the end of the file name )
![change_security_attribute_sucess](https://cloud.githubusercontent.com/assets/23186757/20124407/11165b56-a661-11e6-909d-ab015a1e8ae8.png)

**Comment by Kerbox** [comment]
Can you check in MirrorSetFileSecurity, if the SecurityDescriptor pointer is 4-byte aligned?

**Comment by yin19941005** [comment]
I am not pretty sure but I think it is not. By my understanding, when we set the Security Attribute the operation will be sent to the `\dokan\dokan.c\dokanloop` and call the `DispatchSetSecurity` function.

In `\dokan\security.c\DispatchSetSecurity`, 
`securityDescriptor =
      (PCHAR)EventContext + EventContext->Operation.SetSecurity.BufferOffset;`

The `PCHAR` should be 8 bits long (1 bytes) and `BufferOffset` is `ULONG` should be 4 bytes. So, it doesn't seems guarantee the  SecurityDescriptor pointer is 4-byte aligned.

References: [PCHAR](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383751(v=vs.85).aspx#CHAR) size, `\sys\public.h` for BufferOffset

**Comment by Kerbox** [comment]
The problem originates [here](https://github.com/dokan-dev/dokany/blob/master/sys/security.c#L301). It doesn't align the BufferOffset to 4 bytes, as it should. Either we have to fix it there, or memcpy the buffer into a new aligned buffer in MirrorSetFileSecurity.

**Comment by Liryna** [comment]
Well found guys ! we should probably memcpy the filename into another buffer 👍

**Comment by Kerbox** [comment]
How about we do it something like [this](https://gist.github.com/Kerbox/030c752b57093bc2b26b747ac9c6cb63)? Or would you rather that the user mode should handle it?

**Comment by Liryna** [comment]
This looks like much cleaner way to do it 👍 
(more comments about this case would be perfect !)

**Comment by Kerbox** [comment]
You mean others should comment on this issue, or I should put more comments in the code about it?

**Comment by Liryna** [comment]
Comments in the code 😃 In case some see it and question why it is done.

**Comment by Kerbox** [comment]
Ah, I will do that then 😄

**Comment by Liryna** [comment]
Fixed with https://github.com/dokan-dev/dokany/pull/394 Thanks to @Kerbox !
