### ISSUE TITLE
Mirror.exe fail to mount removable drive (/m option) on latest snapshot

### ISSUE THREAD

**Issue by yin19941005** [dokan-dev/dokany#395]
# Environment
 * Windows version: 
1. Windows 7 SP1 with KB3033929 patch (32 bit)
2. Windows 10 Anniversary (32 bit)
 * Processor architecture: amd64
 * Dokany version: 1.0.1.1014 snapshot e4cd2c312e4d24e4bd5e018c31983b939ad0a448 / 1.0.1.1017 snapshot 1639c0f2a569bb6d44653c3b1f08cab8ecf2e95b
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [ x ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

The latest release of [dokan 1.0.1](https://github.com/dokan-dev/dokany/releases/tag/v1.0.1) does not come with this problem.

# Description
Command used for mount : `mirror.exe /r C:\temp /l Z /d /s /m`

I am testing for the latest snapshot and discovery that the mirror.exe is able to mount up drive with `/m` removable drive anymore. I back to [dokan 1.0.1](https://github.com/dokan-dev/dokany/releases/tag/v1.0.1) release and find that the problem does not occur in that release.

The Error Codes:
- Error Code 183(0xB7) : ERROR_ALREADY_EXISTS
Cannot create a file when that file already exists.
- Error Code 122(0x7A) : ERROR_INSUFFICIENT_BUFFER
The data area passed to a system call is too small.

# Logs
![fail_to_mount_removable_drive](https://cloud.githubusercontent.com/assets/23186757/20164009/002303e0-a73c-11e6-903d-3c6042e384b3.png)

![fail_to_mount_removable_drive_win10](https://cloud.githubusercontent.com/assets/23186757/20164437/e66c7cc0-a73f-11e6-910b-5005f98ee1eb.png)

**Comment by Liryna** [comment]
This looks like comming from https://github.com/dokan-dev/dokany/commit/5bdfb4c3f9994971ed9334da742b7f62b02bdfe1 maybe I missed something 😢

**Comment by Liryna** [comment]
Fixed with https://github.com/dokan-dev/dokany/commit/2eb851397d5988879199b871cf3ee6a53658e424

Thank you @yin19941005 for the report !
