### ISSUE TITLE
Run tests in different settings

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#397]
Given that we reduced the built times recently, I think we can use that time to run FSX and WinFSTest in multiple configurations on AppVeyor to avoid regressions in those configurations. I have not tested whether all the tests pass under all configurations, though.

As a plus, it would be nice to move this functionality from appveyor.yml to a separate PowerShell-script. This makes it easier to run it on your own dev-environment and possibly also on different OS versions before preparing a release, because we only test ~~Win10~~ Win Server 2012 R2 on AppVeyor.

The script could loop over a hash-table that maps short-hand names for each config to mount-commands. Alternatively one could pass a list of short-hand names or mount-commands via command line.

Ideas:
* With or without mount manager
* Drive vs Directory Junction mount point
* removable media on/off
* network drive
* network drive accessed via UNC-Path
* (FUSE mirror does not support enough features, i.e. tests fail).

**Comment by Liryna** [comment]
I agree this would be great ! Appveyor only proposer Windows Server 2012 R2 😢 
So we can only test the Windows 10 driver version.

Totally agree with all the points !
Making tests with the different configuration in externel script is something we can do for sure !

**Comment by Rondom** [comment]
Oh, it is is Server 2012 R2 that AppVeyor runs. I never checked and being not too familiar with it I thought that it must be Win10 from how it looked like when logging in via RDP. 😊 
But I thought that `Server 2012 R2 <=> Desktop 8.1` and `Server 2016 <=> Desktop 10`, so it is the 8.1 driver we test, right?

**Comment by Liryna** [comment]
We should use the 8.1 but looks like not https://github.com/dokan-dev/dokany/blob/master/appveyor.yml#L236 😄

**Comment by Liryna** [comment]
Quick update, I changed the driver to 8.1 in appveyor
https://github.com/dokan-dev/dokany/commit/a8bfb27e7f33c8486c049b1f400f3ec6ea577afd

I will look to create a script that will help to test all mirror configuration with the tools we currently have.

**Comment by Rondom** [comment]
Maybe we should also pin the FSTest GIT-commit we use. Right now we cannot reproduce a test at a later point because we do not know what kind of tests were run exactly.

**Comment by Liryna** [comment]
@Rondom I have extracted and improve the mirror test. https://github.com/dokan-dev/dokany/blob/master/mirror_test.ps1

The test now run with:
* With or without mount manager
* With or without mount point
* removable media on/off
* network drive
* network drive accessed via UNC-Path

This add ~4min to the build test but thats alright 👍 
https://ci.appveyor.com/project/Maxhy/dokany/build/job/5ntisjfmnucnacj2

I didn't made FUSE since like you said the example is not very completed 😢

**Comment by Liryna** [comment]
Closed too fast ><
If you want to change anyway, tell me and I reopen the ticket.

**Comment by Rondom** [comment]
Awesome! I think this is fine for now. Good to see that all tests pass.
I think to test FUSE we need some way to specify which tests we expect to pass and which we expect to fail. Otherwise it is very hard to judge whether things are behaving as expected or not.

**Comment by Liryna** [comment]
I have no idea if even half of the test work with the FUSE mirror, it is probably too simple 😢 
But I agree that should be interesting to know 👍
