### ISSUE TITLE
Windows Hangs Issue when Sharing Folders on dokan drive (1.0.1.1000 release mirror.exe)

### ISSUE THREAD

**Issue by yin19941005** [dokan-dev/dokany#398]
# Environment
 * Windows version: 
1. Windows 10 anniversary (32 bit)
2. Windows 10 anniversary (64 bit)
3. Windows 7 SP1 with KB3033929 patch (32 bit)
4. Windows 7 SP1 with KB3033929 patch (64 bit)
5. Windows Server 2012 R2
 * Processor architecture: amd64
 * Dokany version: 1.0.1.1000 release
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

p.s. Snapshot used : [1.0.1-18](https://ci.appveyor.com/project/Maxhy/dokany/build/job/6a2ru35ahaxq2cog/artifacts) (Only tested for Windows 7 (32 bit) and Windows 10 (32 bit))

# Description
I am trying to use the Windows build-in share folder function to share out the folders on the dokan drive. The folders on the dokan drive are able to share out to other machine. I can get the UNC path successfully by build-in share folder function on Windows. The remote client machine is able to create and read files on the host machine. However, problems will occur under any these condition : there are more than one remote client machine; OR the host machine is trying to access the same file through dokan drive. Different results will be produced between these two condition.

Steps to reproduce :
1. Mount up the drive with mirror on host machine
2. Sharing the folder on the dokan drive by the Windows build-in function on host machine
3. Connect the host machine by inputting the IP address on the remote client machine (both Win 7 & Win 10 tested as client)
4. Create or Open files on shared folder on host machine
5. - Repeat Step 3 and 4 for same file on another remote client machine; ***OR*** 
6. - Access the same file on the host machine through dokan drive
<br>

**(Update on this paragraph.)**
For the multiple remote client machine case, under my testing environment only Windows Server 2012 occur some problem. While Client A open a `.jpg` (just an example) and just viewing it, Client B cannot open the same `.jpg` to view it. Error message `The file that you are trying to access is in use by another program.` (sharing violation) returned to Client B. After Client A close it (maybe also wait for a while), Client B is able to open it. However, same issue happens to Client  A if he/she is trying to re-open it before Client B close it. This seems the dokan drive locked the file by `exclusive lock` instead of `shared lock` making this occurs. 
>For other OS, they seem working normal.

**Correction for this one**. Others OS may also got the same behavior. The testing program is `Windows Photo Viewer` and this program can reproduce the issue. I just tested on Windows Server 2012 R2 and Windows 7 both can reproduce this issue. For Windows 10, the default image viewer `Photo` cannot reproduce this issue, so, I haven't further test this issue on Windows 10.
<br>

For the host machine is trying to access the same file through dokan drive case, the host machine whole Windows explorer will be hanged (not responding) and can't quit mirror.exe by `CTRL + C` interrupt. After that, the Windows even can't shutdown normally, only Power Off the machine can be done. However, the **Windows 10 with removable drive option** does **NOT** come with this problem. It seems completely working fine on this set up. Except Windows 10 with removable drive option, all others OS environment (Win 7, Win 10, Win Ser 2012) with or without removable drive option will crash.

This should not be the normal behavior for the Sharing folder function. I had tested to access the actual storage on the host machine and it does not crash the explorer. That means before I do Step 5 or 6 mentioned above to reproduce, I tried to access the files on the host machine by `C:\temp` for my case and it does not crash the Windows explorer. For Windows 7 and Windows 10, the files can be used normally. For Windows Server 2012, error message `share violation has occurred` will be returned if trying to access to the same file.

In my opinion, this problem should be related to the locking issue. It seems when the Windows Sharing Folder function is trying to lock the files and dokan mishandle it. So, the problem occurs. For multiple remote client machine case, it should be mis-handled by dokan to use `exclusive lock` instead of `shared lock`. For host machine is trying to access the same file through dokan drive case, I think this is because the similar causes related to the locking issue.

Command used to mount for test : 
- `mirror.exe /r C:\temp /l Z /d /s`   (normal drive)
- `mirror.exe /r C:\temp /l Z /d /s /m`   (removable drive option)

# Logs
Successful share the folder:
![get_unc_path_successful](https://cloud.githubusercontent.com/assets/23186757/20203916/1f76f5f6-a806-11e6-8c49-e0efa8885e74.png)

Explorer Hang when trying to access the same files through dokan drive on host machine: 
![explorer_hang](https://cloud.githubusercontent.com/assets/23186757/20203918/24023e82-a806-11e6-8b50-e030955a98e4.png)

`Ctrl + C` can't even quit the mirror.exe
![cannot_quit_mirror](https://cloud.githubusercontent.com/assets/23186757/20203920/26fee662-a806-11e6-8437-fc274d63dafd.png)
<br>

Log from mirror.exe :
[Win7_32_dokan-1.0.1.1000_mirror.LOG.txt](https://github.com/dokan-dev/dokany/files/584987/Win7_32_dokan-1.0.1.1000_mirror.LOG.txt)
[Win7_32_dokan-1.0.1.1000_Removable_mirror.LOG.txt](https://github.com/dokan-dev/dokany/files/584988/Win7_32_dokan-1.0.1.1000_Removable_mirror.LOG.txt)
[Win10_64_dokan-1.0.1.1000_mirror.LOG.txt](https://github.com/dokan-dev/dokany/files/584989/Win10_64_dokan-1.0.1.1000_mirror.LOG.txt)
[Win10_64_dokan-1.0.1.1000_Removable_mirror.LOG.txt](https://github.com/dokan-dev/dokany/files/584990/Win10_64_dokan-1.0.1.1000_Removable_mirror.LOG.txt)
All of them are following the `Steps to reproduce` and do both Step 5 (Access by multiple client) and Step 6 (Access by host through dokan drive) finally hang.
<br>

Log from Windows 7 Kernel with normal drive :
[Win7_32_dokan_normalDrive_share_hang.LOG.txt](https://github.com/dokan-dev/dokany/files/584992/Win7_32_dokan_normalDrive_share_hang.LOG.txt)
Other than success and pending status, I found  : 
> STATUS_INVALID_DEVICE_REQUEST
> STATUS_NOT_IMPLEMENTED
> STATUS_BUFFER_OVERFLOW
> STATUS_ACCESS_DENIED
> STATUS_OBJECT_NAME_NOT_FOUND

in the log file.
I had trying to extract the useful log but it still pretty much.
[Win7_32_dokan_normalDrive_share_hang_extraction.LOG.txt](https://github.com/dokan-dev/dokany/files/584997/Win7_32_dokan_normalDrive_share_hang_extraction.LOG.txt)

**Comment by Liryna** [comment]
Hello @yin19941005 ,

Thank you for the report. This seems to be an issue with FCB lock/unlock and even probably an oplock case not well handled.
Can you try to test with this pull request https://github.com/dokan-dev/dokany/pull/382 ?
There is some changes in the lock/unlock in it

**Comment by yin19941005** [comment]
Hello @Liryna ,

I had a correction on the `multiple remote client machine case` paragraph. Now, the issue can always reproduce on Windows 7 either. One of the program can reproduce the issue is `Windows Photo Viewer`.

I had just test for the pull request #382 and seems it can fix the `host machine is trying to access the same file through dokan drive case` but the `multiple remote client machine case` still persist. With the #382 fix, the Windows didn't hang anymore. The host machine can still open up the files even there are existing a client also open up the files, which is normal behavior. However, another client still cannot open up the file.

For more easy to understand with #382 fix,

1. Mount up the drive with mirror on host machine
2. Sharing the folder on the dokan drive by the Windows build-in function on host machine
3. Connect the host machine by inputting the IP address on the remote client machine A (both Win 7 & Win 10 tested as client)
4. Create or Open files on shared folder on host machine
5. Access the same file on the host machine through dokan drive
6. Host machine successful open the same file. **_(NOT Hang anymore)_**
7. Repeat Step 3 and 4 for same file on another remote client machine B
8. Client machine B cannot open the file. Error message `share violation has occurred` returned. **_(NOT a normal behavior)_** 
<br><br>

I think this is because the fix on #382 make the dokan not locking the whole file up, so the Windows didn't hang. However, the lock didn't seems already well handled. Dokan should be mis-matched something like`shared read lock` as `shared write lock` (Not sure, not familiar with it). This should be the reason why the `shared violation` returned if there are multiple client.

**Comment by Liryna** [comment]
Ok I see @yin19941005 Looks like an oplock sharing issue.

This will need some debug logs to know if first we get the error from DokanCheckShareAccess
https://github.com/dokan-dev/dokany/blob/3a733e8842bf7a371950af9e68a603e5856c151b/sys/create.c#L376
And if it come from here, does that mean `IoCheckShareAccess` called in `DokanCheckShareAccess` have `FcbOrDcb->ShareAccess` not correctly updated ?

**Comment by yin19941005** [comment]
Hi @Liryna ,

Sorry for the delay. I had added some debug logs in `DokanCheckShareAccess` and trying to print out the  return value of `IoCheckShareAccess`on snapshot 1.0.1.1018 and didn't observe any strange return value with it. It would return 0 (`STATUS_SUCCESS`). And the problem persist.

I thought my snapshot version is pretty old and I had updated it to **snapshot version 1.0.1.1049**. And I am **not able to reproduce the issue** with `Windows Photo Viewer` anymore! It seems the issue had fixed! I further tested on snapshot 1.0.1.1045 and the problem didn't occur either. I am still identifying the root cause of this issue. Could you also test with the latest snapshot to check the issue persist or not?

Here is the code I used to print out some debug log on **snapshot 1.0.1.1049** : 
>status = IoCheckShareAccess(DesiredAccess, ShareAccess, FileObject,
                              &FcbOrDcb->ShareAccess, FALSE);
  DDbgPrint("  DokanCheckShareAccess : IoCheckShareAccess return status = %lx \n", status);
  DDbgPrint("  DokanCheckShareAccess : Start print out input parameter Flag ... \n");
  DDbgPrint("  DesiredAccess : \n");
  if (FlagOn(DesiredAccess, FILE_SHARE_READ)) {
	  DDbgPrint("    FILE_SHARE_READ \n");
  }
  if (FlagOn(DesiredAccess, FILE_SHARE_WRITE)) {
	  DDbgPrint("    FILE_SHARE_WRITE \n");
  }
  if (FlagOn(DesiredAccess, FILE_SHARE_DELETE)) {
	  DDbgPrint("    FILE_SHARE_DELETE \n");
  }
  DDbgPrint("  ShareAccess : \n");
  if (FlagOn(ShareAccess, FILE_GENERIC_READ)) {
	  DDbgPrint("    FILE_GENERIC_READ \n");
  }
  if (FlagOn(ShareAccess, FILE_GENERIC_WRITE)) {
	  DDbgPrint("    FILE_GENERIC_WRITE \n");
  }
  if (FlagOn(ShareAccess, FILE_GENERIC_EXECUTE)) {
	  DDbgPrint("    FILE_GENERIC_EXECUTE \n");
  }
  if (FlagOn(ShareAccess, FILE_READ_DATA)) {
	  DDbgPrint("    FILE_READ_DATA \n");
  }
  if (FlagOn(ShareAccess, FILE_LIST_DIRECTORY)) {
	  DDbgPrint("    FILE_LIST_DIRECTORY \n");
  }
  if (FlagOn(ShareAccess, FILE_WRITE_DATA)) {
	  DDbgPrint("    FILE_WRITE_DATA \n");
  }
  if (FlagOn(ShareAccess, FILE_ADD_FILE)) {
	  DDbgPrint("    FILE_ADD_FILE \n");
  }
  if (FlagOn(ShareAccess, FILE_APPEND_DATA)) {
	  DDbgPrint("    FILE_APPEND_DATA \n");
  }
  if (FlagOn(ShareAccess, FILE_ADD_SUBDIRECTORY)) {
	  DDbgPrint("    FILE_ADD_SUBDIRECTORY \n");
  }
  if (FlagOn(ShareAccess, FILE_CREATE_PIPE_INSTANCE)) {
	  DDbgPrint("    FILE_CREATE_PIPE_INSTANCE \n");
  }
  if (FlagOn(ShareAccess, FILE_READ_EA)) {
	  DDbgPrint("    FILE_READ_EA \n");
  }
  if (FlagOn(ShareAccess, FILE_WRITE_EA)) {
	  DDbgPrint("    FILE_WRITE_EA \n");
  }
  if (FlagOn(ShareAccess, FILE_EXECUTE)) {
	  DDbgPrint("    FILE_EXECUTE \n");
  }
  if (FlagOn(ShareAccess, FILE_TRAVERSE)) {
	  DDbgPrint("    FILE_TRAVERSE \n");
  }
  if (FlagOn(ShareAccess, FILE_DELETE_CHILD)) {
	  DDbgPrint("    FILE_DELETE_CHILD \n");
  }
  if (FlagOn(ShareAccess, FILE_READ_ATTRIBUTES)) {
	  DDbgPrint("    FILE_READ_ATTRIBUTES \n");
  }
  if (FlagOn(ShareAccess, FILE_WRITE_ATTRIBUTES)) {
	  DDbgPrint("    FILE_WRITE_ATTRIBUTES \n");
  }

**Comment by Liryna** [comment]
Hi @yin19941005,

Can you test with the 1.0.2 release to see if it fixed your issue ?

**Comment by yin19941005** [comment]
Hi @Liryna ,

I had tested with 1.0.2.1000 release with Windows 10 32 bits host and two Windows 7 client. I am **not able reproduce the issue anymore**!  Although I am not sure which commit had fixed this issue, the latest release had already fixed it!

The 1.0.2.1000 release had **already fixed this issue**! Thank you very much @Liryna !
