### ISSUE TITLE
Dokany does not release directory junction as non-admin with folder mount-point

### ISSUE THREAD

**Issue by jetwhiz** [dokan-dev/dokany#399]
# Environment
 * Windows version: Windows 7, Windows 10 tested
 * Processor architecture: x86 and x64
 * Dokany version: 1.0.1.1000
 * Library type (Dokany/FUSE): affects both Dokany and FUSE
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [?] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

I'm not sure if this is a bug or intended functionality, but when you mount Dokany to a pre-existing folder it will turn it into a directory junction (as expected).  Upon unmounting, however, it remains a mount point and is not returned to being a normal folder (as non-admin).  If run as admin this issue does not exist. 

Steps to reproduce: 
1. Make sure mount-point folder already exists (e.g., C:\Users\me\Desktop\out)
2. Mount without admin privileges (e.g., mirror.exe /r C:\Users\me\Desktop\in /l C:\Users\me\Desktop\out)
3. Unmount (e.g., with ctrl+c)
4. C:\Users\me\Desktop\out is still listed as a mount point (via dir) 

We also experience this issue with encfs4win via the FUSE API, which causes encfs4win to fail to re-mount whenever people use a directory junction mount point. 

![virtualbox_win7_19_11_2016_15_35_35](https://cloud.githubusercontent.com/assets/533569/20456122/357c4842-ae6e-11e6-9acc-63212b9a0aaf.png)

Maybe it is someway related to this issue: https://github.com/dokan-dev/dokany/issues/332 ? 

# Logs

````cmd
## Attempting to add SE_SECURITY_NAME privilege to process token ##
  failed: Unable to adjust token privileges: 1300
Failed to add security privilege to process
        => GetFileSecurity/SetFileSecurity may not work properly
        => Please restart mirror sample with administrator rights to fix it
Dokan: debug mode on
Dokan: use stderr
AllocationUnitSize: 512 SectorSize: 512
device opened
###QueryVolumeInfo -001
CreateMountPoint C:\Users\jetwhiz\Desktop\out -> \??\Volume{d6cc17c5-1731-4085-bce7-964f1e9f5de9}\ success
mounted: C:\Users\jetwhiz\Desktop\out -> \Volume{d6cc17c5-1731-4085-bce7-964f1e9f5de9}
Mounted
send global release for C:\Users\jetwhiz\Desktop\out
Ioctl failed for wait with code 995.
Ioctl failed for wait with code 995.
Ioctl failed for wait with code 995.
Thread will be terminated
Thread will be terminated
Ioctl failed for wait with code 995.
Thread will be terminated
Ioctl failed for wait with code 995.
Thread will be terminated
Thread will be terminated
Dokan Error: DokanKeepAlive CreateFile failed \\.\Volume{d6cc17c5-1731-4085-bce7-964f1e9f5de9}: 2
Unmounted

unload
Success
````

**Comment by Liryna** [comment]
Hi @jetwhiz ,

Thanks you for the report 👍 
You are right, DeleteVolumeMountPoint that should remove the link, fail with access denied when running without admin rights 😢 
https://github.com/dokan-dev/dokany/blob/fb88f567354cdd56dca9021460579c0093d45c8d/dokan/mount.c#L581

I look how this could be fixed.

**Comment by Liryna** [comment]
Fixed with https://github.com/dokan-dev/dokany/commit/9fa712cd98827dd228f73f041b4ff1f82fe99286 👍

**Comment by jetwhiz** [comment]
Great, thanks for the quick patch, @Liryna !
