### ISSUE TITLE
Clarifying statements

### ISSUE THREAD

**Issue by arekbulski** [dokan-dev/dokany#40]
I found 2 issues on the [API wiki page](https://github.com/dokan-dev/dokany/wiki/API) that is unclear to me. If you would please explain, I will edit the wiki accordingly. 

- FindFiles is supposed to return all directory entries for further filtering by dokan library? And is filtering entries prohibited in there?
- Mountpoint option "MountPoint" is supposed to demand that if C:\\... path is provided then C: must necessarily be using NTFS? Back in the old days, C drive could have been using FAT32.

Futher questions regarding comments in the code:
- https://github.com/arekbulski/dokany/blob/master/dokan/dokan.h#L322 <br>
What the hell is CreateDirectly...

**Comment by suy** [comment]
El Tuesday 11 August 2015, Arkadiusz Bulski escribió:
> - FindFiles is supposed to return all directory entries for further
> filtering by dokan library? And is filtering entries prohibited in there?

FindFiles is supposed to return all entries. FindFilesWithPattern can optimize 
that, if I understood that, if you want to implement it yourself. If not, 
Dokan will implement it for you from the resuls of FindFiles.

> - Mountpoint option "MountPoint" is supposed to demand that if C:\... path
> is provided then C: must necessarily be using NTFS? Back in the old days,
> C drive could have been using FAT32 or whatever else.

I think that Dokan needs to open the mount point as reparse point. That might 
not be possible in FAT, but I might be wrong.

**Comment by arekbulski** [comment]
My question refers specifically to whether FindFiles is allowed to filter entries anyway or not.

**Comment by suy** [comment]
Unless I'm missing something, no; all entries.

**Comment by suy** [comment]
Oh, I forgot: "OpenDirectly" is very likely a typo. :-)  Is OpenDirectory. There are only 3 operations that can create a file handle:

* CreateFile (opens or creates files).
* OpenDirectory.
* CreateDirectory (that would be equivalent in Unix/FUSE to mkdir+opendir).

And thank you for your edits to the wiki.

**Comment by arekbulski** [comment]
Actually it's CreateDirectly. You made a pun of a pun... :stuck_out_tongue_winking_eye:

**Comment by Liryna** [comment]
Thank you @suy you are correct as always :smiley: 

Thank again @arekbulski for your review ! Always great to have a external eyes :+1:

**Comment by arekbulski** [comment]
I made changes to wiki directly, they are automatically accepted. But you can review revisions on each wiki page.

**Comment by Liryna** [comment]
Wow amazing ! Great job ! :heart:
