### ISSUE TITLE
Rename Files Fail on Shared dokan drive with mirror.exe (1.0.1.1000 release)

### ISSUE THREAD

**Issue by yin19941005** [dokan-dev/dokany#400]
# Environment
 * Windows version: 
1. Host : 
Windows 7 SP1 with KB3033929 patch (32 bit) for snapshot, 
Windows 10 Anniversary (64 bit) for release
2. Client : 
Windows 7 SP1 with KB3033929 patch (32 bit), 
Windows 10 Anniversary (32 bit), 
Windows 10 Anniversary (64 bit)
 * Processor architecture: amd64
 * Dokany version: 1.0.1.1000 release / 1.0.1.1018 snapshot 2eb851397d5988879199b871cf3ee6a53658e424
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

p.s. Snapshot used : [1.0.1-18](https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.1-18/job/6a2ru35ahaxq2cog/artifacts) (Only tested for Windows 7 (32 bit))

# Description
I am trying to use the Windows build-in share folder function to share out the folders on the dokan drive. For the dokan share drive, I am able to rename the files in the root directory but not able to rename the files in sub-directory. If I directly rename on dokan drive or in the physical drive, there are no problem.

Steps to reproduce :

1. Mount up the drive with mirror on host machine
2. Sharing the dokan drive by the Windows build-in function on host machine
3. Connect the host machine by inputting the IP address on the remote client machine 
(both Win 7 & Win 10 tested as client)
4. Trying to rename the target files (in sub-directory)

I found that the `MoveFile` function is performing wrong operations :
From mirror Log : `MoveFile C:\temp\t1\t2\New folder -> C:\temp\t1\t2\t1\t2\t1` 
However, I am just renaming the folder in `C:\temp\t1\t2\`.

I think the causes of this problem is the `\sys\create.c\DokanGetParentDir` function had been called for twice instead of once. I had added some `DDbgPrint` for the get function start and end. And discovery that the get function will be called twice for each trial on the dokan share drive while the normal behavior is just call it once (I had tested it by directly rename a folder on dokan drive). However, I got no idea why it had called the  `DokanGetParentDir` twice.

Command used to mount : `mirror.exe /r C:\temp /l Z /t 1 /d /s`

# Logs
Screenshot :
![rename_fail](https://cloud.githubusercontent.com/assets/23186757/20512109/241d47a8-b0b8-11e6-824f-63c27a3f4750.png)

Mirror Log :
[[161122]Mirror_dokan-1.0.1.1018_rename.LOG.txt](https://github.com/dokan-dev/dokany/files/605559/161122.Mirror_dokan-1.0.1.1018_rename.LOG.txt)

DbgPrint added on GetFilePath function in mirror:
> DbgPrint(L"  \tGetFilePath : \n");
	DbgPrint(L"  \t\tUnclen = %u , Input File name = %s \n", wcslen(UNCName), FileName);
	DbgPrint(L"  \t\tOutput File Path = %s \n", filePath);

Kernel Log :
[[161122]Kernel_Look After 45s_dokan-1.0.1.1018_rename.LOG.txt](https://github.com/dokan-dev/dokany/files/605560/161122.Kernel_Look.After.45s_dokan-1.0.1.1018_rename.LOG.txt)

DbgPrint added on `\sys\create.c\DokanGetParentDir` function:
> DDbgPrint("  DokanGetParentDir start!\n");
	... ...(function code)
	DDbgPrint("  DokanGetParentDir success end!\n");
	return STATUS_SUCCESS;

**Comment by yin19941005** [comment]
Hello,

I got some new findings on this issue. I had added more DbgPrintW in `\dokan\setfile.c\DokanSetRenameInformation`
>WCHAR newNameTest[MAX_PATH];
ZeroMemory(newNameTest, sizeof(newNameTest));
RtlCopyMemory(newNameTest, renameInfo->FileName, renameInfo->FileNameLength);
DbgPrintW(L"### setfile rename. info name :%s\n", newNameTest);

I found that if I directly rename on dokan drive, there is a leading "`\`".
`### setfile rename. info name :\t1\t2t2`
Through share,
`### setfile rename. info name :t1\t2`

And the following block of if statement will trying to add the parent folder to it.
[setfile.c#L164](https://github.com/dokan-dev/dokany/blob/master/dokan/setfile.c#L164)
>  if (renameInfo->FileName[0] != L'\\') {
    ULONG pos;
    for (pos = EventContext->Operation.SetFile.FileNameLength / sizeof(WCHAR);
         pos != 0; --pos) {
      if (EventContext->Operation.SetFile.FileName[pos] == '\\')
        break;
    }
    RtlCopyMemory(newName, EventContext->Operation.SetFile.FileName,
                  (pos + 1) * sizeof(WCHAR));
    RtlCopyMemory((PCHAR)newName + (pos + 1) * sizeof(WCHAR),
                  renameInfo->FileName, renameInfo->FileNameLength);
  } else {
    RtlCopyMemory(newName, renameInfo->FileName, renameInfo->FileNameLength);
  }

@Liryna ,
Base on my understanding, the if-else statement is trying to handle the relative path input, am I right? Because the `\` should be reserved by Windows, so, I think it is adding the parent path to it in order to get the absolute path.

# Source Log files
[[161124]Mirror_dokan-1.0.1.1018_rename_directOnDokan_debug.LOG.txt](https://github.com/dokan-dev/dokany/files/610369/161124.Mirror_dokan-1.0.1.1018_rename_directOnDokan_debug.LOG.txt)
[[161124]Mirror_dokan-1.0.1.1018_rename_ThroughShare_debug.LOG.txt](https://github.com/dokan-dev/dokany/files/610370/161124.Mirror_dokan-1.0.1.1018_rename_ThroughShare_debug.LOG.txt)

**Comment by Liryna** [comment]
Hi @yin19941005 ,

Sorry for the delay and thank you for the report and finding the source of the issue !

Yes, you are exactly right ! This code try to add the absolut path in case it is missing (that seems to not correctly work in this case). Do you think you can provide a patch that could fix this ? ❤️ (I am currently rebuild my VMs)

**Comment by yin19941005** [comment]
Hello @Liryna ,

I got more new findings on this issue. Just adding the "\\" **_would not solve this issue_**. And the root cause of this issue is on the driver (dokan.sys).

# Findings
I found that the root cause of this issue should be on the `\sys\fileinfo.c\DokanDispatchSetInformation` this function (**on driver**). The leading "\\" missing should be a normal behavior; The problem is cause by the **driver** didn't handle the IRP input correctly.

Base on MSDN, the [FILE_RENAME_INFO structure](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364398(v=vs.85).aspx) would contain a Handle for the `RootDirectory` but the dokan driver will just ignore it. Start from [this line](https://github.com/dokan-dev/dokany/blob/master/sys/fileinfo.c#L452) in fileinfo.c, the driver start to get the values from the IRP but the RootDirectory had been ignored. 

I had added some DbgPrintW to check the RootDirectory in `renameInfo` (get from `Irp->AssociatedIrp.SystemBuffer`) and I discovery that the RootDirectory always **NOT NULL** when the file path didn't contain a leading "\\". One of the use case of RootDirectory is the Shared Dokan Drive. By my understanding, the Windows would use the "RootDirectory" parameter to handle the relative path issue. I think that's why the problem occur.

# Testing result when prepend "\\"
The rename will success if you share the root directory of the dokan drive. For example, using `mirror.exe /r C:\temp /l Z /t 1 /d /s` to mount up dokan drive, the rename will work fine if you sharing "Z:\". However, if you are sharing the sub-folder in the dokan drive, the **rename will remain fail** (e.g. Sharing "Z:\t1\t2\t3\"). 

Moreover, this issue may **_cause explorer hold up_**. I had tested to "Cut-and-Paste" file (the actual operation will be rename). I had tested with this test case : 
Original Path : "Z:\t1\t2\t3\t4\t5" (absolute path for easy understanding)
Destination Path : "Z:\t1\t2\t3\t5" (absolute path for easy understanding)
Shared Folder : "Z:\t1\t2\t3"
The mirror will suck in an infinity loop and keep retrying.

Here is the Edited version of setfile.c for convenient to test if anyone wanted: 
[setfile_dokan-1.0.1.1018 Edited.zip](https://github.com/dokan-dev/dokany/files/615649/setfile_dokan-1.0.1.1018.Edited.zip)

# Possible Solution 
1. Passing the RootDirectory handle to [`MirrorMoveFile`](https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L874) in order to pass it to Windows API and let the Windows handle it
2. Resolve the file path from RootDirectory handle and [prepend it to the file path ](https://github.com/dokan-dev/dokany/blob/master/sys/fileinfo.c#L464)

For the first solution, I think this would be a better solution than the second solution. This is because the Windows seems design the API base on the user will make use of the RootDirectory handle. And this should be less coming up problem if we adapt this solution. However, the API (or Interface?) of  [`MirrorMoveFile`](https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L833) would also change if we are going to pass the handle to it. Some [structure](https://github.com/dokan-dev/dokany/blob/master/sys/public.h#L360) may also required to change.

For the second solution, I am studying on [this essay on MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366789(v=vs.85).aspx) and I am not sure would there will be other side effect or not.
<br><br>
@Liryna , what is your opinion for these two solutions?

**Comment by Liryna** [comment]
@yin19941005 Thank you for your analyse !

There is a pull request made @marinkobabic that possibly can fix this issue, can you try to pull his changes and see if it fix it ?

**Comment by yin19941005** [comment]
I had just tested for the 1.0.1.1025 snapshot for the pull request you mentioned. And it does not fix this issue. However, I believe this issue is also related to the FULL PATH problem.

The difference between #396 and this issue should be in #396 the problem occur with PFILE_NAME_INFORMATION structure and this issue occur with FILE_RENAME_INFO structure. 

In this issue, the path is associated with a handle which is to the root directory in which the file to be renamed is located. BUT the dokan.sys didn't correctly handle it.

[https://msdn.microsoft.com/en-us/library/windows/desktop/aa364398(v=vs.85).aspx](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364398(v=vs.85).aspx)
>typedef struct _FILE_RENAME_INFO {
  BOOL   ReplaceIfExists;     //TRUE to replace the file; otherwise, FALSE.
  HANDLE RootDirectory;  //A handle to the root directory in which the file to be renamed is located.
  DWORD  FileNameLength; //The size of FileName in bytes.
  WCHAR  FileName[1]; //The new file name.
} FILE_RENAME_INFO, *PFILE_RENAME_INFO;

**Comment by marinkobabic** [comment]
I think that FILE_NAME_INFORMATION is still not completely implemented.
Please see the
https://msdn.microsoft.com/en-us/library/windows/hardware/ff567052(v=vs.85).aspx
about shares. I think this can be easily verified using NTFS and dokan.
Should return the same result.

Maybe is this the source of the problem why FILE_RENAME_INFO does not
contain correct data according to your statement.

**Comment by marinkobabic** [comment]
@yin19941005 

I think the source of your problem is here

https://github.com/dokan-dev/dokany/blob/master/sys/fileinfo.c#L475
```
RtlZeroMemory(renameContext->FileName, renameContext->FileNameLength);
        RtlCopyMemory(renameContext->FileName,
                      targetFileObject->FileName.Buffer,
                      targetFileObject->FileName.Length);
```
Please log the **targetFileObject->FileName** before RtlCopyMemory and then log after the RtlCopyMemory the **renameContext->FileName** 

Normally those two values should have the same data after RtlCopyMemory but I don't think it's so. So what are your log results?

**Comment by yin19941005** [comment]
Hi @marinkobabic ,

I had just added some log for the **targetFileObject->FileName.Buffer** and **renameContext->FileName**. I am just renaming the txt from **TestingABC.txt** to **TestingABCD.txt** in the same directory through the share drive. Here is the extracted log :

>(Log with Shared Dokan Drive)
00258244	78.20473480	[DokanFS] ==> DokanSetInformationn	
00258245	78.20476532	[DokanFS]   ProcessId 4	
00258246	78.20478058	[DokanFS]   FileName: t5\t6\TestingABC.txt FCB.FileName: \t1\t2\t3\t4\t5\t6\TestingABC.txt	
00258247	78.20481110	[DokanFS]   FileRenameInformation	
00258248	78.20482635	[DokanFS]   FileObject Specified t5\t6\TestingABCD.txt	
00258249	78.20484161	[DokanFS]   renameInfo->RootDirectory 8000074C	
00258250	78.20487213	[DokanFS]   targetFileObject != NULL	
00258251	78.20488739	[DokanFS]   renameContext->FileNameLength 42, targetFileObject->FileName.Length 42	
00258252	78.20491028	[DokanFS]   renameContext->FileName t5\t6\TestingABCD.txt.txt, targetFileObject->FileName.Buffer t5\t6\TestingABCD.txt 	
00258253	78.20493317	[DokanFS]   After RtlCopyMemory, renameContext->FileName t5\t6\TestingABCD.txt.txt, targetFileObject->FileName.Buffer t5\t6\TestingABCD.txt 	
00258254	78.20494843	[DokanFS]   After assign length, renameContext->FileNameLength 42, targetFileObject->FileName.Length 42 	
00258255	78.20500183	[DokanFS] ==> DokanRegisterPendingIrp	
00258256	78.20502472	[DokanFS] ==> DokanRegisterPendingIrpMain	
00258257	78.20504761	[DokanFS] <== DokanRegisterPendingIrpMain	
00258258	78.20507050	[DokanFS] <== DokanRegisterPendingIrp	
00258259	78.20508575	[DokanFS]   status = 0x103	
00258260	78.20510101	[DokanFS]   status = STATUS_PENDING	
00258261	78.20513153	[DokanFS] <== DokanSetInformation
[[161201]Kernel_dokan-1.0.1.1018_rename_ShareRenameInSameDirectory_debug33.LOG.txt](https://github.com/dokan-dev/dokany/files/626299/161201.Kernel_dokan-1.0.1.1018_rename_ShareRenameInSameDirectory_debug33.LOG.txt)

The following log is the normal local dokan drive rename log.

>(Log with local Dokan Drive)
00423630	29.12574005	[DokanFS] ==> DokanSetInformationn	
00423631	29.12575912	[DokanFS]   ProcessId 472	
00423632	29.12578011	[DokanFS]   FileName: \t1\t2\t3\t4\t5\t6\TestingABC.txt FCB.FileName: \t1\t2\t3\t4\t5\t6\TestingABC.txt	
00423633	29.12579918	[DokanFS]   FileRenameInformation	
00423634	29.12582016	[DokanFS]   FileObject Specified \t1\t2\t3\t4\t5\t6\TestingABCD.txt	
00423635	29.12584114	[DokanFS]   renameInfo->RootDirectory 00000000	
00423636	29.12585831	[DokanFS]   targetFileObject != NULL	
00423637	29.12587738	[DokanFS]   renameContext->FileNameLength 80, targetFileObject->FileName.Length 68	
00423638	29.12589836	[DokanFS]   renameContext->FileName \??\Z:\t1\t2\t3\t4\t5\t6\TestingABCD.txt, targetFileObject->FileName.Buffer \t1\t2\t3\t4\t5\t6\TestingABCD.txt 	
00423639	29.12592697	[DokanFS]   After RtlCopyMemory, renameContext->FileName \t1\t2\t3\t4\t5\t6\TestingABCD.txt, targetFileObject->FileName.Buffer \t1\t2\t3\t4\t5\t6\TestingABCD.txt 	
00423640	29.12596130	[DokanFS]   After assign length, renameContext->FileNameLength 68, targetFileObject->FileName.Length 68 	
00423641	29.12598038	[DokanFS]    rename: 	
00423642	29.12600517	[DokanFS] ==> DokanRegisterPendingIrp	
00423643	29.12602615	[DokanFS] ==> DokanRegisterPendingIrpMain	
00423644	29.12604523	[DokanFS] <== DokanRegisterPendingIrpMain	
00423645	29.12606621	[DokanFS] <== DokanRegisterPendingIrp	
00423646	29.12608528	[DokanFS]   status = 0x103	
00423647	29.12610626	[DokanFS]   status = STATUS_PENDING	
00423648	29.12612343	[DokanFS] <== DokanSetInformation	
[[161201]Kernel_dokan-1.0.1.1018_rename_LocalRenameInSameDirectory_debug34.LOG.txt](https://github.com/dokan-dev/dokany/files/626300/161201.Kernel_dokan-1.0.1.1018_rename_LocalRenameInSameDirectory_debug34.LOG.txt)


Yes, you are correct they are not the same while the normal dokan drive would only getting the same data after **RtlCopyMemory** operation. It is really weird for me. The **renameContext->FileNameLength** and **targetFileObject->FileName.Length** is also the same before assigning the value on the shared dokan drive while the normal dokan drive is relying the assign operation to make them equal.

Maybe we should check the actual length is consistent to the length its stated or not and perform some handling operation. What's your opinion?

**Comment by marinkobabic** [comment]
This pull request should fix your problem https://github.com/dokan-dev/dokany/pull/410

**Comment by yin19941005** [comment]
Thanks a lot @marinkobabic !!
The pull request #410 had fix my problem!
Thank you for your fix!

**Comment by Liryna** [comment]
Thanks both of you for the report and for looking at the issue 👍 ! always appreciate ❤️ 

Fixed with @marinkobabic contribution https://github.com/dokan-dev/dokany/pull/410
