### ISSUE TITLE
Session mounted drives don't show the volume label 

### ISSUE THREAD

**Issue by RustyHacksaw** [dokan-dev/dokany#401]
# Environment
 * Windows version:  7
 * Processor architecture: 32 bit 
 * Dokany version: 1.0.1.1000
 * Library type (Dokany/FUSE): dokany 
 
# Check List
  - [x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x ] I can always reproduce the issue with the provided description below.
  - [x ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
When I mount a drive as a session mount, there is no volume label present, when I mount the drive as global, it shows DOKAN volume label

# Logs
mirror /r c:\users /l m:
works fine

mirror /r c:\users /l m: /c
shows no volume name in explorer

# Support
 - Usage: <personal> - <testing>
 - Your personal priority to solve this issue: <med/high>
 - Support ability: <programming C, can create pull request / deeptesting / investigate driver issues>

**Comment by Liryna** [comment]
Hi @RustyHacksaw ,

Do you start the mirror with admin rights ?

**Comment by RustyHacksaw** [comment]
Hi Liryna,


Yes, I use a command prompt that I started with Run As Administrator.


.r.


________________________________

**Comment by Liryna** [comment]
@RustyHacksaw OK, so this is the normal behavior. When you mount the device with administrator rights and only for the current session (administrator session here) . It is only him that can access it and moreover see the device name.

**Comment by RustyHacksaw** [comment]
Ah, interesting, yes, I see that now.  I guess I was confused by the warning text that said to "restart mirror sample with administrator rights" and didn't bother to check explorer first =)  Thanks for clarifying.
