### ISSUE TITLE
STATUS_OPLOCK_NOT_GRANTED for FileSystemControl operation when using DOKAN_OPTION_FILELOCK_USER_MODE option

### ISSUE THREAD

**Issue by cdarau** [dokan-dev/dokany#402]
# Environment
 * Windows version: Windows 10 Enterprise
 * Processor architecture: x64
 * Dokany version: 1.0.1.1000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I receive error 0x80004005 when trying to play a .mp4 file with Movies & TV Windows 10 player.
It only happens when I'm using DOKAN_OPTION_FILELOCK_USER_MODE option.
I used ProcessMonitor to compare the errors produced when using the above option with those produced when not using it and the obvious difference between the two scenarios is that when using the option, every FSCTL_REQUEST_OPLOCK ends with "OPLOCK NOT GRANTED" result.

# Logs
ProcessMonitor:
![procmonlog](https://cloud.githubusercontent.com/assets/9717639/20581734/928634da-b1e3-11e6-9b41-6ac908a65047.png)

**Comment by Liryna** [comment]
Hi @cdarau ,

Thank for the report, can you add the kernel logs to see which FSCTL_REQUEST_OPLOCK is returning this error ?

**Comment by Liryna** [comment]
Probably we should return STATUS_SUCCESS when DokanUserFsRequest is called and DOKAN_OPTION_FILELOCK_USER_MODE is set (Dcb->FileLockInUserMode).

Can you just check if DokanUserFsRequest is called and it is him who return the error in your case ?

**Comment by Liryna** [comment]
FsRtlOplockFsctrl was returning the error because OplockCount is not correct and there is kind of not correct value since the lock is handled by the user land...set it to 0 fix the issue 👍 
https://github.com/dokan-dev/dokany/blob/master/sys/fscontrol.c#L218

Thank you @cdarau for the report !

**Comment by cdarau** [comment]
Sorry to reply to you so late. I had no time in between.

I'm glad to see you fixed it. Thank you!
