### ISSUE TITLE
Adobe lightroom fails on saving with 'The specified folder is not writable' with Dokan Mirror

### ISSUE THREAD

**Issue by pliard-chromium** [dokan-dev/dokany#411]
# Environment
 * Windows version: 7 
 * Processor architecture: x86_64 
 * Dokany version: Commit cb73b14d037046831538cc7b741104c073b9e91f  (Dec 1st)
 * Library type (Dokany/FUSE): Dokany 
 
# Check List
  - [X ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [X ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ X ] I can always reproduce the issue with the provided description below.

# Description
- Create DokanTest folder under ~/Desktop
- Start Dokany mirror with mirror.exe /r C:\Users\<USER>\Desktop\DokanTest /l N: /d /o /s
- Run the last version of Adobe Lightroom CC (2015.7) and export an image file (File->Export...)
- Change the export location by clicking on 'Choose'.
- Select the Dokany mirror location (N:) , create a new folder called 'New Folder' under it and navigate into it.
- Click on 'Select Folder' to validate.
- Observe that the export fails with a dialog saying 'The specified folder is not writable'.

# Logs
Please find mirror_output.txt attached.
[mirror_output.txt](https://github.com/dokan-dev/dokany/files/642759/mirror_output.txt)

**Comment by Liryna** [comment]
Hi @pliard-chromium ,

Thank you for the report.
Does the issue only happen when you create the folder before saving ?

**Comment by pliard-chromium** [comment]
Hi Liryna,

The issue happens whenever the image is saved not under the root, i.e. saving it under 'N:\' works but saving it under a folder, e.g. 'N:\folder\' doesn't work.

Thanks,
Philippe.

**Comment by Liryna** [comment]
Ok, I see !
Can you give a test with the last master ?
There is a commit https://github.com/dokan-dev/dokany/commit/33b569a5479d5211fc87a9e5ab9360052d64146a that could fix your issue if Adobe use FileNormalizedNameInformation

**Comment by pliard-chromium** [comment]
Ah, I will try that, thanks!

**Comment by Liryna** [comment]
@pliard-chromium have any news on this ?

**Comment by Liryna** [comment]
I will reopen if you have any news about this 👍
