### ISSUE TITLE
CreateFileMapping that expands file fails with error 1224

### ISSUE THREAD

**Issue by emailuser2009** [dokan-dev/dokany#412]
# Environment
 * Windows version: Windows 7
 * Processor architecture: x86
 * Dokany version: 1.0.1.1000
 * Library type (Dokany/FUSE): Dokany/mirror
 
# Check List
  - [X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [X] I can always reproduce the issue with the provided description below.
  - [X] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [X] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
CreateFileMapping() API call that specifies a higher mapping size than current file size fails (incorrectly )with error 1224 (The requested operation cannot be performed on a file with a user-mapped section open.). 

# Logs
[logs.zip](https://github.com/dokan-dev/dokany/files/650929/logs.zip)
[dokantest.zip](https://github.com/dokan-dev/dokany/files/650923/dokantest.zip)

# Support
 - Usage: personal - testing
 - Your personal priority to solve this issue: med
 - Support ability: Programming C

**Comment by emailuser2009** [comment]
Hi @Liryna @marinkobabic 
Do you require any further information to reproduce / diagnose the issue ?

**Comment by Liryna** [comment]
Hi @emailuser2009 ,

Thank you for the report, this happens because we call MmCanFileBeTruncated even when we want to grow the file and not to truncate it.
https://github.com/dokan-dev/dokany/blob/e2c0825262b129110a535225be75609da08b3751/sys/fileinfo.c#L489

@marinkobabic Kernel question 😃  my idea would be to save current file size during FileAllInformation, FileStandardInformation and FileNetworkOpenInformation in the fcb, like that we would know if the file is going to be truncated or not.

Before I possibly duplicate the information, do you know if we already save the file size somewhere ?
It seems like in fcb there is `FSRTL_ADVANCED_FCB_HEADER` struct that has file informations that is currently not use.
https://github.com/dokan-dev/dokany/blob/d3b7927fbc68296f9c41228a3e5fabe322be0b2a/sys/create.c#L74-L75
I wonder if we can use it ?

**Comment by marinkobabic** [comment]
@Liryna Yes, you can use it of course
https://msdn.microsoft.com/en-us/library/windows/hardware/ff539135(v=vs.85).aspx

Am 23.03.2017 11:56 schrieb "Liryna" <notifications@github.com>:

**Comment by emailuser2009** [comment]
@Liryna So the fix required would be something along the lines of..

```
if( pInfoEoF->EndOfFile.QuadPart < fcb->AdvancedFCBHeader.FileSize.QuadPart )
{
	if (!MmCanFileBeTruncated(fileObject->SectionObjectPointer, &pInfoEoF->EndOfFile)) {
	  status = STATUS_USER_MAPPED_FILE;
	  __leave;
	}		
}
```

Is that correct ?

**Comment by Liryna** [comment]
Hi @emailuser2009 ,

Yes, exactly ! but `fcb->AdvancedFCBHeader.FileSize` need to be set during FileAllInformation, FileStandardInformation and FileNetworkOpenInformation (probably more, didnt check all cases) complete wit success here: https://github.com/dokan-dev/dokany/blob/e2c0825262b129110a535225be75609da08b3751/sys/fileinfo.c#L303

**Comment by sefai** [comment]
Hello @Liryna 
This issue causes Visual Studio to fail creating *.ipdb files. I have tried to add what @emailuser2009 suggested and setting fcb->AdvancedFCBHeader.FileSize:

```
else if (irpSp->Parameters.QueryFile.FileInformationClass == FileStandardInformation) {
    
    PFILE_STANDARD_INFORMATION standardInfo = (PFILE_STANDARD_INFORMATION)buffer;
    
    FSRTL_ADVANCED_FCB_HEADER* header = IrpEntry->FileObject->FsContext;
    
    ASSERT(header != NULL);
    
    header->AllocationSize.QuadPart = standardInfo->AllocationSize.QuadPart;
    header->FileSize.QuadPart = standardInfo->EndOfFile.QuadPart;
    
    DDbgPrint("  AllocationSize: %llu, EndOfFile: %llu, FCB.AllocationSize: %llu, FCB.EndOfFile: %llu\n", standardInfo->AllocationSize.QuadPart, standardInfo->EndOfFile.QuadPart, header->AllocationSize.QuadPart, header->FileSize.QuadPart);
}
```

But this causes mirror to become unresponsive and needs a hard reset. Can you help me?

**Comment by Liryna** [comment]
@sefai I made a patch for the issue but like you I have a deadlock.
[0001-Kernel-Save-file-size-to-later-know-if-MmCanFileBeTr.txt](https://github.com/dokan-dev/dokany/files/987914/0001-Kernel-Save-file-size-to-later-know-if-MmCanFileBeTr.txt)

Will need to look at debug log see what is happening.

**Comment by sefai** [comment]
@Liryna I tried various things, but unfortunately couldn't succeed. Looking at other references of FsContext and FsContext2 I thought that we can access the header as follows:

```
fcb = ccb->Fcb;
ASSERT(fcb != NULL);
```

I tried various things but deadlock was unavoidable. I first tried to lock the FCB:

```
DokanFCBLockRW(fcb);
...
fcb->AdvancedFCBHeader.AllocationSize.QuadPart = allocationSize;
fcb->AdvancedFCBHeader.FileSize.QuadPart = fileSize;

DokanFCBUnlock(fcb);
```

Locking seems to work for just a few seconds, but as far as I click on a file in the mirrored drive, DokanFCBLockRW(fcb) call never returns.

```
ZZZ LockRW DokanCompleteQueryInformation  FFFFE0013953BE0
```

Then I thought maybe I needed to lock on ccb;

```
KeEnterCriticalRegion();
ExAcquireResourceExclusiveLite(&ccb->Resource, TRUE);
....
ExReleaseResourceLite(&ccb->Resource);
KeLeaveCriticalRegion();
```

It was just the same as FCB, ExAcquireResourceExclusiveLite(&ccb->Resource, TRUE) call never returns when I click on a file in the mirrored drive. Then I instructed not to wait on [ExAcquireResourceExclusiveLite](https://msdn.microsoft.com/en-us/library/windows/hardware/ff544351%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) call;


```
KeEnterCriticalRegion();
BOOL acquiredLock = ExAcquireResourceExclusiveLite(&ccb->Resource, FALSE);
if (acquiredLock) {
  ....
  ExReleaseResourceLite(&ccb->Resource);
  KeLeaveCriticalRegion();
}
```
This was not dead on file click. In fact, I could open a solution in VS from the mirror, start building, but deadlock occured on lib(output) generation after succesfully compiling various source files.

Not all locks are printed in debug log, so I manually checked FCB and CCB locking, but couldn't find a hint why this would happen. 

Maybe this trace will ring a bell?

**Comment by sefai** [comment]
@Liryna From kernel logs, I can see that first lock attempt on FCB in DokanCompleteSetInformation is causing the deadlock.

```
00004503	3.30350375	[DokanFS] ==> DokanCompleteSetInformation	
00004504	3.30350828	[DokanFS] ZZZ LockRW DokanCompleteSetInformation FFFFE000A3355A80
```

There is a comment in DokanFCB structure, can this be related?
```
// Locking: FIXME
FSRTL_ADVANCED_FCB_HEADER AdvancedFCBHeader;
```

**Comment by Liryna** [comment]
Hi @sefai ,

I am also looking at this but have currently not finding the issue here.
There is a dead lock at `DokanCompleteSetInformation` during `DokanFCBLockRW` I agree with you.
I made more logs:
```
[DokanFS] ZZZ LockRW DokanDispatchCreate FFFF88859A1E2680 \test
[DokanFS] ZZZ LockRW DokanDispatchCreate FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ Unlock DokanDispatchCreate FFFF88859A1E2680 \test
[DokanFS] ZZZ Unlock DokanDispatchCreate FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ LockRW DokanCompleteCreate FFFF88859A1E2680 \test
[DokanFS] ZZZ LockRW DokanCompleteCreate FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ Unlock DokanCompleteCreate FFFF88859A1E2680 \test
[DokanFS] ZZZ Unlock DokanCompleteCreate FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ LockRO DokanDispatchQueryInformation FFFF88859A1E2680 \test
[DokanFS] ZZZ LockRO DokanDispatchQueryInformation FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ Unlock DokanDispatchQueryInformation FFFF88859A1E2680 \test
[DokanFS] ZZZ Unlock DokanDispatchQueryInformation FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ LockRO DokanDispatchQueryInformation FFFF88859A1E2680 \test
[DokanFS] ZZZ LockRO DokanDispatchQueryInformation FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ Unlock DokanDispatchQueryInformation FFFF88859A1E2680 \test
[DokanFS] ZZZ Unlock DokanDispatchQueryInformation FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ LockRO DokanDispatchQueryInformation FFFF88859A1E2680 \test
[DokanFS] ZZZ LockRO DokanDispatchQueryInformation FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ Unlock DokanDispatchQueryInformation FFFF88859A1E2680 \test
[DokanFS] ZZZ Unlock DokanDispatchQueryInformation FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ LockRO DokanDispatchQueryInformation FFFF88859A1E2680 \test
[DokanFS] ZZZ LockRO DokanDispatchQueryInformation FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ Unlock DokanDispatchQueryInformation FFFF88859A1E2680 \test
[DokanFS] ZZZ Unlock DokanDispatchQueryInformation FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ LockRO DokanDispatchQueryInformation FFFF88859A1E2680 \test
[DokanFS] ZZZ LockRO DokanDispatchQueryInformation FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ Unlock DokanDispatchQueryInformation FFFF88859A1E2680 \test
[DokanFS] ZZZ Unlock DokanDispatchQueryInformation FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ LockRO DokanDispatchQueryInformation FFFF88859A1E2680 \test
[DokanFS] ZZZ LockRO DokanDispatchQueryInformation FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ Unlock DokanDispatchQueryInformation FFFF88859A1E2680 \test
[DokanFS] ZZZ Unlock DokanDispatchQueryInformation FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ LockRO DokanDispatchQueryInformation FFFF88859A1E2680 \test
[DokanFS] ZZZ LockRO DokanDispatchQueryInformation FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ Unlock DokanDispatchQueryInformation FFFF88859A1E2680 \test
[DokanFS] ZZZ Unlock DokanDispatchQueryInformation FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ LockRW DokanDispatchSetInformation FFFF88859A1E2680 \test
[DokanFS] ZZZ LockRW DokanDispatchSetInformation FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ Unlock DokanDispatchSetInformation FFFF88859A1E2680 \test
[DokanFS] ZZZ Unlock DokanDispatchSetInformation FFFF88859A1E2680 \test DONE
[DokanFS] ZZZ DokanCompleteSetInformation lock ccb...
[DokanFS] ZZZ DokanCompleteSetInformation lock ccb done
[DokanFS] ZZZ LockRW DokanCompleteSetInformation FFFF88859A1E2680 \test

```

I see no Unlock missing 😢 but for a reason the LockRW does not pass

**Comment by sefai** [comment]
Hi @Liryna,

I am uploading the kernel logs, maybe it does help for anyone to recognize the error.

[vm_kernel.txt](https://github.com/dokan-dev/dokany/files/1024760/vm_kernel.txt)

**Comment by sefai** [comment]
Hello @Liryna,

In DokanCompleteSetInformation, DokanFCBLockRW(fcb) is trying to acquire the FCB lock and if can't get it wait on it. I changed it like this:

```
DDbgPrint("ZZZ LockRWNoWait %s %p\n", __FUNCTION__, fcb); 
KeEnterCriticalRegion(); 
fcbLocked = ExAcquireResourceExclusiveLite(fcb->AdvancedFCBHeader.Resource, FALSE);
KeLeaveCriticalRegion();
```

I did this, because in fastfat code I have seen a comment "_Note that we do not acquire the resource for paging file operations in order to avoid deadlock with Mm._" in FatCommonSetInformation. If you look at the kernel logs which I sent before, the deadlock occurs because FsRtlSetFileSize and DokanCompleteSetInformation is racing for the lock.

Now, with this change it seems to be working. All the winfstests and fsx tests pass, also compiling a Visual Studio solution using incremental linking succeeds.

Do you think this change can have any side effects?

Regards,

**Comment by Liryna** [comment]
Hi @sefai ,

This sounds good ! Well, found !
Have you looked to make this lock conditional depending on paging files like they do ?
https://github.com/Microsoft/Windows-driver-samples/blob/master/filesys/fastfat/fileinfo.c#L845
Normally the flag `FSRTL_FLAG2_IS_PAGING_FILE;` should be set during createfile:
`fcb->AdvancedFCBHeader.Flags2 |= FSRTL_FLAG2_IS_PAGING_FILE;`

**Comment by sefai** [comment]
Yes @Liryna,

I tried to do that, but this flag is never set in Dokan. There is also a debug print for that https://github.com/dokan-dev/dokany/blob/master/sys/create.c#L561, but never seen it in the kernel logs. Maybe this is the hidden cause of the problem?

```
if (irpSp->Flags & SL_OPEN_PAGING_FILE) {
    DDbgPrint("  IrpSp->Flags SL_OPEN_PAGING_FILE\n");
}
```

**Comment by Liryna** [comment]
Ok I see 😢 
I wonder, does `FlagOn(Irp->Flags, IRP_PAGING_IO)` is set during DokanCompleteSetInformation ?

**Comment by sefai** [comment]
Hello @Liryna, IRP_PAGING_IO is set for this call. Should I use it to check if we can lock the FCB or not?

Regards,

**Comment by Liryna** [comment]
@sefai Yes, I think that should be the way to do it Regarding fastfat

**Comment by sefai** [comment]
I checked the winfstest suite logs against the IRP_PAGING_IO flag, and it was never set. So I think we can safely say it will be set for only Memory Mapped file IO.

By the way I can see a lot of cache related code in fastfat, but none in Dokan. Does this mean Dokan does not support caching?

**Comment by Liryna** [comment]
Ah great ! Yes I agree, IRP_PAGING_IO can safely be used here.

Dokan do not have internal cache currently. We have thought a little about it and it can be an improvement in some case like your data of your FS never change outside the drive and the cache will always be correct and automtically updated when a change is made. But if for example, your FS show FTP/Remote data that can be changed at anytime from any source outside your FS, you will need to have a way to detect this changes and say to the kernel dokan that current cache should be reset to update the remote changed otherwise you would use old files/data.
OFC this is not a reason to not to add it on Dokan, just that it has to be well thought to handle such case and give access to the developers a way to notify external changes.

**Comment by Liryna** [comment]
Hi @sefai ,

Do you plan to make a PR with the fix you made ?

**Comment by sefai** [comment]
Dear Liryna, I can do it next week.



iPhone'umdan gönderildi

Liryna <notifications@github.com> şunları yazdı (4 Haz 2017 22:53):

**Comment by Rondom** [comment]
Does this fix GIT on win-SSHFS?
https://github.com/Foreveryone-cz/win-sshfs/issues/108
More analysis here which points to a Dokan-issue:
https://github.com/git-for-windows/git/issues/1143#issuecomment-297710884

**Comment by Liryna** [comment]
Does this was not releated to https://github.com/dokan-dev/dokany/issues/369 ?
