### ISSUE TITLE
Cooperation with Project Cameleonica

### ISSUE THREAD

**Issue by arekbulski** [dokan-dev/dokany#42]
![3a](https://cloud.githubusercontent.com/assets/5385838/9205941/4c84aa34-4065-11e5-8165-d26eae5019ec.png)

I should mention that me being active in this project is not entirely without self interest. I started a prototype project for a radically new, versatile filesystem called Cameleonica. If it gains traction then dokan will be of interest to me. 

I would like to establish some official cooperation between our endeavors. I submitted a heavy set of changes to your wiki, code comments, and io site. I am happy to see that you accepted them. 

https://github.com/arekbulski/Cameleonica/blob/master/README.md

I am looking forward to having people review my ideas, especially from people that are not technical in this topic. Having external perspective is always helpful. If you would spend some time to read it, please post an Issue with your questions and remarks. I am looking forward to answering them.

**Comment by Liryna** [comment]
This seems to be a well structured start with a lot of good ambition ! Wish you the best !
I will follow it and do my best to help you :smiley:

**Comment by Maxhy** [comment]
I'm going to close this as it is not a real issue/feature request about Dokan.
Feel free to post it on the group instead for discussion. Thanks!
