### ISSUE TITLE
>1min hanging caused by kernel batch of timeouts after ~80 seconds

### ISSUE THREAD

**Issue by cdarau** [dokan-dev/dokany#420]
# Environment
 * Windows version: Windows 10 Enterprise N & Windows 8.1 Enterprise N
 * Processor architecture: x64
 * Dokany version: 1.0.1.1000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
This issue happens only when using 1 thread.

Prolonged hangings happen arbitrarily when I try to perform certain simple actions (it could be just opening an image with the Windows.Photos app, or opening a folder, or even right clicking on a file, or trying to choose the mounted drive when saving a file from the internet by a browser and so on). The scenario from the logs was produced when trying to open a picture. Other times when I tried to open the same picture it went well, but this one lasted for almost 1 minute and a half. It still opened correctly in the end, though...

Since I noticed 2 frequent patterns when this happen (at the end of Cleanup and CreateFile, when the call to SendEventInformation lasts for ~80 seconds), I enhanced the user-mode driver code locally with some 3 lines of logging, one before the call to SendEventInformation and 2 after. This portion look like this:
###Close 0164
###Create 0171
CreateFile status = 0
CreateFile before SendEventInformation - 48244 ms Wed Jan 18 00:07:51 2017
The thread 0x1a1c has exited with code 0 (0x0).
The thread 0xdd4 has exited with code 0 (0x0).
The thread 0x14f4 has exited with code 0 (0x0).
CreateFile after SendEventInformation - 130019 ms Wed Jan 18 00:09:13 2017
CreateFile SendEventInformation duration - 81775 ms
###Cleanup 0167

Also, the omologue portion kernel-wise ends in the following manner:
00056664	12:09:13 AM	[DokanFS] ==> ReleaseTimeoutPendingIRP	
00056665	12:09:13 AM	[DokanFS]  timeout Irp #2D7	
00056666	12:09:13 AM	[DokanFS]  timeout Irp #2D8	
00056667	12:09:13 AM	[DokanFS]  timeout Irp #2D9	
00056668	12:09:13 AM	[DokanFS]  timeout Irp #2DA	
00056669	12:09:13 AM	[DokanFS]  timeout Irp #2DC	
00056670	12:09:13 AM	[DokanFS]  timeout Irp #2DD	
00056671	12:09:13 AM	[DokanFS]   status = 0xc000009a	
00056672	12:09:13 AM	[DokanFS]   status = STATUS_INSUFFICIENT_RESOURCES

I attach below whole logs, accompanied by ProcMon log and custom-implementation log, just to have the entire image.

I also noticed in ProcMon that when this happens, there are a lot of CreateFile calls in pending. More important, before all of them there is always at least a certain FileSystemControl call with FSCTL_REQUEST_OPLOCK function, which is also pending those 80 seconds. When the FileSystemControl ends (always with result CANCELLED), then all of the CreateFile calls end as well and the hang/freeze stops.

As stated above, in the ProcMon logs, there could be seen 2 such FileSystemControl calls (both on the 00:07:50 second), which have the result CANCELLED. At run-time, these 2 were the ones pending, while the mentioned CreateFile operations situated below them were also pending. When these 2 ended with CANCELLED result, the execution resumed to normal behaviour.

# Logs
[dokany_usermode.txt](https://github.com/dokan-dev/dokany/files/712533/dokany_usermode.txt)
[dokany_kernelmode.txt](https://github.com/dokan-dev/dokany/files/712532/dokany_kernelmode.txt)
[procmon.txt](https://github.com/dokan-dev/dokany/files/712543/procmon.txt)
[implementation.txt](https://github.com/dokan-dev/dokany/files/712587/implementation.txt)

**Comment by Liryna** [comment]
Hi @cdarau ,

Can you test with the 1.0.2 (this could be also linked to "deadlock") ?
https://github.com/dokan-dev/dokany/releases/tag/v1.0.2

**Comment by Rondom** [comment]
Is there any news on this issue?

**Comment by Liryna** [comment]
@cdarau let me know if you face this issue again or if you have more informations.
