### ISSUE TITLE
When copy the same *.exe type file to the volume after delete it(error:Could not find this item)

### ISSUE THREAD

**Issue by noairman** [dokan-dev/dokany#422]
# Environment
 * Windows version: 10
 * Processor architecture: 64 bit
 * Dokany version: 1.0.1.1000
 * Library type (Dokany/FUSE): dokany/mirror
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
  **When I copy the exe file the volume ,and delete it ,then copy that file again to the same path, the error "Could not find this item".And it will occur every time when it's a .exe type file.but not the other type file.**
![error](https://cloud.githubusercontent.com/assets/10110303/22197710/28f3acf2-e18e-11e6-8a0b-d5f8f8e702b3.jpg)
    
  I don't know why this error happens when i delete the "*.exe" file and copy it again.This is the screenshot with the FileSpy.You can see the "STATUS_OBJECT_NAME_COLLISON" even if i already delete that file.and i can't catch the status in the CreateFile in the dokan library,so it might from the diver,the dokan sys .

![error1](https://cloud.githubusercontent.com/assets/10110303/22198017/8ff93ea2-e18f-11e6-9ad3-fe26074fcc12.jpg)
 
  From the log from Dokan sys,we can see that the normal file will free the FCB each time when the copy operation is done,but the exe type file the fcb->FileCount is 1 but not 0.

the normal zip file:
![error2](https://cloud.githubusercontent.com/assets/10110303/22198344/20a0e7a6-e191-11e6-824a-eca29da6a3d1.jpg)
the exe file:
![error3](https://cloud.githubusercontent.com/assets/10110303/22198421/76afc87e-e191-11e6-816e-cb5d1bb6dc34.jpg)
When InterlockedIncrement(&fcb->FileCount) ,log: FileCount++
When InterlockedDecrement (&fcb->FileCount) ,log: FileCount--

So when I delete it ,no matter how the  fcb->FileCount changes,it will increase to 1 at the end.And then I copy that file again,the "STATUS_OBJECT_NAME_COLLISON" occur in the DokanDispatchCreate,but the file was deleted,so the error occurs "Could not find this item".
(But **sometime** when I delete the "*.exe" file with other type file ,like the zip file ,the fcb->FileCount can be decrease to 0 ,then the copy file will be OK,)

I just tested again with snapshot https://ci.appveyor.com/project/Maxhy/dokany/build/job/agb6c7hl09nh9ch7/artifacts
and got  the same issue   @Liryna 

# Logs
[mirror output.txt](https://github.com/dokan-dev/dokany/files/725577/mirror.output.txt)
[kernel.txt](https://github.com/dokan-dev/dokany/files/725578/kernel.txt)

**Comment by marinkobabic** [comment]
You have this issue only using exe files or also with other file types? What I could imagine is that antivirus software has an handle open to this file. You can verify this when you use the tool process explorer https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx and in the menu find handle you search for your exe file. Another option is to use WinDbg : !handle Command

**Comment by noairman** [comment]
This issue only using exe files，and I close the antivirus software,and do not find that exe file on the  tool process explorer menu.And if I change the exe file to a different type,for instance,the rar type,I can copy that file again after i delete it.
    I tried on another computer with the antivirus software closed,the exe file type still has that issue.As the log shows,I think fcb->FileCount may go wrong,but i can't find exactly why.Could you please check the log or  try to reproduce the issue in your computer.Thanks. @marinkobabic

**Comment by marinkobabic** [comment]
@noairman 
I have tested your issue and it can be reproduced on my virtual box. The difference between a normal file and an exe file is that explorer does CreateFileMapping for the exe file additionally. This explains the behavior. You can check this in the sysinternals tool filemonitor. 

In my opinion the IRP_MJ_CLOSE is not done for the file and the FileCount remains high. When you copy the new file in, the deleted fcb is found in the list and because of the FileCount not being zero you will get the STATUS_OBJECT_NAME_COLLISION https://github.com/dokan-dev/dokany/blob/master/sys/create.c#L741

So the issue must be investigated. Why is the IRP_MJ_CLOSE is not executed? You could try to add the following code here https://github.com/dokan-dev/dokany/blob/de4e1408c498b069ada734d0ca9b5c2de501d14d/sys/cleanup.c#L90

if( fileObject->SectionObjectPointer.ImageSectionObject )
    MmFlushImageSection( &fcb->SectionObjectPointers, MmFlushForWrite );

Additionally the result of https://github.com/dokan-dev/dokany/blob/de4e1408c498b069ada734d0ca9b5c2de501d14d/sys/cleanup.c#L92 CcPurgeCacheSection should be checked and logged if FALSE

@Liryna 
The code above should be added anyway.

**Comment by Liryna** [comment]
Hi @marinkobabic ,

Does adding MmFlushImageSection fix the issue ?
I will make the changes tomorrow. Thanks to look at this 👍 !

**Comment by marinkobabic** [comment]
Have no idea because I actually have no access to my machine.

**Comment by marinkobabic** [comment]
This should fix the issue https://github.com/dokan-dev/dokany/pull/428

**Comment by Liryna** [comment]
PR of @marinkobabic fix correctly the issue 👍 
Thanks a lot as always ❤️ !
