### ISSUE TITLE
used in encfs4win - mounted drive not indexable by windows search

### ISSUE THREAD

**Issue by Giuse69** [dokan-dev/dokany#43]
Hi, dokan/dokany is used in encfs4win but there is a problem: the mounted drive is not seen by indexing service of windows so its content is not fast-searchable.
I don't know if it is a limit of how encfs4win uses dokany or it is not yet a supported feature of dokany, in the latter case this issue is to possibly ask for it.
cheers

Giuse

**Comment by Liryna** [comment]
encfs4win seems to be unstable #36 for now and need a review.
If you have the possibility to maintained it, it would be great !

**Comment by Owyn** [comment]
another encfs windows port using Pismo File Mount instead of Dokany has the same problem btw

**Comment by Liryna** [comment]
Sorry my bad, didn't get it at first.

We are using reparse point for mounting dokan driver.
It seems that windows does not enable indexing for reparse point.
https://social.technet.microsoft.com/Forums/windowsserver/en-US/d8c9c5b1-fc38-476d-a780-e14910edcf6f/widows-search-not-working-with-data-deduplication?forum=winserverfiles

**Comment by Giuse69** [comment]
Exactly, if reparse points are used, no chance of having windows indexing...
@Owyn: the other port you mention is encFSMP that does not show the problem in Windows 7 but it does in Windows 10, so I am hoping that can be fixed... I opened a ticket for that.
No plans of getting rid of reparse point in Dokany..?
Cheers

**Comment by Liryna** [comment]
It is the base of dokan :smile:
