### ISSUE TITLE
CreateFile erroneously returns SHARING VIOLATION

### ISSUE THREAD

**Issue by cdarau** [dokan-dev/dokany#432]
# Environment
 * Windows version: Windows 10 Enterprise N
 * Processor architecture: x64
 * Dokany version: 1.0.2.1000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

There are only 4 commits made after v1.0.2 tag: first 2 of them are doc editing, the 3rd one fixes a deadlock issue in cleanup and the 4th one edits the appveyor yml file => so I haven't tested with the latest snaptshot but it wasn't necessary.

# Description
If I lock a portion of a file, all subsequent CreateFile's operations with "Generic Read" desired access will get SHARING VIOLATION, until I close the handle. I'm not using custom (user-mode) locks. The code that I use to lock is LockFileEx windows function with 0 flags (that means the lock is not exclusive), some offset and some length. The code that I use to unlock is UnlockFileEx windows function with the same offset and length params. Strange is that even though I unlock the respective portion of the file, I still get the same error for each CreateFile, until I close the handle, as I wrote above.

# Logs
I don't have any library/kernel logs and the mirror log doesn't show anything relevant since the error is returned from the library/kernel levels (the mirror's CreateFile callback returns only 0 and some justified unrelated instances of STATUS_OBJECT_NAME_INVALID and STATUS_OBJECT_NAME_NOT_FOUND).

**Comment by Liryna** [comment]
Hi @cdarau ,

Do you any sample that can make us able to reproduce the issue with the mirror ?

**Comment by cdarau** [comment]
Hello @lyrina,

It didn't reproduce? I didn't do nothing special other than specified above. So:

1. mount a folder with mirror (no user-mode locks option)
2. I used the sample from the link: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365204(v=vs.85).aspx
3. I slightly modified a bit in order to grab params from program arguments, to eliminate file deletion at the end and to wait 10 or so seconds between locking and unlocking
4. when you run it you will see that after the lock returns successfully, you won't be able to open the file in an editor, ProcMon capturing a SHARING VIOLATION response to a CreateFile request done with Generic Read desired access, until the handle is closed (last lines of the sample)

Hope it helps

**Comment by Liryna** [comment]
If you try with `DOKAN_OPTION_FILELOCK_USER_MODE` does it change the behavior ?

**Comment by cdarau** [comment]
No. In fact, when I noticed this behaviour for the first time it happened with this option in place. Only after that I tried without it and with the mirror.

**Comment by cdarau** [comment]
Hello again @Lyrina

Do you have any feedback on this also? Thank you very much.

**Comment by Liryna** [comment]
A lot have changed around the sharing violation. I will close this for now. If anyone can reproduce it with latest version. I can reopen this.
