### ISSUE TITLE
FUSE-mirror goes into endless loop when writing file

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#434]
# Environment
 * Windows version: Windows 2016
 * Processor architecture: x64
 * Dokany version: 1.0.2.1000
 * Library type (Dokany/FUSE): FUSE
 
# Check List
  - [ x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ x ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [  ] I can always reproduce the issue with the provided description below.
  - [ x ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [  ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
1. Open a Cygwin64-Terminal, run the fuse_mirror `/cygdrive/c/Program\ Files/Dokan/Dokan\ Library-1.0.?/sample/fuse_mirror/mirror.exe -d -f M:`
2. Open a Windows-CMD prompt, run `echo foo > M:\tmp\bar`

Expected: Command succeeds, file is created
Actual: Command, hangs. FUSE-Mirror-Log is looping the same messages over and over.

(I encountered a BSOD once when trying to unmount the volume via dokanctl while it was looping once. I could not reproduce this so far. :-( Analyzing the dump fails due to memory corruption (or I am too stupid to use WinDbg))

# Logs
* [fuse_mirror_log.txt](https://github.com/dokan-dev/dokany/files/752853/fuse_mirror_log.txt)

# Support
 - Usage: personal - testing
 - Support ability: <programming C, can create pull request>

**Comment by Rondom** [comment]
This seems to be some kind of race. It occurs only in around 80% of the cases.

**Comment by Liryna** [comment]
Hi @Rondom ,

Thats very strange behavior to get a flood of read 😮 like if he was expecting to get something.
Maybe the write is not happening and there is no "foo" ?

**Comment by Rondom** [comment]
The initial test where I encountered the issue was with 1.0.2. I tested with 1.0.1 today and I did not manage to reproduce it.

**Comment by Rondom** [comment]
I tried to reproduce it with  [build 1.0.1.0784](https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.1-784/job/3n94ftdsdbc6cgnq/artifacts) from 4f1d82fe80b574d81dabb59debcfbf1972e4e4b1 ==> Could not reproduce it.

I also tried to reproduce it with the [latest build 1.0.2.1130](https://ci.appveyor.com/project/Maxhy/dokany/build/job/n1yr9mmwj8464x05/artifacts). I could not reproduce it either....

TODO: Install release 1.0.2 again and try to reproduce again. If I can reproduce it there, reproduce with the Appveyor-built 1.0.2.

**Comment by Rondom** [comment]
I tried with release 1.0.2 again and I could NOT reproduce it, either.
Maybe my instructions above are not detailed enough and my memory is not detailed enough?

@Liryna If you want, you can close the bug or you can can leave it open. Whatever you think makes more sense. I tried very hard to reproduce it with the version I initially encountered this with and I could not reproduce it.

**Comment by Liryna** [comment]
@Rondom I never tried to reproduce for now but when I saw it I was impressed that it was never reported before.
If you are sure not to be able to reproduce, I think you can close it for now and we will reopen if someone face the same issue.

(For information, I tried to release 1.0.3 today but Microsoft seems to have their server for sign drivers not working....)
