### ISSUE TITLE
Can't uninstall dokany from the command line

### ISSUE THREAD

**Issue by voltagex** [dokan-dev/dokany#44]
Here's an interesting one for you. It's really quite difficult to uninstall Dokany from the command line. I have a Windows Server Core install that I'm using to test the BSOD bug and now I can't remove Dokan.

Does the RC4 installer support any command line switches?

**Comment by voltagex** [comment]
It looks like DokanUninstall.exe was never created/installed. This leaves the Dokan install in a completely broken state - the installer will not allow a reinstallation.

**Comment by Liryna** [comment]
We are using NSIS (Nullsoft Scriptable Install System) as system to create Windows installers.
http://nsis.sourceforge.net/Main_Page

If I have never faced such issue and I cannot do much about it.
I can only redirect you to them about the bug that you describe.

For command line options:
http://nsis.sourceforge.net/Which_command_line_parameters_can_be_used_to_configure_installers

**Comment by Liryna** [comment]
@voltagex `DokanUninstall.exe was never created/installed`
Did you check in `$PROGRAMFILES32\Dokan\DokanLibrary\` ?
Even for 64bit the ``DokanUninstall.exe` is in `C:\Program Files (x86)`

Sometimes the uninstaller cannot remove dokan.sys because currently use. if you delete it you should be able to reinstall.

**Comment by voltagex** [comment]
Yeah, I worked this out after looking at the NSIS file. I can't reproduce
this error at the moment but I think it happens if you don't have the VC++
redist install and you click OK through the prompt

**Comment by marinkobabic** [comment]
The installer of dokan should be extended and deploy the VC++ redist. This way nobody would face this problem anymore.

**Comment by Liryna** [comment]
The installer propose to open the web page for downloading install the VC++ redist.
But I agree that including it would be better. Last time I checked, doing this was making the config file very ugly.

**Comment by Maxhy** [comment]
I just update NSIS script to optionally embed VC++ redistributable.
On next releases we will provide two installers:
 * DokanInstall_0.x.x.exe which is around 700KB and doesn't embed VC++ redistributable. If VC++ runtime is missing it will open MS webpage
 * DokanInstall_0.x.x_redist.exe which is around 14MB and embed VC++ redistributable. If VC++ runtime is missing it will be silently installed
