### ISSUE TITLE
Unable to set execute file permission flag

### ISSUE THREAD

**Issue by Stellar92** [dokan-dev/dokany#455]
# Environment
 * Windows version: 7
 * Processor architecture: x64
 * Dokany version: 1.0.2
 * Library type (Dokany/FUSE): dokany
 
# Check List
  - [ ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

When copying a file from windows to a remote drive on a linux server mounted with dokan, the file permissions are always set without the execution flag. For example it will be -rw-rw-r-- . I would like the permission to be set by default to -rwxrwxr-x .

I coudln't find any option to set it. Can you please help ?

**Comment by Rondom** [comment]
I am not sure, I understand your setup correctly. Can you describe it a bit more in detail (commands, software used)?
What do you mean by "linux server mounted with dokan"?

Are you sure that the behavior is specific to Dokan? I am not very familiar with Windows ACLs. I remember copying a non-executable file from a Samba share to my local harddisk using Explorer and it did not retain the permission i.e. I could execute the copied file.

**Comment by Stellar92** [comment]
Hello,

To explain a little more:

1 linux server pc (mageia 5.1) with sshd
1 windows 7 x64 client pc using either:
- latest dokan lib & winssh fs frontend from foreveryone-cz
- latest dokan lib and dokany frontend
A linux rep is mounted as a drive on the windows PC
Note: the server sshd pam_umask.so is set to 0002

Under windows, when I copy some data on the mounted drive, ALL files permissions are set to -rw-rw-r-- , and all directories set to drwxrwxr-x.
This ok for the directories, but NOT for the files, as some of them are linux progs or batchs. I would requite a default permission to -rwx-rwx-r-x instead, for all files, even those non executable.
I don't want to chmod them (with a server shell) to 775 each time I copy a file.
Furthermore if I edit a file on the mounted drive under windows, all "x" permissions are removed. Most probably the program creates a new file version, delete the old one and rename the new one).

I agree that samba allows you not only to set umask, but also force permissions (force create mode parameter in smb.conf). There is no such function with sshd, as only umask is parametrable.
So if win sshfs / dokan sets the file permission without "x", there is no way to force it on server side :-(

To conclude, if dokan could set up by default the "x" execute perm for both directories AND files it would solve my problem !

Thanks,

**Comment by Liryna** [comment]
Hi @Stellar92 ,

Dokan is the library to be able to mount whatever as filesystem on windows.
winssh fs frontend from foreveryone-cz control what is shown in the FS and what are the attributes on Linux side for the new files.

I think you should open an issue on their side if this is not already made. We can do nothing here 😢

**Comment by Stellar92** [comment]
Hi Liryna,

Thanks for your reply. I understand your point. Indeed I already raised the issue to the dokan team on github. Let's see if they can do something...

Regards,

**Comment by Liryna** [comment]
You have open a new issue at the correct place: https://github.com/Foreveryone-cz/win-sshfs/issues/137
Feel free to comment if there is changes needed in dokany.

**Comment by Rondom** [comment]
Some lines were accidentally changed and have [indentation issues](https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.2-110/job/61cfq7bmx80edq0e/messages). Click the message to see details of the (suggested) changes

**Comment by Liryna** [comment]
@Rondom wrong thread ❤️ i guess
