### ISSUE TITLE
File gets deleted from directory listing although the delete operation fails due to SHARING_VIOLATION error

### ISSUE THREAD

**Issue by cdarau** [dokan-dev/dokany#456]
# Environment
 * Windows version: Windows 10 Enterprise N
 * Processor architecture: x64
 * Dokany version: 1.0.2.1000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
This is very easy to reproduce:
1. drag&drop any file to the mounted drive
obs: the file should be large enough in order for the operation to take some time
2. during the copy, refresh the directory in which you dragged&dropped the file
obs: the file will appear
3. try to delete it
4. you will be asked if you're ok with it
5. answer "yes"
6. the file dissapears from the listing, although an error prompt will appear which will inform the user that the delete operation can't take place

By comparing this scenario with what the Windows file system is doing in the same situation, I observed that when trying the same thing in Windows, the user doesn't get asked if he's ok to delete the file; instead, the error prompt appears thus not letting the user to allow an operation that can't take place anyway.

# Logs
I don't have any logs for this, sorry.

**Comment by Liryna** [comment]
Hi @cdarau ,

You mean that here we should have a SHARING_VIOLATION directly when user try to remove the file and not to propose him if he want remove it (that is happening now) ?

**Comment by cdarau** [comment]
Hello @Liryna ,

I'm not sure where the mirror gets it wrong. I attached some logs. The zip format for uploading didn't work so I had to put a .txt extension for both .PML and .CSV files that are produced by ProcMon.

From what I can observe, the 2 scenarios go line by line. The first CreateFile that gets SHARING_VIOLATION is the same in both cases. After that, it pour some more CreateFile that also get SHARING_VIOLATION in both scenarios. A single thing caught my attention though: there's a particular CreateFile in the mirror scenario that doesn't appear in the Windows scenario. It's a CreateFile that gets SUCCESS and after that it's succeeded by a call to QueryFileInternalInformationFile that is missing from the Windows scenario. This particular inquiry seems lost among the rest of the calls to CreateFile that all get SHARING_VIOLATION.

I hope this helps.

[MirrorLogfile.txt](https://github.com/dokan-dev/dokany/files/793365/MirrorLogfile.txt)
[ProcMonWindowsLogfilePMLExtension.txt](https://github.com/dokan-dev/dokany/files/793377/ProcMonWindowsLogfilePMLExtension.txt)
[ProcMonWindowsLogfileCSVExtension.txt](https://github.com/dokan-dev/dokany/files/793378/ProcMonWindowsLogfileCSVExtension.txt)
[ProcMonMirrorLogfilePMLExtension.txt](https://github.com/dokan-dev/dokany/files/793375/ProcMonMirrorLogfilePMLExtension.txt)
[ProcMonMirrorLogfileCSVExtension.txt](https://github.com/dokan-dev/dokany/files/793376/ProcMonMirrorLogfileCSVExtension.txt)

**Comment by Liryna** [comment]
A lot have changed around the sharing violation. I will close this for now. If anyone can reproduce it with latest version. I can reopen this.
