### ISSUE TITLE
can add -u option (UNCName) for dokan fuse ?

### ISSUE THREAD

**Issue by gang929** [dokan-dev/dokany#461]
can add -u option (UNCName) for dokan fuse ? so, Dokanfuse can  mount a virtual disk as network drive!

add some dokanfuse option like as below
FUSE_LIB_OPT("-u", uncName, ""),
or 
FUSE_LIB_OPT("volname=%s", uncName, 0),

**Comment by Liryna** [comment]
Hi @gang929 ,

Does this would be alright for you ?
https://github.com/dokan-dev/dokany/commit/f1fb73c7316b8bdda81024d87283614a24f5a268

Tell me if it is ok, work on your side and I will merge it.

**Comment by Rondom** [comment]
Can one create a Dokan network "share" without mounting it as a drive? If so, how would I do this with FUSE?

**Comment by Liryna** [comment]
by network "share" you mean UNC like \\\localhost\myDokan ? or like the mirror when you use `/n` ?
In any case, for having UNC, you need to have the network option enabled.

Fuse network: `-n`
UNCName: `-o uncname="\localhost\myDokan"`

**Comment by gang929** [comment]
Liryna, yes,  your patch f1fb73c is so good!!!!

**Comment by Liryna** [comment]
👍 @gang929 this has been merged https://github.com/dokan-dev/dokany/commit/bd31f0f756300ed2b35ab8a75779348b6bb33da4
