### ISSUE TITLE
Support for Windows 10 long paths

### ISSUE THREAD

**Issue by antiufo** [dokan-dev/dokany#464]
Windows 10 has removed the `MAX_PATH` limit for Win32 applications that declare to support long paths.
If an attempt is made to open a file on a Dokan file system with a very long path, Explorer says "The data area passed to a system call is too small." (while it works if it's on plain NTFS).

Note: I performed the test using a .NET dokan file system. The native `mirror.exe` crashes if an attempt is made to access a very long path.

# Environment
 * Windows version: Windows 10 1607 (14965.1001)
 * Processor architecture: x64
 * Dokany version: 1.0.2
 * Library type (Dokany/FUSE): Dokan .NET
 
# Check List
  - [X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [X] I can always reproduce the issue with the provided description below.
  - [X] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

**Comment by Liryna** [comment]
Hi @antiufo ,

Yes, it is right that MAX_PATH is still sometimes used when managing file path.
This should be changed 👍 Do you think you can make a PR to fix this ?

**Comment by antiufo** [comment]
I looked at the source code and `MAX_PATH` seems to be mostly used for buffer sizes. What do you think about replacing it with 32,768, which seems to be the maximum length (?) for long paths? (Provided that this doesn't cause performance/memory problems)

**Comment by Liryna** [comment]
I looked in sys project, it is not used 👍 but in dokan project there is one  `MAX_PATH`  used for file:
https://github.com/dokan-dev/dokany/blob/de4e1408c498b069ada734d0ca9b5c2de501d14d/dokan/setfile.c#L161

The mirror use a lot of MAX_PATH for GetFilePath
```
  WCHAR filePath[MAX_PATH];

  GetFilePath(filePath, MAX_PATH, FileName);
```

GetFilePath could be changed to allocate a buffer of the proper size but, since it is only an example, I think a custom MAX_PATH with 32768 should also be good 👍 

Tell me if I missed something here.

**Comment by antiufo** [comment]
Ok so:
* `dokan1.dll` and the driver don't seem to have any problems with very long paths
* `mirror.exe` crashes because its own buffer is too small
* In Dokan.NET, path components longer than 256 are trimmed because of how `rawMaximumComponentLength` is [configured](https://github.com/dokan-dev/dokan-dotnet/blob/master/DokanNet/DokanOperationProxy.cs#L960)

**Comment by Liryna** [comment]
:+1: exact

If you replace `MAX_PATH` by `DOKAN_MAX_PATH 32768` in the mirror, does is still crash on your side ?
(otherwise that a rename that expect to crash regarding https://github.com/dokan-dev/dokany/blob/de4e1408c498b069ada734d0ca9b5c2de501d14d/dokan/setfile.c#L161

**Comment by antiufo** [comment]
No, it doesn't crash anymore.
At least in Windows 10 build 14965, long paths can be enabled with a group policy. Additionally, the manifest of the exe must declare its support for this feature. I know that Powershell has that flag enabled. For .NET apps, it's configurable from `App.config` (`UseLegacyPathHandling`, `BlockLongPaths`).

**Comment by Liryna** [comment]
Thank you for the information 👍 and for the report @antiufo 
I added optional define for the mirror and fixed the rename:
https://github.com/dokan-dev/dokany/commit/185120bd8b509372e66db6e44d2fe0a196b0b333
https://github.com/dokan-dev/dokany/commit/e13068d445b28403f11b49a4bacbcaba3b4bcba3
