### ISSUE TITLE
Need Help with migration from older dokan SetEndOfFile problems

### ISSUE THREAD

**Issue by kubinator** [dokan-dev/dokany#470]
Hello, guys.

I'm new here but I really need help.
I tried to migrate my Windows application from dokan 0.6 to version 1 (dokan-master).
I've downloaded sources, library and driver were compiled correctly. dokan_mirror works fine.
But in my app I get "INVALID ARGUMENT" errors constantly when my callbacks for Dokan's SetEndOfFile are invoked. 
I'd appreciate any possible help.

**Comment by Rondom** [comment]
I don't know about your particular problem, but there is a wiki page with some info. Are you returning `NTSTATUS` errors?
https://github.com/dokan-dev/dokany/wiki/Update-dokan-legacy-application-to-Dokany

Should this problem turn out to be something common amongst migrations from legacy Dokan, we can add it to that wiki page.

**Comment by kubinator** [comment]
Thank you, Rondom
Yes, I am returning NTSTATUS errors. I've read this wiki page and it really helped to solve compillation level problems. But it does not help with new runtime errors though((

**Comment by marinkobabic** [comment]
Did you compare your code with mirror. What is the difference? You need to
provide some code here if you need some assistance. You are absolutely sure
that it is this callback causing the issue?

Am 03.03.2017 18:10 schrieb "kubinator" <notifications@github.com>:

**Comment by Liryna** [comment]
@kubinator can this be closed ?

**Comment by kubinator** [comment]
Yes, this can be closed. I've found my mistakes.

**Comment by Liryna** [comment]
Thank you 👍
