### ISSUE TITLE
Signing script outputs (harmless?) error-msgs during FSTest

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#474]
* https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.2-132/job/06x23bgl4c6t0s5o#L628
* https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.2-132/job/06x23bgl4c6t0s5o#L728
* Is the `*.dlls` instead of `*.dll` intended here?  https://github.com/dokan-dev/dokany/blob/56995eda7b78203c3cb1cf282ac80867dd41cfd8/sign.ps1#L1

**Comment by Liryna** [comment]
Hi @Rondom ,

I fixed the script by creating all folder in any cases (not the most pretty but still better that a couple of if path following).
https://github.com/dokan-dev/dokany/commit/fa75db37fe2a6e9a02c0a717bf981e518f7c165f

Also well found for the dlls 👍 😄
