### ISSUE TITLE
Enumerate Alternative Streams

### ISSUE THREAD

**Issue by Maxhy** [dokan-dev/dokany#48]
Alternative Streams are supported on Dokan but not their enumeration.
This is originally reported on https://code.google.com/p/dokan/issues/detail?id=290&start=200

We should create a new routine on DokanOperations to pass the request to user FS and handle it properly.

**Comment by Maxhy** [comment]
I just added it with a new EnumerateNamedStreams callback on DokanOperations (because of that next Dokan release will be 0.8.0).

mirror.c sample was updated to implement this callback as an example.
You can easily try on mirror using the following DOS commands on your volume:
```
echo test1>>myfile.txt:stream1
echo test2>>myfile.txt:stream2
dir /s
```

Do not forget to set DOKAN_OPTION_ALT_STREAM on DokanOptions to enabled alternative stream on your FS.

**Comment by kenjiuno** [comment]
Hi.

I'll see the changes, when the next release will be launched!
