### ISSUE TITLE
BSOD on release1.0.2 when fstortute test utility is used

### ISSUE THREAD

**Issue by andreyloktev** [dokan-dev/dokany#483]
# Environment
 * Windows version: Windows 10 Enterprise 1607
 * Processor architecture: x64
 * Dokany version: 1.0.2
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

There are several problems when a test utility fstorute( in attachments ) is used:
1) When mirror.exe is launched with arguments /r C:\dorkan /l E:\ /t 1 /s /d then fstorture is failed
2) When mirror.exe is launched with arguments /r dokan /l letter /t 5 /s /d then BSOD is happend

fstorture.exe is launched in both cases with arguments E:\root1_1 E:\root2_2 10 nohardlinks nosoftlinks -v -c 10000 ( or you can use powershell script wrapper in attachments )

# Logs
I were not able to upload dump, fstorture.exe and logs here so you can download them on google drive: https://drive.google.com/open?id=0BxgWEqB7RUd-QnM5X29xQUNJdDQ
bsod dump for release version of the Dokan1.sys

**Comment by marinkobabic** [comment]
Please use the version 1.0.3 for your tests. You should not be able to reproduce the BSOD with the actual version.

**Comment by andreyloktev** [comment]
Hello @marinkobabic 
Unfortunately BSOD reproduces on the new version with the same error code if launch fstorture from the command line. If launch powershell script( from the link ) then deadlock appears. Dump file is uploaded on the google drive

**Comment by marinkobabic** [comment]
Here the details about the issue

UNEXPECTED_KERNEL_MODE_TRAP (7f)
dokan1!DiskDeviceControl+0x9c4 [e:\islog\dev\app\dokan\dokany\sys\device.c @ 290]

STACK_COMMAND:  kb

CHKIMG_EXTENSION: !chkimg -lo 50 -d !nt
    fffff800e5ac9387-fffff800e5ac9389  3 bytes - nt!ExFreePoolWithTag+387
	[ 40 fb f6:00 64 c8 ]
3 errors : !nt (fffff800e5ac9387-fffff800e5ac9389)

MODULE_NAME: memory_corruption
IMAGE_NAME:  memory_corruption
FOLLOWUP_NAME:  memory_corruption
DEBUG_FLR_IMAGE_TIMESTAMP:  0
MEMORY_CORRUPTOR:  LARGE
FAILURE_BUCKET_ID:  MEMORY_CORRUPTION_LARGE
BUCKET_ID:  MEMORY_CORRUPTION_LARGE
ANALYSIS_SOURCE:  KM
FAILURE_ID_HASH_STRING:  km:memory_corruption_large
FAILURE_ID_HASH:  {e29154ac-69a4-0eb8-172a-a860f73c0a3c}

This output does not really help. Tried to reproduce your issue on Windows 10 x86 but I had no BSOD. You can reproduce it on x86?

**Comment by marinkobabic** [comment]
No way to reproduce the BSOD on a fresh installed Windows 10 x64 Enterprise 1607

**Comment by blesliecan** [comment]
I am also getting a BSoD when running winfstest on a Windows 10 x64 machine.
Created an empty folder C:\dokan
Start mirror:  mirror.exe /r C:\dokan /l M:
Run test from: run-winfstest.bat . M:\test

Get BSoD when running the first test.

From dump I see:
033117-29890-01.dmp	2017-03-31 7:15:05 AM	UNEXPECTED_KERNEL_MODE_TRAP	0x0000007f	00000000`00000008	fffff801`a6383e70	ffffad00`44830f70	fffff801`a42af3a6	ntoskrnl.exe	ntoskrnl.exe+14e7c0					x64	ntoskrnl.exe+14e7c0					C:\WINDOWS\Minidump\033117-29890-01.dmp	8	15	14393	412,996	2017-03-31 7:19:28 AM

**Comment by blesliecan** [comment]
For what it is worth I also ran mirror in single thread mode with the same effect: BSoD.

I used the /d /s and did a redirect to a log but the log was trashed when the system crashed.

**Comment by marinkobabic** [comment]
Please upload your momory.dmp. You are using 1.0.3?

Am 31.03.2017 17:25 schrieb "blesliecan" <notifications@github.com>:

**Comment by blesliecan** [comment]
Yes I am using 1.0.3.


Do you really want me to upload a 1G memory dump? 
I am also not sure I want to place a memory dump from my machine in a public forum.

**Comment by Liryna** [comment]
@blesliecan There is minidump that is more little but enough for having more information

**Comment by blesliecan** [comment]
That makes more sense. :)


[033117-38359-01.zip](https://github.com/dokan-dev/dokany/files/886893/033117-38359-01.zip)

**Comment by marinkobabic** [comment]
There should be a mini memory dump which is not that big. Another option is
provide the stacktrace like documented here
https://msdn.microsoft.com/en-us/library/windows/hardware/ff538042(v=vs.85).aspx
You should ensure that you have set properly the symbol path.

Am 31.03.2017 22:04 schrieb "blesliecan" <notifications@github.com>:

**Comment by Rondom** [comment]
@blesliecan Something went wrong with your upload. Your zip-file is 22-bytes (but at least it has Phil Katz's initials at the beginning, so it is at least a ZIP-file :-D )

**Comment by Liryna** [comment]
@blesliecan the upload is invalid like @Rondom said. Do you think you can reupload this ?

**Comment by Liryna** [comment]
@blesliecan let us know if you have any information on the issue and I will reopen the ticket.
