### ISSUE TITLE
 Why library just ignore the return value when delete file failed 

### ISSUE THREAD

**Issue by noairman** [dokan-dev/dokany#486]
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

Cleanup.c
   when the delete file operation failed,the mirror did not return the error code ,and the library just ignore the return value.In this condition,there is nothing to do,and the user do not know it,but the file is not deleted.
  Why the library ignore the return value.Is there any better way to slove it?

**Comment by Liryna** [comment]
Hi @noairman ,

Cleanup always has to success. It is during DeleteFile / DeleteDirectory or CreateFile that you have to properly check if the file can be removed and that you are sure of it. That's the purpose of function DeleteFile / DeleteDirectory.
I understand that it is possible that delete fail during the cleanup on the fs side but cleanup is not the place to return an error for windows.

**Comment by noairman** [comment]
Hi @Liryna ,
Thanks,I know that we should make sure if we can delete the file in DeleteFile / DeleteDirectory ,but the delete failed once just during the cleanup.

**Comment by Liryna** [comment]
Hi @noairman ,

This is how windows work we cannot do something about it sorry.
DeleteFile / DeleteDirectory really need to make everything prepare for cleanup remove without issue.

**Comment by Rondom** [comment]
[Some document from Microsoft with more information](http://download.microsoft.com/download/4/3/8/43889780-8d45-4b2e-9d3a-c696a890309f/File%20System%20Behavior%20Overview.pdf) and [this discussion for some background](http://www.osronline.com/showThread.cfm?link=67122).
