### ISSUE TITLE
Archive mounter

### ISSUE THREAD

**Issue by antiufo** [dokan-dev/dokany#487]
Hi, I noticed that there are no archive mounters listed in the project homepage, so I decided to [write one](https://github.com/antiufo/Shaman.Dokan.Archive). It uses the 7zip library to read archives. Feel free to add it to the list, if you want.
Btw there's also a mounter for [WARC](https://github.com/antiufo/Shaman.Dokan.Warc) files.

**Comment by Liryna** [comment]
Hello @antiufo ,

Ah great to see on what you were working 👍 !!!
Congratulations for this two project 🏆 ! That really appreciate offering it to the open source community !

I just added both on dokan main pages 😃 
https://github.com/dokan-dev/dokan-dev.github.io/commit/dff5e2425cbcbe72e90bfbff121c6fe95886ed9d

I also let the issue open some days if you want.
