### ISSUE TITLE
Mirror opening File as Directory on Windows Share when Office Word 2010 Opening the file

### ISSUE THREAD

**Issue by yin19941005** [dokan-dev/dokany#488]
# Environment
 * Windows version (Client):  Windows 7
 * Windows version (Server):  Windows 10
 * Processor architecture: amd64
 * Dokany version: 1.0.2.1136 Snapshot
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
The Mirror would trying to open a file as directory when the Office Word 2010 Opening the file on Windows Share. This seems only happen on mounted the remote drive and the local drive doesn't seems get any error.

# Logs

> ###Create 0189
> 	eventInfo.SerialNumber = 4A3, eventInfo.Status = 0, origFileName = (null) CreateFile : \\192.168.200.18\share\
>   AccountName: VMBB-PC4, DomainName: VMBB-PC20-PC
> 	ShareMode = 0x1
> 	FILE_SHARE_READ
> 	DesiredAccess = 0x120080
> 	FILE_READ_ATTRIBUTES
> 	READ_CONTROL
> 	SYNCHRONIZE
> 	STANDARD_RIGHTS_READ
> 	STANDARD_RIGHTS_WRITE
> 	STANDARD_RIGHTS_EXECUTE
> 	FlagsAndAttributes = 0x0
> 	OPEN_EXISTING
> 	error code = 123
> 
> 
> CreateFile status = c0000033

This image show the mirror is trying to open as a file when GetFileAttributes returned 0x00000010 (FILE_ATTRIBUTE_DIRECTORY) .

![open_directory_as_file_issue](https://cloud.githubusercontent.com/assets/23186757/24596007/4c16b23a-186e-11e7-81a1-beaa6ac99eea.png)

**Comment by yin19941005** [comment]
This issue can be closed when #489 is merged.

**Comment by Rondom** [comment]
#492

**Comment by Liryna** [comment]
Hi @yin19941005 ,

This is fixed with https://github.com/dokan-dev/dokany/commit/ae79f1079cf2e669ea81721554e23b5303a782bd
and the correction to pass the test:
 https://github.com/dokan-dev/dokany/commit/c694747ec172759c0621fd188bccc65e779b18fe
