### ISSUE TITLE
FILE_NAMED_STREAMS flag

### ISSUE THREAD

**Issue by bailey27** [dokan-dev/dokany#490]
I noticed that MirrorGetVolumeInformation() never sets the FILE_NAMED_STREAMS flag, even when the underlying filesystem (e.g. NTFS) supports them.

It looks like Alternate Data Streams generally work.  Mirror passes all the streams tests in winfstest.

However, without this flag, if you copy or move a file with an alternate data stream on a mirror drive,  then you lose the alternate data stream, because the OS doesn't know that the fs supports streams.

Also, if you do set this flag, then you start getting weird paths with an extra backslash after the file name and before the stream specifier.

I mean like 

```
\foo\boo\foo.txt\:blah:$DATA
```

And these paths don't work unless you get rid of the backslash that's in front of the first colon.

I think GetFilePath() needs to take care of that.

I found this web site that has some tools for inspecting streams in files.

http://www.flexhex.com/docs/articles/alternate-streams.phtml

**Comment by Liryna** [comment]
Hi @bailey27 ,

Oh yes `FILE_NAMED_STREAMS` seems to be missing !
I guess the streams are currently working because windows kernel do not refuse stream request even if flag is missing but let the driver handle or not CreateFile for streams (like we are doing: https://github.com/dokan-dev/dokany/blob/d3b7927fbc68296f9c41228a3e5fabe322be0b2a/sys/create.c#L655-L661).
BUT having `FILE_NAMED_STREAMS` seems to be checked by some applications (like explorer here) to enable features (copy extra streams).

Do you know if the path `\foo\boo\foo.txt\:blah:$DATA` come from the kernel or it is dokan kernel that wrongly changed it ?

**Comment by bailey27** [comment]
I think maybe it's happening in the driver in create.c in DokanDispatchCreate() because of needBackSlashAfterRelatedFile.  I'm not sure why it thinks it needs to add a backslash in this case.

I only looked at the code.  I haven't confirmed this.

**Comment by bailey27** [comment]
It looks like that is it.

I think when the file is a normal file, not a stream, then the relatedFileName is the full path of the directory that the file is in, and  fileObject->FileName is the name of the file itself.

But when the file is a stream, then the relatedFileName is the full path to the file, and fileObject->FileName is the stream name.

If I change it like this, then copying and moving a file with an alternate data stream keeps the stream intact.

```
diff --git a/sys/create.c b/sys/create.c
index 4c4f7ed..42fa37d 100755
--- a/sys/create.c
+++ b/sys/create.c
@@ -645,7 +645,7 @@ Return Value:
       }
       if (relatedFileName->Length > 0 &&
           relatedFileName->Buffer[relatedFileName->Length / sizeof(WCHAR) -
-                                  1] != '\\') {
+                                  1] != '\\' && fileObject->FileName.Buffer[0] != ':') {
         needBackSlashAfterRelatedFile = TRUE;
         fileNameLength += sizeof(WCHAR);
       }
```

I am not 100% sure it won't break anything else, but it still passes winfstest (492/492).

**Comment by Liryna** [comment]
Hi @bailey27 ,

OK I see what you mean. To see if` `fileObject->FileName.Buffer[0] != ':'` will not create issues we can try to create a file starting with `:`.
`echo "" > ":lol.txt"`

Normally windows do not allow the character and on my side I have not been able to create a file. There is no error but nothing is created. Can you test on dokan what is the behavior (currently not having my env)

**Comment by bailey27** [comment]
With a modified mirror that sets the stream flag, and a modified driver with the colon check, when I do that I get an error message (in cmd.exe) and no file is created

```
The filename, directory name, or volume label syntax is incorrect.
```

On a normal windows drive, I get no error message, and no file is created.

**Comment by bailey27** [comment]
On the C: drive, it is actually succeding
```
C:\tmp>echo blah > ":lol.txt"

C:\tmp>dir
 Volume in drive C has no label.
 Volume Serial Number is 64CA-D724

 Directory of C:\tmp

04/05/2017  01:43 PM    <DIR>          .
04/05/2017  01:43 PM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  10,746,179,584 bytes free

C:\tmp>more < ":lol.txt"
blah
```

It looks like the blah goes into an alternate data stream named lol.txt in the current directory.  I mean the stream is a stream of the directory.

Do you think Dokany needs to support that?

**Comment by Liryna** [comment]
@bailey27 we should support it 😢 
There is not much documentation about named stream names that could help us unfortunately.
We can only try to reproduce the behavior we see.

**Comment by bailey27** [comment]
Ok, I will try to figure out why it doesn't work.

**Comment by bailey27** [comment]
It looks data streams attached to directories are working, if they are attached to a subdirectory and not the root dir.

```
C:\>echo blah > m:\blah:foo

C:\>echo blah > m:\:foo
The filename, directory name, or volume label syntax is incorrect.
```

The reason the CreateFile() in mirror fails is that when you try to open a stream of the root dir, you end up with a path like (my mirror root is c:\\tmp) "c:\\tmp\\:foo".  

It works in a subdir because their is now no trailing slash in front of the stream (e.g. "c:\\tmp\\blah:foo").

I did a quick fix in mirror to make it work.  Does it need to be fixed in the kernel driver?

I think the driver is the "right place" to fix it, but then I also think passing paths that look like simply ":blah" to user mode is sort of weird.

Here is what I changed in mirror

```
 static void GetFilePath(PWCHAR filePath, ULONG numberOfElements,
                         LPCWSTR FileName) {
+
+  // for if we're trying to open a file that's actually an alternate data
+  // stream of the root dircetory as in "\:foo"
+  if (wcslen(FileName) >= 2 && FileName[0] == '\\' && FileName[1] == ':') {
+         FileName++;
+  }
   wcsncpy_s(filePath, numberOfElements, RootDirectory, wcslen(RootDirectory));
   size_t unclen = wcslen(UNCName);
   if (unclen > 0 && _wcsnicmp(FileName, UNCName, unclen) == 0) {
```  


Also, you need admin privileges to write to a data stream on the root directory on C:.  

But if the mirror root is c:\ and mirror is run as admin, then anybody can do it.

**Comment by Liryna** [comment]
Thank you @bailey27 for the analyse !
I agree, the fix has to be in the kernel. The userland should always trust the file name provided and never need to touch it.

**Comment by bailey27** [comment]
This seems to work
```
diff --git a/sys/create.c b/sys/create.c
index 4c4f7ed..97cf018 100755
--- a/sys/create.c
+++ b/sys/create.c
@@ -459,6 +459,7 @@ Return Value:
   PWCHAR parentDir = NULL; // for SL_OPEN_TARGET_DIRECTORY
   ULONG parentDirLength = 0;
   BOOLEAN needBackSlashAfterRelatedFile = FALSE;
+  BOOLEAN alternateDataStreamOfRootDir = FALSE;
   ULONG securityDescriptorSize = 0;
   ULONG alignedEventContextSize = 0;
   ULONG alignedObjectNameSize =
@@ -645,10 +646,18 @@ Return Value:
       }
       if (relatedFileName->Length > 0 &&
           relatedFileName->Buffer[relatedFileName->Length / sizeof(WCHAR) -
-                                  1] != '\\') {
+                                  1] != '\\' && fileObject->FileName.Buffer[0] != ':') {
         needBackSlashAfterRelatedFile = TRUE;
         fileNameLength += sizeof(WCHAR);
       }
+      // for if we're trying to open a file that's actually an alternate data
+      // stream of the root dircetory as in "\:foo"
+      // in this case we won't prepend relatedFileName to the file name
+      if (relatedFileName->Length / sizeof(WCHAR) == 1 &&
+               relatedFileName->Buffer[0] == '\\' &&
+               fileObject->FileName.Buffer[0] == ':') {
+       alternateDataStreamOfRootDir = TRUE;
+      }
     }

     // don't open file like stream
@@ -671,7 +680,7 @@ Return Value:

     RtlZeroMemory(fileName, fileNameLength + sizeof(WCHAR));

-    if (relatedFileName != NULL) {
+    if (relatedFileName != NULL && !alternateDataStreamOfRootDir) {
       DDbgPrint("  RelatedFileName:%wZ\n", relatedFileName);

       // copy the file name of related file object
```

**Comment by Liryna** [comment]
Alright for me @bailey27 thank again 👍 you can create a pull request with the patch ❤️ (or you would like that I apply it myself ?)

**Comment by bailey27** [comment]
I'll do a pull request.
