### ISSUE TITLE
MirrorGetVolumeInformation

### ISSUE THREAD

**Issue by bailey27** [dokan-dev/dokany#491]
I noticed that MirrorGetVolumeInformation() is setting the MaximumComponentLength to 256.

But on NTFS it should be 255.  If I do GetVolumeInformation on my C: drive, that is what it returns.

I think MirrorGetVolumeInformation() should call GetVolumeInformaton() on the underlying fs and should copy the MaximumComponentLength from what is returned for the underlying fs.

I think it should also copy the name of the underlying fs instead of being hard-coded to copy "NTFS".

And I think it should also get the FileSystemFlags from the underlying fs and return the AND of those with the ones that are hard-coded there.

**Comment by Liryna** [comment]
Hi @bailey27 ,

Looks like even MaximumComponentLength  is currently ignored. I will try to look into this.
https://github.com/dokan-dev/dokany/blob/de4e1408c498b069ada734d0ca9b5c2de501d14d/dokan/volume.c#L62
Anyway this size is wrong if I can say because we support long file names https://github.com/dokan-dev/dokany/issues/464
But of course, we should set the proper value 👍 well found

>I think MirrorGetVolumeInformation() should call GetVolumeInformaton() on the underlying fs

We can but there is "probably" more options enabled that what dokan support. This should be tested but I agree with the idea to do this and comment on the current value as an example.

**Comment by Liryna** [comment]
@bailey27 Absolutely agree with your proposition ❤️ !

**Comment by Rondom** [comment]
> `FILE_CASE_SENSITIVE_SEARCH | FILE_CASE_PRESERVED_NAMES `

Can those be used in a sensible way to work around limitations on reparse points? #293

**Comment by Liryna** [comment]
@Rondom I just did a test and still having the names uppercase 😢

**Comment by bailey27** [comment]
I changed the default max component length from 256 to 255, and I made it call GetVolumeInformation().

If that succeeds, then returns the AND of the returned files system flags with mirror's default flags.

It returns the max component length as reported by the underlying fs, and also the file system name.

GetVolumeInformation() fails, then it returns the mirror defaults.

I also noticed that mirror wasn't checking the optional (at least optional in the Windows GetVolumeInformation() API) arguments for NULL.  It looks like it was always getting non-null before, but I put the checks there anyway.

Here is the diff

```
diff --git a/samples/dokan_mirror/mirror.c b/samples/dokan_mirror/mirror.c
index 3b6896e..b3de06a 100644
--- a/samples/dokan_mirror/mirror.c
+++ b/samples/dokan_mirror/mirror.c
@@ -1192,17 +1192,53 @@ static NTSTATUS DOKAN_CALLBACK MirrorGetVolumeInformation(
     PDOKAN_FILE_INFO DokanFileInfo) {
   UNREFERENCED_PARAMETER(DokanFileInfo);

+  WCHAR volumeRoot[4];
+  DWORD fsFlags = 0;
+
   wcscpy_s(VolumeNameBuffer, VolumeNameSize, L"DOKAN");
-  *VolumeSerialNumber = 0x19831116;
-  *MaximumComponentLength = 256;
-  *FileSystemFlags = FILE_CASE_SENSITIVE_SEARCH | FILE_CASE_PRESERVED_NAMES |
+
+  if (VolumeSerialNumber)
+    *VolumeSerialNumber = 0x19831116;
+  if (MaximumComponentLength)
+    *MaximumComponentLength = 255;
+  if (FileSystemFlags)
+   *FileSystemFlags = FILE_CASE_SENSITIVE_SEARCH | FILE_CASE_PRESERVED_NAMES |
                      FILE_SUPPORTS_REMOTE_STORAGE | FILE_UNICODE_ON_DISK |
                      FILE_PERSISTENT_ACLS | FILE_NAMED_STREAMS;

-  // File system name could be anything up to 10 characters.
-  // But Windows check few feature availability based on file system name.
-  // For this, it is recommended to set NTFS or FAT here.
-  wcscpy_s(FileSystemNameBuffer, FileSystemNameSize, L"NTFS");
+  volumeRoot[0] = RootDirectory[0];
+  volumeRoot[1] = ':';
+  volumeRoot[2] = '\\';
+  volumeRoot[3] = '\0';
+
+  if (GetVolumeInformation(volumeRoot, NULL, 0, NULL, MaximumComponentLength,
+        &fsFlags, FileSystemNameBuffer, FileSystemNameSize)) {
+
+    if (FileSystemFlags)
+      *FileSystemFlags  &= fsFlags;
+
+    if (MaximumComponentLength) {
+      DbgPrint(L"GetVolumeInformation: max component length %u\n",
+                 *MaximumComponentLength);
+    }
+    if (FileSystemNameBuffer) {
+      DbgPrint(L"GetVolumeInformation: file system name %s\n",
+                 FileSystemNameBuffer);
+    }
+    if (FileSystemFlags) {
+      DbgPrint(L"GetVolumeInformation: got file system flags 0x%08x,"
+          " returning 0x%08x\n", fsFlags, *FileSystemFlags);
+    }
+  } else {
+
+    DbgPrint(L"GetVolumeInformation: unable to query underlying fs,"
+               " using defaults.  Last error = %u\n", GetLastError());
+
+    // File system name could be anything up to 10 characters.
+    // But Windows check few feature availability based on file system name.
+    // For this, it is recommended to set NTFS or FAT here.
+    wcscpy_s(FileSystemNameBuffer, FileSystemNameSize, L"NTFS");
+  }

   return STATUS_SUCCESS;
 }
```

Here is some debug output.  I tried it on NTFS and FAT32

```
C:\git\dokany\x64\Debug>.\mirror.exe /d /s /r c:\tmp /l m 2>&1 | grep GetVolume
GetVolumeInformation: max component length 255
GetVolumeInformation: file system name NTFS
GetVolumeInformation: got file system flags 0x03e700ff, returning 0x0004000f

C:\git\dokany\x64\Debug>.\mirror.exe /d /s /r f:\tmp /l m 2>&1 | grep GetVolume
GetVolumeInformation: max component length 255
GetVolumeInformation: file system name FAT32
GetVolumeInformation: got file system flags 0x00020006, returning 0x00000006

```

It passes 492/492 in winfstest on NTFS.  

@Liryna , do you want me to do a pull request with this change?

**Comment by Rondom** [comment]
Thx, bailey. This was on my todo-list as well :-)

**Comment by Rondom** [comment]
> Anyway this size is wrong if I can say because we support long file names #464 

This is about individual file/directory names.

**Comment by Liryna** [comment]
@bailey27 thats looks perfect 👍 !!!
I pull request would be really great thank you ❤️ ❤️ ❤️

**Comment by bailey27** [comment]
@Liryna , I did the pull request.

**Comment by Liryna** [comment]
Thank you @bailey27 as always ! 🏆
