### ISSUE TITLE
dokanctl: UAC-Prompt even for non-priviliged operations on Win10, (works on Win7)

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#495]
# Environment
 * Windows version: Windows 2016, Windows 10 Anniversary
 * Processor architecture: x64
 * Dokany version: 1.0.3
 * Library type (Dokany/FUSE): irrelevant
 
# Check List
  - [ x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ x ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ x ] I can always reproduce the issue with the provided description below.
  - [ x ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ x ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

*Actual:*
When running `dokanctl.exe` without parameters it shows usage information. When running it in a non-admin-cmd-window on Win10 and Win2016 I get an UAC prompt. Due to how Windows works, this creates a new window for the elevated process, which makes it impossible to see the output, because the window quickly disappears.

*Expected:*

No UAC on listing mount point, show usage and print version when running dokanctl from an unelevated command prompt / PowerShell.

According to #311:
> Dokanctl no longer need admin permission for listing mount point, show usage and print version.

Indeed, this is true on Windows 7, but does not work on Windows 10.

**Comment by Liryna** [comment]
Hi @Rondom ,

Well found 👍 always testing in debug so never faced it 😢 
The vs project does not have the proper uac right set on even build type.
Fixed with: https://github.com/dokan-dev/dokany/commit/9ef806831b89cb5a07062051952eec2bfa1cda84
