### ISSUE TITLE
TRUNCATE_EXISTING not mapping correctly to user implementation

### ISSUE THREAD

**Issue by brunoklein99** [dokan-dev/dokany#497]
# Environment
 * Windows version: Windows 10 (10493.1066)
 * Processor architecture: 64bit
 * Dokany version: 1.0.3.1000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Calling CreateFile with `TRUNCATE_EXISTING` does not map correctly to Dokany user implementation.

# Steps to reproduce

1. Create an executable with the following snippet:

```
#include "stdafx.h"
#include <Windows.h>


int main()
{
	HANDLE hFile = CreateFile(L"m:\nonexistentfile", GENERIC_WRITE, 0, 0, TRUNCATE_EXISTING, FILE_ATTRIBUTE_NORMAL, 0);
	
	if (hFile = INVALID_HANDLE_VALUE)
	{
		DWORD lasterror = GetLastError();
	}

    return 0;
}
```
2. Start mirror `mirror.exe /r C:\Users /d /l M:`
3. Attach debugger
4. Run executable created in step 1
5. Debugger output will be same as bellow:
```
###Create 0010
CreateFile : C:\Users\
onexistentfile
  AccountName: klein-desk, DomainName: DESKTOP-520FBF9
	ShareMode = 0x0
	DesiredAccess = 0x120196
	FILE_READ_ATTRIBUTES
	READ_CONTROL
	FILE_WRITE_DATA
	FILE_WRITE_ATTRIBUTES
	FILE_WRITE_EA
	FILE_APPEND_DATA
	SYNCHRONIZE
	STANDARD_RIGHTS_READ
	STANDARD_RIGHTS_WRITE
	STANDARD_RIGHTS_EXECUTE
	FlagsAndAttributes = 0x80
	FILE_ATTRIBUTE_NORMAL
	OPEN_EXISTING
	error code = 123


CreateFile status = c0000033
```
Notice how it says `OPEN_EXISTING` instead of the expected `TRUNCATE_EXISTING`

# Logs

Logs are above.

---

Please let me know if information is insufficient.

Thank you.

**Comment by Liryna** [comment]
Hi @brunoklein99 ,

Thank you for the report.
I reproduce your test and got the same result. I enabled kernel debug to see how windows request us to open the file.
`CreateDisposition` requested by the kernel is equal to 1 (`FILE_OPEN` // `OPEN_EXISTING`). So the kernel do not request us to open as `TRUNCATE_EXISTING`

We correctly support the flag IF the kernel request us to open with it: https://github.com/dokan-dev/dokany/blob/1d8aa517ef86b3fbef6c6c8ac03257f9c4e5de2d/dokan/dokan.c#L924

Just after I created the file (since in the first test it was without the file exisitng):
```
###Create 0003
CreateFile : C:\Users\nonexistentfile
  AccountName: liryna, DomainName: DESKTOP-H41JCS5
        ShareMode = 0x0
        DesiredAccess = 0x120196
        FILE_READ_ATTRIBUTES
        READ_CONTROL
        FILE_WRITE_DATA
        FILE_WRITE_ATTRIBUTES
        FILE_WRITE_EA
        FILE_APPEND_DATA
        SYNCHRONIZE
        STANDARD_RIGHTS_READ
        STANDARD_RIGHTS_WRITE
        STANDARD_RIGHTS_EXECUTE
        FlagsAndAttributes = 0x80
        FILE_ATTRIBUTE_NORMAL
        OPEN_EXISTING

CreateFile status = 0
###GetFileInfo 0003
GetFileInfo : C:\Users\nonexistentfile
        GetFileInformationByHandle success, file size = 8

        result =  0
        FileStandardInformation
        DispatchQueryInformation result =  0
###GetFileInfo 0003
GetFileInfo : C:\Users\nonexistentfile
        GetFileInformationByHandle success, file size = 8

        result =  0
        FileBasicInformation
        DispatchQueryInformation result =  0
###GetFileInfo 0003
GetFileInfo : C:\Users\nonexistentfile
        GetFileInformationByHandle success, file size = 8

        result =  0
        FileStandardInformation
        DispatchQueryInformation result =  0
###GetFileInfo 0003
GetFileInfo : C:\Users\nonexistentfile
        GetFileInformationByHandle success, file size = 8

        result =  0
        FileInternalInformation
        DispatchQueryInformation result =  0
###GetFileInfo 0003
GetFileInfo : C:\Users\nonexistentfile
        GetFileInformationByHandle success, file size = 8

        result =  0
        FileStandardInformation
        DispatchQueryInformation result =  0
###SetFileInfo 0003  19
SetAllocationSize C:\Users\nonexistentfile, 0
        DispatchSetInformation result =  0
###Cleanup 0003
Cleanup: C:\Users\nonexistentfile

###Close 0003
Close: C:\Users\nonexistentfile
```

The kernel seems to anyway open with `OPEN_EXISTING` BUT call `SetAllocationSize` just after with size 0 to truncate the file.
Looks like it is the way how the kernel work.

**Comment by Liryna** [comment]
@brunoklein99 can this be closed ?

**Comment by brunoklein99** [comment]
Yes, thank you.
