### ISSUE TITLE
MirrorDeleteFile is never called

### ISSUE THREAD

**Issue by sefai** [dokan-dev/dokany#500]
# Environment
 * Windows version: Windows 8.1
 * Processor architecture:  64 bit
 * Dokany version: 1.0.3
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
When I delete a file using the mirror sample, **DeleteFile** in **MirrorCleanup** always returns error code 2 (**ERROR_FILE_NOT_FOUND**), **MirrorDeleteFile** is not called but the file is magically deleted from the mirror drive. This behaviour is persistent with all file deletions.

# Logs
File _New Bitmap Image.bmp_ is created and deleted right after...[mirror.txt](https://github.com/dokan-dev/dokany/files/955478/mirror.txt)

**Comment by Liryna** [comment]
Hi @sefai ,

DeleteFile in MirrorCleanup return error code 2 (ERROR_FILE_NOT_FOUND) because the file has been removed like expected during CloseFile since it has been opened with `FILE_FLAG_DELETE_ON_CLOSE`.

```
###Create 0428
CreateFile : C:\Users\johndoe\Documents\MirrorRoot\New Bitmap Image.bmp
  AccountName: johndoe, DomainName: NONE
	ShareMode = 0x4
	FILE_SHARE_DELETE
	DesiredAccess = 0x10000
	DELETE
	FlagsAndAttributes = 0x4000000
	FILE_FLAG_DELETE_ON_CLOSE
	OPEN_EXISTING

CreateFile status = 0
###GetFileInfo 0428
GetFileInfo : C:\Users\johndoe\Documents\MirrorRoot\New Bitmap Image.bmp
	GetFileInformationByHandle success, file size = 0

	result =  0
	FileStandardInformation
	DispatchQueryInformation result =  0
###GetFileInfo 0428
GetFileInfo : C:\Users\johndoe\Documents\MirrorRoot\New Bitmap Image.bmp
	GetFileInformationByHandle success, file size = 0

	result =  0
	FileStandardInformation
	DispatchQueryInformation result =  0
###Cleanup 0428
Cleanup: C:\Users\johndoe\Documents\MirrorRoot\New Bitmap Image.bmp

	DeleteOnClose
  DeleteFile  error code = 2

###Close 0428
```

Microsoft has two ways to delete a file: Open with `FILE_FLAG_DELETE_ON_CLOSE` or set delete flag with SetFileInformationByHandle after CreateFile (this is when MirrorDeleteFile is called to check if the delete is possible).

I hope I have answered your question. 👍

**Comment by Rondom** [comment]
So, does this mean I will have to do any checks whether delete file is possible both in ZwCreateFile and DeleteFile?

**Comment by Liryna** [comment]
Yes, will need to check during CreateFile especially if there is no sharing violation with possible other handle open on it.

**Comment by sefai** [comment]
@Liryna Thank you for the explanation. What will be the lightest way of handling this case in the user application? Can we safely assume the file is deleted successfully if the error returned from DeleteFile equals to ERROR_FILE_NOT_FOUND?

**Comment by Liryna** [comment]
If it return `ERROR_FILE_NOT_FOUND` yes we can assume that the file has been removed.
https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L436-L437
We are calling DeleteFile is case of it was not open with `FILE_FLAG_DELETE_ON_CLOSE`. The best would be to save the flag `FILE_FLAG_DELETE_ON_CLOSE` somewhere to know if we need to call DeleteFile in cleanup or not.

**Comment by Liryna** [comment]
If it return `ERROR_FILE_NOT_FOUND` yes we can assume that the file has been removed.
https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L436-L437
We are calling DeleteFile is case of it was not open with `FILE_FLAG_DELETE_ON_CLOSE`. The best would be to save the flag `FILE_FLAG_DELETE_ON_CLOSE` somewhere to know if we need to call DeleteFile in cleanup or not to skip the `ERROR_FILE_NOT_FOUND`.

**Comment by Liryna** [comment]
@sefai does this answer your question ?

**Comment by sefai** [comment]
Yes, thank you ver much @Liryna
