### ISSUE TITLE
Why does DokanLoop() open and close handle to driver in the loop?

### ISSUE THREAD

**Issue by bailey27** [dokan-dev/dokany#504]
Why does DokanLoop() keep opening and closing the handle to the driver in the loop?

It doesn't seem to hurt performance that much, but I wonder if it is necessary?

Also, it seems like it will close the handle a second time when it exits the loop.

Would this be better?

```
diff --git a/dokan/dokan.c b/dokan/dokan.c
index 376c8e0..e33bea4 100644
--- a/dokan/dokan.c
+++ b/dokan/dokan.c
@@ -360,7 +360,8 @@ UINT WINAPI DokanLoop(PDOKAN_INSTANCE DokanInstance) {
   status = TRUE;
   while (status) {

-    device =
+    if (device == INVALID_HANDLE_VALUE) {
+      device =
         CreateFile(GetRawDeviceName(DokanInstance->DeviceName, rawDeviceName,
                                     MAX_PATH),         // lpFileName
                    GENERIC_READ | GENERIC_WRITE,       // dwDesiredAccess
@@ -370,6 +371,7 @@ UINT WINAPI DokanLoop(PDOKAN_INSTANCE DokanInstance) {
                    0,                                  // dwFlagsAndAttributes
                    NULL                                // hTemplateFile
                    );
+    }

     if (device == INVALID_HANDLE_VALUE) {
       DbgPrint(
@@ -467,7 +469,6 @@ UINT WINAPI DokanLoop(PDOKAN_INSTANCE DokanInstance) {
       DbgPrint("ReturnedLength %d\n", returnedLength);
     }

-    CloseHandle(device);
   }

   CloseHandle(device);

```

**Comment by Liryna** [comment]
Hi @bailey27 ,

This come from PR https://github.com/dokan-dev/dokany/pull/303 of @marinkobabic that fix the issue https://github.com/dokan-dev/dokany/issues/230
My guess would be that it was made to be sure to always have a valid handle on the device.

**Comment by marinkobabic** [comment]
I changed once to keep the handle opened. The driver can't remove the
device because of the opened handle. Causes blue screens in specific
scenarios.

This way we have much better control.

To improve performance the branch with thread pool should be completed.

Am 05.05.2017 22:08 schrieb "Liryna" <notifications@github.com>:

**Comment by bailey27** [comment]
Ok.   Thanks for the explanation.
