### ISSUE TITLE
Feature Request: Interface for setting the sddl for the device object(s) created by the Dokan kernel driver

### ISSUE THREAD

**Issue by marcellmajor** [dokan-dev/dokany#512]
# Feature Request:
Please provide an interface for setting sddl for the device object(s) created by the Dokan kernel driver. E.g. it can be normally part of the installer script or .inf file so at least there is a possibility for customizing it if needed.

# Rationale:
For security consideration we would need a way to restrict some type of Windows users from even trying to use the device object.

# Background:
Currently it is hard coded in
https://github.com/dokan-dev/dokany/blob/60b08e009708b049c6d8c6f24f5050e37b97e403/sys/dokan.h#L706

**Comment by Liryna** [comment]
This is now possible in 2.0.0 see the changelog
