### ISSUE TITLE
mount.c:DokanMount() do not return when BroadcastSystemMessage() keep broadcasting the message

### ISSUE THREAD

**Issue by noairman** [dokan-dev/dokany#513]
# Environment
 * Windows version: 10
 * Processor architecture: 64 bit
 * Dokany version: Release 1.0.3
 * Library type (Dokany/FUSE): dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [] I can always reproduce the issue with the provided description below.
  - [] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
   The function DokanMount in mount.c do not return.As we can see ,the BroadcastSystemMessage will not return with the BSF_FORCEIFHUNG  and BSF_NOTIMEOUTIFNOTHUNG flag,if one of the recipients is always not responding.
    **It happened once,but i can't reproduce the issue.**
At that time ,the value of the receipients is BSM_APPLICATIONS,and i don't know which receipient is not responding.Why should we use the BSF_NOTIMEOUTIFNOTHUNG with no time out to keep waiting for a response to the message?

```
if (BroadcastSystemMessage(
          BSF_NOHANG | BSF_FORCEIFHUNG | BSF_NOTIMEOUTIFNOTHUNG, &receipients,
          WM_DEVICECHANGE, device_event, (LPARAM)&params) <= 0) {
    DbgPrint("DokanBroadcastLink: BroadcastSystemMessage failed - %d\n",
             GetLastError());
  }
```

**Comment by Liryna** [comment]
Hi @noairman ,

Humm that's a wierd behavior.
`
BSF_NOTIMEOUTIFNOTHUNG -
Waits for a response to the message, as long as the recipient is not being unresponsive. Does not time out.`
I would expect from this that it can take time but do not lock process 😢 
It would mean that a process that respond, ignores to process our call ?

**Comment by noairman** [comment]
@Liryna ,
yeah,and somehow the BroadcastSystemMessage does not return,and keeping waiting and broadcasting.

**Comment by Liryna** [comment]
It is true that removing `BSF_NOTIMEOUTIFNOTHUNG` should not harm. We do not need to wait anyway, it is a simple notification.
Otherwise I just think was a bug and should normally not happen regarding the documentation...

You can make a PR if you want to remove it.

**Comment by Liryna** [comment]
I will close this issue for now. If anyone face the same issue, just comment and I will look more on this !
