### ISSUE TITLE
it takes long time to open the Winrar File in dokan mirror

### ISSUE THREAD

**Issue by noairman** [dokan-dev/dokany#515]
# Environment
 * Windows version: 10
 * Processor architecture: 64 bit
 * Dokany version: Release 1.0.3
 * Library type (Dokany/FUSE): dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
  When try to open a winarar file which has a lot of files in it,the windows volume and the dokan mirror show different read.
 1.In windows volume，the winrar only send a few IRP_MJ_READ operation
![1](https://cloud.githubusercontent.com/assets/10110303/26229609/abdafade-3c75-11e7-8bce-ea6b9201a72c.jpg)

![3](https://cloud.githubusercontent.com/assets/10110303/26231917/eee0e4b0-3c84-11e7-963a-fa465e889f95.jpg)

2.but in dokan mirror the winrar send a lot of IRP_MJ_READ operatio,and most of read len are less that 100 byte ,And it tried to read the file from the begining to the end ,which make the winrar a long time to response.
![2](https://cloud.githubusercontent.com/assets/10110303/26229696/3a653382-3c76-11e7-9d0a-ad550962a408.jpg)

**why the operation is different between the windows volume and  dokan mirror with the same winrar file?**

**Comment by Liryna** [comment]
Hi @noairman ,

Ah I already faced such behavior when windows kernel request a lots of little read.
Can you log and compare the read size on a normal FS ? I would expect something like  the 200000 read is more fast or only a part is returned.

**Comment by Liryna** [comment]
Hi @noairman ,

So for dokan there is no 200000 read at first ?
Is there any IO difference on the file before the read between ntfs and dokan ?

**Comment by noairman** [comment]
the first 200000 read is the same,but after that it starts with a lot of read less that 100.
The pic above is not the begining,you can check the pic below with the read of the beignning 
![4](https://cloud.githubusercontent.com/assets/10110303/26235345/1048a2c4-3c9d-11e7-8e38-b8e792e645f3.jpg)


And there is the whloe log of the filespy
[FileSpy.txt](https://github.com/dokan-dev/dokany/files/1013247/FileSpy.txt)

**Comment by Liryna** [comment]
@noairman will close this for inactivity and also I could not reproduce it on my side. If anyone face the issue, please do not hesitate.
