### ISSUE TITLE
NFS

### ISSUE THREAD

**Issue by techtonik** [dokan-dev/dokany#516]
There is no NFS support using Dokan at http://dokan-dev.github.io/

Why? I found https://github.com/nekoni/nekodrive but it seems dead already https://github.com/nekoni/nekodrive/issues/47

**Comment by Liryna** [comment]
Hi @techtonik ,

The list of FS on the website is updated after FS developers request to add them.
There is a lot of FS using Dokan and I cannot list all of them.

About NFS, looks like https://github.com/terdos/WinNFS is the most updated. Probably it is worst to update the DokanNet dependency and try to run it.

**Comment by Daniel-Abrecht** [comment]
There are two Windows ports of Ronnie Sahlbergs' fuse-nfs program: https://github.com/sahlberg/fuse-nfs/
My port is based on Dokanys' fuse-wrapper: https://github.com/Daniel-Abrecht/fuse-nfs-crossbuild-scripts/
The other port is from Bill Zissimopoulos and based on winfsp: https://github.com/billziss-gh/nfs-win

Please note that fuse-nfs is based on libnfs which currently doesn't support kerberos, which means that both of these fuse-nfs ports won't support kerberos authentication either.

**Comment by Liryna** [comment]
Ah thanks @Daniel-Abrecht !
Would you like that I add your project on the dokan page ?

**Comment by Daniel-Abrecht** [comment]
Yes, I would really appreciate this.

**Comment by Liryna** [comment]
Done 👍 @Daniel-Abrecht 
https://github.com/dokan-dev/dokan-dev.github.io/commit/4fd7a081e28e1241003f27b20c73988cdf85ec5b

**Comment by Daniel-Abrecht** [comment]
Maybe I should change the description from "Some shell scripts to build fuse-nfs for windows using dokany" to "fuse-nfs for windows using dokany" to avoid confusion, because there are also releases.

**Comment by Liryna** [comment]
Updated ❤️  https://github.com/dokan-dev/dokan-dev.github.io/commit/bba464778a661ec6a45dd93a27256c7f2f119363

**Comment by techtonik** [comment]
Awesom. =)
