### ISSUE TITLE
BSOD on IFSTest on AppVeyor Win2012R2 image

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#519]
# Environment
 * Windows version: 2012 R2
 * Processor architecture: amd64
 * Dokany version: master (0e159e37d28d44828210d72b34d736ccd43933d5) with some AppVeyor changes
 * Library type (Dokany/FUSE): dokany
 
# Check List
  - [ x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ x ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ x ] I can always reproduce the issue with the provided description below.
  - [ x ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ x ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Running IFSTest (Win10Anniversary) on the AppVeyor VS2015 image causes a BSOD.
I have not tried to reproduce it anywhere else. The corresponding commit, has a modified mirror_test.ps1 that runs IFSTest.
(I will also bug the AppVeyor-people with two reproducible test cases for BSOD, in one situation the current build step will silently be skipped, in the other one the build hangs completely...)

# Logs
Can be found in the [AppVeyor output](https://ci.appveyor.com/project/Rondom/dokany/build/1.0.3-339/job/nj3gfa14hf35r4t8#L1197). A memory.dmp can be downloaded there as well.

(I am also wondering why KD is not displaying any line-numbers in the AppVeyor-output. Maybe someone can tell me how to load the debug-symbols currectly.)

    & "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\kd.exe" -z $memory_dmp -y "SRV*${env:APPVEYOR_BUILD_FOLDER}\x64\Win8.1Release\*http://msdl.microsoft.com/download/symbols" -c "!analyze -v; q" }

**Comment by Liryna** [comment]
Hi @Rondom ,

Thank you trying to add IFSTest to appveyor 👍 

Should probably change the build configuration to build as debug and not release 😢 
@marinkobabic any idea what release pdb is not used ?

**Comment by marinkobabic** [comment]
Normally winding displays why the pub is not used. It shows if the pub has
been found and the reason of not using it.

Am 26.05.2017 08:36 schrieb "Liryna" <notifications@github.com>:

**Comment by Rondom** [comment]
Ok, I found out how to print more information (`-lines` parameter).  If you have suggestions for other WinDbg-commands to run automatically, feel free to tell me. 
https://ci.appveyor.com/project/Rondom/dokany/build/1.0.3-365/job/58vvbd79bisbxgmt
The crash seems to occur somewhere in DokanDispatchCreate. You can download a dump including the PDB and binaries in the "Artifacts"-tab on AppVeyor.

Without having much of a clue about the code I tried reverting @bailey27's two recent commits 51e690f and 756ab5b, but that did not help.

I cannot reproduce the issue on my Win 2016 machine

**Comment by Liryna** [comment]
Humm by looking at the code, this could happen if `relatedFileName->Length` is < `sizeof(WCHAR)`

Can you just add a check for it on your repository to make appveyor rerun the build ?

**Comment by Rondom** [comment]
Could it be that the `relatedFileName->Length` is the buffer length in sizeof(WCHAR) instead of the number of bytes? I did the change you suggested, but it did not help. Maybe I did something wrong? 

      if (relatedFileName->Length > 0 && fileObject->FileName.Length > 0 &&
          relatedFileName->Length >= sizeof(WCHAR) &&  // test
	  relatedFileName->Buffer[relatedFileName->Length / sizeof(WCHAR) -
                                  1] != '\\' && fileObject->FileName.Buffer[0] != ':') {
        needBackSlashAfterRelatedFile = TRUE;
        fileNameLength += sizeof(WCHAR);
      }

**Comment by Liryna** [comment]
@Rondom Thanks for the test. Since the BSOD is `DRIVER_PAGE_FAULT_BEYOND_END_OF_ALLOCATION` (read / write outside alloc memory), looks like maybe `relatedFileName->Length` has a wrong value ?
Can you comment all the code using `relatedFileName` to see if he is the issue here ?

**Comment by Rondom** [comment]
I did as you suggested. I did not spend too much time on understanding the code, so maybe I commented the wrong things and made it worse. I know get a crash at a completely different place :-(

* [Build output with reference to crashing line](https://ci.appveyor.com/project/Rondom/dokany/build/1.0.3-376#L1405)
* [Changes I did](https://github.com/Rondom/dokany/commit/2d1718af96c6d4567d8ee19f9143dad6b68ab086)

**Comment by Liryna** [comment]
Ok looks like there is really an incorrect `FileName->Length`
We are exactly in the same lengh calcul that we just commented: https://ci.appveyor.com/project/Rondom/dokany/build/1.0.3-376#L1413

**Comment by Rondom** [comment]
So, in order to understand it better. That one crash was in `create.c` in `DokanDispatchCreate`, the new crash is in `DokanNotifyReportChange0` in `dokan.c:478`. How are the two connected? Should I try something else?

**Comment by Liryna** [comment]
They both use the same file object and length of it.
Looks like somewhere we set a wrong length on this objet that produces the BSOD when we use it.

I will try to look later we does this could happen.

**Comment by Rondom** [comment]
OK, thanks. (I am a bit tired, so I am a bit slow at understanding)

**Comment by marinkobabic** [comment]
Can the issue be reproduced in a separate vm when running test ifstest.exe manually? If this is the case, then we can debug and investigate the source of the problem.

**Comment by Rondom** [comment]
I cannot reproduce it on Win2016. That's all I can say. if you have a Win 8.1 system, you should probably (or hopefully) be able to reproduce it.

**Comment by Rondom** [comment]
@Liryna what do you think about running the tests also on both Win2012R2 and  Win2016 on AppVeyor? For this, we would need to download the artifact from the actual build, to use it in the "FSTest" configuration, because we cannot build in AppVeyor's Win2016-images. (This means that the two will be dependant on another). Any other drawbacks, objections?

**Comment by Liryna** [comment]
I do not see drawbacks or objections here. I had no idea this could be possible 😮 !
Would be interesting how can this looks like in the appveyor file.

**Comment by Rondom** [comment]
It looks a bit clumsy. AppVeyor will build all combinations, but we exclude the ones we do not want.

      image:
        - Visual Studio 2015
        - Visual Studio 2017
      matrix:
        exclude:
          - configuration: All
            image: Visual Studio 2017
          - configuration: Coverity
            image: Visual Studio 2017

Turns out it is not so easy to re-use the artifact from the "All"-configuration. Seems like AppVeyor needs a Token-Auth for their API even if it is read-only-access from the build-worker. I think it is not worth the effort in this case, because one could not safely enable it for pull requests. That also rules out some other things, like comparing tests between the previous build and the current build and printing the delta. 😢 

Rather I think we can wait for the WDK to be installed on the VS2017-image (Win10), which has VS2015 installed as well, so that we can build there for the tests as well, while keeping the compilation environment as similar as possible to avoid testing builds that are too different from one another. appveyor/ci#1554

I think that's the best we can do with the free AppVeyor-infrastucture while keeping effort reasonable.

**Comment by Rondom** [comment]
I have just learned that no Auth-Token is needed for publicly available information. So I extended my code to run the tests both on Win2016 and 2012R2. The result was that we get a BSOD on both OSes.

My local tests were done on Win2016 with  0e159e3 and so were the first tests with BSOD on AppVeyor. 

I will submit my PR as a draft. Hopefully, it can be merged once the BSOD is fixed.

**Comment by Liryna** [comment]
Thank you @Rondom ! 
Will try to look at this BSOD to move on for your PR, Unfortunately, I will only have time in july 😢 

Great work again 💘 !

**Comment by Liryna** [comment]
I have fork the Ifstest PR to look at the issue and am facing another BSOD on appveyor
https://ci.appveyor.com/project/Liryna/dokany/build/1.0.3-5/job/olur3pvne83159jj#L660

I try to install ifstest on my side and reproduce

**Comment by Liryna** [comment]
@Rondom I have pull your branch / revert marinko PR that was creating issue on it and I am not able to reproduce the bsod 😢 

[ifstest result.txt](https://github.com/dokan-dev/dokany/files/1117986/ifstest.result.txt)

For me `Virus`, `DefragEnhancements` test group was crashing ifstest, it can probably be ignored with others

I try to add some check on appveyor build see if we can avoid the bsod about file length for now...

**Comment by Rondom** [comment]
Have you tried running it with the same verifier settings and maybe even running the script from the same path?

Otherwise there is still the possibility to RDP into the build VM...

**Comment by Liryna** [comment]
👍 verifier enable make the bsod happen !

Looks like the test that make crash is `DirectoryFullPathCreationTest` (just guessing since I seen `FileFullPathCreationTest` print before. But my virtualbox do not let my windows create a dump for a reason 😢 it just freeze. @marinkobabic are you using virtualbox ? do you have the same issue ?

**Comment by marinkobabic** [comment]
Yes. I habe the same issue. Normally I attach the kernel debugger so it's
not a huge problem.

Am 02.07.2017 21:12 schrieb "Liryna" <notifications@github.com>:

**Comment by Liryna** [comment]
@marinkobabic Will try that !
@Rondom I found the BSOD issue, it is quiet simple 😞 
Can you just add to your PR:
```
  relatedFileName->Length = relatedFcb->FileName.Length;
```
Like here:
https://github.com/Liryna/dokany/commit/6e59613b23247247b6683a8b2bdf69cbc0c8de4b#diff-86caa6b16e4044982075fe5d5bc59915R608

After that, all test pass without BSOD 👍

**Comment by Liryna** [comment]
Test currently running on my appveyor with the fix:
https://ci.appveyor.com/project/Liryna/dokany/build/job/c74npkyfvs8w8ig7

**Comment by Rondom** [comment]
Only the assignment, i.e. without the other change in the if-statement in line 647?

**Comment by Liryna** [comment]
Only the assignment yes, the other line is me who revert a previous test that I did.

**Comment by Rondom** [comment]
Please double-check the commit, but if we get no BSOD on AppVeyor things should be fine and this issue is fixed and the PR can be merged. :raised_hands:
