### ISSUE TITLE
Using Dokan as a Raw Disk

### ISSUE THREAD

**Issue by shlatchz** [dokan-dev/dokany#52]
Hi,
Is it possible to use Dokan as a raw disk, and create a filesystem on it?

Thanks!

**Comment by Maxhy** [comment]
Loop device is not the purpose of Dokan and is now natively supported on Windows since 7 https://en.wikipedia.org/wiki/Loop_device#Availability

**Comment by shlatchz** [comment]
yes, but what if you want a boot sector on your dokan drive?

**Comment by Afterster** [comment]
Hu, could you explain your use case here?

**Comment by Maxhy** [comment]
Hu, could you explain your use case here?

**Comment by shlatchz** [comment]
For example, you want to boot a linux OS from your dokan drive

**Comment by Maxhy** [comment]
And why would you like to do that? Your user-mode file system will not be loaded yet at boot time.
Could you describe more than one line what you attempt to achieve? Thanks.
