### ISSUE TITLE
Can dokan be used to access LUKS disks/files?

### ISSUE THREAD

**Issue by sledgehammer999** [dokan-dev/dokany#524]
Probably a dumb question and feel free to close this if so.

I know quite a bit of programming, but not much about this low-level/kernel-level programming. Also I am totally out of my league regarding filesystem programming terminology.

But I have an itch that I want to scratch:
Can dokan be used to access LUKS disks/files? AFAIK LUKS encrypts an entire filesystem eg FAT32. I suppose dokan can be used to manipulate and decrypt/encrypt the LUKS volume, but what happens to the decrypted filesystem contained in the LUKS volume? Do you have to handle it yourself or can you somehow tell Windows "hey, here is a FAT32 volume please mount it and handle it"?
Assume that the contained filesystem is always something that Windows has a driver for.

If dokan isn't the answer, can you kindly point me to the right direction?

**Comment by Rondom** [comment]
First of all: Do you know about FreeOTFE or LibreCrypt?

Dokany is for implementing an actual filesystem.

You might have a look at ImDisk. The official version by the author only supports raw images, but it is open source (the author seems to only publish source tarballs i.e. there is no repo.) There is a community-maintained version that adds support for other image formats. Not sure how difficult it is to provide support for your own.

**Comment by sledgehammer999** [comment]
>Do you know about FreeOTFE or LibreCrypt?

Yes. They are abandonware and don't seem to work for me. Also written in Pascal that I nothing of. Finally they don't provide signed drivers like dokany does.

>There is a community-maintained version that adds support for other image formats. Not sure how difficult it is to provide support for your own.

This is very interesting. Can you give link to the community maintained version? I can't seem to be able to find it.

So it is apparent that dokany isn't what I am looking for. Thx for response. I am closing this.

**Comment by Rondom** [comment]
I think it's this one: https://sourceforge.net/projects/imdisk-toolkit/
