### ISSUE TITLE
GetVolumePathName return false,the last error is 'The parameter is incorrect' 

### ISSUE THREAD

**Issue by noairman** [dokan-dev/dokany#525]
# Environment
 * Windows version: 10
 * Processor architecture: 64 bit
 * Dokany version: Release 1.0.3
 * Library type (Dokany/FUSE): dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
  Mirror mount the volume M: ,when pass the "M:\\",the GetVolumePathName function always return false,and the last error is '**The parameter is incorrect**' 
 so,it might means that the first parameter lpszFileName was not correct.In that case ,what should I pass to that function?

GetVolumePathName function,retrieves the volume mount point where the specified path is mounted:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa364996(v=vs.85).aspx

**And we can't see the any information of M: on the Disk Management.**
I dont' know if it could be same issues when system can't indentify the M: on Disk Management.

**Comment by Liryna** [comment]
Hi @noairman ,

Have you try to use `/o (use mount manager)` with the mirror for the test ?

**Comment by noairman** [comment]
Hi,@Liryna,
the function return true when mount with _/o(use mount manager)_ .Thanks
