### ISSUE TITLE
mirror crashed when mount it on the windows server 2008 R2 (SP1)

### ISSUE THREAD

**Issue by noairman** [dokan-dev/dokany#526]
# Environment
 * Windows version: windows server 2008
 * Processor architecture: 64 bit
 * Dokany version: Release 1.0.3
 * Library type (Dokany/FUSE): dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

As the log shows,after the AddSeSecurityNamePrivilege function,it crashed.

![1](https://cloud.githubusercontent.com/assets/10110303/26813366/3042a9a0-4ab0-11e7-80ef-7f344da306f4.png)
![2](https://cloud.githubusercontent.com/assets/10110303/26813370/3782f2c4-4ab0-11e7-8a70-d6cbaee5e8ef.png)
![3](https://cloud.githubusercontent.com/assets/10110303/26814155/eb7b8930-4ab5-11e7-941f-262f285012ba.png)

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	mirror.exe
  Application Version:	0.0.0.0
  Application Timestamp:	58d51fd7
  Fault Module Name:	dokan1.dll
  Fault Module Version:	1.0.3.1000
  Fault Module Timestamp:	590c3486
  Exception Code:	c0000005
  Exception Offset:	00000000000046f6
  OS Version:	6.1.7601.2.1.0.274.10
  Locale ID:	1033
  Additional Information 1:	e826
  Additional Information 2:	e8265d768adbb4c22c2682609fcc0d60
  Additional Information 3:	7fc2
  Additional Information 4:	7fc2db46a28ae6bcf874a4d7047c4a23

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by Liryna** [comment]
Hi @noairman ,

Have you a way to debug to get information on the crash or even see what is happening ?
Try to use `/r C:\`

**Comment by noairman** [comment]
@Liryna 
i tried the "`mirror.exe /d /s /r c:\ /l M:"` with the same issue
and now i need to get the dump file and see what is happening in dokan1.dll.

**Comment by Liryna** [comment]
@noairman have you been able to look at the crash ?
Does it happen only on one machine ?
