### ISSUE TITLE
Clever idea? Can I call Java code from within C?

### ISSUE THREAD

**Issue by gsaxena888** [dokan-dev/dokany#527]
Earlier, I posted a question asking if we had a Java API to dokan (https://github.com/dokan-dev/dokany/issues/514). 

However, I had an idea, but it seems too good to be true: is it possible in the sample mirror.c code (https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c) that for every dokan function I replace the BODY of the function with a call to Java? (Not only does my team know Java, but a lot of our logic is already written in Java.) Is there any reason why that would not work, not be stable, or not be reasonably performant? (We'd use JNI and our use-case is that one of the two scenarios: scenario 1: there's a very large (eg 3 GB) file for which there's a lot of random read/writes; scenario 2: we want to create a dokan drive which will be used to store a large IntelliJ Java project's source files and it will be used by IntelliJ to compile all the Java files etc -- so 10,000s of small files that are read and written to.)

**Comment by Rondom** [comment]
Well, that is exactly how you would go about writing a JNI-wrapper I guess (further comments in the other issue).

**Comment by Liryna** [comment]
Hi @gsaxena888 ,

Dokan use a [DOKAN_OPERATIONS](https://dokan-dev.github.io/dokany-doc/html/struct_d_o_k_a_n___o_p_e_r_a_t_i_o_n_s.html) struct that holds all the calls (that is used by the mirror like you say). Every wrapper currently creates this binary struct in their language and give it to dokan to after proxy the calls into language adapted parameters of it (C# ex: https://github.com/dokan-dev/dokan-dotnet/blob/master/DokanNet/Native/DOKAN_OPERATIONS.cs https://github.com/dokan-dev/dokan-dotnet/blob/master/DokanNet/DokanOperationProxy.cs).

What you say can be possible also, it is another way to do it but probably having a struct would avoid one function call (but does it really count compared to the jump to managed language ?).

If you plan to make a FS for heavy project, you should probably look to do it in C if you can.

**Comment by hkarakose** [comment]
Following is a screenshot from `MirrorGetVolumeInformation`. If I want to integrate to Dokan using JNI, is this the method that needs to be implemented in Java layer?

![image](https://user-images.githubusercontent.com/406291/27343163-15b9059c-55b0-11e7-855b-04f35ac7865e.png)

**Comment by Liryna** [comment]
@hkarakose you need to forward MirrorGetVolumeInformation to Java with a JNI call. `GetVolumeInformation` is a windows call.

**Comment by Liryna** [comment]
Does this issue can be closed ?

**Comment by hkarakose** [comment]
Yes, thanks.
