### ISSUE TITLE
BSOD while debugging .NET mirror sample

### ISSUE THREAD

**Issue by viciousviper** [dokan-dev/dokany#53]
This is on Dokan 0.7.4.
I'd be happy to provide further  details - if I had access to the 0.7.4 pdb.

> 
> Microsoft (R) Windows Debugger Version 6.3.9600.17336 AMD64
> Copyright (c) Microsoft Corporation. All rights reserved.
> 
> 
> Loading Dump File [C:\Windows\MEMORY.DMP]
> Kernel Bitmap Dump File: Full address space is available
> 
> 
> ************* Symbol Path validation summary **************
> Response                         Time (ms)     Location
> Deferred                                       SRV*C:\Windows\symbol_cache*http://msdl.microsoft.com/download/symbols
> Symbol search path is: SRV*C:\Windows\symbol_cache*http://msdl.microsoft.com/download/symbols
> Executable search path is: 
> Windows 8 Kernel Version 9600 MP (8 procs) Free x64
> Product: WinNt, suite: TerminalServer SingleUserTS
> Built by: 9600.17936.amd64fre.winblue_ltsb.150715-0840
> Machine Name:
> Kernel base = 0xfffff802\`a3a06000 PsLoadedModuleList = 0xfffff802\`a3cdb7b0
> Debug session time: Fri Sep  4 19:35:30.194 2015 (UTC + 2:00)
> System Uptime: 0 days 0:12:38.930
> Loading Kernel Symbols
> ...............................................................
> ................................................................
> ................................................................
> ..............
> Loading User Symbols
> 
> Loading unloaded module list
> ..........
> *******************************************************************************
> *                                                                             *
> *                        Bugcheck Analysis                                    *
> *                                                                             *
> *******************************************************************************
> 
> Use !analyze -v to get detailed debugging information.
> 
> BugCheck 7E, {ffffffffc0000005, fffff802a3a94cb9, ffffd000219c86b8, ffffd000219c7ec0}
> 
> *** ERROR: Module load completed but symbols could not be loaded for dokan.sys
> Probably caused by : dokan.sys ( dokan+2523 )
> 
> Followup: MachineOwner
> 
> 4: kd> !analyze -v
> *******************************************************************************
> *                                                                             *
> *                        Bugcheck Analysis                                    *
> *                                                                             *
> *******************************************************************************
> 
> SYSTEM_THREAD_EXCEPTION_NOT_HANDLED (7e)
> This is a very common bugcheck.  Usually the exception address pinpoints
> the driver/function that caused the problem.  Always note this address
> as well as the link date of the driver/image that contains this address.
> Arguments:
> Arg1: ffffffffc0000005, The exception code that was not handled
> Arg2: fffff802a3a94cb9, The address that the exception occurred at
> Arg3: ffffd000219c86b8, Exception Record Address
> Arg4: ffffd000219c7ec0, Context Record Address
> 
> Debugging Details:
> 
> 
> EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%08l referenced memory at 0x%08lx. The memory could not be "%s".
> 
> FAULTING_IP: 
> nt!IopfCompleteRequest+a69
> fffff802\`a3a94cb9 488b4018        mov     rax,qword ptr [rax+18h]
> 
> EXCEPTION_RECORD:  ffffd000219c86b8 -- (.exr 0xffffd000219c86b8)
> ExceptionAddress: fffff802a3a94cb9 (nt!IopfCompleteRequest+0x0000000000000a69)
>    ExceptionCode: c0000005 (Access violation)
>   ExceptionFlags: 00000000
> NumberParameters: 2
>    Parameter[0]: 0000000000000000
>    Parameter[1]: 0000000000000019
> Attempt to read from address 0000000000000019
> 
> CONTEXT:  ffffd000219c7ec0 -- (.cxr 0xffffd000219c7ec0;r)
> rax=0000000000000001 rbx=ffffe00158824350 rcx=0000000000000884
> rdx=0000000000000000 rsi=0000000000000000 rdi=0000000000000001
> rip=fffff802a3a94cb9 rsp=ffffd000219c88f0 rbp=ffffd000219c89f0
>  r8=0000000000000001  r9=ffffe00158888800 r10=fffff801e9674280
> r11=ffffd000219c8a28 r12=00000000a000000c r13=0000000000000000
> r14=ffffe00158836f00 r15=00000000a0000003
> iopl=0         nv up ei pl nz na pe nc
> cs=0010  ss=0018  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
> nt!IopfCompleteRequest+0xa69:
> fffff802\`a3a94cb9 488b4018        mov     rax,qword ptr [rax+18h] ds:002b:00000000\`00000019=????????????????
> Last set context:
> rax=0000000000000001 rbx=ffffe00158824350 rcx=0000000000000884
> rdx=0000000000000000 rsi=0000000000000000 rdi=0000000000000001
> rip=fffff802a3a94cb9 rsp=ffffd000219c88f0 rbp=ffffd000219c89f0
>  r8=0000000000000001  r9=ffffe00158888800 r10=fffff801e9674280
> r11=ffffd000219c8a28 r12=00000000a000000c r13=0000000000000000
> r14=ffffe00158836f00 r15=00000000a0000003
> iopl=0         nv up ei pl nz na pe nc
> cs=0010  ss=0018  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
> nt!IopfCompleteRequest+0xa69:
> fffff802\`a3a94cb9 488b4018        mov     rax,qword ptr [rax+18h] ds:002b:00000000\`00000019=????????????????
> Resetting default scope
> 
> PROCESS_NAME:  System
> 
> CURRENT_IRQL:  0
> 
> ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%08l referenced memory at 0x%08lx. The memory could not be "%s".
> 
> EXCEPTION_PARAMETER1:  0000000000000000
> 
> EXCEPTION_PARAMETER2:  0000000000000019
> 
> READ_ADDRESS: unable to get nt!MmNonPagedPoolStart
> unable to get nt!MmSizeOfNonPagedPoolInBytes
>  0000000000000019 
> 
> FOLLOWUP_IP: 
> dokan+2523
> fffff801\`e966e523 4883c428        add     rsp,28h
> 
> BUGCHECK_STR:  AV
> 
> DEFAULT_BUCKET_ID:  NULL_CLASS_PTR_DEREFERENCE
> 
> ANALYSIS_VERSION: 6.3.9600.17336 (debuggers(dbg).150226-1500) amd64fre
> 
> LAST_CONTROL_TRANSFER:  from fffff801e966e523 to fffff802a3a94cb9
> 
> STACK_TEXT:  
> ffffd000\`219c88f0 fffff801\`e966e523 : ffffe001\`58824350 fffff802\`a3e60900 ffffe001\`627b53d0 ffffe001\`58836ef0 : nt!IopfCompleteRequest+0xa69
> ffffd000\`219c8a30 fffff801\`e9671244 : ffffe001\`57496540 ffffe001\`58837da0 ffffe001\`58836f68 ffffe001\`58836e30 : dokan+0x2523
> ffffd000\`219c8a60 fffff801\`e9670b7e : ffffe001\`58836f68 ffffe001\`58837da0 ffffe001\`58836e30 ffffe001\`58836f68 : dokan+0x5244
> ffffd000\`219c8aa0 fffff801\`e9671d6c : ffffe001\`5fd9c0b0 ffffe001\`58837da0 ffffe001\`58836e30 ffffe001\`00000002 : dokan+0x4b7e
> ffffd000\`219c8af0 fffff801\`e96719d1 : ffffffff\`fffe7960 00000000\`00000001 00000000\`00000080 ffffe001\`58837da8 : dokan+0x5d6c
> ffffd000\`219c8b30 fffff801\`e9671c4e : ffffe001\`58837da0 00000000\`00000000 ffffe001\`57309801 00000000\`00000000 : dokan+0x59d1
> ffffd000\`219c8b60 fffff802\`a3b040a8 : 00000000\`00000000 ffffe001\`58834080 ffffe001\`58834080 00000000\`00000000 : dokan+0x5c4e
> ffffd000\`219c8c00 fffff802\`a3b5bfc6 : ffffd001\`2f0a7180 ffffe001\`58834080 ffffd001\`2f0b33c0 fffff802\`a3a9fd28 : nt!PspSystemThreadStartup+0x58
> ffffd000\`219c8c60 00000000\`00000000 : ffffd000\`219c9000 ffffd000\`219c3000 00000000\`00000000 00000000\`00000000 : nt!KiStartSystemThread+0x16
> 
> 
> SYMBOL_STACK_INDEX:  1
> 
> SYMBOL_NAME:  dokan+2523
> 
> FOLLOWUP_NAME:  MachineOwner
> 
> MODULE_NAME: dokan
> 
> IMAGE_NAME:  dokan.sys
> 
> DEBUG_FLR_IMAGE_TIMESTAMP:  55d73d9a
> 
> STACK_COMMAND:  .cxr 0xffffd000219c7ec0 ; kb
> 
> FAILURE_BUCKET_ID:  AV_dokan+2523
> 
> BUCKET_ID:  AV_dokan+2523
> 
> ANALYSIS_SOURCE:  KM
> 
> FAILURE_ID_HASH_STRING:  km:av_dokan+2523
> 
> FAILURE_ID_HASH:  {9d91f95c-aa94-4f23-2d77-0f802f2a29b4}
> 
> Followup: MachineOwner
>

**Comment by Liryna** [comment]
Since it is related to https://github.com/dokan-dev/dokan-dotnet/issues/16, I close it.
