### ISSUE TITLE
[question] ReadDirectoryChanges/FileSystemwatcher => notify manually ?

### ISSUE THREAD

**Issue by oguimbal** [dokan-dev/dokany#532]
# Environment
 * Windows version: All
 * Processor architecture: All
 * Dokany version: All
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

Attaching a FileSystemWatcher to a Dokan device works well... as long as the changes originate from an operation that is made through the device (which is quite understandable !).

But what if changes come from "inside" ?
ex: using the mirror sample, if I change something in the mirrored directory, no event will be emitted when watching the mirror.

Is there any way to manually notify the dokan driver that a file/dir has changed so it could return something to ReadDirectoryChanges  ?

(Just a note that i'd like to have found earlier, for those who only want Explorer right in case of a change:  use [SHChangeNotify](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762118(v=vs.85).aspx)).

**Comment by Rondom** [comment]
There is no such functionality at this point. One would need to come up with a design and implement it.

**Comment by kenjiuno** [comment]
> Attaching a FileSystemWatcher to a Dokan device works well... as long as the changes originate from an operation that is made through the device (which is quite understandable !).

It seems that Dokan already delivers changes by `DokanNotifyReportChange`
https://github.com/dokan-dev/dokany/search?utf8=%E2%9C%93&q=DokanNotifyReportChange&type=

> But what if changes come from "inside" ?
> ex: using the mirror sample, if I change something in the mirrored directory, no event will be emitted when watching the mirror.

Make `DokanNotifyReportChange` or `DokanNotifyReportChange0` available to user land code would be useful if they implement their own notification mechanism.

**Comment by Liryna** [comment]
`DokanNotifyReportChange` is part of the kernel code. Making it available to user land is possible. It would need to add a dokan IRP between Library<-> Kernel.

**Comment by Liryna** [comment]
DokanNotify is now available from userland 👍 
https://github.com/dokan-dev/dokany/commit/66c9c5a7d737f6fc071dcd76a17b686e3ac16be8
