### ISSUE TITLE
"Driver something wrong" with newest snapshot

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#533]
# Environment
 * Windows version: Server 2016
 * Processor architecture: amd64
 * Dokany version: latest snapshot 3846b9dd
 * Library type (Dokany/FUSE): dokany
 
# Check List
  - [ x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ x ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ x ] I can always reproduce the issue with the provided description below.
  - [ x ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I have just installed the latest snapshot. And it does not work at all. Maybe it is my environment or there is some regression.

When I first tried it, I got "driver something wrong". After rebooting and uninstalling and reinstalling the driver using dokanctl I get the following behaviour

# Logs
```
PS C:\Program Files\Dokan\Dokan Library-1.0.3\sample\mirror> .\mirror.exe  /s /r C:\ /l O:
AllocationUnitSize: 512 SectorSize: 512
device opened
Ioctl failed for wait with code 1.
Ioctl failed for wait with code 1.
Thread will be terminated
Ioctl failed for wait with code 1.
Thread will be terminated
Ioctl failed for wait with code 1.
Thread will be terminated
Thread will be terminated
Ioctl failed for wait with code 1.
Thread will be terminated
mounted: O: -> \Volume{d6cc17c5-1736-4085-bce7-964f1e9f5de9}

unload
Success
PS C:\Program Files\Dokan\Dokan Library-1.0.3\sample\mirror> .\mirror.exe  /s /r C:\ /l O:
AllocationUnitSize: 512 SectorSize: 512
device opened
Dokan Error: driver start error
Driver something wrong
send global release for O:
DokanError: Ioctl failed with code 1617
Failed to unmount: O:
PS C:\Program Files\Dokan\Dokan Library-1.0.3\sample\mirror> ..\..\dokanctl.exe /l a
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
  Mount points: 3
  0# MountPoint: \DosDevices\M: - UNC:  - DeviceName: \Device\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}
  1# MountPoint: \DosDevices\N: - UNC:  - DeviceName: \Device\Volume{d6cc17c5-1735-4085-bce7-964f1e9f5de9}
  2# MountPoint: \DosDevices\O: - UNC:  - DeviceName: \Device\Volume{d6cc17c5-1736-4085-bce7-964f1e9f5de9}
PS C:\Program Files\Dokan\Dokan Library-1.0.3\sample\mirror> ..\..\dokanctl.exe /u O
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
send global release for O:
DokanError: Ioctl failed with code 1617
Failed to unmount: O:
Unmount status = 1
PS C:\Program Files\Dokan\Dokan Library-1.0.3\sample\mirror>
```

**Comment by marinkobabic** [comment]
Kernel log needed. Maybe my pull request has broken it.

Am 17.06.2017 23:07 schrieb "Andreas Gnau" <notifications@github.com>:

**Comment by Liryna** [comment]
First mount:
Kernel: 
[firstmount.txt](https://github.com/dokan-dev/dokany/files/1083379/firstmount.txt)

```
mirror.exe /r C:\Users /l i /d /s
## Attempting to add SE_SECURITY_NAME privilege to process token ##
  success: privilege already present
Dokan: debug mode on
Dokan: use stderr
AllocationUnitSize: 512 SectorSize: 512
device opened
Ioctl failed for wait with code 1.
Ioctl failed for wait with code 1.
Ioctl failed for wait with code 1.
Ioctl failed for wait with code 1.
Ioctl failed for wait with code 1.
Thread will be terminated
Thread will be terminated
Thread will be terminated
Thread will be terminated
Thread will be terminated
mounted: i -> \Volume{d6cc17c5-1736-4085-bce7-964f1e9f5de9}
Mounted
Unmounted

unload
Success
```

Secound mount:
Kernel: 
[secondmount.txt](https://github.com/dokan-dev/dokany/files/1083380/secondmount.txt)

```
mirror.exe /r C:\Users /l i /d /s
## Attempting to add SE_SECURITY_NAME privilege to process token ##
  success: privilege already present
Dokan: debug mode on
Dokan: use stderr
AllocationUnitSize: 512 SectorSize: 512
device opened
Dokan Error: driver start error
Driver something wrong
send global release for i:
DokanError: Ioctl failed with code 1617
Failed to unmount: i:
```

**Comment by marinkobabic** [comment]
In the first log you can find

UserBuffer is not in the user space. This would cause BSOD!!

So the ckeck has to be improved. Have no access to my machine until Tuesday
to fix it.

Am 18.06.2017 11:04 nachm. schrieb "Liryna" <notifications@github.com>:

**Comment by marinkobabic** [comment]
Would be interesting to know the Irp->RequestorMode; during write. Then we
can do a check if RequestorMode != KernelMode additionally

Am 18.06.2017 11:22 nachm. schrieb "Marinko Babic" <
marinko.android@gmail.com>:

**Comment by Rondom** [comment]
Thanks @Liryna, could not find the time to do it.

Previously my tests with IFSTest on AppVeyor were based on 0e159e37d28d44828210d72b34d736ccd43933d5 and I got the out-of-bounds described in issue #519. I am now noticing , that with your change @marinkobabic, the BSOD we get on AppVeyor changes to a different one (I have double-checked this and its reproducible). Now with your commit, instead of the out-of-bounds issue descibed in #519, we get the bugcheck posted below at the end of this post.  [See the build log for complete `!analyze -v` and the minidump and built executables in the artifacts.](https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.3-199/job/xhw28cfx887qq71y#L511).

Now please tell me, whether I should open a third issue about that (because it is a separate issue). To me it sounds separate, but I do not see why your commit (in addition to causing this issue) should magically fix the #519 BSOD and in turn uncover another issue. Then again I don't understand why this issue here (mounting not working at all) was not uncovered on AppVeyor Win2016, which is pretty similar to my environment. Could it be the verifier being enabled? Questions over questions...

```
DRIVER_VERIFIER_IOMANAGER_VIOLATION (c9)
The IO manager has caught a misbehaving driver.
Arguments:
Arg1: 0000000000000224, An IRP dispatch handler has returned a status that is inconsistent with the
	IRP's IoStatus.Status field.
Arg2: fffff801b0003398, The address in the driver's code where the error was detected.
Arg3: ffffcf817f530ea0, IRP address.
Arg4: ffffffffc000000d, Expected status code.
```

```
FAULTING_SOURCE_FILE:  c:\projects\dokany\sys\dispatch.c
FAULTING_SOURCE_LINE_NUMBER:  25
FAULTING_SOURCE_CODE:  
    21: 
    22: #include "dokan.h"
    23: 
    24: NTSTATUS
>   25: DokanBuildRequest(__in PDEVICE_OBJECT DeviceObject, __in PIRP Irp) {
    26:   BOOLEAN AtIrqlPassiveLevel = FALSE;
    27:   BOOLEAN IsTopLevelIrp = FALSE;
    28:   NTSTATUS Status = STATUS_UNSUCCESSFUL;
    29: 
    30:   __try {
```

**Comment by marinkobabic** [comment]
I can explain why we have here a new issue. My pull request caused a bug
and the bug was not discovered by the build process. So I expected that all
is fine but it's not. The build process must enable the verifier to
discover such issues. Can you implement this for the future please?

So now what happened. DokanCompleteIrpRequest changed the status on the
Irp. This was never before the case. The driver returned a different status
using return statement than the one which is on the Irp.

So please undo my commit because the Idea is great but the implementation
is not complete.

Will do another pull request which does the fix properly. Sorry for the
trouble because I relied on the build process.

Thanks
Marinko

Am 19.06.2017 00:05 schrieb "Andreas Gnau" <notifications@github.com>:

**Comment by Liryna** [comment]
Done 👍 https://github.com/dokan-dev/dokany/pull/535

**Comment by marinkobabic** [comment]
Thx a lot.

Am 19.06.2017 14:27 schrieb "Liryna" <notifications@github.com>:

**Comment by Rondom** [comment]
> I can explain why we have here a new issue. My pull request caused a bug and the bug was not discovered by the build process. So I expected that all is fine but it's not. The build process must enable the verifier to discover such issues. Can you implement this for the future please?

Verifier has always been enabled (my PR does not change anything in that regard). 

* how we invoke it:
https://github.com/dokan-dev/dokany/blob/3846b9ddd26bae7e8097779efb391097828ce78e/appveyor.yml#L39
 * and its output there:
https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.3-198/job/ndg4y44f8n3a3xj9#L22
 * and also  here (with my PR, where we the verifier detects the IRP-issue):
https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.3-199/job/xhw28cfx887qq71y#L53

**Comment by Rondom** [comment]
There was actually an issue with BSOD's not being detected on AppVeyor, which I fixed in the process of implementing the IFSTest-PR. So Marinko's PR did cause a BSOD on AppVeyor, but nobody noticed it. :-) I could have remembered that :-)

**Comment by marinkobabic** [comment]
It's great to know that the issue has been fixed :-) This way we will
provide a much better quality.

In the system there is a condition if Marinko so don't report any BSOD :-)

Am 22.06.2017 17:55 schrieb "Andreas Gnau" <notifications@github.com>:

**Comment by Liryna** [comment]
I close this issue and we keep looking at the `EXCEPTION_DOUBLE_FAULT`
here https://github.com/dokan-dev/dokany/issues/530
