### ISSUE TITLE
Unable to set breakpoint in MirrorFindStreams

### ISSUE THREAD

**Issue by hkarakose** [dokan-dev/dokany#536]
# Environment
 * Windows version: 10 
 * Processor architecture: x64 
 * Dokany version: 1.0.3
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [OK] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [OK] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [OK] I can always reproduce the issue with the provided description below.
  - [OK] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [OK] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
When I put a breakpoint in `mirror.c/MirrorGetVolumeInformation` method, it works and program stops at the breakpoint (see following screenshot):

![image](https://user-images.githubusercontent.com/406291/27310023-5ddbcbba-5525-11e7-908f-15288a83ccc9.png)

I am sure that I don't have a visual studio breakpoint configuration problem. But when I put a breakpoint in  `mirror.c/MirrorFindStreams` method, it doesn't work and program doesn't stop at the breakpoint.

![image](https://user-images.githubusercontent.com/406291/27310093-e56fc400-5525-11e7-8c62-4ae8baff702d.png)

I can see that my printf statements actually work from command prompt:

![image](https://user-images.githubusercontent.com/406291/27310154-440303a6-5526-11e7-9f5c-f5ff1a60cfa8.png)

Do you have any idea why the breakpoint in MirrorFindStreams doesn't work?

**Comment by sefai** [comment]
Why do you think it should be called? Are you testing Alternate Data Streams on mirror volume?

**Comment by hkarakose** [comment]
I am just trying to learn the api, and how mirror.c works. I added a printf statement to this function and saw that this function is called.

**Comment by marinkobabic** [comment]
Normally you can write a statement like debugger.break and the debugger
will stop there if for some reason the normal breakpoint does not work.

Am 21.06.2017 11:49 schrieb "Halil Karakose" <notifications@github.com>:

**Comment by Liryna** [comment]
@hkarakose does this issue can be closed ?

**Comment by hkarakose** [comment]
Yes, thanks for the information.
