### ISSUE TITLE
mirror.c cannot delete empty directory

### ISSUE THREAD

**Issue by acapola** [dokan-dev/dokany#54]
The code to delete a directory in mirror.c is the following:

	hFind = FindFirstFile(filePath, &findData);
	while (hFind != INVALID_HANDLE_VALUE) {
		if (wcscmp(findData.cFileName, L"..") != 0 &&
			wcscmp(findData.cFileName, L".") != 0) {
			FindClose(hFind);
			DbgPrint(L"  Directory is not empty: %s\n", findData.cFileName);
			return -(int)ERROR_DIR_NOT_EMPTY;
		}
		if (!FindNextFile(hFind, &findData)) {
			break;
		}
	}
	FindClose(hFind);

	if (GetLastError() == ERROR_NO_MORE_FILES) {
		return 0;
	} else {
		return -1;
	}

The deletion is actually done in dokan code, the value returned here just indicate if it is OK to delete the file or not. returning 0 triggers the file deletion.

When the directory is not empty, hFind is valid, we enter the loop and exit at some point with ERROR_NO_MORE_FILES as last error, all is fine.

When the directory is empty, hFind is INVALID_HANDLE_VALUE and so is the last error, therefore we return -1 and the directory is not deleted.

**Comment by Liryna** [comment]
Do you have a example that can produce the behaviour you describe ?

Because I have made this test a lots of times. When you create an empty folder, you should have `.` & `..` files.

**Comment by Maxhy** [comment]
I agree with @Liryna and I just tested to be sure.
I cannot reproduce your behavior @acapola, could you analyze again on your side and give more information? Thanks.

**Comment by acapola** [comment]
Please find below the console session. To be sure I also created a new directory "test" and immediately tried to delete it:

    C:\Users\seb>
    C:\Users\seb>t:
    
    T:\>RD "New folder"
    Access is denied.
    
    T:\>MD test
    
    T:\>dir
     Volume in drive T is DOKAN
     Volume Serial Number is 1983-1116
    
     Directory of T:\
    
    09/07/2015  10:43 PM    <DIR>          .
    09/07/2015  10:43 PM    <DIR>          ..
    09/06/2015  08:08 PM    <DIR>          New folder
    09/07/2015  10:43 PM    <DIR>          test
                   0 File(s)              0 bytes
                   4 Dir(s)     536,870,912 bytes free
    
    T:\>RD test
    Access is denied.
    
    T:\>c:
    C:\Users\seb>


and the matching log from mirror:

    W:\lofe\windows\dokan_mirror\Win32\Debug>mirror.exe /r c:\tmp\public /l t: /d /s
    
    Dokan: debug mode on
    Dokan: use stderr
    device opened
    mounted: t: -> \Volume{d6cc17c5-1771-4085-bce7-964f1e9f5de9}
    ###Create 0000
    OpenDirectory : c:\tmp\public\
    
    CreateFile status = 0
    ###QueryVolumeInfo 0000
    ###Cleanup 0000
    Cleanup: c:\tmp\public\
    
    ###Close 0000
    ###Create 0001
    Close: c:\tmp\public\
    
    OpenDirectory : c:\tmp\public\
    
    CreateFile status = 0
    ###Create 0002
       CreateDisposition 0x00000001
    CreateFile : c:\tmp\public\autorun.inf
      AccountName: seb, DomainName: seb-win7
            OPEN_EXISTING
            ShareMode = 0x7
            FILE_SHARE_READ
            FILE_SHARE_WRITE
            FILE_SHARE_DELETE
            AccessMode = 0x80
            FILE_READ_ATTRIBUTES
            FlagsAndAttributes = 0x2000000
            FILE_FLAG_BACKUP_SEMANTICS
            error code = 2
    
    CreateFile status = -2
    ###Create 0003
       CreateDisposition 0x00000001
    CreateFile : c:\tmp\public\AutoRun.inf
      AccountName: seb, DomainName: seb-win7
            OPEN_EXISTING
            ShareMode = 0x7
            FILE_SHARE_READ
            FILE_SHARE_WRITE
            FILE_SHARE_DELETE
            AccessMode = 0x80
            FILE_READ_ATTRIBUTES
            FlagsAndAttributes = 0x2000000
            FILE_FLAG_BACKUP_SEMANTICS
            error code = 2
    
    CreateFile status = -2
    ###Create 0004
       CreateDisposition 0x00000001
    CreateFile : c:\tmp\public\N*
      AccountName: seb, DomainName: seb-win7
            OPEN_EXISTING
            ShareMode = 0x7
            FILE_SHARE_READ
            FILE_SHARE_WRITE
            FILE_SHARE_DELETE
            AccessMode = 0x80
            FILE_READ_ATTRIBUTES
            FlagsAndAttributes = 0x2000000
            FILE_FLAG_BACKUP_SEMANTICS
            error code = 123
    
    CreateFile status = -123
    ###Create 0005
       CreateDisposition 0x00000001
    CreateFile : c:\tmp\public\N*
      AccountName: seb, DomainName: seb-win7
            OPEN_EXISTING
            ShareMode = 0x7
            FILE_SHARE_READ
            FILE_SHARE_WRITE
            FILE_SHARE_DELETE
            AccessMode = 0x80
            FILE_READ_ATTRIBUTES
            FlagsAndAttributes = 0x2000000
            FILE_FLAG_BACKUP_SEMANTICS
            error code = 123
    
    CreateFile status = -123
    ###Create 0006
    OpenDirectory : c:\tmp\public\
    
    CreateFile status = 0
    ###QueryVolumeInfo 0006
    ###Cleanup 0006
    Cleanup: c:\tmp\public\
    
    ###Close 0006
    ###Create 0007
    Close: c:\tmp\public\
    
       CreateDisposition 0x00000001
    CreateFile : c:\tmp\public\N*
      AccountName: seb, DomainName: seb-win7
            OPEN_EXISTING
            ShareMode = 0x7
            FILE_SHARE_READ
            FILE_SHARE_WRITE
            FILE_SHARE_DELETE
            AccessMode = 0x80
            FILE_READ_ATTRIBUTES
            FlagsAndAttributes = 0x2000000
            FILE_FLAG_BACKUP_SEMANTICS
            error code = 123
    
    CreateFile status = -123
    ###Create 0008
       CreateDisposition 0x00000001
    CreateFile : c:\tmp\public\N*
      AccountName: seb, DomainName: seb-win7
            OPEN_EXISTING
            ShareMode = 0x7
            FILE_SHARE_READ
            FILE_SHARE_WRITE
            FILE_SHARE_DELETE
            AccessMode = 0x80
            FILE_READ_ATTRIBUTES
            FlagsAndAttributes = 0x2000000
            FILE_FLAG_BACKUP_SEMANTICS
            error code = 123
    
    CreateFile status = -123
    ###Create 0009
    OpenDirectory : c:\tmp\public\
    
    CreateFile status = 0
    ###FindFiles 0009
    FindFiles :c:\tmp\public\\*
            FindFiles return 3 entries in c:\tmp\public\\*
    
    index from 0
    FileMatch? : . (N*,0,0)
    FileMatch? : .. (N*,0,0)
    FileMatch? : New folder (N*,0,0)
      =>return single entry
    index to 1
    index from 1
    FileMatch? : . (N*,1,0)
    FileMatch? : .. (N*,1,0)
    FileMatch? : New folder (N*,1,0)
      STATUS_NO_MORE_FILES
    ###Cleanup 0009
    Cleanup: c:\tmp\public\
    
    ###Close 0009
    Close: c:\tmp\public\
    
    ###Create 0010
    OpenDirectory : c:\tmp\public\New folder
    
    CreateFile status = 0
    ###GetFileInfo 0010
    GetFileInfo : c:\tmp\public\New folder
            GetFileInformationByHandle success, file size = 0
    
    ###SetFileInfo 0010  13
    DeleteDirectory c:\tmp\public\New folder
      DispositionInfo status = STATUS_CANNOT_DELETE
    ###Cleanup 0010
    Cleanup: c:\tmp\public\New folder
    
    ###Close 0010
    Close: c:\tmp\public\New folder
    
    ###Create 0011
    CreateDirectory : c:\tmp\public\test
    CreateFile status = 0
    ###Cleanup 0011
    Cleanup: c:\tmp\public\test
            invalid handle
    
    ###Close 0011
    Close: c:\tmp\public\test
    
    ###Create 0012
    OpenDirectory : c:\tmp\public\
    
    CreateFile status = 0
    ###QueryVolumeInfo 0012
    ###Cleanup 0012
    Cleanup: c:\tmp\public\
    
    ###Close 0012
    ###Create 0013
    Close: c:\tmp\public\
    
       CreateDisposition 0x00000001
    CreateFile : c:\tmp\public\
      AccountName: seb, DomainName: seb-win7
            OPEN_EXISTING
            ShareMode = 0x7
            FILE_SHARE_READ
            FILE_SHARE_WRITE
            FILE_SHARE_DELETE
            AccessMode = 0x80
            FILE_READ_ATTRIBUTES
            FlagsAndAttributes = 0x2000000
            FILE_FLAG_BACKUP_SEMANTICS
    
    CreateFile status = 0
    ###GetFileInfo 0013
    GetFileInfo : c:\tmp\public\
            GetFileInformationByHandle success, file size = 4096
    
    ###Cleanup 0013
    Cleanup: c:\tmp\public\
    
    ###Close 0013
    ###Create 0014
    Close: c:\tmp\public\
    
       CreateDisposition 0x00000001
    CreateFile : c:\tmp\public\*
      AccountName: seb, DomainName: seb-win7
            OPEN_EXISTING
            ShareMode = 0x7
            FILE_SHARE_READ
            FILE_SHARE_WRITE
            FILE_SHARE_DELETE
            AccessMode = 0x80
            FILE_READ_ATTRIBUTES
            FlagsAndAttributes = 0x2000000
            FILE_FLAG_BACKUP_SEMANTICS
            error code = 123
    
    CreateFile status = -123
    ###Create 0015
    OpenDirectory : c:\tmp\public\
    
    CreateFile status = 0
    ###QueryVolumeInfo 0015
    ###Cleanup 0015
    Cleanup: c:\tmp\public\
    
    ###Close 0015
    Close: c:\tmp\public\
    
    ###Create 0016
    OpenDirectory : c:\tmp\public\
    
    CreateFile status = 0
    ###FindFiles 0016
    FindFiles :c:\tmp\public\\*
            FindFiles return 4 entries in c:\tmp\public\\*
    
    index from 0
    FileMatch? : . (*,0,0)
      =>return single entry
    index to 1
    index from 1
    FileMatch? : . (*,1,0)
    FileMatch? : .. (*,1,1)
      =>return
    FileMatch? : New folder (*,1,2)
      =>return
    FileMatch? : test (*,1,3)
      =>return
    index to 4
    index from 4
    FileMatch? : . (*,4,0)
    FileMatch? : .. (*,4,1)
    FileMatch? : New folder (*,4,2)
    FileMatch? : test (*,4,3)
      STATUS_NO_MORE_FILES
    ###Cleanup 0016
    Cleanup: c:\tmp\public\
    
    ###Close 0016
    ###Create 0017
    Close: c:\tmp\public\
    
    OpenDirectory : c:\tmp\public\
    
    CreateFile status = 0
    ###QueryVolumeInfo 0017
    ###Cleanup 0017
    Cleanup: c:\tmp\public\
    
    ###Close 0017
    Close: c:\tmp\public\
    
    ###Create 0018
    OpenDirectory : c:\tmp\public\test
    
    CreateFile status = 0
    ###GetFileInfo 0018
    GetFileInfo : c:\tmp\public\test
            GetFileInformationByHandle success, file size = 0
    
    ###SetFileInfo 0018  13
    DeleteDirectory c:\tmp\public\test
      DispositionInfo status = STATUS_CANNOT_DELETE
    ###Cleanup 0018
    Cleanup: c:\tmp\public\test
    
    ###Close 0018
    Close: c:\tmp\public\test
    
    ###Create 0019
    OpenDirectory : c:\tmp\public\
    
    CreateFile status = 0
    ###QueryVolumeInfo 0019
    ###QueryVolumeInfo 0019
    ###Cleanup 0019
    Cleanup: c:\tmp\public\
    
    ###Close 0019
    ###Create 0020
    Close: c:\tmp\public\
    
    OpenDirectory : c:\tmp\public\
    
    CreateFile status = 0
    ###QueryVolumeInfo 0020
    ###Cleanup 0020
    Cleanup: c:\tmp\public\
    
    ###Close 0020
    Close: c:\tmp\public\
    
    ###Cleanup 0001
    Cleanup: c:\tmp\public\
    
    ###Close 0001
    Close: c:\tmp\public\
    
    DokanRemoveMountPoint t:
    DokanControl recieved DeviceName:\Volume{d6cc17c5-1771-4085-bce7-964f1e9f5de9}
    send release
    ^C
    W:\lofe\windows\dokan_mirror\Win32\Debug>
	

I think the reason is rather clear, is there anything wrong in my initial understanding of the problem ?

**Comment by Maxhy** [comment]
@acapola You're probably right but we cannot reproduce the issue on our side.
Which operating system are you using? Which file system are you mirroring (NTFS I believe)?

**Comment by acapola** [comment]
I use windows 7 64bit ultimate k (k for korean edition), so yes, NTFS.

**Comment by marinkobabic** [comment]
So please create a simple console application which doesh Find = FindFirstFile(filePath, &findData); 

filePath is your test directory test\* and check the handle. Run the console application from same place like mirror. Do you get invalid handle? Check the difference between your fix path and the path used in mirror.

**Comment by acapola** [comment]
Sorry I don't see what the experiment brings, all I can see is according to Microsoft's documentation.
MSDN is rather clear on the behavior of that function:

> If the function fails or fails to locate files from the search string in the lpFileName parameter, the return value is INVALID_HANDLE_VALUE and the contents of lpFindFileData are indeterminate. To get extended error information, call the GetLastError function.
> If the function fails because no matching files can be found, the GetLastError function returns ERROR_FILE_NOT_FOUND.

So we end up doing FindClose(INVALID_HANDLE_VALUE), that can't be right.

I would fix it this way:

    hFind = FindFirstFile(filePath, &findData);
    if (hFind == INVALID_HANDLE_VALUE) return 0;
    while (hFind != INVALID_HANDLE_VALUE) {
    ...

**Comment by Liryna** [comment]
4a8863e022d28ae0d4875ae989b7344140fc103a
Done.

As @acapola say, FindFirstFile can fail for any reason and a check should be add.
All other FindFirstFile in mirror.c was already protected.
