### ISSUE TITLE
IFSTest NotificationSecurityTest hangs

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#547]
# Environment
 * Windows version: 2016
 * Processor architecture: amd64 
 * Dokany version: master
 * Library type (Dokany/FUSE): dokany
 
# Check List
  - [ x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ x ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ x ] I can always reproduce the issue with the provided description below.
  - [ x ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ x ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
IFSTest NotificationSecurityTest hangs or takes very long to finish (probably because the notification does not arrive)

**Comment by Liryna** [comment]
Fixed with https://github.com/dokan-dev/dokany/commit/624ff772b9d5c052730a05d7e83e399d95931d12
