### ISSUE TITLE
Random BSOD when saving MS Word files on Windows shared Dokan drive

### ISSUE THREAD

**Issue by yin19941005** [dokan-dev/dokany#549]
# Environment
 * Server : Windows version: Windows Storage Server 2016
 * Client : Windows 7
 * Processor architecture: AMD64 (for both client and server)
 * Dokany version: 1.0.3.1000 release
 * Library type (Dokany/FUSE): Dokany
 * Microsoft Office version: MS Word 2007
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation (I didn't test with mirror because I think the issue occur in dokan1.sys)
  - [x] I can always reproduce the issue with the provided description below. But this takes some time.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Steps to reproduce : 

1. On the client VM, accessing the dokan drive, which mounted and shared out on the Server, create or open a MS Word file.

2. Modify the MS Word file and save it.

3. Repeat Step 2, until BSOD. Sometimes, the dokan will hold up. But wait for a timeout (maybe 3 minutes?), it can function again. Usually, I can reproduce the BSOD within 10 minutes.

# Description
The BSOD message is PAGE_FAULT_IN_NONPAGED_AREA (50). The causes of BSOD is on [this line of code](https://github.com/dokan-dev/dokany/blob/master/sys/dokan.c#L478). 

```
USHORT nameOffset;

... ... (Skip)

// search the last "\"
nameOffset = (USHORT)(FileName->Length / sizeof(WCHAR) - 1);
for (; FileName->Buffer[nameOffset] != L'\\'; --nameOffset)
;
```

As the `Locals` image on below you can see the FileName (PUNICODE_STRING) didn't contain any `\` character. The BSOD occur when `nameOffset = 0xFFFF` and trying to reference `FileName->Buffer[nameOffset]`. The reason why `nameOffset = 0xFFFF` is because the characteristics of the `Unsigned type`. I found a reference in [stackoverflow](https://stackoverflow.com/questions/7221409/is-unsigned-integer-subtraction-defined-behavior) : 

> A computation involving unsigned operands can never overflow, because a result that cannot be represented by the resulting unsigned integer type is reduced modulo the number that is one greater than the largest value that can be represented by the resulting type. (ISO/IEC 9899:1999 (E) §6.2.5/9)

So, when we performing `0 - 1` in `USHORT`, it will equals to `0xFFFF`. And this is dangerous and caused the BSOD. If the BSOD doesn't occur, it should be in the infinity loop and that's why it will hold up for some cases.

# Suggestion Fix

In my opinion, I think the normal case the `FileName` will contain the absolute path and we can find the `\` character but the MS Word 2007 some how some way generate an abnormal case. So, I suggest to change the code like this way : 

```
// 0 > 0 will return false and end the loop
while(nameOffset > 0)
{
	nameOffset--;

	if(FileName->Buffer[nameOffset] == L'\\') 
	{
		nameOffset++; // the next is the begining of filename
		break;
	}
}

nameOffset *= sizeof(WCHAR); // Offset is in bytes
```

I searched `] != L'\\'; --` on the entire solution and found these similar implementation may also cause the BSOD : 

[https://github.com/dokan-dev/dokany/blob/master/sys/dokan.c#L478](https://github.com/dokan-dev/dokany/blob/master/sys/dokan.c#L478)
[https://github.com/dokan-dev/dokany/blob/master/sys/event.c#L625](https://github.com/dokan-dev/dokany/blob/master/sys/event.c#L625)
[https://github.com/dokan-dev/dokany/blob/master/sys/timeout.c#L56](https://github.com/dokan-dev/dokany/blob/master/sys/timeout.c#L56)

@Liryna , do you think the suggestion fix is appropriate? Besides, are there other similar implementation may cause BSOD I couldn't found ?

# Logs
[analyze -v.txt](https://github.com/dokan-dev/dokany/files/1129890/analyze.-v.txt)

FAULTING_IP: 
dokan1!DokanNotifyReportChange0+123 [e:\islog\dev\app\dokan\dokany\sys\dokan.c @ 478]
fffff800`5c9c8ea3 0fb70441        movzx   eax,word ptr [rcx+rax*2]

PAGE_FAULT_IN_NONPAGED_AREA (50)
Invalid system memory was referenced.  This cannot be protected by try-except.
Typically the address is just plain bad or it is pointing at freed memory.
Arguments:
Arg1: ffffd88dea98a0ee, memory referenced.
Arg2: 0000000000000000, value 0 = read operation, 1 = write operation.
Arg3: fffff8005c9c8ea3, If non-zero, the instruction address which referenced the bad memory
	address.
Arg4: 0000000000000000, (reserved)

![callstack_locals_01](https://user-images.githubusercontent.com/23186757/27941845-5d29c83c-6305-11e7-8dab-3d76bbdd7f69.png)

**Comment by Liryna** [comment]
Hi @yin19941005 ,

Thank you for the great analyze as always !

I always wanted to change this sensitive piece of code ! What you proposed it perfect and would avoid at least BSOD 😮 
maybe we can make a function of this not to have code duplication ?

Just to be sure does `FileName->Length` has a correct value in here ?

**Comment by yin19941005** [comment]
Hi @Liryna ,

Sorry for delay. Yes, I think we can make a function for searching the last `\` in PUNICODE_STRING. Making it as function also make sure we have the same behavior (because the code is same) when we want to perform the same operation (in this case, searching the last `\`) in the current implementation and the future added code. So, I also prefer to make a function for it.

I think we can add the function in "sys/dokan.h" just like [some functions in it](https://github.com/dokan-dev/dokany/blob/master/sys/dokan.h#L711). Or should I create something like "dokan_utility.c" and put the functions in it?

**Comment by Liryna** [comment]
A "dokan_utility.c" would be nice. I think there is other function that I will be able to move in it 👍

**Comment by yin19941005** [comment]
Hi @Liryna ,

Sorry for delay. I stuck in some careless mistake when implementing the code. I tried to make the function more general and trying to perform some error checking l in order to fit more situations. I tested on my environment (same as I posted above) and this should fix the BSOD cause by the unsigned characteristics.
