### ISSUE TITLE
dokan1.dll is not a vaild Win32 application

### ISSUE THREAD

**Issue by hkarakose** [dokan-dev/dokany#550]
I used to run mirror.exe in VS2015. But I am trying to run mirror.exe VS2017. But I am receiving following error:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/406291/27962895-ece00a14-633b-11e7-8545-9a76446b5f09.png">

I am a java guy. How should I troubleshoot this problem?

Following is the configuration manager:

<img width="723" alt="image" src="https://user-images.githubusercontent.com/406291/27963115-a97c6c08-633c-11e7-94e8-4be56522cf43.png">

**Comment by marinkobabic** [comment]
You should set the mirror as start Project. The option should be available
in the context menu of the project.

Am 07.07.2017 16:54 schrieb "Halil Karakose" <notifications@github.com>:

**Comment by hkarakose** [comment]
OK, Thank you very much
