### ISSUE TITLE
desktop.ini is requested many times in mirror.exe

### ISSUE THREAD

**Issue by hkarakose** [dokan-dev/dokany#551]
I am trying to mount a remote folder to windows. There isn't any desktop.ini files in the source. But I see many CreateFile requests to desktop.ini file. 

 * Are these requests real file create requests?
 * I don't want any desktop.ini files in the source. How can I prevent these requests? Can I just return `STATUS_SUCCESS` as follows:

```
static NTSTATUS DOKAN_CALLBACK
MirrorCreateFile(LPCWSTR FileName, PDOKAN_IO_SECURITY_CONTEXT SecurityContext,
                 ACCESS_MASK DesiredAccess, ULONG FileAttributes,
                 ULONG ShareAccess, ULONG CreateDisposition,
                 ULONG CreateOptions, PDOKAN_FILE_INFO DokanFileInfo) {
...
  if (wcsstr(filePath, L"\\desktop.ini") != NULL) {
      return STATUS_SUCCESS;
  }
...
}

**Comment by Liryna** [comment]
Hi @hkarakose ,

Yes, this are real files requests.
https://www.computerhope.com/issues/ch001060.htm
(there is probably better link to explain this)

You can return success, but you will need to answer to read/write request of this file. it is probably better that you return access denied on this 👍

**Comment by hkarakose** [comment]
Thanks for clarification
