### ISSUE TITLE
Display contents of a subfolder in CreateFile

### ISSUE THREAD

**Issue by hkarakose** [dokan-dev/dokany#552]
I am trying to mount a remote source to windows. I can mount and see contents of a root folder.

I am trying to double-click a subfolder a see its contents. In `MirrorCreateFile`, a handle is fetched. In my case, a web service returns contents of the subfolder. What should I replace following handle with?

```
static NTSTATUS DOKAN_CALLBACK
MirrorCreateFile(LPCWSTR FileName, PDOKAN_IO_SECURITY_CONTEXT SecurityContext,
                 ACCESS_MASK DesiredAccess, ULONG FileAttributes,
                 ULONG ShareAccess, ULONG CreateDisposition,
                 ULONG CreateOptions, PDOKAN_FILE_INFO DokanFileInfo) {
...
      handle = CreateFile(filePath, genericDesiredAccess, ShareAccess,
                     &securityAttrib, OPEN_EXISTING,
                     fileAttributesAndFlags | FILE_FLAG_BACKUP_SEMANTICS, NULL);
...
```

**Comment by Liryna** [comment]
@hkarakose Humm this is up to you. It can be a webservice context or something that can help later to understand on which on text you are.

**Comment by sefai** [comment]
@hkarakose 

You must create a _**WIN32_FIND_DATAW findData**_ structure for each content and use **_FillFindData(&findData, DokanFileInfo)_** in FindFiles callback.

```
static NTSTATUS DOKAN_CALLBACK MirrorFindFiles(LPCWSTR FileName, PFillFindData FillFindData, PDOKAN_FILE_INFO DokanFileInfo) {

 // get folder contents from webservice
 ...

  foreach content in subfolder
  {
    assign findData.cFileName
    set findData.dwFileAttributes
    set findData.ftCreationTime
    set findData.ftLastAccessTime
    set findData.ftLastWriteTime
    set findData.nFileSizeHigh
    set findData.nFileSizeLow
    FillFindData(&findData, DokanFileInfo);
  }

  return STATUS_SUCCESS;
}
```

Then you must handle all the necessary logic in other callbacks. For instance if explorer, or some other programs tries to open this content you must provide your own CreateFile logic since you won't be opening a real file on the disk.

**Comment by Liryna** [comment]
@hkarakose does  @sefai answer ( ❤️ ) answer you question ?

**Comment by hkarakose** [comment]
Yes, thank you.
