### ISSUE TITLE
1.0.3 won't install on Windows 10 Pro

### ISSUE THREAD

**Issue by matswebjorn** [dokan-dev/dokany#558]
# Environment
 * Windows version: 10
 * Processor architecture: x64
 * Dokany version: 1.0.3
 * Library type (Dokany/FUSE): 
 
# Check List
  - [ x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ x ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ x ] I can always reproduce the issue with the provided description below.
  - [ x ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ x ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
When I start the installer it complains that VC++ 2015 runtime x86 is not installed, even thou it is installed as can be seen from the attached screendump. I have also tried to reinstall the runtime without success. See attached screendump.
![dokan](https://user-images.githubusercontent.com/13833726/28333750-38b44e6c-6bf9-11e7-9e25-ed252b502a62.jpg)

# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
In case of BSOD, please attach minidump or dump analyze output.

**Comment by Liryna** [comment]
Hi @matswebjorn ,

The installer is looking for VC++ 2015 version 14.0.**23918**. You will need to update the version that you have installed.

**Comment by matswebjorn** [comment]
Yes, I just realized that I needed "Microsoft Visual C++ 2015 Redistributable Update 3" from https://www.microsoft.com/en-us/download/confirmation.aspx?id=53587. Now it installs
