### ISSUE TITLE
CI: IFSTest errors when running against UNC-Path

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#560]
Microsoft IFSTest errors when running against UNC-Paths. If it is indeed not possible to run IFSTest against UNC-Paths, we should not try to invoke IFSTest when running against an UNC-Path and instead print out a a message like "Skipping IFSTest, because it cannot be run against UNC-Paths"

* Code-Change here: https://github.com/dokan-dev/dokany/blob/fc58b5b7ef25ed18a45e1ef156993391572a632c/samples/mirror_test.ps1#L115-L117
* AppVeyor log, where the issue occurs: https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.3-216/job/aewg5e3feeot3hu1#L7101

**Comment by Liryna** [comment]
Done with https://github.com/dokan-dev/dokany/commit/0da5cc963f772aa0c9a4c302b598567484f572e1
We check path if it is UNC or not
