### ISSUE TITLE
CI: Build does not fail if IFSTest cannot be run due to an error

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#561]
When Microsoft IFSTest errors during our CI-Runs on AppVeyor, we do not fail our build for some reason.
We can simulate a failing IFSTest, by passing invalid paramters or by running it against a non-existant drive.

This was noticed, when #560 was encountered, but it's a general issue that should be fixed, because AppVeyor should not be green when there is an unexpected issue launching the tests.

* AppVeyor log, where the issue occurs: https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.3-216/job/aewg5e3feeot3hu1#L7101
* Code-Change here: https://github.com/dokan-dev/dokany/blob/fc58b5b7ef25ed18a45e1ef156993391572a632c/samples/mirror_test.ps1#L115-L117
* Not sure, how a fix would look like. I am not familar with how a PowerShell script handles error codes. Maybe adding a `& powershell ` in front does the trick? Maybe not the most idiomatic way of solving this, though.

**Comment by Liryna** [comment]
Done with https://github.com/dokan-dev/dokany/commit/0da5cc963f772aa0c9a4c302b598567484f572e1
IFSTest doest not return error code, we can only analyse stderr
