### ISSUE TITLE
Network broken after redist install

### ISSUE THREAD

**Issue by CollinChaffin** [dokan-dev/dokany#562]
This needs to be PULLED!! Installing this provider totally BREAKS networking on WIN7x64! All NET USE commands no longer work generate "network name not valid" despite a simple "dir \xxxxxx\dir" on the same dir working fine. Uninstalling this DOKANY redist solves the issue.

**Comment by CollinChaffin** [comment]
I should say, it then leaves another mess with these new errors:

System error 50 has occurred.

The request is not supported.

Upon simple NET USE etc.

Why would you keep such a BROKEN installer available!?!?!?  This has completely, utterly SCREWED my WIN7x64 network stack, and I even see CLOSED issues indicating this has happened before, so is it simply never been fixed properly?  The ONLY install was this redist exe library latest release.  Then, uninstalling has now CHANGED the error from "network name is not available" despite dir \\server\share working just fine, to the error 50 now above.  I'm guessing this rewrote the network providers incorrectly as indicated in other closed issues.  Once I confirm the final fix, I will post it here for others in this bind.

**Comment by Liryna** [comment]
Hi @CollinChaffin ,

Could you use the template issue ? https://github.com/dokan-dev/dokany/blob/master/.github/ISSUE_TEMPLATE.md

I understand that you have an issue but I have no idea what version you are using, how to get the same issue you have....

Please edit this issue with proper information to make us able to help you.

**Comment by CollinChaffin** [comment]
As I suspected, this installer totally WIPED out all my providers and left me with THIS:

![snag_7-28-2017_15-58-56](https://user-images.githubusercontent.com/9301483/28736086-e124b6e8-73ad-11e7-803b-278cdf2942be.png)

**Comment by Liryna** [comment]
Here is the code that uninstall the provider:
https://github.com/dokan-dev/dokany/blob/b4dc99ad9efa0b60b05a1e37653e1fc1ba793f43/dokan/mount.c#L333

**Comment by CollinChaffin** [comment]
Well, here are all the providers gone now:

RDPNP,LanmanWorkstation,webclient

And possibly others.  See issue #200 because this EXACT same kind of thing happened.  I'll start digging through this repo code as well once I fix my totally borked workstation network stack.  Again, this was the only install/uninstall.  And, it was borked after the install and BEFORE the uninstall....so it's NOT the uninstall code - it's the INSTALL code we need to look at.

**Comment by CollinChaffin** [comment]
Okay so will be digging through the INSTALL code tonight assuming it's all here on the repo, because I went all the way to backup just to absolutely ENSURE I had the original providers before this install overwrote them, and luckily I did because there were actually more than the other system I compared to.  Here is my network provider key as of installing this UPGRADED dokan redist:

pfmunc,RDPNP,LanmanWorkstation,webclient,Dokan1

Mind you, I actually had Dokan installed, but it was the 2016 version and once I installed this latest full redist which includes the NETWORK provider.  It was that ful redist with the network provider that did this damage just downloaded TODAY and installed TODAY, so .10.8 I believe.

Luckily, if you have a backup of these keys the second I restored them without even logging out I was able to repeat the failed NET USE command in the very same open cmd window and it successfully mapped the drives.

So, I don't think it's any problem with the provider code (I'm guessing) but based on seeing these 2 critical network provider keys overwritten leaving ONLY dokan1 - that this issue is 100% the INSTALLER code we need to fix.  I apologize for being upset but bear in mind this install really did 100% break my laptop's ms-networking ability due to the lanmanworkstation provider removal right at a time when I really needed it!  Now that I've cooled down and restored it, I'll see what I can do to help get to the root cause in the code and report back here if I find anything!

P.S.  For those that also may have found their reg keys blown away, mind you that you MAY have had different providers added, but in a pinch here is a reg export of my HKLM\CurrentControlSet\Control\NetworkProvider tree ready for emergency import (please review and use at your own risk):

--------CUT BELOW THIS LINE AND SAVE AS NETPROVIDERS.REG AND DOUBLE-CLICK TO IMPORT IF NEEDED (NON-MS PROVIDERS REMOVED)-----------
````

Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\TEMPSYS\ControlSet001\Control\NetworkProvider]

[HKEY_LOCAL_MACHINE\TEMPSYS\ControlSet001\Control\NetworkProvider\HwOrder]
"ProviderOrder"="RDPNP,LanmanWorkstation,webclient"

[HKEY_LOCAL_MACHINE\TEMPSYS\ControlSet001\Control\NetworkProvider\Order]
"ProviderOrder.backup"="RDPNP,LanmanWorkstation,webclient"

````

**Comment by CollinChaffin** [comment]
Okay so it's been a while since I've had to read straight c code, but I'm approaching my 30 yr mark in the business and just spit-balling that perhaps this is the root cause of this issue:  :)

mount.c:
````
RegOpenKeyEx(HKEY_LOCAL_MACHINE, DOKAN_NP_SERVICE_KEY, 0, KEY_ALL_ACCESS,
               &key);
  RegDeleteKey(key, L"NetworkProvider");

  RegCloseKey(key);
  ````
  
  Also, it sure looks to me like both the install and uninstall routines are TOTALLY lacking any real error checking whatsoever and it is no wonder the keys are not getting set properly.  Especially when you think about simple situations like what I believe happened to me - walk through that C code as an UPGRADE where you simply install OVER THE TOP OF AN EXISTING DOKAN working install.........I believe that code does not properly handle that situation, nor case of failed installs or uninstalls with retries, etc.
  
 The first thing I would suggest is adding simple detailed install logging of every action.  Second, and it's literally been DECADES since I've had to code in straight C so this WILL be faster for you to do it since you obviously wrote this existing routine, perhaps add a bit more logic around what I would suggest as a FULL buffer read of ALL reg keys used or impacted by Dokan into an array/dict to allow for more comprehensive testing for determining needed key changes.  That would allow for many more situations and better protect the registry from unneeded changes.  In my case this was a simple UPGRADE using the full redist installer which if you think about it DID NOT EVEN NEED TO TOUCH that provider key(s) since Dokan1 was already listed, yet following the logic it still did and then obviously that uninstall code blatantly shows it doing a "RegDeleteKey(key, L"NetworkProvider");" so how on earth is this NOT breaking more people doing uninstalls?!?  Or, am I missing something where a key RESTORE is supposedly taking place?

**Comment by Liryna** [comment]
Here we remove the dokan network provider:
https://github.com/dokan-dev/dokany/blob/b4dc99ad9efa0b60b05a1e37653e1fc1ba793f43/dokan/mount.c#L345-L349
`"System\\CurrentControlSet\\Services\\dokan" DOKAN_MAJOR_API_VERSION`

Here we remore `dokan1` from the ProviderOrder
https://github.com/dokan-dev/dokany/blob/b4dc99ad9efa0b60b05a1e37653e1fc1ba793f43/dokan/mount.c#L351-L371

But @CollinChaffin like I said before, I have no idea what version you were using. We changed this code a long time ago when it could create such behavior you describe.

I looked at the code again and could not find anyway how this could happen.

**Comment by Liryna** [comment]
@CollinChaffin let me know if you get more information on this and I will reopen it.
