### ISSUE TITLE
Download link - wrong signature

### ISSUE THREAD

**Issue by s-stexx** [dokan-dev/dokany#563]
# Environment
 * Windows version: 7
 * Processor architecture: x86
 * Dokany version: Newest
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [-] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Bug in GitHub Download link. Signatures do not match: If I click on your newest Download link to the Dokany_Redist.exe my Browser 

Script blocker detects a Signature mismatch. I can continue to get it, but I am not sure if your Github page is maybe infected with malware. The situation is worse: I can not find any MD5 or SHAx Sum for the download link.

# Logs
I can not upload pictures on github ?! See cutted screenshot on my Server: 
https://mesom.de/dateien/github_issue/mismatch.png

**Comment by Liryna** [comment]
Hi @s-stexx,

I have no problem to download the release. It is maybe a github issue on on of their server you are using.
We cannot do much about it :sad:

**Comment by s-stexx** [comment]
Can you maybe please provide a md5 or a sha1 to me (or the newest Minor Dokany_Redist.exe) ?

**Comment by Liryna** [comment]
DokanSetup_redist.exe - md5: 9797203EF8E7AA488274C36767FD819C
sha256: 38710F89F716326AB0A83DE17270B70F4D96452DC0B34B654EA1B29B5B17BAB7

**Comment by s-stexx** [comment]
Thank you very much. They match!
