### ISSUE TITLE
provide option mount img as PHYSICALDRIVE

### ISSUE THREAD

**Issue by crazypenguincode** [dokan-dev/dokany#564]
# Environment
 * win10 x64 1.03 
 
# Description

* dokany is very interesting，as i know ,i can use dokany interface mount a raw image as logical partition(like:letter z:), may be the image is a dd of the entire disk  contain muti partitions. can dokany do it, or have any suggestion? thank you

**Comment by crazypenguincode** [comment]
mip can mount a dd image as a PHYSICALDRIVE ,when use cmd : wmic diskdrive list brief
shows :
StorLib Virtual Storage    \\.\PHYSICALDRIVE7  StorLib Virtual Storage    1           42949672960
StorLib Virtual Storage    \\.\PHYSICALDRIVE8  StorLib Virtual Storage    2           0
dokany mirror.exe can mount as letter

**Comment by Liryna** [comment]
Hello, 

Unfortunately this is not possible by default with dokany but you can create a file system using Dokany that would translate the Img file into the FS. Some people already did by using grub source code and ext4 FS. If you make a research in the repository you should find some post talking about it.
