### ISSUE TITLE
Drive letter becomes unassignable after the program crashed

### ISSUE THREAD

**Issue by lins05** [dokan-dev/dokany#568]
# Environment
 * Windows version: win7 sp1
 * Processor architecture: x64
 * Dokany version: 1.0.2/1.0.4
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [X] I can always reproduce the issue with the provided description below.
  - [X] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

When the file system program that uses dokan crashed (e.g. segfault, or killed in task manager), the drive letter it used can't be assigned anymore. If we try to mount with the old drive letter, we'll get the error "Can't assign a drive letter" (we get the same error if we use mirror.exe to mount to that letter). The only way to get around that is either to use another drive letter, or reboot the system.

After the program crashed, `dokanctl /l` shows there is no mountpoints in use, and `dokanctl /u S` with admin privilege (s is the drive letter we use) shows:

```sh
c:\Program Files\Dokan\Dokan Library-1.0.4\>dokanctl.exe /u S

Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
send global release for S:
DokanError: Ioctl failed with code 122
Failed to unmount: S:
Unmount status = 1
```

One interesting thing we note is: after the program crashed and the letter become unassignable, we can run mirror.exe with admin privilege to assign that letter. But if I try to enter the drive from explorer, it would show an error like:

![explorer_2017-09-01_11-43-01](https://user-images.githubusercontent.com/717363/29966681-9613fd68-8f45-11e7-9f5f-9dc55e6bda59.png)

**Comment by Liryna** [comment]
Hi @lins05 ,

Is this the same as https://github.com/dokan-dev/dokany/issues/332 ?

**Comment by lins05** [comment]
@Liryna Yes I think so (i search the issues with keywords like "drive letter crash" but that one isn't in the search result :(  .

I checked the code and find we're also using the `DOKAN_OPTION_CURRENT_SESSION` flag, so it should be the same problem the #523 tries to fix. I'll try the [test build](https://github.com/dokan-dev/dokany/pull/523#issuecomment-308319454) to see if it fixed the issue and report the result here.

**Comment by Liryna** [comment]
@lins05 have you been able to do the test ?

**Comment by Liryna** [comment]
@lins05 let me known if you have any update on this
