### ISSUE TITLE
Warnings/exceptions in dokan-java log file

### ISSUE THREAD

**Issue by cplerch** [dokan-dev/dokany#570]
# Environment
 * Windows version:  Windows 10 Pro
 * Processor architecture: x64
 * Dokany version:  latest (1.0.4)
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I tested mirroring with dokan-java. It generally works fine. Just wanted to report some of the warnings and exceptions I found in the log file:
 * Invalid Structure field in class com.sun.jna.platform.win32.WinBase$WIN32_FIND_DATA, field name 'cFileName' (class [C): Arrays of length zero not allowed: class [C
 * com.dokany.java.DokanyOperationsProxy    : GetFileInformation: /$RECYCLE.BIN/S-1-5-21-514270414-2989288975-3594427135-1002/
   com.dokany.java.DokanyOperationsProxy    : Error reading info: The System cannot find the requested path
 * com.dokany.java.DokanyOperationsProxy    : GetFileInformation: /$Extend/
   com.dokany.java.DokanyOperationsProxy    : Error reading info: The System cannot find the requested path

Are these warnings, particullary the first one listed above, reasons for concern?

# Logs
Pls find attached:
[20170907T093121.zip](https://github.com/dokan-dev/dokany/files/1283834/20170907T093121.zip)

**Comment by Liryna** [comment]
Hello @cplerch ,

Thank you for the report!
Does this should not be opened in https://github.com/dokan-dev/dokan-java ?

**Comment by cplerch** [comment]
Perhaps, however I'm still not sure about the origin of these warnings: dokany driver/dlls or dokan-java code. Please decide!

**Comment by Liryna** [comment]
This warning comes from the java wrapper @cplerch .
It needs to be reported on the java wrapper repository.

**Comment by cplerch** [comment]
OK, will move it over - you can close this one.
