### ISSUE TITLE
Include Dokan Chocolatey package in build process

### ISSUE THREAD

**Issue by er1z** [dokan-dev/dokany#574]
Is it possible for developers to maintain a Chocolatey package of Dokany? It would keep things fresh instead of waiting for Choco's package maintainer action.

https://chocolatey.org/packages/dokany

**Comment by Liryna** [comment]
If this can be included in the build process, I can update the chocolatey package during release time.

Hi @ulex, are you still maintaining the package ?

**Comment by bcurran3** [comment]
v1.05 has been pushed to Chocolatey

@Liryna I can add you as maintainer of the packages

sources are here:
https://github.com/bcurran3/ChocolateyPackages/tree/master/dokany
https://github.com/bcurran3/ChocolateyPackages/tree/master/dokany-redistributable

**Comment by Liryna** [comment]
Thanks a lot @bcurran3 !

Will take a look to see how to integrate to the build release 👍

**Comment by bcurran3** [comment]
Great. It would really just require updating the chocolateyinstall.ps1 script with current dl link and checksum. Hmmm...and the nuspec with the version. At some point I might set it up with the AutoUpdate (AU) script. I have to get over the learning curve to finish setting it up and create the scripts for a lot of programs. So it's on a when I get the time basis.

**Comment by bcurran3** [comment]
v1.0.5 is "live" in the Chocolatey community feed

**Comment by Liryna** [comment]
Thanks a lot @bcurran3 !
Will keep the issue open for the time the 1.0.6 will comes in case I need help.

**Comment by Liryna** [comment]
Integrate Dokan ChocolateyPackages creation in the existing build script would be great to help in the release process.

The script used is [build.bat](https://github.com/dokan-dev/dokany/blob/master/dokan_wix/build.bat). The creation of the Chocolatey packages would be at the end.

The goal would be to use the @bcurran3 nuspec in a git submodule.
https://github.com/bcurran3/ChocolateyPackages/tree/master/dokany
https://github.com/bcurran3/ChocolateyPackages/tree/master/dokany-redistributable
To update the version from [version.xml](https://github.com/dokan-dev/dokany/blob/master/dokan_wix/version.xml#L10) (by using powershell xml read for example).

And the AutoUpdate like @bcurran3 said would be really great ! But keep in mind after uninstall, it needs a reboot to be able to reinstall Dokan ! (Kernel driver limitation)
