### ISSUE TITLE
All operations is using the mount user access token will cause Security Holes

### ISSUE THREAD

**Issue by yin19941005** [dokan-dev/dokany#575]
# Environment
 * Windows version: Windows 10 build 1607 (64 bit)
 * Processor architecture: AMD64
 * Dokany version: Dokan-1.0.5.1000 release
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
The following are examples which demonstrate how the security holes will occur:
### User without write permission can write file if mirror.exe started by another authorized user
Use a local admin (called `VMBB-PC6`) to mount drive with this command : `mirror.exe /r C:\dokan_temp /l Z /d /s`

1. Create a text file, e.g. testing.txt, with the same local admin account
2. Modify and Save the text file with the same local admin account
3. Set **deny write permission** to **`user01`** (another user, without admin right) with the text file (show in the image1)
4. Switch Windows User to `user01`
5. Try to modify and save the txt file with `user01`.
- **The expected behavior**:
`user01` is able to open the file but not able to write and save the text file through the mirror drive. (confirmed with physical path)
- **The actual behavior**:
`user01` is able to open, write and save the text file through the mirror drive. (**Security Issue**)

### User without permission can modify the [DACL](https://msdn.microsoft.com/en-us/library/windows/desktop/aa446597(v=vs.85).aspx) of the file if mirror.exe started by another authorized user

Use a local admin (called `VMBB-PC6`) to mount drive with this command : `mirror.exe /r C:\dokan_temp /l Z /d /s`

1. Create a text file, e.g. testing.txt, with the same local admin account
2. Modify and Save the text file with the same local admin account
3. Check the file owner, it should be the local admin account (show in the image2)
4. Switch Windows User to `user01`
5. Try to modify the text file DACL with `user01`.
- **The expected behavior**:
`user01` is able to view the DACL but not modify the DACL through the mirror drive. (confirmed with physical path)
- **The actual behavior**:
`user01` is able to view, modify the DACL through the mirror drive. (**Security Issue**)

## Analytics
In my opinion, the problem is we are using the `running thread access token` (i.e. the user that start the mirror.exe) to perform all the operation without any permission checking. Of course, `DOKAN_OPTION_CURRENT_SESSION` option can be a workaround solution because this will simply block all other users. As I know, the _libfuse Library_ got a option called `default permissions` to perform permission checking for the mounted drive. So, I suggest to **add an option in dokan similar with the `default permissions` option**.

I think it is nice a idea that to having a option instead of forcing everyone to perform the permission checking. @Liryna, what do you think about it?

# Logs
### Image1:
![write_error_01](https://user-images.githubusercontent.com/23186757/30692493-5adc3616-9efe-11e7-9ebd-182c3d66de7b.png)
### Image2:
![dacl_error_01](https://user-images.githubusercontent.com/23186757/30949015-80fccd9a-a446-11e7-95b6-ae79dd61370e.png)

**Comment by yin19941005** [comment]
Hi all,

I think I basically find a solution to deal with this issue. The idea itself is pretty simple : **Impersonate the caller user** by [`ImpersonateLoggedOnUser`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa378612(v=vs.85).aspx). However, I facing some difficulties.

### Suggest Solution : Impersonate the caller user

In current mirror implementation, actually, we had already get the caller access token and we used it to print user's name in debug mode by calling `PrintUserName` function in mirror. At this line [https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L107](https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L107), the handle is actually the caller access token.

So, we can doing something like this in the `MirrorCreateFile` function : 
```
...
...

  HANDLE userTokenHandle = DokanOpenRequestorToken(DokanFileInfo);

  if (userTokenHandle == INVALID_HANDLE_VALUE) {
	  DbgPrint(L"  DokanOpenRequestorToken failed\n");
	  // Handling the error
  }

...
...
...

      if (!ImpersonateLoggedOnUser(userTokenHandle)) {
          DbgPrint(L"  Create : ImpersonateLoggedOnUser failed.\n");
          // Handling the error
      }

      // FILE_FLAG_BACKUP_SEMANTICS is required for opening directory handles
      handle =
          CreateFile(filePath, genericDesiredAccess, ShareAccess,
                     &securityAttrib, OPEN_EXISTING,
                     fileAttributesAndFlags | FILE_FLAG_BACKUP_SEMANTICS, NULL);

      // Clean Up operation for impersonate
      RevertToSelf();

...
...
...
```

I tested to call `ImpersonateLoggedOnUser` before every time we call `CreateFile` or `CreateDirectory`, Windows will use the caller access token to perform the operation. This means, Windows will perform the permission checking with caller access token, set the file owner as caller user, etc. And this issue can be resolved.

However, this comes with a little problem and some difficulties.

### Little problem
The little problem is, when the mirror is started by a normal user, we cannot impersonate as other user and receive `ERROR_BAD_IMPERSONATION_LEVEL`. This would occur when you try to switch Windows User and cannot access the mirror drive. But, if the user is a normal user, it shouldn't generate serious security issue. So, we may remind the user when using the `ImpersonateUserOption` (Suggested new option for dokan), they should mount with administrator right.

### Difficulties
When we get the caller access token, we are rely on [`IO_STACK_LOCATION.Parameters.Create.PIO_SECURITY_CONTEXT`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff550659(v=vs.85).aspx) from the IRP. The implementation in dokany in this link [https://github.com/dokan-dev/dokany/blob/master/sys/access.c#L89](https://github.com/dokan-dev/dokany/blob/master/sys/access.c#L89). This is the limitation from Windows, so, we are only able to get the caller access token in the `MirrorCreateFile` function.

**However, we did call `CreateFile` on other mirror functions.** The read function on [here](https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L509), the write function on [here](https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L565), get File Information on [here](https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L693).

@Liryna , I wonder why we are calling the `CreateFile` on these functions? If it is mis-cleanuped the handle, should we simply return `ERROR_INVALID_HANDLE` (i.e. `STATUS_INVALID_HANDLE` NTSTATUS) instead of trying to re-open it? I checked the `Git History`, this code is since this commit `Move to clang format llvm` 15343707589097d1b6941946506a5b9dac5d4eda. So, I didn't got any idea in which cases this will happen.

**Comment by Liryna** [comment]
Hi @yin19941005 ,

I will look at your issue this weekend. Just a quick answer to now: We call CreateFile in Read/Write because it can happen (Microsoft doc also say it) that a read/write can happen after a cleanup call and it needs to be successful.
See https://github.com/dokan-dev/dokany/issues/210#issuecomment-236972909

**Comment by yin19941005** [comment]
Hi @Liryna ,

Thank you for your response! It's helps me a lot to understand it!

Base on my understanding, the handle in Windows actually is a capacity in [Capability-based security](https://en.wikipedia.org/wiki/Capability-based_security). This means it not only identifies an object, but **also associates access rights** (by wiki). This means the security checking will be done on the `IRP_MJ_CREATE` routine functions because the returned handle is already granted the access right. In fact, the security checking **must be** done on the `IRP_MJ_CREATE` routine functions because we are only able to get the caller access token on these functions by the design of the [`IO_STACK_LOCATION`](https://msdn.microsoft.com/en-us/library/windows/hardware/ff550659(v=vs.85).aspx) structure.

I am still studying on it, so I am not pretty sure but it seems we can skip the security check when re-open the handle in Read/Write. Base on the document, it seems only _system components_ might hold outstanding references to the file object. If we did perform the security check on `MirrorCreateFile` function, I think these component were already passed the security check and _system components_ sounds is safe even we don't check it. However, these kind of Read/Write operation (re-open the handle before perform) will generate some strange audit log : these operations are always done by the the mount user (the user who start mirror) instead of those _system components_.

I will keep study it to see is there any findings on how to handle these Read/Write cases.

**Comment by Liryna** [comment]
Hi @yin19941005 ,

I understand what you mean here. When using normal users for the mount, you will always get a limitation to create other files for other users. I would say, it always has to be mounted as Admin if you want to handle createfile for other users.

I agree we do not use in the mirror the security access to read/write but "normally" it should not really hurt since if right is called, it means security check passed in createfile.

I hope I understood exactly what you mean ! Really great that you take a look at it 👍

**Comment by yin19941005** [comment]
Hi @Liryna ,

Sorry for the late reply. Yes, I think you had understood exactly what I mean!

I agree "_it always has to be mounted as Admin if you want to handle createfile for other users_". I think adding some message to remind the `Impersonate Option` is requiring the administrator right will be enough to avoid misuse of this option.

I will make a pull request for the `Impersonate Option`.

**Comment by Liryna** [comment]
This has been fixed with @yin19941005 PR https://github.com/dokan-dev/dokany/pull/582

Thank you for your report and work !!
