### ISSUE TITLE
DokanFreeFCB has potential race condition issues.

### ISSUE THREAD

**Issue by kuaaan** [dokan-dev/dokany#58]
originally, dokan.sys [6.0.0] source code had a race condition issues as follows : 
<pre><code>
NTSTATUS
DokanFreeFCB(
  __in PDokanFCB Fcb
  )
{
        // sth is omitted ...

	Fcb->FileCount--;  // here!!

	if (Fcb->FileCount == 0) {  // and here!!

		RemoveEntryList(&Fcb->NextFCB);
</code></pre>

current dokan.sys is fixed as follows : 

<pre><code>
NTSTATUS
DokanFreeFCB(
  __in PDokanFCB Fcb
  )
{
	PDokanVCB vcb;

        // sth is omitted...

	InterlockedDecrement(&Fcb->FileCount);  // fixed code...

	if (Fcb->FileCount == 0) {

		RemoveEntryList(&Fcb->NextFCB);

</code></pre>

I think current code is much better... but not perfect.
there is still race condition issue between InterlockedDecrement and if statement.
If multiple threads execute "InterlockedDecrement(&Fcb->FileCount);" statement at the same time, above code is risk that no thread enter "if (Fcb->FileCount == 0)" block.

It should be fixed as follows : 

<pre><code>
NTSTATUS
DokanFreeFCB(
  __in PDokanFCB Fcb
  )
{
	LONG		FileCount = 0;
	// sth is omitted...

	FileCount = InterlockedDecrement(&Fcb->FileCount);		// should be fixed like this!!

	if (FileCount == 0) {

		RemoveEntryList(&Fcb->NextFCB);

</code></pre>

According to the above code, even if multiple thread enter DokanFreeFCB at the same time, only (and at least) one thread will enter "if (FileCount == 0)" block.

**Comment by Liryna** [comment]
Hi @kuaaan ,

Thanks for your report ! Always good to have a code review!
But it seems that Fcb is well protected with ExAcquireResourceExclusiveLite.
https://github.com/dokan-dev/dokany/blob/master/sys/create.c#L175

Don't you think ?

**Comment by kuaaan** [comment]
Yes. you're right.
I missed locking code :)
It looks find.
Sorry for false positive reporting!
