### ISSUE TITLE
Fallback to existing system file access

### ISSUE THREAD

**Issue by rjamesnw** [dokan-dev/dokany#583]
Quick question: Do I have to implement the whole system (as in my own FAT/NTFS/Etc) or, at my programs discretion, ignore certain file read/write requests and have it fall back to the default file system driver?  I'm interested in intercepting file reads/writes in only some but not all cases.

Also, for .Net, I assume I have to:
1. Install the driver before development (and write an installer for my end users?)
2. Install the NuGet package after install.

And that's all I need to get started for .Net?

**Comment by Liryna** [comment]
Hi @rjamesnw ,

Dokan make you able to create whatever filesystem you would like, not only a mirror of an existing file system.
FS can be a view of SQL server, websites ....

I think you are more interested in a [MiniFilter](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/file-system-minifilter-drivers)

**Comment by rjamesnw** [comment]
Thanks - yeah, I saw that already; not sure I want to go down that road yet lol. ;)

**Comment by Liryna** [comment]
Well it is the purpose of it and I can understand your reaction :'(
Dokan would not really help unless you create a mirror and would say to only use the mirror but probably overkill if you just wanna look at the read/write.

Does this answer your questions ?
