### ISSUE TITLE
Hang when using only one Dokan thread

### ISSUE THREAD

**Issue by ivorytir** [dokan-dev/dokany#586]
# Environment
 * Windows version: 7
 * Processor architecture: x86
 * Dokany version: 1.0.5
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [X] I can always reproduce the issue with the provided description below.
  - [X] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Running [winfstest](https://bitbucket.org/billziss/secfs.test) on a mirror-mounted drive with only one Dokan thread hangs and eventually errors out. There seem to be a deadlock somewhere in the Dokan driver layer causing the hang during "Cleanup". The hang is eventually broken by Irp 15 second timeout so the test continues but the results are messed up from that point on. Using 2 or more threads workarounds the issue. Note that this didn't happen in pre-v1.0 version of Dokan.

Command used to mount the drive:
mirror.exe /r c:\Temp /l q /t 1

# Logs
[hang.log](https://github.com/dokan-dev/dokany/files/1376140/hang.log)

**Comment by Liryna** [comment]
Hi @ivorytir ,

Thank you for your report.
Do you have exactly the test winfstest that hang ?

**Comment by ivorytir** [comment]
Hi @Liryna,
I believe any test has an issue when the ThreadCount is 1. Tried just now, got 15 second hang/delay for the first test from the **00.t**:
`expect("CreateFile %s GENERIC_WRITE 0 0 CREATE_NEW FILE_ATTRIBUTE_NORMAL 0" % name, 0)`

**Comment by kkrriiss** [comment]
Hi, is this problem solved?

**Comment by kkrriiss** [comment]
Hi, is this problem solved?

**Comment by Liryna** [comment]
All 500 tests now passes with mirror using one thread 👍
