### ISSUE TITLE
Improve documentation grammar and spelling 

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#587]
Currently [the documentation](https://dokan-dev.github.io/dokany-doc/html/) has a few grammar and spelling mistakes.

A native speaker or someone with a very good command of English should proofread it and submit changes as a pull request.
The documentation is automatically generated from [the source code](https://github.com/dokan-dev/dokany/blob/master/dokan/dokan.h) using Doxygen on every automatic build of the master branch and pushed to https://dokan-dev.github.io/dokany-doc/html/

To generate the documentation locally, one needs to install Doxygen and run `doxygen` inside the "documentations"-folder.

While one is at it, one can have a look at the homepage as well: https://dokan-dev.github.io / https://github.com/dokan-dev/dokan-dev.github.io.

**Comment by klyap** [comment]
I can help!

**Comment by Rondom** [comment]
We do not need any changes to the readme or mainpage.md at this point (PRs open for that already).

dokan.h still needs some improvement.

**Comment by t-miller** [comment]
I'm on it!
