### ISSUE TITLE
\cert\dokan-import.ps1 script should warn if SecureBoot is enabled (PowerShell)

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#589]
`\cert\dokan-import.ps1` ([documentation here](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot)) is a PowerShell-script used for installing a self-signed certificate that is used for development builds and configures Windows to run testsigned drivers. This does not work on newer Windows versions when SecureBoot is enabled.

The script should not proceed or output a warning if SecureBoot is enabled to avoid confused users that want to test a bugfix.

**Comment by Dumbaz** [comment]
https://technet.microsoft.com/de-de/library/jj603041(v=wps.630).aspx
> This cmdlet requires that Windows PowerShell be run in administrator mode.

Returns either enabled, disabled or not supported state of secure boot. If it´s not solved tomorrow I will do so, have no Windows PC at hand right now.

**Comment by Rondom** [comment]
Oh, and it should probably also deal with the fact that the Cmdlet is not available (Windows 7???)

**Comment by Liryna** [comment]
@Hi Dumbaz ,

If you are still interested, this is still available 😎
