### ISSUE TITLE
WiX Installer - Include VC redist version in error message when not installed

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokany#590]
The WiX Installer currently shows an error when the vc++ redistributable is missing from the system and needs to be installed. We should include the minimum version needed in the message to properly inform which version is needed. We already faced a case where redistributable 2015 was already installed but an older version was installed and the user did not understand what was wrong. This would solve the unclear message.

We would just add "14.0.23918" in the message but it would be better if this version is a wix variable reused in the message and in the condition.

https://github.com/dokan-dev/dokany/blob/master/dokan_wix/Dokan_x64.wxs#L135-L136
https://github.com/dokan-dev/dokany/blob/master/dokan_wix/Dokan_x86.wxs#L124

**Comment by Rondom** [comment]
Also state that it is the minimum version, i.e. any later version is fine.

**Comment by Liryna** [comment]
Done with https://github.com/dokan-dev/dokany/commit/08aeab6ff1305e9eec2799f7f6a2b97d28781dec
