### ISSUE TITLE
dokanctl /? does not print help

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#593]
`dokanctl /?` will complain about an unknown parameter and tell you to run `dokanctl /?`.
Running `dokanctl` without parameters prints usage information.

Expected: 
`dokanctl /?` prints usage information

https://github.com/dokan-dev/dokany/blob/master/dokan_control/dokanctl.c

**Comment by Liryna** [comment]
Done with https://github.com/dokan-dev/dokany/commit/ba2109895215e57c8da646d18ecf532413df4263
