### ISSUE TITLE
Directory attributes lost after copying from outside mirror to mirror drive

### ISSUE THREAD

**Issue by yin19941005** [dokan-dev/dokany#598]
# Environment
 * Windows version:  Windows 10 PRO (1607) 64 bit
 * Processor architecture: AMD64
 * Dokany version: 1.0.5.1000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Step to reproduce

1. Prepare a directory with hidden attribute outside mirror drive
2. Copy it to mirror drive
3. Check the attribute (Attribute already lost!!)

# Description
This issue is similar with #584 but the fix for file attribute lost fix seems not enough for directory attribute lost fix. I couldn't found any document describe the process of copying the file or directory to another drive and how to handle their attributes, so, the following is my hypothesis based on the log from mirror.

From the copy file log below, you can see the file is created by `CreateFile` function with `CREATE_NEW` create disposition and having `FILE_ATTRIBUTE_ARCHIVE` and `FILE_ATTRIBUTE_READONLY`. The following calls didn't called the `SetFileAttributes` functions (it trying to set 0x0 to it, this means MUST NOT changed). However, the out coming file is correctly contain the file attribute, this means the `CreateFile` function will set the file attribute.

In the copy directory case, you can see the `SetFileAttributes` functions is also not called at all. But the expected out coming directory should contain the attribute. Since we cannot use `CreateFile` to create directory so we use `CreateDirectory` instead. And obviously, the `CreateDirectory` won't handle the attribute (it don't have parameter for attribute). 

So, I guess the Windows is expecting we will set the attribute for directory if it called the `IRP_MJ_CREATE` routine functions with `FILE_WRITE_ATTRIBUTES` desired access and input attribute.

# Suggest Solution
Set the attribute for directory if `FILE_WRITE_ATTRIBUTES` is set and passed in `FileAttributes` is non-zero.

# Logs
### Copy Directory Log (with Attribute)
###Create 0022
CreateFile : C:\dokan_temp\Attribute_test
  AccountName: VMBB-PC6, DomainName: VMBB-PC13-PC
	ShareMode = 0x3
	FILE_SHARE_READ
	FILE_SHARE_WRITE
	DesiredAccess = 0x100001
	FILE_READ_DATA
	SYNCHRONIZE
	FlagsAndAttributes = 0x200080
	FILE_ATTRIBUTE_NORMAL
	FILE_FLAG_OPEN_REPARSE_POINT
	CREATE_NEW

CreateFile status = 0
###GetFileInfo 0022
GetFileInfo : C:\dokan_temp\Attribute_test
	GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 16
	result =  0
	FileStandardInformation
	DispatchQueryInformation result =  0
###GetFileInfo 0022
GetFileInfo : C:\dokan_temp\Attribute_test
	GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 16
	result =  0
	FileBasicInformation
	DispatchQueryInformation result =  0
###Cleanup 0022
Cleanup: C:\dokan_temp\Attribute_test

###Close 0022
Close: C:\dokan_temp\Attribute_test

```
###Create 0023
CreateFile : C:\dokan_temp\Attribute_test
  AccountName: VMBB-PC6, DomainName: VMBB-PC13-PC
	ShareMode = 0x0
	DesiredAccess = 0x17019b
	DELETE
	FILE_READ_DATA
	FILE_READ_ATTRIBUTES
	FILE_READ_EA
	READ_CONTROL
	FILE_WRITE_DATA
	FILE_WRITE_ATTRIBUTES
	FILE_WRITE_EA
	WRITE_DAC
	SYNCHRONIZE
	STANDARD_RIGHTS_READ
	STANDARD_RIGHTS_WRITE
	STANDARD_RIGHTS_EXECUTE
	FlagsAndAttributes = 0x2
	FILE_ATTRIBUTE_HIDDEN
	OPEN_EXISTING

CreateFile status = 0
```
###GetFileInfo 0023
GetFileInfo : C:\dokan_temp\Attribute_test
	GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 16
	result =  0
	FileStandardInformation
	DispatchQueryInformation result =  0
###GetFileInfo 0023
GetFileInfo : C:\dokan_temp\Attribute_test
	GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 16
	result =  0
	FileBasicInformation
	DispatchQueryInformation result =  0
###SetFileInfo 0023  4
SetFileAttributes C:\dokan_temp\Attribute_test 0x0
Set 0x00000000 to FileAttributes means MUST NOT be changed. Didn't call SetFileAttributes function. 

SetFileTime C:\dokan_temp\Attribute_test

	DispatchSetInformation result =  0
###GetFileInfo 0023
GetFileInfo : C:\dokan_temp\Attribute_test
	GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 16
	result =  0
	FileNetworkOpenInformation
	DispatchQueryInformation result =  0
###Cleanup 0023
Cleanup: C:\dokan_temp\Attribute_test

###Close 0023
Close: C:\dokan_temp\Attribute_test

### Copy File Log (With Attribute)
###Create 0028
CreateFile : C:\dokan_temp\Attribute_test.txt
  AccountName: VMBB-PC6, DomainName: VMBB-PC13-PC
	ShareMode = 0x0
	DesiredAccess = 0x17019f
	DELETE
	FILE_READ_DATA
	FILE_READ_ATTRIBUTES
	FILE_READ_EA
	READ_CONTROL
	FILE_WRITE_DATA
	FILE_WRITE_ATTRIBUTES
	FILE_WRITE_EA
	FILE_APPEND_DATA
	WRITE_DAC
	SYNCHRONIZE
	STANDARD_RIGHTS_READ
	STANDARD_RIGHTS_WRITE
	STANDARD_RIGHTS_EXECUTE
	FlagsAndAttributes = 0x8000021
	FILE_ATTRIBUTE_ARCHIVE
	FILE_ATTRIBUTE_READONLY
	FILE_FLAG_SEQUENTIAL_SCAN
	CREATE_NEW

CreateFile status = 0
###GetFileInfo 0028
GetFileInfo : C:\dokan_temp\Attribute_test.txt
	GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 33
	result =  0
	FileStandardInformation
	DispatchQueryInformation result =  0
###GetFileInfo 0028
GetFileInfo : C:\dokan_temp\Attribute_test.txt
	GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 33
	result =  0
	FileBasicInformation
	DispatchQueryInformation result =  0
###GetFileInfo 0028
GetFileInfo : C:\dokan_temp\Attribute_test.txt
	GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 33
	result =  0
	FileStandardInformation
	DispatchQueryInformation result =  0
###GetFileInfo 0028
GetFileInfo : C:\dokan_temp\Attribute_test.txt
	GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 33
	result =  0
	FileInternalInformation
	DispatchQueryInformation result =  0
###QueryVolumeInfo 0028
GetVolumeInformation: max component length 255
GetVolumeInformation: file system name NTFS
GetVolumeInformation: got file system flags 0x03e700ff, returning 0x0004000f
###GetFileInfo 0028
GetFileInfo : C:\dokan_temp\Attribute_test.txt
	GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 33
	result =  0
	FileBasicInformation
	DispatchQueryInformation result =  0
###GetFileInfo 0028
GetFileInfo : C:\dokan_temp\Attribute_test.txt
	GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 33
	result =  0
	FileStandardInformation
	DispatchQueryInformation result =  0
###SetFileInfo 0028  20
SetEndOfFile C:\dokan_temp\Attribute_test.txt, 15
	DispatchSetInformation result =  0
###QueryVolumeInfo 0028
GetVolumeInformation: max component length 255
GetVolumeInformation: file system name NTFS
GetVolumeInformation: got file system flags 0x03e700ff, returning 0x0004000f
###WriteFile 0028
WriteFile : C:\dokan_temp\Attribute_test.txt, offset 0, length 15
	write 15, offset 0

###SetFileInfo 0028  4
SetFileAttributes C:\dokan_temp\Attribute_test.txt 0x0
Set 0x00000000 to FileAttributes means MUST NOT be changed. Didn't call SetFileAttributes function. 

SetFileTime C:\dokan_temp\Attribute_test.txt

	DispatchSetInformation result =  0

###GetFileInfo 0028
GetFileInfo : C:\dokan_temp\Attribute_test.txt
	GetFileInformationByHandle success, file size = 15
FILE ATTRIBUTE  = 32
	result =  0
  unknown type:55
	DispatchQueryInformation result =  c000000d
###GetFileInfo 0028
GetFileInfo : C:\dokan_temp\Attribute_test.txt
	GetFileInformationByHandle success, file size = 15
FILE ATTRIBUTE  = 32
	result =  0
	FileNetworkOpenInformation
	DispatchQueryInformation result =  0
###GetFileInfo 0028
GetFileInfo : C:\dokan_temp\Attribute_test.txt
	GetFileInformationByHandle success, file size = 15
FILE ATTRIBUTE  = 32
	result =  0
	FileNetworkOpenInformation
	DispatchQueryInformation result =  0
###Cleanup 0028
Cleanup: C:\dokan_temp\Attribute_test.txt

###Close 0028
Close: C:\dokan_temp\Attribute_test.txt

**Comment by Liryna** [comment]
https://github.com/dokan-dev/dokany/pull/599#issuecomment-491543897
