### ISSUE TITLE
dokan_vector.h missing in 2.0 beta binary release

### ISSUE THREAD

**Issue by bailey27** [dokan-dev/dokany#602]
I installed DokanSetup_redist-2.0.0-BETA1.exe , and dokan_vector.h is missing in the development files.

**Comment by bailey27** [comment]
I got it from github.

**Comment by Rondom** [comment]
Can you submit a PR against the installer in the Corillian-asyncio branch to add the file to be installed? You have to do the change for both x86 and x64.

**Comment by bailey27** [comment]
I added it to both.  I created a pull request.  I've never done a pull request on a branch before, so I hope I did it right.

**Comment by Liryna** [comment]
Fixed with your PR @bailey27 https://github.com/dokan-dev/dokany/pull/604

Thanks you for the contribution as always !
