### ISSUE TITLE
FUSE - Cannot mount as read-only

### ISSUE THREAD

**Issue by leochou0729** [dokan-dev/dokany#606]
When I use encfs4win, I cannot mount it as read only using "-o rdonly" option. I have no idea why fuse mirror doesn't support read-only mode but mirror has a /w option. Thanks!

**Comment by Liryna** [comment]
Hi @leochou0729 ,

You are right `DOKAN_OPTION_WRITE_PROTECT` https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L1565
is not used in the fuse options for now. 
Here is how it is handle for debug option:
https://github.com/dokan-dev/dokany/blob/12ae5ecf999f1d2741b4a86f6d01dc49be1ca1bf/dokan_fuse/src/dokanfuse.cpp#L581
https://github.com/dokan-dev/dokany/blob/12ae5ecf999f1d2741b4a86f6d01dc49be1ca1bf/dokan_fuse/src/dokanfuse.cpp#L522-L523
This can be easily done. Do you think you could make a PR for it ?

**Comment by Liryna** [comment]
This has been fixed by your PR @leochou0729 https://github.com/dokan-dev/dokany/pull/609

Thanks a lot for your contribution !

**Comment by leochou0729** [comment]
You're welcome ;) @Liryna
