### ISSUE TITLE
2.0 FileName is LPWSTR and not LPCWSTR in certain events

### ISSUE THREAD

**Issue by bailey27** [dokan-dev/dokany#608]
In the 2.0/Corillian-asyncio branch, in the DOKAN_GET_FILE_SECURITY_EVENT, DOKAN_SET_FILE_SECURITY_EVENT, and DOKAN_FIND_STREAMS_EVENT structures, the FileName member is an LPWSTR and not an LPCWSTR  like it is in the other events.

Shouldn't it always be an LPCWSTR?

**Comment by Liryna** [comment]
I just ping @ Corillian  here if he has a reason for this.

**Comment by Liryna** [comment]
Hi @bailey27 ,

I just made the changes https://github.com/dokan-dev/dokany/commit/d40bdd2c51d938e5c447e62cb178b4a0ed77bbaa
Thanks for the report !
