### ISSUE TITLE
Excel macro problems

### ISSUE THREAD

**Issue by gambetto** [dokan-dev/dokany#610]
# Environment
 * Windows version: 10
 * Processor architecture: x64
 * Dokany version: 1.0.5
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet]
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
 
# Description

Try to save this specific excel file doesn't work and force to reboot system.

1) Open italy_regions.xls
2) Click on "Protection Advice" and select "Content Activation"
3) Try to save
[italy_regions.zip](https://github.com/dokan-dev/dokany/files/1407089/italy_regions.zip)

# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
In case of BSOD, please attach minidump or dump analyze output.
[dokan-excel-reboot.log](https://github.com/dokan-dev/dokany/files/1410940/dokan-excel-reboot.log)

**Comment by Liryna** [comment]
Hi @gambetto ,

Are you using the mirror for this ? What the mirror option used ? What are the mirror logs ?

**Comment by gambetto** [comment]
Yes, I used the mirror with default option.

2017-10-23 14:40 GMT+02:00 Liryna <notifications@github.com>:

**Comment by gambetto** [comment]
[dokan-excel-reboot.log](https://github.com/dokan-dev/dokany/files/1410934/dokan-excel-reboot.log)

**Comment by gambetto** [comment]
Hi Liryna, I've verified the issue with dokan mirror and the problem is
confirmed.
I've attached mirror log.
Do you need other informations ?

Thanks.
Giuseppe

2017-10-23 14:44 GMT+02:00 Giuseppe Tofani <giuseppe.tofani@gmail.com>:

**Comment by Liryna** [comment]
Hi @gambetto ,

No, this should be enough thank you !
I will just not be able to take a look at it for now unfortunately.

**Comment by Liryna** [comment]
Hi @gambetto ,

I have reproduce your issue and it seems to be the same as https://github.com/dokan-dev/dokany/issues/611
Are you using Win 10 16299 ? (last update)

**Comment by gambetto** [comment]
![image](https://user-images.githubusercontent.com/7262110/32728933-749980d8-c882-11e7-9569-9f04a4e18cce.png)
