### ISSUE TITLE
Dokan Bundle Installer: Logo is cut off

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#615]
Dokan Bundle Installer: Logo is cut off

![image](https://user-images.githubusercontent.com/125913/32299955-bfc0e44a-bf57-11e7-893e-5afe21ba869e.png)

**Comment by js69** [comment]
The logo should be resized to probably 96x96 pixels.

**Comment by js69** [comment]
It's actually 64 by 64 pixels in the default mbapreq.thm

**Comment by Liryna** [comment]
Thank you for the report @Rondom !
Correct @js69 , 64x64 is indeed the needed size here 👍 
https://github.com/dokan-dev/dokany/commit/969a91610cfaedd35720908eb9df0cdce927c513
