### ISSUE TITLE
Problems with file mapping

### ISSUE THREAD

**Issue by andreyloktev** [dokan-dev/dokany#62]
Hello everybody!
There are several bugs with memory-mapped files:
1) Wrong behaviour in MirrorWriteFile:
   If a "Write" request comes from Virtual Memory Manager ( DOKAN_PAGING_IO is set ) then a file size will must not to be changed.
   For example:
   h = CreateFile(...)
   MapWrite( h, data = "Hello World" )
   CloseFile(h)
   After that the file size is equal to 4K( page size ) although the file size should be equal to 11 bytes
   Try to use this code:
   ```
   static int DOKAN_CALLBACK MirrorWriteFile( ... )
   {
       ...

       FileSize = GetFileSize(...);
       LARGE_INTEGER distanceToMove;

       if ( DokanFileInfo->WriteToEndOfFile )
       {
           if( DokanFileInfo->PagingIo )
            {
                *NumberOfBytesWritten = 0;
                return 0;
            }
            LARGE_INTEGER z;
            z.QuadPart = 0;
            if ( !SetFilePointerEx( handle, z, NULL, FILE_END ) )
            {
                 DbgPrint(L"\tseek error, offset = EOF, error = %d\n", GetLastError());
                 return -1;
            }
        }
        else
        {
            if( DokanFileInfo->PagingIo  )
            {
                if( Offset >= FileSize )
                {
                    return 0;
                }

                if( ( Offset + NumberOfBytesToWrite ) > fi.FileSize )
                {
                    NumberOfBytesToWrite = fi.FileSize - Offset;
                }
            }
		
            if( Offset > fi.FileSize )
            {
                //In the mirror sample helperZeroFileData is not necessary. NTFS will zero a hole.
                //But if user's file system is different from NTFS( or other Windows's file systems ) then  users will have to zero the hole themselves.
                err = helperZeroFileData( ... );
                if( err )
                {
                    return -1;
                }
            }

            distanceToMove.QuadPart = Offset;
            if ( !SetFilePointerEx( handle, distanceToMove, NULL, FILE_BEGIN ) )
            {
               DbgPrint(L"\tseek error, offset = %d, error = %d\n", offset, GetLastError());
                return -1;
            }
        }

        ...
    }

   ```
2) Wrong behaviour in driver's DokanDispatchWrite, DokanDispatchRead, DokanDispatchSetInformation( set EOF ):
   Previous mapped files are not flushed in DokanDispatchWrite, DokanDispatchRead. Also they are not invalidated in DokanDispatchWrite, DokanDispatchSetInformation.
   For example:
   h = CreateFile(...)
   MapWrite( h, offset = 0x100, length = 0x10, data = 0xaa )
   WriteFile( h, offset = 0x100, length = 0x10, data = 0x00 )
   MapRead( h, offset = 0x100, length = 0x10, buffer )
   After MapRead buffer will not contain zero data
   
   Try to use:

    NTSTATUS DokanDispatchRead( ... )
    {
        ...
        if (fcb->Flags & DOKAN_FILE_DIRECTORY)
        {
            DDbgPrint("   DOKAN_FILE_DIRECTORY %p\n", fcb);
            status = STATUS_INVALID_PARAMETER;
            __leave;
        }

        if (Irp->Flags & IRP_PAGING_IO) 
        {
            isPagingIo = TRUE;
        }

        if(
              !isPagingIo &&
              ( fileObject->SectionObjectPointer != NULL ) &&
              ( fileObject->SectionObjectPointer->DataSectionObject != NULL )
          )
        {
           ExAcquireResourceExclusiveLite( &fcb->PagingIoResource, TRUE );
           CcFlushCache(
                        &fcb->SectionObjectPointers,
                        &irpSp->Parameters.Read.ByteOffset,
                        irpSp->Parameters.Read.Length,
	                    NULL
                       );
             ExReleaseResourceLite( &fcb->PagingIoResource );
        }
        ...
    }

    NTSTATUS DokanDispatchWrite( ... )
    {
        ...
        if (Irp->Flags & IRP_PAGING_IO) 
        {
            isPagingIo = TRUE;
        }

        if(
              !isPagingIo &&
              ( fileObject->SectionObjectPointer != NULL ) &&
              ( fileObject->SectionObjectPointer->DataSectionObject != NULL )
          )
        {
           ExAcquireResourceExclusiveLite( &fcb->PagingIoResource, TRUE );
           CcFlushCache(
                        &fcb->SectionObjectPointers,
                        writeToEoF ? NULL : &irpSp->Parameters.Write.ByteOffset,
                        irpSp->Parameters.Write.Length,
                        NULL
                       );
            CcPurgeCacheSection(
                       &fcb->SectionObjectPointers,
                       writeToEoF ? NULL : &irpSp->Parameters.Write.ByteOffset,
                       irpSp->Parameters.Write.Length,
                       FALSE
                      );
             ExReleaseResourceLite( &fcb->PagingIoResource );
        }
        ...
    }

    NTSTATUS DokanDispatchSetInformation( ... )
    {
        ...
        switch (irpSp->Parameters.SetFile.FileInformationClass)
        {
            ...
        case FileEndOfFileInformation:
            if( 
                ( fileObject->SectionObjectPointer != NULL ) &&
                ( fileObject->SectionObjectPointer->DataSectionObject != NULL )
              )
            {
                ExAcquireResourceExclusiveLite(&fcb->Resource, TRUE);
				
                pInfoEoF = (PFILE_END_OF_FILE_INFORMATION)buffer;
                //Not truncate an image file if it has been already mapped
                if (!MmCanFileBeTruncated( fileObject->SectionObjectPointer, &pInfoEoF->EndOfFile ) )
                {
                    status = STATUS_USER_MAPPED_FILE;
                    __leave;
                }

                ExReleaseResourceLite(&fcb->Resource);
                
                //Real file size is in an user mode app. So flush and invalidate a whole region
                if( !isPagingIo )
                {
                    ExAcquireResourceExclusiveLite( &fcb->PagingIoResource, TRUE );
                    CcFlushCache(&fcb->SectionObjectPointers, NULL, 0, NULL);
                    CcPurgeCacheSection(&fcb->SectionObjectPointers, NULL, 0, FALSE);
                    ExReleaseResourceLite( &fcb->PagingIoResource );
                 }
            }
            ...
        }
        ...
    }

**Comment by Liryna** [comment]
Hi andreyloktev,

Thanks for your report !

Does the second code is a fix of the two bug report ?

**Comment by andreyloktev** [comment]
Hi Liryna!
Yes, I've tested it locally. After a time i will upload changes in my forked version.
P.S. There is a cool utility "fsx"( http://codemonkey.org.uk/projects/fsx ) for "true" testing read, write, mapread, mapwrite operations :)  I will also upload a ported version.

**Comment by Liryna** [comment]
Oh, this is really great !
I will be glad to review your pull request ! :+1: 

It is right that a testing software for the C code would be great! 
And if it is possible, I would add it to appveyor.

**Comment by andreyloktev** [comment]
>And if it is possible, I would add it to appveyor.
Ok, no problems!

**Comment by Liryna** [comment]
Hi @andreyloktev ,

Sorry for the long delay :cry:
Thank you for your contribution, very appreciate ! It work like a charm !

You changes has been merged to the master https://github.com/dokan-dev/dokany/commit/1d53d9ae44e7b95563739729959f764812870d3d
