### ISSUE TITLE
WiX - Include ARM64 binary in installer

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokany#621]
Dokan can build and run on ARM.
The installer currently does not include the ARM binary.
It would be great to create another [WXS](https://github.com/dokan-dev/dokany/blob/master/dokan_wix/Dokan_x64.wxs) for ARM and include it in the main installer.
See #431

**Comment by woachk** [comment]
@Liryna Windows SDK overrides for desktop apps aren't needed anymore now. And yeah, WXS is the only remaining issue, but remember that IoT doesn't have MSI at all

**Comment by woachk** [comment]
![image](https://user-images.githubusercontent.com/24752637/36073301-42fa501c-0f26-11e8-81f0-e04afb86e078.png)
an ARM screenshot

**Comment by Liryna** [comment]
@woachk what do you mean by
>Windows SDK overrides for desktop apps aren't needed anymore now

**Comment by woachk** [comment]
@Liryna desktop API available stuff

**Comment by Liryna** [comment]
Humm @woachk , I am not sure to understand here. What would we need to change ?

Also about this issue, from what I understand (and what you said) ARM/ARM64, IoT Core do not have way to install driver/app from an installer.
https://docs.microsoft.com/en-us/windows/iot-core/develop-your-app/appinstaller
https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/driverdeployment

Is this really the case ? If so, there is no need to add ARM/ARM64 in WiX no ?
Sorry but since I never touched this version of the OS 😢 I am really looking to be guided here on the current state of how people use IoT Core.

**Comment by woachk** [comment]
ARM(64) Windows 10 is available for desktop systems and will be on market in the next few months, it's currently available in Taiwan for example.

**Comment by Liryna** [comment]
Ok So only ARM64 will need to be in the installer ?

**Comment by woachk** [comment]
Yes, Arm32 desktop Windows exists and that's where my screenshot comes from, but it isn't public so it doesn't really matter for almost everyone (except me :-) ).

**Comment by woachk** [comment]
Related note: difx.lib isn't available on ARM & ARM64 Windows SDKs

**Comment by Liryna** [comment]
Done https://github.com/dokan-dev/dokany/commit/b79aea97644fb5f442adc32074ca316c86f96c0f
