### ISSUE TITLE
Move to VS 2017 / v141 / SDK 10.0.16299.0 / Installer Redist 2017 

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokany#622]
WDK for VS 2017 has finally been released.
This makes use able to fully move to VS 2017 and new SDK.
Here is the current migration changes:
https://github.com/Liryna/dokany/commit/5c9dbaca1b7364a46822918f0d79c1b284cc0730

KB2999226 checks seems to no longer be needed since C++ 2015 Redistributable Update 3
"Microsoft Visual C++ 2015 Redistributable includes bug fixes to the runtime DLLs and also the latest versions for KB 2999226."
See https://www.microsoft.com/en-us/download/details.aspx?id=53587

ARM - VS 2017 need additional features enabled and a special flag on the cxproj to build ARM/ARM64.
See http://pete.akeo.ie/2017/05/compiling-desktop-arm-applications-with.html

@Rondom Appveyor has now the WDK installed in 2017 image that is needed to build. I have removed Visual Studio 2015 image of Appveyor.yml, The test were running in 2015 and 2017 image, does running in 2015 add something ? Another OS ? (I can revert the change.)

TODO:
- [x] Test install on fresh Windows 7 - Install
- [x] Test install on Windows 7 SP1
- [x] Test install on Windows 8.1
- [x] Test install on fresh Windows 10

**Comment by Rondom** [comment]
The VS2015-image runs Win 2012R2 (=8.1), the VS2017 one Win 2016 (=10). I think 10 and 7 are most common, but AppVeyor only provides those two images to free users. I think testing on 8.1 still provides value given that we don't test on Win7.

All that is needed is replacing 2015 with 2017 and 2017 and 2015 in the config. I cannot remember why, but the order of images matters. So inside `image:` 2017 should should come first.

**Comment by Liryna** [comment]
Thank you @Rondom , I have pushed my commit and revert the image config as you proposed 👍 
https://github.com/dokan-dev/dokany/commit/3b63b90efa1b4aae885dd9d54aea3675f6c3939c

Appveyor build: https://ci.appveyor.com/project/Maxhy/dokany/build/1.1.0-333

**Comment by Rondom** [comment]
**Ideally** some of the companies using Dokany in commercial projects would sponsor some infrastructure to run it with different Windows versions.

Windows 7, to avoid regressions and Windows 10 "trunk" (or whatever MS calls it) so that issues introduced by changes that MS does are caught early. We have now had two issues which were only noticed after some users upgraded and noticed things not working and I somehow doubt it will be the last Win10 update that changes something with regards to filesystems...

**Comment by Liryna** [comment]
@Rondom excellent Idea !
I will highlight your message during the release

I have tested the installer on the different windows I have all behavior seems to be good 👍 !

I merged the changes https://github.com/dokan-dev/dokany/pull/626
Will do a release during the week

**Comment by KyleSanderson** [comment]
@Liryna your message is bad, you're looking for VC++ 2017, not VC++ 2015. By the way, the binaries are here https://blogs.msdn.microsoft.com/chuckw/2017/08/14/visual-studio-2017-15-3-update/ (the installer fails to grab the right versions).

**Comment by Liryna** [comment]
Hi @KyleSanderson ,

You are right, I found that I forgot to change the VC++ version in the error message when it is not installed 👍 
https://github.com/dokan-dev/dokany/commit/77611b04fef95b5b09438f2a1761e1595404ce27
Regarding the link, even if the link you provided is correct, but I prefer to give the generic one that has "less chance" to change.

Thanks for the report !
