### ISSUE TITLE
Build one driver for all OS versions

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#624]
Right now a different driver is built for each Windows version. It has been suggested to build one driver that runs on all OSes. Right now, `#ifdef`s are used for code paths specific to a certain Windows version.

This has been suggested here:
https://groups.google.com/forum/#!topic/dokan/2hJ6l5a_Ciw

**Comment by Liryna** [comment]
- Remove no longer supported XP/Vista code https://github.com/dokan-dev/dokany/commit/4574aa5b276c55c1bc0b3dda86048b5ac2787cee to simplify the task
- Replace ifdef _WIN32_WINNT / NTDDI_VERSION by runtime check with RtlIsNtDdiVersionAvailable https://github.com/dokan-dev/dokany/commit/46cc105e1e5b4408c59ec897ee4c8f1b0e2f79f7

This gives us already the ability to build one driver for Win7 to Win10.
Remaining issue is ARM / ARM64 cannot be built for Win10. I will see how to manage the configuration in VS

**Comment by Liryna** [comment]
As explained here: https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/platforms-and-driver-versions
We need to use the latest WDK and target the lowest platform supported. Moving to Win7 target.

The build will lack of `FsRtlAreThereWaitingFileLocks` `FsRtlCheckLockForOplockRequest` only available from win8. `RtlIsNtDdiVersionAvailable` cannot help here.

**Comment by Rondom** [comment]
> The build will lack of FsRtlAreThereWaitingFileLocks FsRtlCheckLockForOplockRequest only available from win8. RtlIsNtDdiVersionAvailable cannot help here.

Couldn't this be solved by: https://docs.microsoft.com/en-us/windows-hardware/drivers/gettingstarted/platforms-and-driver-versions#conditionally-calling-windows-version-dependent-functions

**Comment by Liryna** [comment]
@Rondom very good point, I just missed it ! Will look into this 😎

**Comment by Liryna** [comment]
Dokan sys is now a single binary for all platforms. Installer has also been moved to use this single driver.
https://github.com/dokan-dev/dokany/commit/fa653bedb54fa0c5a5fce5a610ff5ecf06062b83
