### ISSUE TITLE
System.AccessViolationException:

### ISSUE THREAD

**Issue by probeerz** [dokan-dev/dokany#629]
# Environment
 * Windows version: 10 
 * Processor architecture:  64
 * Dokany version: 1.1
 * Library type (Dokany/NET): 
 
# Check List
  - [ ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ ] I can always reproduce the issue with the provided description below.
  - [ ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
When I run Mirror sample project, ZwCreateFileProxy throws exception at NativeMethods.DokanMapKernalToUserCreateFileFlags

System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

# Logs

**Comment by Liryna** [comment]
Hi @probeerz ,

See https://github.com/dokan-dev/dokan-dotnet/issues/162
