### ISSUE TITLE
BSOD mount.exe  with 0.7.4

### ISSUE THREAD

**Issue by MarkJJMcCormack** [dokan-dev/dokany#63]
Whilst attempting to write a simple .NET based simple file system (experimenting) using Visual Studio 2012 & .NET 4 I encountered two BSOD during the day.  They seem to relate to the mounter.exe rather than the driver, but of course I don't really have the experience to know.  My machine has hardly ever BSOD so I am pretty sure it is Dokan related.

I have pasted the BSOD analyse for the second of the two BSODs.

====================================================

Microsoft (R) Windows Debugger Version 6.3.9600.17336 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

Loading Dump File [C:\Windows\MEMORY.DMP]
Kernel Summary Dump File: Only kernel address space is available

************* Symbol Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       SRV*C:\Windows\symbol_cache*http://msdl.microsoft.com/download/symbols
Symbol search path is: SRV*C:\Windows\symbol_cache*http://msdl.microsoft.com/download/symbols
Executable search path is: 
Windows 7 Kernel Version 7601 (Service Pack 1) MP (8 procs) Free x64
Product: WinNt, suite: TerminalServer SingleUserTS
Built by: 7601.18939.amd64fre.win7sp1_gdr.150722-0600
Machine Name:
Kernel base = 0xfffff800`0341f000 PsLoadedModuleList = 0xfffff800`03666730
Debug session time: Mon Sep 21 21:40:12.408 2015 (UTC + 1:00)
System Uptime: 0 days 5:25:44.221
Loading Kernel Symbols
...............................................................
................................................................
.......................................
Loading User Symbols
PEB is paged out (Peb.Ldr = 00000000`7efdf018).  Type ".hh dbgerr001" for details
Loading unloaded module list
...........
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

Use !analyze -v to get detailed debugging information.

BugCheck 3B, {c0000005, fffff800037697a1, fffff88009ac6860, 0}

Probably caused by : ntkrnlmp.exe ( nt!ObpQueryNameString+51 )

Followup: MachineOwner
---------

6: kd> !analyze -v
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

SYSTEM_SERVICE_EXCEPTION (3b)
An exception happened while executing a system service routine.
Arguments:
Arg1: 00000000c0000005, Exception code that caused the bugcheck
Arg2: fffff800037697a1, Address of the instruction which caused the bugcheck
Arg3: fffff88009ac6860, Address of the context record for the exception that caused the bugcheck
Arg4: 0000000000000000, zero.

Debugging Details:
------------------

EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%08lx referenced memory at 0x%08lx. The memory could not be %s.

FAULTING_IP: 
nt!ObpQueryNameString+51
fffff800`037697a1 410fb64718      movzx   eax,byte ptr [r15+18h]

CONTEXT:  fffff88009ac6860 -- (.cxr 0xfffff88009ac6860;r)
rax=fffff88009ac7338 rbx=fffffa8010be2ee0 rcx=0074007300790053
rdx=fffffa8010be2f00 rsi=0000000000000001 rdi=0000000000000000
rip=fffff800037697a1 rsp=fffff88009ac7240 rbp=0074007300790053
 r8=00000000000000fe  r9=fffff88009ac73b8 r10=fffff88001359840
r11=fffff88009ac7478 r12=fffffa800d3cd3f0 r13=0074007300790053
r14=fffffa8010be2f00 r15=0074007300790023
iopl=0         nv up ei pl zr na po nc
cs=0010  ss=0018  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246
nt!ObpQueryNameString+0x51:
fffff800`037697a1 410fb64718      movzx   eax,byte ptr [r15+18h] ds:002b:00740073`0079003b=??
Last set context:
rax=fffff88009ac7338 rbx=fffffa8010be2ee0 rcx=0074007300790053
rdx=fffffa8010be2f00 rsi=0000000000000001 rdi=0000000000000000
rip=fffff800037697a1 rsp=fffff88009ac7240 rbp=0074007300790053
 r8=00000000000000fe  r9=fffff88009ac73b8 r10=fffff88001359840
r11=fffff88009ac7478 r12=fffffa800d3cd3f0 r13=0074007300790053
r14=fffffa8010be2f00 r15=0074007300790023
iopl=0         nv up ei pl zr na po nc
cs=0010  ss=0018  ds=002b  es=002b  fs=0053  gs=002b             efl=00010246
nt!ObpQueryNameString+0x51:
fffff800`037697a1 410fb64718      movzx   eax,byte ptr [r15+18h] ds:002b:00740073`0079003b=??
Resetting default scope

DEFAULT_BUCKET_ID:  WIN7_DRIVER_FAULT

BUGCHECK_STR:  0x3B

PROCESS_NAME:  mounter.exe

CURRENT_IRQL:  0

ANALYSIS_VERSION: 6.3.9600.17336 (debuggers(dbg).150226-1500) amd64fre

LAST_CONTROL_TRANSFER:  from fffff80003771b0e to fffff800037697a1

STACK_TEXT:  
fffff880`09ac7240 fffff800`03771b0e : 00740073`00790053 fffffa80`10be2f00 fffffa80`000000fe fffff880`09ac73b8 : nt!ObpQueryNameString+0x51
fffff880`09ac7340 fffff880`01364e31 : fffffa80`00000000 fffffa80`00000000 00000000`00001000 00000000`00000000 : nt!ObQueryNameString+0xe
fffff880`09ac7380 fffff880`01363327 : fffffa80`10be2ee0 fffff800`03495a04 fffff800`0369da50 00000000`00000000 : fltmgr!FltpGetObjectName+0x31
fffff880`09ac73b0 fffff880`0135e971 : fffffa80`0d3cd2a0 fffff800`0369da50 00000000`00000000 00000000`00000000 : fltmgr!FltpFsControlMountVolume+0xa7
fffff880`09ac7480 fffff800`036fb28f : fffffa80`0d3cd2a0 00000000`00000000 fffffa80`0d3cd2a0 fffffa80`14dc4560 : fltmgr!FltpFsControl+0x101
fffff880`09ac74e0 fffff800`034819d7 : fffff880`09ac77d0 fffff880`09ac7701 fffffa80`13a83c00 00000000`00000000 : nt!IopMountVolume+0x28f
fffff880`09ac75a0 fffff800`03791206 : 00000000`00000025 00000000`00000000 fffff880`09ac77d0 fffff880`09ac7778 : nt!IopCheckVpbMounted+0x1b7
fffff880`09ac7610 fffff800`0378dbae : fffffa80`13a83c40 00000000`00000000 fffffa80`126a2b10 00000000`00000001 : nt!IopParseDevice+0xb4d
fffff880`09ac7770 fffff800`0378e696 : 00000000`00000000 fffff880`09ac78f0 00000000`00000040 fffffa80`0cdcef30 : nt!ObpLookupObjectName+0x784
fffff880`09ac7870 fffff800`0378ff9c : 00000000`00f80018 00000000`00000000 fffff8a0`13f8e601 fffff800`00000000 : nt!ObOpenObjectByName+0x306
fffff880`09ac7940 fffff800`0379b5c8 : 00000000`0029e7c8 00000000`c0100080 00000000`0029f090 00000000`0029e7e0 : nt!IopCreateFile+0x2bc
fffff880`09ac79e0 fffff800`03491853 : 00000000`00000000 fffff800`037adc00 fffff880`746c6644 fffff880`09ac7af8 : nt!NtCreateFile+0x78
fffff880`09ac7a70 00000000`77afdf0a : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiSystemServiceCopyEnd+0x13
00000000`0029e758 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : 0x77afdf0a

FOLLOWUP_IP: 
nt!ObpQueryNameString+51
fffff800`037697a1 410fb64718      movzx   eax,byte ptr [r15+18h]

SYMBOL_STACK_INDEX:  0

SYMBOL_NAME:  nt!ObpQueryNameString+51

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: nt

IMAGE_NAME:  ntkrnlmp.exe

DEBUG_FLR_IMAGE_TIMESTAMP:  55afca65

IMAGE_VERSION:  6.1.7601.18939

STACK_COMMAND:  .cxr 0xfffff88009ac6860 ; kb

FAILURE_BUCKET_ID:  X64_0x3B_nt!ObpQueryNameString+51

BUCKET_ID:  X64_0x3B_nt!ObpQueryNameString+51

ANALYSIS_SOURCE:  KM

FAILURE_ID_HASH_STRING:  km:x64_0x3b_nt!obpquerynamestring+51

FAILURE_ID_HASH:  {371ec258-1b9b-87e1-9657-7586a7b66133}

Followup: MachineOwner
---------

**Comment by Liryna** [comment]
Hi,

Thank for the report !
Yes it seems to come from dokan.

Mount.exe will be removed in dokan 8.0.0 see https://github.com/dokan-dev/dokany/issues/50
Therefore we will not investigate in this crash.

Sorry for the inconvenient.

**Comment by MarkJJMcCormack** [comment]
Hi Liryna,

Thank you for your response.  I uninstalled 0.7.4 and put 0.7.2 on to see if it made any difference - maybe a later change had introduced something I though?  The mounter running on 0.7.4 was x64 and the one in 0.7.2 is x86 (my machine is 64bit Intel)

After about 10 minutes of debugging I got the same BSOD, again related to the mounter.exe.

I would understand that putting breakpoints in the .NET API callbacks could be problematic from a driver point-of-view, but it is kind of a nice way to finding out what is getting called into my functions from the driver. Perhaps I am expecting too much!!

Having read the #50 issue do I understand correctly that there is a known serious problem with the mounter.exe and hence why you say it will not be investigated?  This is understandable if this is the case.

Is there any work-around you could suggest or shall I look for alternatives (at least until 8.0.0 release)?

Thanks.

**Comment by Liryna** [comment]
Normally when you put a breakpoint in the .NET API, the driver should see that the userland code timeout and will try to unmount himself (it is a normal behaviour).
(Otherwise the system will continuously try to use the device until windows get slow and probably crash).
I can only suggest you to use debug print :disappointed:

About your crash, It is an unknown issue even if we know that mounter.exe is a source of instability.
I have not work-around that I can propose you sorry :(

**Comment by MarkJJMcCormack** [comment]
OK, thank you very much for your time in looking at my issue, it is certainly appreciated!

I will see if I can work with debug print and continue my experiments.
Thanks again.

**Comment by Albeoris** [comment]
I also fell with a BSOD. :(
Dump: https://yadi.sk/d/CjBY94kgjMDDo
