### ISSUE TITLE
Installer failing w/ Windows 7 SP1 (vcredist_2017_x86.exe issue)

### ISSUE THREAD

**Issue by jetwhiz** [dokan-dev/dokany#633]
# Environment
 * Windows version: 7 SP1
 * Processor architecture: x86
 * Dokany version: 1.1.0
 * Library type (Dokany/FUSE): Installer (Dokany)
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
When attempting to install Dokany on Windows 7 SP1, the installer fails while trying to install vcredist 2017.  
If I download "Microsoft Visual C++ Redistributable for Visual Studio 2017 -- x86" from https://www.visualstudio.com/downloads/, and then install Dokany after, the install works correctly.  

# Logs
[install-log.txt](https://github.com/dokan-dev/dokany/files/1545065/install-log.txt)

**Comment by Liryna** [comment]
Hi @jetwhiz ,

Does your windows is x86 ?

**Comment by jetwhiz** [comment]
Hi @Liryna 

Yes this test machine is x86.  Specifically, Windows 7 Professional SP1 x86.

**Comment by Liryna** [comment]
This is because of a mistake in the installer sorry...swaped x86 and x64 :'(
https://github.com/dokan-dev/dokany/issues/628#issuecomment-348754879

He try to install the x64 binary that is named x86

I fixed in the master. Hope to make a release in the next weeks !

**Comment by jetwhiz** [comment]
Ah, I didn't check the closed issues!  I'll keep an eye out for the next release.  Thanks!
