### ISSUE TITLE
Imperstonation and SetFileSecurity/GetFileSecurity

### ISSUE THREAD

**Issue by bailey27** [dokan-dev/dokany#636]
I notice that when you run mirror as administrator with impersonation turned on, that it fails the same tests in winfstest as it does when you run it without administrator privileges.

I guess this happens because the file handle was opened as the calling user, and even though e.g SetUserObjectSecurity() is being called from a process being run as administrator, that these calls fail because the handle was opened as a normal user.

I was wondering if anybody has any thoughts about this.

**Comment by yin19941005** [comment]
Hi @bailey27 ,

Let me confirm I got what you mean first. Are you talking about the case following:

| mirror  | winfstest | some test result |
| ------------- | ------------- | ------------- |
| With administrator privileges, Impersonation On | With administrator privileges | Failed |
| With administrator privileges, Impersonation On | Without administrator privileges | Pass |

Or you are talking about other case?

**Comment by bailey27** [comment]
No, I meant like this


| mirror        | winfstest           | some test result  |
| ------------- |:-------------| :-----|
| With administrator privileges, Impersonation Off    | Without administrator privileges| Pass |
| With administrator privileges, Impersonation On      | Without administrator privileges      |   Failed  |

**Comment by yin19941005** [comment]
Hi @bailey27 ,

I got what you exactly mean now. I am not familiar with winfstest but I guess maybe winfstest didn't handle the case properly or we should run the winfstest with administrator privileges.

Here is my expected test result base on the above information : 

| mirror | winfstest | Result of tests required admin right |
| ------------- | ------------- | ------------- |
| With administrator privileges, Impersonation Off | Without administrator privileges | Pass |
| With administrator privileges, Impersonation On | Without administrator privileges | Failed |
| With administrator privileges, Impersonation Off | With administrator privileges | Pass |
| With administrator privileges, Impersonation On | With administrator privileges | Pass |

If you performing some action required administrator right when the Impersonation option is **On**, you will find some error 1314 **(`ERROR_PRIVILEGE_NOT_HELD`)** at the debug log in mirror like the following : 
```
...
error code = 1314

CreateFile status = c0000061
...
```

The `STATUS_PRIVILEGE_NOT_HELD` will be returned and the application (for my case, it should be Windows File Explorer) will call with the user token contain administrator privileges again. Then this time, the token contain enough privileges and the operations will success.

So, I guess maybe winfstest just receive the `STATUS_PRIVILEGE_NOT_HELD` and mark the test as failed or it simply didn't contain enough privilege. @bailey27 , could you check what's the expected return value and the actual return value for those specific test? And maybe you can try to run the winfstest with administrator privileges?

**Comment by bailey27** [comment]
Yes,  your table above is correct.

I think this is the right behavior, and there isn't really a problem.

Thank you for clearing this up.
