### ISSUE TITLE
Is this project actively maobtained?

### ISSUE THREAD

**Issue by TonyValenti** [dokan-dev/dokany#637]
Hi all,
I’m wanting to build an app similar to google drive file stream. Does Dokan let me do that?  Also, is this project actively maintained?  Is it stable?

**Comment by Liryna** [comment]
Hi @TonyValenti ,

Yes, this project is actively maintained ! We have a great community around it, a good support from companies using it.
He has [a lot of unit tests](https://ci.appveyor.com/project/Maxhy/dokany/branch/master) enabled at each commit to follow the stability 👍 

Yes, it can create a similar application as google drive. There are a couple of projects than you can see [here](https://dokan-dev.github.io/)

And we also answer in less than 30 min 😄

**Comment by TonyValenti** [comment]
Thanks so much!  I'm really excited to give this a shot!

**Comment by Rondom** [comment]
I have not tried Google Drive Stream, so I cannot check, but  the list of open-source components they use claim that it is using Dokany under the hood. ;-)
* https://support.google.com/drive/answer/1716931
* https://github.com/google/google-drive-dokany
