### ISSUE TITLE
Nice error message on DLL-ABI-mismatch?

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#638]
Is it possible to return a nice error when an application linked against Dokan 1.0.y uses a Dokan 1.1.y-DLL?

I see that DokanMain has an takes the requested version as an argument (`DOKAN_OPTIONS::Version)`. Could it be used for that? Is that the intended purpose of having the argument in the first place?

**Comment by Liryna** [comment]
Hi @Rondom ,

The `DOKAN_OPTIONS::Version` is checked in the dokan.dll [here](https://github.com/dokan-dev/dokany/blob/acdfbbda4e6e0fd0f183a3fa8ed894838d56bbbd/dokan/dokan.c#L200).
The error is returned from DokanMain and checked in the mirror to [display a message](https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L1715).

Is that what you were looking for ?

**Comment by Rondom** [comment]
Yes, that is what I was looking for. I only looked at the behaviour and not at the code. Of course the behaviour given that the number in the header is not increased... Something for the next version...

**Comment by Rondom** [comment]
I filed the issue not knowing that the error is already  handled properly if there is a mismatch. So if that works, I think nothing needs to be done except changing the version.

**Comment by Liryna** [comment]
@Rondom done with https://github.com/dokan-dev/dokany/commit/fc40ebb34e8e6b9072db9efce7c186972709a45a 👍 Thank you !
