### ISSUE TITLE
impersonation: userTokenHandle not closed in MirrorCreateFile()

### ISSUE THREAD

**Issue by bailey27** [dokan-dev/dokany#639]
When impersonation is used, MirrorCreateFile() never closes userTokenHandle.

I see this token is gotten and closed in PrintUsername().

Should the handle be closed in MirrorCreateFile() as well?

**Comment by yin19941005** [comment]
Hi @bailey27 ,

Yes, I think so. I think this is my fault that forgetting to close the userTokenHandle in my PR. I just have a quick look on the code and seems we should close it at [this line for directory](https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L398) and [this line for file](https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L460)

**Comment by bailey27** [comment]
I think mirror should also capture the result of GetLastError() before calling RevertToSelf() in the off chance that RevertToSelf() fails and sets last error.  

I think mirror intends to print the GetLastError() about whey the CreateFile() failed.  

In other words, a failing RevertToSelf() could mask the last error from the CreateFile().

**Comment by Liryna** [comment]
Hi @bailey27 ,

Thank you for the report ! It is right userTokenHandle was not closed 😢 
I made the changes like @yin19941005 said 👍 and save the last error to not corrupt it as you told.
https://github.com/dokan-dev/dokany/commit/413119b46a3a8addd28ff831502c71872b41d264
