### ISSUE TITLE
Installation fails due a pre-requisite

### ISSUE THREAD

**Issue by GBR-613** [dokan-dev/dokany#644]
Installation of the current version fails due a missed pre-requisite "VC++ 2015 runtime".
The dialog box points to a link that is not available anymore.
Appreciate if you could publish it (or at least direct link to it) in your download page.
Thanks in advance!

**Comment by Liryna** [comment]
Hi @GBR-613 ,

VC++ 2017 runtime is needed. This was an error and has been fixed since the release.
https://github.com/dokan-dev/dokany/compare/v1.1.0...master
Also I have updated the link now (that was redirect by microsoft) to the new one.

Thank your for the report @GBR-613 👍
