### ISSUE TITLE
C# file system

### ISSUE THREAD

**Issue by AceHack** [dokan-dev/dokany#645]
https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/getting-started-with-universal-drivers

Is it possible to create a windows file system using a universal driver in UMDF 2 mode or will I need dokany?  If so can you give me an example or help me get started with a C# windows file system?

Thanks.

**Comment by marinkobabic** [comment]
This is your starting point. https://github.com/dokan-dev/dokan-dotnet
Dokany provides a filesystem driver and a user mode access to it? Please
can you provide more details about your target?

**Comment by AceHack** [comment]
I'm really curious if it's possible to just use a universal driver in UMDF 2 for the file system.  Thanks.

**Comment by marinkobabic** [comment]
It's possible to have such a filesystem of course. I think that you can use
unmanaged C# instead of C or C++.

**Comment by AceHack** [comment]
I'm looking to create a distributed FS for windows similar to GlusterFS or CephFS, I have the distributed systems experience, I've just not done a lot of driver work other than GPIO.  Thanks.

**Comment by marinkobabic** [comment]
I would focus more on the distributed stuff. Dokany provides already the
driver stuff for you. Check the mirror example. The files can be provided
by any external server. Dokany will expose them to the local system inside
if the normal explorer. Your task is just to adapt the external system to
Dokany.

**Comment by Liryna** [comment]
Hi @AceHack ,

Does @marinkobabic has answer you question ?
