### ISSUE TITLE
GlusterFS FUSE for windows

### ISSUE THREAD

**Issue by AceHack** [dokan-dev/dokany#646]
When looking at a project like glusterfs, how hard would it be to plug it into windows using this project?

https://github.com/gluster/glusterfs

**Comment by Liryna** [comment]
Hi @AceHack ,

Dokany would provide you the FS layer (it creates the device for you, handle kernel calls). The part of the work "remaining" is to implement the dokan API (CreateFile, Read, write, list folders, security informations, device space,...) by creating a bridge between gluster API and dokan.

The difficulty would depend on the gluster API or project like.

**Comment by AceHack** [comment]
GlusterFS client is FUSE API on linux

**Comment by Liryna** [comment]
dokan has a FUSE API wrapper

**Comment by Rondom** [comment]
Glusterfs uses the kernel FUSE ABI if I see it correctly, i.e. it interacts with /dev/fuse directly. Dokany only supports the high-level libfuse API. I guess it would take quite a bit of work to port this.

**Comment by Rondom** [comment]
Glusterfs uses the kernel FUSE ABI if I see it correctly, i.e. it interacts with /dev/fuse directly. Dokany only supports the high-level libfuse API. I guess it would take quite a bit of work to port this.

Not sure about your use case of running it on Windows. Depending on the specific use case it might as well be easier to port whatever else that requires you to use Windows to Linux, I think.

**Comment by Liryna** [comment]
Hi @AceHack ,

Does @Rondom has answer you question ?
