### ISSUE TITLE
Windows IoT

### ISSUE THREAD

**Issue by AceHack** [dokan-dev/dokany#647]
Do you know if this project will run on windows IoT/ARM?

https://developer.microsoft.com/en-us/windows/iot

**Comment by Rondom** [comment]
We do produce arm32 and arm64 binaries, which can be downloaded in the Dokan.zip file with every release.

We need some help on the installer, so any PR in that regard is welcome, see  #621.

**Comment by Liryna** [comment]
@Rondom is right.
From Microsoft doc, https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/peripheraldrivers
You will need to use the correct driver architecture.

**Comment by AceHack** [comment]
The page you link says

> Note:
> Windows IoT Core supports Universal Inf only.

So this project has a universal inf?

**Comment by Liryna** [comment]
Yes @AceHack , you can see here the output of InfVerif https://ci.appveyor.com/project/Maxhy/dokany/build/1.1.0-346/job/469mlt5yyja462yh#L1731

There is no error/warning for universal
https://docs.microsoft.com/en-us/windows-hardware/drivers/devtest/infverif

**Comment by Liryna** [comment]
Hi @AceHack ,

Did I@marinkobabic has answer you question ?
