### ISSUE TITLE
Installation fails with  0x80091007 "Der Hashwert ist falsch" when executing DokanSetup.exe

### ISSUE THREAD

**Issue by gv2011** [dokan-dev/dokany#649]
See attached log.

[Dokan_Library_1.1.0.1000_Bundle_20180105111419.log](https://github.com/dokan-dev/dokany/files/1606270/Dokan_Library_1.1.0.1000_Bundle_20180105111419.log)

**Comment by Liryna** [comment]
Hello @gv2011 ,

This has already been report See https://github.com/dokan-dev/dokany/issues/628

**Comment by gv2011** [comment]
Seems to be a different cause. Moved DokanSetup.exe to a new folder, problem still exists. But don't have time for that now.

**Comment by Rondom** [comment]
Use DokanSetup_redist.exe

**Comment by Liryna** [comment]
@gv2011 Try to install the redist 2017 directly and run again the dokan installer.
I will try to make a new installer soon.
