### ISSUE TITLE
Typo in error message during installation

### ISSUE THREAD

**Issue by chludwig** [dokan-dev/dokany#652]
# Environment
 * Windows version: 7 64bit
 * Donkan Library: v1.1.0 64bit

# Description
When installing Donkan without having installed the proper C++ Runtime, the error message advices to install `VC 2015` Redistributable (at least v 14.11.2xx).  But it should say `VC 2017`, because the latest VC 2015 seems to be v 14.0.24215.
It took me some time to find the right VC Redistributable.

**Comment by Liryna** [comment]
Hi @chludwig ,

Thank you for the report. This has been fixed for the next version https://github.com/dokan-dev/dokany/commit/77611b04fef95b5b09438f2a1761e1595404ce27 👍
