### ISSUE TITLE
 dokannp1.dll  must be copied to `%WINDIR%\system32` 

### ISSUE THREAD

**Issue by HanixNicolas** [dokan-dev/dokany#656]
# Environment
 * Windows version: Windows 10 Enterprise N  x64
 * Processor architecture:  x64
 * Dokany version: 1.1.0.2000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
    Using Mirror on Windows 10 Enterprise N  x64
    mirror /r c:\test /l M: /n /c 
    Drive M  is ok in explorer,but run  C:\Windows\SysWOW64\notepad.exe 
     click menu File->Open->This PC
     The drive M show as Disconnected Network Drive

# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
In case of BSOD, please attach minidump or dump analyze output.

**Comment by HanixNicolas** [comment]
In explorer Drive is ok
![explorer](https://user-images.githubusercontent.com/35907136/35547656-44756cda-05b5-11e8-84f1-93e8a09a47dd.png)

32bit notepad.exe try to open file.
![32bit-notepad](https://user-images.githubusercontent.com/35907136/35547718-a4fe7240-05b5-11e8-8cf5-f03005c3d8f5.png)

The Drive M show as disconnected Network Drive
![notepad](https://user-images.githubusercontent.com/35907136/35547703-9726c028-05b5-11e8-94a4-87267e81a185.png)

the reason is dokannp1.dll must be copied to %WINDIR%\system32.
on x64  copy dokannp1.dll (64) to  %WINDIR%\system32
             copy dokannp1.dll (x86)  to %WINDIR%\SysWOW64
and change the registry to %WINDIR%\system32\dokannp1.dll
![dokannp1_reg](https://user-images.githubusercontent.com/35907136/35547787-3d591afe-05b6-11e8-9847-8db581ba72f3.png)

**Comment by Liryna** [comment]
Hi @HanixNicolas ,

It is weird that it needs to be copied in system32. dokannp1.dll was at first in the folder but we moved it to installer folder, changed the dokanctl to register correctly the dll path.

I also did the test on my VM and I do not face the issue.
![image](https://user-images.githubusercontent.com/4311419/35701908-c8bd7382-0797-11e8-8812-8a41a5b647a2.png)

Does you notepad is running in 32bit ? (dokannp register is 64bit so in case of....already seen some app 32bit having issue on the NP)

**Comment by HanixNicolas** [comment]
Hi,@Liryna,I am very happy to receive your reply.
notepad 64bit  also work in my VM.

On 64bit windows,The operating system uses the %SystemRoot%\system32 directory for its 64-bit library and executable files.  When executing 32-bit applications, WoW64 transparently redirects 32-bit DLLs to %SystemRoot%\SysWoW64, which contains 32-bit libraries and executables. 
more info:
[WoW64](https://en.wikipedia.org/wiki/WoW64)
[File System Redirector](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384187(v=vs.85).aspx)

**Comment by Liryna** [comment]
Hi @HanixNicolas ,

Yes, I am aware of the 32-bit redirection. We even disable it in dokanctl (that register during install the network provider with `dokanctl /i n`.
https://github.com/dokan-dev/dokany/blob/master/dokan_control/dokanctl.c#L116

What I wonder is if we probably need to register the dokannp1 32 bits also in the register ? (so register 32 & 64 NP)
What I am

**Comment by HanixNicolas** [comment]
Hi @Liryna   
we don't  need to register the dokannp1 32 bits also in the register.
Just copy 32bit dokannp1.dll  to %WINDIR%\SysWOW64
and change the registry HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\dokan1\NetworkProvider
change ProviderPath type to REG_EXPAND_SZ value to %WINDIR%\system32\dokannp1.dll.
Then it will be ok.

**Comment by Liryna** [comment]
Hi @HanixNicolas ,

I could do more test and you are right, register the dokannp1.dll inside the system32 fix the issue 👍 
What bothers me here is that dokannp1.dll need dokan1.dll because of the usage of `DokanGetMountPointList` and it would mean to copy dokan1.dll in the system32.

(for information it is me who moved it to install folder 👎  https://github.com/dokan-dev/dokany/issues/171)

@Rondom what do you think about install dokannp1 & dokan1.dll in system32 again ?

**Comment by Liryna** [comment]
My bad 😞  @Rondom, forgot dokan1.dll is already in system32 folder. So the change has no issue and no reason to not be done 👍 
I have revert https://github.com/dokan-dev/dokany/issues/171 -> https://github.com/dokan-dev/dokany/commit/405c71eb1070c7c01d512b9e8eeece6b99afabbf

Thank you for your time @HanixNicolas and feedback !
