### ISSUE TITLE
C:\Windows\SysWOW64\notepad.exe to open file   2end network drive mount shows as "Disconnected Network Drive"

### ISSUE THREAD

**Issue by HanixNicolas** [dokan-dev/dokany#657]
# Environment
 * Windows version: Windows 10 Enterprise N x64
 * Processor architecture: x64
 * Dokany version: master(20180130)
 * Library type : Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
on  Windows 10 Enterprise N x64 
copy dokannp1.dll to  %WINDIR%\system32 and change the registy by the [#656](https://github.com/dokan-dev/dokany/issues/656)
use mirror
mirror.exe /r c:\xx /l M /n /c
mirror.exe /r c:\xx /l T  /n /c
in explorer both drives is ok
but use 32bit notepad.exe which in C:\Windows\SysWOW64   to open file only the first drive is ok.the others show as "Disconnected Network Drive"

![2end_drive](https://user-images.githubusercontent.com/35907136/35555879-8f38c296-05db-11e8-88c1-fe70367606d1.png)

**Comment by Liryna** [comment]
Hi @HanixNicolas ,

This seems to be releated to https://github.com/dokan-dev/dokany/issues/653

**Comment by HanixNicolas** [comment]
I try to debug it and find the reason.
in the file sys\public.h
`typedef struct _DOKAN_CONTROL {
  /** File System Type */
  ULONG Type;
  /** Mount point. Can be "M:\" (drive letter) or "C:\mount\dokan" (path in NTFS) */
  WCHAR MountPoint[MAX_PATH];
  /** UNC name used for network volume */
  WCHAR UNCName[64];
  /** Disk Device Name */
  WCHAR DeviceName[64];
  /** Volume Device Object */
  PVOID DeviceObject;
  /** Session ID of calling process */
  ULONG SessionId;
} DOKAN_CONTROL, *PDOKAN_CONTROL;`


sizeof(PVOID) is 4 on x86
but sizeof(PVOID) is 8 on x64
on this case user space process is x86 but driver is x64,dokannp1.dll communicate to driver,only can read the first DOKAN_CONTROL ,others will failed.

**Comment by HanixNicolas** [comment]
Hi @Liryna  this is another issues. I build dokany by the code of today  after  [#653](https://github.com/dokan-dev/dokany/issues/653) is fixed.
should change PVOID to PVOID64,both sizeof(PVOID64) is 8 on x86 and x64

**Comment by Liryna** [comment]
Oh ok I see 👍
PVOID64 would be great. This would break (using previous library/kernel version with at patched library/kernel) the `DokanGetMountPointList` for 32bit kernel but I see no other way.

**Comment by HanixNicolas** [comment]
Hi @Rondom ,there is a solution for temp fix.
On x64 windows,32-bit user space files dokan1.dll  dokannp1.dll dokanfuse1.dll that in C:\Windows\SysWOW64,build with PVOID64.
On x86  windows,files still build with PVOID.
So that ,we can not change the driver,and not break   ABI-compatibility.
but we need to modify the build script and install script to work around.

**Comment by mccoysc** [comment]
the x86 and x64 issue should be handled by kernel module:
all structures and data type should use the static size,not void* and so on.and should use the same aligan size(8,etc).

**Comment by mccoysc** [comment]
any void*，ulong* and any other pointer type and handle type should not be used,but instead of __int64

**Comment by Liryna** [comment]
Hi @Rondom ,

Current state:

|   | Kernel x86| Kernel x64 |
| ------------- | ------------- | ------------- |
| Dll x86  | OK  | **KO** |
| Dll x64  | **KO** | OK  |

2 OK - 2 KO (50%)

With patched:

|   | Kernel x86| Kernel x64 | Patched Kernel x86| Patched  Kernel x64 |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| Dll x86  | OK  | **KO** | **KO** | **KO** |
| Dll x64  | **KO**  | OK  | OK  | OK  |
| Patched Dll x86  | **KO**  | OK | OK  | OK  |
| Patched Dll x64  | **KO** | OK  | OK  | OK  |

10 OK - 6 KO (60%)

I agree that here we would break the Dll x86 / Kernel x86 and patched Dll with Kernel x86 but in other situations this would fix the current ABI (not from far %). So we are kind of in a situation where it would hurt but a little less than currently.
More over, this is not a main function used by dev I would say. It was made only for dokannp that is always registered x64 on every system x64 (kernel also x64).

**Comment by Rondom** [comment]
Ah, I see. I agree.
