### ISSUE TITLE
Using Mirror  mount  drive that use UNC paths only for current session.But the Drive will show in another session as "Disconnected Network Drive"

### ISSUE THREAD

**Issue by HanixNicolas** [dokan-dev/dokany#659]
# Environment
 * Windows version: Windows 2012 R2 update x64
 * Processor architecture: x64
 * Dokany version: master(20180131)
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Using Mirror  mount  drive that use UNC paths only for current session.But the Drive will show in another session as "Disconnected Network Drive"
mirror.exe /r c:\xx /l x /n /c /u \xx\yy
In  current session it is fine.
![session2](https://user-images.githubusercontent.com/35907136/35601967-a41b12aa-0670-11e8-9327-e423278df2ac.png)
then I  use another user to login by rdp on the same machine.，didnot run the mirror command, but the drive show as "Disconnected Network Drive"
![session1](https://user-images.githubusercontent.com/35907136/35602078-3b9108f6-0671-11e8-95e4-8185f745303d.png)
If the drive is mouted for current session, it should not be showed in other session.

**Comment by HanixNicolas** [comment]
I try to debug it and find the reason:
In the dokannp1.dll not use SessionId to Filte  the drives that  belong to current session.

**Comment by Liryna** [comment]
Hi @HanixNicolas ,

Thank you for the report and specially for providing the fix for it !
You can create at PR with the changes 👍 (if you can just redo the commit to revert the 2018->2017 on copyright)

**Comment by HanixNicolas** [comment]
Hi @Liryna  I have created a different PR with this bug fix.
