### ISSUE TITLE
fileinfo.h is missing in release (DokanInstall_0.8.0.exe), cannot build dokan_mirror

### ISSUE THREAD

**Issue by justanotheranonymoususer** [dokan-dev/dokany#66]

**Comment by Liryna** [comment]
Hello Bruce Wayne,
I take a look.

**Comment by justanotheranonymoususer** [comment]
![](http://i.imgur.com/mrfmf5B.png)

**Comment by Liryna** [comment]
I have updated the pre-release with https://github.com/dokan-dev/dokany/commit/1f94c875bc90c339b1f7bb2e57dcbac514e0a6bc
Can you take a try ?

**Comment by justanotheranonymoususer** [comment]
It works now after a couple of include/lib path fixups. Namely:

![](http://i.imgur.com/UPnubsz.png)

Also, I get the following warning:

> warning : The referenced project '..\dokan\dokan.vcxproj' does not exist.

I assume that the original solution tree, the one that's in this repository, is expected.

**Comment by Liryna** [comment]
Yes I seen with your request :(
I tried to add additional include folders in the project to have only #include "dokan.h" but it seems to has not effects.
Can you try on your side ?

**Comment by justanotheranonymoususer** [comment]
Well, you can change it to `#include "dokan.h"` and `#include "fileinfo.h"`, and set the include path in the project settings. Also, I'd probably create a solution for that project. The issue with this approach is that now the files will differ from the files in the repo, so they will require these little fixups every time.

**Comment by Liryna** [comment]
I tried to set the include path in the project settings but stil wasn't able to build. Have no time to make more test for now :(

**Comment by Liryna** [comment]
Done in https://github.com/dokan-dev/dokany/releases/tag/v0.8.0-RC1
But we should probably move the project to a solution.
