### ISSUE TITLE
Remove redist dependency with /MT

### ISSUE THREAD

**Issue by 1364529444** [dokan-dev/dokany#660]
compile the exe and dlls with /MT param,not /MD pls.
and then any extra run-time dlls(vcpxxxx.dll,etc) needed.

**Comment by 1364529444** [comment]
compile the exe and dlls with /MT param,not /MD pls.
and then no any extra run-time dlls(vcpxxxx.dll,etc) needed.

**Comment by Liryna** [comment]
Hi @1364529444 ,

With MD executable are smaller, people can update by just replacing the library, no issue with shared memory.
I think the difference is only about taste, no ? Or you see a real issue by using MD ?

**Comment by mccoysc** [comment]
if compiled in /MT,the exe and dll can run without any vc runtime requirements. and you said "shared memory",in fact,it's a bad code style that malloc/new memory in on module and free/delete in another module.

**Comment by Liryna** [comment]
Thank you @mccoysc for the input. I will make some test and see about it 👍

**Comment by atanamir** [comment]
If I may add my 2 cents, it's best to distribute both flavors (MD and MT).  If you look at boost's nuget binaries for windows, they release both.  In our case, we link our dokan FS code with other libraries also compiled with /MD, so having a /MD-compiled dokan static library is important for us.

**Comment by mccoysc** [comment]
Yes,you can use dokan which compiled with /MT and other 3rd-party libs which compiled with/MD,they will work well.

**Comment by atanamir** [comment]
yes, but it's not recommended.  It's best if they all use the same; the goal of /MD is to reduce binary size, and that only works when everything is linked in using /MD.  Again, both /MD and /MT should be distributed together, and the devs can pick which one to use.

**Comment by mccoysc** [comment]
In fact ，/MD increase the app pkg size and app dependcy issues. 
/MT compiled exe only link the code which used by your exe,not the entire run-time file.

**Comment by atanamir** [comment]
There's definitely pros and cons to either approach.  Dynamic linking of the C++ library allows your application to receive any patches they release to the runtime libraries in the future, whereas /MT will not.  I prefer MD to MT, every person is entitled to their preference.  Again, as I've mentioned, both should be distributed, not one or the other.

**Comment by mccoysc** [comment]
/MD can receive run-time patches……but in fact no any end-point users care about the patches and nearly,ms give none c/c++ run-time patches.

**Comment by Liryna** [comment]
Hi @atanamir , @mccoysc ,

Having MT and MD binaries in release would be a good idea. As currently we use MD, I would propose to have MT binaries in a subfolder of the release/installer.
Does one of you would be interested to do a PR for it ?

**Comment by Liryna** [comment]
The  new release include has a installer without the VC redist dependancy
See the installer with noVC https://github.com/dokan-dev/dokany/releases/tag/v1.4.0.1000
