### ISSUE TITLE
winfstest fails on shared directory on mirror

### ISSUE THREAD

**Issue by shino0729** [dokan-dev/dokany#663]
# Environment
 * Windows version: Windows Server 2012 R2
 * Processor architecture: x64
 * Dokany version: 1.1.0.2000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Using mirror sample I mounted `M` drive and created directory `M:\bar`.
I shared `M:\bar` as `<ServerName>\bar` (right click directory -> property -> sharing -> Advanced Sharing...) and try to do winfstest to the shared directory.
However winfstest 10.t which includes ACL tests is failed. After ACL is changed from GA (GENERIC_ALL) to GR (GENERIC_READ), it seem to fail to delete the file.

**Comment by Liryna** [comment]
Hi @shino0729 ,

Do you have some logs of what his happening ?
On the CI the Winfstest for a mounted network drive.
https://ci.appveyor.com/project/Maxhy/dokany/build/1.1.0-360/job/yn5lw5sikdaojnun#L8483
It is not exactly what you are doing but maybe a workaround ?

**Comment by shino0729** [comment]
Hi @Liryna ,

I attached a log file [debugview.log](https://github.com/dokan-dev/dokany/files/1757172/debugview.log) and the result of winfstest is as follows (test only from No.6 to No.10).
```
>python .\t\base\10.t \\<ServerName>\share\tmp
ok 1 - expect "CreateFile \\<ServerName>\share\tmp1ff49824 GENERIC_WRITE 0 D:P(A;;GA;;;WD) CREATE_NEW FILE_ATTRIBUTE_NORMAL 0" 0
ok 2 - expect "CreateFile \\<ServerName>\share\tmp1ff49824 GENERIC_READ 0 0 OPEN_EXISTING 0 0" 0
ok 3 - expect "SetFileSecurity \\<ServerName>\share\tmp1ff49824 DACL_SECURITY_INFORMATION D:P(D;;GR;;;WD)" 0
ok 4 - expect "CreateFile \\<ServerName>\share\tmp1ff49824 GENERIC_READ 0 0 OPEN_EXISTING 0 0" ERROR_ACCESS_DENIED
not ok 5 - expect "DeleteFile \\<ServerName>\share\tmp1ff49824" 0 - got ERROR_INVALID_PARAMETER
1..5
```

In addition I describe how to reproduce.

1. mount mirror (`mirror.exe /r D:\mirror /l m /o`)
2. share directory `M:\share` as `<ServerName>\share`
(right click directory -> property -> sharing -> Advanced Sharing...) 
3. run winfstest (`python .\t\base\10.t \\<ServerName>\share\tmp`)

As you said, a mounted network drive by using `/n` option looks working well. So it can be a workaround.
Thank you.

**Comment by shino0729** [comment]
Hi @Liryna ,

A mounted network drive is not accessible from remote, so it doesn't work as a share directory.
I attached [mirror.log](https://github.com/dokan-dev/dokany/files/1918236/mirror.log) that is the result of winfstest 10.t.

**Comment by Liryna** [comment]
Hi @shino0729 ,

All winfstest now pass using a mirror shared folder 👍
