### ISSUE TITLE
CI - Fail build Coverity 

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokany#665]
Coverity is currently under maintenance since 20 Feb.
https://scan.coverity.com/builds
https://twitter.com/CoverityScan/status/966068113941979136

Will need to follow this and probably update when we get more news (probably they move fully to Synopsys)

**Comment by Liryna** [comment]
Coverity disabled for now https://github.com/dokan-dev/dokany/commit/b9b8981e6c838e216f8421999f4efaebfa622cde 
Still no update

**Comment by Rondom** [comment]
Coverity is back, but everyone is advised to change their credentials (I guess besides the password it includes the credentials stored in "secure environment variables" in AppVeyor)

**Comment by Liryna** [comment]
Hi @Rondom ,

Yes coverity is back but since our build fail with http error 500 BUT the build is correctly sent and analyzed.
https://ci.appveyor.com/project/Maxhy/dokany/build/1.1.0-407/job/byorkqn2pit61q2d#L524
I have updated the api key as you said and disabled the return check value for now.
https://github.com/dokan-dev/dokany/commit/3afd8dcb8def766885d33939e0f992c57cae6033

I also try to contact coverity support for the reason

**Comment by Liryna** [comment]
Have created an issue on coveritypublisher that we are using
https://github.com/csMACnz/coveritypublisher/issues/16

**Comment by Liryna** [comment]
Coverity was removed
