### ISSUE TITLE
dokan.sys is not removed upon uninstallation, even after restart

### ISSUE THREAD

**Issue by justanotheranonymoususer** [dokan-dev/dokany#67]
And this blocks an installation of a new version.
Should probably use something like `MoveFileEx(szDstFile, NULL, MOVEFILE_DELAY_UNTIL_REBOOT)`.

**Comment by Liryna** [comment]
It is a NSIS (http://nsis.sourceforge.net/Main_Page) issue. I dont know if they have a option to delete file after reboot.

**Comment by justanotheranonymoususer** [comment]
If nothing else, you can use the [NSIS System Plug-in](http://nsis.sourceforge.net/Docs/System/System.html) to run `MoveFileEx` directly.

**Comment by Liryna** [comment]
Ah! this could make it !

**Comment by justanotheranonymoususer** [comment]
Actually, it seems like NSIS has a flag just for that.
http://nsis.sourceforge.net/Docs/Chapter4.html#delete
`Delete /REBOOTOK $INSTDIR\somefile.dat`

**Comment by Liryna** [comment]
Done :+1: 
Next pre-release will have it.
