### ISSUE TITLE
dokan1.sys build by myself ,but can't run because of No drive signature

### ISSUE THREAD

**Issue by zhengwei0418** [dokan-dev/dokany#671]
hello, i have build dokan1.sys  by download source code from git,build is success,but start failed in cmd dokanctl.exe /r d. the error code is 577,and i running debug to see the error , i found it's caused by Drive without number the signature.

Can you tell me how to solve this problem?thank you

**Comment by Liryna** [comment]
Hi @zhengwei0418 ,

You should find the informations in the wiki: https://github.com/dokan-dev/dokany/wiki
https://github.com/dokan-dev/dokany/wiki/Build#signing

By your previous issue, see the API documentation: https://dokan-dev.github.io/dokany-doc/html/

**Comment by zhengwei0418** [comment]
Thank you for your help.

I have another question:The signature tool USES the timestamp URL with paramer /t or /tr report error sometimes,error message is:invalid response. _

I modified the URL to end the problem.
