### ISSUE TITLE
Strategies for dealing with explorer's thumbnailer....

### ISSUE THREAD

**Issue by pweyzen** [dokan-dev/dokany#673]
Hi-

While viewing your file system inside the Windows Explorer, Windows will attempt to read your files in order to generate thumbnails....

This presents a challenge to me given that the "explorer.exe thumbnailer" will attempt to read your files in order to generate thumbnails for the icon views....  My files lives in my cloud....  and I don't want to download all of my cloud content.  (defeating the purpose of the cloud)

I am looking for strategies to deal with this.

Any thoughts?

P.S. Just blocking access by the explorer process is not a complete answer.  Explorer will also read the file when you "drag-copy" a file or ^C^V to make a file copy....

**Comment by Liryna** [comment]
Hi @pweyzen ,

You can find some different talks about this on the google group dokan:
https://groups.google.com/forum/#!searchin/dokan/thumbnails%7Csort:date/dokan/_grlEGvmHvo/dInPEy35AgAJ
https://groups.google.com/forum/#!searchin/dokan/thumbnails|sort:date/dokan/DOBqyhhmd-A/B6fqzHJDAQAJ
https://groups.google.com/forum/#!searchin/dokan/thumbnails|sort:date/dokan/BqD9qA3nloY/TvH8-YzCBQAJ
