### ISSUE TITLE
build dokan install packet is done，but cmd dokanctl.exe /u d is failed

### ISSUE THREAD

**Issue by zhengwei0418** [dokan-dev/dokany#674]
dokan source code version：1.1.0.2000
download from release 
build packet without install Cygwin ，MSYS2 
install OS：win server 2012

I successfully used the compiled program to install and uninstall dokan1.sys on win10.

I generated the installation package based on the document.Install packet DokanSetupDbg_redist.exe is success,but when i use cmd  dokanctl.exe /u d to uninstall dokan1.sys,it's failed.

the error msg is:
C:\Program Files\Dokan\Dokan Library-1.1.0>dokanctl.exe /u d
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
send global release for d:
Dokan Error: Failed to open \\.\Dokan_1 with code 2
Failed to unmount: d:
Unmount status = 1

 I found that #158 was a similar problem，but I haven't installed a historical version.
Could you please tell me how to solve it?

**Comment by Liryna** [comment]
Hi @zhengwei0418 ,

Are you able to run a mirror ?

**Comment by zhengwei0418** [comment]
No, the mirror runs an error.

cmd and output : 
C:\Program Files\Dokan\Dokan Library-1.1.0\sample\mirror>mirror.exe /r C:\dokan\mirror /l k: /d
Can't install driver

**Comment by Liryna** [comment]
@zhengwei0418 the driver seems not to be installed. What happens if you run dokanctl /i d ?
Did you sign the driver properly ? Did you enable the sign testing https://github.com/dokan-dev/dokany/wiki/Build#signing ?

**Comment by zhengwei0418** [comment]
@Liryna the cmd：dokanctl /i d error mssage is Dokan Error: Failed to open \.\Dokan_1 with code 2;

Yes, I executed the three commands provided under Signing module.

**Comment by Liryna** [comment]
If the driver is signed correctly, you should not have issues.

**Comment by zhengwei0418** [comment]
@Liryna ，e........
There is one such operation in build execution.But I didn't know what to do, so I hit enter without do anything.the show message is:
Please submit drivers to developer hardware dashboard. Hit ENTER when it is done

**Comment by Liryna** [comment]
did you check the dokan sys installer by your installed ? Does it has the sign ?
Be careful that there is two sys driver in the build output folder.

**Comment by zhengwei0418** [comment]
I checked all the dokan1.sys files under the generated x64 directory.All of them have been signed, and the signature information is as follows.

![1 6a52m0 z md7v4 er g](https://user-images.githubusercontent.com/37130256/38004312-44974e96-326e-11e8-95ba-3ac9cb7a6e6e.png)

**Comment by Liryna** [comment]
@zhengwei0418 "DokanSign" is a self-signed certificate. You need a valid certificate to install on production machines.

**Comment by zhengwei0418** [comment]
What you mean is that I can sign with any valid certificate without the certificate under the cert directory.

**Comment by Liryna** [comment]
@zhengwei0418 Well you can do it if the certificate is properly installed that here do not seems to be the case.
Look at the wiki dokany it explains how to use the dokan snapshot thay are self-signed

**Comment by zhengwei0418** [comment]
@Liryna I have tried to use a valid certificate to sign dokan1.sys for normal use.
