### ISSUE TITLE
winfstest fails in case Cleanup has a long time processing

### ISSUE THREAD

**Issue by shino0729** [dokan-dev/dokany#675]
# Environment
 * Windows version: Windows Server 2016
 * Processor architecture: x64
 * Dokany version: 1.1.0.2000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
**I added only sleep() function to the mirror sample.**
  - [ ] I can always reproduce the issue with the provided description below.
**I can reproduce the issue sometimes. It seems to be a timing issue.**
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I added _Sleep()_ function to the mirror sample as shown below and test with [WinFSTest](https://github.com/Liryna/winfstest) . The test No.10 (**_10.t_**) of the WinFSTest was failed but I cannot reproduced it always because it seems to be a timing issue. In my environment, 500ms sleep timer is the highest reproduction frequency. 

I attached log file and the WinFSTest No.10 code ([issue.zip](https://github.com/dokan-dev/dokany/files/1851728/issue.zip))

* mirror.c (added only **_Sleep()_** function)
```
static void DOKAN_CALLBACK MirrorCleanup(LPCWSTR FileName,
                                         PDOKAN_FILE_INFO DokanFileInfo) {
  ...

  if (DokanFileInfo->DeleteOnClose) {
    // Should already be deleted by CloseHandle
    // if open with FILE_FLAG_DELETE_ON_CLOSE
    DbgPrint(L"\tDeleteOnClose\n");
    if (DokanFileInfo->IsDirectory) {
      DbgPrint(L"  DeleteDirectory ");
      if (!RemoveDirectory(filePath)) {
        DbgPrint(L"error code = %d\n\n", GetLastError());
      } else {
        DbgPrint(L"success\n\n");
      }
    } else {
      DbgPrint(L"  DeleteFile ");
      if (DeleteFile(filePath) == 0) {
        DbgPrint(L" error code = %d\n\n", GetLastError());
      } else {
        DbgPrint(L"success\n\n");
        Sleep(500);  // <------------------------- added code
      }
    }
  }
}
```
* mirror execution
```
> mirror.exe /l O  /r c:\mirror\ /o /d /s
```

* WinFSTest result
```
> mklink /D mirror 
[issue.zip](https://github.com/dokan-dev/dokany/files/1851726/issue.zip)
O:\test
> set PYTHONPATH=.
> python .\t\base\10.t mirror\tmp
ok 1 - expect "CreateFile mirror\tmpd4216be8 GENERIC_WRITE 0 D:P(A;;GA;;;WD) CREATE_NEW FILE_ATTRIBUTE_NORMAL 0" 0
ok 2 - expect "CreateFile mirror\tmpd4216be8 GENERIC_READ 0 0 OPEN_EXISTING 0 0" 0
ok 3 - expect "SetFileSecurity mirror\tmpd4216be8 DACL_SECURITY_INFORMATION D:P(D;;GR;;;WD)" 0
ok 4 - expect "CreateFile mirror\tmpd4216be8 GENERIC_READ 0 0 OPEN_EXISTING 0 0" ERROR_ACCESS_DENIED
ok 5 - expect "DeleteFile mirror\tmpd4216be8" 0
not ok 6 - expect "CreateDirectory mirror\tmpd4216be8 D:P(A;;GA;;;WD)" 0 - got ERROR_ALREADY_EXISTS
not ok 7 - expect "GetFileSecurity mirror\tmpd4216be8 DACL_SECURITY_INFORMATION" 0 - got ERROR_FILE_NOT_FOUND
not ok 8 - expect "SetFileSecurity mirror\tmpd4216be8 DACL_SECURITY_INFORMATION D:P(A;;GA;;;WD)(A;;GR;;;SY)" 0 - got ERROR_FILE_NOT_FOUND
not ok 9 - expect "GetFileSecurity mirror\tmpd4216be8 DACL_SECURITY_INFORMATION" 0 - got ERROR_FILE_NOT_FOUND
not ok 10 - expect "RemoveDirectory mirror\tmpd4216be8" 0 - got ERROR_FILE_NOT_FOUND
1..10
```

# Logs
[issue.zip](https://github.com/dokan-dev/dokany/files/1851728/issue.zip)

**Comment by Liryna** [comment]
Hi @shino0729 ,

By reviewing the logs, during success there is two CreateFile at the same time, one with CREATE_NEW (CreateDirectory) and another with OPEN_EXISTING (probably to get info from the system) and both succeed.
With the sleep, both CreateFile are just OPEN_EXISTING and both returns ERROR_FILE_NOT_FOUND.

Since there is no CREATE_NEW from CreateDirectory, I wonder if it is not a cache somewhere that will not try to create after getting ERROR_FILE_NOT_FOUND a from OPEN_EXISTING.

Can you retry with a mirror using one thread ?

**Comment by shino0729** [comment]
Hi @Liryna ,

Currently I couldn't reproduce this issue in my environment but I encountered another problem shown below on same test and same environment.

`> mirror.exe /l O  /r c:\mirror\ /o /d /s /t 1`
 
```
ok 1 - expect "CreateFile .\sbtmp\tmpa5232bcf GENERIC_WRITE 0 D:P(A;;GA;;;WD) CREATE_NEW FILE_ATTRIBUTE_NORMAL 0" 0
ok 2 - expect "CreateFile .\sbtmp\tmpa5232bcf GENERIC_READ 0 0 OPEN_EXISTING 0 0" 0
ok 3 - expect "SetFileSecurity .\sbtmp\tmpa5232bcf DACL_SECURITY_INFORMATION D:P(D;;GR;;;WD)" 0
ok 4 - expect "CreateFile .\sbtmp\tmpa5232bcf GENERIC_READ 0 0 OPEN_EXISTING 0 0" ERROR_ACCESS_DENIED
ok 5 - expect "DeleteFile .\sbtmp\tmpa5232bcf" 0
ok 6 - expect "CreateDirectory .\sbtmp\tmpa5232bcf D:P(A;;GA;;;WD)" 0
ok 7 - expect "GetFileSecurity .\sbtmp\tmpa5232bcf DACL_SECURITY_INFORMATION" <lambda> - result [{'Sddl': 'D:P(A;;FA;;;WD)'}]
ok 8 - expect "SetFileSecurity .\sbtmp\tmpa5232bcf DACL_SECURITY_INFORMATION D:P(A;;GA;;;WD)(A;;GR;;;SY)" 0
ok 9 - expect "GetFileSecurity .\sbtmp\tmpa5232bcf DACL_SECURITY_INFORMATION" <lambda> - result [{'Sddl': 'D:P(A;;FA;;;WD)(A;;FR;;;SY)'}]
```

The test has 10 item but it seems to freeze after 9th test. This issue is not occurred always.

**Comment by Liryna** [comment]
Hi @shino0729 ,

All winfstest now pass using a mirror shared folder 👍

**Comment by Liryna** [comment]
Hi @shino0729 ,

I added the `Sleep(500);` during Cleanup. All 500 tests now pass 👍 
If you still can reproduce it, please do not hesitate and will reopen the issue.
