### ISSUE TITLE
Unable to run any installer package from Dokany Network Drive

### ISSUE THREAD

**Issue by michalpelka** [dokan-dev/dokany#678]
# Environment
 * Windows version: Windows 10
 * Processor architecture: x64
 * Dokany version: 1.1.0.2000
 * Library type (Dokany/FUSE): Dokany

# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI - https://ci.appveyor.com/project/Maxhy/dokany/build/1.1.0-415/job/un7m5w0ud91smf6v/artifacts

# Description

Problem is experienced only when mirror.exe is run to mount a network drive. When user tries to open installer package (e.g. https://notepad-plus-plus.org/repository/7.x/7.5.6/npp.7.5.6.Installer.exe) by double-clicking an executable on dokany network drive, prompt about security "Open File - Security Warning" appears. After clicking "Run" error prompt appears "M:\npp.7.5.6.Installer.exe The specified path does not exists. Check the path, and then try again"
When same exe file is opened using cmd with Administrator rights everything works correctly.
# Logs
[kernel.LOG](https://github.com/dokan-dev/dokany/files/1889355/kernel.LOG)
[mirror_output.txt](https://github.com/dokan-dev/dokany/files/1889356/mirror_output.txt)

**Comment by michalpelka** [comment]
@Liryna thanks fo reply and suggestion.

Indeed by using UNC path and adding server to trusted zone I can get rid of 
![screenshot_4](https://user-images.githubusercontent.com/3209244/38942354-d919639e-432e-11e8-8eaa-dd0112dd69b8.png)
but my problem is still present :(
![screenshot_5](https://user-images.githubusercontent.com/3209244/38942377-e75caefc-432e-11e8-9461-6ae15f065796.png)

**Comment by marinkobabic** [comment]
Drive is mapped using user permission and the execution happens using admin
permission. There does the drive not exist.

**Comment by michalpelka** [comment]
@marinkobabic thanks for reply, but the problem present during running a mirror with \n switch (for network drive) (in administrator's command shell or user). When it is used with \n switch somehow calls to run setup packages does not reach mirror.

**Comment by marinkobabic** [comment]
This is normal behaviour of Windows when working with network drives.

Network drives are mapped using the User session. When you in this session
would start an explorer instance with elevated permission then you wouldn't
see any of the network drives, because it's different Windows session.

You can test this behaviour easily on your machine.

**Comment by marinkobabic** [comment]
We need to get to common understanding. So please do the following.

- Login as normal user
- map some network drives
- start cmd and execute "net use"

You should see all the mapped drives listed. So far so good.

- start new cmd using "run as administrator"
- execute "net use" and you will not see the list of mapped drives

Please use normal drives which are not related to Dokany nor mirror to
understand the normal Windows behaviour related to sessions I'm talking
about.

Do you agree now?

Thanks
Marinko

**Comment by michalpelka** [comment]
@marinkobabic, I made that test - with ordinary Windows mapped network drive,
net use reports only when I run only as User.

On other hand net use as User and as Admin reports Dokany drive.

**Comment by marinkobabic** [comment]
If you start an exe from network driver which needs admin permissions you
would get the same error.

This is not related to Dokany at all.

**Comment by michalpelka** [comment]
Hello,
I made experiment with Samba and Windows SMB , mapped network driver and I can successfully run *.exe with admin elevation.

**Comment by michalpelka** [comment]
Hello,
I am confused. I think that fixed by accident issue with installers in our product, which uses network provided. I simply changed name of file system (FileSystemNameBuffer) returned in GetVolumeInformation. Before it was name of our product, now is NTFS or FAT. NTFS or FAT string allow to execute installers. Please advise.

**Comment by Liryna** [comment]
Hi @michalpelka ,

Windows seems to have different behavior regarding the FS name. I do not know much the reason for it and could not find a documentation about it. Seems like here it needs a windows FS.
https://github.com/dokan-dev/dokany/blob/e95fe8fb65d4a08bba8256be254435db6683943f/samples/dokan_mirror/mirror.c#L1360-L1361

**Comment by Rondom** [comment]
Maybe some hint could be added to the Doxygen-documentation to warn against changing this. I remember that there were a different issue in the past where something did not work with a custom FS name.

**Comment by Liryna** [comment]
You are right @Rondom this should have been in the wiki from start. Just added it so https://github.com/dokan-dev/dokany/commit/d60990cfe4b80f73ec8c8ec576dcabff86539879

@michalpelka does the issue is fully fixed on your side ?

**Comment by michalpelka** [comment]
@Liryna - I fixed my issue with changing our FS Name to NTFS. 
What is more I recreated the problems which I had with *.exe on mirror example, overriding FS Name to custom string.
Thanks @Liryna and @marinkobabic  for help!
