### ISSUE TITLE
Windows dokan can delete a non-empty directory, not forced delete by the cmd command 

### ISSUE THREAD

**Issue by zhengwei0418** [dokan-dev/dokany#679]
dokan version：1.1.0.2 Debug

OS：win10 x64

After the dokan was installed, the dokan mirror was run, and a three-layer folder was created. The directory structure was: 1/2/3/hello.txt, and I directly deleted the directory failure, but the success was deleted by the CMD command: rd/s/q 1

How can I delete a directory directly without CMD?

**Comment by Liryna** [comment]
Hi @zhengwei0418 ,

Could you provide more information ? I do not really understand what you are trying to do.
I will also need mirror logs.

**Comment by zhengwei0418** [comment]
that's my mistake.I modified the function DeleteDirectory, , I still do the delete operation when the directory is not empty.

Sorry for the trouble
