### ISSUE TITLE
Metro photo app failed to open pictures from mirror mounted removable drive on Win8 32bit

### ISSUE THREAD

**Issue by wangrenyao** [dokan-dev/dokany#680]
# Environment
 * Windows version: Windows 8
 * Processor architecture: 32bit
 * Dokany version: 1.1.0.2000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Use the metro photo app to open a picture in a mounted drive, failed and the app crashed.
  
1. Install dokany 1.1.0.2000 on **Win8 32bit**.
2. Use mirror.exe to mount a **removable drive**   (mirror.exe /m /r C:\Users /l m).
3. Use metro photo app to open a picture (*.jpg or other image format)  from the mounted drive.
4. The picture is not opened, and the photo app exited(crashed), the screen switched to main metro UI.

 ### Others

1. Only reproduced on Win8 32bit. I have tested on Win8 64bit, Win8.1 and Win10, the picture can be opened.
2. **If i mount without removable parameter(mirror.exe /r C:\Users /l m), the picture can be opened normally.**
3. The same picture image can be opened by "mspaint.exe" on Win8 32bit.

# Logs

**Comment by Liryna** [comment]
Hi @wangrenyao ,

Thank you for the report.

Can you provide some clear log of the mirror when only this happens in it ?

**Comment by Liryna** [comment]
Hi @wangrenyao ,

A lot of changes happened in the main branch and some could fix your issue. Do you think you could retry using the latest snapshot ?
