### ISSUE TITLE
Shown on pull request #682, error in AppVeyor build

### ISSUE THREAD

**Issue by kyanha** [dokan-dev/dokany#689]
https://ci.appveyor.com/project/Maxhy/dokany/build/1.1.0-423 shows an error.  It looks like the Appveyor build is failing because of a bad OAuth key for SonarQube.  (This is from the automated checks on #682.)

![image](https://user-images.githubusercontent.com/181781/40162484-feb795e4-5968-11e8-8aeb-ce6c682141dd.png)
![image](https://user-images.githubusercontent.com/181781/40162531-1c567c6e-5969-11e8-8140-405b80855a62.png)
![image](https://user-images.githubusercontent.com/181781/40162564-35907cfc-5969-11e8-97cc-a965008bd503.png)

**Comment by Liryna** [comment]
Thank you for the report @kyanha 
This has already been fixed here https://github.com/dokan-dev/dokany/commit/397131fbfa2f21fe76c3519a9acebd3f998ea46f
