### ISSUE TITLE
"Can't install driver" on win10 1803

### ISSUE THREAD

**Issue by nimin** [dokan-dev/dokany#690]
# Environment
 * Windows version: windows 10 1803
 * Processor architecture:  X64
 * Dokany version: 1.1.0
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I downloaded the lastest dokany-master and build it with VS2017.
By the command "mirror /r c:\users /l M:", always return "Can't install driver".
And all fomer programs that use "dokan1.dll" ceased to work.

# Logs
D:\dokany-master\Win32\Debug>mirror /d /s /r c:\users /l M:
RootDirectory: c:\users
## Attempting to add SE_SECURITY_NAME privilege to process token ##
  success: privilege already present
Dokan: debug mode on
Dokan: use stderr
AllocationUnitSize: 512 SectorSize: 512
Dokan Error: CreateFile Failed \\.\Dokan_1: 2
Can't install driver

**Comment by Liryna** [comment]
Hi @nimin ,

Do you have a stable release installed for your build mirror to connect ?

**Comment by nimin** [comment]
hello @Liryna 
I tried mirror.exe and dokan1.dll in dokany 1.1.0 zip file, and got the same error.

**Comment by Liryna** [comment]
Hi @nimin ,

I just did the test and had no issue.
![image](https://user-images.githubusercontent.com/4311419/40322103-8e792d66-5d31-11e8-815b-1eff6cccdc87.png)

You need to install dokan using the .exe installer or run `dokanctl /i d` after copy the driver in the driver windows folder.
