### ISSUE TITLE
[Question] Oplock clarification when recieving FILE_RESERVE_OPFILTER

### ISSUE THREAD

**Issue by sgraves66** [dokan-dev/dokany#693]
Windows Explorer is passing ```FILE_RESERVE_OPFILTER``` during some file operations. I'm a bit confused on how to handle this properly as, unlike the mirror example, I'm not passing through to ```::CreateFile()```. 

My inclination is to return ```NTSTATUS_SUCCESS``` if no file handles are currently open and if there are to return ```STATUS_OPLOCK_NOT_GRANTED```. What I'm unclear about is if there are any additional steps that should be taken within the driver after a successful return. Is it safe to treat this as a 'any open files?' query or am I missing the bigger picture? Oplocks from an implementation standpoint are new to me and details are rather scarce in regards to ```FILE_RESERVE_OPFILTER```. Thanks in advance for any assistance.

**Comment by Liryna** [comment]
Hi @sgraves66 ,

`FILE_RESERVE_OPFILTER` is just forward to the FS but you should just ignore it. The oplock is managed  before you get the request by dokan driver during CreateFile.

**Comment by sgraves66** [comment]
Thanks @Liryna 
In that case, I'm down to one last bug associated with mounting an ISO stored within the mounted filesystem (Windows 7/10 inherent behavior, not via an external application). I wanted to rule out handling oplock flags incorrectly. 

The ISO is assigned a drive letter and is browseable through Windows Explorer; however, I receive an error message ```Sorry, there was a problem mounting the file``` after mounting and ```An error occurred while ejecting 'DVD Drive'...``` when trying to eject. I don't see any relevant debug logging from Dokany that indicate a failure or encounter any I/O errors within my filesystem.

I'll test with the mirror application when I have time but also wanted to check if this is something you may have encountered.

**Comment by Liryna** [comment]
@sgraves66 Can you try with the mount manager option?

**Comment by sgraves66** [comment]
Yep, was just missing the flag... A few days spent on this one :'( Thanks for the fix!
