### ISSUE TITLE
get file info error because createfile receive file name: asd.txt and asd.TXT,But the two names point to the same file

### ISSUE THREAD

**Issue by zhengwei0418** [dokan-dev/dokany#697]
# Environment
 * Windows version: win10
 * Processor architecture: x64
 * Dokany version: 1.1.0.2
 * Library type (Dokany/FUSE):Dokany 
# Description
I use dokan and fuse to implement a file system, Windows client USES dokan, the bottom layer USES GRPC to forward all messages to fuse on the ubuntu server side for execution, and the client mounts to the directory: e:\test_dokan.At the time of renamefile asd.txt, get asd.txt infomation received two file names at the time of createfile: asd.txt and asd.TXT.Because ubuntu is case sensitive, it failed to get the asd.TXT information.Is there any way to solve this problem?

When the client mounts to volume: K:.You can successfully get file infomation, and no creatfile will receive file name: asd.TXT

**Comment by Liryna** [comment]
Hi @zhengwei0418 ,

Have you tried to enable `FILE_CASE_SENSITIVE_SEARCH` to the `FileSystemFlags` ?
https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L1323
You will probably also need to add the flag `FILE_FLAG_POSIX_SEMANTICS` to CreateFile for making case sensitive

**Comment by Liryna** [comment]
Hi @zhengwei0418 ,

Thank you for your feedback. I am not sure there is a solution for previous windows version 😞 

Otherwise would be to lower all file names but that does not sound like the best solution.

**Comment by alexwang82** [comment]
> I have successfully modified one of my win10 environments which install on pc
@zhengwei0418 I have the same problem. Could you share your solution?
