### ISSUE TITLE
test if file is open before unmount 

### ISSUE THREAD

**Issue by abrandeau** [dokan-dev/dokany#699]
I create a mountain point
I open an excel file from this directory
I want to test if a file is open before close the mountain point.

is it possible?

**Comment by Liryna** [comment]
@abrandeau Hi,

You can keep a list on your side of current open files to know this.

**Comment by abrandeau** [comment]
Hello

I test dokan and CBFS

CBFS has a function to test this : GetOpenedFilesSnapshot()



Anthony Brandeau
Consultant informatique

[cid:image001.jpg@01D4096B.325CA4F0]
     [cid:image002.png@01D4096B.325CA4F0] <https://www.facebook.com/Soluneo/>  [cid:image003.png@01D4096B.325CA4F0] <https://twitter.com/Soluneo_Adecia>  [cid:image004.png@01D4096B.325CA4F0] <https://www.linkedin.com/company/27006369/>  [cid:image005.png@01D4096B.325CA4F0] <http://www.viadeo.com/fr/company/soluneo>





02 51 37 10 17 - direct 02 51 99 61 10
5, rue Paul-Emile Victor
85007 La Roche sur Yon Cedex
www.soluneo.fr<http://www.soluneo.fr>






Veuillez imprimer ce mail seulement si vous en avez réellement besoin
Ce message et toutes les pièces jointes (ci-après le "message") sont établis à l'intention exclusive de ses destinataires. Si vous recevez ce message par erreur, merci de le détruire et d'en avertir immédiatement l'expéditeur par e-mail. Toute utilisation de ce message non conforme à sa destination, toute diffusion ou toute publication, totale ou partielle, est interdite, sauf autorisation expresse. Les communications sur Internet n'étant pas sécurisées, l’expéditeur informe qu'il ne peut accepter aucune responsabilité quant au contenu de ce message.
De : Liryna [mailto:notifications@github.com]
Envoyé : jeudi 21 juin 2018 14:12
À : dokan-dev/dokany <dokany@noreply.github.com>
Cc : Anthony BRANDEAU - ADECIA <a.brandeau@adecia.fr>; Mention <mention@noreply.github.com>
Objet : Re: [dokan-dev/dokany] test if file is open before unmount (#699)


@abrandeau<https://github.com/abrandeau> Hi,

You can keep a list on your side of current open files to know this.

**Comment by abrandeau** [comment]
what the difference between dokan and CBFS? except price

**Comment by Liryna** [comment]
Un service français :) ?
Dokan et CBFS sont deux produits matures. Je pense que le choix se fait d'un point de vue des gouts et besoin de chacun.

**Comment by Liryna** [comment]
D'accord je vois. Dokany n'a pas de fonction dans le même genre malheureusement.
Pour information, il est possible d'avoir le processId de la requête si cela peu aider.

**Comment by abrandeau** [comment]
vous saviez que CBFS ont tout un argumentaire pour dire pourquoi il ne faut utiliser DOKAN sur leur site

**Comment by Liryna** [comment]
Oui ils ont même du Google AdSense contre nous 😄 
Je vous laisse imaginer les raisons de faire cela à un projet open source 👍 

https://github.com/dokan-dev/dokany/wiki/Unsupported

**Comment by abrandeau** [comment]
Bonjour,
Je continue mes test de comparaison Dokan CBFS.
Je rencontre des problèmes à utiliser CBFS.connect à partir d'un partage réseau où je fais un point de montage...

Avec Dokan est ce que cela pose problème de vouloir faire cela?

**Comment by Liryna** [comment]
Bonjour @abrandeau ,

Je n'ai que très peu utiliser CBFS. Je ne pourrai pas vous aider dans cette comparaison.
Vous pouvez demander à la communauté sur le google group si vous voulez.

**Comment by abrandeau** [comment]
vous disiez : 
"You can keep a list on your side of current open files to know this."

J'ai ajouté une liste des fichiers ouverts dans la classe d'exemple 
public class Mirror : IDokanOperations

 public List<string> liste_application_file_open = new List<string>();

mais à quel moment ajouté un fichier dans les fonctions ?
j'ai du mal à trouver... pas dans ReadFile...
liste_application_file_open.Add(fileName);

une idée?
Anthony

**Comment by Liryna** [comment]
https://dokan-dev.github.io/dokany-doc/html/
Il y a une explication des séquences d'opérations qui vous aidera certainement.

**Comment by abrandeau** [comment]
j'ai regardé mais je ne vois pas clairement où positionner cette gestion de liste des fichiers ouverts.

pour l'ouverture il me semble : ReadFile... cela semble fonctionner en débuggant et en testant l'ouverture de fichier excel, je vois bien mes fichiers dans ma liste

pour la fermeture ???
closefile, unlockfile, ??

**Comment by Liryna** [comment]
Sur la page:
```
These functions are typically invoked in this sequence:

    DOKAN_OPERATIONS::ZwCreateFile <- Ouverture
    Other functions (like DOKAN_OPERATIONS.ReadFile or DOKAN_OPERATIONS.WriteFile)
    DOKAN_OPERATIONS::Cleanup
    DOKAN_OPERATIONS::CloseFile <- Fermeture

```

**Comment by abrandeau** [comment]
merci pour la réactivité
si j'ôte le fichier de ma liste dans DOKAN_OPERATIONS::CloseFile

ouverture par excel d'un fixhier xls... on commence à le modifier... on est passé dans le closefile... et le fichier n'est plus dans ma liste donc alors que toujours ouvert dans Excel????

**Comment by Liryna** [comment]
Il peut y avoir plusieurs CreateFile pour le même fichier en meme temps et donc plusieurs CloseFile par la suite.

**Comment by abrandeau** [comment]
comment faire pour savoir qu'il s'agit du dernier closefile? et donc qu'on peut considérer le fichier 'non ouvert'
pour mon information : pourquoi il y aurait plusieurs createfile?

**Comment by Liryna** [comment]
Ce comportement n'a rien à avoir avec Dokan. C'est le système Windows qui fonctionne de cette manière.
Tu dois incrémenter le nombre d'ouverture et décrémenté dans le close pour savoir ou tu en es.
Plusieurs createfile pour plusieurs applications / plusieurs CreateFile d'une même application 😃

**Comment by Liryna** [comment]
@abrandeau je crois que à partir d'ici je vais devoir vous laisser investiguer par vous même :)
