### ISSUE TITLE
Dokany should hold a reference to mount point directory handle

### ISSUE THREAD

**Issue by TrabacchinLuigi** [dokan-dev/dokany#700]
# Environment
 * Windows version: Win10
 * Processor architecture: x64
 * Dokany version: latest
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Just start mirror example with `.\mirror.exe /r C:\Users /l C:\MirrorFolder` then rename or delete `C:\MirrorFolder`

# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
In case of BSOD, please attach minidump or dump analyze output.

[Problem should be here](https://github.com/dokan-dev/dokany/blob/master/dokan/mount.c#L357)

**Comment by TrabacchinLuigi** [comment]
I've mitigated the problem creating a safefilehandle to the directory my fs is mounted on not following the junction link during the mounted callback and the disposing it during the unmount

**Comment by Rondom** [comment]
What is the consequence if you don't keep the handle? What will break if one renames the directory?

**Comment by kyanha** [comment]
If you mount an NTFS volume on a directory, and then rename the directory, the mount follows the rename of the mount point.  Having Dokany keep a handle open to the directory it's mounted on will actually change the behavior from what the system already does.

The 'correct' way to handle it is to deny delete on the mountpoint to the users who shouldn't rename it.  (The Delete permission is required to rename a file or directory.)

Test case:
[open an elevated command prompt]
```
> mkdir %userprofile%\mount
> diskpart
DISKPART> create vdisk file="%userprofile%\tempmount.vhdx" size=512 type=expandable
DISKPART> select vdisk file="%userprofile%\tempmount.vhdx"
DISKPART> attach vdisk
DISKPART> create partition primary
DISKPART> format recommended
DISKPART> assign mount="%userprofile%\mount"
DISKPART> list volume

  Volume ###  Ltr  Label        Fs     Type        Size     Status     Info
  ----------  ---  -----------  -----  ----------  -------  ---------  --------
[...]
  Volume 5                      NTFS   Partition    510 MB  Healthy
    C:\Users\username\mount\

DISKPART> exit

Leaving DiskPart...

> dir %userprofile%\mount /a
 Volume in drive C is Windows
 Volume Serial Number is 86F1-7F16

 Directory of C:\Users\username\mount

2018-06-22  22:19    <DIR>          System Volume Information
               0 File(s)              0 bytes
               1 Dir(s)     518,840,320 bytes free

> move %userprofile%\mount %userprofile%\newmount
        1 dir(s) moved.

> dir /a %userprofile%\newmount
 Volume in drive C is Windows
 Volume Serial Number is 86F1-7F16

 Directory of C:\Users\username\newmount

2018-06-22  22:19    <DIR>          System Volume Information
               0 File(s)              0 bytes
               1 Dir(s)     518,840,320 bytes free

> diskpart
DISKPART> list volume

  Volume ###  Ltr  Label        Fs     Type        Size     Status     Info
  ----------  ---  -----------  -----  ----------  -------  ---------  --------
[...]
  Volume 5                      NTFS   Partition    510 MB  Healthy
    C:\Users\username\mountnew\

DISKPART> select volume 5

Volume 5 is the selected volume.

DISKPART> remove mount="%userprofile%\mountnew"

DiskPart successfully removed the drive letter or mount point.

DISKPART> select vdisk file="%userprofile%\tempmount.vhdx"

DiskPart successfully selected the virtual disk file.

DISKPART> detach vdisk

DiskPart successfully detached the virtual disk file.

DISKPART> exit

Leaving DiskPart...

> del %userprofile%\tempmount.vhdx

>
```

You type everything after a > character.  Everything that's not after such a character is output.  The [...] are system specific, and your volume numbers will be different than mine.  Where it says `select volume` after you go into diskpart the second time, you need to ensure that you enter the correct volume number from the prior `list volume` command.

**Comment by TrabacchinLuigi** [comment]
I believe the permission approach is not right, as you said renaming it have no consequences but it is being done outside the programmer workflow, and this is all about the programmer workflow, I've mounted the disk programmatically and then when I write the disk is no longer there...
I can obtain the behaviour I want anyway opening an handle from my implementation (in .net) but it is very hard, it requires pinvoke and a lot of experience no many users would do that, they'll simple choose another product

**Comment by TrabacchinLuigi** [comment]
@liryna I've tried both approach the permission and the handle, the permission isn't that good, who can delete it? We don't have a dokany user, and we don't want to elevate to change them also, an user could change them anyway if he's administrator, also it's a pain setting them right (assuming you can find a right combinatin, which inmo doesn't exist)
The handler to the directory junking instead seems just right, if you try to do something to that folder before unmounting you are told that directory is being used (which is true)

**Comment by TrabacchinLuigi** [comment]
As I said because it's been done outside the programmer workflow, maybe this could be optional, for the sake of curiosity why are you relying on the ability to rename mount points?

**Comment by kyanha** [comment]
`I've tried both approach the permission and the handle, the permission isn't that good, who can delete it?`  Anyone who has FILE_DELETE_CHILD permission on the parent directory.  ("For a directory, the right to delete the directory and all the files it contains, including read-only files.")

I rely on the ability to rename mount points so that I can change the filesystem out from under a particularly poorly-coded piece of software (rename the mount point, rename another mount point to the original mount point, save the software state, rename the second mount point, rename the first mount point back to the original junction name, software continues without issue).  It also allows me to run a test suite serially against several filesystems without changing anything about the test runner, instead only changing aspects of the environment, without having to dismount and remount.

**Comment by TrabacchinLuigi** [comment]
>  Anyone who has FILE_DELETE_CHILD 

Exactly what i don't want, anyone coming there and being able to delete my mount point... if i remove that permission from the user who mounted the disk then i won't be able to dismount it, also this won't prevent user from rename it

**Comment by Rondom** [comment]
@TrabacchinLuigi Would accessing the volume using `\\?\Volume{GUID}\` work as a robust way of accessing your volume?

See also #136 about making the attaching of the drive letter / junction a separate action.

**Comment by TrabacchinLuigi** [comment]
@rondom not really, i need it to be also accessible to users, and have the same path for everyone (kinda of distributed fs)
But the proposal #136 seems a very nice idea, i could mount the drive then mount it and lock the mount when i mount it (i already do the same, only i tough it would be a nice feature for everyone to have it done automatically, and avoid to write code that need to pinvoke)
