### ISSUE TITLE
GetDiskFreeSpace with FileName

### ISSUE THREAD

**Issue by shino0729** [dokan-dev/dokany#702]
I would like to use the _FileName_ parameter in _GetDiskFreeSpace_ callback function. As shown this page (<https://msdn.microsoft.com/en-us/library/windows/desktop/aa364937(v=vs.85).aspx>), _GetDiskFreeSpaceEx_ has a directory name parameter.

I would like to use a quotas but it does not support (#696). I think that _FileName_ is useful to support like a per-user quotas. So plz support _FileName_ parameter in _GetDiskFreeSpace_.

**Comment by Liryna** [comment]
Hi @shino0729 ,

Have you tried to call GetDiskFreeSpaceEx when mounting with mount manager ?

**Comment by shino0729** [comment]
Hi @Liryna ,

Yes, _GetDiskFreeSpaceEx_ works fine but it doesn't realize my request.
Currently dokany _GetDiskFreeSpace_ callback function doesn't have _FileName_ parameter but I would like to return free space value based on the directory name. This is one of the _GetDiskFreeSpaceEx_ requirements as described here <https://msdn.microsoft.com/en-us/library/windows/desktop/aa364937(v=vs.85).aspx>.

**Comment by Liryna** [comment]
Hi @shino0729 ,

I just made a test with a sample and `GetDiskFreeSpaceEx` correctly return the good value when use on a Dokan device.
I think this can be closed regarding your previous ticket. If you have any other question do not hesitate.
