### ISSUE TITLE
Please revert commit 81eca07b348e55d391f357c137adaa8fd8f11dc0, it breaks cross compiled dokan fuse builds.

### ISSUE THREAD

**Issue by Daniel-Abrecht** [dokan-dev/dokany#703]
The commit 81eca07b348e55d391f357c137adaa8fd8f11dc0 changes all occurrences of `#include <windows.h>` to `#include <Windows.h>`, claiming it to correct a typo. Windows is case insensitive, and the capitalization of windows.h varies greatly across different windows SDKs, so this change neither fixes nor improves anything on windows.

Because linux is case sensitive and all linux cross compilers use lowercase for windows.h, the change broke cross compiling of dokan fuse and of applications which use dokan fuse.

Please revert commit 81eca07b348e55d391f357c137adaa8fd8f11dc0.

**Comment by Rondom** [comment]
I and commit 0e8366c7441ad1358a6a33b584341c335f33781d agree :-D

**Comment by kyanha** [comment]
Does `dokan_fuse/include/fuse_win.h` need the same treatment?

**Comment by Daniel-Abrecht** [comment]
All of the following files need the fix:
```
dokan_fuse/src/dokanfuse.cpp
dokan/dokan.h
dokan/dokani.h
dokan/list.h
dokan_fuse/src/fusemain.cpp
dokan_fuse/src/utils.cpp
dokan_fuse/src/fuse_helpers.c
```

`dokan_fuse/include/fuse_win.h` is not affected, because the include in there is only included if `_MSC_VER` is defined.

Commit 0e8366c only fixes `dokan/dokan.h`, which isn't sufficient. I've attached some build logs to show that every file I listed above indeed needs the fix: [log.txt](https://github.com/dokan-dev/dokany/files/2130170/log.txt)

**Comment by Rondom** [comment]
> Edit: I just noticed commit 0e8366c was from 2016 anyway.

That was just a tongue-in-cheek way of saying that I fixed this before ;-)

**Comment by Liryna** [comment]
My bad 😞 made the change after trying to fix some sonarqube report and missed this point.
Thank you for the report @Daniel-Abrecht !

**Comment by kyanha** [comment]
Hey @Liryna, is there a public SonarQube instance or SonarCloud for the dokan-dev projects?  I'm pretty sure that SonarCloud is free for open source projects.

**Comment by Liryna** [comment]
Hey @kyanha , Sonar allows opensource to use it for free. You can find the link in the readme: https://sonarcloud.io/dashboard?id=dokany

**Comment by kyanha** [comment]
Cool, thanks!  Do you have any plans to load the dokan-dotnet, dokan-sshfs, dokan-delphi, dokan-java, and/or dokan-ruby projects into it?

**Comment by Liryna** [comment]
I have created a ticket to keep in mind for dokan-dotnet https://github.com/dokan-dev/dokan-dotnet/issues/191
For other projects, have to see with other maintainers if they plan to do it (also probably add a CI like appveyor at first 😃 )
