### ISSUE TITLE
dokan_mirror: file removed even if MirrorDeleteFile returns STATUS_ACCESS_DENIED

### ISSUE THREAD

**Issue by justanotheranonymoususer** [dokan-dev/dokany#71]
I changed `MirrorDeleteFile` to:

	static NTSTATUS DOKAN_CALLBACK
	MirrorDeleteFile(
		LPCWSTR				FileName,
		PDOKAN_FILE_INFO	DokanFileInfo)
	{
		UNREFERENCED_PARAMETER(FileName);
		UNREFERENCED_PARAMETER(DokanFileInfo);

		return STATUS_ACCESS_DENIED;
	}

Still, I can remove a file in the mounted drive.
It seems like `DeleteOnClose` is still being set in this case.

**Comment by justanotheranonymoususer** [comment]
OK, it seems like the system removes files not with `DeleteFile`, but with `CreateFile(..., FILE_FLAG_DELETE_ON_CLOSE, ...)`, so perhaps it's not a bug.

In general, I try to modify dokan_mirror so that the clone will be read-only. Is there a straightforward and complete way to do that, without filtering every flag (such as `FILE_FLAG_DELETE_ON_CLOSE`) explicitly?

**Comment by Liryna** [comment]
You are right, files are only delete in cleanup when open with deleteonclose flag.
About read only, if you change right access when MirrorGetFileInformation is requested. It should make the work.

**Comment by justanotheranonymoususer** [comment]
`MirrorGetFileInformation` doesn't seem to provide a solution. But returning `STATUS_ACCESS_DENIED` for every operation that requires write access seems to work. If you have other ideas about it, let me know :)

**Comment by marinkobabic** [comment]
Normally to provide a readonly device the device characteristics must be changed
to https://msdn.microsoft.com/en-us/library/windows/hardware/ff563818(v=vs.85).aspx  FILE_READ_ONLY_DEVICE

**Comment by justanotheranonymoususer** [comment]
Thanks @marinkobabic. Here's my attempt: https://github.com/dokan-dev/dokany/pull/72
