### ISSUE TITLE
Build with CMake and free toolchains (MinGW)

### ISSUE THREAD

**Issue by KOLANICH** [dokan-dev/dokany#711]
Microsoft Visual Studio is a compiler bundled with telemetry. I wonder if we can move dokany build to CMake and free toolchains.

**Comment by KOLANICH** [comment]
Hi, @Liryna.

>What would be the purpose of this even if possible since the project only target windows ?

the purpose is to build the software without using any proprietary commercial compilers like Visual Studio.
1 I cannot easily download it since to download it I have to run their software with telemetry. It can be possible to reverse engineer their downloader, but this is way to nowhere, since the tool is still proprietary and closed source.
2 As far as I remember, VS itself contains telemetry. Though it may be possible to carve it out, again, playing cat-and-mouse game is a way to nowhere.
3 It is commercial software. That it is free as in "free beer" doesn't mean that it is free in enterprise environment.

I guess that the userspace library can be built without VS somehow. I mean if I want to build the software with gcc, it is a bad idea to rely on libraries using MS runtime, since gcc uses other runtime (and according to StackOverflow, it is hard to make programs built with gcc use MS runtime) using differrent conventions. So we definitely need support for multiple toolchains.

>no idea with cmake handle the windows driver kit

I have done some experiments trying to build other software. You may or may not need MS WDK. MinGW and ReactOS have own WDKs, but they are far from being complete, it is possible to build some drivers with them (at least the ones used by ReactOS, and they have some FS drivers). Some drivers cannot be built with them. See https://github.com/open-source-ideas/open-source-ideas/issues/64 for more info.

**Comment by Liryna** [comment]
I see your point @KOLANICH . I will be glad to review a technical solution viable solution.
