### ISSUE TITLE
Dokany not properly forwarding file/directory deletion requests

### ISSUE THREAD

**Issue by lumip** [dokan-dev/dokany#718]
EDIT: hold on, have to check the checklist

# Environment
 * Windows version: 7 SP 1
 * Processor architecture: x64bit
 * Dokany version: 1.1.0.2000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ ] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

Judging from the code snippet below the dokany library tries to determine whether a file object is a directory or a plain file and then calling the corresponding deletion function in DokanOperations irrespective whether the file object deletion was invoked with the `DeleteFile` or `RemoveDirectory` Windows API function. 

https://github.com/dokan-dev/dokany/blob/83be68351c70d916e58bdae8e3424e521fe07b04/dokan/setfile.c#L118-L124

Example:
- There is file `Z:\testfile` in my filesystem mounted at `Z:`. 
- A program `p` calls `RemoveDirectory("Z:\testfile"). 
- Dokan library reroutes this to a `DokanOperations.DeleteFile` call which successfully completes since the object is indeed a directory
- The expected behavior would be for `RemoveDirectory` in `p` to fail with error `ERROR_DIRECTORY`

This is tested in the winfstest-suite which thus fails for my filesystem implementation and I seem to can't  fix this on my end..

**Comment by Liryna** [comment]
Hi @lumip ,

This is not a dokan issue. The call is preceded by a CreateFile that request a directory. It is at this point that the CreateFile will need to fail with `STATUS_NOT_A_DIRECTORY`
See https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L382

**Comment by lumip** [comment]
Ah, I see. I guess this changed from the orignal old Dokan? As far as I remember, that required to update the IsDirectory context information in the CreateFile, which was still happening in my code (my transition is not completely done, I guess)

**Comment by lumip** [comment]
I'm still getting calls to my `ZwCreateFile` that try to open a directory without having the `IsDirectory` is not set in the file info structure. Can you confirm that the following is required behavior for `ZwCreateFile` implementations:
- if `IsDirectory` is set 
-- if the requested path is not a directory, fail and return `STATUS_NOT_A_DIRECTORY`
-- if the requested path is a directory, proceed to open it as a directory
- if `IsDirectory` is not set
-- if the requested path is a directory, set `IsDirectory` and proceed opening the file as directory
-- if the requested path is not a directory, proceed to open it as a file

**Comment by Liryna** [comment]
@lumip This part is explained in the documentation. If something is missing I will be glad to add it.

**Comment by lumip** [comment]
At least that's how I understand the following
>If the file is a directory, CreateFile is also called. In this case, CreateFile should return STATUS_SUCCESS when that directory can be opened and DOKAN_FILE_INFO.IsDirectory has to be set to TRUE. On the other hand, if DOKAN_FILE_INFO.IsDirectory is set to TRUE but the path targets a file, STATUS_NOT_A_DIRECTORY must be returned.

(from https://dokan-dev.github.io/dokany-doc/html/struct_d_o_k_a_n___o_p_e_r_a_t_i_o_n_s.html#a40c2f61e1287237f5fd5c2690e795183 )

However, with this I run into the exactly opposite problem.. when a directory is deleted with `DeleteFile` by an application, I will have to set the `IsDirectory` flat and open the directory in `ZwCreate` according to docs. This will cause a call to `DokanOperations.DeleteDirectory` instead of `DokanOperations.DeleteFile`, which will incorrectly succeed..
I'm now confused :D

**Comment by Liryna** [comment]
@lumip Yes this is another similar case :-D it is handle à little more at the beginning of the mirror CreateFile. I cannot give a direct link right now but you should find it.

I will use your remarks to complet the document ^^

**Comment by lumip** [comment]
I guess it's here
https://github.com/dokan-dev/dokany/blob/099db8a0ff2fd6de422ea4f917f404acbf3d96c9/samples/dokan_mirror/mirror.c#L264-L279
The check makes sense.. but I can't do the same using the .NET-wrapper of dokany since most of the FileOptions, namely the FILE_NON_DIRECTORY_FILE is not included in the System.IO.FileOptions enum.

**Comment by lumip** [comment]
I'll close this as my question has been answered. (thanks for the really swift responses!) I don't really like how all this is done because it seems somewhat hacky with different checks for the same stuff in different places all over the filesystem implementation, though, and might have another look at how dokany handles the IsDirectory flag (and makes decisions about calls to DeleteFile/DeleteDirectory) if you don't mind.
