### ISSUE TITLE
CBFS comparison

### ISSUE THREAD

**Issue by Salamandar** [dokan-dev/dokany#721]
It's not a real issue, but CBFS spits on Dokan/Dokany on their side-by-side comparison : https://www.callbacktechnologies.com/kb/articles/cbfs-vs-dokan.rst

Some are "true" ("Professionally written and maintained code") but some are completely false ("Custom disk icons in Explorer").

Just wanted to give you a heads up.

**Comment by Liryna** [comment]
Hi @Salamandar ,

Thank you for the feedback.
That's unfortunately a known issue that we probably cannot do something about.
https://github.com/dokan-dev/dokany/wiki/Unsupported#alternatives
I always found it funny to see after so many years they are still paying for google ads with false information when looking for dokan/dokany on google.

It even seems to be personal more than business but it is a situation that existed much before I even knew/maintained dokan

**Comment by Rondom** [comment]
They have always had interesting marketing strategies, but the following article makes an entertaining read...
https://www.codeproject.com/Articles/581146/8-reasons-to-choose-commercial-library-instead-of
They used to have this one on their website, but at least from a quick glance, they seem to have removed it.

On a more serious note: Objectively, sure, Dokany has its drawbacks. Still I am always astonished how many companies use it and seem to be okay with that it does for their needs. Too bad that this is not reflected in the amount of patches and developers contributing...
