### ISSUE TITLE
Is GetFileInformation() supposed to always succeed?

### ISSUE THREAD

**Issue by lumip** [dokan-dev/dokany#722]
I've noticed that Dokan internally issues calls to DokanOperations.GetFileInformation() without there being a Windows API call to e.g. GetFileAttributes e.g. here https://github.com/dokan-dev/dokany/blob/83be68351c70d916e58bdae8e3424e521fe07b04/dokan/setfile.c#L105 .  In my implementation, these fail when the file handle was not opened with ReadAttribute access in CreateFile. 

Is GetFileInformation() supposed to always succeed?
[Documentation](https://dokan-dev.github.io/dokany-doc/html/struct_d_o_k_a_n___o_p_e_r_a_t_i_o_n_s.html#af06a3e372ed1ddbfe89e2f5046373dfd) states
>Returns
    STATUS_SUCCESS on success or NTSTATUS appropriate to the request result. 

which I interpreted to mean to return AccessDenied if required access was not requested.

**Comment by Liryna** [comment]
Hi @lumip,

As the documentation says, the `NTSTATUS` can be `STATUS_SUCCESS` or an appropriate to the request result like an error.
The truth is that `GetFileInformation` is used for a [lots different types](https://github.com/dokan-dev/dokany/blob/83be68351c70d916e58bdae8e3424e521fe07b04/dokan/fileinfo.c#L453-L550) of request made by `IRP_MJ_QUERY_INFORMATION` that has each of them allowed status like 
https://msdn.microsoft.com/en-us/library/cc232094.aspx
Currently we only return one type of failure
https://github.com/dokan-dev/dokany/blob/83be68351c70d916e58bdae8e3424e521fe07b04/dokan/fileinfo.c#L448 
but this could be improved by checking if all users returned error are allowed or not.

**Comment by lumip** [comment]
In the example I linked above, the function `DokanSetDispositionInformation` internally calls `GetFileInformation` to do some of request verification / access check for deletion. This call to `GetFileInformation` is never caused by an explicit `IRP_J_QUERY_*` but Dokan internal.
If I not return `STATUS_SUCCESS` in this case in my implementation of `GetFileInformation`, will that be a problem for Dokan?

**Comment by Liryna** [comment]
Oh I have not seen it was this `GetFileInformation` that you pointed sorry.
You can return an error here but it would mean you implementation would not be able to return `STATUS_CANNOT_DELETE` when you file is readonly.

You can, however, handle this case in DeleteFile or DeleteDirectory if you can.

**Comment by Liryna** [comment]
This would probably create duplicate code on the implementation side by doing this. Especially, if we start like this we may create more than a single operation for each special case and feature that need to be handled. Here we are lucky enough that this function can be called to get the proposer information without needing to create a new one.

**Comment by lumip** [comment]
alright
