### ISSUE TITLE
Guard #pragma warnings() with #ifdef _MSC_VER

### ISSUE THREAD

**Issue by Salamandar** [dokan-dev/dokany#725]
Everything is in the title.

Some headers have `#pragma warning(…)` inside so we have compiler warnings.

Those lines should be guarded by compiler detection like `#ifdef _MSC_VER` ;)

**Comment by Rondom** [comment]
Can you submit a pull request, with your changes? That would be great.

**Comment by Salamandar** [comment]
Finally got the time to work on it.
It's only used in public.h, lines ~365 and 379.
You should write
```

#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable : 4201)
#endif
typedef struct _DOKAN_RENAME_INFORMATION {
#if (_WIN32_WINNT >= _WIN32_WINNT_WIN10_RS1)
	union {
		BOOLEAN ReplaceIfExists;  // FileRenameInformation
		ULONG Flags;              // FileRenameInformationEx
	} DUMMYUNIONNAME;
#else
	BOOLEAN ReplaceIfExists;
#endif
  ULONG FileNameLength;
  WCHAR FileName[1];
} DOKAN_RENAME_INFORMATION, *PDOKAN_RENAME_INFORMATION;
#ifdef _MSC_VER
#pragma warning(pop)
#endif
```

**Comment by Liryna** [comment]
Done 👍 @Salamandar https://github.com/dokan-dev/dokany/commit/d24abedd3150b8cc0b2ec05a148b5bf387e82916
Thank you !

**Comment by Salamandar** [comment]
Great !
