### ISSUE TITLE
Question about PDOKAN_FILE_INFO.Context

### ISSUE THREAD

**Issue by samokhodkin** [dokan-dev/dokany#726]
Hi!

I'm playing with the library, and am a bit confused about who controls the PDOKAN_FILE_INFO.Context, the driver or a filesystem application.  The documentation says: 

"DOKAN_FILE_INFO.Context is an arbitrary value assigned by the file system application."

So I expected that its value is null when the ZwCreateFile is called. 
Instead, the structure comes with already assigned Context, which takes consequtive values (1,2,3,...) upon each next call of ZwCreateFile.
Who is assigning it, and *may I assign my own value instead?*

Thanks
I'm playing with the dokany via dokan-java interface.

**Comment by Liryna** [comment]
Hi @samokhodkin ,

`DOKAN_FILE_INFO.Context is an arbitrary value assigned by the file system application.` Here the file system application is your app.
During `ZwCreateFile` it should have the value null but seems like dokan-java has already set a value before providing it to your code.

Can you move this issue to the good repository ?

**Comment by samokhodkin** [comment]
Hi!
Sorted it out, it's my fault. I'm sorry. Please close it.

Thanks
