### ISSUE TITLE
Squashfuse with dokan_fuse wrapper

### ISSUE THREAD

**Issue by gustavocarita** [dokan-dev/dokany#730]
Hello everyone! 

I want to port squashfuse into Windows using Dokan fuse wrapper... I'm not experienced in windows systems and dokan is a totally new world to me, how hard would it be to have it accomplished?

Or is just a matter of compiling squashfuse with dokan_fuse wrapper?

Thanks!

**Comment by Liryna** [comment]
Hi @gustavocarita ,

Normally you should only need to build your fs against the dokan fuse wrapper. The difficulty will depend on the implementation.
For example, the fuse mirror has been used directly without changes.

Good luck on your port on windows !

**Comment by gustavocarita** [comment]
I was able to compile squashfuse already on windows, but too bad I needed the Lowlevel API and that is not supported by dokany at the moment.
