### ISSUE TITLE
Mounting with mirror.exe hangs

### ISSUE THREAD

**Issue by DimitarKapashikov** [dokan-dev/dokany#733]
# Environment
 * Windows version: Windows 10
 * Processor architecture: x64
 * Dokany version: 1.1.0
 * Library type (Dokany/FUSE): Dokany mirror.exe
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Mounting with mirror.exe ( mirror.exe /m /r c:\users /l m ) hangs. Antivirus is disabled.
[dbgview-08302018.log](https://github.com/dokan-dev/dokany/files/2345368/dbgview-08302018.log)

# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
In case of BSOD, please attach minidump or dump analyze output.

**Comment by Liryna** [comment]
Hi @DimitarKapashikov ,

Could you give more information on how this is happening, what is exactly the behavior and how to reproduce this ?

**Comment by DimitarKapashikov** [comment]
HI @Liryna,

When I execute the mirror.exe (mirror.exe /m /r c:\users /l m) I can see the drive letter but I cannot access the content.

Regards,
Dimitar

**Comment by Liryna** [comment]
Does the mirror logs shows activity ? The device dismounts himself ?

**Comment by DimitarKapashikov** [comment]
Hi @Liryna 

Do you mean the logs generated by mounting with /d ?

Thanks and Regards,
Dimitar

**Comment by Liryna** [comment]
Yes with `/d /s` if you want the std output.

**Comment by DimitarKapashikov** [comment]
[dbgview-09062018.log](https://github.com/dokan-dev/dokany/files/2360906/dbgview-09062018.log)

Hi @Liryna ,

Attached is the new log with d option.

Regards,
Dimitar

**Comment by Liryna** [comment]
Hi @DimitarKapashikov ,

Thank you for the logs. Seems like you have a software looking for McAfee files.
Probably it is him that do not let you get access to the device until he succeed.
In the logs there is not special error code that I found.

**Comment by Liryna** [comment]
Hi @DimitarKapashikov ,

Have you been able to find if McAfee was releated to your issue ?

**Comment by DimitarKapashikov** [comment]
Hi @Liryna ,

We are still investigating ,on machines where the McAfee EERM is not installed it works. I am going to update you once we have more information.

Thanks and Regards,
Dimitar

**Comment by DimitarKapashikov** [comment]
Hi @Liryna 

Changing the McAfee policy for removable media, fixed the issue. Thank you very much for your support.

Dimitar

**Comment by Liryna** [comment]
Thank you @DimitarKapashikov for the feedback ! Glad that you found a solution !
