### ISSUE TITLE
fuse read after close

### ISSUE THREAD

**Issue by lijie0123** [dokan-dev/dokany#734]
# Environment
 * Windows version: 10.0.17134.228
 * Processor architecture: amd64
 * Dokany version: 1.2.0.1000
 * Library type (Dokany/FUSE): FUSE
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
fuse will still read after the file is closed and cause invalid memory access.
The bug is in method ''impl_fuse_context::read_file'' in file "fusemain.cpp", line 614. While in this read loop, the file is closed at another thread, the hndl will be deleted, and cause the dangling pointer access.

# Logs

**Comment by Liryna** [comment]
Hi @lijie0123 ,

Can you provide a sample to reproduce the behavior ?
Normally kernel would not request a close if there is still a read pending. Or it means the read was taking too much time and kernel has supposed the request has timeout.

**Comment by lijie0123** [comment]
My log is bellow:
14984 TRACE [11328] read: ENTER: path=/hisense_demonstration_visual-DWEU.mkv,offset=335544320,size=65536 
15121 TRACE [13380] release: ENTER: path=/hisense_demonstration_visual-DWEU.mkv
15130 TRACE [13380] release: EXIT:  path=/hisense_demonstration_visual-DWEU.mkv
15199 TRACE [11328]  read: EXIT:  path=/hisense_demonstration_visual-DWEU.mkv,offset=335544320,size=65536 

When I use windows movies & TV application to open a video and drag progress bar and close the app, the fuse wrapper crashed because of access invalid memory. But with VLC, it is all OK, vlc will close after the read procedure return back.

When I update macro  MAX_READ_SIZE  to a larger number, this problem is avoided.

Reading process only take 0.2s and it is not timed out because with a larger MAX_READ_SIZE, it is not time out.

So, the file can be closed while reading procedure has not finished, and the while loop in the fuse_main impl_fuse_context::read_file function will cause invalid memory access and it can not be mitigated by client code.

**Comment by kyanha** [comment]
@Liryna  Recall that Dokan 0.6.0's documentation stated that outstanding reads and writes can occur after Cleanup is called, particularly in the case of paged I/O.  I think this was probably an oversight in the design of the original Dokan 0.6.0, and nobody's revisited that design decision.

From https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/dispatchcleanup-routines:

```
While processing an IRP_MJ_CLEANUP request, a driver can receive additional requests, such as 
IRP_MJ_READ or IRP_MJ_WRITE. Therefore, a driver that must deallocate resources must also 
synchronize execution of its DispatchCleanup routine with other dispatch routines, such as 
DispatchRead and DispatchWrite.
```
(Please see that URL for the process that should happen, including canceling all outstanding read or write IRPs for the handle that's being cleaned up, and locking additional read and write IRPs for that handle.  This should probably be done before the user-mode Cleanup routine is called.  But, I haven't looked at the code, so it's entirely possible it's already done and I'm barking up the wrong tree.)

**Comment by Liryna** [comment]
@kyanha Our cleanup is very simple for now... It would be indeed a great improvement to look for pending read write irp and proceed them before the cleanup that we would delay!

**Comment by kyanha** [comment]
If there's a need to prevent additional IRP_MJ_(READ|WRITE) during IRP_MJ_CLEANUP, we need to track the underlying filenames that currently have outstanding Cleanup dispatches.  This suggests that it needs a list or a hash of those objects kept in-kernel in something of the following process (I'm calling the list or hash `ListOfCleanup` here):

To clean up all pending reads and writes:
1. Receive IRP_MJ_CLEANUP
2. Lock, Add name to `ListOfCleanup`, unlock.
3. Search all pending IRPs for IRP_MJ_(READ|WRITE) on the same handle, complete them.
4. Dispatch to usermode Cleanup routine.
5. On return from usermode Cleanup, complete the IRP.

On IRP_MJ_CLOSE:
1. Receive IRP_MJ_CLOSE
2. dispatch usermode CloseFile routine.
6. On return from usermode CloseFile routine, lock, remove handle from `ListOfCleanup`, unlock.

Then, for IRP_MJ_(READ|WRITE) (to prevent calls on a handle that's being cleaned up):
1. Receive IRP_MJ_(READ|WRITE).
2. Lock, Search name in `ListOfCleanup`, unlock.
3. If found, complete IRP with STATUS_CANCELED (? or is there a better one?)
4. If not already completed, dispatch usermode (Read|Write)File routine.

I have nowhere near enough knowledge in kernel mode to be able to write this myself.  :(

(The filename is how the kernel tracks files, and is most likely used when the last handle to the file is being closed.  I think that if the filesystem declares that it can open files by ID, the ID is used instead, but I have no evidence for this hypothesis.)

**Comment by Liryna** [comment]
This should be retested with the patch https://github.com/dokan-dev/dokany/commit/d3e3fcd9624cd1e9ed71dfd44edf28e6f590a14d

**Comment by Liryna** [comment]
Close for inactivity and as it might be patched with the above commit.
