### ISSUE TITLE
Q: Unexpected upper case paths in some callbacks

### ISSUE THREAD

**Issue by samokhodkin** [dokan-dev/dokany#735]
Hi, guys.

My FS is case-sensitive and I cannot make it work.
My GetVolumeInformation returns 
 FILE_CASE_PRESERVED_NAMES | FILE_CASE_SENSITIVE_SEARCH | FILE_UNICODE_ON_DISK
in rawFileSystemFlags. But this doesn't help.

For example, when create a directory:
> mkdir mydir

the system calls ZwCreateFile("\mydir",...).

But if I do
> cd mydir

the system calls ZwCreateFile("\MYDIR",...), which is not found.

What may I do to provide the consistent behaviour? Or, more generally, how to install the case-sensitive FS?

Thanks

P.S. A related question. The ProcMon doen't see any calls to dokan folders. 
Is the same with you, or I'm doing something wrong?

**Comment by Liryna** [comment]
Hi @samokhodkin ,

How are you mounting the FS ? Reparse point ?

**Comment by samokhodkin** [comment]
My previous comment had a mistake, the problem doesn't show when mounting as volume.
I found this problem is well known, and has been fixed in recent release.

https://github.com/dokan-dev/dokany/issues/293
https://github.com/dokan-dev/dokany/issues/712
https://github.com/dokan-dev/dokany/pull/713/commits/8d37170333114d9347a88b044255860ca385b413

Close, please
