### ISSUE TITLE
Start/Stop service is broken

### ISSUE THREAD

**Issue by alexander-ossur** [dokan-dev/dokany#738]
# Environment
 * Windows version:  8.1
 * Processor architecture: x64
 * Dokany version: 1.2.0.1000 installed by MSI
 * Library type (Dokany/FUSE): 
 
# Description
It does not matter if I Start/Stop Dokan1 programmatically or use "dokanctl.exe" or use "SC.exe", it will stuck in "ERROR_SERVICE_MARKED_FOR_DELETE  1072"

Simple steps to reproduce:
1. Install everything by MSI
2. Run "dokanctl /i d"
3. Run "dokanctl /r d"
3. And again run "dokanctl /i d" to install. This time it will tell us "Failed to install service (Dokan1). error = 1072"

The bug probably related to this: [https://support.microsoft.com/en-us/help/287516/bug-service-startup-type-is-disabled](https://support.microsoft.com/en-us/help/287516/bug-service-startup-type-is-disabled)

**Comment by Liryna** [comment]
Hi @alexander-ossur ,

After installing the msi, you do not need to run dokanctl /i d
Getting the error ERROR_SERVICE_MARKED_FOR_DELETE is normal after a /r d

**Comment by Liryna** [comment]
You are probably look at this https://github.com/dokan-dev/dokany/issues/669

**Comment by alexander-ossur** [comment]
Thank you @Liryna ,

Yes, it seems #669 is the reason of that behaviour. I will move there.
