### ISSUE TITLE
Does Dokany has any known C++ FS memory implementation?

### ISSUE THREAD

**Issue by alexander-ossur** [dokan-dev/dokany#740]
Sorry for asking it here. Consider this as a feature request

I found two solutions written in C#, but I need a C++ implementation

**Comment by Liryna** [comment]
@alexander-ossur Hi,

Are you looking at a c++ wrapper of the interface like the C# is going?
For now there is no such project as far as I know. If you plan to do one, I would be glad to answer your questions and add the projet as an official part of the dokan-dev.

**Comment by alexander-ossur** [comment]
Thank you @Liryna,

Not sure if this can be called as a wrapper. What I need is to store files and directories in RAM. A good example of that is https://github.com/billziss-gh/memfs-dokany.

Just wondering there are more alternatives.

**Comment by Liryna** [comment]
@alexander-ossur Both are using a library that communicate with a kernel driver. The wrapper is the code the wrap the C library to whatever language needed. What would be possible is to have an wrapper of the library interface to use the c++ std instead of pure C Handle for exemple.
