### ISSUE TITLE
ReadFile and WriteFile aren't called

### ISSUE THREAD

**Issue by samokhodkin** [dokan-dev/dokany#741]
Hi,

Some time ago I've had a working dokan-based application, but recently had to rewrite it because of 
extremely low speed.

I changed only the interface between java and native side, which was the performance bottleneck (changed JNA to bare JNI). The new version is supposed to work identically as previous, but it doesn't.

The problem is that in the new version the dokan refuses to call the two functions, namely the DOKAN_OPERATIONS.ReadFile and DOKAN_OPERATIONS.WriteFile. 
The rest functions are called just like in the previous version, only these two are completely skipped.

ProcMon data.
For example, I mount a "m:" dokan drive, open console, change the drive to "m:", and issue this command:
`echo aaa > tmp.txt`
In the old version this caused this ProcMon output:
`13:46:35,2348137	cmd.exe	1764	 CreateFile	\Device\Volume{d6cc17c5-172f-4085-bce7-964f1e9f5de9}\tmp.txt	SUCCESS	Desired Access: Generic Write, Read Attributes, Disposition: OverwriteIf, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, AllocationSize: 0, OpenResult: Created`

`13:46:35,2881083	cmd.exe	1764	 WriteFile	\Device\Volume{d6cc17c5-172f-4085-bce7-964f1e9f5de9}\tmp.txt	SUCCESS	Offset: 0, Length: 6, Priority: Normal`

`13:46:35,2908703	cmd.exe	1764	 CloseFile	\Device\Volume{d6cc17c5-172f-4085-bce7-964f1e9f5de9}\tmp.txt	SUCCESS`

and the file was successfully created and written to.

In the new version the same command causes the output that differs in one line:

`13:45:14,7923612	cmd.exe	1764	 CreateFile	\Device\Volume{d6cc17c5-172e-4085-bce7-964f1e9f5de9}\tmp.txt	SUCCESS	Desired Access: Generic Write, Read Attributes, Disposition: OverwriteIf, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, AllocationSize: 0, OpenResult: Created`

`13:45:14,8048548	cmd.exe	1764	 WriteFile	\Device\Volume{d6cc17c5-172e-4085-bce7-964f1e9f5de9}\tmp.txt	INVALID PARAMETER	Offset: 0, Length: 6, Priority: Normal`

`13:45:14,8057953	cmd.exe	1764	 CloseFile	\Device\Volume{d6cc17c5-172e-4085-bce7-964f1e9f5de9}\tmp.txt	SUCCESS	`

Note the INVALID PARAMETER in the WriteFile.

The dokan's debug output is also identical, except that in the previous version there were two lines
`###WriteFile 0004
###Read 0004
`
that are missing in the new version.

It's not a bug in the dokan, rather it's something in my app, but I'm completely stuck trying to find what I did wrong. I need a direction where to search. What may be causing the the dokan driver skip the read/write calls and return a INVALID PARAMETER instead?

Can someone help?

**Comment by Liryna** [comment]
Hi @samokhodkin ,

Would it be possible that device is mounted as read only ?
Can you share the debug log ?

**Comment by samokhodkin** [comment]
Hi, @Liryna,

I have finally found it! As stupid a typo as it looks
   public static final byte TRUE=1;
   public static final byte FALSE=1;

In fact this affected only the  DOKAN_FILE_INFO.IsDirectory, so either the
system or the driver saw the attempt to write to the directory.

Now everything works great, close the thread.

And KUDOS+++ for your work.
