### ISSUE TITLE
Work with error disk

### ISSUE THREAD

**Issue by Martin736** [dokan-dev/dokany#742]
Hello,

I try to use dokan mirror example to mirror a chkdsk error disk. The disk has bugs and sometimes chdsk reports errors.

When I use mirror, the process terminate without error messages but the return value is "-1073740791".

Looks like mirror don't catch that disk errors and exits without message. Using "/d /s" last log ist every time "### Create 0000". Sometimes nothing else, sometimes later with higher numbers than 0000.

# Environment
 * Windows version: 10 32bit
 * Processor architecture: AMD x64
 * Dokany version: 120, 0x190
 * Library type (Dokany/FUSE): ?
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
mirror a chkdsk disk exit mirror without message

# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
In case of BSOD, please attach minidump or dump analyze output.

**Comment by Liryna** [comment]
Hi @Martin736 ,

Can you be more precise ? I do not fully understand what you try to achieve and what is happening.
Also full logs mirror and kernel would be helpful here.

**Comment by Martin736** [comment]
> I try to use dokan mirror example to mirror a chkdsk error disk. The disk has bugs and sometimes chdsk reports errors.

> When I use mirror, the process terminate without error messages but the return value is "-1073740791".

> Looks like mirror don't catch that disk errors and exits without message. Using "/d /s" last log ist every time "### Create 0000". Sometimes nothing else, sometimes later with higher numbers than 0000.

Yes, first I will explain a litle bit more.

1. HDD disk having errors (chkdsk errors).
2. Mirror the disk (1.) to a dokan drive.
3. Access a file at the dokan drive (2.) where the real disk (1.) has a error and return a disk error, mirror terminate (exit) without a message or a Debug-Log and the return code of the error from the disk (1.)

I want to catch the error from the disk access (1.) and return the error as a error oft the dokan disk (2.) and that mirror don't exit without message (3.).

**Comment by Martin736** [comment]
are you sure that kernel debug is needed here?

**Comment by Rondom** [comment]
I am not sure I understand what you want to achieve. I think if the mirror exits without a warning in case of such errors that's an issue we should investigate.

If you want to solve some issue by using the mirror,  though, then I am not sure what you expect the mirror to do. It won't magically solve any problems you have accessing that filesystem using normal means, because the mirror will access it in the same way other applications access it.

**Comment by Martin736** [comment]
> I think if the mirror exits without a warning in case of such errors that's an issue we should investigate.

Yes.

> It won't magically solve any problems you have accessing that filesystem using normal means, because the mirror will access it in the same way other applications access it.

Yes, access a file that produce a file system error. When I try to open the file by notepad.exe on disk a popup "File system error (-1073741521)." and button "ok".

And now: When I try to open the file by notepad.exe on the mirror disk, the mirror.exe terminates with return code "-1073741521" and without message, mirror disk removed.

What I want to achieve: When I try to open the file by notepad.exe on the mirror disk, the mirror.exe not terminates and notepad.exe produced a popup "File system error (-1073741521)." and button "ok", like access disk direct without mirror.exe

**Comment by Martin736** [comment]
To make it more precise: When you Google images "File system error (-1073741521)" you see images from the error message. I want to see the error message using mirror.exe and not that mirror.exe terminates and disk dismount.

**Comment by Liryna** [comment]
Hi @Martin736 ,

As I understand, we will have difficulty to reproduce the issue unless we have a disk with errors.

Can you see if the mirror crash ? It seems by the log that it is not complete and the mirror stop unexpectedly. Can you attach a debugger on it and see where does the crash comes from ?

**Comment by Martin736** [comment]
> As I understand, we will have difficulty to reproduce the issue unless we have a disk with errors.

yes, I think so too.

> Can you see if the mirror crash ? It seems by the log that it is not complete and the mirror stop unexpectedly. Can you attach a debugger on it and see where does the crash comes from ?

I was not able to debug the kernel module until now, I think the mirror.exe crash at "MirrorCreateFile" before first Debug message?

**Comment by Martin736** [comment]
perhaps not "MirrorCreateFile", when a other function is called before "MirrorCreateFile" and after "### Create XXXXX" output.

**Comment by Liryna** [comment]
@Martin736 Thats possible. No need kernel debug for now. Everything seems to be in the mirror since you dont even has the log of MirrorCreateFile

**Comment by Martin736** [comment]
I add a Debug line to MirrorCreateFile and I can see that MirrorCreateFile is called before crash.

**Comment by Liryna** [comment]
Hi @Martin736 ,

Have you been able to get more informations on your case ?
