### ISSUE TITLE
DokanKeepAlive CreateFile failed

### ISSUE THREAD

**Issue by alexander-ossur** [dokan-dev/dokany#743]
# Environment
 * Windows version: 8.1
 * Processor architecture: x64
 * Dokany version: 1.2.0
 * Library type (Dokany/FUSE): Dokany
 
# Description
Error appears when I am debugging my own code which is using Dokany API. Although it seems working okay if I just run a code without breakpoints.

There is no smallest possible code for reproduction yet, but the steps are:
1. Run DokanMain and wait for Mounted event
2. Do some simple operations like: std::filesystem::create_directory ("I:\\TEMP\\[mount point]\\directory1\\directory2")
3. Now next operation is marked with breakpoint: std::filesystem::exists ("I:\\TEMP\\[mount point]\\directory1\\directory2")
Debugger will pause at this point waiting for user's action. Let's say I am investigating variables and etc for 30 seconds and then hit "Step Over" button.
Dokany will fail with "DokanKeepAlive CreateFile failed". Logs attached.

What I did:
1. DOKAN_OPTIONS::Timeout was set to much higher value. BTW what is the default value?
2. Initially DOKAN_OPTIONS::ThreadCount was set to "1", as I wanted to minimize all that "jumping" mess while debugging
3. DOKAN_OPTIONS::ThreadCount was set to "2"

# Logs

> Dokan: debug mode on
> AllocationUnitSize: 512 SectorSize: 512
> device opened
> CreateMountPoint I:\TEMP\fjbe6fbwk87sb_test -> \??\Volume{d6cc17c5-1735-4085-bce7-964f1e9f5de9}\ success
> mounted: I:\TEMP\fjbe6fbwk87sb_test -> \Volume{d6cc17c5-1735-4085-bce7-964f1e9f5de9}
> ###Create 0000
> CreateFile status = c0000034
> ###Create 0001
> ###QueryVolumeInfo -001
> CreateFile status = 0
> ###GetFileInfo 0001
> 	result =  0
>   unknown type:54
> 	DispatchQueryInformation result =  c000000d
> ###GetFileInfo 0001
> 	result =  0
> 	FileStandardInformation
> 	DispatchQueryInformation result =  0
> ###GetFileInfo 0001
> 	result =  0
> 	FileBasicInformation
> 	DispatchQueryInformation result =  0
> ###Cleanup 0001
> ###Close 0001
> ###Create 0002
> CreateFile status = 0
> ###GetFileInfo 0002
> 	result =  0
> 	FileStandardInformation
> 	DispatchQueryInformation result =  0
> ###GetFileInfo 0002
> 	result =  0
> 	FileNetworkOpenInformation
> 	DispatchQueryInformation result =  0
> ###Cleanup 0002
> ###Close 0002
> ###Create 0003
> CreateFile status = 0
> ###GetFileInfo 0003
> 	result =  0
> 	FileStandardInformation
> 	DispatchQueryInformation result =  0
> ###GetFileInfo 0003
> 	result =  0
> 	FileNetworkOpenInformation
> 	DispatchQueryInformation result =  0
> ###Cleanup 0003
> ###Close 0003
> ###Create 0004
> CreateFile status = 0
> ###Create 0005
> ###GetFileInfo 0004
> 	result =  0
> 	FileStandardInformation
> 	DispatchQueryInformation result =  0
> ###Cleanup 0004
> CreateFile status = c0000034
> ###Close 0004
> ###Create 0006
> ###Create 0007
> CreateFile status = 0
> CreateFile status = 0
> ###GetFileInfo 0006
> 	result =  0
> 	FileStandardInformation
> ###GetFileInfo 0007
> 	DispatchQueryInformation result =  0
> 	result =  0
> 	FileStandardInformation
> 	DispatchQueryInformation result =  0
> ###GetFileInfo 0006
> ###QueryVolumeInfo 0007
> 	result =  0
> 	FileBasicInformation
> 	DispatchQueryInformation result =  0
> ###Cleanup 0007
> ###Cleanup 0006

Now I am waiting for 30 secs, and then hit "Step Over" button

> ###Close 0007
> Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1735-4085-bce7-964f1e9f5de9}: 2
> The thread 0x2a1c has exited with code -1 (0xffffffff).
> Dokan Error: DokanKeepAlive CreateFile failed \\.\Volume{d6cc17c5-1735-4085-bce7-964f1e9f5de9}: 2
> Dokan Error: CreateFile failed \\.\Volume{d6cc17c5-1735-4085-bce7-964f1e9f5de9}: 2
> The thread 0x1a04 has exited with code 0 (0x0).
> The thread 0x2434 has exited with code -1 (0xffffffff).

**Comment by Liryna** [comment]
Hi @alexander-ossur ,

This is the expected behavior. The Kernel driver will unmount the device if he has no answer from the library for more than X seconds. Without it, it would leave the computer in an unstable environment with a ghost device that timeout every request of every software.
