### ISSUE TITLE
Subsequent ::CreateFile call gives different DesiredAccess

### ISSUE THREAD

**Issue by alexander-ossur** [dokan-dev/dokany#744]
# Environment
 * Windows version: 8.1
 * Processor architecture: x64
 * Dokany version: 120
 * Library type (Dokany/FUSE): Dokany
 
# Description
To test I am creating a new file HANDLE:
`handle1 = ::CreateFile (filename, GENERIC_ALL, FILE_SHARE_READ | FILE_SHARE_WRITE, NULL /*default security*/, CREATE_NEW, FILE_ATTRIBUTE_NORMAL, NULL /*no attr. template*/);`

ZwCreateFile gives a good amount access into ACCESS_MASK. Specifically:
> bit, hex, name
> 1 1 FILE_READ_DATA
> 10 2 FILE_WRITE_DATA
> 100 4 FILE_APPEND_DATA
> 1000 8 FILE_READ_EA
> 10000 10 FILE_WRITE_EA
> 100000 20 FILE_EXECUTE
> 1000000 40 ???
> 10000000 80 FILE_READ_ATTRIBUTES
> 100000000 100 FILE_WRITE_ATTRIBUTES
> 10000000000000000 10000 ???
> 100000000000000000 20000 READ_CONTROL
> 1000000000000000000 40000 ???
> 10000000000000000000 80000 ???
> 100000000000000000000 100000 SYNCHRONIZE

Now, while holding a handle, I am opening the same file:
`handle2 = ::CreateFile (filename, GENERIC_ALL, FILE_SHARE_READ | FILE_SHARE_WRITE, NULL /*default security*/, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL /*no attr. template*/);`

This time ZwCreateFile gives absolutely different access mask. Is there any reason of that or it's just a bug?

Thank you in advance.

**Comment by Liryna** [comment]
Hi @alexander-ossur ,

The param of ZwCreateFile are provided directly from the Kernel Windows. You can use procmon if you would like to see exactly what is happening and reproduce the behavior on NTFS.

**Comment by Liryna** [comment]
Hi @alexander-ossur ,

Have you been able to take a look procmon ?
