### ISSUE TITLE
Support set file tag attribute?

### ISSUE THREAD

**Issue by winneryong** [dokan-dev/dokany#751]
Hi,
I use https://github.com/Dijji/FileMeta to set file **tag** attribute in explorer, But dokany not support this operations，Popup an error dialog。
**Will it support in the future?**

**Comment by Liryna** [comment]
Hi @winneryong ,

Could you provided the error message ? Have you made a test with the mirror sample or just with pyfs ?
Please describe how to reproduce it.

**Comment by winneryong** [comment]
Hi, @Liryna 
I use **mirror.exe** and **FileMeta** to set an .txt file tag, is ok, no error. 
When i use pyfs to mount remote file system as local disk drive H:, and use **FileMeta** to set .txt file tag in Driver H:,  input tag content and click save button, pop an error dialog,  Error code : **0x80030057** Messsage: Invalid parameter error.
ENV:
windows 10 x64
dokany 1.1.0
pyfilesystem:  1.0  see attachment
 
[dokan.zip](https://github.com/dokan-dev/dokany/files/2545925/dokan.zip)

**Comment by Liryna** [comment]
Hi @winneryong ,

I made a test using the C mirror
https://github.com/dokan-dev/dokany/tree/master/samples/dokan_mirror also available in your dokan install folder
There is no problem to set / edit the tag of FileMeta
![image](https://user-images.githubusercontent.com/4311419/47966394-19d30500-e052-11e8-969d-2e0d7885e847.png)

This is probably an error or a case not supported in pyfs. Will need logs to see where does the invalid parameter would come. I would guess during a CreateFile. Could you provide them ?

**Comment by winneryong** [comment]
Hi @Liryna 
Thank you for your reply, I will test pyfs again, and then give you feedback.

**Comment by Liryna** [comment]
Hi @winneryong ,

You can enable the debug logs in this way:
https://github.com/PyFilesystem/pyfilesystem/blob/master/fs/expose/dokan/__init__.py#L1154

**Comment by Liryna** [comment]
Hi @winneryong ,

Please ping me on the issue https://github.com/PyFilesystem/pyfilesystem/issues/280 when you have the required information to continue.
