### ISSUE TITLE
Microsoft Office doc save behaves different for different versions of Windows 10

### ISSUE THREAD

**Issue by Arup-MK-Halder** [dokan-dev/dokany#754]
# Environment
 * Windows version: Windows 10 version 1511,1607,1711 & 1803
 * Processor architecture: Intel(R) core(TM) i7-4800MQ CPU@2.70GHz 2.69GHz  
 * Dokany version: 1.2.0.100
 * Library type (Dokany/FUSE): Dokany
 
# Description
We are trying open a MS office file, edit and save the same.
We are creating the tmp files in our application cache and when try to replace the original office file with the updated tmp file, it fails. While debugging our application we found that the file is in use by another process.

It only work fine in Windows 10 ver 1803

# Logs
The file tested with mirror is 1.docx
[mirror.log](https://github.com/dokan-dev/dokany/files/2574888/mirror.log)

**Comment by Liryna** [comment]
@Arup-MK-Halder Hi,

It is a normal behavior that office behave differently or even the system behave differently depending on the windows or office version. Dokan only forward what the kernel is requesting.

In your issue, do you report this behavior change or that office do not work in the mirror?

**Comment by Arup-MK-Halder** [comment]
Hi @Liryna ,

Thanks for your response.

I tried with mirror and it worked fine.
It seems that our application(uses DokanNet) is accessing the file and thus we are getting the error.
We even debugged to check any open file handle that might be causing the issue but didn't found any.
The same application code works fine when on Windows 10 ver 1803.

**Comment by Arup-MK-Halder** [comment]
Hi @Liryna ,
I tried capturing the dokan debug logs, if this can be helpful.
[MDD16-5CLIENT.LOG](https://github.com/dokan-dev/dokany/files/2583840/MDD16-5CLIENT.LOG)

**Comment by Liryna** [comment]
Hi @Arup-MK-Halder ,

By looking at the mirror logs, I did not find an error during the process. What is exactly the error you are getting ?

**Comment by Arup-MK-Halder** [comment]
Thanks for for help.
Found that CreateFile implementation had used get Process.GetProcessById() and had not closed it. Causing the file handle to be open and thus causing the above issue.
