### ISSUE TITLE
On win 10 machine, you need admin privilege to run Dokany mirror application

### ISSUE THREAD

**Issue by vikas25538** [dokan-dev/dokany#757]
On win 10 machine, if i try to run mirror application i get following message:
Failed to add security privilege to process
=> GetFileSecurity/SetFileSecurity may not work properly
=> Please restart mirror sample with administrator rights to fix it.

Is there a way to overcome\avoid this. This is crucial as i cannot run the application in administrator mode.

I checked the earlier issues, there is no concrete workaround for this.

In our application which uses Dokany for file system, on win 10, same thing is happening. We need admin privilege to run the application as the mounted drive does not behave properly, for example file operations fail.

**Comment by Liryna** [comment]
Hi @vikas25538 ,

You can run your FS application as a service and you would get the admin right required to do the GetFileSecurity/SetFileSecurity

**Comment by vikas25538** [comment]
It did not work. Still hitting the same issue. 
Could you explain the reason for Dokany to require admin mode?
Is this required just at the start to do something with raised privilege OR Dokany working will continuously do something with raised privilege i.e.  is it some one off task or Dokany need throughout admin privilege?

**Comment by Liryna** [comment]
Please see https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L1646-L1655
It is only for the sample. Dokan does not need admin rights

**Comment by vikas25538** [comment]
My observation is different.
On win 10, my application which integrates with Dokany is working only if i run it in admin mode. If i run my application in normal user mode then file operations on the mapped drive fail.

Only change we have done is integration with Dokany. To confirm the behavior, i ran Dokany mirror application and it logged that you need admin privilege. This led us to conclude that Dokany needs admin privilege. Your previous comments contradicts that.

**Comment by vikas25538** [comment]
From mirror code, i see that the g_HasSeSecurityPrivilege flag is used in below section of code which i believe is called very frequently.

  HANDLE handle = CreateFile(
      filePath,
      READ_CONTROL | ((requestingSaclInfo && g_HasSeSecurityPrivilege)
                          ? ACCESS_SYSTEM_SECURITY
                          : 0),
      FILE_SHARE_WRITE | FILE_SHARE_READ | FILE_SHARE_DELETE,
      NULL, // security attribute
      OPEN_EXISTING,
      FILE_FLAG_BACKUP_SEMANTICS, // |FILE_FLAG_NO_BUFFERING,
      NULL);

**Comment by Liryna** [comment]
If Mirror operations fail, it means the process user does not have the right to access / get proper data on your mirrored folder.

As you just linked, CreateFile is Win32 API, if it fail it mean your user has no right to process it.

**Comment by vikas25538** [comment]
Same logic must be applicable for Dokany thats why it works in admin mode with my application. Please correct if i am wrong.

**Comment by vikas25538** [comment]
My bad. I was under the impression that mirror application internally uses Dokany.
So the way we are using Dokany in our application is making it require admin rights. Does this seem correct explanation?

**Comment by Liryna** [comment]
If you are using Win API that requires admin rights or elevated normal user rights, yes. I am just surprised that running as a service is not working. It should be strong enough to process standard request.

**Comment by Liryna** [comment]
@vikas25538 do not hesitate if you find the issue should be reopened.
