### ISSUE TITLE
On some win 10 machines, opening of word/excel/ppt file from mapped drive throws error

### ISSUE THREAD

**Issue by vikas25538** [dokan-dev/dokany#758]
# Environment
 * Windows version: win 10 enterprise
 * Processor architecture: x64
 * Dokany version: 1.2.0
 * Library type (Dokany/FUSE):  Dokany
 
![untitled](https://user-images.githubusercontent.com/10174998/49273258-69aebb80-f49a-11e8-97d5-f06af191b041.png)

In our application, we are using Dokany FS. Dokany FS integration works on win 7 machines but has issues on win 10 machines. Navigation works just fine but opening the file fails with the error depicted in attached image.
I tried replicating the behavior with mirror application. With mirror application, it works fine but you need to run it in admin mode.

I started my application in admin mode and it worked on that machine also.
BTW this current user of the machine is Administrator only.

**Comment by Liryna** [comment]
@vikas25538 Hi,

I think here you will need to compare the mirror logs and your FS to find which calls return an error or from when the behavior of calls are not the same.

**Comment by vikas25538** [comment]
@Liryna 
How to generate logs for Dokany? 
My application mounts FS with following options:
DokanOptions.RemovableDrive | DokanOptions.StderrOutput

**Comment by Liryna** [comment]
https://dokan-dev.github.io/dokany-doc/html/group___d_o_k_a_n___o_p_t_i_o_n.html#ga9892226236c01bb264d701023cfc539b
You will also need to enable debug and have a console to display the logs or output will be sent to debugger
See https://msdn.microsoft.com/fr-fr/library/windows/desktop/aa363362(v=vs.85).aspx

**Comment by vikas25538** [comment]
[win10_64_normal mode.LOG](https://github.com/dokan-dev/dokany/files/2638265/win10_64_normal.mode.LOG)


Hi @Liryna ,

I collected debug logs by running the application. There is unmount being called automatically. This is one difference i could see from the logs generated by running the application in non-admin mode.

**Comment by vikas25538** [comment]
@Liryna 
In my debug environment also, in normal mode unmount callback is coming while mounting itself.

**Comment by vikas25538** [comment]
@Liryna 
what is that request? What should i do to make it work without "run as administrator" option?

**Comment by Liryna** [comment]
Request are read / write / createfile that you get in your FS. One of them took too much time. See https://dokan-dev.github.io/dokany-doc/html/struct_d_o_k_a_n___o_p_t_i_o_n_s.html#ad953734dbc1baf170937eec8c1b4228b
https://dokan-dev.github.io/dokany-doc/html/group___dokan.html#ga1d5b0bf526fbf143a726fe1816fe7f15

About run as admin, I am able to open / edit a word document on my VM without admin rights. You will need to look on your side what errors do you get. Use procmon to see the call differences.

**Comment by vikas25538** [comment]
In the logs there  are no createfile calls. Moreover in debug mode i do not get any createfile callback.
If i do run the application as admin, i get createfile and other callbacks. It is specically on win 10 X64 machines.

**Comment by vikas25538** [comment]
@Liryna Can you point me to mount code so that i can see what it is doing?

**Comment by Liryna** [comment]
If you had no calls at all, how did you get to list and open the world file on your first screenshot ?

**Comment by vikas25538** [comment]
Our application has Shell Namespace extension integration with the help of which we map the server location onto the windows file system created via Dokan. So that mapping is there but dokany drive is unmounted.

In the below two images, you can clearly see the difference. My Documentum Desktop is there in both. But see the P drive mounted by Dokany.
![not working](https://user-images.githubusercontent.com/10174998/49426037-4dc25700-f7c5-11e8-85cf-d79c841715fa.png)
![working in when run as admin mode](https://user-images.githubusercontent.com/10174998/49426038-4dc25700-f7c5-11e8-9cbb-1bf9923fb29c.png)

**Comment by Liryna** [comment]
@vikas25538 Does your system is configured in any special way? Usually such behavior is when the device cannot be accessed. As you showed you get no request on drive side and it is unmount. But the communication is working at least at the beginning between the library and the driver to request a mont event.

**Comment by Liryna** [comment]
@vikas25538 You still have no output on library side when debug is enabled?

**Comment by vikas25538** [comment]
@Liryna I did not get the question. Please elaborate.
I removed antivirus from the machine and even windows defender program is switched off.

**Comment by Liryna** [comment]
For now you have only provided the kernel logs, can you also provide the dokan library logs ?

**Comment by vikas25538** [comment]
Additional Info:
we are referring the following link for our dot net integration:
https://github.com/dokan-dev/dokan-dotnet

In this one of the statement says "Administrator privileges are required to run file system applications."

**Comment by Liryna** [comment]
Please lets first confirm that the mirror is working. Another wrapper / implementation we will see later.

**Comment by vikas25538** [comment]
Running mirror requires you to run as administrator. So this problem does not arise. Moreover except win 10 x64 bit, the integration is all fine on other platforms.

**Comment by Liryna** [comment]
@vikas25538 If \testenv cannot be accessed by your non-admin. You FS will fail to get informations.
I do not have your env, I cannot say more.
`DokanOptions.NetworkDrive` does not need admin rights.
