### ISSUE TITLE
DokanLibraryInstaller: `Close` greyed out, can only click `Cancel`

### ISSUE THREAD

**Issue by nicolas-raoul** [dokan-dev/dokany#76]
I started installing DokanInstall_0.8.0.exe, it told me to install vcredist_x86.exe, so I did.

Now I am in this situation:

![dokan](https://cloud.githubusercontent.com/assets/99590/10158799/53a7d3fa-66cf-11e5-981d-5ffadfcbf11d.png)

`Close` is greyed out, it seems like I can only click `Cancel`.

What is happening? Did the installation succeed (as suggested by the "Completed" title) or fail? The UI does not make it obvious.

(Apparently the installation has actually failed)

**Comment by Liryna** [comment]
See release changelog: New installer embed VC++ redistributable - DokanInstall_X.X.X_redist.exe

**Comment by nicolas-raoul** [comment]
OK thanks! :-)
