### ISSUE TITLE
Merry Christmas Folks! 

### ISSUE THREAD

**Issue by TrabacchinLuigi** [dokan-dev/dokany#767]
Hey guys! Happy holidays and merry xmas! xD 👍 ❤️ 

This is not a bug! 🤣

**Comment by Liryna** [comment]
Merry Christmas you too @TrabacchinLuigi and to the other people of Dokan community!
May the open source be with you this year !

https://github.com/dokan-dev/dokany/commit/5d5c7bf9967ada0189127f49028962ed5852e951
