### ISSUE TITLE
dokan  ver 1.2.1 crashed inside DokanMain()

### ISSUE THREAD

**Issue by gfyllos** [dokan-dev/dokany#768]
# Environment
 * Windows version:  Windows 7, SP1 AND Windows 10
 * Processor architecture: 64-bit
 * Dokany version: 1.2.1.100
 * Library type (Dokany/FUSE): dokany

# Description
I've been using dokan ver 0.7.4 for long time. Today I installed the latest dokany version (121) and tried my APP on two systems ( Win7 and Win 10 ) both 64-bit. My app crashes inside DokanMain() on both systems., with message "Access Violation reading location 0xFFFFFFFFFFF". On the Win7, the debugger  says that this location is inside ucrtbase.dll. On Win10, no info at all.

I appreciate any help, thank you, gt

**Comment by Liryna** [comment]
Hi @gfyllos ,

Does it crash instantly ? Could you check that the interface has properly been updated ? (some changes since 0.7.4 it changed)
https://github.com/dokan-dev/dokany/wiki/Update-dokan-legacy-application-to-Dokany

**Comment by Liryna** [comment]
Hi @gfyllos ,

Please let me know if this need to be reopened.
