### ISSUE TITLE
Assertion failed at DokanNet.DokanOperationProxy.GetFileInformationProxy

### ISSUE THREAD

**Issue by nicolas-raoul** [dokan-dev/dokany#77]
I built Dokan.net in Visual Studio, installed Dokan 0.8.0, and double-clicked on `dokan-dotnet\sample\RegistoryFS\bin\Debug\RegistoryFS.exe`

A pop-up appeared saying:

```
Assertion failed
at DokanNet.DokanOperationProxy.GetFileInformationProxy(String rawFileName, BY_HANDLE_FILE_INFORMATION& rawHandleFileInformation, DokanFileInfo rawFileInfo) in C:\Users\win7pro32bit\Documents\dokan-dotnet\DokanNet\DokanOperationProxy.cs:line 385
Abort   Retry   Ignore   
```

Did I do something wrong? I have not found any documentation or code comments related to the samples.

**Comment by Liryna** [comment]
Could you run the mirror first https://github.com/dokan-dev/dokany/wiki/Use%20Mirror%20exemple
Just to see if it come from DokanNet or not.

**Comment by nicolas-raoul** [comment]
Mirror works great :-)

**Comment by Liryna** [comment]
Can you test the mirror in dokannet ?
I have to say that I didnt run RegistoryFS since 0.8.0 :(

**Comment by nicolas-raoul** [comment]
I double-clicked on `dokan-dotnet\sample\DokanNetMirror\bin\Debug\DokanNetMirror.exe` and it works perfectly, a `N:` drive appears which shows the same content as my `C:` drive.

**Comment by Liryna** [comment]
Ok, you are unable to debug RegistoryFS  and have some information about the error ?

**Comment by Liryna** [comment]
Or can you rebuild RegistoryFS and replace NtStatus.Error by NtStatus.AccessDenied ?

**Comment by nicolas-raoul** [comment]
I just discovered Dokan, so I am very new, but I will try :-)

**Comment by Liryna** [comment]
Fixed with https://github.com/dokan-dev/dokan-dotnet/commit/463bf08dc4ebf396854b8cdbf2a4d4de4ee85e19

**Comment by nicolas-raoul** [comment]
Thanks for the quick fix! It works now.
