### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by DatJulian** [dokan-dev/dokany#770]
[This](https://github.com/dokan-dev/dokany/blob/5d5c7bf9967ada0189127f49028962ed5852e951/dokan/dokan.h#L671) documentation line is probably wrong.
The function gets called no matter whether DOKAN_OPTION_ALT_STREAM is set.
I did not follow the issue blueprint because everything of it is irrelevant.

**Comment by Liryna** [comment]
Hi @DatJulian ,

You are right, only CreateFile was protecting alt stream calls.
Fixed with https://github.com/dokan-dev/dokany/commit/2442bb0a663cd52c5c8b0d975b16598bc695280e

Thank you for the report 🏆 very appreciated !
