### ISSUE TITLE
New FileDispositionInformationEx for  Windows 10, version 1709.

### ISSUE THREAD

**Issue by alexander-ossur** [dokan-dev/dokany#777]
# Environment
 * Windows version: Windows 10
 * Processor architecture: x64 and x86
 * Dokany version: 1.2.0 and 1.2.1
 * Library type (Dokany/FUSE): Dokany

# Description
Dokany driver fails to handle ::SetFileInformationByHandle WinAPI on Windows 10. This is not #349 but very close to it. Please see the code below.

To reproduce:
1. Run Mirror and mount to some location:
mirror /r "C:\Downloads\Temp" /l M:

2. Create a test, or a standalone application with a code:
```
#include "gtest/gtest.h"

TEST (TestIcService, Test__) {
	std::filesystem::path directory__ = L"M:\\test directory";
	std::error_code error__;

	// Create directory
	std::filesystem::create_directory (directory__, error__);

	// Remove directory
	std::filesystem::remove (directory__, error__);
}
```
3. Compile with "Windows SDK Version 10" and a platform toolset "Visual Studio 2017 (v141)"

The code will fail in Windows 10 at "std::filesystem::remove", but will work in Windows 8.1
Closer look leads to internals of "std::filesystem::remove" and points to "SetFileInformationByHandle" API. 
In this test "SetFileInformationByHandle" returns ERROR_INVALID_FUNCTION. In our other (non Mirror and more complex) tests may return ERROR_FILE_NOT_FOUND, while directory is present and opened successfully.

Please keep in mind. In this test _STL_WIN32_WINNT is not set hence application links to "SetFileInformationByHandle" dynamically. You may see that part in the "filesystem.cpp".

**Comment by Liryna** [comment]
Hi @alexander-ossur ,

Could you provide the mirror log when `std::filesystem::remove (directory__, error__);` is called ?

**Comment by alexander-ossur** [comment]
Hello @Liryna 

Sure, here it is:

# Starting a Mirror application:
> mirror /r "C:\Downloads\Temp" /l M: /s
> AllocationUnitSize: 512 SectorSize: 512
> device opened
> ###QueryVolumeInfo -001
> mounted: M: -> \Volume{d6cc17c5-1775-4085-bce7-964f1e9f5de9}
> ###Create 0000
> CreateFile status = c0000034
> ###Create 0001
> CreateFile status = c0000034
> ###Create 0002
> CreateFile status = c0000034
> ###Create 0003
> CreateFile status = 0
> ###GetFileInfo 0003
>         result =  0
>   unknown type:54
>         DispatchQueryInformation result =  c000000d
> ###GetFileInfo 0003
>         result =  0
>         FileStandardInformation
>         DispatchQueryInformation result =  0
> ###GetFileInfo 0003
>         result =  0
>         FileBasicInformation
>         DispatchQueryInformation result =  0
> ###Cleanup 0003
> ###Close 0003
> ###Create 0004
> CreateFile status = c0000034

# Calling std::filesystem::create_directory
> ###Create 0005
> CreateFile status = 0
> ###GetFileInfo 0005
>         result =  0
>         FileStandardInformation
>         DispatchQueryInformation result =  0
> ###GetFileInfo 0005
>         result =  0
>         FileNetworkOpenInformation
>         DispatchQueryInformation result =  0
> ###Cleanup 0005
> ###Create 0006
> CreateFile status = 0
> ###Close 0005
> ###GetFileInfo 0006
>         result =  0
>         FileStandardInformation
>         DispatchQueryInformation result =  0
> ###QueryVolumeInfo 0006
> ###Cleanup 0006
> ###Close 0006
> ###Create 0007
> CreateFile status = c0000035

# Calling std::filesystem::remove
> ###Create 0008
> CreateFile status = 0
> ###GetFileInfo 0008
>         result =  0
>         FileStandardInformation
>         DispatchQueryInformation result =  0
> ###GetFileInfo 0008
>         result =  0
>         FileBasicInformation
>         DispatchQueryInformation result =  0
> ###SetFileInfo 0008  64
>   unknown FileInformationClass 64
>         DispatchSetInformation result =  c0000002
> ###Cleanup 0008
> ###Close 0008
> ###Create 0009
> CreateFile status = 0
> ###GetFileInfo 0009
>         result =  0
>         FileStandardInformation
>         DispatchQueryInformation result =  0
> ###QueryVolumeInfo 0009
> ###Cleanup 0009
> ###QueryVolumeInfo -001
> ###Close 0009

PS. std::filesystem::remove makes three WinAPI calls: CreateFile, SetFileInformationByHandle and CloseHandle

**Comment by alexander-ossur** [comment]
Just in case (tldr) I will put here internal function for std::filesystem::remove:

```
[[nodiscard]] __std_fs_remove_result __stdcall __std_fs_remove(const wchar_t * const _Target) noexcept
	{	// remove _Target without caring whether _Target is a file or directory
	__std_win_error _Last_error;
#if _STL_ALWAYS_HAS_SetFileInformationByHandle
 #define _SetFileInformationByHandle SetFileInformationByHandle
#else /* ^^^ _STL_ALWAYS_HAS_SetFileInformationByHandle ^^^ // vvv !_STL_ALWAYS_HAS_SetFileInformationByHandle vvv */
	const auto _SetFileInformationByHandle = __vcrt_SetFileInformationByHandle;
	if (_SetFileInformationByHandle == _Not_supported_SetFileInformationByHandle)
		{	// Windows XP
		if (RemoveDirectoryW(_Target))
			{	// try RemoveDirectoryW first because it gives a specific error code for "the input was a file";
				// DeleteFileW on a directory input returns ERROR_ACCESS_DENIED
			return {true, __std_win_error::_Success};
			}

		_Last_error = __std_win_error{GetLastError()};
		if (_Last_error == __std_win_error::_Directory_name_is_invalid)
			{	// input may have been a file
			if (DeleteFileW(_Target))
				{
				return {true, __std_win_error::_Success};
				}

			_Last_error = __std_win_error{GetLastError()};
			}

		return {false, _Translate_not_found_to_success(__std_win_error{GetLastError()})};
		}
#endif /* _STL_ALWAYS_HAS_SetFileInformationByHandle */

	constexpr auto _Flags = __std_fs_file_flags::_Backup_semantics | __std_fs_file_flags::_Open_reparse_point;
	const _STD _Fs_file _Handle(_Target, __std_access_rights::_Delete, _Flags, &_Last_error);
	if (_Last_error != __std_win_error::_Success)
		{
		return {false, _Translate_not_found_to_success(_Last_error)};
		}

	// From newer Windows SDK than currently used to build vctools:
	// #define FILE_DISPOSITION_FLAG_DELETE                     0x00000001
	// #define FILE_DISPOSITION_FLAG_POSIX_SEMANTICS            0x00000002

	// typedef struct _FILE_DISPOSITION_INFO_EX {
	//     DWORD Flags;
	// } FILE_DISPOSITION_INFO_EX, *PFILE_DISPOSITION_INFO_EX;

	struct _File_disposition_info_ex {
		DWORD _Flags;
	};
	_File_disposition_info_ex _Info_ex{0x3};

	// FileDispositionInfoEx isn't documented in MSDN at the time of this writing, but is present
	// in minwinbase.h as of at least 10.0.16299.0
	constexpr auto _FileDispositionInfoExClass = static_cast<FILE_INFO_BY_HANDLE_CLASS>(21);
	if (_SetFileInformationByHandle(_Handle._Get(), _FileDispositionInfoExClass, &_Info_ex, sizeof(_Info_ex)))
		{
		return {true, __std_win_error::_Success};
		}

	_Last_error = __std_win_error{GetLastError()};
	if (_Last_error != __std_win_error::_Invalid_parameter)
		{
		return {false, _Last_error};
		}

	// Filesystem without POSIX delete support, or older than Windows 10 RS1 version without such support:
	FILE_DISPOSITION_INFO _Info{/* .Delete= */TRUE};
	if (_SetFileInformationByHandle(_Handle._Get(), FileDispositionInfo, &_Info, sizeof(_Info)))
		{
		return {true, __std_win_error::_Success};
		}

	return {false, __std_win_error{GetLastError()}};

#undef _SetFileInformationByHandle
	}
```

Most interesting (failing) part is:
```
	struct _File_disposition_info_ex {
		DWORD _Flags;
	};
	_File_disposition_info_ex _Info_ex{0x3};

	// FileDispositionInfoEx isn't documented in MSDN at the time of this writing, but is present
	// in minwinbase.h as of at least 10.0.16299.0
	constexpr auto _FileDispositionInfoExClass = static_cast<FILE_INFO_BY_HANDLE_CLASS>(21);
	if (_SetFileInformationByHandle(_Handle._Get(), _FileDispositionInfoExClass, &_Info_ex, sizeof(_Info_ex)))
		{
		return {true, __std_win_error::_Success};
		}

	_Last_error = __std_win_error{GetLastError()};
	if (_Last_error != __std_win_error::_Invalid_parameter)
		{
		return {false, _Last_error};
		}
```

Where "_SetFileInformationByHandle" is: SetFileInformationByHandle API

**Comment by Liryna** [comment]
Hi @alexander-ossur ,

64 is for the new `FileDispositionInformationEx` This value is available starting with Windows 10, version 1709.
https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/ns-ntddk-_file_disposition_information_ex

I will look to add it.
Thank you for the report !

**Comment by Liryna** [comment]
Hi @alexander-ossur ,

I just added `FileDispositionInformationEx`. Can you just rebuild the dokan library on your side. Replace it with yours and make a test ?
https://github.com/dokan-dev/dokany/commit/1dfa9e43a4ac1c19c9202cd67750f8c627ff63ff

I am not fully sure of how it has to work. MSDN is not fully clear. I check `FILE_DISPOSITION_DELETE` and should work with your library (flags 0x3). I just still wonder how `FILE_DISPOSITION_ON_CLOSE` has to be used.

**Comment by alexander-ossur** [comment]
Hi @Liryna 

Sorry I created a message and then deleted it in order to make a deeper look

Now it calls `NTSTATUS(DOKAN_CALLBACK *DeleteDirectory)(LPCWSTR FileName,
    PDOKAN_FILE_INFO DokanFileInfo);` and internally sets `DeleteOnClose`

But it does not forward `DeleteOnClose` to `void(DOKAN_CALLBACK *Cleanup)(LPCWSTR FileName,
                                PDOKAN_FILE_INFO DokanFileInfo);`

**Comment by Liryna** [comment]
Thank you for the feedback @alexander-ossur 
Just fixed this part 👍 https://github.com/dokan-dev/dokany/commit/d318f82fc232f04595505582c93c33d97acc4ae9
Tested on my side and works great.

**Comment by alexander-ossur** [comment]
Thank you @Liryna 

I tested the d318f82 and getting the same issue: `DeleteOnClose` is not set. A quick question: should I compile and install system driver too?

Unfortunately I can not run Mirror on d318f82. It exists with 
> AllocationUnitSize: 512 SectorSize: 512
> device opened
> ###QueryVolumeInfo -001
> ###Create 0000
> CreateFile status = c000003a
> Failed to open keepalive file: \\?\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}\__drive_fs_keepalive
> Failed to activate keepalive handle.

**Comment by Liryna** [comment]
@alexander-ossur yes the fix is also in the driver code
https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#dokan-driver
or instead of building you can use the snapshot 
https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot

**Comment by alexander-ossur** [comment]
Thank you @Liryna 

I can confirm all tests are passing now. I did not run these on Win 8.1, but will come back if related issue is still there.

Thank you again ;)
