### ISSUE TITLE
Mirror.exe wont stay running

### ISSUE THREAD

**Issue by jjacobsfs** [dokan-dev/dokany#779]
Environment
 * Windows version:  Windows 10 Pro, v10.0.17763
 * Processor architecture: x64
 * Dokany version: 1.2.1.2000
 * Library type (Dokany/FUSE): Dokany
  * Dokany command:  "C:\Dokan 1.2.1.2000\mirror.exe" /r \\nas\projects /l p

Description
Using the command above, mirror.exe will only stay running for about 5 seconds and then it shuts down.  I am not sure if this is a bug or not.  Maybe its just user error but I didn't see a forum for dokany anywhere to post this.  Thanks and I appreciate the help.

**Comment by Liryna** [comment]
Hi @jjacobsfs ,

Could you provide the debug logs of the mirror ? https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#mirrorfs

**Comment by jjacobsfs** [comment]
Hello.  See attached.  Thanks.

**Comment by Liryna** [comment]
Thank you @jjacobsfs logs seems to be truncated, possible that the app is killed ?

**Comment by jjacobsfs** [comment]
Hello.  I see what you're saying but that is all I am getting in the command prompt.  Any ideas?

Thanks

**Comment by Liryna** [comment]
@jjacobsfs Any anti-virus or third part that could do this?

**Comment by jjacobsfs** [comment]
I shut off antivirus and any other third party apps.

I have a mapped network drive for that same network share.  Would that cause issues?  As a test, I created a new network share that was not mapped and mirror.exe ran longer than before (but it was still eventually killed).

I will keep troubleshooting and see what I can come up with.

**Comment by marinkobabic** [comment]
Please try to map the windows drive and to use mapped drive as source for
the mirror

**Comment by jjacobsfs** [comment]
I tried mapping the mapped drive.  It works longer but then ends up crashing Windows.  I haven't seen it do it but every time I leave mirror running and come back after several hours, Windows has restarted.

**Comment by Liryna** [comment]
@jjacobsfs we will need more informations to reproduce this or logs to see what is happening

**Comment by marinkobabic** [comment]
Almost in all cases this is related to keep alive but logs are needed.

**Comment by taruti** [comment]
I think some of our users are also stumbling upon something similar, don't have anything enough info yet.

**Comment by jjacobsfs** [comment]
Sorry, haven't had the time to get logs yet.  I rarely use Dokan now and only use it if I want my backup software to sync changes on my NAS because everytime it crashes windows.  I will try to get logs soon.

**Comment by TrabacchinLuigi** [comment]
Got this very problem, just with our implementation, our filesystems where being unmounted out of our control, so i've tried 3 things: 

1. `TryResetTimeout` that did not help much, i've added it where i knew there was some long requests.
2. Rolling back to previous version seemed to help, but i very liked the GC pressure reduction.
3. Also the fix suggested in #776 seems to help. but i have to run the driver with test signature.

**Comment by TrabacchinLuigi** [comment]
Got another feedback today, old version still get unmounted (on slower machines) when we got very long calls, so i'm investigating where to put more `TryResetTimeout` i'll provide feedback after more testing

**Comment by TrabacchinLuigi** [comment]
Ok: So i've filled our code with `TryResetTimeout` (where network requests where made) with no results.
Eliminated the slow-factor (ran it just locally, so no long requests where made) and still no results.
I think i'll install debug version of dokan and try to enable the logs.

**Comment by TrabacchinLuigi** [comment]
[DBG-KERNEL.LOG](https://github.com/dokan-dev/dokany/files/2920225/DBG-KERNEL.LOG)
here we go: from mount to the end

**Comment by TrabacchinLuigi** [comment]
```
 => NotificationLoop	
00071922	46.30887604	[DokanFS] Try acquire SpinLock...	
00071923	46.30887604	[DokanFS] SpinLock irp Acquired	
00071924	46.30887985	[DokanFS] SpinLock notify Acquired	
00071925	46.30887985	[DokanFS] Clear Events...	
00071926	46.30887985	[DokanFS] Notify event cleared	
00071927	46.30888367	[DokanFS] Pending event cleared	
00071928	46.30888367	[DokanFS] Release SpinLock...	
00071929	46.30888748	[DokanFS] SpinLock notify Released	
00071930	46.30888748	[DokanFS] SpinLock irp Released	
00071931	46.30889130	[DokanFS] <= NotificationLoop	
00071932	50.00617599	[DokanFS] ==> ReleaseTimeoutPendingIRP	
00071933	50.00617981	[DokanFS]   IrpQueue is Empty	
00071934	50.00618362	[DokanFS]   Timeout reached so perform an umount	
00071935	50.00618362	[DokanFS] ==> DokanUnmount	
00071936	50.00618744	[DokanFS]   Send Unmount to Service : \Volume{d6cc17c5-1736-4085-bce7-964f1e9f5de9}	
00071937	50.00625610	[DokanFS] => NotificationLoop	
00071938	50.00625992	[DokanFS] Try acquire SpinLock...	
```

i've set up a 20seconds timeout mounting this FS and i call  `TryResetTimeout` before any long operation with a value bigger than the operation timeout (and probably i didn't need it because the file i was reading is local...

**Comment by TrabacchinLuigi** [comment]
i also have a log from our implementation showing each call duration 
![image](https://user-images.githubusercontent.com/136717/53657840-961fd280-3c57-11e9-908e-59af88b95fb6.png) and i can see none went slow... but the drive got unmounted anyway

**Comment by TrabacchinLuigi** [comment]
P.S. those test where all made with 1.1.0.1000 (setup 1.1.0.2000)

**Comment by TrabacchinLuigi** [comment]
Built the driver with changes from #776 and installed in the same test machine, got a movie playing for 24Minutes and still no unmount (wasn't lasting a couple of minutes before)

**Comment by Liryna** [comment]
Will continue here #779
