### ISSUE TITLE
DisplayName key in Dokan 0.8.0 Uninstall data in the registry doesn't update consistenly

### ISSUE THREAD

**Issue by zik319** [dokan-dev/dokany#78]
Hi,
I've started testing out the new version no major issues so, great work! :)

One small issue, I've installed the new version after removing version 0.7.4 and it seems that it updated the the registry only part of the the times.
I'm talking about the DisplayName key in HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\DokanLibrary
After successfully installing 0.8.0 it still shows 0.7.4 
All of my test were done on Win7 SP1 64bit machines

**Comment by Liryna** [comment]
I will try to update the version of my NSIS but I don't think we can do much about it :(

**Comment by Liryna** [comment]
I made a test and worked properly.
Next release will fix it :)

**Comment by zik319** [comment]
Just out of curiosity what was the problem?
I took a a look at the NSI and it seems correct.

**Comment by Liryna** [comment]
Yes it seems but during DeleteRegKey HKLM, I think NSIS was targeting the wrong HKLM folder (probably the x86).
I am pretty sure this issue does not happen in 32bit.
