### ISSUE TITLE
Portable version without explicit installation

### ISSUE THREAD

**Issue by eocron** [dokan-dev/dokany#781]
Hello, is it possible in future releases to make driver to setup/setdown it's environment from code alone and not from installers/uninstallers?

It is useful, when you don't need any installation routine and just want to put everything in single .exe file or project which will determine lifetime of driver in Windows itself. Running installation on every client is frustrating and sometimes not viable solution.... #

**Comment by Liryna** [comment]
@eocron Hi,

There is alright à zip file with all the binaries for every architecture. Is this not what you are looking for?
