### ISSUE TITLE
Upgrading from 1.0.1.1000 to 1.2.1.2000

### ISSUE THREAD

**Issue by andreas-eriksson** [dokan-dev/dokany#782]
I recently upgraded my dokany version and have been having some problems since then. I created a filesystem in .NET by starting from the mirror example for dokan-dotnet. I have added the maximumComponentLength parameter to the GetVolumeInformation method. My filesystem is not very complex and only allows read access.

I now sometimes have problems with the filesystem being unmounted before I quit my program. This results in me not being able to find/read the files anymore. I would suspect that this is some sort of timeout that causes the unmount. It seems to happen very sporadically and does not always occur. I have debugged my code and there are no exceptions of any kind. I don't really know where to start my investigation and would be helpful if someone can point me in a general direction. Are there any more breaking changes between the two versions?

**Comment by Liryna** [comment]
@andreas-eriksson Hi,

Could you give the full debug logs of the app and specially when it stops?

**Comment by andreas-eriksson** [comment]
My app mounts several folders and one of them was somehow unmounted at 2019-02-27 08:57:48.445. The log is then silent for almost a minute even though I know that file read attempts was made.

https://www.dropbox.com/s/e1nsdx2x58ozovl/LogFile.txt?dl=0

I'm not sure if the log will actually tell you anything useful. I have tried using the .net mirror sample to read the same files and that works every time.

**Comment by Liryna** [comment]
Could this be the same to https://github.com/dokan-dev/dokany/issues/779 ?

**Comment by Liryna** [comment]
Will continue here #779
