### ISSUE TITLE
findFilesWithPattern: Strange conversion of input search pattern

### ISSUE THREAD

**Issue by infeo** [dokan-dev/dokany#783]
# Environment
 * Windows version: Windows 10 Pro 1809
 * Processor architecture: x64
 * Dokany version: 1.2.1.1000
 * Library type (Dokany/FUSE): Dokany 
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Maybe i miss something here, but the search string given as a parameter into the findFilesWithPattern() function does not match every time the actual search pattern. 

I implemented a stub for the findFilesWithPattern function with some debug output which always returns `STATUS_NOT_IMPLEMENTED`:
 ``` C
static NTSTATUS DOKAN_CALLBACK
MirrorFindFilesWithPattern(LPCWSTR FileName,
				LPCWSTR SearchPattern,
                                PFillFindData FillFindData,
                                PDOKAN_FILE_INFO DokanFileInfo) {
  WCHAR filePath[DOKAN_MAX_PATH];
  GetFilePath(filePath, DOKAN_MAX_PATH, FileName);
  DbgPrint(L"FindFilesWithPattern : %s\n", filePath);
  DbgPrint(L"\tFindFilesWithPattern : search pattern is %s\n\n", SearchPattern);

  return STATUS_NOT_IMPLEMENTED;
}
```

And added it to the dokan operations struct:
``` C
//...
dokanOperations->FindFiles = MirrorFindFiles;
dokanOperations->FindFilesWithPattern = MirrorFindFilesWithPattern;
dokanOperations->SetFileAttributes = MirrorSetFileAttributes;
//...
```

After building the mirror exemple and mounting a directory, I open a terminal, change the directory to the mount point and enter `dir test.*`.

The expected input search string of findFilesWithPattern would be `test.*`
The actual one is `test"*`

# Logs
The log shows the following:
```
###FindFiles 0014

FindFilesWithPattern : Y:\test\

	FindFilesWithPattern : search pattern is test"*
```

**Comment by Rondom** [comment]
This is how Windows works to keep compatibility with MS-DOS-style globbing. The dot `.` from the Windows-API is replaced with a quote `"` to signify a dot with "MS-DOS-meaning" inside the kernel. 

See the comment here, which should explain things a bit: https://github.com/dokan-dev/dokany/blob/94e8162163f3b79283d02b725c3030a3e78c53f1/dokan/directory.c#L630-L649
See also the explanation by MS: https://msdn.microsoft.com/en-us/library/ff546850(v=VS.85).aspx

There seems to be room for improvement in the documentation. Both [DOKAN_OPERATIONS.FindFilesWithPattern](https://dokan-dev.github.io/dokany-doc/html/struct_d_o_k_a_n___o_p_e_r_a_t_i_o_n_s.html#a0f280feb3cbff134e997bec6d6db5171) and [DokanIsNameInExpression](https://dokan-dev.github.io/dokany-doc/html/group___dokan.html#ga2e8585b8730ee74c0cd0cadf3e8cb01a) should explain this properly using a Doxygen-comment in the header-file. The comment from the code mentioned above can serve as inspiration for that.

**Comment by infeo** [comment]
Thanks for the detailed explanation and pointing to the corresponing code. 
I corrected the topic of the issue accordingly to be a property of windows rather than a bug.

**Comment by Rondom** [comment]
Yes, we should keep this issue open to track updating the documentation.

**Comment by Liryna** [comment]
I agree this part had to be better explained. Following @Rondom guidance 👍 does this https://github.com/dokan-dev/dokany/commit/fef36fea2f5bee126d269aaa8df29e89a57282d7 would be enough ?

**Comment by infeo** [comment]
I think for a developer it is more important what are the final input for the search expression parameter. The description leaves this quite open:
1. `.` is replaced by `"`, if it is succeeded by `?` or `*` in the search string: `test.*` ↦ `test"*`
2. `*` is replaced by `<`, if it is succeed by `.` in the search string: `t*.txt` ↦ `t<.txt`
3. `?` is always replaced by `>`: `t?st.txt` ↦ `t>st.txt`

**Comment by Liryna** [comment]
I can understand your points. I just not fully sure that the place to details how DOS expressions are working. There are a lot of documents online that fully explain and give examples about this subject.
If we make enough clear the type of expression used here, it would normally be enough for the devs find the proper information. Do you agree ?

**Comment by Rondom** [comment]
You mean how Windows translates a search pattern from the Win32-API into a kernel-search pattern? What do you do with that information? You will have to deal with the search pattern that the kernel/Dokan provides you. Isn't it enough to know how to interpret each character in the search pattern in this case? What value do you see in knowing about the translation from Win32 to kernel? Do you intend to translate the kernel-pattern back to a Win32-userspace-pattern?

Without knowing the source code of Windows I would guess that ´*´ and ´?´ get forwarded straight to the kernel when using WSL or the older Unix subsystem Interix/SFU/SUA. When one uses the Win32-Subsystem, the `*`, `?` and `.` get replaced according to some rules, like you describe in your comment.

**Comment by infeo** [comment]
I do see, that my suggestion is actually unrelated to dokany and more to the conversion of the win32 subsystem to the windows kernel. The above documentation should be sufficient then and for the rest one must do some research, because that's just how windows works.

@Rondom My background is being a deveolper using the [Java-Wrapper for Dokany](https://github.com/dokan-dev/dokan-java). When you implement now the findFilesWithPattern function and use the windows kernel search pattern directly in the java API, it does not yield the correct result. Thus i have to convert the pattern into a valid java one and therefore i need to know the conversions rules.

Regardless, glad that you answerd so fast and the issue is resolved now!

**Comment by Rondom** [comment]
But Java uses yet another pattern-language for globbing. See my other comment in the other bug here: https://github.com/cryptomator/dokany-nio-adapter/issues/19#issuecomment-470128252

I first thought that we could indeed create a function to map between Win32-glob-pattern and Windows-Kernel-glob-patterns, similarly to how we do for [`CreateFile`-Flags](https://dokan-dev.github.io/dokany-doc/html/group___dokan.html#ga58cc5a921a84f54042f2ac04b27bbc75) or [`NTSTATUS`](https://dokan-dev.github.io/dokany-doc/html/group___dokan.html#ga1bcba8145ee5205cd41fa5eebdffaa82).

Then I read that [those kernel-globbing patterns should work from Win32 as well](https://blogs.msdn.microsoft.com/jeremykuhne/2017/06/04/wildcards-in-windows/). Thus, such a function is not necessary.
