### ISSUE TITLE
Bundle Dokany with an installer

### ISSUE THREAD

**Issue by akkishore** [dokan-dev/dokany#786]
How to bundle Dokany with an installer (created using InstallForge). Can I run DokanySetup.exe silently without any UI? Can it exit if there's same major installation already installed? Whats the need for DokanSetup_redist.exe? Should it also be distributed?

**Comment by Liryna** [comment]
@akkishore Hi,

I never used installforge, but I will guess they have support to package msi dependency.

You should find answer of you other questions in the github wiki.
Do not hesizif you have further questions.

**Comment by Liryna** [comment]
@akkishore Please see https://github.com/dokan-dev/dokany/wiki/How-to-package-your-application-with-Dokan
