### ISSUE TITLE
A certificate was explicitly revoked by its issuer

### ISSUE THREAD

**Issue by barcelona-messi** [dokan-dev/dokany#789]
Driver is EV signed and Microsoft signature certified，wrong when run "sc start dokan1" on some computers, err:A certificate was explicitly revoked by its issuer,The signature looks normal, why?

**Comment by Liryna** [comment]
Hi @barcelona-messi ,

Could you provide more information on this ? Did not face that.

**Comment by barcelona-messi** [comment]
> Hi @barcelona-messi ,
> 
> Could you provide more information on this ? Did not face that.

hi, I compiled dokan myself, I have EV driver signature on the driver file，Then submit the driver signature on the Windows Hardware Developer Center portal，Wrong when using the driver，error:“A certificate was explicitly revoked by its issuer"

**Comment by Liryna** [comment]
Oh, so this is not related to dokan signature.
You will probably need to look at your cert issuers for this or the chain certificate on your computer.
