### ISSUE TITLE
 Dokan Microsoft Signature question

### ISSUE THREAD

**Issue by barcelona-messi** [dokan-dev/dokany#790]
I would like to submit the Microsoft driver signature at which URL after compiling dokan myself?

**Comment by Liryna** [comment]
Hi @barcelona-messi ,

You will need to publish to the developer hardware dashboard https://developer.microsoft.com/en-us/windows/hardware
https://github.com/dokan-dev/dokany/blob/master/dokan_wix/build.bat#L29

**Comment by barcelona-messi** [comment]
> Hi @barcelona-messi ,
> 
> You will need to publish to the developer hardware dashboard https://developer.microsoft.com/en-us/windows/hardware
> https://github.com/dokan-dev/dokany/blob/master/dokan_wix/build.bat#L29

After I submitted the Microsoft signature：
![image](https://user-images.githubusercontent.com/16136063/54682618-63784400-4b4a-11e9-804b-1f5fd60de89e.png)



Original dokan：
![image](https://user-images.githubusercontent.com/16136063/54682635-7428ba00-4b4a-11e9-808c-1fb9b23ddca7.png)


Can you help me answer it?

**Comment by Liryna** [comment]
You are probably enabling wrong signature options on the portal.

**Comment by barcelona-messi** [comment]
Original dokan：
![image](https://user-images.githubusercontent.com/16136063/54684546-94a74300-4b4f-11e9-8583-502b90db9934.png)

Why are there 3 certificates?

**Comment by Liryna** [comment]
@barcelona-messi That's ISLOG company certificats

**Comment by barcelona-messi** [comment]
I mean, is it necessary to have 3 signatures?Can I only sign SHA1?

**Comment by Liryna** [comment]
@barcelona-messi Microsoft documentation explain well the process of signature for drivers.
