### ISSUE TITLE
Cannot open pdf file when AppContainer is enabled in Acrobat Reader 2019

### ISSUE THREAD

**Issue by killing** [dokan-dev/dokany#794]
# Environment
 * Windows version: Windows 10 Pro
 * Processor architecture: x64
 * Dokany version: 1.2.1.2000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [ x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ x] I can always reproduce the issue with the provided description below.
  - [ ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

With the latest version of Acrobat Reader 2019, if "Run in AppContainer" is enabled in the security options of Acrobat Reader, accessing a pdf file in a Dokany virtual drive will report "permission denied" error. The error can be reproduced with the Mirror sample. I think there is some incompatibility between Dokany and Windows' AppContainer mechanism.

# Logs

**Comment by Liryna** [comment]
@killing Hi!

Have you tried to use the mount manager option of the mirror?

**Comment by killing** [comment]
Hi @Liryna 

Thanks for fast response. We've tried that. But with no luck.

**Comment by Liryna** [comment]
Hi @killing ,

Could you provide the mirros logs ? Maybe there is something about the permission denied.

**Comment by Liryna** [comment]
Hi @killing ,

I tried to reproduce the issue on installing Adobe Reader 2019, enabled "Run in Appcontainer", restart the app, opened some pdf sample in the mirror but I could not get an error.

Have you tried different pdf ? In a clean env ?

**Comment by Liryna** [comment]
Hi @killing ,

Could it be the same as https://github.com/dokan-dev/dokany/issues/640 ?

**Comment by killing** [comment]
Hi @Liryna ,

I think the problem is similar. We can reproduce the issue with any PDF files we tested. We'll provide the mirror logs for debugging.

**Comment by Liryna** [comment]
Thank you for your input @killing 
Can we continue the conversation there ? https://github.com/dokan-dev/dokany/issues/640#issuecomment-491601155 I need some help to face the issue 😄
