### ISSUE TITLE
Dokany should call Cleanup and Closefile also after a timeout

### ISSUE THREAD

**Issue by TrabacchinLuigi** [dokan-dev/dokany#796]
When a timeout happen for whatever reason the managed side of the driver (dokan.net implementations) have no way to know the context need to be disposed, the garbage collector isn't reliable and won't call dispose or finalize on objects if the memory is not needed and could lead to file streams kept open, a way to know that dokany "gave up" on those contexts would be very useful

**Comment by Liryna** [comment]
Hi @TrabacchinLuigi ,

If the implementation has produced a timeout, how can it be trusted to release his resources ?
The userland process could still keep a ref on each context and release them himself after the device was unmount during his timeout failure.

**Comment by TrabacchinLuigi** [comment]
Hi @Liryna ,
I understand the question, but even if the userland can't be trusted to complete the operation it is also not sure it won't succed, maybe a specialized call that don't get awaited could be used.
I've a couple of cases when this could happen: for instance if i attach with the debugger and pause the execution (i know this isn't a very strong usercase) or when a process that use the disk get killed i end up with some zombie context and in some cases those context could have a stream open in them...
About keeping a reference and dispose them from the userland we already do that, but the disk don't get unmounted when this happen... or i'm missing something... I'll provide feedback as soon as i make sure about this...
Another "solution" could be a way to query dokany if a context is still in use, but i would prefer the other way around

**Comment by Liryna** [comment]
@TrabacchinLuigi An app killed with open context on the device will still be cleanup by windows kernel (this is exactly how the new keepalive is working).

**Comment by TrabacchinLuigi** [comment]
opz i'm not using the last version... this was happening in old code, maybe we can pause this topic till i upgrade ... won't take long

**Comment by TrabacchinLuigi** [comment]
I've managed to get rid of old contexts without the need of any modifications of dokany nor upgrading to last version (that i intend to do anyway).  
we can close this.
