### ISSUE TITLE
use fixed volume guid

### ISSUE THREAD

**Issue by Mava23** [dokan-dev/dokany#799]
Feature request:

I want to set the volumen guid (\\?\Volume{GUID}\) at mount time.

Is that possible?

Thanks.

**Comment by Liryna** [comment]
Hi @Mava23 ,

No, this is currently not possible.

**Comment by Mava23** [comment]
https://github.com/dokan-dev/dokany/issues/579

Perhaps remove cleanup? And than reuse guid, like in this bug?
