### ISSUE TITLE
BSOD with 0.7.4 dokan-java, PDB available?

### ISSUE THREAD

**Issue by blschatz** [dokan-dev/dokany#80]
I am working to update the java bindings to 0.7.4 level and x64 and had a BSOD. Are there any PDB's for dokan.sys (x64) available so I can identify where this occurred?

**Comment by Liryna** [comment]
Sorry, I have overridden them :cry:
We should create another installer for the pdb.

**Comment by viciousviper** [comment]
Might I request that you include a pdb package in all future releases? The pdb for 0.8.0-pre is nowhere to be found, either :cry:

**Comment by Liryna** [comment]
Yes, that why I propose to create another NSIS installer :D
If someone could do it, it would help me !

**Comment by Liryna** [comment]
Done withhttps://github.com/dokan-dev/dokany/commit/fc600988ae7b2945cdcfb032a299804058dee671
The next pre-release:
https://github.com/dokan-dev/dokany/releases/tag/v0.8.0-RC1

Does this fit the request ?

**Comment by viciousviper** [comment]
Didn't check the actual files but the installer package content looks good to me.

**Comment by blschatz** [comment]
I ended up building my own, but that will help in the future. Thanks!
