### ISSUE TITLE
Dokany is assuming that a file is opened while it's not

### ISSUE THREAD

**Issue by TrabacchinLuigi** [dokan-dev/dokany#800]
# Environment
 * Windows version: 10 build 1809
 * Processor architecture: x64
 * Dokany version: 1.2.2.1000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I was hunting some bugs in our implementation today and stumbled into something weird: i was not able to open a file stream, but the file was not in use by any process on the machine, yet the driver was answering the file was in use. In the userland i did not see any calls, after checking twice i was really sure it was not our logger problem...

![Can't open the file](https://user-images.githubusercontent.com/136717/58099422-e2860900-7bdb-11e9-895b-f45834bcb66b.png) Can't open the file

![But the userland don't get called](https://user-images.githubusercontent.com/136717/58099477-021d3180-7bdc-11e9-8762-06ec2f756208.png) But the userland don't get called

![Windows Restart Manager](https://user-images.githubusercontent.com/136717/58099720-87084b00-7bdc-11e9-9682-acd17abec419.png)
This small utility use the Windows Restart manager to query which process have an handle on the file, and none are listed

How do i inspect if Dokany have some context still there ?
An API to ask Dokany what it have "opened" would be great

**Comment by Liryna** [comment]
Hi @TrabacchinLuigi ,

This seems to be a shared issue. Kernel driver dokan can return such error without asking the userland fs.
Could you look at the procmon log see all the activity on the file and possible handle open on it ?
Also look at the kernel logs activity.

**Comment by TrabacchinLuigi** [comment]
I did not start with the log enabled :( but i can see the console output and no dokan.net output to be seen.
Process monitor have something interesting 
![procmon](https://user-images.githubusercontent.com/136717/58100995-11ea4500-7bdf-11e9-97da-dedff0252394.png) 
process monitor

**Comment by Liryna** [comment]
Ok, try use process explorer now and see who has an handle on it.

**Comment by TrabacchinLuigi** [comment]
_weirdness intensify_

![process explorer](https://user-images.githubusercontent.com/136717/58101693-60e4aa00-7be0-11e9-9ed2-27d13eed46bf.png)
The folder handle is something we do just to prevent the user from moving the mount path. That is ok.

The weird thing is no handle is open down there, you just get SHARING VIOLATION

**Comment by Liryna** [comment]
So you have a handle open here still in your app by looking at process explorer ?

**Comment by TrabacchinLuigi** [comment]
nope, that only handle is the mount point

**Comment by Liryna** [comment]
Can you reproduce it at will ? Have you tried on a snapshot ?

**Comment by TrabacchinLuigi** [comment]
No we can't reproduce at will, but i have my machine in this state right now, but it happens quite often, we did not try the snapshot, this is happening on released version.

To clarify a bit: HiveDrive.wpf.exe uses dokan.net to mount an FS in C:\HiveDrive\{ProjectName}, then we where using a CAD into one of those folders (revit.exe) suddenly it stopped working, so after inspecting a bit we found out that the reason the cad stopped working was it was getting that sharing violation, and we could not find a reason why since the user implmentation was not called anymore, and no handle seem to be opened...

**Comment by TrabacchinLuigi** [comment]
I'm going to build the driver and debug it in a virtual machine, in the meantime I've tried to enable the debug output without success.
I've followed the instructions in this repo wiki, and also tried to use the new windbg, without any luck, any suggestions ?

**Comment by TrabacchinLuigi** [comment]
I've been running the current snapshot of dokany for almost 4 hours and i have the strong feeling that this is not happening on the new version (it did broke on other machines running the old version), but it is a virtual machine with debug mode enabled, so maybe it is because it is slower or because the log is enabled, or the debug build/mode...
What about the current snapshot gets promoted to a new version of Dokany and we proceed to test it?
I didn't saw any downside with the new version, and it also fixes the BSOD while createfile is hanged...

**Comment by Liryna** [comment]
@TrabacchinLuigi That's a good news thank you for the feedback.
Yes there is a lot of changes around sharing violation since the last release and other improvements. I have the update the changelog by the way.
I planned to make a release of it in the next weeks but since this version break the api, I wanna look again if anything else that also break api can be done.

**Comment by TrabacchinLuigi** [comment]
Breaking API: not a problem just increment the major version :P 
i'm going to read the changelog then, i guess it have something to do with the read-write locks

**Comment by TrabacchinLuigi** [comment]
BTW what do you mean with breaking changes? because i've used a project built with the previous version of dokan.net and seems to work...

**Comment by Liryna** [comment]
Hi @TrabacchinLuigi 

I just update the full changelog https://github.com/dokan-dev/dokany/commit/24e7875f86ec1880e2389c421f521ac84a2fb0c5

My bad, I was meaning ABI so yes we will move to 1.3.x.
`DokanGetMountPointList` prototype has changed to handle larger mount point list. Projects like dokannp using it would need to adapt their code. Dokan-net is even not implementing the function, that's why you are good 😉

**Comment by TrabacchinLuigi** [comment]
i've installed the snapshot version on bunch of machines all working good this never happened with the snapshot version, may be a case, but i guess this could be closed, if it will ever happen again i'll reopen it
