### ISSUE TITLE
Cryptomator / Dokany / Treesize Free

### ISSUE THREAD

**Issue by rorygsales** [dokan-dev/dokany#805]
Feature request - TreeSize Free support

Hi :)

I have test a product out call Cryptomator (v1.4.11) which uses Dokany for its volume types in Windows (not sure about Mac etc).

The product generally works great but I have filed a bug / feature request (not sure which is more accurate) that might to have anything to do with Cryptomator but rather Dokany and WebDAV

[Cryptomator bug / feature request](https://github.com/cryptomator/cryptomator/issues/855)

Basically Treesize free which is a useful Windows program to analyse where your disk usage has gone in multiple folders or disks/drives throws a error. I am assuming this error is due to the way that Dokany presents the "virtual drive". I am making many assumptions here as I have not looked at either of the projects code.

I have not tested a alternative piece of software that uses Dokany. If you would like me to test one please suggest another project that I can install on Windows 10 and find out if this is a common problem.

Many thanks in advance.

Kind Regards
Rory

**Comment by Liryna** [comment]
Hi @rorygsales ,

I just tried with the mirror sample and Treesize could see the device & scan it.
You can try yourself running: `C:\Program Files\Dokan\Dokan Library-1.2.2\sample\mirror>mirror.exe /r C:\Users /l m`
![image](https://user-images.githubusercontent.com/4311419/59561483-29232380-9021-11e9-8e4b-3af67ac2ca1d.png)

Could you show me the device property that cryptomator creates ?

**Comment by rorygsales** [comment]
Hi Liryna,

Your a star.

I have a update from the Cryptomator team. [bug / feature request](https://github.com/cryptomator/cryptomator/issues/855). They spoke about the [CURRENT_SESSION flag](https://github.com/cryptomator/cryptomator/issues/802) - custom mounting flags.

I have test it with my user and not administrator (which treesize on frequent use encourages) and it works.

Thank you for testing and the feedback. I will have to wait for them to add this feature that allows for mounting as the current user and administrator.

Kind Regards
Rory
