### ISSUE TITLE
🏢 Companies 🏢 - 🚀 Dokan needs your support more than ever ! 🚀

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokany#808]
Since Windows 10 version 1607, Kernel drivers need to be signed with an EV Code Signing certificate. Dokan driver do not make exception and is since using the EV Certificate from ISLOG company financed by **Keybase donation**.

The EV certificate had 3 years life time and is going to **expire this August the 27/08/2019**. Without Keybase ❤️ contribution Dokan could not do any release working on the newest Windows 10 & Windows Servers.

An EV Code Signing certificate cost  $664.00 USD / year  ([Digicert](https://www.digicert.com/code-signing/ev-code-signing/)).

Dokan needs support from companies to renew his certificate like Keybase did in the past !

Small information: Dokany will celebrate its 5th anniversary this December 🎂 🎉 

If anyone would like to reach me privatly, you can reach me by mail: liryna.stark@gmail.com

**Comment by jchristn** [comment]
Paypal address?  Count me in.

**Comment by Liryna** [comment]
@jchristn 👍 if you can reach me directly by mail liryna.stark@gmail.com will give you the account

**Comment by Liryna** [comment]
In 2016, DigiCert cert was $224.00 USD / year or $497.00 USD for 3 years.
In 2019, it is $664.00 USD / year...we need 3 years of certificates for the perenity of the project.

**Comment by jchristn** [comment]
How much more do you have to go?

**Comment by Liryna** [comment]
We have reached 645$, we have some promises that should come in the next days. The goal is 664 * 3 = 1992$ I am sure we will reach the amount before the expiration (end of august)

**Comment by jchristn** [comment]
Count me in for $100 in the 2nd half of this month if you don't hit the goal

**Comment by SylwesterZarebski** [comment]
Maybe cheaper certificates could be used?
E.g.: https://www.globalsign.com/en/code-signing-certificate/ev-code-signing-certificates/
Or another from list: https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate

**Comment by SylwesterZarebski** [comment]
PS. Is sponsor links worth using (from % taken point of view)? I did not used them before.

**Comment by Liryna** [comment]
Hi @SylwesterZarebski ,

Yes, there is cheaper ssl certificates. At the start the goal was just to renew your cert and keep going as it is. My mistake here, I knew it would cost but was strongly surprise the price has grown so much for the same product. I had some talk with the companies giving their support. Yes, we can and will take a cheaper EV cert BUT my concern is not on the "EV" part about if I can use it to sign SHA2 for Windows 7 (and cross SHA1 before the update).
For now, we cross sign using a non-EV certificate that I know the root CA is available on all the needed windows without update + EV cert for windows 10. I wanted to use only the new cert for doing all signs.
https://cheapsslsecurity.com/sectigo/sectigo-ev-code-signing-certificate.html <- 
So I contacted Sectigo if their certificate is normally detected for Windows 7. They gave Windows 8 as lower "compatibility". Yes, I guess Digicert would probably the same. Therefore we will still need to do the cross sign.
My thought for now is to buy a cheaper EV cert (~900$) and simple sign cert (~200$).

**Comment by Liryna** [comment]
Hi everyone,

We just received the amount needed to do the order for the EV Certificat !
I keep the issue open to keep people aware of the order state.

**Comment by TonyValenti** [comment]
Get it from digicert a lot cheaper:

https://www.digicert.com/friends/sysdev/

**Comment by Liryna** [comment]
Wow @TonyValenti ! Thank you, will keep it for the next time 😞

**Comment by decare** [comment]
@Liryna

Hi! Thanks for the great software and all your efforts in keeping it up and running!

Can you please update us on the EV certificate order state? The current certificate fom ISLOG will expire tomorrow already and unfortunately some end users of the Dokan software won't be able to install it.

Thanks a lot!

**Comment by Liryna** [comment]
Hi @decare ,

EV Certificate is still in order state. More official validation for the company is in process and taking more time than expected.

Regarding the installer, even if the certificates expire, the installers will perfectly work. The signature is made and will not expire because of the timestamp signature made.

**Comment by knightwolfjk** [comment]
I has been almost a full month, and I'm strongly considering Cryptomator (which uses Dokany or webDAVfor a virtual drive).  Any news?

**Comment by Liryna** [comment]
@knightwolfjk Cryptomator is one of our contributor 😎

We have reach the help needed for the certificat. I should unpin the issue later.
Otherwise the process to get the certificate is almost done... Was no expecting this number of validation :( we should be at the last step before delivery now.

**Comment by knightwolfjk** [comment]
Thank you for the update.  Good luck!

**Comment by Liryna** [comment]
the certificate is being delivered 👍

**Comment by Liryna** [comment]
Dokany is officially good to go for the next 3 years 😎 
Thanks 💝 to all the companies showing their support 👍 without them it wouldn't happen 👏 👏 👏 
The company behind the certificate is ADAPP.
![image](https://user-images.githubusercontent.com/4311419/66428891-34a6ba00-ea17-11e9-88d5-f14d6fc226c1.png)
![image](https://user-images.githubusercontent.com/4311419/66429232-f231ad00-ea17-11e9-8d9d-db94270fd65a.png)
![image](https://user-images.githubusercontent.com/4311419/66428957-56a03c80-ea17-11e9-97da-08234854853c.png)

See you all in december for the 5 years of dokany! 🎅

**Comment by knightwolfjk** [comment]
Congrats and thanks for the update!  

Probably NBD but might want to update the OP ^

**Comment by KerberX** [comment]
@Liryna Hi
Is it possoble to sign Dokany Beta 2 drivers with new signature? I belive that is the reason I can't run them in Windows 10 x64 (1809).

**Comment by Liryna** [comment]
@KerberX Yes, this would be a good idea. Would be also nice to merge the changes on it too. Are you using day to day this version? No crash or improvement to report?

**Comment by KerberX** [comment]
@Liryna 
Yes, I'm using v2.0 for quite a long time and I made a program that uses it (https://github.com/KerberX/Kortex-Mod-Manager). Many poeple are claiming the VFS is pretty stable. Apart this issue (https://github.com/KerberX/KxVirtualFileSystem/issues/3) I can't remember any significant problems with v2.0.

**Comment by Liryna** [comment]
@KerberX New release of the v2 - it uses the new certificates!
https://github.com/dokan-dev/dokany/releases/tag/v2.0.0-BETA2
All the processes and Microsoft EV submission passed without any issue. This pre-release is a good test that all our sign process is working for every type of windows.
