### ISSUE TITLE
CI: FSTest on VS2019 image

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#809]
Two tasks remain:
* fsx and winfstest do not build on the VS2019 image
* HLK 1809 should be used for Windows Server 2019

**Comment by Rondom** [comment]
I can look at the latter of the two bullet points.

**Comment by Rondom** [comment]
Ah, nevermind. I see you already did it.

**Comment by Liryna** [comment]
@Rondom Yes, was interested to reproduce how you did :-D

Hope it will pass :)

**Comment by Rondom** [comment]
> Hope it will pass :)

Golden rule of AppVeyor: It never works on the first try :-D

**Comment by Liryna** [comment]
tools & HLK are now updated for 2019 image 👍
