### ISSUE TITLE
What is holding back the new release?

### ISSUE THREAD

**Issue by TrabacchinLuigi** [dokan-dev/dokany#812]
This is just a question.
Since I'm using successfully the last snapshot for at least one month (maybe more) and tested on many other machines: I was wondering what is holding the new release back? It seem to work slightly better than the released one...

**Comment by Liryna** [comment]
I fully agree 😎 We just moved to VS 2019 at the last moment and had to fix all the CI. All test seems to pass smoothly so we can imagine a release during the month 👍

**Comment by Liryna** [comment]
[v1.3.0.1000 is now released!](https://github.com/dokan-dev/dokany/releases/tag/v1.3.0.1000)
