### ISSUE TITLE
dokansetup.exe install with quiet mode

### ISSUE THREAD

**Issue by MatriQ** [dokan-dev/dokany#813]
# Environment
 * Windows version: win10
 * Processor architecture: x86
 * Dokany version: 1.2.1.2000
 * Library type (Dokany/FUSE): Dokany
 

I integrated dokansetup.exe in my application installer,like this
![image](https://user-images.githubusercontent.com/1320925/60886975-d76b6300-a285-11e9-9bdd-631ca386a340.png)
 
there the installer will show error msg:There is a problem with this Windows Installer package. A program run as part of the set up did not finish as expected.
and I try run "DokanSteup.exe /quiet",every thing is ok.

how to fix it? thanks

**Comment by Liryna** [comment]
Hi @MatriQ ,

You will need to enable msi logs to see exactly.
Otherwise, since you use the package without the VC redistributable, my guess would be that they are missing on the system.

**Comment by MatriQ** [comment]
@Liryna  thank your reminder
I got the error log
```log
20:34:40: _28197B5F_E425_401B_B146_7D198EC702E1. 
MSI (s) (60:70) [20:34:50:311]: Running as a service.
MSI (s) (60:70) [20:34:56:326]: Running as a service.
MSI (s) (60:70) [20:35:02:358]: Running as a service.
CustomAction _28197B5F_E425_401B_B146_7D198EC702E1 returned actual error code 1618 (note this may not be 100% accurate if translation happened inside sandbox)
MSI (s) (60:60) [20:35:02:389]: Note: 1: 1722 2: _28197B5F_E425_401B_B146_7D198EC702E1 3: C:\Windows\Installer\MSID060.tmp 4: /Install /quiet /norestart 
DEBUG: Error 2835:  The control ErrorIcon was not found on dialog ErrorDialog
```
and I can't find file C:\Windows\Installer\MSID060.tmp。 I don't know why.

**Comment by Liryna** [comment]
Will need more log to help
`msiexec /i MyApplication.msi /l*v MyLogFile.txt`

**Comment by MatriQ** [comment]
ok,there is the log
```log
MSI (s) (60:20) [20:50:02:110]: Executing op: ActionStart(Name=_28197B5F_E425_401B_B146_7D198EC702E1,,)
操作 20:50:02: _28197B5F_E425_401B_B146_7D198EC702E1. 
MSI (s) (60:20) [20:50:02:110]: Executing op: CustomActionSchedule(Action=_28197B5F_E425_401B_B146_7D198EC702E1,ActionType=3074,Source=BinaryData,Target=/Install /quiet /norestart,)
MSI (s) (60:64) [20:50:05:938]: Running as a service.
MSI (s) (60:64) [20:50:11:954]: Running as a service.
MSI (s) (60:64) [20:50:17:970]: Running as a service.
MSI (s) (60:64) [20:50:24:001]: Running as a service.
CustomAction _28197B5F_E425_401B_B146_7D198EC702E1 returned actual error code 1618 (note this may not be 100% accurate if translation happened inside sandbox)
MSI (s) (60:20) [20:50:24:063]: Note: 1: 1722 2: _28197B5F_E425_401B_B146_7D198EC702E1 3: C:\Windows\Installer\MSIE0C3.tmp 4: /Install /quiet /norestart 
DEBUG: Error 2835:  The control ErrorIcon was not found on dialog ErrorDialog
```

**Comment by Liryna** [comment]
Here is an exemple of full log: https://github.com/dokan-dev/dokany/issues/771#issuecomment-459665223

**Comment by MatriQ** [comment]
thanks,some chinese words in log ,hope there no trouble for you
[install.log](https://github.com/dokan-dev/dokany/files/3373057/install.log)

**Comment by Liryna** [comment]
@MatriQ That's your log application. Please do the log on the dokan installer only.

**Comment by MatriQ** [comment]
how to got dokan installer log  when exec dokan installer by my application installer?

**Comment by Liryna** [comment]
If it fails, you should be able to get the failure using dokan installer directly.
If you do not get a failure, it means it is not well integrated with your installer.

**Comment by MatriQ** [comment]
yeah,Is's not well integrated,I hope to fix it by this issue

**Comment by Liryna** [comment]
If you find anything related to an unexpected behavior with dokan installer please do not hesitate and I will look into it. Here I do not know how I can help you.

**Comment by MatriQ** [comment]
@Liryna  I find it , can't run  multiple msi installer process
