### ISSUE TITLE
dokan_fuse/mirror failing to mount

### ISSUE THREAD

**Issue by slipch** [dokan-dev/dokany#815]
# Environment
 * Windows version:  Microsoft Windows 10 Pro  10.0.17134 N/A Build 17134
 * Processor architecture:   [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~3401 Mhz
 * Dokany version: 1.2.2.1000
 * Library type (Dokany/FUSE): FUSE
 
# Check List
  - [v] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [v] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [v] I can always reproduce the issue with the provided description below.
  - [v] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description
dokan_fuse/mirror failing to mount
command is "./mirror.exe -d -f M:"
I use two systems. One of them works fine. Both the mirror example and my code perform as expected.
But with my main dev system it simply always fails. What I see it cannot create __drive_fs_keepalive.

dokan/mirror in the same system works fine

# Logs
[console.txt](https://github.com/dokan-dev/dokany/files/3401673/console.txt)
[KBP1-DHP-F65198.LOG](https://github.com/dokan-dev/dokany/files/3401674/KBP1-DHP-F65198.LOG)

**Comment by Liryna** [comment]
Which version of the driver are you using ? Is it the same computer you are doing your BSOD test on it ?

**Comment by slipch** [comment]
I've installed 1.2.2.1000. Product version on dokan1.sys shows 1.2.2.100
I didn't understand the question about BSOD. I had no BSODs connected with dokan. I'm not sure what you mean by "BSOD test"

**Comment by Liryna** [comment]
Hi @slipch 

Oh my bad ! I just mixed two issues sorry 😄 
My thought here is that the driver did not install correctly if none of the dokan app can run.
Can you run `dokanctl /v` and later `dokanctl /i d` ?

**Comment by slipch** [comment]
$ ./dokanctl /v
Driver path: 'C:\WINDOWS\system32\drivers\dokan1.sys'
dokanctl : Mar  8 2019 15:22:21
Dokan version : 122
Dokan driver version : 0x190

k.slipchenko@KBP1-DHP-F65198 /cygdrive/d/Projects/DokanNew/Release
$ ./dokanctl /i d
Driver path: 'C:\WINDOWS\system32\drivers\dokan1.sys'
Installing driver...
DokanServiceInstall: Service (Dokan1) is already installed
Driver install failed

**Comment by slipch** [comment]
Note that it is FUSE/mirror failing
dokan\mirror seems to work without issues

**Comment by Liryna** [comment]
It is probably related to https://github.com/dokan-dev/dokany/issues/804
Are you using the dokan fuse mirror from the installer ?

Could you try with the snapshot:
https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot
https://ci.appveyor.com/project/Maxhy/dokany/branch/master/job/0vid5goli6hupjg4/artifacts

**Comment by slipch** [comment]
I can not see mirror in the installer. But I used mirror (and cygdokanfuse1.dll) from zip archive in the same release as the installer. Also tried to build it myself from sources in dokany-1.2.2.1000

Tried https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot, unfortunately the same result
And built dokany binaries from the sources in git. The issue persist

**Comment by Liryna** [comment]
Hi @slipch 

Seems like you have a software disturbing the mount. Do you have in mind what it could be ? here it was the processid 15820 who opened __drive_fs_keepalive successfully in the kernel logs.

**Comment by slipch** [comment]
Hi Liryna,
I believe that the disrupting process that successfully opened the "keep alive" file is the same mirror.exe.
First time it succeeds and then tries to open it again for some reason and fails. It also crashes and creates dump file. But it is a mirror.exe that I built from sources. I'm not sure what you need to view it. It seems gcc doesn't creates pdbs.
I've repeated the experiment with process-monitor. This archive  
[withPM.zip](https://github.com/dokan-dev/dokany/files/3417832/withPM.zip)
 includes process-monitor log. You can see there the mirror PID and the fact that in opens __drive_fs_keepalive successfully first time.

**Comment by Liryna** [comment]
Hi @slipch ,

Thank you for the logs !

Here is the peace of code for keepalive. https://github.com/dokan-dev/dokany/blob/be8edbb1a5da5fa257b336ebf4bd0c5dd0545dc3/dokan/dokan.c#L282-L298
There is only one call of CreateFile for this file. Am surprise you have so much of them where the first one succeed and we get an error `Failed to open keepalive file: \\?\Volume{d6cc17c5-1731-4085-bce7-964f1e9f5de9}\__drive_fs_keepalive`.

@slipch would you be able to debug / trace this ? I could not reproduce it on my side 😢

**Comment by slipch** [comment]
Hi Liryna
You probably know, CreateFile is not necessary used precisely for creating files. It also opens files. May be there are other commands that end up in CreateFile. Thus the code not necessary calls CreateFile directly. I think things go awry before the program tries to open the keep-alive file. Looking carefully in the console log we can see that the first obvious error is
  unknown type:54
        DispatchQueryInformation result =  c000000d
That likely came from DispatchQueryInformation in dokany\dokan\fileinfo.c. The case "54" (FileStandardLinkInformation) is indeed missing from the switch. Though it is present DokanDispatchQueryInformation in dokany\sys\fileinfo.c.
The error is translated into "invalid parameter".
And I can see that the first real failure in the process monitor looks like
2:34:17.6428452 PM	mirror.exe	13724	DeviceIoControl	D:\Projects\DokanyBuiltBinaries\Cygwin\mirror.exe	INVALID PARAMETER	Control: IOCTL_MOUNTDEV_QUERY_DEVICE_NAME
And may be this failure is the result of the error in DispatchQueryInformation.

It could be that anti-spy-ware on this system have something to do with problem. After all that is the only difference with my test system that works. And yet dokany mirror doesn't have such problem. Thus it doesn't seem hopeless.
I can't put much more time into that right now but I hope to return to it.

**Comment by Liryna** [comment]
Hi @slipch 

Any news on this ?

**Comment by slipch** [comment]
Hi Liryna,
Sorry for the delay
The project with dokany FUSE is postponed. I can't work on it now
I'll do another project with dokany next week but without dokany FUSE
