### ISSUE TITLE
How to Install Vc Redistributable before dokan installation in "DokanMSI_x64" wix project

### ISSUE THREAD

**Issue by Sumanthdv** [dokan-dev/dokany#817]
Hi,
   Can anyone tell me how to handle installation of VC Redistributable before Dokan Installation in "DokanMSI_x64" wix project.
I know this is handled in bundle .wxs, but i need to handle this in DokanMSI_x64 wix project.
This is my requirement.

Thanks,
D V Sai Sumanth.

**Comment by Liryna** [comment]
Hi @Sumanthdv 

Dokan exe installer is exactly doing what you are looking for:
https://github.com/dokan-dev/dokany/blob/master/dokan_wix/Bootstrapper/Bundle.wxs

**Comment by Sumanthdv** [comment]
Hi Liryna,
    Actually I have an installer for my application, in order to run my application I need to have dokan installed . So when I'm calling the Dokan.exe from my installer , It says that "Another Installation is in progress". and Also  I need Silent execution of this dokan.exe without showing Dokan Installer UI.

Or else can you tell me how to add files to install directory in Bundle.wxs file and also change the installer UI?

Can you help me in this regard.

Thanks,
D V Sai Sumanth

**Comment by Liryna** [comment]
This peace of code is doing the redist and dokan msi install
https://github.com/dokan-dev/dokany/blob/master/dokan_wix/Bootstrapper/Bundle.wxs#L64-L121
You will need to integrate it to your installer.

**Comment by Liryna** [comment]
@Sumanthdv can this be closed ?

**Comment by Sumanthdv** [comment]
ok
