### ISSUE TITLE
Does a timeout of any operation leads to an unmount?

### ISSUE THREAD

**Issue by infeo** [dokan-dev/dokany#819]
# Environment
 * Windows version: 10 Pro 1903
 * Processor architecture: 64
 * Dokany version: 1.3.1000
 * Library type (Dokany/FUSE): Dokany 
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
This is just a question for stating things more clearly:
Mounting a filesystem with Dokany one has to specify a timeout variable. In the documentation it is described as the following:
> Max timeout in milliseconds of each request before Dokan gives up to wait events to complete

I'm not a windows programmer, but from my point of view it says that the _single file system request is aborted_, but the overall drives still works.

But if one looks at the mirror example, the help documentation describes the timeout with explictly stating that the _dokany volume is unmounted when the threshold is hit_. Additionally i found the following issue also describing this behaviour: https://github.com/dokan-dev/dokany/issues/205#issuecomment-200761448

If the latter one is always true (which I strongly assume), the documentation of the API should be updated.

**Comment by Liryna** [comment]
@infeo Does https://github.com/dokan-dev/dokany/commit/01a12b8dfd5c69ce4b5b210546a0067c1489cd13 is enough clear for you ?

**Comment by infeo** [comment]
Perfect! Thanks a lot for the clarification.

Am 16. September 2019 13:36:59 MESZ schrieb Liryna <notifications@github.com>:
