### ISSUE TITLE
DokanInstall_0.8.0-RC2.exe fails on `dokanctl.exe /i a`

### ISSUE THREAD

**Issue by acu192** [dokan-dev/dokany#82]
I'm using a Windows 8 VM. It's a semi-fresh install of Windows 8, and it's a fresh install of Dokany (I'm using VM snapshots to be sure of that).

DokanInstall_0.8.0-RC2.exe fails while running `dokanctl.exe /i a`.

But... DokanInstall_0.8.0-RC1.exe succeeds, so I'm just using that for now!

Let me know what other info I can provide! You all rock.

**Comment by Liryna** [comment]
Hi,

Can you provide the output of ` dokanctl.exe /i a` ?

**Comment by acu192** [comment]
dokanctl.exe can't run when I try it manually (missing DLL, if I remember correctly).

Edit: Okay, looks like you found it too!

**Comment by Liryna** [comment]
Should be fix with ed5ab8ceb7ed66ae465e34e88e4c7265f3eb2e8c
I will make a release tomorrow

**Comment by Liryna** [comment]
New release with the fix: https://github.com/dokan-dev/dokany/releases/tag/v0.8.0-RC2
Could you take a look and tell me if your issue is fixed :) ?

**Comment by acu192** [comment]
It works! Thanks!
