### ISSUE TITLE
Extreme slow copy speed from Windows client to server for many small files (fuse-nfs)

### ISSUE THREAD

**Issue by Nyanraltotlapun** [dokan-dev/dokany#820]
I want to refer this issue here https://github.com/Daniel-Abrecht/fuse-nfs-crossbuild-scripts/issues/1

Perhaps this can be fixed on dokany side?

**Setup:**
Windows 10 x64
libnfs=master fuse-nfs=master dokany=v1.2.1.2000
Dokany from corresponding x64 msi installer
FreeBSD NFSv3 server with mapall=nobody:nobody
Connect command:
`fuse-nfs.exe -n nfs://ip/main-zpool/share -m E:` 
(I also tried different options R -W (set to small values(9000) and to big values(500000), -H -A etc no difference)

**Problem:**
Extreme slow copy speed from Windows client to server for many(1240) not so small (around 1Mb) files. Speeds starts at 10-12Mb\s and ends at 2Mb\s.
Linux client do this blazing fast, with the same files.
And the NFS-Win port https://github.com/billziss-gh/nfs-win that is based on the same nfs lib give me around 50Mb\s
Same results for total commander and explorer copy.
For big file i get around 60Mb\s but NFS-Win give me 80+Mb\s

**Assumption:**
It seams to me that after each file copy fuse-nfs or docan or something is requesting full dir list from the server. Or perhaps it is permissions mapping problem...

**Comment by jacky35** [comment]
Hello,
I think for this to be relevant it would have to redo the tests with version 1.3.0.1000 of dokany.

The latest version has really made great progress.

Jacky
