### ISSUE TITLE
Segfault calling WaitForMultipleObjects on DokanKeepAlive thread handle

### ISSUE THREAD

**Issue by rkrikava** [dokan-dev/dokany#821]
# Environment
 * Windows version: Windows 10
 * Processor architecture: x64
 * Dokany version: v1.3.0
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x ] I can always reproduce the issue with the provided description below.
  - [x ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
If running an older driver (v1.1.0) with v1.3.0 of dokan.dll, resulting with a running DokanKeepAlive thread, the userspace app will crash when WaitForMultipleObjects is called on the thread handle.

See attached patch to fix
[dokan_v1_3_0_fix.txt](https://github.com/dokan-dev/dokany/files/3575752/dokan_v1_3_0_fix.txt)

**Comment by Liryna** [comment]
Hi @rkrikava ,

My bad, I had to see it when I imported the legacy keepalive... I have added your fix to the master
https://github.com/dokan-dev/dokany/commit/6fda00864a6411aa3a4ffa9f0f57830207aec093

Thank you very much for your report and including the fix 🏆  !
