### ISSUE TITLE
Failed to save MsWord file caused by mis-handled SetFileSecurity on Mirror.exe

### ISSUE THREAD

**Issue by yin19941005** [dokan-dev/dokany#822]
# Environment
 * Windows version:  Windows 7 and Windows 10
 * Processor architecture: x86
 * Dokany version: 1.3.0.1000
 * Library type (Dokany/FUSE): Dokany
 
This issue doesn't exist on version 1.2.2.1000 (tested on Windodws 7 x86).

# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

No, I didn't test any snapshot as only changelog and readme update on the latest snapshot.

# Description
**Command used to mount mirror: `mirror.exe /r C:\dokan_test /l Z: /d /s > C:\logs\mirror_setSecurityIssue_001.LOG 2>&1`**

When editing the security attribute, the existing security attribute will be cleanup and only the new added security attribute will exist. The mirror without any options on with new created text file is able to reproduce this issue.

**This issue will cause `MS Word` could not save file normally** (version MsWord2013). As the MS Word will create a tmp file and rename it on saving, the security attribute mis-cleanup will fail this process. As a result, the MS Word could not save normally.

### Steps to reproduce (For Windows 7)
1. Mount the dokan drive by mirror
2. Create a new text file
3. Right click the file -> Properties -> Security
4. Check there are existing security attribute (should be from inheritance)
5. Click Edit -> Add -> Input a user name (e.g. `user01`) -> Click Ok
6. Modify the permission for it and Click Ok
7. Click Ok to close (It should looks normal at this moment as we didn't click apply)
8. Repeat step 3 (i.e. open the security tag again) and check the result 
9. On the root directory, repeat step 3 (i.e. open the security tag again) and check the result 
10. Done

For Windows 10, basically is same, the only different is on step 7, Windows already notice something wrong and prompt requires Administrator right. It will same mis-cleanup the security attribute.

# Screenshot
### Security Attribute on New File Create
It's normal when file is just created, both through mirror or not through mirror have the same behavior:

![securityAttribute_miscleanup_002](https://user-images.githubusercontent.com/23186757/64399487-3806f880-d09b-11e9-8d47-e0e7ea7d044b.png)

### Set Security Attribute expected behavior
![securityAttribute_miscleanup_003](https://user-images.githubusercontent.com/23186757/64399504-46551480-d09b-11e9-8b45-b274ef66c0d7.png)

##### From dokan drive
![securityAttribute_miscleanup_004](https://user-images.githubusercontent.com/23186757/64399787-5c170980-d09c-11e9-9937-fa4ff0ef0e63.png)

##### From the actual root directory,
![securityAttribute_miscleanup_001](https://user-images.githubusercontent.com/23186757/64399517-4c4af580-d09b-11e9-8cd4-71e928ed0e5d.png)

# Logs
Windows 7:
[mirror_setSecurityIssue_001.LOG](https://github.com/dokan-dev/dokany/files/3582128/mirror_setSecurityIssue_001.LOG)

**Comment by yin19941005** [comment]
Update:

I found I didn't run the mirror right on previous test and I retried with admin right to start the mirror.exe. Same behavior even with the admin right. The following is the mirror logs with admin right:

[mirror_adminRight_setSecurityIssue_001.LOG](https://github.com/dokan-dev/dokany/files/3590025/mirror_adminRight_setSecurityIssue_001.LOG)

I tried to modify the `MirrorSetFileSecurity` function in mirror and save MS Word file, it is working. 
```
static NTSTATUS DOKAN_CALLBACK MirrorSetFileSecurity(
  LPCWSTR FileName, PSECURITY_INFORMATION SecurityInformation,
  PSECURITY_DESCRIPTOR SecurityDescriptor, ULONG SecurityDescriptorLength,
  PDOKAN_FILE_INFO DokanFileInfo) {
  HANDLE handle;
  WCHAR filePath[DOKAN_MAX_PATH];

  UNREFERENCED_PARAMETER(SecurityDescriptorLength);

  GetFilePath(filePath, DOKAN_MAX_PATH, FileName);

  DbgPrint(L"SetFileSecurity %s\n", filePath);

  handle = (HANDLE)DokanFileInfo->Context;
  if (!handle || handle == INVALID_HANDLE_VALUE) {
    DbgPrint(L"\tinvalid handle\n\n");
    return STATUS_INVALID_HANDLE;
  }

  /*
  Not actual set anything and return success
  if (!SetUserObjectSecurity(handle, SecurityInformation, SecurityDescriptor)) {
    int error = GetLastError();
    DbgPrint(L"  SetUserObjectSecurity error: %d\n", error);
    return DokanNtStatusFromWin32(error);
  }
  */
  return STATUS_SUCCESS;
}
```

**Comment by KerberX** [comment]
What if you'll use `SetKernelObjectSecurity` instead of 'SetUserObjectSecurity'? It does work for me though I use v2.0 beta.

**Comment by yin19941005** [comment]
Hi @KerberX,

Thank you for advise. It's the same behavior on using `SetKernelObjectSecurity`. The following code is used:
```
  if (!SetKernelObjectSecurity(handle, *SecurityInformation, SecurityDescriptor)) {
    int error = GetLastError();
    DbgPrint(L"  SetKernelObjectSecurity error: %d\n", error);
    return DokanNtStatusFromWin32(error);
  }
```

The weird thing is the dokan-1.2.2.1000 version is working fine but I couldn't spot any changes to cause this issue on `mirror.c` and `security.c`. @Liryna , any idea to this?

**Comment by yin19941005** [comment]
I confirmed running version 1.2.2.1000 mirror on version 1.3.0.1000 dokan.sys/dll is able to reproduce the issue as well.

### Updated Logs
I was following the `Steps to reproduce (For Windows 7)` on the description to generate these logs. The version specified is for all mirror, dll and sys.
#### version 1.2.2.1000 (normal case)
[mirror_1.2.2.1000_withKernelLog_setSecurityAttribute_001.LOG](https://github.com/dokan-dev/dokany/files/3595186/mirror_1.2.2.1000_withKernelLog_setSecurityAttribute_001.LOG)
[mirror_1.2.2.1000_withKernelLog_setSecurityAttribute_kernelLog_001.LOG](https://github.com/dokan-dev/dokany/files/3595187/mirror_1.2.2.1000_withKernelLog_setSecurityAttribute_kernelLog_001.LOG)
#### version 1.3.0.1000 (failed case)
[mirror_1.3.0.1000_withKernelLog_setSecurityAttribute_001.LOG](https://github.com/dokan-dev/dokany/files/3595189/mirror_1.3.0.1000_withKernelLog_setSecurityAttribute_001.LOG)
[mirror_1.3.0.1000_withKernelLog_setSecurityAttribute_kernelLog_001.LOG](https://github.com/dokan-dev/dokany/files/3595188/mirror_1.3.0.1000_withKernelLog_setSecurityAttribute_kernelLog_001.LOG)

**Comment by yin19941005** [comment]
Hi @KerberX,

Sure, here you go: https://github.com/yin19941005/dokany/tree/hotfix-mirror-setFileSecurity

https://github.com/yin19941005/dokany/commit/21e040a4db24253f87cc6fadbd9394d72eb9d9a6

I am only handled the DACL and the fail case did handled (still return STATUS_SUCCESS anyway). The code is quite messy as it just for testing.

**Comment by KerberX** [comment]
Thanks. I'll keep your solution in mind if I'll face with similar problem.

**Comment by Liryna** [comment]
@yin19941005 do you think you would have some more time to compare with procmon if there is a call order / return status different between the two versions ?

**Comment by yin19941005** [comment]
Hi @Liryna,

Ok, I will try to compare call order / return status different between the two versions after I finish the workaround fix for this.

It looks the issue is the inheritance ace is missing in the security descriptor when  `MirrorSetFileSecurity` in mirror is called.

I added the following code on `MirrorSetFileSecurity` in mirror:
```
LPTSTR StringSecurityDescriptor = NULL;
  ULONG StringSecurityDescriptorLen;
  BOOL convertResult = ConvertSecurityDescriptorToStringSecurityDescriptor(
     SecurityDescriptor, SDDL_REVISION_1, *SecurityInformation,
     &StringSecurityDescriptor, &StringSecurityDescriptorLen);
  if (convertResult) {
    DbgPrint(
        L"  ConvertSecurityDescriptorToStringSecurityDescriptor success on "
        L"SetFileSecurity %s\n",
        filePath);
  DbgPrint(L"  Converted StringSecurityDescriptor %s\n",
             StringSecurityDescriptor);
  } else {
    DbgPrint(L"  ConvertSecurityDescriptorToStringSecurityDescriptor failed on "
             L"SetFileSecurity %s\n",
             filePath);
  }
```

For 1.2.2.1000, 
`Converted StringSecurityDescriptor D:ARAI(A;;0x1200a9;;;S-1-5-21-4016021104-3883208471-1191975126-1001)(A;ID;FA;;;BA)(A;ID;FA;;;SY)(A;ID;0x1200a9;;;BU)(A;ID;0x1301bf;;;AU)`

https://docs.microsoft.com/en-us/windows/win32/secauthz/sid-strings

For 1.3.0.1000,
`Converted StringSecurityDescriptor D:ARAI(A;;0x1200a9;;;S-1-5-21-4016021104-3883208471-1191975126-1001)`

**Comment by yin19941005** [comment]
Hi @Liryna,

I think I had found the cause. The following image show a screenshot of procmon, left part is version 1.2.2.1000 and right part is version 1.3.0.1000. Both side should be on the same operation (I mapped by eyes from the beginning):

![procmon_001](https://user-images.githubusercontent.com/23186757/65138174-20d1ee80-da3d-11e9-950e-31586c5e2a3d.png)

It seems we couldn't open parent folder of the file (reporting `FILE NOT FOUND`) and this cause could not read the `inheritance ace` in DACL from the parent folder. However, it could read the DACL from the target file (`New Text Document.txt` in this case) (9/18/2019 1:02:43.0060205 PM on the right part). As a result, the Windows explorer consider there are not parent folder exist and simply set the non-inheritance ace from the existing DACL. 

It sounds make a lot sense to me now. Base on my understanding, we did get massive change on `create` operation in order to support `oplock`. The root cause should be something like some case mis-parse the path. I am checking what's wrong on the `create` operation part now.

**Comment by Liryna** [comment]
Hi @yin19941005 ,

Thanks you very much !
You are right, massive change on `create`, `oplock` but also https://github.com/dokan-dev/dokany/commit/639666bb458097a2cd559aa354beead8d84a2004

FileNameInformation provide the full path including Device. As you can see on your screenshot, the createfile failing because `Device` is wrongly added to the path that he probably received from `FileNameInformation`.

Another issue https://github.com/dokan-dev/dokany/issues/824 having the same behavior.
With a possible fix I haven’t checked for now https://github.com/dokan-dev/dokany/pull/825

We need to be sure in which case the full path with the device has to be provided.

**Comment by yin19941005** [comment]
Hi @Liryna,

I just had a quick test for #825. The mirror didn't try to open `\Device` anymore but it trying to open `\System32\System32\dokannp1.dll` and `\System32\dokan1.dll`. Although the setSecurity issue gone with #825, I believe it will produce other issue. The following is the mirror log (same command `mirror.exe /r C:\dokan_test /l Z: /d /s` is used) :

```
###Create 0103
CreateFile : C:\dokan_test\System32\System32\dokannp1.dll
  AccountName: bloom001, DomainName: BB_SMB_TESTING
	ShareMode = 0x7
	FILE_SHARE_READ
	FILE_SHARE_WRITE
	FILE_SHARE_DELETE
	DesiredAccess = 0x80
	FILE_READ_ATTRIBUTES
	FlagsAndAttributes = 0x200000
	FILE_FLAG_OPEN_REPARSE_POINT
	OPEN_EXISTING
	error code = 3


CreateFile status = c000003a
###Create 0104
CreateFile : C:\dokan_test\System32\dokan1.dll
  AccountName: bloom001, DomainName: BB_SMB_TESTING
	ShareMode = 0x7
	FILE_SHARE_READ
	FILE_SHARE_WRITE
	FILE_SHARE_DELETE
	DesiredAccess = 0x80
	FILE_READ_ATTRIBUTES
	FlagsAndAttributes = 0x200000
	FILE_FLAG_OPEN_REPARSE_POINT
	OPEN_EXISTING
	error code = 3


CreateFile status = c000003a
```

**Comment by Liryna** [comment]
Hi @yin19941005 @Temtaime,

I have been able to test @Temtaime PR. I had BSOD using Avira / 360 antivirus when network device option is used.
So here are different things:
-When using File System Drivers, it expects you to just return  `\folder\filename.txt`
-When using Network Redirector Drivers,  it expects you to return `\\server\share\folder\filename.txt` (UNC + FileName)
See https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/irp-mj-query-information

@Temtaime PR correctly fixes the usage of `DiskDeviceName` for local devices.

The issue is that previous code way before this commit was already wrongly using `DiskDeviceName` instead of `UNCName` 
https://github.com/dokan-dev/dokany/commit/639666bb458097a2cd559aa354beead8d84a2004
It means for network devices we were returning `\Devices\....\FileName` instead of `\\server\share\folder\filename.txt`

To fix both issues, we just need to use UNCName for network and nothing for local device.

But here is the thing, Avira / 360 antivirus will produce a BSOD if UNC is not found in the network path (normal). But what happens when we do a simple network mount without UNC ? I choose to use the `DiskDeviceName`  in this case as it seems to the best way.

Here is the fix https://github.com/dokan-dev/dokany/commit/ca36a734ee72611ae84bf1de868fd0a427e34a58

If you both could give any feedback on this.
On my side, setSecurity / Antivirus BSOD are fixed.

**Comment by yin19941005** [comment]
Hi @Liryna,

I just tested with the fix ca36a73: the issue resolved in normal drive and removable drive but persist in network drive (without UNC).

![procmon_002](https://user-images.githubusercontent.com/23186757/65400049-a4e7f580-ddf2-11e9-8d39-043939180765.png)

**Comment by Liryna** [comment]
@yin19941005 I agree here is the issue I was talking before. It is expected that we return a path with unc. If we do not, anti-virus and maybe other apps will crash as it is an unexpected format.
Returning devicename is not a working solution as you just reported.

Need to look more but probably allowing a network mount without unc should not be allowed.

**Comment by yin19941005** [comment]
Hi @Liryna,

I think I got what you mean now. Base on my understanding, the expected behavior should be:

| Path | Normal File Drive | Removable Drive | Network Drive |
| :---: | :---: |:---: | :---: |
| Path with UNC | Normal | Normal | Normal |
| Path without UNC | Normal | Normal | BSOD for some application |

I am trying to have more test on it but I am not really sure I use the UNC option correct or not. For saving MsWord, it looks normal (for `/u "\localhost\Z$"`). However, when I tried to use `/u "\localhost\Z$"` as the UNC, the security tab is hidden by the explorer (i.e. could not set security attribute) ; I tried to use `/u '\localhost\Z$'` as the UNC, it failed to set the security attribute as the following screenshot :

![networkDrive_securityAttribute_error_001](https://user-images.githubusercontent.com/23186757/65497810-6edb6c00-deed-11e9-9d0b-78402e16b499.png)

Is it any way to set security attribute on network drive? 

I am not familiar with UNC but could we always having `"localhost\{Drive Letter}$"` or `"\127.0.0.1\{Drive Letter}$"` as a default UNC?

**Comment by Liryna** [comment]
Hi @yin19941005 

You made a great summary 👍 of the situation.
It doesn't feel like there is much we can improve here. As you said, we can create ourselves a `\\localhost\Z` when Z is the mount point. But maybe the user would not want this behavior because he already has `\\localhost\Z` used for something else ?

Someone who cares to have all features working correctly with network devices should use an UNC.
Maybe we could update state this point in the documentation OR directly force the UNC usage ?

**Comment by kyanha** [comment]
My vote would be: directly force UNC usage on any network mount.  That's what the system expects, that's what various antivirus seems to bug out if it's not there, and we might as well ensure that it's there to minimize deviation.

**Comment by Liryna** [comment]
I fully agree. This should probably be done for `1.4.0` as breaking change. I will let the time for anyone who thinks we should keep simple network devices without UNC for a valid reason.

Otherwise having an auto-generated UNC like `\localhost\dokan[1-9]` when no UNC provided might not be the best...or is it ?

**Comment by kyanha** [comment]
All UNCs have two leading backslashes.  I don't know what bugs in other software (i.e., antivirus) might be triggered if it doesn't. :/

**Comment by Liryna** [comment]
The start with single backslash comes from windows API functions that expect it like this.

**Comment by kyanha** [comment]
Which API functions expect a single backslash to refer to a UNC path?  Which APIs return a single backslash when referring to files on UNC?

I've never run into anything documented like that. (That doesn't mean they don't exist, just that the documentation that I've read doesn't state they exist.) :/

**Comment by Liryna** [comment]
There is FileAllInformation and FileNameInformation that expect a full path with a single leading backslash.
https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/irp-mj-query-information#operation-network-redirector-drivers

**Comment by Liryna** [comment]
I move the issue to https://github.com/dokan-dev/dokany/issues/849

**Comment by Liryna** [comment]
@kyanha Win32 subsystem replaces the `\\` characters with the name `\Device\UNC`. `\Device\UNC` is a symbolic link to `\Device\MUP`. [MUP](https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/support-for-unc-naming-and-mup) is where dokan kernel register the UNC, MUP will at this moment redirect the remaining path to dokan kernel.
`\\dokan\mfs1` => `\Device\UNC\dokan\mfs1` => `\Device\MUP\dokan\mfs1` => `\mfs1` (what dokan kernel receives)

I will try to document this better on the MPR (network redirector) and the MUP registration in the kernel.

**Comment by bailey27** [comment]
I see in the latest Dokany 1.3.1.1000  this comment in the changelog

Kernel - FileNameInformation - Only concat UNCName / DiskDeviceName for network devices

Does that fix this issue?

**Comment by kyanha** [comment]
@Liryna I worry about a conflict with an SMB device named 'dokan'.  Other self-hosted UNC devices typically prepend their names with '.', to avoid conflict (like '.dokan').  Is this something which might be altered?  I don't recall it beibg in the documentation as something which was supported?

**Comment by Liryna** [comment]
@kyanha UNC name are for every protocol. It is not exclusively linked to SMB. The conflict is the same as having multiple SMB server with same name.

It is up to developers to handle such conflicts from my point of view.

@bailey27 yes this should fix the issue but network option still need to provide an unc name.
