### ISSUE TITLE
Install two dokan driver in one machine?

### ISSUE THREAD

**Issue by UnknowsBetter** [dokan-dev/dokany#830]
How to install two dokan driver in one machine?

I want to install latest version but both **keep my old dokan** version, which has same major version number with the latest one.

I have tried to change the DokanAPIVersion, but when I manually install the driver, I got error said it cannot start Service, last error code is 577

What should I do, is there anybody could help me?

![image](https://user-images.githubusercontent.com/55789224/65654569-e45d4e80-e04b-11e9-955d-9115baeade40.png)

**Comment by Liryna** [comment]
@UnknowsBetter Hi,

You can only have one driver of the same major version. There is unique global resources allocated by the driver. Even having a different file name will not change this.

As all dokan driver à backward compatible. What is your goal exactly here?

**Comment by Liryna** [comment]
@UnknowsBetter do not hesitate if you need anything else.

**Comment by UnknowsBetter** [comment]
thanks a lot !!!
