### ISSUE TITLE
Private file system?

### ISSUE THREAD

**Issue by BiatuAutMiahn** [dokan-dev/dokany#832]
Is it possible to restrict a virtual filesystem to a single process and potentially child it's processes/threads?

**Comment by Liryna** [comment]
@BiatuAutMiahn Yes, you can check the processid of each request to only allow the wanted process an return accès denied status for other process.

**Comment by BiatuAutMiahn** [comment]
ok cool, what about making the drive completely invisible? say UNC path?

**Comment by Liryna** [comment]
Current session mount might already help you. But to go further, maybe you would need to run your application with a specific system user with this option. This would allow you single process also running in this user (group ?) the only one to see it.

**Comment by BiatuAutMiahn** [comment]
Well my intended application for dokany is to have an isolated filesystem in which to run software that an end user will not be able to tamper with, such as portable applications.

Thank you for your feedback
