### ISSUE TITLE
Dokan not working in Container/Windowsserver Core

### ISSUE THREAD

**Issue by xgcssch** [dokan-dev/dokany#834]
# Environment
 * Windows version: 1809 (17736.737)
 * Processor architecture: x64
 * Dokany version: 1.3.0
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet]
  - [n/a] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the latest version and have reboot my computer after.
  - [x] I tested one of the last snapshot from appveyor CI

# Description
I tried to install dokan in a Windows Server Core container running with docker.
The container base image is Windows Server Core 2016 / 1809.
The installation completes successfully, but the driver is not accessible:

```
"c:\Program Files\Dokan\DokanLibrary-1.3.0\dokanctl.exe" /v
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
dokanctl : Jul 24 2019 14:10:25
Dokan version : 130
Dokan Error: Failed to open \\.\Dokan_1 with code 2
Dokan driver version : 0x0
```
Neither Application Eventlog nor System shows any hints.

Is Dokan expected to run on Windows Server core?
Is Dokan expected to run on Windows Server core running inside a docker container?

Steps to reproduce:
1. Install [Docker](https://docs.docker.com/docker-for-windows/install/)
2. Create an empty directory and put the following Dockerfile into that directory:
[Dockerfile.txt](https://github.com/dokan-dev/dokany/files/3702570/Dockerfile.txt)
3. Rename Dockerfile.txt to Dockerfile (Github does not allow files without extension)
4. Create a subdirectory `Data` and place `VC_redist.x64.exe`, `Dokan_x64.msi` and `mirror.exe` there
5. Open an admin shell, change to the directory created in step 2., and issue `docker build -t windowscoredokan .`
6. Start the freshly build container with `docker run -ti windowscoredokan`
7. After the container has come up with a commandprompt: `"c:\Program Files\Dokan\DokanLibrary-1.3.0\dokanctl.exe" /v` shows the problem.

Thanks much
Sönke

**Comment by Liryna** [comment]
@xgcssch Hi,

Windows Server Core does not seems to be able to register the driver during install. Can you try to run this command :
pnputil –i –a dokan1.inf
See https://docs.microsoft.com/fr-fr/windows-server/administration/server-core/server-core-manage#add-hardware-and-manage-drivers-locally
(Dokan is not plug and play)

**Comment by Liryna** [comment]
@xgcssch Have you tried to just do a dokanctl /i d?
if it fails, you can get some logs using Dbgview:
https://blogs.technet.microsoft.com/mbriggs/2009/02/06/how-to-capture-a-dbgview-trace-from-windows-core/

**Comment by xgcssch** [comment]
It seems, that the driver is installed.

```
C:\Program Files\Dokan\DokanLibrary-1.3.0>dokanctl.exe /i d
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
Installing driver...
DokanServiceInstall: Service (Dokan1) is already installed
Driver install failed
```
Driver reinstallation succeeds too:

```
C:\Program Files\Dokan\DokanLibrary-1.3.0>dokanctl.exe /r d
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
Removing 'Dokan1'...
DokanServiceControl: Service (Dokan1) deleted
'Dokan1' removed.

C:\Program Files\Dokan\DokanLibrary-1.3.0>dokanctl.exe /i d
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
Installing driver...
DokanServiceInstall: Service (Dokan1) installed
DokanServiceControl: Service (Dokan1) started
DokanServiceInstall: Service (Dokan1) started
Driver installation succeeded!
```
But the service does not come up:

```
C:\Program Files\Dokan\DokanLibrary-1.3.0>sc query dokan1

SERVICE_NAME: dokan1
        TYPE               : 2  FILE_SYSTEM_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 1077  (0x435)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```
The Windows error 1077  (ERROR_SERVICE_NEVER_STARTED) gives me no clue.
Explicit Service start does not succeed either:
```
C:\Program Files\Dokan\DokanLibrary-1.3.0>sc start dokan1

SERVICE_NAME: dokan1
        TYPE               : 2  FILE_SYSTEM_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 1077  (0x435)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 0
        FLAGS              :

```

**Comment by Liryna** [comment]
@xgcssch Dbgview should give us some hint on what is happening. Have you succeed to get them?

**Comment by xgcssch** [comment]
@Liryna I haven't got Dbgview working inside the docker container. Nor could i install a kernel debugger. Instead i installed a VM with a standard Windows Server Core image and tested there: it worked right from the start.
After that i gave up with my plan to install dokan inside the container. 
Therefor i will close this issue.

Next idea was to install dokan on the docker host and mount the target as a volume inside the docker container.
At first sight this worked fine. But than i discovered, that when i tried to change into a subdirectory below the mapped dokan volume path, i always ended up in the lexicographic first directory entry.
Inspecting the debug output of "mirror", i discovered that the FileIdExtdBothDirectoryInformation event is triggered, but not handled.
After that i added code to handle that event, and as a result the problem is gone.

I will submit a pull request for the fix.
Best regards and thanks for you help and this awesome project!

**Comment by Liryna** [comment]
Thank you @xgcssch for your feedback and for your test ! (and for the coming PR ❤️ too )

**Comment by hans-olav** [comment]
I was trying to run Dokan in a container and just ran into the same issue as described here on latest Dokan/latest Windows.
It would be great if we could make it work. Should we open this issue again? @Liryna?

**Comment by Liryna** [comment]
@hans-olav Yes, please open a new issue with the kernel logs. We will see if that the same issue or not from there.
