### ISSUE TITLE
Enable Code Analysis on debug builds

### ISSUE THREAD

**Issue by kyanha** [dokan-dev/dokany#837]
Please enable code analysis on all debug configurations (including the Windows-version specific debug builds in sys/).  When I enabled it just now, I got a fascinating glimpse of 84 warnings against commit 758ba03.

All projects except for sys/ were set to "Microsoft Native Recommended Rules".
sys/ was set to "Microsoft Driver Recommended Rules".

Please note that I am using Visual Studio 2019 Community Edition.  I do not know if the warnings generated change in Professional Edition.  (I say this because the annotation for Microsoft Native Recommended Rules says that it's intended for use with Professional Edition.)

**Comment by Liryna** [comment]
It is right we should take the time to fix every report from VS code analysis, sonar and coverity
https://scan.coverity.com/projects/dokan-dev-dokany
https://sonarcloud.io/dashboard?id=dokany

I try time to time to fix them. I know that half are false report (or dokan hack) and should mark to be ignored.

I just wonder if it is useful to enable it for every debug build or just one ? I need to check if there is some difference.

**Comment by kyanha** [comment]
All the remaining Coverity reports are false (fwprintf's "%s" format does take WCHAR* as its argument).

Your Sonarcloud report is incomplete.  The reason is because it will only process the first build in its sonarqube.msbuild and build-wrapper capture, and the order of build.bat (with "Release" and "Debug" first) doesn't build dokan1.sys in the first build.  (This was partly the point of my PR #797, to actually get sys/ coverage in Sonarcloud.  I don't know PowerShell, so I couldn't submit a replacement PR to your specs.)

To see the difference, compare the following two reports (both based on dokan-dev/dokany master branch):
https://sonarcloud.io/dashboard?id=dokany
https://sonarcloud.io/dashboard?id=dokany-sys

As for whether it's useful to enable code analysis for every debug build or just one, I think it's useful for all of them.  The reason: people who are working only on the platform that they're interested in will always have Visual Studio giving them the code analysis.  (And even if it's enabled in the .vcxproj files, it looks like msbuild won't actually run the analysis without the `/p:RunCodeAnalysisOnce=True` argument, so it appears it won't slow down or increase the cost of CI builds.  You could always modify the build script to declare that parameter as `false`, too, if it actually does.)

**Comment by Liryna** [comment]
Hi @kyanha ,

Thanks for the PR 👍 
Had to say you could not switch the script to ps 😉 I just did it https://github.com/dokan-dev/dokany/commit/bd8eb71281db1051d59005015e6fbe656dc10903 and added your idea to analyze sys code https://sonarcloud.io/dashboard?id=dokany-dev-sys

Let me know if I forgot something and I will merge it with your PR to move on fixing reports.

**Comment by Liryna** [comment]
@kyanha what was the reason you have split into two different sonar the lib and sys ?

**Comment by Liryna** [comment]
@Liryna OK just found the reason in your PR. I need to reorder the build also.

Would it also not mean that only one build is needed for sonar?

**Comment by Liryna** [comment]
Reopen (auto merge close) until most important fixing reports are made.

**Comment by kyanha** [comment]
I don't have enough knowledge of Sonar's internals to know whether it can change its analysis based on the platform options used for the build.  If I had to guess from what I know, I'd say it normally can't... but if there are complex #ifdef chains then its analysis will be limited to only the preprocessor symbols available during that build.

**Comment by kyanha** [comment]
> 
> 
> @Liryna OK just found the reason in your PR. I need to reorder the build also.
> 
> Would it also not mean that only one build is needed for sonar?

I honestly don't know.  I would think that only one build would be needed, but I don't know if Sonar's processing differs based on the platform the build is for, and I'd rather verify that before deciding to move ahead with only reporting on a single build.

**Comment by Liryna** [comment]
From https://docs.sonarqube.org/latest/analysis/scan/sonarscanner-for-msbuild/ seems like we can build whatever we want between begin and start BUT `Projects targeting multiple frameworks and using preprocessor directives could have slightly inaccurate metrics (lines of code, complexity, etc.) because the metrics are calculated only from the first of the built targets.`

So my guess would be that only first platform preprocessor define are counted.
Let's see what this topic will give us https://community.sonarsource.com/t/multi-platform-configuration-build/16170

**Comment by Liryna** [comment]
Fast answer => `no, we analyze the same code which is compiled during the build which is wrapped by build-wrapper.`
I will look to have only one build of libs and sys 👍 Win10

**Comment by kyanha** [comment]
Awesome.  And once #624 is complete, there won't be incorrect metrics or ignored code in the build.

**Comment by Liryna** [comment]
@kyanha I have looked into #624 that's not something would happen or when we will drop win7

**Comment by Liryna** [comment]
@kyanha Dokan sys is now a single binary https://github.com/dokan-dev/dokany/commit/fa653bedb54fa0c5a5fce5a610ff5ecf06062b83
Also sonar only build one version now (libs + sys together )👍

**Comment by kyanha** [comment]
👍 Awesome.  I think we can probably close this one and start filing new issues on the most pressing warnings we find.  Awesome work on fa653be and #624!

**Comment by Liryna** [comment]
Yes, this can be closed. Lets follow https://github.com/dokan-dev/dokany/issues/844 !
