### ISSUE TITLE
Unclear documentation of zwcreatefile

### ISSUE THREAD

**Issue by spectre1989** [dokan-dev/dokany#852]
The documentation of zwcreatefile says the following:

> In case \c OPEN_ALWAYS & \c CREATE_ALWAYS are successfully opening an existing file, STATUS_OBJECT_NAME_COLLISION should be returned instead of STATUS_SUCCESS . This will inform Dokan that the file has been opened and not created during the request

In the case of CREATE_ALWAYS the file is always created, so this doesn't inform dokan that the file was not created. Unless this is a mistake and it should be OPEN_EXISTING rather than CREATE_ALWAYS?

Does this all still apply for directories or is it only files?

**Comment by Liryna** [comment]
Hi @spectre1989 ,

https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea
CREATE_ALWAYS: `Creates a new file, always.
If the specified file exists and is writable, the function overwrites the file, the function succeeds, and last-error code is set to ERROR_ALREADY_EXISTS (183).
If the specified file does not exist and is a valid path, a new file is created, the function succeeds, and the last-error code is set to zero.`

Am actually doing a memory fs to improve the doc/example that it might help you.
OPEN_EXISTING: 
https://github.com/dokan-dev/dokany/blob/memoryfs/samples/dokan_memory/MemoryFSOperations.cpp#L116-L123

CREATE_ALWAYS: 
https://github.com/dokan-dev/dokany/blob/memoryfs/samples/dokan_memory/MemoryFSOperations.cpp#L80-L93

I don't think those flags are possible for directories need to check.

**Comment by spectre1989** [comment]
So it does sound like CREATE_ALWAYS should return STATUS_OBJECT_NAME_COLLISION then, but in that case the file is still not opened.

**Comment by Liryna** [comment]
The file is open during the CREATE_ALWAYS when return `STATUS_OBJECT_NAME_COLLISION`
https://github.com/dokan-dev/dokany/blob/master/dokan/create.c#L93-L98
It is going to be converted to a success for dokan library and inform the file existed
https://github.com/dokan-dev/dokany/blob/master/dokan/create.c#L326-L334

**Comment by Liryna** [comment]
@spectre1989 please do not hesitate if you think I might miss something here.

**Comment by Liryna** [comment]
@spectre1989 Let me know if this need to be reopen
