### ISSUE TITLE
Mounting .iso files from Dokan drive gives problems

### ISSUE THREAD

**Issue by paul35621** [dokan-dev/dokany#855]
# Environment
 * Windows version: 10.0.17763
 * Processor architecture: 64 bit
 * Dokany version: 1.3.1
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

Since Windows 10 mounting of .iso files is built-in. Usually, in Windows Explorer you can double click on a .iso file, and then a new drive will appear. After usage you can unmount it by doing right-click and Eject.

But, this seems not to work well if the .iso file resides on a Dokan drive. I discovered the problem with my own application, but it also happens with the sample mirror application. I used the following command to create a mirror drive:

    mirror /d /s /r d:\test /l x: 2> c:\Users\Paul\Desktop\log.txt

Now, when I open `x:\ubuntu-18.04.2-desktop-amd64.iso`, an error box with title `Couldn't Mount File` and content `Sorry, there was a problem mounting the file.` is displayed. The iso file is still mounted, but when trying to unmount (eject) the drive, the error `An error occurred while ejecting 'DVD Drive (I:) Ubuntu 18.04.2 L'.` shows and no unmounting is being done.

When I run the mirror application as administrator, the result is the same.

Since the application I'm writing is centered around .iso files, it would be really nice to know what causes this and if this can be fixed.

[log.txt](https://github.com/dokan-dev/dokany/files/4011484/log.txt)

**Comment by Liryna** [comment]
@paul35621 Hi,


Have you tried to mount with the mount manager option enabled?

**Comment by paul35621** [comment]
I have now. That fixes the problem in the mirror application, thanks!

But in my own application it still doesn't work when I add the `DOKAN_OPTION_MOUNT_MANAGER` option. The `Sorry, there was a problem mounting the file.` error shows and no mounting is done at all.

I can however run my application to create a Dokan drive, then mirror that drive using the mirror application, and then mount the .iso file from the mirror drive. That does work.

I understand this problem is specific to my application, but maybe it's a simple thing. Do you have an idea what could be the problem? These are my options:

	DOKAN_OPERATIONS operations;
	ZeroMemory(&operations, sizeof(DOKAN_OPERATIONS));
	operations.ZwCreateFile = callbackZwCreateFile;
	operations.CloseFile = callbackCloseFile;
	operations.ReadFile = callbackReadFile;
	operations.GetFileInformation = callbackGetFileInformation;
	operations.FindFiles = callbackFindFiles;
	operations.GetVolumeInformation = callbackGetVolumeInformation;
	operations.Mounted = callbackMounted;

	DOKAN_OPTIONS options;
	options.Version = DOKAN_VERSION;
	options.ThreadCount = 0;
	options.Options = DOKAN_OPTION_WRITE_PROTECT | DOKAN_OPTION_ENABLE_NOTIFICATION_API | DOKAN_OPTION_MOUNT_MANAGER;
	options.GlobalContext = 0;
	options.MountPoint = L"V:\\";
	options.UNCName = NULL;
	options.Timeout = 1000;
	options.AllocationUnitSize = 1024;
	options.SectorSize = 1024;

**Comment by Liryna** [comment]
Humm you do not support a couple of operations but it might be possible they will not be mandatory for what you need. It is always better to handle the most possible to handle any request for the app using your iso files.

You can use procmon to trace what kind of request your iso app is doing and see if there is something he might no like and then create the error.

**Comment by paul35621** [comment]
Okay, I'll figure out what the problem is and report back here.

**Comment by paul35621** [comment]
Yes, I figured it out finally! Mounting via PowerShell gave the reason why it failed:

	PS C:\Users\Paul> Mount-DiskImage -ImagePath "v:\out.iso"
	Mount-DiskImage : The sector size of the physical disk on which the virtual disk resides is not supported. 
	At line:1 char:1
	+ Mount-DiskImage -ImagePath "v:\out.iso"
	+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	    + CategoryInfo          : NotSpecified: (MSFT_DiskImage:ROOT/Microsoft/.../MSFT_DiskImage) [Mount-DiskImage], CimException
	    + FullyQualifiedErrorId : HRESULT 0xc03a001d,Mount-DiskImage

A sector size of 1024 is apparently not supported. So now I just leave it at 0 to use the default of 512 bytes sector size:

	DOKAN_OPTIONS options;
	ZeroMemory(&options, sizeof(DOKAN_OPTIONS));
	options.Version = DOKAN_VERSION;
	options.Options = DOKAN_OPTION_WRITE_PROTECT | DOKAN_OPTION_ENABLE_NOTIFICATION_API | DOKAN_OPTION_MOUNT_MANAGER;
	options.MountPoint = L"V:\\";
	options.Timeout = 1000;

**Comment by Liryna** [comment]
Thank you for the feedback @paul35621 !
