### ISSUE TITLE
[Question] Integrate ProjFS or VFSforGit?

### ISSUE THREAD

**Issue by quangkieu** [dokan-dev/dokany#859]
# Environment
 * Windows version: Windows 10/1809+

Hey just a quick question as I could not find mention of this in Issues.
I just wonder if you have plan to Integrate to either of those for the back-end infrastructure for newer Windows 10 so it is more native kernel?

Quang

**Comment by Liryna** [comment]
@quangkieu Hi!

Dokan is the library capable to implement filesystem like the one you listed. It is up to anyone to do it using dokan.
Therefore we do not plan to create this filesystem inside dokan as it would be a different project.

**Comment by Liryna** [comment]
@quangkieu let me know if anything to add to this and will reopen the ticket.
