### ISSUE TITLE
Drive space info missing in Explorer

### ISSUE THREAD

**Issue by leochou0729** [dokan-dev/dokany#861]
Please take a look at this link.
https://github.com/jetwhiz/encfs4win/issues/140#issue-549389612

I'm not sure this issue is related to encfs or fuse. Thanks!

**Comment by Liryna** [comment]
@leochou0729 Hi,

This usually happens when the user land do not answer to the first filesystem calls. Would be a good as first step to look in encf what happens.

**Comment by leochou0729** [comment]
Can I ask what is the first file system call? Is it .init function?

**Comment by Liryna** [comment]
Closing this as related to issue you provided
