### ISSUE TITLE
Q: Making a minimal installer

### ISSUE THREAD

**Issue by samokhodkin** [dokan-dev/dokany#864]
Hi, I have difficulties with embedding Dokany to my app. The purpose is to make it as little as possible.

The total size of the required files (dokan1.sys, dokan1.dll, dokanctl.exe) is within 400 Kb, which is quite small. But the last two files require the VC2019 redistributable to work, and this is another 14 Mb (https://aka.ms/vs/16/release/vc_redist.x64.exe). Unacceptably large for me.

What can be done? Can these files be compiled without dependency on the latest redistributable?

**Comment by Liryna** [comment]
Hi @samokhodkin 

You might find your answer in this issue https://github.com/dokan-dev/dokany/issues/660
I am open to any suggestions but if you can build and sign dokan1.dll, dokanctl.exe yourself, it might be good to try MT option.
