### ISSUE TITLE
On win 10 machines, long delay when opening PPT files

### ISSUE THREAD

**Issue by yuchwang59** [dokan-dev/dokany#865]
# Environment
 * Windows version: 10 professional
 * Processor architecture: Intel(R) Core(TM) i7-8550U CPU @1.8GHz 1.99 GHz
 * Dokany version: 1.3.1.1000
 * Library type (Dokany/FUSE): FUSE
 
# Check List
  - [Y] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [Y] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [Y] I can always reproduce the issue with the provided description below.
  - [Y] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [Y] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Problem: It takes 2 seconds to open a PPT file in a local folder (ntfs) and 27 seconds to open the same PPT file in the dokan directory. 
According to the preliminary analysis, the PPT is read by several bytes each time, which causes frequent interface invoking. 

Question 1: Does Dokan have a method similar to Linux kernel page cache to read 4 KB data at a time? 

Question 2: Are there any optimization suggestions? 

Question 3: It takes 6 seconds to open a PPT file of 27 MB by using dokan mirror and 36 seconds to open the same file by using fuse mirror. What might be the cause of this difference? 

# Logs
Please attach in separate files: mirror [output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#mirrorfs), library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#get-logs).
In case of BSOD, please attach minidump or dump [analyze output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#crash-report-bsod).

**Comment by Liryna** [comment]
Hi @yuchwang59 ,

Are you using the mirror sample for your test ? Can you provide the command used ?
Please also provide the mirror logs to see what is exactly happening.

Regarding caching, multiple performance enhancement are planned for this year :+1:

**Comment by yuchwang59** [comment]
Dokan Library-1.2.1\sample\fuse_mirror\mirror.exe m -d

then open a PPT file of  8 MB under the disk created, which takes 46 seconds
[log_dokan.zip](https://github.com/dokan-dev/dokany/files/4101577/log_dokan.zip)

**Comment by yuchwang59** [comment]
Hi Liryna,

Thanks for your response. Anything new about the issue of ppt file opening? I sent you the commands used and relevant logs.

BR,
YUCH




On 01/21/2020 23:27, Liryna wrote:

Hi @yuchwang59 ,

Are you using the mirror sample for your test ? Can you provide the command used ?
Please also provide the mirror logs to see what is exactly happening.

Regarding caching, multiple performance enhancement are planned for this year 👍

**Comment by yuchwang59** [comment]
When we use <Dokan Library-1.2.1\sample\fuse_mirror\mirror.exe m> (without -d), everything is ok

**Comment by yuchwang59** [comment]
Regarding caching, multiple performance enhancement are planned for this year 👍

**Comment by yuchwang59** [comment]
Hi @Liryna , 

As is commented on 21 Jan
Regarding caching, multiple performance enhancement are planned for this year 👍

What is expected performance improvement in percentage?
When will the version with performance enhancement be released? 

For now, compared with NTFS, the performance of using mirror dokany 1.3.1.1000 decreases by around 70%.
Command: mirror.exe /r D:\\ /l M

**Comment by Liryna** [comment]
Hi,

That's pretty hard to say. We need to first know what are the current perf using a user land filesystem without any resource depending.

The number you provide compared to ntfs is normal as we run on top of ntfs, there is no magic here we can do.

I plan to finish the memory filesystem, add some simple benchmark to evaluate at each changes how much we got from it.

Dokan is already fast enough for people to create a user land filesystem for vidéo editing. The performance we will add is to beyond that.

**Comment by Liryna** [comment]
Hi @yuchwang59 ,

Could you give a try with the new release 1.4.0.1000 with the mirror and option `z` ?
https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L1545
