### ISSUE TITLE
Mounting to NTFS path causes local C: drive to be shown as disconnected network drive

### ISSUE THREAD

**Issue by 0x4a616e** [dokan-dev/dokany#867]
# Environment
 * Windows version:  Windows 10
 * Processor architecture: x64
 * Dokany version: 1.3.0.1000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [ ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

I have a .NET application using dokan-net and dokan, that mounts a user mode file system to an NTFS path using `DokanOptions.CurrentSession` as the only mount option. Everything works well when the app is started manually, but when the app is started via `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`, the local drive `C:` gets shown as a disconnected network drive in the explorer. However, everything still seems to work normally.

I already tried starting the application via a script that adds a delay of a minute before actually starting the application but the issue persists...

Unfortunately, this only happens on very few machines (not mine to make it even worse) but there it happens _all the time_. I don't really have any idea how to debug this or how to provide further information that might help identifying the issue...

Help me dokan-dev-team, you're my only hope 🤖

**Comment by Liryna** [comment]
Hi @0x4a616e ,

Do you have access to one of those machines ? Does removing dokannp.dll in system32 folder change the behavior ? (will need to kill explorer to remove it)

**Comment by 0x4a616e** [comment]
Hi @Liryna , thanks for the quick response! Luckily I have (limited) access to one of those machines. I removed `dokannp.dll` and badaboom: it worked!

**Comment by Liryna** [comment]
Humm @0x4a616e that good! Would you be able to get the logs with dbgview ?
A simple refresh or new explorer windows should query the dll to know if:
- This is a dokan drive or not
- If it is a dokan drive -> what UNC name is used

So we might see `C:\` and should answer that it is not our drive

**Comment by 0x4a616e** [comment]
I guess i'll be able to do that, but probably not today as we have to install the debug build first. I'll try to get the logs asap!

Looking at the network providers, the only difference between affected and not-affected machines I was able to spot is that it only seems to affect Dell notebooks using `RemediationNP` network providers... However I have no idea what this thing is doing (google provides virtually nothing) so I was a bit reluctant to remove it. Changing the order however had no effect...

**Comment by 0x4a616e** [comment]
Unfortunatley I cannot get the logs with dbgview as I cannot enable debugging with bcdedit on that machine. I'm currently trying to find a separate unused notebook with which I can reproduce the issue to generate the logs. In the meantime, is there maybe any other information I could provide by less intrusive means?

**Comment by Liryna** [comment]
bcdedit is only if you want the kernel driver logs with a debug version. Here you only need the dokannp build on debug. Build one locally and replaced it on the target machine. You should then see the debug logs in DbgView of the dokannp.

**Comment by 0x4a616e** [comment]
Ok, got it! But you might not like it ;) It took me a bit longer since I wasn't sure it was working because I could not see a single thing in `DbgView`. Just to verify, I tested a different version of the application that used a network drive instead of a NTFS mount point and _then_ i was able to see log entries like

    00000028	8.24398232	[7492] NpGetConnection I:, 260	
    00000029	8.24410057	[7492] NpGetConnection I:, 40	
    00000030	8.28461647	[7492] NpGetConnection I:, 0	
    00000031	8.28481102	[7492] NpGetConnection I:, 28	
    00000032	8.31705284	[7492] NpGetConnection I:, 260	
    00000033	8.37127018	[7492] NpGetConnection I:, 0	
    00000034	8.37154675	[7492] NpGetConnection I:, 28	

So it looks like the debug logging was indeed working _but_ it didn't log a thing when the issue occurred. Does that mean, that `dokannp1.dll` was not used and thus is probably not the one that turned C: into a disconnected network drive? 

I also checked the Windows event log, but all i got was this: <img width="1025" alt="image" src="https://user-images.githubusercontent.com/5487722/73457104-6f8c7f00-4373-11ea-988e-532358207b01.png">

**Comment by Liryna** [comment]
Ah nothing about C :cry: ? Even a full log after restart (kill) of explorer shows nothing ? That not gonna be easy to track if not...
It might still be a third part that create this behavior

**Comment by 0x4a616e** [comment]
Restarting the explorer got me a bit more, but still no mentioning of C. Maybe this helps!
[explorer_restart.log](https://github.com/dokan-dev/dokany/files/4134618/explorer_restart.log)

**Comment by Liryna** [comment]
@0x4a616e Thanks will look at them!
In the mean time, are you or have you tried using an unc name?

**Comment by 0x4a616e** [comment]
@Liryna good guess! Using a UNC name like `\\?\C:\Users\Me\VFS` worked well and the C: drive was just shown as a regular drive. However this had the funny side effect that the entire path `C:\Users\Me\VFS` is now visible twice in the explorer (i.e. on C: i have now 2 folders named `Users` and so on...).

Further good news: I managed to get my hands on an unused notebook to smash on which I can reproduce the issue. So I can basically run all tests you need now. DbgView however did not show anything different there...

Is it possible that nothing of interest occurs in DbgView as the issue _only_ occurs when mounting is triggered during autostart (via Run key)?

Maybe as a site note: I also experienced AccessViolationExceptions on some machines when mounting the VFS during autostart with dokan-net but the same operation works well wenn the application is started manually. Do you think that might be related or is that some different issue?

**Comment by Liryna** [comment]
Yeah, UNC name should not have been optional in first place. Would you be able to use something like `\\myfs\fs1` this would avoid the double folder as you said.

Yes, regarding that with UNC name it works, it might not be a dokan issue but more that before we were providing a local path when all other were expecting a network path (normal expectation for a network device).

Does the `AccessViolationExceptions` also happens with UNC ?

**Comment by 0x4a616e** [comment]
Yes, all kinds of UNC names seem to work. It also works well when i mount the file system to a new drive letter like `e:`. The only issue seems to be with NTFS mount points.

Unfortunately I cannot test whether the `AccessViolationException` occurs with UNC names, but I know that it happens with drive letters too.

**Comment by Liryna** [comment]
@0x4a616e In summary you still have an issue with ntfs reparse point? You use network option with it?

**Comment by 0x4a616e** [comment]
Right. The only option I use is `DokanOptions.CurrentSession`, so no network option. If you think it helps I could e.g. give it a try with mount manager too.

**Comment by Liryna** [comment]
@0x4a616e Mount manager cannot be used with reparse point.
Could you just open a new ticket maybe with this issue you have?

**Comment by 0x4a616e** [comment]
A new ticket for this `AccessViolationException`? Sure, can do. Should i create it here or in dokan-net?

I tried to summarise all information i have for the current issue again here (sorry for the german output, but i guess the relevant part should be clear):

*cmd.exe*:

    C:\Program Files\Dokan\Dokan Library-1.3.0.1000>net use
    Neue Verbindungen werden gespeichert.


    Status       Lokal     Remote                    Netzwerk

    -------------------------------------------------------------------------------
             C:        \CenterDevice             Dokan1
    Der Befehl wurde erfolgreich ausgeführt.
    C:\Program Files\Dokan\Dokan Library-1.3.0.1000>dokanctl.exe /l
    Driver path: 'C:\WINDOWS\system32\drivers\dokan1.sys'
      Mount points: 1
      0# MountPoint: \DosDevices\C:\CD_Test\CenterDevice - UNC: CenterDevice - DeviceName: \Device\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}

*DbgView*:

    [7616] NPOpenEnum: dwScope 0x00000001, dwType 0x00000000, dwUsage 0x00000000, lpNetResource 0000000000000000
    [7616] NPOpenEnum: pCtx 00000161B87C74F0
    [7616] NPEnumResource: hEnum 00000161B87C74F0, lpcCount 0000000F72D8EEF0, lpBuffer 00000161B87E6800, lpBufferSize 0000000F72D8EF60.
    [7616] NPEnumResource: *lpcCount 0xffffffff, *lpBufferSize 0x1000, pCtx->index 0
    [7616] NPEnumResource CurrentSesstionID:1
    [7616] NPEnumResource nbRead:1
    [7616] NPEnumResource SesstionID:1
    [7616] NPEnumResource: RESOURCE_CONNECTED
    [7616] NPEnumResource: lpRemoteName: \CenterDevice
    [7616] NPEnumResource: Entries returned 1, dwStatus 0x00000000
    [7616] NPEnumResource: hEnum 00000161B87C74F0, lpcCount 0000000F72D8EEF0, lpBuffer 00000161B87E8820, lpBufferSize 0000000F72D8EF60.
    [7616] NPEnumResource: *lpcCount 0xffffffff, *lpBufferSize 0x1000, pCtx->index 1
    [7616] NPEnumResource CurrentSesstionID:1
    [7616] NPEnumResource nbRead:1
    [7616] NPEnumResource: Entries returned 0, dwStatus 0x00000103
    [7616] NPCloseEnum: hEnum 00000161B87C74F0
    [7616] NPCloseEnum: returns

*Windows event log*:

    Entered event start.
    Finding mount entry; lockGlobal = 0; mount point = \DosDevices\C:\CD_Test\CenterDevice.
    No mount entry found.
    Creating disk device; mount point = C:\CD_Test\CenterDevice; mount ID = 1l
    disk device name: \Device\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}; symbolic link name: \Do
    sDevices\Global\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}; mount point: \DosDevices\C:\CD_Te
    st\CenterDevice; type: 8
    SymbolicLink: \DosDevices\Global\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9} -> \Device\Volume
    {d6cc17c5-1734-4085-bce7-964f1e9f5de9} created
    Event start using mount ID: 1; device name: \Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}.
    Mounting disk device.
    Mounting volume using MountPoint \DosDevices\C:\CD_Test\CenterDevice device \Device\Volume{d6cc
    17c5-1734-4085-bce7-964f1e9f5de9}
    Finding mount entry; lockGlobal = 1; mount point = .
    Found entry with matching device name: \Device\Volume{d6cc17c5-1734-4085-bce7-964f1e9f5de9}
    Mount entry found: \DosDevices\C:\CD_Test\CenterDevice -> \Device\Volume{d6cc17c5-1734-4085-bce
    7-964f1e9f5de9}
    Mounting successfully done.
    Finished event start successfully
    Handle created before IOCTL_EVENT_WAIT for file (null)
    Handle created before IOCTL_EVENT_WAIT for file (null)
    Opened file with user mode dispatch blocked: \__drive_fs_keepalive
    Opened keepalive file from process 6476.
    Activating keepalive handle from process 6476.
    Mounting disk device.

**Comment by Liryna** [comment]
Ah I wasn't ever thinking at using network option with reparse point, what reason are you using this ?
Without the network option and the UNC, any issue ?

**Comment by 0x4a616e** [comment]
I don't use the network option, that is the point ;) The only option I use is `DokanOptions.CurrentSession`

**Comment by Liryna** [comment]
So you have an UNC but without network option, with current session flag and mount with a reparse point ?
I have difficulty to follow the choice of those options. I would understand a simple reparse point in a folder that only the current user has the right to access but the mix of all of this intrigues me.

**Comment by 0x4a616e** [comment]
No, I'm not using a UNC path. I'm trying to mount the VFS to `C:\CD_Test\CenterDevice`, with this exact path as shown in the logs. And yes, I'm using the current session flag so that it is only visible to the current user.

I just ran a test with using a UNC path and that resulted in the C: drive no longer being shown as disconnected network drive.

Also, I initially thought that the `C:` being shown as disconnected network drive only happens when the VFS is mounted via autostart, but that does not seem to be the case. When I manually start the application to mount the VFS, everything _seems_ to look normal until I restart the explorer. Then `C:` is shown as disconnected network drive again.

**Comment by Liryna** [comment]
Humm this is really weird the reparse point trigger an UNC discovery. It do not expect it to happen but I might be missing a point here. We need to look at what the link between both.

**Comment by 0x4a616e** [comment]
Ok, sorry for the confusion, I may have been using a UNC name after all... I was using the following method from dokan-dotnet:

    public static void Mount(this IDokanOperations operations, string mountPoint, DokanOptions mountOptions,
            int threadCount, int version, TimeSpan timeout, string uncName, ILogger logger = null)
        {
            Mount(operations, mountPoint, mountOptions, threadCount, version, timeout, uncName, 512, 512, logger);
        }

and i was using `mountPoint=C:\CD_Test\CenterDevice` _and_ `uncName=CenterDevice`. I'm sorry, but i think in my previous answers i may have confused using a UNC path for `mountPoint` with the `uncName` parameter. If i remove `uncName`, everything is well. Adding the UNC name again causes this issue on "some" machines (here I still couldn't find any pattern)...

I used the UNC name as my app also supports mounting the VFS as a network drive with a given drive letter. So maybe as a quick fix I can just remove the UNC name if I don't mount as a network drive.

If this is expected behaviour if an NTFS path is given as mount point _and_ a UNC name is provided, you may as well close this issue. Thanks again very much for your help!

**Comment by Liryna** [comment]
UNC name option should only be used on a network device 😢 
I might even patch it to disallow this option OR fix dokannp to support this reparse point.
But regarding your logs dokannp haven't received any request for C driver...so we might not be able to resolve it.

**Comment by 0x4a616e** [comment]
Maybe it would be an option just to ignore the UNC name if the network option is not set. Otherwise, it does not seem to do any good anyway... I still wonder why this issue only occurred on a handful of machines but after removing the UNC name, everything is working perfectly again 👍 I will have the notebook on which the C: drive appeared as disconnected network drive for a few more days. If there is any detail you'd be interested in, i'd be happy to provide it! Thanks again for your help!

**Comment by Liryna** [comment]
@0x4a616e any updates on this 😃 ?

**Comment by 0x4a616e** [comment]
@Liryna nothing new :) removing the UNC option for non-network drives worked well. So I'm not sure if it'd make sense to somehow enforce that (e.g. returning an error if this parameter combination is used) but other than that I don't think there's anything left to be done.

**Comment by Liryna** [comment]
Agree! There is already https://github.com/dokan-dev/dokany/issues/849
Thanks for your feedback 👍
