### ISSUE TITLE
After updated windows10 to 2020H1, dokany does't work

### ISSUE THREAD

**Issue by martines2018** [dokan-dev/dokany#872]
# Environment
 * Windows version:  win10 2020H1，build version 19041
 * Processor architecture:  X64
 * Dokany version:  1.3.1
 * Library type (Dokany/FUSE):  Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [X] I can always reproduce the issue with the provided description below.
  - [X] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
After updated windows10 to 2020H1, dokany does't work.  console terminated after I click a folder.

# Logs
Please attach in separate files: mirror [output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#mirrorfs), library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#get-logs).
In case of BSOD, please attach minidump or dump [analyze output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#crash-report-bsod).

**Comment by Liryna** [comment]
Hi @martines2018 ,

Do you have any logs to provide ?

**Comment by martines2018** [comment]
C:\dokan\x64\Debug>mirror.exe /d /s /r c:\test /l m
RootDirectory: c:\test
## Attempting to add SE_SECURITY_NAME privilege to process token ##
  success: privilege already present
Dokan: debug mode on
Dokan: use stderr
AllocationUnitSize: 512 SectorSize: 512
device opened
###QueryVolumeInfo -001
GetVolumeInformation: max component length 255
GetVolumeInformation: file system name NTFS
GetVolumeInformation: got file system flags 0x03e706ff, returning 0x0004000f
###Create 0000
CreateFile : c:\test\
  AccountName: administrator, DomainName: WINDOWS
        ShareMode = 0x7
        FILE_SHARE_READ
        FILE_SHARE_WRITE
        FILE_SHARE_DELETE
        DesiredAccess = 0x80
        FILE_READ_ATTRIBUTES
        FlagsAndAttributes = 0x200000
        FILE_FLAG_OPEN_REPARSE_POINT
        OPEN_EXISTING

CreateFile status = 0
###GetFileInfo 0000
GetFileInfo : c:\test\
        GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 16
        result =  0
  unknown type:54
        DispatchQueryInformation result =  c000000d
###GetFileInfo 0000
GetFileInfo : c:\test\
        GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 16
        result =  0
        FileStandardInformation
        DispatchQueryInformation result =  0
###GetFileInfo 0000
GetFileInfo : c:\test\
        GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 16
        result =  0
        FileBasicInformation
        DispatchQueryInformation result =  0
###Cleanup 0000
Cleanup: c:\test\

###Close 0000
Close: c:\test\

###Create 0001
CreateFile : c:\test\
  AccountName: administrator, DomainName: WINDOWS
        ShareMode = 0x3
        FILE_SHARE_READ
        FILE_SHARE_WRITE
        DesiredAccess = 0x100080
        FILE_READ_ATTRIBUTES
        SYNCHRONIZE
        FlagsAndAttributes = 0x200080
        FILE_ATTRIBUTE_NORMAL
        FILE_FLAG_OPEN_REPARSE_POINT
        OPEN_EXISTING

CreateFile status = 0
###GetFileInfo 0001
GetFileInfo : c:\test\
        GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 16
        result =  0
        FileStandardInformation
        DispatchQueryInformation result =  0
###Cleanup 0001
Cleanup: c:\test\

###Close 0001
Close: c:\test\

mounted: m -> \Volume{}
Mounted
###Create 0002
CreateFile : c:\test\
  AccountName: SYSTEM, DomainName: NT AUTHORITY
        ShareMode = 0x3
        FILE_SHARE_READ
        FILE_SHARE_WRITE
        DesiredAccess = 0x100080
        FILE_READ_ATTRIBUTES
        SYNCHRONIZE
        FlagsAndAttributes = 0x200080
        FILE_ATTRIBUTE_NORMAL
        FILE_FLAG_OPEN_REPARSE_POINT
        OPEN_EXISTING

CreateFile status = 0
###GetFileInfo 0002
GetFileInfo : c:\test\
        GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 16
        result =  0
        FileStandardInformation
        DispatchQueryInformation result =  0
###Cleanup 0002
Cleanup: c:\test\

###Close 0002
Close: c:\test\

###Create 0003
CreateFile : c:\test\
  AccountName: administrator, DomainName: WINDOWS
        ShareMode = 0x3
        FILE_SHARE_READ
        FILE_SHARE_WRITE
        DesiredAccess = 0x100000
        SYNCHRONIZE
        FlagsAndAttributes = 0x0
        OPEN_EXISTING

CreateFile status = 0
###GetFileInfo 0003
GetFileInfo : c:\test\
        GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 16
        result =  0
        FileStandardInformation
        DispatchQueryInformation result =  0
###QueryVolumeInfo 0003
GetVolumeInformation: max component length 255
GetVolumeInformation: file system name NTFS
GetVolumeInformation: got file system flags 0x03e706ff, returning 0x0004000f
###QueryVolumeInfo 0003
GetVolumeInformation: max component length 255
GetVolumeInformation: file system name NTFS
GetVolumeInformation: got file system flags 0x03e706ff, returning 0x0004000f
###Cleanup 0003
Cleanup: c:\test\

###Close 0003
Close: c:\test\

###Create 0004
CreateFile : c:\test\
  AccountName: administrator, DomainName: WINDOWS
        ShareMode = 0x0
        DesiredAcce###Create 0005
ss = 0x100000
CreateFile : c:\test\
        SYNCHRONIZE
  AccountName: administrator, DomainName: WINDOWS
        FlagsAndAttributes = 0x0
        ShareMode = 0x7
        OPEN_EXISTING
        FILE_SHARE_READ
        FILE_SHARE_WRITE

CreateFile status = 0
        ###GetFileInfo 0004
FILE_SHARE_DELETE
        DesiredAccess = 0x80
        FILE_READ_ATTRIBUTES
GetFileInfo : c:\test\
        FlagsAndAttributes = 0x200000
        FILE_FLAG_OPEN_REPARSE_POINT
        OPEN_EXISTING
        GetFileInformationByHandle success, file size = 0

FCreateFile status = 0
ILE###GetFileInfo 0005
 ATTRIBUTE  = 16
G       result =  0
e       FileStandardInformation
tF      DispatchQueryInformation result =  0
i###QueryVolumeInfo 0004
le###Cleanup 0004
Info : c:\test\
Cleanup: c:\test\

        ###Close 0004
G###Create 0006
etFileInformationByHandle success, file size = 0
Close: c:\test\

CreateFile : c:\test\
FILE ATTRIBUTE  = 16
        result =  0
        FileStandardInformation
A       DispatchQueryInformation result =  0
c###GetFileInfo 0005
countName: administrator, DomainName: WINDOWS
GetFileInfo : c:\test\
        ShareMode = 0x0
        GetFileInformationByHandle success, file size = 0
FILE ATTRIBUTE  = 16
                result =  0
D       FileNetworkOpenInformation
e       DispatchQueryInformation result =  0
sir###Cleanup 0005
edAccess = 0x100000
Cleanup: c:\test\

        ###Close 0005
S###Create 0007
YNCHRONIZE
Close: c:\test\

        FlagsAndAttributes = 0x0
        OPEN_EXISTING

CreateFile status = 0
###QueryVolumeInfo 0006
###Cleanup 0006
Cleanup: c:\test\

###Close 0006
###Create 0008
Close: c:\test\

CreateFile : c:\test\
  AccountName: administrator, DomainName: WINDOWS
        ShareMode = 0x3
        FILE_SHARE_READ
        FILE_SHARE_WRITE
        DesiredAccess = 0x100000
        SYNCHRONIZE
        FlagsAndAttributes = 0x0
        OPEN_EXISTING

CreateFile status = 0
###QueryVolumeInfo 0008
GetVolumeInformation: max component length 255
GetVolumeInformation: file system name NTFS
GetVolumeInformation: got file system flags 0x03e706ff, returning 0x0004000f
###QueryVolumeInfo 0008
GetVolumeInformation: max component length 255
GetVolumeInformation: file system name NTFS
GetVolumeInformation: got file system flags 0x03e706ff, returning 0x0004000f
###Cleanup 0008
Cleanup: c:\test\

###Close 0008
Close: c:\test\

C:\dokan\x64\Debug>

**Comment by Liryna** [comment]
Do you have a debugger to see if it is the mirror that crash or where in the dokan lib ?

**Comment by martines2018** [comment]
How to do it?

**Comment by Liryna** [comment]
Hi @martines2018 ,

I Installed latest dokan release on 20H1 insider preview. I tested multi things like open folder / read / write / copy files and everything looks to be working correctly.
Do you have any other information how to reproduce the issue ? Have you fully updated the version ?

**Comment by martines2018** [comment]
What‘s your windows build version?  The version I installed is 19041.113

**Comment by Liryna** [comment]
It is a fresh install of 19041.207 build.

**Comment by Liryna** [comment]
@martines2018 Could you share some steps for me to reproduce the issue ?

**Comment by Liryna** [comment]
@martines2018 let me know when you have a way to reproduce the issue.
