### ISSUE TITLE
The common installation failure problem of vc_redist_2019 in lower version systems such as win7

### ISSUE THREAD

**Issue by hefengliang** [dokan-dev/dokany#874]
At present, the downloadable installation package of DOKAN must be centrally deployed and installed vc_redist_2019, but vc_redist_2019 actually often fails to install on many systems lower than win10, which directly causes the installation of DOKAN to fail.
vc_redist_2019 is compatible with earlier versions of the system through a system patch ([reference document](https://docs.microsoft.com/en-us/cpp/windows/universal-crt-deployment?view=vs-2019))。
In the actual production environment, many systems work in an offline environment and cannot update system patches, and it is difficult to install accurate system patches for offline users, because system patches have many dependencies on each other and the patches corresponding to each system version Not the same,
Therefore, we cannot guarantee that all users have accurately installed the patches, which increases the difficulty of operation and maintenance.

I think the better solution is to use CRT local deployment and copy the dependent CRT dlls to the working directory. This can be implemented by third-party developers. What DOKAN needs is to provide an installer that does not depend on vc_redist_2019.
Removing the dependency on vs2019 CRT in Dokan_x64.msi Dokan_x86.msi DokanSetup.exe can give developers a more flexible CRT local deployment solution, instead of all installations having to rely on the centrally deployed vc_redist_2019.

Thank you for your work!

**Comment by Liryna** [comment]
@hefengliang Hi,

Have you looked at the possibility to directly use the binaries from the zip release?
They are signed and ready to be package in your own installer that can handle the CRT as you said.

Making the msi not dependent to CRT would not be logic as it need it to work.
The best solution is to change dokan library to fully remove the CRT dependency. It is doable but I do not have the time for it. If anyone would like to achieve it, that would be highly appreciated.

**Comment by hefengliang** [comment]
Using the files in the zip directly is feasible, but requires me to handle the system differences in the installer myself.
As you said, a better solution is to make Dokan independent of the CRT, which will help more people and make them feel relaxed.
This should be a very simple matter. It only takes a few minutes to modify the link options: from / MD to / MT.
dokan1.sys does not depend on the CRT.
Are there any omissions in my considerations?
I did some verification results:
================================================================
Dump of file dokan1.dll

File Type: DLL

  Image has the following dependencies:

    KERNEL32.dll
    USER32.dll
    ADVAPI32.dll
    SHELL32.dll

================================================================
Dump of file dokanctl.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    KERNEL32.dll
    SHELL32.dll
    dokan1.dll
     
================================================================
Dump of file dokanfuse1.dll

File Type: DLL

  Image has the following dependencies:

    KERNEL32.dll

================================================================
Dump of file mirror.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    KERNEL32.dll
    USER32.dll
    ADVAPI32.dll
    dokan1.dll
    ntdll.dll

================================================================

Dump of file dokannp1.dll

File Type: DLL

  Image has the following dependencies:

    KERNEL32.dll
    dokan1.dll

================================================================
Dump of file dokan1.sys

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    ntoskrnl.exe
    
================================================================

**Comment by hefengliang** [comment]
@Liryna HI:
Using the files in the zip directly is feasible, but requires me to handle the system differences in the installer myself.
As you said, a better solution is to make Dokan independent of the CRT, which will help more people and make them feel relaxed.
This should be a very simple matter. It only takes a few minutes to modify the link options: from / MD to / MT.
dokan1.sys does not depend on the CRT.
Are there any omissions in my considerations?
I did some verification results:
================================================================
Dump of file dokan1.dll

File Type: DLL

  Image has the following dependencies:

    KERNEL32.dll
    USER32.dll
    ADVAPI32.dll
    SHELL32.dll

================================================================
Dump of file dokanctl.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    KERNEL32.dll
    SHELL32.dll
    dokan1.dll
     
================================================================
Dump of file dokanfuse1.dll

File Type: DLL

  Image has the following dependencies:

    KERNEL32.dll

================================================================
Dump of file mirror.exe

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    KERNEL32.dll
    USER32.dll
    ADVAPI32.dll
    dokan1.dll
    ntdll.dll

================================================================

Dump of file dokannp1.dll

File Type: DLL

  Image has the following dependencies:

    KERNEL32.dll
    dokan1.dll

================================================================
Dump of file dokan1.sys

File Type: EXECUTABLE IMAGE

  Image has the following dependencies:

    ntoskrnl.exe

**Comment by Liryna** [comment]
Change the option is simple but being sure the library still work after it (if it build) is a longer I believe.
Have you tried to do it ?

**Comment by hefengliang** [comment]
We just need to remove the CRT dependencies, we don't need to remove all the dependent libraries.
Such as USER32.dll ADVAPI32.dll SHELL32.dll KERNEL32.dll ntdll.dll and so on, these are directly supported by the windows system.
The DOKAN library does not rely on other third-party dlls, so I think it only needs / MT, which should not have any impact on the function.

Only modified to compile Release win32 mirror.exe and dokan1.dll using / MT, I did some simple tests in a win7 64bit virtual machine:
1. Install DokanSetup_redist.exe.
2. Uninstall all VS runtime libraries in the system.
3. Remove dokan1.dll in SysWoW64.
4. Put win32 mirror.exe and dokan1.dll into the directory and execute the command: mirror.exe / r C: \ Users / l M:
5. I did some operations in the M drive and he seems to be running normally!

After changing to / MT, all projects except the sys project can be compiled by win 32 x64.

**Comment by Liryna** [comment]
@hefengliang That's nice if there is no issue at all! Could you try to make a PR to change Visual studio configuration for all Release / Debug version and change the installer? (I can take care of the installer later if you want)

**Comment by hefengliang** [comment]
@Liryna  I'm happy to do something for the cool DOKAN, and I will take the time to do the work later this weekend.
Hope DOKAN can be better!

**Comment by Liryna** [comment]
@hefengliang I will just close this issue as it turns to be the same than https://github.com/dokan-dev/dokany/issues/660 please lets continue on the other issue 👍
