### ISSUE TITLE
Manual installation doesn't work in windows 7, 10

### ISSUE THREAD

**Issue by samokhodkin** [dokan-dev/dokany#880]
I am trying to make a small silent installer, and so far with not much a success.
The installer is tested against windows 10 and 7 inside a virtual machine.
The windows versions are 
Windows 7 SP 1 version 6.1 build 7601 
Windows 10 version 1903 build 18362.239

My approach is the following. 

1. I take the files that I think to be relevant to a working directory:
  dokan.inf
  dokan1.sys
  dokan1.cat
  dokan1.cer
  dokan1.dll
  dokanctl.exe

 I have statically compiled the exe and dll files, so they don't require the VC++ runtime.

2. I copy the dokan1.sys to c:\windows\system32\drivers

3. from the working directory I run the command:
  dokanctl /i d

Both Windows 10 and 7 complain about missing signature.

Iterestingly enough, I have found a workaround to install the driver in win10. 
Using pnputil.exe I installed and then uninstalled the dokan.inf. After that the dokanctl.exe started to work too. In the win7 this method doesn't work, the system complains about the missing line in the inf.

I'm obviously doing something wrong, so the system cannot find the signature. But what is the correct procedure?

**Comment by Liryna** [comment]
Hi @samokhodkin ,

Did you rebuild the driver yourself ? If yes, you need to sign it correctly with a the proper certificate and for windows 10 submit the driver to Microsoft portal.
https://github.com/dokan-dev/dokany/blob/master/scripts/sign.ps1
https://github.com/dokan-dev/dokany/blob/master/scripts/build_installer.ps1#L19-L26
If you are not doing any changes to the driver, you can use the one from the release zip that are properly signed, if you do make changes do not forget to publish them according to the licensing.

On Win7 you need this patch https://github.com/dokan-dev/dokany/blob/master/dokan_wix/Dokan_x86.wxs#L118

**Comment by samokhodkin** [comment]
No, I didn't rebuild the driver. All the files, except dokan1.dll and dokanctl.exe, were taken from the dokan.zip on https://github.com/dokan-dev/dokany/releases/tag/v1.3.1.1000.

As I told, the system accepts the driver via pnputil.exe.  It seems the dokanctl.exe does it the wrong way. 

The fact is the instruction in the "Manual installation" section doesn't work. Or is not clear enough.

**Comment by Liryna** [comment]
@samokhodkin Dokanctl is used by the installer to activer the driver. https://github.com/dokan-dev/dokany/tree/master/dokan_wix/WiXCA/CustomAction.cpp
We would have more feedback if it wouldn't work on Win7/10

**Comment by samokhodkin** [comment]
I found the mistake. I used the dokan.sys from the x64/Release/Driver directory, but the right one is in the x64/Release/Driver/sys. I guess the first one doesn't contain a signature. 

In the windows 10 it now works ok.
Later I will try the KB3033929 patch for windows 7.

Thanks for feedback, Liryna.

**Comment by Liryna** [comment]
Thank you @samokhodkin Glad it work out for you
