### ISSUE TITLE
Invalid driver symbols

### ISSUE THREAD

**Issue by petrutlucian94** [dokan-dev/dokany#882]
The debug installer provides the wrong driver symbols [1]. The .pdb file that gets installed at "C:\Program Files\Dokan\Dokan Library-1.3.1\driver\dokan1.pdb" seems to provide the userspace dll symbols instead of the driver ones [2].

[1] https://github.com/dokan-dev/dokany/releases/download/v1.3.1.1000/DokanSetupDbg.exe
[2] https://pastebin.com/raw/BKs796Dr

**Comment by Liryna** [comment]
Hi @petrutlucian94 ,

Thank you for you report.
Indeed the wrong pdb was copied by the installer 🏆  . Here is the fix for the next version https://github.com/dokan-dev/dokany/commit/8cce5a6ae76ec9fdd2c66cc5293ba973d9912ea4 

If you are in need of the pdb now, they are in also in the zip release 👍

**Comment by petrutlucian94** [comment]
That's great, thanks for taking care of this on such a short notice.
