### ISSUE TITLE
Conflicting with anti-virus program

### ISSUE THREAD

**Issue by leochou0729** [dokan-dev/dokany#885]
Hello,
I try to mount a encfs drive with Dokany 1.3.1.1000 on Windows 10, but it hangs with only a drive letter in file explorer and the whole disk is not accessable.
These are the debug logs from user mode program and kernel driver.
[user_mode.log](https://github.com/dokan-dev/dokany/files/4480472/user_mode.log)
[kernel.log](https://github.com/dokan-dev/dokany/files/4480473/kernel.log)

I think it's very likely Dokan is conflicting with Symantec Endpoint Protection on my company computer.
I notice there are several similar issues already posted on Github, like this one:
https://github.com/dokan-dev/dokany/issues/698
https://github.com/dokan-dev/dokany/issues/843

I cannot find a way on the anti-virus side, even disabling the protection doesn't make any difference.
Is using windows mount manager the only known way to bypass anti-virus? If so, how can I do it for encfs?
The only fuse options I can find in source code are as follows:
```
-o umask=M             set file and directory permissions (octal)
-o fileumask=M         set file permissions (octal)
-o dirumask=M          set directory permissions (octal)
-o fsname=M            set filesystem name
-o volname=M           set volume name
-o uncname=M           set UNC name
-o setsignals=M        set signal usage (1 to use)
-o daemon_timeout=M    set timeout in seconds
-o alloc_unit_size=M   set allocation unit size
-o sector_size=M       set sector size
-n                     use network drive
```

Please correct me if I'm wrong. 
Or is there any other method I could try to solve this problem? Uninstalling symantec is not a option for me, because my company installs it on every machine. Thanks!

**Comment by Liryna** [comment]
Hi @leochou0729 ,

Yes, unfortunately antivirus behavior on dokan is out of our control.
Are you using the latest version of the antivirus ?
Have you tried to use the [mirror](https://github.com/dokan-dev/dokany/wiki/Use-Mirror-example) with and without the mount manager option ?
It is not sure the option would change the behavior in any ways regarding the log. The mount happens but the communication between userland and kernel is blocked by the antivirus.

**Comment by leochou0729** [comment]
Hi @Liryna 
I can start mirror.exe succesfully with and without /o option.
I notice the mirror drive is local disk by default.
When I use /m option, the mirror drive faces the same problem as encfs does.
When I use /o /m option, the mirror drive works with no problem.

AFAIK, the -o local option is not supported in Dokany. 
And using mount manager is also not supported for encfs.
Please correct me if I'm wrong.

**Comment by leochou0729** [comment]
Hi @Liryna 
I also tested encfs with -n option. The drive can mounted successfully.
I have no idea if there is any side effect to mount encfs as a network drive.
Another problem is that the -o volname doesn't have any effect if it's used with -n option, so I need to change the drive name manually in file explorer.

I also found that when encfs exits, file explorer doesn't always refresh its UI accordingly. 
The drive icon on the left pane will always be there until I reopen file explorer.

**Comment by Liryna** [comment]
@leochou0729 Indeed mount manager option cannot be used for now. Here is the patch to allow the option: https://github.com/dokan-dev/dokany/commit/c09d5ec5159aa07a4564d6dd9e20ad08f57648fe

If it is working with network option, there is no harm / difference to use it.
Regarding volname and network option, I do not really see how it could happen https://github.com/dokan-dev/dokany/blob/c09d5ec5159aa07a4564d6dd9e20ad08f57648fe/dokan_fuse/src/dokanfuse.cpp#L521

**Comment by leochou0729** [comment]
Thanks a million for your help! I will verify this patch ASAP and let you know. 
The network option has an annoying problem that there is a red cross icon on the drive after it is unmounted. The drive icon never disappear in file explorer. I cannot disconnect it in file explorer either. I think it's a normal windows behavior.

**Comment by leochou0729** [comment]
Hi @Liryna 
I've tested the patch and it works without any problem. ^_^
Can I just replace the dokanfuse1.dll on my computer? Does it work compatibly with other components in 1.3.1.1000? Thanks!

**Comment by leochou0729** [comment]
Hi @Liryna 
I notice the drive now shows its type as local disk and file system as encfs.exe. 
Is it a side effect using the mount manager?
If I use /o /m option with mirror.exe, file explorer can show its type as removable disk and file system as NTFS.
Is there a way to show the correct information for encfs? Thanks!

**Comment by Liryna** [comment]
There is no harm. I would maybe just say NTFS filesystem name is sometimes expected for some apps but otherwise it is fine as it is.

**Comment by Liryna** [comment]
@leochou0729 can the issue be closed if that solved for you ?

**Comment by leochou0729** [comment]
Hi @Liryna 
Sorry for the late reply. I have one more small question. Can I make the property window show correct file system by modifying encfs code? Is there a callback funtion for this purpose? Thanks!

**Comment by Liryna** [comment]
Yes, there is a callback to set the filesystem name. I prefer you ask encfs
as I prefer not recommand on I project I do not own.

Le mer. 22 avr. 2020 à 04:55, leochou0729 <notifications@github.com> a
écrit :

**Comment by Liryna** [comment]
Hi @leochou0729 ,

Can this be closed ?

**Comment by leochou0729** [comment]
Sure. Thanks a lot! @Liryna
