### ISSUE TITLE
Mount UNC without Drive letter

### ISSUE THREAD

**Issue by adropit** [dokan-dev/dokany#886]
# Environment
 * Windows version: 1809
 * Processor architecture: x64
 * Dokany version: 1.3.1.1000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [ ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Hello,

We are analyzing the Dokany library and would like to be able to mount an UNC path without having a drive letter for a network drive.
Something like:
mirror.exe /r C:\Dokan_tmp\ /u \MyFS\MyFS1

As you responded in issue #879 this is not possible in the current Dokany implementation and also is not a priority for now.

Could you provide more information about the files (methods) that need to be changed in order to make this possible? 
We would like to also analyze the possibility to implement it ourselves.

**Comment by Liryna** [comment]
Hi @adropit ,

I would be glad to talk about it, let's just keep to discussion in the first thread if you don't mind.
