### ISSUE TITLE
how to judge the dokan service whether is installed?

### ISSUE THREAD

**Issue by zxgm** [dokan-dev/dokany#888]
How to judge the dokan service whether is installed? Look up the C:\Program Files\Dokan install directory?And how to make sure the  dokan service that is installed work?

**Comment by Liryna** [comment]
you can execute the command `dokanctl /v` to get the driver version installed and running.

**Comment by Liryna** [comment]
@zxgm let me know this way is not enough for you and I will reopen the ticket.
