### ISSUE TITLE
fuse_win: convert_flags() incorrectly sets O_RDWR/O_WRONLY

### ISSUE THREAD

**Issue by c-klapaucius** [dokan-dev/dokany#89]
STANDARD_RIGHTS_WRITE and FILE_GENERIC_WRITE should not be part of ACCESS_WRITE.
The same applies to required_share().
STANDARD_RIGHTS_WRITE is "currently defined to READ_CONTROL" and is set for read operations.
FILE_GENERIC_WRITE contains STANDARD_RIGHTS_WRITE.
Thus, it's not currently possible to create read-only files with fuse_win.

**Comment by Liryna** [comment]
Hi @c-klapaucius ,
I understand the issue with this flags and the ability to create read-only files.
Since I am not a user of dokan fuse, could you provide a pull request with the appropriate changes tested ?

**Comment by Liryna** [comment]
Fixed with https://github.com/dokan-dev/dokany/pull/90
