### ISSUE TITLE
Samba share doesn't work after installing Dokany (using the installer)

### ISSUE THREAD

**Issue by KerberX** [dokan-dev/dokany#891]
# Environment
 * Windows version: Windows 10, 1909
 * Processor architecture: x64
 * Dokany version: 2.0
 * Library type: Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [ ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I installed Dokany long time ago and didn't really noticed the issue until now. I noticed that I can't open any SMB shares, either `\\localhost` or remote. I was getting this error:
![image](https://user-images.githubusercontent.com/32564546/80458058-ea484480-8938-11ea-9dc2-e89abb3cd65f.png)

I have found a solution here: <https://superuser.com/a/1391935>. Basically it says there is a wrong network adapter order in the registry listed in `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order`. It was `,Dokan2`, the default value is `RDPNP,LanmanWorkstation,webclient`. I restored the default, rebooted the PC and everything went back to working.

I assume the installer (I think) tried to add this value to the list but instead overwrote the entire list for some reason.

**Comment by Liryna** [comment]
Hi @KerberX ,

The value is normally correctly changed while keeping the current value. There is probably an issue with the code doing that in some case.
https://github.com/dokan-dev/dokany/blob/44c4a69a8cf2ac390d49ce9e87653340fc27bd79/dokan/mount.c#L303-L304

**Comment by KerberX** [comment]
Well, the buffer is certainly big enough to hold the default value. Is `DokanNetworkProviderInstall` called in every scenario or only when network provider option is used when mounting the FS?

**Comment by Liryna** [comment]
The function is only called at install time. `dokanctl /i n` is called by the driver here.
https://github.com/dokan-dev/dokany/blob/master/dokan_wix/WiXCA/CustomAction.cpp#L164-L165

**Comment by KerberX** [comment]
That's strange. I'm sure I didn't call this. Well, maybe there should be an error cheek for `RegQueryValueEx` call?

**Comment by Liryna** [comment]
The installer is doing it for, it should be made by user normally. `RegQueryValueEx` yes return code should be checked and maybe others too. I just expected it to work for you now and the failure might happen because of the previous content you have.

**Comment by KerberX** [comment]
Unfortunately I can't tell you what's been there before the issue. Maybe it's make sense to expand the `commanp` buffer to 1024?

For everything else I think this issue description can help other people to solve similar problems. I spent a few days trying to hunt this down.

**Comment by Liryna** [comment]
`commanp` just hold `,Dokan2`, 64 is enough. I only see more error check here and avoid corrupt the registry in case of failure.

**Comment by Liryna** [comment]
Check added https://github.com/dokan-dev/dokany/commit/89fe90b209d00418eb6f4603bffef7b28969b19a
It should be enough to not corrupt the user env. But if anyone see the behavior again, please let us know and we will try to see again about it.
