### ISSUE TITLE
Dokan not working after installation

### ISSUE THREAD

**Issue by mardy** [dokan-dev/dokany#897]
# Environment
 * Windows version: 8.1
 * Processor architecture: x64
 * Dokany version: 1.3.1.1000 (DokanSetupDbg_redist)
 * Library type (Dokany/FUSE): FUSE
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

After installing the DokanSetupDbg_redist package and rebooting, Dokan does not appear to have been properly setup:

```
C:\Program Files\Dokan\Dokan Library-1.3.1>dokanctl.exe /v
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
dokanctl : Dec 16 2019 15:59:55
Dokan version : 131
Dokan Error: Failed to open \\.\Dokan_1 with code 2
Dokan driver version : 0x0
```

I tried uninstalling and reinstalling it, but after reboot I'm left in the same state.

Mirror output:
```
C:\Program Files\Dokan\Dokan Library-1.3.1\sample\mirror>mirror.exe /d /s /r C:\Users /l m
RootDirectory: C:\Users
## Attempting to add SE_SECURITY_NAME privilege to process token ##
  success: privilege already present
Dokan: debug mode on
Dokan: use stderr
AllocationUnitSize: 512 SectorSize: 512
Dokan Error: CreateFile Failed \\.\Dokan_1: 2
Can't install driver
```

**Comment by Liryna** [comment]
Hi @mardy ,

Have you tried `DokanSetup_redist` ? the debug version is supposedly to work by configuring windows: https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#self-sign-build

**Comment by mardy** [comment]
Hi Liryna! No, I didn't try that, since I thought that the debug version would help me finding issues with my driver. Indeed, the lines from the Howto do fix the problem!

Maybe I just missed it and it's there already, but if not, it might be a good idea to add a note somewhere in the wiki that says that debug builds are not signed.

Anyway, sorry for the noise and thanks for the quick help! :-)

**Comment by Liryna** [comment]
Done! I added the line https://github.com/dokan-dev/dokany/wiki/Installation 👍
Thanks for your feedback
