### ISSUE TITLE
Installing from source instructions

### ISSUE THREAD

**Issue by suy** [dokan-dev/dokany#9]
Hi.

This is 50% question 50% feature request. :)  I promise that if I get the first 50% I'll send a pull request updating the docs.

I failed to install the driver by following the instructions coming from the original dokan repository. I compiled the project just fine by opening the solution in Visual Studio, but running "dokanctl.exe /i d" got me just an error. I ran with DebugView, and the error was:

 ```
[1912] Service (Dokan) installed
[1912] failed to start service (Dokan): 1275
[1912] Service (Dokan) start failed
```
Seems this error code is ERROR_DRIVER_BLOCKED ("This driver has been blocked from loading."). This isn't very helpful, and what I've found searching wasn't helpful either.

I ran the installer that you provide (thank you!) and it works. From the log it prints, I see it does more or less the same, so I don't know what could be different.

In a previous setup I got it to work, but it was the original dokan on Vista with WDK 7. Now it's Windows 8 with WDK 8 and dokany.

If you have any hints I would be very grateful, since I am going to use extensively some Dokan implementation, and being able to run something I've built myself could be quite important.

Thank you.

**Comment by Liryna** [comment]
Hi,

Did you sign the driver you have build with a valid certificate ?
or have you disable the Driver Signature Verification ?

**Comment by suy** [comment]
Ah, sorry I forgot to mention that: I didn't do anything to sign or not to sign. I saw in the generated files a test certificate, and on the properties of the driver says is signed. Given the certificate is just a test one, that might be the issue, right?

Thank you.

**Comment by Liryna** [comment]
It is exactly that :)

see; https://github.com/Maxhy/dokany/issues/8

**Comment by suy** [comment]
Well, it took me a bit to get everything right. The problem wasn't the driver signature verification (at least not only). I was using the default build configuration, which is 32 bits, while my OS is 64 bits. I still don't understand all the possible build configurations, but I got it to work.

I'll try to send a pull request with instructions for newbies like myself. :)

Thank you!

**Comment by Maxhy** [comment]
Closing this then, feel free to suggest any PR, any help will be highly appreciated ;)
