### ISSUE TITLE
dokanctl.exe crash when unmount in the environment where 360 antivirus software is installed

### ISSUE THREAD

**Issue by j1053803540** [dokan-dev/dokany#901]
# Environment
 * Windows version: win7/10
 * Processor architecture: x86
 * Dokany version: 1.3.1.1000
 * Library type (Dokany/FUSE): 
 
# Check List
  - [ ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [ ] I can always reproduce the issue with the provided description below.
  - [ ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
when "dokanctl.exe -u path" The following exception occurred 

![QQ图片20200601141402](https://user-images.githubusercontent.com/18157458/83380881-b79adb80-a411-11ea-9a43-f249f2a2ef1a.png)

# Logs
Please attach in separate files: mirror [output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#mirrorfs), library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#get-logs).
In case of BSOD, please attach minidump or dump [analyze output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#crash-report-bsod).

**Comment by Liryna** [comment]
Hi @j1053803540 

I just installed the latest 360 and tried to reproduce the issue but without success.
![image](https://user-images.githubusercontent.com/4311419/83387601-421d1400-a3ed-11ea-8414-e1337e654905.png)
Do you have any other information to share ?

**Comment by Liryna** [comment]
@j1053803540 let me know when you will get more information on this to reopen the ticket.
