### ISSUE TITLE
PVOID64 causes troubles when compiling with 32-bit MinGW

### ISSUE THREAD

**Issue by DDoSolitary** [dokan-dev/dokany#902]
I'm trying to use Dokan's user mode library with 32-bit MinGW gcc and encountered a strange issue:
The `SessionId` field of the `DOKAN_CONTROL` array returned by `DokanGetMountPointList` is always 0 even when `DOKAN_OPTION_CURRENT_SESSION` is set.

After some digging, I found out that the problem is caused by the `VolumeDeviceObject` field of `DOKAN_CONTROL`, which is defined as `PVOID64`.
MSVC defines `PVOID64` as `void * __ptr64` so it is always 64-bit long on whatever architecture, which is expected. However, MinGW simply defines `PVOID64` as `void *`, so it is 32-bit long when compiling for x86. (I also tried to add __ptr64 to a pointer but `sizeof` still return 4, so it seems that MinGW doesn't support __ptr64 properly.)
So, the kernel driver treats the pointer as a 64-bit one while my user mode application treats it as a 32-bit one. As as result, when trying to read `SessionId`, my application actually reads the higher 32 bits of `VolumeDeviceObject`, which has been deliberately set 0 by the driver.

A quick fix would be change the definition of `VolumeDeviceObject` to something like this:
```c
#ifdef _MSC_VER
  PVOID64 VolumeDeviceObject;
#else
  ULONG64 VolumeDeviceObject;
#endif
```
As the pointer is only dereferenced in the kernel driver, which is currently compiled with MSVC, this change won't produce any compilation errors. However, if someone wants to compile the driver with MinGW in the future, compilation will fail because ULONG64 is not a pointer and thus can't be dereferenced.

**Comment by Liryna** [comment]
Hi @DDoSolitary ,

Thank you for the detailed report! very appreciated 👍 
In fact, VolumeDeviceObject should never have been returned...
See https://github.com/dokan-dev/dokany/blob/1026b0f9ce73c64a700aa1dd5f14cfef61986494/sys/init.c#L601-L603

Do you think it might be possible to add a define in https://github.com/dokan-dev/dokany/blob/6424efd09d8efd5f1ae6622a6b4ef9be27d25153/dokan_fuse/include/fuse_win.h#L50 for overriding `PVOID64`  ?

**Comment by DDoSolitary** [comment]
> Do you think it might be possible to add a define in 

This is not very ideal because PVOID64 is a `typedef` rahter than `#define`, which can't be `#undef`ed, so compiler will complain about re-definition of PVOID64.

**Comment by Liryna** [comment]
Having PVOID64 as 32 bites is really weird. I do not believe this should be fixed on our side.  Is there any issue / ticket open at mingw ? If not, that might be interesting to know what is their opinion.

**Comment by DDoSolitary** [comment]
I couldn't find anything related in their bug tracker. However, I think it is pretty reasonable. First of all, __ptr64, which is used to implement PVOID64 under the hood, is a [Microsoft specific compiler extension](https://docs.microsoft.com/en-us/cpp/cpp/ptr32-ptr64) only available with the Visual C++ compiler and not gcc. The compiler provided by MinGW is basically gcc ported to Windows rather than re-implementation of Visual C++, so it doesn't support the __ptr64 extension. And without this extension, as far as I know, there isn't a way in C/C++ to create a 64-bit pointer in a 32-bit program (I guess that's why Microsoft decided to implement such a compiler extension). So there's only two choices left for the MinGW guys writing the Windows SDK headers: either make it a 64-bit integer or a 32-bit pointer. It seems that they chose the latter.

BTW, PVOID64 seems to be something undocumented and only used in few places in the Windows SDK headers. Googling "PVOID64 site:docs.microsoft.com" only returns 9 results and none of them contains documentation for PVOID64. So probably it should not be used by a third-party project in the first place.

**Comment by DDoSolitary** [comment]
What is pretty strange is that the MinGW gcc does recognizes __ptr64 as a keyword and compiles code with __ptr64 present successfully, unlike gcc on Linux simply reporting errors, but adding this keyword has no effect on size of pointers. Probably they just make this keyword a no-op.

**Comment by Liryna** [comment]
I imagine they support `int64_t` so they might have a way to have 64 bits variable working. Have you a link to their type definition to share ?

I do agree PVOID64 should not be used here and that might point. It is a kernel driver variable where such types are used and should not have been exported outside at first but I cannot do the change unless I break the API.

**Comment by DDoSolitary** [comment]
Yes, 64-bit variables do work but not 64-bit pointers in 32-bit programs. The special part of `void * __ptr64` compared to normal 64-bit variables is that it still behaves as a pointer (i.e. it can be dereferenced directly without converting it to a pointer).

Definition of __ptr64: https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-headers/crt/_mingw.h.in
Definition of PVOID64: https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-headers/include/winnt.h#l258

**Comment by Liryna** [comment]
Thank you @DDoSolitary for the deep look into this 👍 I endup agreeing with you and applied the changes your requested on your first post https://github.com/dokan-dev/dokany/commit/0db2fd2b4f4e0307a0d36070b633b68a50a966dd.

I also had the idea to create another function like `DokanGetMountPointListEx` to remove the field but that might just be for later.

Let me know if there is anything else I can do here.
