### ISSUE TITLE
FindFiles(): Letter case is ignored

### ISSUE THREAD

**Issue by infeo** [dokan-dev/dokany#904]
# Environment
 * Windows version: 10 Pro N 1909
 * Processor architecture: x64
 * Dokany version: 1.3.1.1000
 * Library type (Dokany/FUSE):  Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [-] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
By design Dokany also supports case sensitive filesystems (mainly because it is the devs task to implement the file system). Also by design, the developer can decide to implement only the function FindFiles() for file listing and let the dokan handle possible filtering/matching or implement the slightly more complex FindFilesWithPatterns and having the chance to use own filter expression.

But the first case does not always lead to the correct listing result. Looking at the direcotry listing base function `DispatchDirectoryInformation()` in `directory.c`, in case of a success, the retrieved file list is processed/filtered by the function `MatchFiles()`:
https://github.com/dokan-dev/dokany/blob/adc18b35097bd72322084086ab766592f51a1037/dokan/directory.c#L637-L639

The function contains the parameter `BOOL patternCheck`, which indirectly decides if the retrieved list is filtered by Dokany or not. If it is `TRUE`, every entry in the list checked if it matches this pattern:
https://github.com/dokan-dev/dokany/blob/adc18b35097bd72322084086ab766592f51a1037/dokan/directory.c#L410-L412

By knowing, that for every FindFiles() call `patternCheck` is set to `TRUE`, here one can see the bug for case sensitive file systems. The function `DokanNameIsExpression` has as a third parameter a boolean value deciding if the case of the search pattern is ignored or not. It is fixed to `TRUE`, therefore the case is always ignored.

# Suggested Solution
There are from my point of view two options:
## Option A: Change API

Change the definition of FindFiles() by add a pointer to a boolean value, which can be set.

Case sensitivity is inherently tied to the file system. One may think that changing the default behaviour to _not_ ignore the case is the way to go since it is more stricter, but this isn't the Windows way, where a lot of applications don't care about the letter case. Therefore one needs a way to tell Dokany to care about the case. And this could be done by exactly such a pointer.

## Option B: Update Docs
Update the documentation to make it clear that FindFiles() is kinda case insensitive.

Quick and easy fix, without breaking the current API. 😉 

# Logs
I tested this with the windows cmd shell and the case sensitive file system [cryptoFS](https://github.com/cryptomator/cryptofs). I created two directories (`test` and `Test`). each containing a file (`small.txt` and `big.txt`) and tried to navigate to both of them.
[cmd_output_buggy.log](https://github.com/dokan-dev/dokany/files/4737677/cmd_output_buggy.log)
[cmd_output_correct.log](https://github.com/dokan-dev/dokany/files/4737679/cmd_output_correct.log)

**Comment by Liryna** [comment]
Hi @infeo ,

In reality, dokan need more changes to clearly support case or non case sensitive option.
See https://github.com/dokan-dev/dokany/issues/839 the code is practically ready and I missed `FindFiles`! Thanks for reporting it!
I was waiting to finish MemFS to finish be able to make proposer testing.

The option set at mount to enable case or non case sensitive could be used to set the correct `DokanNameIsExpression` option.

**Comment by infeo** [comment]
> dokan need more changes to clearly support case or non case sensitive option
uhh, didn't knew about that. Guess i'm lucky that I didn't stumbled upon other case problems 😅 

> I was waiting to finish MemFS to finish be able to make proposer testing.
Oh, yes, that is a good idea. Testing case sensitivity with the mirror examples is kinda useless^^

> The option set at mount to enable case or non case sensitive could be used to set the correct DokanNameIsExpression option.
Yes, that is one possiblilty. Also thought about suggesting it,  but it would then be decoupled from the actual implementing filesystem which is represented by the DOKAN_OPERATIONS struct. (Your filesystem can be the one time case sensitive and the other not, depending on the mount options.)

**Comment by Liryna** [comment]
Closing it as duplicate with https://github.com/dokan-dev/dokany/issues/839
