### ISSUE TITLE
Reason for different handling of booleans

### ISSUE THREAD

**Issue by JaniruTEC** [dokan-dev/dokany#907]
I was looking at the definitions of _DOKAN_FILE_INFO and _DOKAN_ACCESS_STATE in order to fix https://github.com/dokan-dev/dokan-java/issues/46 for the dokan-java project. The defintions are linked below:
https://github.com/dokan-dev/dokany/blob/1694ff1e3ac0c73afc6327b70c825574b4159d80/dokan/dokan.h#L155-L185
https://github.com/dokan-dev/dokany/blob/1694ff1e3ac0c73afc6327b70c825574b4159d80/sys/public.h#L181-L193
I noticed that the definitions use different types to store boolean values. _DOKAN_FILE_INFO uses WCHARs/bytes and compares against 0 to determine if the flag is set; _DOKAN_ACCESS_STATE uses BOOLEANs. 
Is this intentional or just a matter of Dokany's history? Does it have to do something with the sys/user-layer?

**Comment by Liryna** [comment]
@JaniruTEC Hi,

Yes, that only dokan history reason. Also DOKAN_ACCESS_STATE is based on ACCESS_STATE that use BOOLEAN.
Anyway the logic had to be BOOLEAN usage from my point of view, might be a good idea to review it for 2.x.x

**Comment by JaniruTEC** [comment]
Hey, @Liryna.

Thanks for your quick answer. Reviewing this would be highly appreciated from the wrapper-project, I guess. 
Maybe handling this as a combined bitmask would be another option?

**Comment by Liryna** [comment]
I do not have an exact idea for now how it needs to look like. There is a ticket o

**Comment by Liryna** [comment]
Windows headers:
`typedef UCHAR BOOLEAN;`
`typedef int                 BOOL;`
`typedef unsigned char UCHAR;`

With `UCHAR` you are sure of the space used which is needed when the library is x86 and the driver is x64.
