### ISSUE TITLE
Mirror Library mount as local disk?

### ISSUE THREAD

**Issue by taducquang** [dokan-dev/dokany#908]
# Environment
 * Windows version: Server 2012 R2
 * Processor architecture: x64
 * Dokany version: 1.14.0
 * Library type (Dokany/FUSE): 

# Description
Im using mirror.exe and it works good but is there anyway to make it mount as local disk? Some softwares can't detect removable disks because they check disk drives (Like in Device Manager) instead of volume drives.
If there's any way to do it, please suggest for me. Thanks a lot.

**Comment by Liryna** [comment]
What are the mirror option you are using? Removable disk drive is a specific option to add.

Also try to use mount manager option /o it might be what you are look for.

**Comment by taducquang** [comment]
Im using this command as removable disk

mirror.exe /m /r C:\Users /l m

I tried with option /o and checked in disk drives of Device Manager but not found it.

**Comment by Liryna** [comment]
You need to remove the /m option and add /o. Both together are not compatible for now.

**Comment by taducquang** [comment]
I already tried that, its always working as usual but the problem like i said, its not recognized as local disk, you can go to hard drives section of Device Manager in Window to check, its not in there.

**Comment by Liryna** [comment]
@taducquang Yes, the disk will not show up here it is normal. The drive is not registered as a physical drive. What would you expect to be able there with it?

**Comment by taducquang** [comment]
If you say so, i guess there's nothing i can do to make it appears even as virtual disk. Okay i will close this. Thanks.

**Comment by DocMAX** [comment]
I know exactly what the author means. Some software "detect" that this is no local drive. We need an extra "fake" physical drive. Please reopen..

**Comment by Liryna** [comment]
@DocMAX Could you suggest what is actually needed here and what would be the impact?

**Comment by Liryna** [comment]
@DocMAX Dokan is a virtual drive. It has no physical drive attached to it and it is  part of the design.

If anyone is interested to implement a virtual physical driver, I am willing to reopen the issue but otherwise I do not believe this is feasible.

**Comment by taducquang** [comment]
I think RaiDrive did solve this but they meet some limitations when working with multithread when reading files.
Just for a reference.

P/S: Its paid software so no wonder they can did that.
