### ISSUE TITLE
Typo in Wiki

### ISSUE THREAD

**Issue by JaniruTEC** [dokan-dev/dokany#910]
I know it's minimal, but I don't have write-permission for the wiki, so I have to annoy you guys ;P

https://github.com/dokan-dev/dokany/wiki/Installation (line 57 of the MD file) states a file named "dokan.dll". I guess, you meant to write "dokan1.dl"

Alternatively you could add the wiki as sub-module to allow PRs; see: https://stackoverflow.com/a/6941730

**Comment by Liryna** [comment]
Thanks for noticing the mistake @JaniruTEC I made the change.
Not sure I would want to have the wiki as submodule for now but thanks for the tips, I wasn't aware of it!
