### ISSUE TITLE
In fuse, the read-only attribute setting of the file is invalid

### ISSUE THREAD

**Issue by hefengliang** [dokan-dev/dokany#911]
#658 Environment
 * Windows version: win10
 * Processor architecture: x86
 * Dokany version: 1.4.0
 * Library type (Dokany/FUSE):FUSE 
 
# Check List
  - [*] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [*] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [*] I can always reproduce the issue with the provided description below.
  - [*] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [*] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
 I use the following command line to start the fuse sample:
mirror.exe M:\ -d -odaemon _timeout= 60 -ovolname=test -ouncname=M:\ -ofsname=FS

I found that setting the doc file as a read-only attribute in FUSE would prompt "The function is incorrect." I copied a doc file with a read-only attribute to fuse, and I found that the read-only attribute disappeared.
Is FUSE not supporting this feature? Or is it a bug?

**Comment by Liryna** [comment]
Hi @hefengliang ,

The sample himself do not support the Win SetAttributes but the wrapper does allows you to handle them by implementing 
See 
https://github.com/dokan-dev/dokany/blob/4029f7a60b79a165c8f224dd96fb03f6495a4c26/dokan_fuse/src/fusemain.cpp#L850-L866

https://github.com/dokan-dev/dokany/blob/a164b057e2498dabf875f19ddddc640eeaf0ac9a/dokan_fuse/include/fuse.h#L450-L452

**Comment by hefengliang** [comment]
@ Liryna   Thank you very much for your reply, my question has been resolved
