### ISSUE TITLE
Dokan hangs when calling NtSetInformationFile with a large buffer

### ISSUE THREAD

**Issue by DDoSolitary** [dokan-dev/dokany#917]
# Environment
 * Windows version: Windows 10 build 20161
 * Processor architecture: x64
 * Dokany version: 1.4.0
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
If I pass a large input buffer to `NtSetInformationFile` and pass size of the buffer rather than `sizeof(FILE_XXX_INFORMATION)` to its `Length` parameter, Dokan will hang forever without returning anything. I'm not very sure about the exact minimum buffer size that triggers this bug, but it seems that it's approximately 32768 bytes. Normal NTFS drives can process such large buffers without errors.

# Logs
Mirror log: https://paste.ubuntu.com/p/YngkvrwNxJ/

**Comment by DDoSolitary** [comment]
Update: It seems that only some of the information classes trigger this bug. For example FileBasicInformation and FileDispositionInformation do, but FileRenameInformation doesn't.

**Comment by Liryna** [comment]
@DDoSolitary Thanks for your report very appreciated.

Do you have a code sample you could share which exactly produce the issue? I will try to take a look at it this week after you send it.

**Comment by DDoSolitary** [comment]
```C++
#pragma comment(lib, "ntdll.lib")

#include <Windows.h>
#include <winternl.h>

extern "C" NTSYSCALLAPI NTSTATUS NtSetInformationFile(
	HANDLE                 FileHandle,
	PIO_STATUS_BLOCK       IoStatusBlock,
	PVOID                  FileInformation,
	ULONG                  Length,
	FILE_INFORMATION_CLASS FileInformationClass
);

int main() {
	HANDLE h = CreateFile(
		L"Z:\\t",
		GENERIC_ALL,
		FILE_SHARE_READ,
		nullptr,
		OPEN_ALWAYS,
		0,
		nullptr
	);
	IO_STATUS_BLOCK sb = {};
	int size = 65536;
	void *info = malloc(size);
	memset(info, 0x00, size);
	auto stat = NtSetInformationFile(
		h,
		&sb,
		info,
		size,
		(FILE_INFORMATION_CLASS)13 // FileDispositionInformation
	);
}
```

Z: is drive mounted by mirror

**Comment by Liryna** [comment]
Thanks @DDoSolitary ! I have been able to reproduce and find a way to fix it but it is touching a piece of code that I am already planning to largely improve.
How have you faced this issue ? have you seen an app doing so ?
Do you think the fix can wait some time for me to finish the work ?

**Comment by DDoSolitary** [comment]
Well, I haven't seen any apps calling NtSetInformationFile in such a way practically. I encountered this issue when I was using the [filetest](http://www.zezula.net/en/fstools/filetest.html) utility to debug my memfs implementation in Rust. Therefore, I think it is not something urgent and it might be OK to wait for the large improvement.

**Comment by Liryna** [comment]
@DDoSolitary king to let you know I made a temporary fix until I will do the big changes that will avoid such case later.
