### ISSUE TITLE
Problems with uninstall/install

### ISSUE THREAD

**Issue by cheesyfries7** [dokan-dev/dokany#918]
# Environment
 * Windows version: Windows 10 Pro version 1909
 * Processor architecture: x64
 * Dokany version: 1.4.0.1000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I am using Dokany with Cryptomator and was having some problems when using Dokany for the mounted virtual drive, and I was told to try update the Dokany version I already had installed. So I uninstalled, then installed the new version (1.4.0.1000) via DokanSetup_redist.exe and did a restart

I still had some problems with Cryptomator/Dokany but came across this
thread: https://community.cryptomator.org/t/unable-to-mount-filesystem-win-10/5559/10 , which suggested to check if the certain files were deleted upon installation.

I tried to uninstall again, but it seems on my end I couldn't delete dokan1.sys in the Windows\System32\drivers folder.

I tried the following:
  * replacing it with another file
  * using Unlocker/Lockhunter programs to check if it was locked to any
    processes (there was none), also did their delete at startup option
    but it won't delete.
  * using CMD, checked to make sure I have ownership of the file and
    full control, I am the only user on the PC so I am the admin as well
  * Reboot in safe mode and tried normal delete, delete through CMD
  * Check registry for any entries related to dokany, delete, restart,
    try deleting dokany1.sys again

Eventually, I got to delete it by using the LockHunter program to rename the file and move it out of the drivers folder before deleting it.

Then I encountered my next problem - after restarting computer, using the same DokanSetup_redist.exe of the latest version, it does not want to install the files

- I click the .exe file, but there is no progress bar, it just instantly says it is finished installing
- When I check Program Files and Windows/System32 folder, none of the Dokany folders/ files are there
- Dokany shows up as installed in the control panel, and I can uninstall it again just fine (even though there is nothing there)
- I tried reinstalling it via Cryptomator as Dokany comes bundled with it but during installation, it says there is a newer version of Dokany installed, and it skips the installation (even though I do not have Dokany installed)

Not sure what is wrong here, hoping to get some help. Thanks

**Comment by Liryna** [comment]
@cheesyfries7 Hi,

Thanks for posting here!

The driver not being able to be removed was probably due to the service still running. Can you try if it still exists by running: net stop dokan1
This should fail since the file is removed. 

If the error is not about unknown service, will need to try to remove it using command line before trying to reinstall.

**Comment by cheesyfries7** [comment]
> 
> 
> @cheesyfries7 Hi,
> 
> Thanks for posting here!
> 
> The driver not being able to be removed was probably due to the service still running. Can you try if it still exists by running: net stop dokan1
> This should fail since the file is removed.
> 
> If the error is not about unknown service, will need to try to remove it using command line before trying to reinstall.

Hello, sorry am a noob - this is via CMD right? If so then it says: "The dokan1 service is not started."

**Comment by Liryna** [comment]
@cheesyfries7 Perfect so the service is still there. You can remove by running the command: sc delete dokan1

Will need to run it in a command line with admin rights.

**Comment by cheesyfries7** [comment]
> 
> 
> @cheesyfries7 Perfect so the service is still there. You can remove by running the command: sc delete dokan1
> 
> Will need to run it in a command line with admin rights.

Just did this and it was deleted. I tried reinstalling again via the redist exe file but it won't install still

**Comment by Liryna** [comment]
@cheesyfries7 Could you now share the installer log? There is normally a like for it.

**Comment by cheesyfries7** [comment]
> 
> 
> @cheesyfries7 Could you now share the installer log? There is normally a like for it.

How can I go about accessing and sharing the log? I just tried using [msiexec.exe](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/msiexec) but getting an error, tried it with both the redist.exe and the .msi installer
![Annotation 2020-07-23 004235](https://user-images.githubusercontent.com/68644291/88204133-738fbe80-cc7d-11ea-9ad1-265d659dcb70.jpg)

**Comment by Liryna** [comment]
@cheesyfries7 You get the same error with dokan 1.4.0.1000 redist? Direct at launch? That's weird. You turn on logs with /l* that is explained in the page you linked.

**Comment by cheesyfries7** [comment]
> 
> 
> @cheesyfries7 You get the same error with dokan 1.4.0.1000 redist? Direct at launch? That's weird. You turn on logs with /l* that is explained in the page you linked.

Yes, here is the log that is produced:

`=== Verbose logging started: 07/23/2020  21:10:14  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\WINDOWS\system32\msiexec.exe ===
MSI (c) (EC:60) [21:10:14:685]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (EC:60) [21:10:14:685]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (EC:C0) [21:10:14:699]: Resetting cached policy values
MSI (c) (EC:C0) [21:10:14:699]: Machine policy value 'Debug' is 0
MSI (c) (EC:C0) [21:10:14:699]: ******* RunEngine:
           ******* Product: C:\Users\....\Desktop\DokanSetup_redist.exe
           ******* Action: 
           ******* CommandLine: **********
MSI (c) (EC:C0) [21:10:14:701]: Note: 1: 2203 2: C:\Users\....\Desktop\DokanSetup_redist.exe 3: -2147286960 
MSI (c) (EC:C0) [21:10:14:702]: MainEngineThread is returning 1620
=== Verbose logging stopped: 07/23/2020  21:10:14 ===
`

**Comment by Liryna** [comment]
@cheesyfries7 Can you try with msiexec /i Dokan_x64.msi /l*v DokanLogFile.txt ?

**Comment by cheesyfries7** [comment]
> 
> 
> @cheesyfries7 Can you try with msiexec /i Dokan_x64.msi /l*v DokanLogFile.txt ?

It was able to run but it seems to be detecting an installation so I was only given the uninstall option, and I tried uninstalling it through there. Here is the log: [DokanLogFile.txt](https://github.com/dokan-dev/dokany/files/4970200/DokanLogFile.txt)

**Comment by Liryna** [comment]
@cheesyfries7 Oh so if it see it still install you will need to use one of the Microsoft tools that force removing apps in a wrong state. I do not remember the name and cannot Google now but you should easily find it yourself. Let me know if after the installation will pass.

**Comment by cheesyfries7** [comment]
> 
> 
> @cheesyfries7 Oh so if it see it still install you will need to use one of the Microsoft tools that force removing apps in a wrong state. I do not remember the name and cannot Google now but you should easily find it yourself. Let me know if after the installation will pass.

I used [Windows troubleshooter](https://support.microsoft.com/en-us/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed) which fixed the problem and was finally able to reinstall! Really don't know what happened there.

Installed Cryptomator right after but still having problems with vaults using Dokany :-( though I guess, that is a separate issue from this already. 

Many thanks for your help and patience!

**Comment by Liryna** [comment]
@cheesyfries7 No problem! Glad it got solved!
