### ISSUE TITLE
noob questions about Dokany

### ISSUE THREAD

**Issue by Busbar2297** [dokan-dev/dokany#919]
# Environment
 * Windows version: 10
 * Processor architecture: x64
 * Dokany version: 1.4.0.1000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I have very primitive questions regarding Dokany, I am starting in this and got some very basic questions:
- When you mount a virtual file system, where is it stored, in memory ?! or as a file on the file system, for example using the mirror example I can mount virtual file system as drive or on folder, but where are they stored ?! apologize if it is stupid.
- I tried to override the mirror example and prevent writing text files, I disabled change notifications on file create if the file is text and same for file create and file write, yet files are still being created on the mirror, am I missing something ?!

Thanks.

# Logs
Please attach in separate files: mirror [output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#mirrorfs), library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#get-logs).
In case of BSOD, please attach minidump or dump [analyze output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#crash-report-bsod).

**Comment by Liryna** [comment]
Hi @Busbar2297 ,

* Dokan create a virtual file system but the storage behind of this file system is let to the user implementation (Dokan API). Like the memfs will keep all the files into memory and the mirror will forward the request the another drive.
* To disable create of text file you simply need in CreateFile of the mirror to check the filename requested (*.txt) with a create event and return a `STATUS_ACCESS_DENIED`.

Hope this answer your question.

**Comment by Busbar2297** [comment]
Hi Liryna,
thanks for your quick response, I started to get it after a while, Now what I understood from the mirror example:
1- When you mount a path it is virtually mapped into the virtual FS, so it is not a clone, it is link a shortcut to it.
2- changes are not replicated, IMHO you see what was reflected on the original drive into the virtual FS, right ?!

speaking about preventing certain extensions using the mirror example, it worked fine apparently i needed to rebuild the project in VS somehow, but I can see that actions are denied on the virtual FS not the actual FS, what if I want to modify read/write operations on the original FS without mounting a virtual FS, is it doable, or this is where the minifilters come into play ?!

Thanks.

**Comment by Liryna** [comment]
@Busbar2297 Yes the mirror is just a link even if a prefer to say that it replays the action. When a user or software do a CreateFile, the dokan API CreateFile is called and in the implementation we replay this CreateFile with the same parameters and return the status.
The mirror do not subscribe to the original drive changes yet (that would be a great contribution!) so if you change something in the origrinal drive, you will not see it in the mirror unless you refresh the view. Just to be clear again, this is the mirror limitation and not Dokan limitation.

About your last question, yes thats where the minifilters comes into play :) Dokan cannot answer this need.

**Comment by Liryna** [comment]
@Busbar2297 let me know if you need further information and I will reopen the ticket.
