### ISSUE TITLE
Socket creation failed using an executable with Dokan

### ISSUE THREAD

**Issue by EpsilonXX** [dokan-dev/dokany#92]
Hi,

I'm wondering if anyone succeeded to run an executable with socket creation using Dokan.
I got the error 10022 using socket(AF_INET,SOCK_STREAM,0) like reported at 
https://code.google.com/p/dokan/issues/detail?id=226.

I ran mirror with different options without a chance.
Do you have any ideas how to fix it ?

Best regards , 
EpsilonXX

**Comment by Maxhy** [comment]
This should be handled with #47 and #50 according to the following discussion https://www.osronline.com/showthread.cfm?link=250353

**Comment by Maxhy** [comment]
@EpsilonXX mount manager branch with correct file system registering was merged. Your issue should now be fixed, could you confirm?

**Comment by Liryna** [comment]
The release with the possible fix: https://github.com/dokan-dev/dokany/releases/tag/v1.0.0-BETA1

**Comment by EpsilonXX** [comment]
Hi guys,

I've just tried the new version but got the same error,could you check with this sample?
Run mirror and call the testDokanSocket.exe from dokan,if everything is ok you should get 
"socket succeeded: xx"

[testDokanSocket.zip](https://github.com/dokan-dev/dokany/files/86466/testDokanSocket.zip)

Thx

**Comment by Maxhy** [comment]
Indeed... I thought that filter manager would attach itself to the device with the latest changes but it is not the case. This is outside by knowledge now, any help would be appreciated...

**Comment by Maxhy** [comment]
Mhh this is because of DokanInitVpb on DokanCreateDiskDevice (https://github.com/dokan-dev/dokany/blob/c4a0ae2c8620cdbeeb4c6b0297e983d4eb7a711a/sys/init.c#L938) I believe.
Vpb initialization should now only be done on IRP_MN_MOUNT_VOLUME, now that the file system is correctly registered. I'm gonna fix that later.

**Comment by Maxhy** [comment]
Fixed thanks to everybody. You can build yourself to test it or wait for the next beta in the coming days.
