### ISSUE TITLE
Add an option to bypass share access restrictions when mirroring

### ISSUE THREAD

**Issue by szmarczak** [dokan-dev/dokany#922]
So the original directory can be freely modified.

For now I just build the `mirror` example and replace

https://github.com/dokan-dev/dokany/blob/1eb62bb1736a22ae2d3bae1defa045a008016774/samples/dokan_mirror/mirror.c#L459

with

```c
 FILE_SHARE_READ | FILE_SHARE_WRITE,
```

**Comment by Liryna** [comment]
Hi @szmarczak ,

The goal of the mirror is to forward the kernel request to a mirrored folder and keep the value as they are.
The sample help the community to learn using the Dokan API and adapt them with their specific needs as you did.

Let me know if you have a specific reason I am missing here.
