### ISSUE TITLE
Cannot save file with Microsoft Photo on network drive

### ISSUE THREAD

**Issue by phobeus** [dokan-dev/dokany#925]
# Environment
 * Windows version: 10 (version 1909)
 * Processor architecture: x64
 * Dokany version: 1.3.1.1000 (release)
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
When saving files from Microsoft Photos onto a network drive, it reports an error. The written file is unreadable. The attached log tried to save a test.jpg file.

# How to reproduce
- Run dokan mirror in network mode: mirror.exe /r C:\tools /l Y:\ /n /s
- Run Microsoft Photo and open any file
- Edit the file with "Draw" or something and hit "Save"
- Choose the path in the dokan drive (Y:\)
- An error message is shown: "It looks like you don't have permission to save changes to this file."
- The written file cannot be opened. Seems corrupted?

# Logs
[dokanoutput.log](https://github.com/dokan-dev/dokany/files/5125724/dokanoutput.log)

**Comment by phobeus** [comment]
I thought at first, it was an issue with the temporary hidden file being created, but I wasn't able to reproduce it with only creating a hidden file in the container.

**Comment by Liryna** [comment]
@phobeus Hi,

So does it directly work when not using /n option ? have you tried by adding /o ?

**Comment by phobeus** [comment]
Hi @Liryna thanks for the quick reply :-)

Yes, it works without the /n option. It does not work with /o (although, /o only works without /n)

**Comment by Liryna** [comment]
@phobeus would you be able to use procmon and log the activity of the app ? Share the output
I have difficulty to see in the log what exactly failed. Looks like the test.jpg is moved to test.jpg~RF17058f28.TMP than a new file ~est.tmp is created and write with the new content I imagine that end up being move to test.jpg.
Later open to test.jpg fails with `ERROR_ACCESS_DENIED`

**Comment by phobeus** [comment]
The target file name for the log was testing.jpg.
[Networkdrive_Dokan_Save_Photos.zip](https://github.com/dokan-dev/dokany/files/5127792/Networkdrive_Dokan_Save_Photos.zip)

I ran the mount with `.\mirror.exe /r C:\tools /l Y:\ /s /n`

**Comment by Liryna** [comment]
@phobeus Thanks!
OK I see the issue and have been able to reproduce. The file seems like to have incorrect security informations that creates the access denied (read permission is missing).

When using network device, it should always be used with a UNC /u \myfs\dokan1 and in this case, it solves the issue on my side. Can you give a try with a UNC ?

**Comment by phobeus** [comment]
Providing the UNC solves the problem, yes. In both cases, with /o or /n.
I also tested this when mounting to a folder instead of a drive.
Thanks for the quick reply.

**Comment by Liryna** [comment]
No problem! Glad it worked out.
