### ISSUE TITLE
Can't open EXE file on Virtual Drive by Dokan

### ISSUE THREAD

**Issue by alexlozdev** [dokan-dev/dokany#929]
I tested virtual drive by Dokan on the windows explorer.
- Image files (JPEG, GIF, PNG) ok to open on virtual drive
- video files (avi, mpeg4) ok to open on virtual drive
- office files (word, ppt, excel) ok to open on virtual drive.
- Exe files : I can't open Exe files on virtual drive on Windows explorer. 

Windows 10 x64
Dokan library 1.4.0

When double-clicking exe file on windows explorer, this no-responding state keeps for 30 seconds
![2](https://user-images.githubusercontent.com/68958931/94242765-27ab0100-fedc-11ea-9871-dda041fd9849.png)

after that, it displays next error
![3](https://user-images.githubusercontent.com/68958931/94242788-2ed20f00-fedc-11ea-8981-9eae3670ffe4.png)

My Question is 
- Does the Dokan library support the Exe- Executing?
- if support exe-executing, what is the error reason? (I checked it for all exes I have)
- if not support , Is there a way to fix?

**Comment by KerberX** [comment]
How do you open the .exe, from the Windows Explorer on a virtual drive using the mirror sample?

**Comment by Liryna** [comment]
@alexlozdev Agree with Kerbex, we need more details here. Exe does work but if you are hitting a special case we need your guidance to investigate.

**Comment by alexlozdev** [comment]
It sounds interesting. I am going to open(double clicking) a exe file on the virtual drive by dokan from windows explorer. 
All types of files works like original(before mounted) on virtual drive mounted by dokan, but I can execute the exe file on it.
Is it clear?

**Comment by Liryna** [comment]
@alexlozdev No we need to know how you test, what the platform and version you are using and logs. Also the exe you try to start.

**Comment by alexlozdev** [comment]
Windows 10 x64
Dokan1.4.0
![1](https://user-images.githubusercontent.com/68958931/94239201-101d4980-fed7-11ea-89db-9745fa93bc46.png)

**Comment by Liryna** [comment]
@alexlozdev The app you want to start need admin rights, does the filesystem you are running also has the admin rights?

**Comment by alexlozdev** [comment]
[Run as Administrator] also display same error.
So, Dokan supports the Exe File Executing on virtual Mount drive in any case?

**Comment by Liryna** [comment]
@alexlozdev Dokan support exe yes.

**Comment by alexlozdev** [comment]
I didn't failed to executing for all exe file. I tested it by mirror.exe(sample project in git)

**Comment by Liryna** [comment]
@alexlozdev When you created the issue there were explanations how to properly report an issue for us to look into it. Please edit your first message with the text and the informations. Until that, we have no way to help you further.

**Comment by alexlozdev** [comment]
I edited first message

**Comment by Liryna** [comment]
Thanks! Please try with `/o` mount manager option. It might help by looking at the error message.

**Comment by alexlozdev** [comment]
Same error displays and Can't any log
![3](https://user-images.githubusercontent.com/68958931/94249144-16b2bd80-fee5-11ea-8db7-d22f4c4adfd6.png)

**Comment by Liryna** [comment]
@alexlozdev Could you provide the procmon (see wiki debug section ) logs during the moment you try to open the exe?

Also you can try to use memfs and copy the binary in it and try to exec from it. It might be good to see if that a mirror issue.

**Comment by alexlozdev** [comment]
[test3.zip](https://github.com/dokan-dev/dokany/files/5282172/test3.zip)
This is the zip of log file which I captured by procmon

**Comment by alexlozdev** [comment]
Did you check if it is possible to open any exe file on the virtual drive by dokan.
if it is possible, will you send me the exe file name or link?

**Comment by KerberX** [comment]
Dokany does support .exe files. It may not support some special cases involving them. Like the one I described in #650 (probably has something to do with memory mapping), but it shouldn't be the case for you since the VFS process (mirror) and the process that starts your .exe (Windows Explorer) are different.

**Comment by alexlozdev** [comment]
I have never seen the exe opening on virtual drive by dokan.
I tested it to open exe files on virtual drive by dokan on windows explorer.
Is this special case? then Will you let me know the normal case to open the exe on virtual drive?

**Comment by Liryna** [comment]
![image](https://user-images.githubusercontent.com/4311419/94358475-8b325b80-00a1-11eb-8a4e-d65f2ed0079d.png)
Just tried procmon & SlackSetup from  the mirror. Both work perfectly. Slack end up closing after the auto install finish.
Added process explorer to show both were executed from explorer inside M:\

I also do not seen any error in your procmon logs.
Are you using a 100% clean environment (fresh install) to test ? Or there is some other apps that could create this behavior like antivirus / mini filters ?

**Comment by alexlozdev** [comment]
Thanks for your help.
I reinstalled the window10 system again. 
After dokan library 1.4.0 , I did the test again.
I succeed to open the exe inside the virtual drive by dokan.

I checked that Dokan supports Exe opening.
If I find the reason of issue (not opening exe), I will upload it.

**Comment by Liryna** [comment]
@alexlozdev Awesome! Yes please let us know and we will see if we can do something about it.
