### ISSUE TITLE
DokanError: Ioctl failed with code 87

### ISSUE THREAD

**Issue by dhmWh** [dokan-dev/dokany#936]
# Environment
 * Windows version: Windows Server 2019 Standard
 * Processor architecture: intel x86 
 * Dokany version: 1.4.0.1000 Bundle
 * Library type (Dokany/FUSE): Dokany

# Description
The following error occurred when opening the file：
DokanError: Ioctl failed with code 87
IOCTL_GET_ACCESS_TOKEN failed
DokanOpenRequestorToken failed

**Comment by Liryna** [comment]
Hi @dhmWh ,

Need more context and information here. Logs? What was used? How to reproduce?

**Comment by dhmWh** [comment]
Hi @Liryna,
 This is the parameter:  /l G:  /t 1 /d /s /r D:\fenqu1
Before this error occurred, I read a file called "2020" (this file is in the CD library). I need to wait for the robot to grab the CD to the CD drive and mount it in the CreateFile function before returning. The waiting time is about 20s.
###Create 1241
CreateFile : D:/fenqu1/DM-SMS-V2-TEST/2020
DokanError: Ioctl failed with code 87
IOCTL_GET_ACCESS_TOKEN failed
  DokanOpenRequestorToken failed
        ShareMode = 0x7
        FILE_SHARE_READ
        FILE_SHARE_WRITE
        FILE_SHARE_DELETE
        DesiredAccess = 0x120089
        FILE_READ_DATA
        FILE_READ_ATTRIBUTES
        FILE_READ_EA
        READ_CONTROL
        SYNCHRONIZE
        STANDARD_RIGHTS_READ
        STANDARD_RIGHTS_WRITE
        STANDARD_RIGHTS_EXECUTE
        FlagsAndAttributes = 0x8200000
        FILE_FLAG_SEQUENTIAL_SCAN
        FILE_FLAG_OPEN_REPARSE_POINT
        OPEN_EXISTING
CreateFile status = 0
###Create 1242
CreateFile : D:/fenqu1/
DokanError: Ioctl failed with code 87
IOCTL_GET_ACCESS_TOKEN failed
  DokanOpenRequestorToken failed
        ShareMode = 0x3
        FILE_SHARE_READ
        FILE_SHARE_WRITE
        DesiredAccess = 0x100001
        FILE_READ_DATA
        SYNCHRONIZE
        FlagsAndAttributes = 0x0
        OPEN_EXISTING

CreateFile status = 0
###Create 1243
CreateFile : D:/fenqu1/DM-SMS-V2-TEST/2020
DokanError: Ioctl failed with code 87
IOCTL_GET_ACCESS_TOKEN failed
  DokanOpenRequestorToken failed
        ShareMode = 0x7
        FILE_SHARE_READ
        FILE_SHARE_WRITE
        FILE_SHARE_DELETE
        DesiredAccess = 0x80
        FILE_READ_ATTRIBUTES
        FlagsAndAttributes = 0x200000
        FILE_FLAG_OPEN_REPARSE_POINT
        OPEN_EXISTING
CreateFile status = 0
###Create 1244
CreateFile : D:/fenqu1/
DokanError: Ioctl failed with code 87
IOCTL_GET_ACCESS_TOKEN failed
  DokanOpenRequestorToken failed
        ShareMode = 0x3
        FILE_SHARE_READ
        FILE_SHARE_WRITE
        DesiredAccess = 0x100000
        SYNCHRONIZE
        FlagsAndAttributes = 0x0
        OPEN_EXISTING

CreateFile status = 0
###Create 1245
CreateFile : D:/fenqu1/
  AccountName: Administrator, DomainName: WIN-KS5TODRR757
        ShareMode = 0x3
        FILE_SHARE_READ
        FILE_SHARE_WRITE
        DesiredAccess = 0x100000
        SYNCHRONIZE
        FlagsAndAttributes = 0x0
        OPEN_EXISTING

CreateFile status = 0
###Create 1246
CreateFile : D:/fenqu1/
  AccountName: Administrator, DomainName: WIN-KS5TODRR757
        ShareMode = 0x3
        FILE_SHARE_READ
        FILE_SHARE_WRITE
        DesiredAccess = 0x100000
        SYNCHRONIZE
        FlagsAndAttributes = 0x0
        OPEN_EXISTING

CreateFile status = 0

**Comment by Liryna** [comment]
Thanks. The other CreateFile do not have this error after right?
It is possible that the CreateFile is no longer valid because you are waiting 20 seconds which is too long for the system.

Could you not wait that the CD is in place before actually mounting the mirror?
Otherwise you can call dokanresettimeout function in the CreateFile until the CD is ready but I would not suggest that.

**Comment by dhmWh** [comment]
Thank you@Liryna ，
There is no problem with the other CreateFile. Our use scenario is like this, the files are stored on the CD, we have a lot of CDs, but there are only two CDs. When users read the files, they find the CD where the files are located through the database, and then grab the corresponding CDs and put them into the CD drive through the manipulator, so there must be a delay in this process. Do you have any good solutions over there?

**Comment by Liryna** [comment]
@dhmWh The failure of this command is not important in your case. So you can ignore it but if you see more of such requests failing and especially more important like CreateFile, I would suggest to use dokanresettimeout until you get your CD available.

Mounting the drive when all the resources are ready would be of course à better solution.
