### ISSUE TITLE
On 64-bit Windows, Dokan Library does not get removed from Programs and Features after uninstall

### ISSUE THREAD

**Issue by ech0matrix** [dokan-dev/dokany#94]
I'm running Windows 7 64-bit SP1. After I run DokanInstall_0.8.0.exe (this is RC1), I see that it successfully adds an uninstaller entry to Windows' Programs and Features. However, when I run the uninstaller, the entry remains after Dokan has been uninstalled. If I click the uninstall option a second time, Windows will report an error message and remove the entry if I click Yes.

When Dokan is installed, I looked through the registry, and I see the entry in: HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\DokanLibrary

Out of curiosity, I moved the entry to the 32-bit hive:
HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\DokanLibrary

Now when Dokan uninstalls, it actually successfully removes the entry. So it appears that on 64-bit Windows, the install is running in a 64-bit context, but the uninstall is running in a 32-bit context (and fails to remove the 64-bit registry keys). The fix would be for the install and uninstall to reference the same registry keys. This being 64-bit Windows, ideally in the 64-bit hive of the registry.

As a work around, I wrap the launch of the installer from a 32-bit application, and it runs with the 32-bit context and the keys go into the 32-bit registry. Then when I run the uninstaller from Programs and Features, the registry keys are successfully removed and Dokan Library removed from the list of installed programs.

**Comment by Liryna** [comment]
Fixed with RC2 https://github.com/dokan-dev/dokany/issues/78
