### ISSUE TITLE
Physical disks use Dokan

### ISSUE THREAD

**Issue by pykernel** [dokan-dev/dokany#941]
I have a physical disk that provides a read and write interface。
How to use Dokan to develop file systems for it?
I user  python language.
Thans!

**Comment by Liryna** [comment]
@ostester If you look at the wiki there is a python library that wrap the dokan API.
I cannot say if Dokan can answer your need. This depends on the API of your physical disk.

**Comment by ostester** [comment]
> @ostester如果您查看维基，则有一个包装dokan API的python库。
> 我不能说道康能否满足您的需求。这取决于物理磁盘的API。
Thanks, I read the wiki, but it only says which interface to call, but I don't know how to use it in Python

**Comment by Liryna** [comment]
Here is the API https://github.com/PyFilesystem/pyfilesystem

**Comment by pykernel** [comment]
> 这是API https://github.com/PyFilesystem/pyfilesystem



> 这是API https://github.com/PyFilesystem/pyfilesystem

Thank you. I saw the pyfilesystem library. I need to study it carefully because I don't understand how to call a physical disk storage unit.
