### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by yule-sun** [dokan-dev/dokany#942]
I dowanload dokan.zip & DokanSetup-noVC.exe , and install on my Windows Server 2012R2 system .Nothing happens after DokanSetup-noVC.exe is installed, I don't know how to use it.
And then  I installed dokan.zip according to this step：
First, copy the driver file dokan1.sys to %WINDIR%\system32\drivers that can be found in x64\Release\Driver\dokan1.sys for x64 Windows system.
Then copy Dokan Library dokan1.dll and Dokan Network Provider dokannp1.dll from x64\Release to %WINDIR%\system32 so it can be called globally by any application (otherwise you will have to put it side-by-side to your application).
Move to x64\Release, then install Dokan driver with dokanctl.exe /i d and Dokan network provider with dokanctl.exe /i n if you want to mount network drive.

 I got an error like this,oops. So is it necessary to build before performing the above steps? Is there an easy way to install it?

PS C:\dokan\Release> .\dokanctl.exe /i d
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
Installing driver...
DokanServiceInstall: Failed to install service (Dokan1). error = 1072
Driver install failed

Looking forward to your reply.

**Comment by Liryna** [comment]
@yule-sun You only need to run one installer to have Dokan installed. The zip version is if you want to only have the binaries to integrate them into your installer for example.

After the installation you have the driver installed and you are ready to run the mirror (sample) and develop your own filesystem if you need.

**Comment by yule-sun** [comment]
Thank you very much for your reply, Do you mean I need to download the file from the link below and then install it?
dokan-noVC.zip
https://github.com/dokan-dev/dokany/releases/download/v1.4.0.1000/dokan-noVC.zip

Because the download speed of the above file is too slow, I downloaded the following file.
DokanSetup-noVC.exe
https://github.com/dokan-dev/dokany/releases/download/v1.4.0.1000/DokanSetup-noVC.exe

After installation,  I received an error as below when i run the command mirror.exe. Do I need to install the cygwin program on my computer?
![image](https://user-images.githubusercontent.com/37107125/99021354-751e2300-259b-11eb-9353-e16cebc7e08a.png)

In addition, I have another question, I hope you don’t bother me. I did not find where to configure the ceph.conf file, so I don’t know how to connect to the ceph cluster，Request your help?

**Comment by Liryna** [comment]
@yule-sun Ah you are looking to install dokan for a ceph project that use dokan. You should look with them what file from dokan you need to install and how to configure it.

Here it is Dokan project and I will not be able to help you for ceph.

**Comment by yule-sun** [comment]
Uh, maybe my English description is not very clear, I mean how to use this project to map the cephfs file system. I think this project can do this. After all, it is so powerful, but I don't know how to use it.

**Comment by Liryna** [comment]
@yule-sun If you want to make the implementation for ceph you need to choose which API you want to use that is offered by Dokan. I would suggest the Dokan API and not the fuse one if you can build directly with Visual studio.

Cygwin or mingw is only needed if you use the fuse wrapper with Linux libraries on Windows.

Looking at the error you have from the installer it already looks like you have the driver installed from one of the installation you did.
You can use the mirror of memfs sample for the zip or install directory to test the driver and also look at how they work. Would be a good start to base your work for a ceph filesystem. They are located in another folder near the fuse mirror you tried to start.

**Comment by yule-sun** [comment]
Well, it looks like I need more attempts to use it better, thank you for your reply.

**Comment by Liryna** [comment]
Let me know if you need more info for the installation and will reopen the issue.
