### ISSUE TITLE
 Paid help: dokany develops a file system for physical disks, implemented in python

### ISSUE THREAD

**Issue by pykernel** [dokan-dev/dokany#943]
My project requirements are as follows:
There is a physical disk, which is divided into a quarantine area. This quarantine area can only be accessed through a designated interface, and the quarantine area is not visible in the operating system disk manager. Currently, only read and write interfaces are provided in the quarantine area.
I need to implement a file system to operate this isolation area so that it can create files and directories.
I plan to use python to develop this project. If you can ask for help, you can contact me.

**Comment by Liryna** [comment]
Hi @pykernel 

Github is only used for our project issues unfortunately. You can use the Google group to share you need.
The link is in the readme. Good luck on your project!
