### ISSUE TITLE
Executable cannot be run with elevated privileges on virtual drive

### ISSUE THREAD

**Issue by leochou0729** [dokan-dev/dokany#947]
# Environment
 * Windows version:  Windows 10 1909
 * Processor architecture:  x64
 * Dokany version: 1.4.0.1000
 * Library type (Dokany/FUSE): 

# Description
  I've tested many exe files with a manifest requiring admin privileges. They all cannot be run on an encfs drive with this error message.

> The specified path does not exist. Check the path and then try again.

  I need my drive to be a local one, so I use the -m option to mount it. Without this option, the drive would be removable by default and elevated exe can be run without any problem. I also tried mirror.exe, which works perfectly either with /m option or /o option. I have no idea what's wrong with the mount manager in this situation? Is there any way to mount fuse drives as local ones just like mirror.exe does? Thanks!

# Log
This is the Procmon log, which captures the launch procedure of the executable. 
[Log](https://www.dropbox.com/s/1w62dd22ddg3aug/Logfile.PML?dl=0)

**Comment by Liryna** [comment]
@leochou0729 Hi,

I am not sure to follow. I agree there is no way to mount as simple local drove without mount manager for now and I will make a change for it soon. But is it working with -m (mount manager) and not as removable drive ?
It is know that some win32 API use the mount manager information to get the device path. So without it, they will just fail with the message you gave.

**Comment by leochou0729** [comment]
Hi,
These are my testing results.

1. mirror.exe /r C:\Users\leo\Desktop\test /l Z  //mounted as local drive be default, works
2. mirror.exe /r /m C:\Users\leo\Desktop\test /l Z  //mounted as removable drive, works
3. mirror.exe /r /o C:\Users\leo\Desktop\test /l Z  //mounted as local drive using mount manager, works
4. encfs4win.exe C:\Users\leo\Desktop\test Z: //mounted as removable drive by default, works
5. encfs4win.exe C:\Users\leo\Desktop\test Z: -- -m  //mounted as local drive using mount manager, doesn't work

I have no idea why No. 3 works but No.5 doesn't. I also cannot find a way to mount encfs drives as local ones, just like No. 1. Does mirror.exe use mount manager by default if no option is provided? Thanks!

**Comment by Liryna** [comment]
@leochou0729 No mirror does not use mount manager by default.
Does both process were started we admin rights?

**Comment by leochou0729** [comment]
Hi @Liryna ,
Both processes are launched without admin rights.

**Comment by Liryna** [comment]
@leochou0729 Starting an app that requires admin rights to run in a dokan virtual drive need the mirror or the fuse to run also with admin rights.

**Comment by leochou0729** [comment]
@Liryna The mirror.exe is not started with admin rights, but it works perfectly.

**Comment by Liryna** [comment]
https://github.com/dokan-dev/dokany/commit/feeacb527f4a0fe10b1a58cf8e267995751f13c2 now mount local drive by default and has an option for removable drive.

The Procmon logs you provided are missing the filesystem activity looks like.

Otherwise, it is possible that the issue is that fuse do not support GetFileSecurity like the mirror and that is needed by Windows. The current behavior is that the library will return a default set of permission which will not work here.

**Comment by leochou0729** [comment]
Hi @Liryna,
After testing, I find this problem is totally unrelated to admin privileges, mount manager or unimplemented GetFileSecurity/SetFileSecurity functions.
When I use the "-o -fsname" option to give the fuse drive correct file system info, the executables in it can be started successfully with admin rights. 
I just wonder if there is any fuse callback funtion that can return the fs info, or the only way to set this info is using command line parameters? Is it possible to add GetFileSecurity/SetFileSecurity callbacks to fuse interface just like other windows specific callbacks? Thanks!

FYI, this is the original Procmon log with complete info. 
[Log](https://www.dropbox.com/s/1w62dd22ddg3aug/Logfile.PML?dl=0)

**Comment by Liryna** [comment]
Indeed! Glad you found the reason. I agree this default filesystem name should have never been used.
Changed it with NTFS as default https://github.com/dokan-dev/dokany/commit/153dcc842a12f304e4c679d8d4b5d395d932e429 which should solves the issue.

Can this be closed ?

**Comment by leochou0729** [comment]
Sure. Thanks! @Liryna
