### ISSUE TITLE
Failed to install on Windows 7

### ISSUE THREAD

**Issue by leochou0729** [dokan-dev/dokany#948]
# Environment
 * Windows version: Windows 7 Ultimate SP1
 * Processor architecture: x86
 * Dokany version: 1.4.0.1000
 * Library type (Dokany/FUSE): 

# Description
  DokanSetup-noVC.exe failed with the following error messsages and log file.
  
![DokanSetup-noVC1](https://user-images.githubusercontent.com/13413417/100188755-d47a1c80-2f25-11eb-8dc7-74bb7bcaf1b4.PNG)
![DokanSetup-noVC2](https://user-images.githubusercontent.com/13413417/100188764-dba12a80-2f25-11eb-98c6-25964bfe907f.PNG)
[DokanSetup-noVC.log](https://github.com/dokan-dev/dokany/files/5594673/DokanSetup-noVC.log)

DokanSetup.exe failed with the following error message and log file.
![DokanSetup](https://user-images.githubusercontent.com/13413417/100188813-fd021680-2f25-11eb-8f9c-dae925062dcb.PNG)
[DokanSetup.log](https://github.com/dokan-dev/dokany/files/5594675/DokanSetup.log)

DokanSetup_redist.exe can be run successfully.

Besides this, I have two more questions.
![installer](https://user-images.githubusercontent.com/13413417/100189127-9fba9500-2f26-11eb-9ad6-8daa86077174.png)

1. Why is intaller without VC much bigger than installer with VC?
2. What's the differences between DokanSetup_redist.exe and DokanSetup.exe? They both seem to have the VC runtime, but the redist one is about 6 times bigger. If I need to package Dokan in my app installer and install it automatically, which one should I take?
Thanks!

**Comment by Liryna** [comment]
The log file at `C:\Users\ADMINI~1\AppData\Local\Temp\Dokan_Library_1.4.0.1000_Bundle_20201125134809_000_Dokan_x86.msi.log` is needed here. (The path is in the log you provided)

noVC install is built with static dependency to Visual Studio redistributable which make the binaries bigger.
See https://github.com/dokan-dev/dokany/issues/660

**Comment by leochou0729** [comment]
Hi @Liryna 
This is the required log file.
[Dokan_Library_1.4.0.1000_Bundle_20201125134809_000_Dokan_x86.msi.log](https://github.com/dokan-dev/dokany/files/5610324/Dokan_Library_1.4.0.1000_Bundle_20201125134809_000_Dokan_x86.msi.log)

**Comment by Liryna** [comment]
Thanks for the logs!

Indeed this dependency is no longer needed since we static link vcredist.
Fixed with https://github.com/dokan-dev/dokany/compare/5a43c6c6f23d...9c3fada98aec
