### ISSUE TITLE
Cannot link FUSE sample fusexmp

### ISSUE THREAD

**Issue by aryajur** [dokan-dev/dokany#954]
# Environment
 * Windows version: Windows 10 Home 64 bit
 * Processor architecture: Intel Core i7-8650
 * Dokany version: 1.4.0.1
 * Library type (Dokany/FUSE): FUSE
 
# Check List
  - [X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [X] I can always reproduce the issue with the provided description below.
  - [X] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [Could not compile Dokany ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
I am trying to compile the fusexmp.c sample file using mingw (installed using [MSYS2](https://www.msys2.org/)). Here are the steps I did:
1. Installed Dokany using the file [Dokan_x64.msi](https://github.com/dokan-dev/dokany/releases/download/v1.4.0.1000/Dokan_x64.msi) in the release
2. Created a local directory tree like:
inc -> contains all files from C:\Program Files\Dokan\DokanLibrary-1.4.0\include\fuse
lib -> contains dokanfuse1.dll copied from C:\Program Files\Dokan\DokanLibrary-1.4.0
src -> contains fusexmp.c copied from C:\Program Files\Dokan\DokanLibrary-1.4.0\sample\fuse_mirror
3. I tried compiling it using the command:
> gcc -o fusexmp -D_FILE_OFFSET_BITS=64 -I../inc -L../lib -l dokanfuse1 fusexmp.c

I get the following error:
../lib/dokanfuse1.dll: file not recognized: file format not recognized

# Logs

**Comment by Liryna** [comment]
@aryajur Hey,

Have you tried to build using using the cmake ? https://www.github.com/dokan-dev/dokany/tree/master/dokan_fuse%2Fbuild.ps1

**Comment by aryajur** [comment]
@Liryna thank you for the quick response. The problem was that I was using the 64 bit dokanfuse1.dll with a 32 bit gcc.
the fusexmp.c file however has a lot of functions that seem non compatible with mingw like mknod, mkfifo, lstat, etc.

**Comment by Liryna** [comment]
@aryajur fusexmp.c is just a sample from FUSE official. It probably just not compatible with mingw.

**Comment by aryajur** [comment]
@Liryna ok got it. I did finally remove the incompatibilities and compiled it. I then tried running it like:
fusexmp.exe /r C:\Users /l m
It says:
fuse: invalid argument `C:\Users' am I using it right?
Could not yet try the precompiled version that came with the installation since it needs a bunch of cygwin dll files.

**Comment by Liryna** [comment]
The argument format you are using is for the mirror sample. Here it is the fuse argument type you need to use.

**Comment by aryajur** [comment]
Thanks. I think I will close this issue now since the linking problem is figured out.
