### ISSUE TITLE
Problems using network share

### ISSUE THREAD

**Issue by katcherw** [dokan-dev/dokany#963]
# Environment
 * Windows version: Windows Server 2016 (server), Windows 10 (remote client)
 * Processor architecture: x64
 * Dokany version: 1.4.0.1000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [ ] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

Our Dokany-based virtual file system is working well so far using a local mount point. However, we then share the mounted folder as a network drive, and then we are seeing some problems. The most major problem is that in the Windows Explorer, we create a text file and then copy it to the same directory using ctrl-c/ctrl-v, but the copy of the text file appears as a directory. This is intermittent. In the callback code, we are not returning the original file as a directory and never setting the DokanyFileInfo->IsDirectory flag and never setting a directory attribute. Locally, this works fine, but remotely there is some directory attribute being set somewhere. Here is a ProcessMonitor dump and you can see that QueryNetworkOpenInformation shows a D flag in FileAttributes. Locally, only the A flag is set.

![image](https://user-images.githubusercontent.com/9508150/105559093-44b2dd80-5cde-11eb-9359-a8eb03b078ca.png)

To debug this, we were attempting to compare with memfs. Unfortunately, we are running into another bug there. We can't always create a new directory. When using the File Explorer to create a new folder, it looks like it gets created okay (I see it in the explorer window), but when trying to access it, I get this message:

![image](https://user-images.githubusercontent.com/9508150/105559503-5b0d6900-5cdf-11eb-8de0-7d5e9358584c.png)

You can see in Process Monitor that it looks like the directory was created successfully, but then later it seems to not be able to recognize it anymore:

![image](https://user-images.githubusercontent.com/9508150/105560339-7b3e2780-5ce1-11eb-9132-a16d2315e1fe.png)

Remember, all this is working perfectly locally. This is also working perfectly, even remotely, with mirror. It's only memfs that has a problem, and our application is modeled off of memfs.

Have you ever seen these types of problems before? I can try to capture logs if it would be useful. I'm not sure how to debug this, because I don't see any problems in the log files, and not sure what would affect only a network share and not a local share. Any advice you can give would be much appreciated.

# Logs
Please attach in separate files: mirror [output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#mirrorfs), library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#get-logs).
In case of BSOD, please attach minidump or dump [analyze output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#crash-report-bsod).

**Comment by Liryna** [comment]
Hi @katcherw ,

Thanks for the report. The reason of the issue was the same as #909 
I just made a fix https://github.com/dokan-dev/dokany/commit/7c1981577a521f956b3167348f2ee93421578934 that correct the behavior on my side. Let me know if you will still face the issue.

**Comment by katcherw** [comment]
Unfortunately this didn't solve the issue. I don't see any evidence of an extra slash anywhere, rather the problem is a file that was just created is somehow appearing with a directory attribute set even though the file system isn't setting one.

**Comment by Liryna** [comment]
If you rebuild memfs with the fix, are you now able to create a folder and acces it ?
Can you now reproduce the same issue you are facing with memfs ?

**Comment by katcherw** [comment]
Even with the latest code that contains the fix, I still see the problem. All I need to do is start memfs like the following:

`memfs /l c:\mnt`

Then I share c:\mnt and give everybody read/write permission. On the remote computer I use File Explorer to go into the shared directory and then I create a new folder. The folder creates correctly. But when I double click to go into the folder, I get this error:

![image](https://user-images.githubusercontent.com/9508150/105897244-ee97b000-5fe5-11eb-99c9-3de4a4026aa6.png)

After hitting okay, I can go into the directory and create files in there without problems.

I am also uploading the logs. I added a few logs to dokany.lib to try to debug.

[dokany.log](https://github.com/dokan-dev/dokany/files/5875733/dokany.log)

Bill

**Comment by Liryna** [comment]
@katcherw Thanks

In the log that you sent, there are sequential Opens that fails:
\New folder\New folder
\New folder
\bill
\bill\New folder

To finally create  \New folder

I have never seen such behavior and do not understand why there is a double New folder, then a bill to finally create a New folder.
Could you provide a procmon of this exact moment ?

**Comment by katcherw** [comment]
It looks like the explorer client keeps looking for those old folders from old experiments, that's why you are seeing the additional opens. This time, I created a new mount point so the client doesn't ask for old data.

I am uploading a new log file, the procmon dump, and a wireshark capture:

[dokany.log](https://github.com/dokan-dev/dokany/files/5876842/dokany.log)
[dokany1.pml.zip](https://github.com/dokan-dev/dokany/files/5876848/dokany1.pml.zip)
[dokany1.pcapng.zip](https://github.com/dokan-dev/dokany/files/5876847/dokany1.pcapng.zip)

I see in the procmon that it creates New Folder, queries it, but then suddenly can't open it anymore:

![image](https://user-images.githubusercontent.com/9508150/105922828-5d3a3500-6009-11eb-9ce7-2e5828bcc3ab.png)

I don't see these creates in the Wireshark, so I'm confused where these calls are going. I tried mirror again, and it works perfectly fine. 

I tried to use a local unc path, but I can't get it to work yet. I ran: `memfs.exe /d /l c:\mnt /n /u \myfs\myfs1` but it keeps saying Windows can't access that location.

Bill

**Comment by katcherw** [comment]
I'm still not sure what's causing the problem in memfs. But we figured out the original problem in our own file system. I'll explain it here in case somebody else runs into the same thing.

To summarize, the symptom was that attributes of a file after creating a regular file was being reported as a directory. This was only happening on a remote client after sharing the mounted folder. Additionally, the problem went away when disabling the SMB client cache. Another symptom was that the security tab wouldn't appear, also only on remote clients.

The cause of the problem turned out to be that we weren't filling in the fileIndex correctly in GetFileInformation. Apparently, the SMB client cache relies on a unique id to look up the proper attribute. The local file system must be more forgiving if this value is not unique. Once we ensured there was a unique number, everything started working again.

**Comment by Liryna** [comment]
Thank you for your investigation and sharing the results!

For the file index, is that a fix you would be able to make a pull request to fix it in memfs?

**Comment by katcherw** [comment]
It looks like memfs handles this correctly from what I can tell. It uses an incrementing integer for every new file, so that should work.

**Comment by Liryna** [comment]
I agree. It looks to be correctly set.

Do you think this ticket can be closed or there is still something to investigate?

**Comment by katcherw** [comment]
The ticket can be closed. Thanks for your help.
