### ISSUE TITLE
Dokany spams windows eventlog.

### ISSUE THREAD

**Issue by Wolvverine** [dokan-dev/dokany#966]
# Environment
 * Windows version: 8.1 64-bit
 * Processor architecture: Intel i7
 * Dokany version: 1.4.0.100

Dokany spams windows eventlog: 

Mounting disk  device.

# Description
More here (it is Dokany issue):

https://github.com/cryptomator/cryptomator/issues/963

**Comment by Liryna** [comment]
I am already actif on the thread you linked. Note that this is going to be disabled by default on the next release.
