### ISSUE TITLE
Replace dokan1.sys file in windows 10

### ISSUE THREAD

**Issue by zqlustc** [dokan-dev/dokany#967]
Hi
    I have generated the x64 debug dokan1.sys file. Windows refuse to replace in the system32/driver directory, It reminds that the directory is being accessed, how to deal with it?

# Environment
 * Windows version:  windows 10
 * Processor architecture: x64
 * Dokany version: latest that self-compiling
 * Library type (Dokany/FUSE):

**Comment by Liryna** [comment]
Hi,

You need to remove to stop the previous dokan driver with `dokanctl /r d`, reboot and install with `dokanctl /I d`.

Also see https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#self-sign-build

**Comment by zqlustc** [comment]
> Hi,
> 
> You need to remove to stop the previous dokan driver with `dokanctl /r d`, reboot and install with `dokanctl /I d`.
> 
> Also see https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#self-sign-build

Hi,
I have just try the method. The file(system32/driver/dokan1.sys) still exists after executing `dokanctl /r d` after rebooting. And executing `dokanctl /I d` do not replace it. No error or warning occurs overall the operation.

**Comment by Liryna** [comment]
Without logs I cannot help much here. The command should do the work.

**Comment by zqlustc** [comment]
> Without logs I cannot help much here. The command should do the work.
Hi,
I will give the log later. 
Maybe the best method is to build DokanSetupDbg.exe. Now it generated the x64 debug dokan(include dokan1.dll, dokanfuse1.dll and dokan1.sys). After build the all solutions, it do not gererated the DokanSetupDbg.exe. How could I use them(dokan1.dll, dokanfuse1.dll and dokan1.sys) to build the DokanSetupDbg.exe?
Thanks.

**Comment by zqlustc** [comment]
> Without logs I cannot help much here. The command should do the work.

Without logs I cannot help much here. The command should do the work.
Hi,
I will give the log later.
Maybe the best method is to build DokanSetupDbg.exe. Now it generated the x64 debug dokan(include dokan1.dll, dokanfuse1.dll and dokan1.sys). After build the all solutions, it do not gererated the DokanSetupDbg.exe. How could I use them(dokan1.dll, dokanfuse1.dll and dokan1.sys) to build the DokanSetupDbg.exe?
Thanks.

**Comment by Liryna** [comment]
Please, take the time to look at all the script s and the wiki of the repository. All your current and previous questions can easily be answered there.
