### ISSUE TITLE
ACLs

### ISSUE THREAD

**Issue by katcherw** [dokan-dev/dokany#968]
# Environment
 * Windows version: Windows Server 2016
 * Processor architecture: x64
 * Dokany version: latest from git
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

I am trying to get ACLs to work on my file system. I can add and modify ACLs to the security tab of the properties dialog for a file, and my file system stores and reads these correctly. However, they don't seem to be honored. If I create an ACE for a user with deny privileges, that user still has access to the file. 

So my question is, what do I need to do to get these working? Does the OS/Dokany do any permission checking? Or do I need to do it manually? If I need to do it manually, are there any ACLs that can help? 

I looked to memfs for an example, but ACLs don't seem to be working there at all. First of all, I don't see the security tab at all. In the code, I added FILE_PERSISTENT_ACLS to the filesystem flags in getVolumeInformation and recompiled, and now I see the security tab. But when I try to add a user to the ACL, I get the following error:

![image](https://user-images.githubusercontent.com/9508150/106944951-3957ad00-66f5-11eb-9084-e39db9f36e04.png)

I do see code in memfs to handle security descriptors. So is this a bug or is ACLs not intended to be supported? 

Bill

# Logs
Please attach in separate files: mirror [output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#mirrorfs), library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#get-logs).
In case of BSOD, please attach minidump or dump [analyze output](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan#crash-report-bsod).
[dokany.log](https://github.com/dokan-dev/dokany/files/5928097/dokany.log)

**Comment by Liryna** [comment]
@katcherw ACL are supported by Dokan. The tricky issue is that Windows userland API do not make it very easy to handle them.
Do you have the get and set security operations enabled on your implementation?
It is this functions that are used when the security tab is used. You will need to store the value set and properly return the modification.
As you can see in memfs comments...it is a little tricky.

**Comment by katcherw** [comment]
Yes, get and set security operations are enabled and I can successfully persistently store and retrieve ACLs. The only part that is not working is actually getting the ACLs enforced. Is it only createFile that needs to do this, or every operation? Are there any examples that I can follow? And why is memfs not working?

Bill

**Comment by Liryna** [comment]
Createfile is the only entry point where the security need to be checked to ensure what will follow is allowed.
I haven't found a userland API that directly check with the one saved.
Probably what can be done (there is surely better...) is to convert the security informations to security string and compare manually the content.
Sorry There is no sample unfortunately.

**Comment by katcherw** [comment]
Okay, thanks for your response!

**Comment by katcherw** [comment]
It looks like mirror also does not honor the ACLs.

I think I can use AccessCheck to do the checking, but I need a security token representing the user. I can get the current logged in user's token, but this won't work with a remote connection. Does Dokany have any mechanism to pass the security token from a remote user?

**Comment by Liryna** [comment]
@katcherw We have unit test for acls that pass on the mirror. It can honor them because it replicate the createfile on the underlying volume that will return the access denied.

Also I do not understand why the user token will not work remotely? Your using have to login with the system and get a session to access the volume.

**Comment by katcherw** [comment]
When a remote user logs in and accesses a share directly, then there is no problem because we can get the access token from the logged in user. But another scenario is that the mounted directory is shared as a network drive. In this case, multiple clients can each be accessing the share drive simultaneously. Using the system APIs to get the access token for the logged in user will only return the user who is currently logged in, not necessarily who initiated an SMB call. 

Fortunately, we found a Dokany routine, DokanOpenRequestorToken, that appears to return the client access token for the user that actually initiated the createFile call. So far this is working well, but we are still testing. It looks like mirror is only calling this when the impersonation option is selected, so that explains why mirror wasn't honoring the ACLs for our test cases. And memfs doesn't look like it is calling this at all.

One other comment: it appears that calling DokanOpenRequestorToken is issuing an IOCTL to the driver. Since file systems should normally be calling this during every createFile, it would probably be more efficient just to pass the access token to createFile always. Perhaps you can consider this for future releases.

**Comment by Liryna** [comment]
@katcherw I will keep it in mind for the v2. Thank you for sharing your feedback.

**Comment by kiran-m-kannur** [comment]
Hi @Liryna , has this been fixed yet ?

**Comment by Liryna** [comment]
> Hi @Liryna , has this been fixed yet ?

Which part of this issue are you referring to exactly? The ACL worked for the user. The possible optimization to have the ACL sent as part of the create payload to avoid having to do a call wasn't implemented.

**Comment by kiran-m-kannur** [comment]
Sorry my bad, I'll make my issue clear. 
So my case is this:
I’m running into a weird permissions issue and could use some help.

**Setup:**
I have set up a virtual mount using example memfs as an admin.
Inside this mount, there’s a folder called "test" with a document in it.
I've shared the "test" folder over the network with another Windows user ("test-user").

**Permissions Configuration:**
I've disabled both read and write permissions for "test-user" on the "test" folder as admin.

Here is my problem I'm facing : 
Even though I disabled the permissions, "test-user" can still open and modify the document in the "test" folder.

I’ve Tried:

1. Checking the folder’s Security tab permissions.
2. Looked at the network share permissions.
3. Made sure no inherited permissions were allowing access.
4. Confirmed "test-user" isn’t in any groups with read/write permissions.

**Comment by LTRData** [comment]
You need to check requestor token for requesting user when handling `CreateFile` and check file ACLs for permissions. Then, either succeed or return access denied depending on whether the requestor user should have access to the file or not.

**Comment by Liryna** [comment]
https://github.com/dokan-dev/dokany/blob/master/samples/dokan_memfs/memfs_operations.cpp#L100

**Comment by kiran-m-kannur** [comment]
Sorry for the late reply, I stopped working on this project in-between.
I have implemented access checks within the CreateFile function, but I am encountering unexpected issues such as files being created multiple times during a single CreateFile call. My question is: Should access checks be limited to the CreateFile function, or should they also be implemented in subsequent functions invoked after CreateFile? If anyone has a sample implementation demonstrating the correct approach, that would be highly appreciated.

**Comment by LTRData** [comment]
No, access checks should only be done in `CreateFile` function. You need to be prepared that `CreateFile` can be called several times, for example an application could try to open a file for writing, get that request denied from the file system and then retry opening for read only. If that also fails, it can retry for read attributes only and so on.

There are also other scenarios where a file can be opened several times, for example to quickly get attributes, file size etc first to make a directory list and then afterwards open the file again for reading data to find out about the contents of the file.
