### ISSUE TITLE
Microsoft Photos app in Windows 10 is unable to display pictures

### ISSUE THREAD

**Issue by ivorytir** [dokan-dev/dokany#97]
Hi,
The Microsoft Photos (Microsoft.Photos.exe), default photo viewing app in Windows 10, is not able to display pictures from a dokany-mapped drive. It shows error **IMG_xyz.jpg We can't open this file**

The issue is easily reproducible using the mirror example (tested on commit c39e712). It happens in local or removable drive mode (/r), network drive mode (/n) seems to be fine. I can provide dokany debug output if needed, but have not spotted any errors in there though.

Cheers, Ivo

**Comment by Liryna** [comment]
Hello,

This has already been reported in a closed ticket.
https://github.com/dokan-dev/dokany/issues/26#issuecomment-133009331
The possible fix has been added to the TODO of dokan (see Add Oplock Semantics)
https://github.com/dokan-dev/dokany/issues/45

If you can provide patch to add the implementation it would be really great !

**Comment by Liryna** [comment]
Fixed with https://github.com/dokan-dev/dokany/commit/731a6279dc8e67460a6169e56886475225f9d8b8

**Comment by ivorytir** [comment]
Thanks Liryna, the fix works great!

**Comment by js69** [comment]
I think we need to reopen the issue. With the current repo (compiled locally) I have the issue that the preview in Explorer shows pictures only partially and Windows 10 Photo app doesn't show some pictures completely on C-mirror sample drives. Screenshot shows the icon thumbnall and preview in Explorer with picture obviously not loaded completely.

![explorerpreviewinmirror](https://cloud.githubusercontent.com/assets/16227213/14353815/198041ce-fcdb-11e5-9295-ae455614bfd0.png)

Tested in a Win 10 (10586) VM.The issue occurs not always, nondeterministically, try with 10 large pictures in a folder for reproduction.

**Comment by Liryna** [comment]
Hi @js69 ,

I think your issue is more related to https://github.com/dokan-dev/dokany/issues/154
Before the fix of this issue, you was absolutly not able to open a picture at all.

**Comment by js69** [comment]
Yeah, you are right. Sorry for duplicate.
