### ISSUE TITLE
"dokan1" spamming event viewer (no idea what dokany is lol) 

### ISSUE THREAD

**Issue by mars1147** [dokan-dev/dokany#971]
* Windows version: 10 20H2
 * Processor architecture: ryzen 5800x 
 * Dokany version: I have no idea, because I don't think I willingly installed it, and don't see it on my PC...😅
 * Library type (Dokany/FUSE): ?
 
Noticed "dokan1" spamming, constantly, in event viewer. Description says "mounting disk device". I had absolutely no idea what dokany was before googling my issue just now, so I definitely didn't knowingly install it, nor do I see it on my system. I apologize for my ignorance, and would really appreciate any help! Thank you! 

![20210211_000651](https://user-images.githubusercontent.com/78897477/107609040-5879a180-6c03-11eb-8390-5366a234f6a2.png)

![dokan](https://user-images.githubusercontent.com/78897477/107609074-734c1600-6c03-11eb-8c6a-d787e647a7f1.png)

**Comment by Liryna** [comment]
@mars1147 Is it spamming like constantly? Or there is just a couple of entries in one time ?
Do you know since when this is happening? Like installation of a new app / driver ?

**Comment by infeo** [comment]
Is by any chance the program `wincdemu` installed?

The Cryptomator project uses Dokany, and on their issue tracker a similar issue was opened some time ago: https://github.com/cryptomator/cryptomator/issues/963

**Comment by mars1147** [comment]
> @mars1147 Is it spamming like constantly? Or there is just a couple of entries in one time ?
> Do you know since when this is happening? Like installation of a new app / driver ?

It's constantly. Not sure if you can see my attached photos, but it shows multiple entries per minute. I'm not sure when it started happening, unfortunately. I don't look in event viewer often, so I just noticed it the other day. Is it possible to search for the first instance in the logs?

**Comment by mars1147** [comment]
> Is by any chance the program `wincdemu` installed?
> 
> The Cryptomator project uses Dokany, and on their issue tracker a similar issue was opened some time ago: [cryptomator/cryptomator#963](https://github.com/cryptomator/cryptomator/issues/963)

Yeah, I saw the cryptomator thing, but I don't have that, either. Pretty sure I also don't have wincdemu, but I will double check once I'm able to get on my PC!

**Comment by gcalzo** [comment]
I do have cryptomator and I do have these events... hoping to have them fixed soon...

**Comment by Liryna** [comment]
I simply disabled the log to remove the noise in the next release.

**Comment by Liryna** [comment]
Closing this as next release will have the fix.
