### ISSUE TITLE
Refuse to delete file

### ISSUE THREAD

**Issue by hefengliang** [dokan-dev/dokany#983]
I tried to refuse to delete the file in unlink. No matter what error code was returned, explorer still deleted the file view.
I checked isson: https://github.com/dokan-dev/dokany/pull/970, your reply says that you can refuse to delete through "createfile" or "set delete",
But my question is that when "createfile" was called, I didn't know that this call was made for the purpose of deleting. I don't understand what "set delete" means?
I expect there is a way to confirm the deletion before unlinking and reject it?

# Environment
 * Windows version: win10
 * Processor architecture: x64
 * Dokany version: 1.4.1
 * Library type (Dokany/FUSE): FUSE
 
# Check List
  - [*] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [*] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [*] I can always reproduce the issue with the provided description below.
  - [*] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ *] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

**Comment by Liryna** [comment]
Hi @hefengliang ,

I believe you are talking about the delete workflow when the file is open with `FILE_DELETE_ON_CLOSE` flag so signal that the file needs to be deleted on cleanup (unlink).
To refuse this delete, you would need to fail the open request. See https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/delete-on-close

This is a `Windows` logic that has not equivalent on Unix from what I know to reproduce this behavior.

**Comment by hefengliang** [comment]
Thanks for the hint, I will try.

**Comment by Liryna** [comment]
I will close the issue in the meantime. Do not hesitate to reopen if there is anything to add.
