### ISSUE TITLE
Question about malware analisys

### ISSUE THREAD

**Issue by GCHE1** [dokan-dev/dokany#986]
I'm sorry if that is not a proper way of asking questions.

Not really an issue but question. I want to analyse memory of running malware. I already know I can set up read only disk, but that malware is stripping access to it's memory probably by using kernel techniques so whenever I open handle to it's executable I have no permissions to read or write to memory.

Can I somehow set up dokany to prevent this technique?

**Comment by Liryna** [comment]
Hi @GCHE1 ,

Unfortunately, I do not see how Dokan as a FileSystem would be to help you to analyse the malware memory. Good luck!
