### ISSUE TITLE
CreateFile cleanup

### ISSUE THREAD

**Issue by billziss-gh** [dokan-dev/dokany#99]
There are a number of issues with the current CreateFile implementation:

* The eventInfo variable need not be a malloc allocation. This seems superfluous (unless I am missing something)

* NTSTATUS handling in CreateFile is rather complicated. I believe this can be simplified greatly by using code similar to the following:

        switch (disposition) {
        case FILE_CREATE:
            eventInfo.Operation.Create.Information = FILE_CREATED;
            break;
        case FILE_OPEN_IF:
        case FILE_OPEN:
            eventInfo.Operation.Create.Information = FILE_OPENED;
            break;
        case FILE_OVERWRITE:
        case FILE_OVERWRITE_IF:
            eventInfo.Operation.Create.Information = FILE_OVERWRITTEN;
            break;
        case FILE_SUPERSEDE:
            eventInfo.Operation.Create.Information = FILE_SUPERSEDED;
            break;
        default:
            break;
        }

* STATUS_OBJECT_NAME_COLLISION should not be handled specially. I note that ERROR_ALREADY_EXISTS is added by the Win32 CreateFileW using a test along the lines of:

        if (disposition == CREATE_ALWAYS && iosb.Information == FILE_OVERWRITTEN) ||
            disposition == OPEN_ALWAYS && iosb.Information == FILE_OPENED)) {
            SetLastError(ERROR_ALREADY_EXISTS);
        }

* SL_OPEN_TARGET_DIRECTORY is not handled properly. For one thing, we should return FILE_EXISTS, FILE_DOES_NOT_EXIST based on whether the original pointed file exists (not the target directory). In my tests with MoveFileExW everything worked when setting the information code to FILE_OPENED though. [The information codes FILE_EXISTS and FILE_DOES_NOT_EXIST are not used except in the case of SL_OPEN_TARGET_DIRECTORY. Confirmed on Fastfat and NTFS.]

* The SL_CASE_SENSITIVE, SL_FORCE_ACCESS_CHECK, SL_OPEN_PAGING_FILE are not currently handled at all.

**Comment by Liryna** [comment]
@billziss-gh , I will begin to review the issue since createfile has been changed.

**Comment by Liryna** [comment]
* EventInfo has been changed Thank you :+1:  https://github.com/dokan-dev/dokany/commit/54f859232a2819675f5e698b6f96338fc5c3864a

* I agree that this part of the code should be cleaned: https://github.com/dokan-dev/dokany/blob/master/dokan/create.c#L180
But the code that you proposed does not handle all the case.
FILE_OPEN_IF = FILE_OPENED & FILE_OVERWRITE/FILE_OVERWRITE_IF = FILE_OVERWRITTEN always  is wrong. it is important for the system to know if you have opened or created the file.

* Using `SetLastError(ERROR_ALREADY_EXISTS);` seems to be a good idea that I will test !

* I agree that SL_OPEN_TARGET_DIRECTORY is not handled properly but I do not know how :cry: 
* I have added it to the issue TODO

**Comment by Liryna** [comment]
@billziss-gh , feel free to reopen the issue if you want.
I have created different tickets with your feedback.
