### ISSUE TITLE
Mounted(): When is it executed?

### ISSUE THREAD

**Issue by infeo** [dokan-dev/dokany#992]
# Environment
 * Windows version: 10
 * Processor architecture: x64
 * Dokany version: 1.4.1.1000
 * Library type (Dokany/FUSE): Dokany 
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [-] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [-] I can always reproduce the issue with the provided description below.
  - [-] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [-] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
This is a question about the mounting process of Dokany.

At what point in time is the `mounted()` method called?

I'm working on a project which uses Dokany. Recently we made the internal change that a mount operation is only considered successful, if the [`Mounted()`](https://dokan-dev.github.io/dokany-doc/html/struct_d_o_k_a_n___o_p_e_r_a_t_i_o_n_s.html#a7de1d1fe723fc4a0ec19d0953277f7e7) method is executed within an timely manner. This means we wait 10s and if up to this point it is not executed, we consider it a failure. Due to this change several users [reported](https://github.com/cryptomator/cryptomator/issues/1627), that the mounting operation timed out. So we wonder if 10s is still too low or maybe there are pitfalls with the `Mounted()` method.

**Comment by Liryna** [comment]
@infeo Mounted is called when the mount request sent to the driver is processed and returns. At this moment the drive will be accessible.
https://github.com/dokan-dev/dokany/blob/master/dokan/dokan.c#L350

This step should be fast unless a filter driver (antivirus) delay the request. Have you been able to know what the users have in common ? Does the mount manager option is used ?

**Comment by infeo** [comment]
Thanks for answering it 🙂 

The mount manager is not used. I will ask around if and what AV software is used.

>FYI the code at head has some changes on how the communication is working. It have some chances to improve conflicts with filter drivers.
Uh, that is cool! Do you have any ETA on the release already?

**Comment by Liryna** [comment]
@infeo Hopefully next week!

**Comment by Liryna** [comment]
@infeo https://github.com/dokan-dev/dokany/releases/tag/v1.5.0.1000 here it is
