### ISSUE TITLE
Do not use the current file shared mode?

### ISSUE THREAD

**Issue by zqlustc** [dokan-dev/dokany#994]
For help!!!
  The file have not been inserted in the file list of filelock, why do we have to check `file.get() != p`, or when this  happen? @Liryna, thanks.

https://github.com/dokan-dev/dokany/blob/a7fd5801442921cbf9fa6d869a705dae4c31a9dd/dokan_fuse/src/fusemain.cpp#L1044

**Comment by Liryna** [comment]
@zqlustc let me know if I can be of any help.
