### ISSUE TITLE
'mirror.exe' is not recognized 

### ISSUE THREAD

**Issue by ajdezigns** [dokan-dev/dokany#995]
# Environment
 * Windows version: 10
 * Processor architecture: Xeon
 * Dokany version: 1.5.0
 * Library type (Dokany/FUSE): 
 
# Description

C:\Users\Plex>mirror.exe /u \Drobo5N\public /l z
'mirror.exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Liryna** [comment]
The mirror is located in the install folder. Please execute from there or directly use the full path when calling it 

C:\Program Files\Dokan\Dokan Library-1.5.0\sample\mirror\mirror.exe

**Comment by ajdezigns** [comment]
Only issue is I have no such sample folder that was created during installation. 

![image](https://user-images.githubusercontent.com/4680112/120056710-0fabf400-c00c-11eb-9654-aa858808a4fa.png)

**Comment by Liryna** [comment]
@ajdezigns I believe during the installation you have uncheck in the option the development tools. That's why it is not there.
