### ISSUE TITLE
Concurrent create causes file creation failure

### ISSUE THREAD

**Issue by zqlustc** [dokan-dev/dokany#997]
Create A was intercepted here, concurrent create causes file creation failure.
```
           process 1                                                             process 2
-> DokanDispatchCreate                    
                                                                     -> DokanDispatchCreate (FILE_CREATE)
......
                                                                     -> return STATUS_OBJECT_NAME_COLLISION
......
-> return FILE_DOES_NOT_EXIST
```
https://github.com/dokan-dev/dokany/blob/685aab7699134dd5d046f5af6e2a965e0e7fa771/sys/create.c#L691-L693

It will cause probabilistic file creation failure, we can avoid the problem? @Liryna

**Comment by Liryna** [comment]
I do not really understand what is the problem here. Filesystem are multi thread and such things can happen if the handle is closed before or after another one.
Please use the template for the issues.
